### ISSUE TITLE
Getting Cannot find project 'cli' error when following the tutorial

### ISSUE THREAD

**Issue by yuchien302** [nrwl/nx#10037]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/02-create-cli

### Additional context or description
I followed the tutorial, and it keep saying Cannot find project 'cli'
<img width="278" alt="image" src="https://user-images.githubusercontent.com/1877281/165652663-a98f851d-3ccd-45cb-8eb6-671e421a2132.png">

Turns out I have to run `nx reset` to get it works. Wasted an hour figuring this out.

**Comment by AgentEnder** [comment]
This is a bug, and should be fixed by #10031

**Comment by itunbridgedev** [comment]
This tutorial series has been very obnoxious. First, on [step](https://nx.dev/core-tutorial/01-create-blog)) this command fails:
`npx create-nx-workspace@latest`
Error:
 NX   Nx failed to install dependencies
Exit code: 1

After googling, I found this [so article](https://stackoverflow.com/questions/69873618/nx-error-nx-failed-to-install-dependencies) which mentions NX Repo path having spaces in it (did not apply) and a recommendation to use this command instead to install an earlier version:
`npx create-nx-workspace@13.9.3`

After successfully installing this earlier version, I ran into another issue trying to run `npx nx serve blog` - Error: Cannot find project 'blog' which lead me to this [issue](https://github.com/nrwl/nx/issues/11053) which explains the workspace.json file is used to configure project paths (the tutorial mentions nothing about this).

Then on [step 2](https://nx.dev/core-tutorial/02-create-cli) I'm again blocked when trying to run `npx nx serve cli` - Error: Could not find project "cli"

I realize this bug was fixed in 14.0.4, but step 1 forced me to use an earlier version. the suggested `npx nx reset` command doesn't seem to fix the issue.
