### ISSUE TITLE
creating a workspace with angular preset fails to create an angular app

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#10067]
## Current Behavior
`npx create-nx-workspace --preset=angular` doesn't create an angular app

## Expected Behavior
creating an angular workspace has (in the past) created an angular app

## Steps to Reproduce
`npx create-nx-workspace --preset=angular` see the folder structure exists, but dependencies look like:

``` json
 "dependencies": {
    "@nrwl/angular": "14.0.5"
  },
  "devDependencies": {
    "@angular/cli": "~13.3.0",
    "@nrwl/cli": "14.0.5",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "14.0.5",
    "nx": "14.0.5",
    "prettier": "^2.5.1",
    "typescript": "~4.6.2"
  }
}
```

and there is nothing in the `/apps` directory

### Environment
``` bash
Node : 14.18.1
   OS   : win32 x64
   npm  : 6.14.15
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

### Additional Info
The nestjs option results in the same thing (no app)

It's possible this is due to the naming of the workspace, `test-14` results in this problem, and when trying to add an application manually after the initial command, this is the error:

``` bash
> Executing task: npx nx generate @nrwl/angular:application --name=demo-app --style=scss --no-interactive <

SchematicsException [Error]: Selector (test-14-root) is invalid.
    at validateHtmlSelector (D:\IdeaCrew\GitHub\test-14\node_modules\@schematics\angular\utility\validation.js:18:15)
    at D:\IdeaCrew\GitHub\test-14\node_modules\@schematics\angular\component\index.js:115:47
Selector (test-14-root) is invalid.
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', 'npx nx generate @nrwl/angular:application --name=demo-app --style=scss --no-interactive'" terminated with exit code: 1.
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is an interesting one. You're correct with the assumption that the `test-14` name is a problem. The Angular CLI schematics don't like "standalone" numbers in the project names, component selectors, etc. Since the `@nrwl/angular:*` generators rely on those schematics, this restriction applies. If you were to create a `test14` instead, it would succeed.

There was some work done to bypass this restriction to some extent here https://github.com/nrwl/nx/pull/6646, but it didn't cover the scenario of having the `npmScope` with "standalone" numbers.

Also, in hindsight, I don't think that was a complete solution. Completely removing the numbers from the project name, would introduce an issue if folks want to create a couple of apps with similar names but different numbers `test-1` and `test-2`, because both would result in the same name. The error for such a scenario would be confusing because it would state that the project name already exists, even though the dev is passing a different name.

On the other hand, there also seems to be a separate issue where `create-nx-workspace` didn't error even though the application generation failed.
