### ISSUE TITLE
Can't import files from one library into another library (bypassing index.ts)

### ISSUE THREAD

**Issue by gregveres** [nrwl/nx#10082]
## Current Behavior
I have a process on our back end that auto generates interfaces, enums and services that are necessary to call our back end. 
All of these get generated into three directories: interfaces, enums and services. 
I have put these directories into buildable library that is structured like this:
/libs/api/src/{interfaces,enums,services}
In each directory are the appropriate TS files.

In my tsconfig.base.json file, I have added the following path entries:
```
      "@skycourt/api/enums/*": ["libs/api/src/enums/*"],
      "@skycourt/api/interfaces/*": ["libs/api/src/interfaces/*"],
      "@skycourt/api/services/*": ["libs/api/src/services/*"],
```

In the second library, called helpers, I import a couple of the enums and interfaces like this:
```import { ActivityType } from '@skycourt/api/enums/ActivityType';```

VSCode happily recognizes these paths. Lint happily recognizes these paths and I am able to run the jest tests in the second library that uses these paths. 

However, when I try to build the helpers library, I get these errors:
```
Compiling TypeScript files for project "common-helpers"...
libs/common/helpers/src/lib/ActivityIcon.ts:1:30 - error TS2307: Cannot find module '@skycourt/api/enums/ActivityType' or its corresponding type declarations.

1 import { ActivityType } from '@skycourt/api/enums/ActivityType';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I know that Nx understands the dependency betwen helpers and api because when I display the graph, there is an arrow from helpers to api. 

## Expected Behavior
I expected the import to be resolved properly while building.

## Steps to Reproduce
I have created a minimal repo using Nx 13.9.7 that illustrates the issue. 
I am using 13.9.7 because my main project is a Vue app and Nx-plus/vue can't seem to be used with anything newer than 13.9.7.

If you clone this repo: https://github.com/gregveres/nx-import-bug
and then execute ```nx build helpers``` you willl see this error:
```
Compiling TypeScript files for project "helpers"...
libs/helpers/src/lib/helpers.ts:1:30 - error TS2307: Cannot find module '@myorg/api/enums/ActivityType' or its corresponding type declarations.

1 import { ActivityType } from '@myorg/api/enums/ActivityType'
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

when it really should compile. 

### Environment
```
04-30 13:11:32 17> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.17
   
   nx : 13.9.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.7
   @nrwl/eslint-plugin-nx : 13.9.7
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.7
   @nrwl/js : 13.9.7
   @nrwl/linter : 13.9.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.7
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by gregveres** [comment]
I also tried creating barrel file for each of my directories: enums, interfaces and services.
This gave me a library that looked like this:
src
|- lib
|- enums.ts
|- interfaces.ts
|- services.ts
|- index.ts

where index.ts was: 
```
export * from './enums'
export * from './interfaces'
export * from './services'
```

if I changed the import to be:
```
import { SCDayOfWeek } from '@skycourt/api/enums';
```
would produce the same error but this would work:
```
import { SCDayOfWeek } from '@skycourt/api';
```

when I had the following paths defined in my tsconfig.base.json

```
      "@skycourt/api": ["libs/api/src/index.ts"],
      "@skycourt/api/enums": ["libs/api/src/enums.ts"],
      "@skycourt/api/interfaces": ["libs/api/src/interfaces.ts"],
      "@skycourt/api/services": ["libs/api/src/services.ts"],
```

Is there any way to allow something like this to work?

```
import { SCDayOfWeek } from '@skycourt/api/enums';
```

**Comment by gregveres** [comment]
I realized how I am supposed to do this. 
I have broken the api library into three libraries, api-enums, api-interfaces and api-services. 
I then had our back end tool create barrel files for the three that export all the enums, interfaces or services together into a single index.ts.

My tsconfig.base.json now looks like: 

```
      "@skycourt/api/enums": ["libs/api/src/lib/index.ts"],
      "@skycourt/api/interfaces": ["libs/api/src/lib/index.ts"],
      "@skycourt/api/services": ["libs/api/src/lib/index.ts"],
```

this allows me to import items like this

```
import { someEnum } from '@skycourt/api/enums';
import { someInterface } from '@skycourt/api/interfaces';
import { someService } from '@skycourt/api/services';
```
I am still having an issue but I am sure this is the way I am supposed to go with it. I will open another issue if I can't figure out the new issue I am having.

**Comment by pedrorezende** [comment]
Hi everyone. I'm having the same issue described by @gregveres . I'm using the version 14.0.5 . I think the solution shouldn't be exporting everything from an `index.ts`. I'm trying to migrate my projects to a monorepo managed by NX, so it means a lot of refactoring just because wildcards on typescript paths aren't working correctly. Anyone has a workaround for this?

**Comment by gregveres** [comment]
@pedrorezende It looks like you are doing the same thing I am doing - converting to a monorepo. 
I was happy enough with the solution I found above for the api files, but I am still struggling with the fact that libraries are treated as opaque entities that export all or nothing. I have been using folders as psuedo libraries, but with folders it was easy to reach into a folder and pull out a single element. I can't do that with libraries. This isn't really a problem building the app, but I am find it a big problem with unit testing. For instance some of the items in a library might need to be mocked out where others need to have their code run during a test. I haven't figured out how to do that other than to break up the library into more finely grained libraries. 

If you have run across this and found a solution, I would love to hear how you dealt with it.

**Comment by udnes99** [comment]
Why is this closed? Experiencing the same issue.

**Comment by nhhockeyplayer** [comment]
This needs to be OPEN

The policy on this topic is vague and implementation suspended in the air incomplete and currently INCOMPLETE

Library imports statements warrant precision

Ever since es2015 modules (angular modules generated by nx) have been forced into barrel (index.ts) files the es2015 angular.module.ts forward/backward compatible (and flexible export mechanism isolated to the angular.module.ts) es2015 module concept has become a blurr and inoperable since index.ts is now forced into the library schematic characterizing the entire library INTERFACE 

This was never an issue with earlier versions of Nx, es2015 modules were effectively modeled with a simple utility lib function that pulled in everything from the es2015 angular.module.ts but we cannot do this anymore its index.ts files or nothing now. 

Theres also new confusion between public-api interface and private interface overlap which appears to be documented

Barrel files were likely introduced and done to accomodate react/webpack/javascripter community since index.ts barrel files are javascript centric and serve the javascript functional programmer community.

Please re-open and make this a priority. The field is trying to run with libs at this time and we need this nailed down.

Angular projects are being impacted and we are unable to model large scale buildable publishable libs accordingly without these export/import anomalies which are no doubt imposing confusing codebases

Thanks for an awesome elite product
Looking forward to your best

**Comment by mcarriere** [comment]
The PR that was merged is a step in the right direction but as far as I can tell doesn't allow bypassing the index.ts. This should be reopened

**Comment by mbrimmer83** [comment]
For others running into this issue.
I ran into this error in one of my applications and the issue ended up being an issue with my application `tsconfig.app.json`.
I had an empty "paths": {}` object in my config overriding the root ts config where the library paths are set up.
Broken config, removing paths fix this issue for me
```
"compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["node", "express"],
    "paths": {} // Remove this line or be sure to merge the root level to resolve libs
    "composite": true
  }
```
