### ISSUE TITLE
Migrating a project that has Jest config already to NX

### ISSUE THREAD

**Issue by gokhanoner** [nrwl/nx#10151]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

No

### Additional context or description

There seems to be no documentation about migrating an Angular project that's using jest already. I migrated the project itself without changing the layout, but below command fails ( second one )

```
npm install --save-dev @nrwl/jest
npx nx g @nrwl/jest:jest-project --project=project-name--dry-run
  -> project-name: already has a test architect option.
```

Is there a documentation regarding this?

**Comment by gokhanoner** [comment]
any update on this one?

**Comment by tukusejssirs** [comment]
I wanted to use `babel` in order to test ESM modules (`jest` still has troubles with ESM), therefore I run `nx g @nrwl/jest:jest-project --compiler=babel`, but it failed because app `already has a test architect option.`.

Is there a (simple) way to update `jest` to use `babel` instead of `ts-jest`?
