### ISSUE TITLE
Allow wildcards in nx.json implicitDependencies

### ISSUE THREAD

**Issue by gschuager** [nrwl/nx#10184]
## Description

Allow specifying multiple projects in **nx.json** `implicitDependencies` using wildcards.

## Motivation

I have a **./backend** folder where I group several nx projects (apps and libs), which are named with the prefix `backend-`; at the root of that folder there are some configuration files that affect all the mentioned projects.

I need some way to specify an implicit dependency between all those projects and the corresponding configuration files.

Currently we have 2 options:
- use `*` which creates a dependency to all the workspace projects, not only those inside the **backend** folder
- list each individual project and update that config whenever any project gets added, moved or deleted.

In my case, these are .NET projects and the common files are **Directory.Build.props** and **Directory.Packages.props**, so it would be nice to be able to specify the following in nx.json:

```
  "implicitDependencies": {
    "backend/Directory.Build.Props": "backend-*",
    "backend/Directory.Packages.Props": "backend-*"
  },
```

Currently, that config yields the following error message:

```
nx.json is not configured properly. "backend/Directory.Build.Props" is improperly configured to implicitly depend on "backend-*" but should be an array of project names or "*".
```

**Comment by rfprod** [comment]
@gschuager nx developers and maintainers know better, but from my experience and in my subjective opinion what you want to achieve should be configured on the project level instead of global, and on your own because the case is too specific. See here https://nx.dev/configuration/projectjson
You should probably put your common files in a separate library, so that you can reference it as a single project with common configs, e.g. `backend-common`.
I would recommend looking in the dicrection of custom workspace generators for your .net apps/libs. You could extend one if you use [nx-dotnet](https://github.com/nx-dotnet/nx-dotnet).
A custom generator can add predefined `implicitDependencies` to the `project.json` files of new apps/libs automatically.
Also, you can implement a custom executor that will update your existing `project.json` files as needed and when needed.

**Comment by AgentEnder** [comment]
@rfprod I think one issue in this case is that the project level implicit dependencies cannot reference files, and the only way to say "project X depends on file Y" is through implicit dependencies at workspace root.

Rather than allowing wildcards like this though, we have been discussing the ability to specify tags e.g: 
```json
 "implicitDependencies": {
    "backend/Directory.Build.Props": "tag:lang-c-sharp",
    "backend/Directory.Packages.Props": "tag:lang-c-sharp"
  },
```

I think this would cover the functionality in a bit more flexible manner. Definitely open to your opinion though, @gschuager

**Comment by gschuager** [comment]
Thanks both for your inputs.

@AgentEnder your proposal is certainly more flexible and it would allow us to accomplish the same objective.

**Comment by AgentEnder** [comment]
I reopened this. The original request for wildcards may work now, not 100% sure. In the meantime, the solution agreed on hasn't been implemented yet.

**Comment by AgentEnder** [comment]
I'm reclosing this. `implicitDependencies` in `nx.json` is deprecated in favor of `inputs` and `namedInputs`, which tackle this problem in a slightly different manner.
