### ISSUE TITLE
maxWorkers nor memoryLimit allowed by @angular-devkit/build-angular:browser executor.

### ISSUE THREAD

**Issue by raphael22** [nrwl/nx#10215]
## Current Behavior

Nx won't allow option maxWorkers nor memoryLimit as described in documentation: https://nx.dev/cli/build#maxworkers
Neither project.json nor workspace.json seems to accept it.

## Expected Behavior

Nx should allow maxWorkers option.
Look like a regression, this ticket seems related: https://github.com/nrwl/nx/issues/2856

## Steps to Reproduce

Create a fresh workspace: `npx create-nx-workspace --preset=angular`
Add maxWorkers option:
![image](https://user-images.githubusercontent.com/3912356/167422551-b8e7b1d3-a936-4c96-9052-4276baf080f2.png)

Try to build or serve.

### Failure Logs

```
nx build
> nx run test-app:build:production
'maxWorkers' is not found in schema

nx serve
> nx run test-app:serve:development
Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(maxWorkers).
```

### Environment

Windows 10 - WSL2 Ubuntu
Node 16 - npm 8
Angular 13.3 - Nx 13.10.2

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please note that `maxWorkers` and `memoryLimit` are not options supported by the `@angular-devkit/build-angular:browser` executor. That's why you get an error if you try to use them with that executor. Each executor has its schema with the definition of the accepted options.

The Intellisense provided by Nx Console in VSCode will correctly show the options available for the executor you're using. That's why you see it highlighted in the configuration. You can see the options available to the `@angular-devkit/build-angular:browser` executor in https://angular.io/cli/build#options. It's better to use the reference page of each executor to know the options allowed by it.

The documentation page you refer to seems outdated and needs a refresh to avoid some confusion.

**Comment by raphael22** [comment]
@leosvelperez Hi !
Okay so there is no way to limit memory usage of angular executor ?

I have the same problem as mention in #2856
16gb of ram will be blasted away with default worker/ram options.

**Comment by leosvelperez** [comment]
@raphael22 that's correct, the Angular CLI builder doesn't provide any options to limit the memory usage. This is a limitation on the Angular CLI, the Nx executors for Angular use the Angular CLI compilation under the hood and therefore, the same applies.

You can use `--max-old-space-size` to increase the allocated RAM.

**Comment by leosvelperez** [comment]
I'm gonna close this issue since it has been clarified.
