### ISSUE TITLE
enforce-module-boundaries - Support secondary entry points in workspace libraries

### ISSUE THREAD

**Issue by RobinvanTienhoven** [nrwl/nx#10269]
## Description
Currently the enforce-module-boundaries only looks at project level and not at the entry points for workspace libraries. This means that when using secondary entry points and importing between libraries can result in a circular dependency between projects. 

Using the following library structure:

```
   .
   ├── ...
   ├── libs
   │   ├── api
   │   |   └── src/lib
   |   │     └── services
   |   └── util
   │       └── src/lib
   │          ├── logging
   │          └── validation
   ├── ...
```

With the following paths in TSConfig.base:
```
"paths": {
   "@api/service": ["libs/api/src/lib/service"],
   "@util/logging": ["libs/util/src/lib/logging"],
   "@util/validation": ["libs/util/src/lib/validation"]
 }
```

Using the logging module in service while using the service module in validation results in a circular dependency between projects.
Error: 
```Typescript
 Circular dependency between "util" and "api" detected: util -> api -> util
 
 Circular file chain:
 - libs/util/src/lib/validation/validator.ts
 - [
    libs/api/src/lib/services/reference/reference-service.ts
   ]
```

## Motivation
Normally this would be correct, but since I am using secondary entrypoints in my libraries (index.ts in each separate folder with a TSConfig path pointing to it) I do not reference the whole project, what should mean there is no circular dependency. The linting rule should not throw a `Circular dependency detected` error. 

## Suggested Implementation
Since the [current implementation](https://nx.dev/packages/angular/generators/library-secondary-entry-point) of a creating a secondary entry point for a library only works with buildable & publishable libraries (it requires a package.json in the library itself), the feature should be extended to also support workspace libraries.

## Alternate Implementations
An alternative option would be to be able to configure the linting rule to check for the actual import instead of only looking at projects. The only catch is that this should be configurable per project, since not all projects within the monorepo will use the secondary entry points.

**Comment by RobinvanTienhoven** [comment]
Thanks you for the response, your explanation of the problem is correct. 

We've thought about splitting the library into multiple small libraries, but that would mean about 30+ small libraries with only one function, where we now have 4 libraries that all contain small building blocks (utils, api, portal-components, and so on). 

This is quite useful when importing stuff in the different applications and (in my opinion) keeps the import tree clean: 

```Typescript
import { Logger } from '@utils/logging';
import { PhoneValidator } from '@utils/validation';
import { ButtonModule } from '@portal-components';
```

Where normal imports without sub-paths would look like: 
```Typescript
import { Logger, PhoneValidator } from '@utils';
import { ButtonModule } from '@portal-components';
```
these imports can become quite big with the number of small util functions we have.

Is there a way to make the linter understand that it is ok to import stuff from a deeper path or is creating a lot of small libraries the only way?
(allow `@utils/<path>` instead of just looking at the projects (`@utils`) for module-boundaries)

**Comment by meeroslav** [comment]
If what you need is:
```ts
import { Logger } from '@utils/logging';
import { PhoneValidator } from '@utils/validation';
```

You can still achieve it by having a single `utils` project and having barrel `index.ts` files in `logging` and `validation` folders. Note that cross imports between `logging` and `validation` will still have to be relative since they belong to the same project. If you do not like this you can explicitly switch it off in eslint rule `{ allowCircularSelfDependency: true }`.

Unfortunately, all that does not solve your circular dependency chain (as presented above), which results from a mistake in the architecture. 

There is of course a way to "make the linter understand" but it's not the correct thing to do, since it's causing a circular dependency (and that's not related to the linter). Think of every library as potentially publishable. How would you publish it to npm - as `utils` or `@utils/logging` + `@utils/validation`? If the answer is the latter, then they should be two packages/libraries in your monorepo.

**Comment by meeroslav** [comment]
Thank you @RobinvanTienhoven for follow-up. I will therefore close this issue.
