### ISSUE TITLE
@nrwl/node:webpack treats packages as externals when using npm workspaces

### ISSUE THREAD

**Issue by arrocke** [nrwl/nx#10386]
## Current Behavior

We use nx and npm workspaces. NPM will create a symlink to your package in node_modules. Since our package names are the same as our typescript aliases, the node webpack executor considers libraries as external and doesn't rewrite module import paths.

Example:
We have a ts library named `@pi/types`. NPM links it to `node_modules/@pi/types`, and we import it into our node package as `import types from '@pi/types'`. When compiling the node application, the library is not compiled into the bundle. If we delete the linked node_module, then it compiles as expected

## Expected Behavior

I would expect that the webpack externals configuration would treat packages in the workspace as exceptions to the external rule

## Steps to Reproduce

1. Create ts library with `@nrwl/js`
1. Create node application with `@nrwl/node`
1. Add these two packages to the root package.json as npm workspaces
1. Make sure that the library name in its package.json is the same as the typescript alias
1. Run npm install
1. Build node application
1. Try to run application

### Environment

Node : 14.18.2
   OS   : linux x64
   npm  : 8.6.0
   
   nx : 13.8.7
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.7
   @nrwl/cypress : 13.8.7
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.7
   @nrwl/eslint-plugin-nx : 14.1.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.7
   @nrwl/js : 13.8.7
   @nrwl/linter : 13.8.7
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.7
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.7
   @nrwl/web : 13.8.7
   @nrwl/workspace : 13.8.7
   typescript : 4.2.4
   rxjs : 6.6.7

**Comment by arrocke** [comment]
As a workaround, we added this to our webpack config:
```
  config.externals = [
    nodeExternals({
      modulesDir: path.resolve(__dirname, '../../node_modules'),
      allowlist: [/^@pi\//]
    })
  ]
```

**Comment by nartc** [comment]
@arrocke thanks for reporting. By default, `nrwl/node:webpack` treats **ALL** external dependencies as external. In this case, we know that `@pi/types` is external because of NPM Workspaces.

If the workaround is working for you, that's great. In `nrwl/node:webpack`, there is an option `externalDependencies` that you can also set to `[]` to tell `nrwl/node:webpack` what the **actual** external dependencies are. This way, `nrwl/node:webpack` will bundle your library if it's not listed in the array. This has a con of getting verbose if your application is utilizing many 3rd party libraries. 

```json
{
   "build": {
      "executor": "@nrwl/node:webpack",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/app-one",
        "main": "apps/app-one/src/main.ts",
        "tsConfig": "apps/app-one/tsconfig.app.json",
        "assets": ["apps/app-one/src/assets"],
        "externalDependencies": []
      },
   }
}
```

Now, we can definitely apply your workaround in `nrwl/node:webpack` code but it might get tricky when you have `publishable` libraries. Are those supposed to be externals or supposed to be bundled? People can also have different `importPath` than the default one with the `npmScope` as well. It can get very dynamic and `nrwl/node:webpack` might not be able to figure it out to change the webpack config dynamically.

Since we already have a workaround using `externalDependencies` built-in, I'm going to close the issue as non-fix. If you feel like the fix should indeed be in nrwl/node itself, please send a PR or open a new issue with a feature request.

Thanks again.
