### ISSUE TITLE
The `@nrwl/storybook` does not recognize`@storybook/angular` as ui framework

### ISSUE THREAD

**Issue by ales-albert-kilbergr** [nrwl/nx#10583]
## Current Behavior

The `@nrwl/storybook` library in version `14.1.9` does not allow to run storybook for angular.

**The error:**

```
Property 'uiFramework' does not match the schema. '@storybook/angular' should be one of @storybook/react,@storybook/html,@storybook/web-components,@storybook/vue,@storybook/vue3,@storybook/svelte.
```

**Reason**

The `@nrwl/storybook` package does not list`@storybook/angular` in its schema.

Checked in files 
 - `packages/storybook/src/executors/storybook/schema.json`
 - `packages/storybook/src/executors/build-storybook/schema.json`

https://github.com/nrwl/nx/blob/c0a0f1691373996f1b76622143c5646168ef1eb3/packages/storybook/src/executors/build-storybook/schema.json#L16-L23

If the drop of support for `@storybook/angular` is intentional, close this issue with comment, whether it is a temporary or permanent.

Thanks.

**Comment by eglyte** [comment]
https://github.com/nrwl/nx/pull/10387/files#diff-f0c11fce7b2a08f1f50a8fbc7f1e67de387c290b15aa9a84d24423105b11112cR338
on last commit to master "default" changed and there is no "@storybook/angular" in the "enum" list
- "default": "@storybook/angular",
+ "default": "@storybook/react",

**Comment by baunov** [comment]
Same issue. Is there some temp fix before the update gets published?

**Comment by Coly010** [comment]
Hey :) Thanks for reporting the issue!

Do you have a repo containing the issue?

I feel like you should be able to switch to use `@storybook/angular:build-storybook` and `@storybook/angular:start-storybook` in your app's project.json, but I'd like to confirm this

**Comment by mandarini** [comment]
Hi there @baunov @ales-albert-kilbergr @eglyte ! Thanks for this issue.

Please take a look at these comments here: [Comment 1](https://github.com/nrwl/nx/issues/8496#issuecomment-1139564057), [Comment 2](https://github.com/nrwl/nx/issues/8496#issuecomment-1139569746)

Also, please take a look at the [documentation](https://nx.dev/storybook/extra-topics-for-angular-projects) as well as our new generator, [change-storybook-targets](https://nx.dev/packages/storybook/generators/change-storybook-targets).

I am assuming you did not use `nx migrate` to move to latest version, but that's ok. You can use the [change-storybook-targets](https://nx.dev/packages/storybook/generators/change-storybook-targets) to change your Storybook targets for Angular projects across the repo.

As I noted in the comments liked above, this is 100% intentional. Starting Nx v.14.1.8 we are moving away from the Nx executor, and we're using the native Storybook executor.

**Comment by mandarini** [comment]
So, I will be closing this issue now, and let me know if you're still having trouble! :)

**Comment by venture-vin** [comment]
Hoping that someone can point me in the right direction with this issue. I am on `angular version=12.2` with `nx version=12.10.1` and `nrwl/storybook=15.3.3` which looks to resolve to storybook version = 6.3.0. My problem is the same as the original comment. `Property 'uiFramework' does not match the schema. '@storybook/angular' should be one of @storybook/react,@storybook/html,@storybook/web-components,@storybook/vue,@storybook/vue3,@storybook/svelte.`

I see all the migration documentation points to upgrading NX to 14. But the highest version I can upgrade to currently is nx 13 (have not upgraded yet to angular 13, that's going to be a separate project that hasn't started yet). 

I am setting up Storybook in an already existing Angular project with nx configured. Would the recommendation here be to use a different storybook version that contains uiFramework enum until I can upgrade angular and therefore nx that would be compatible with the new executor commands? 

Please let me know if I can provide more information to get some help. Spent the last 3 hours searching through migration docs, issues, and discord but was unable to come up with anything that works.

**Comment by mandarini** [comment]
Hello! So, the thing is that your `@nrwl/*` packages versions should all be aligned, for Nx to work correctly. Can you please try aligning the versions, and see if it works?

**Comment by venture-vin** [comment]
> Hello @venture-vin ! So, the thing is that your `@nrwl/*` packages versions should all be aligned, for Nx to work correctly. Can you please try aligning the versions, and see if it works? So, just install the version of `@nrwl/storybook` that all your other `@nrwl/*` packages are using.

This worked @mandarini, thank you so much! Hopefully, this helps someone else that is looking at this issue.
