### ISSUE TITLE
add a way to run affected on staged items only

### ISSUE THREAD

**Issue by ZNackasha** [nrwl/nx#10672]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

add a way to run affected on staged items only

## Motivation

i want to run a git precommit hook on affected staged items

**Comment by AgentEnder** [comment]
Hey @ZNackasha, can you go into more details about your use case? I'd be hesitant to add a `--staged` flag for `nx affected` for a few reasons. They mostly boil down to this one root concern:
- Nx targets run at the **_project_** level, not the **_file_** level, where as `--staged` operates at the file level.

Imagine using this with `test` or `lint`. 
- If you have 1 file from the project staged, but lint or test errors are present in other files, the target run will fail regardless of the fact that --staged was passed in. This is because the target for the **_project_** failed
- If you have 1 file from the project staged, but **_fixed_** lint or test errors are present in other files, the target run will pass regardless of the fact that --staged was passed in. This is because the files for the project are in a working state in your working directory, despite the staged index containing the repo in a broken state.

**Comment by kevincaradant** [comment]
Hi @AgentEnder  and @ZNackasha 

I don't know if this feature is still on the roadmap, but I think I would like the same feature because I would like a precommit ( really quick for affected and format:write also ) without to have all others files linked because for example, it's using a pipe (angular). It's a real use case for me. 
We want to "migrate" a little bit by little bit without having all the dependencies checks like today.
Maybe I don't use correctly the CLI but today I'm using in my `.lintstagedrc.js` file : 

```
module.exports = {
  '{apps, libs}/**/*': [
    'npx nx affected:lint --fix --parallel --uncommitted',
    'npx nx format:write --uncommitted --libs-and-apps true',
  ],
};
```

But the issue is when I change one file, sometimes, it will edit 15 files because the others files are using this staged service or Pipe with angular. Anyway, I would like to avoid this behavior, maybe something exist today for this ? 

Thanks :)
