### ISSUE TITLE
Migration step "migration-v14" (Updates the Angular CDK to v14) problem

### ISSUE THREAD

**Issue by mlc-mlapis** [nrwl/nx#10681]
## Current Behavior
When running the latest migration process (to Nx 14.2.4: `nx migration latest`) the following migration step is also generated:
```
{
      "version": "14.0.0-0",
      "description": "Updates the Angular CDK to v14",
      "factory": "./ng-update/index#updateToV14",
      "package": "@angular/cdk",
      "name": "migration-v14"
    }
```
Running the `nx migrate --run-migrations` command leads to the following report:
```
Running migration migration-v14
    Skipping migration for project general. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project providers. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project lazy-loading-e2e. Unable to determine 'tsconfig.json' file in workspace config.
      ✓  Updated Angular CDK to version 14 
Successfully finished migration-v14
```
The problem related to the lines:
```
Skipping migration for project general. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project providers. Unable to determine 'tsconfig.json' file in workspace config. 
```
can be solved by adding the line `"tsConfig": "libs/<lib>/tsconfig.lib.json"` into the `test: {options: ...}` section of the `project.json` configuration of each lib:
```
 "targets": {
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": [
        "coverage/libs/<lib>"
      ],
      "options": {
        "jestConfig": "libs/<lib>/jest.config.ts",
        "passWithNoTests": true,
        "tsConfig": "libs/<lib>/tsconfig.lib.json"
      }
    },
```

But it's unclear what to do in the cases of the generated E2E applications to eliminate the message `Skipping migration for project <app>-e2e. Unable to determine 'tsconfig.json' file in workspace config.`

Adding the line `"tsConfig": "apps/<app>-e2e/tsconfig.json"` into the `e2e: {options: ...}` section of the `project.json` configuration for such an E2E application doesn't help:
```
{
  "$schema": "..\\..\\node_modules\\nx\\schemas\\project-schema.json",
  "sourceRoot": "apps/<app>-e2e/src",
  "projectType": "application",
  "targets": {
    "e2e": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "cypressConfig": "apps/<app>-e2e/cypress.json",
        "devServerTarget": "<app>:serve:development",
        "tsConfig": "apps/<app>-e2e/tsconfig.json"
      },
      "configurations": {
        "production": {
          "devServerTarget": "<app>:serve:production"
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": [
        "{options.outputFile}"
      ],
      "options": {
        "lintFilePatterns": [
          "apps/<app>-e2e/**/*.{js,ts}"
        ]
      }
    }
  },
  "tags": [],
  "implicitDependencies": [
    "lazy-loading"
  ]
}

```

## Expected Behavior
No warning and passing migrations successfully even for E2E apps.

## Steps to Reproduce
Migrate from an Angular application v13 with CDK dependency to the Angular v14 through the Nx migration.

### Environment
Nx v14.1.9 with Angular 13.3.11 and running the `nx migrate latest` command.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please note that's just a warning, not an error and it doesn't really affect e2e projects because the migration won't make any changes for them. That migration comes from the `@angular/cdk` package which is not something authored by Nx so we can't make changes to it to accommodate other requirements. Since the Angular CLI doesn't create e2e projects, their migrations don't consider there can be projects that are not "Angular" projects, which is possible in an Nx workspace.

A full solution to this would require a good amount of effort and it will mean preventing running those migrations from Angular packages and "clone" them into Nx while adapting its logic to handle the scenarios mentioned above. 

Given is a warning that's not exactly causing an issue and that a solution for it requires considerable effort, I'm going to close this for the time being. We'll consider the solution outlined above for future migrations.

**Comment by mlc-mlapis** [comment]
@leosvelperez Thank you for your explanation. 👍
