### ISSUE TITLE
Support jest-light-runner

### ISSUE THREAD

**Issue by intellix** [nrwl/nx#10781]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'd like to be able to use jest-light-runner (https://www.npmjs.com/package/jest-light-runner)

## Motivation

Babel reported that their test suite became 2x faster with it, as it doesn't use VMs and you can achieve isolation in other ways. It improve the developer experience when testing. 

## Suggested Implementation

I believe that we should be able to specify: `{ runner: 'jest-light-runner' }` inside jest.preset.js and thne it would just work. Currently you get issues with unrecognised TS files.

**Comment by AgentEnder** [comment]
Hey @intellix! We aren't likely to add first-class support for jest-light-runner at this moment, as it's not something that we use with clients or is used by a large set of the community.

That being said, @nrwl/jest:jest doesn't do anything special regarding how jest is executed. The configuration, path mappings, etc., go through the normal jest execution flow. If configured correctly, this should "just work."

Looking at the readme for jest-light-runner, on-the-fly compilation isn't supported for typescript. Nx sets this up for you by default since most jest runners support it. On top of adding the configuration for the runner in jest.preset.js, you'd need to update your project's jest configurations to do something about this. Here is the relevant section of the readme: https://www.npmjs.com/package/jest-light-runner#user-content-unsupported-jest-features

I'm going to close this out since it's not something we will be adding at this point. If you continue down this path, I'd recommend setting up some generators in your workspace (either via workspace-generator or local plugins) that handle this for you.
