### ISSUE TITLE
Yarn+NX rebuilds all workspaces with any package.json dependency change

### ISSUE THREAD

**Issue by gbisaga** [nrwl/nx#10842]
## Current Behavior

NX rebuilds all yarn workspaces when the package.json dependencies of any workspace change. Since we are using internally-published packages and iterating them frequently, this causes the project to rebuild way too often.

## Expected Behavior

NX only rebuilds workspaces with actual dependency changes.

## Steps to Reproduce

1. Clone https://github.com/gbisaga/nx-rebuild-all
2. `yarn install --frozen-lockfile`
3. `yarn build:all`
4. `yarn workspace @ps-refarch/nxpackage3 add jsonwebtoken`
5. `yarn build:all`

Expected behavior: only @foo-monorepo/nxpackage3 rebuilds
Actual behavior: all 3 workspaces rebuild

### Environment

   Node : 16.13.1
   OS   : win32 x64
   yarn : 1.22.18

   nx : 14.3.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.1
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.1
   @nrwl/js : Not Found
   @nrwl/linter : 14.3.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

**Comment by gregjacobs** [comment]
+1, and I just noticed the same while evaluating Nx. We update dependencies quite often in our current [Rush](https://rushjs.io/) repository, and I could foresee this creating a lot of full repo rebuilds in Nx.

Instead of hashing the dependencies/devDependencies text inside package.json, it seems Nx needs a mechanism to hash based on the particular npm dependencies that are actually used by the package + its build tools. Perhaps the root-level package-lock.json or yarn.lock could be used for this purpose? (Store a hash of the dependency graph created for any given package X?) Or is the better solution to have a separate package.json file for each package?

**Comment by gbisaga** [comment]
Greg, we do have a separate package.json for each of the components, which is why the current behavior seems unexpected. I am guessing the reason it's rebuilding is because yarn "hoists" the package installs up to the base directory - i.e. even though I installed this package in the `@foo-monorepo/nxpackage3` component, it actually installs it in the root node_modules. Technically, this means other components _could_ access it there, although that would be incorrect. I feel like it should be hashing the separate component dependencies instead of all of them combined as it seems to be doing.

**Comment by dan-cooke** [comment]
This is because of `implicitDependencies`

Quite a few discussions and issues around this in NX

https://github.com/nrwl/nx/discussions/5580
https://github.com/nrwl/nx/discussions/5580

This is the main issue tracking this  https://github.com/nrwl/nx/issues/1972 and its been sitting for 2 years now.

Its a major problem with NX - if you have a large monorepo, any changes to `package.json` will trigger `nx affected` for all projects and libraries - even though only one project may use the library.

This really wrecks havock on CI builds when you are building 10+ apps in parallel in docker - no one change should ever require that many projects to rebuilt.

**Comment by ianldgs** [comment]
Yeah, simply adding a new dependency to one library, even with pnpm workspaces, is causing all packages to be affected.
I've tried with nx@15.8.6, which is supposed to have all the new lockfile parsing, but no luck.
@meeroslav is there any new change that could fix this?
It's the whole point of NX to not affect everything all the time.

**Comment by ianldgs** [comment]
Understood, @meeroslav! Thanks for looking.

So, in my case it's clear why the packages didn't get a cache hit: there's a versioning step that bumps the affected packages, therefore invalidating the cache.
Maybe we could only run this in a "release" build, once a day, but I really like merging to master and having the npm package I just created/fixed be published to the registry.

At some point in NX < 14 (I think) (before named inputs), any change to the root package.json would affect all packages. That was annoying, but after integrating npm/yarn/pnpm workspaces we could declare dependencies per package, so the change in the local package.json would only affect their respective packages. Lockfile used to be ignored in that case IIRC.
IMO that was a better flow, as some of our packages require explicit declaration anyway. And if a dependency at the root was changed, it was much more likely that it really affected all packages (e.g. upgrading `nx`).
