### ISSUE TITLE
wrapAngularDevkitSchematic unable to find schematics in`@angular-architect/ddd' collection.

### ISSUE THREAD

**Issue by landonbuttars** [nrwl/nx#10840]
## Current Behavior

`wrapAngularDevkitSchematic` is unable to find schematics from the `@angular-architect/ddd' collection.

I'm able to use schematics from `@schematics/angular`. Not sure the difference between the two projects, their collections.json looks similar enough.

```
export default async function (tree: Tree, schema: any) {

  const dddFeatureGenerator = wrapAngularDevkitSchematic('@angular-architects/ddd', 'domain');

  await dddFeatureGenerator(tree, {
    name: schema.name,
    prefix: false,
    domain: schema.domain,
    domainDirectory: schema.domainDirectory,
    app: schema.app,
    entity: schema.entity,
    type: schema.type,
    importPath: schema.importPath,
    noApp: schema.noApp,
    standalone: schema.standalone,
    ngrx: false,
  });

  await formatFiles(tree);

  return () => {
    installPackagesTask(tree);
  };
}
```

## Expected Behavior

wrapAngularDevkitSchematic should find the collection no problem...

## Steps to Reproduce

Create a generator
Add `@angular-architect/ddd`
Copy the above code into the generator
It should error out.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by landonbuttars** [comment]
It seems that the intended way to use an external generator is to import it from the external package. This becomes quite annoying when the third party package doesn't export the generator which is the case with `@angular-architects/ddd`.

A workaround for this was to import the generator function directly from the node_modules. 

Should there be a new function or expand the existing function to include executing generators from external libraries?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `wrapAngularDevkitSchematic` helper resolves an Angular DevKit schematic and returns a function that can be used to invoke the schematic as a generator function. For that to work, the Angular DevKit schematic must be defined in the collection. In this case, there are no schematics defined in the `@angular-architects/ddd` collection, there are only generators, and therefore, the helper is not supposed to be used.

As you realized, a generator is just a function; as such, it's meant to be imported and invoked directly. This provides a better DX and features like type safety, while a schematic doesn't provide the same. You can create an issue in the `@angular-architect/ddd` repo asking the author to export the generators.

I'm closing this since everything is working as expected.
