### ISSUE TITLE
How to create documentation.json for each project configured with storybook?

### ISSUE THREAD

**Issue by its-ratikant** [nrwl/nx#10854]
`nx g @nrwl/angular:storybook-configuration <project-name>` does not create documentation.json for that specific lib / app. How to create documentation.json for each project which are configured with storybook? Can we have some kind of executor/task or so to generate it? something like: `nx run project-name:generate-doc` and also can it be even part of storybook runner task?

For Angular we have to do something like the below: but for multiple libs/apps how we can do this?

```
{
  ...
  "scripts": {
    "docs:json": "compodoc -p ./tsconfig.json -e json -d .",
    "storybook": "npm run docs:json && start-storybook -p 6006 -s src/assets",
    ...
  },
}
```

**Comment by its-ratikant** [comment]
Hi, any ways we can achieve this?

**Comment by mandarini** [comment]
Hi there @its-ratikant !

So, I see you're using Angular with Storybook and Nx. In that case, you can use the [Storybook official documentation for how to create docs](https://storybook.js.org/docs/angular/writing-docs/introduction).

If you're using React with Storybook and Nx, I dare say the process would be quite similar, here's the [Storybook documentation](https://storybook.js.org/docs/react/writing-docs/introduction).

There is no executor on the Nx side at the moment to generate docs for all projects that have a Storybook configuration, since, I believe this could fall easily into traps - or assumptions as to how each project is configured.

However, if you do want to generate docs massively, for more than one project at the time, you can configure the `storybook`/`build-storybook` targets of your projects (in each project's `project.json`) to use `compodoc` and generate docs. Then, you can use the [`run-many`](https://nx.dev/cli/run-many) command, and generate the docs for all the projects you provide!

Take a look [here](https://nx.dev/packages/workspace/executors/run-commands#nx-affected) as well. You can create your custom `target` and combine the `storybook` command into one!

**Comment by its-ratikant** [comment]
Thanks a lot for your help!!

I am able to create docs (documentation + documentation.json) using below task runner:

 ```
"generate-docs": {
      "executor": "nx:run-commands",
      "options": {
        "command": "npx compodoc -p libs/ui-components/tsconfig.json -d libs/ui-components/documentation"
      }
    },
    "generate-docs-json": {
      "executor": "nx:run-commands",
      "options": {
        "command": "npx compodoc -p libs/ui-components/tsconfig.json -d libs/ui-components -e json"
      }
    }

```

I needed documentation.json to get generated as it is required to show the doc properly and even controls as per the type definition of each property.

Now I want `generate-docs-json` as a part of the below task executor, so that it will create the documentation.json first before it  runs the storybook.

```
"storybook": {
      "executor": "@storybook/angular:start-storybook",
      "options": {
        "port": 4400,
        "configDir": "libs/ui-components/.storybook",
        "browserTarget": "ui-components:build-storybook",
        "compodoc": false
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
```

In preview.js I have below configuration:
```
import { setCompodocJson } from '@storybook/addon-docs/angular';
import docJson from '../documentation.json';

setCompodocJson(docJson);

```

![image](https://user-images.githubusercontent.com/77279630/175571182-9f232fb6-d861-41be-8145-2ecc173ebaca.png)

**Comment by its-ratikant** [comment]
This way it works!!

```
"storybook-all": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "nx run ui-components:generate-docs-json",
          "nx run ui-components:storybook"
        ],
        "parallel": false
      }
```

**Comment by mandarini** [comment]
Perfect!!!!! :D :D

**Comment by timtos** [comment]
If we need to do all this, what is this `"compodoc": false` setting for? I thought one could set this to `true` and everything works out of the box. Was I wrong? I couldn't find any documentation on this.

**Comment by mandarini** [comment]
It's set to false, because if it's set to true, then you need to install `compodoc` and configure documentation for your Storybook. The [documentation about it is here](https://storybook.js.org/docs/angular/writing-docs/introduction), in the official Storybook docs. In the Angular case, Nx does not do anything more than Storybook already does. You should be able to use the Storybook docs to do anything you need! :) Let me know if I can provide any more information!

**Comment by timtos** [comment]
@mandarini, thank you for your input. One question remains: Would it make sense to extend the default properties like so:
`"compodocArgs": ["-e", "json", "--disablePrivate"]`

Without this `disablePrivate` setting, even private observables will be available to be changed in storybook, making them to strings, which results in: Invalid pipe argument. And as this setting is for storybook only, I would say, that this makes sense. Or am I doing something totally wrong?

**Comment by mandarini** [comment]
Hi @timtos ! I am not sure how to answer that, to be honest :( It's Storybook specific, so I would suggest you make the same question on the Storybook side :( I'm sorry I cannot answer that, I have not worked much with Storybook docs...

**Comment by timtos** [comment]
Hey @mandarini, thank you so much for your answers and help, I thought this is nx related as nx is setting the defaults [here](https://github.com/nrwl/nx/search?q=compodocArgs).

![image](https://user-images.githubusercontent.com/2648014/178257959-540b0b2c-685e-4993-9878-760f4c6d9a10.png)

For me this is ok now, but I guess for other people starting with compodoc, it will be confusing, too, when they are using observables - and who isn't? ;)

**Comment by mandarini** [comment]
If you look [here](https://github.com/nrwl/nx/blob/51b66d139498f8cc15b7166b29e2c11ee08e6705/packages/storybook/src/generators/change-storybook-targets/change-storybook-targets.spec.ts#L7), the file that you mention above is imported in the test. It's just a Storybook configuration with extra options, so that I can test the `change-storybook-targets` generator, and make sure it copies over all the options! I wrote there some valid config, but I could have written 
```
"options":
  {
    "doesntreallymatter": "whatIwriteHere"
  }
```

to test it..
