### ISSUE TITLE
 cmd line option for STORE with relevant rigging

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#10879]
Introduce a cmd line option during @nrwl/angular:ngrx schematic code generation for (nxconsole too)

- STORE
- COMPONENT STORE
- ENTITY STORE 

but none so far I can see. 

This would eliminate alot of undoing redoing immediately after the code generation. And Im generating a ton of stores now. These little bits will help and go far. Example... My hitcount needs no entity store... its just one instance off root store. I dont need all the entity store stuff forced on my initial scaffold code generation. 

If there is a switch let me know I will use it. But everything being generated is entity store assuming consumers will alter the interfaces and it would be so nice if we had to do nothing.

this came out of
https://github.com/nrwl/nx/issues/10845

**Comment by nhhockeyplayer** [comment]
Can this get some attention?

There really should be a 4-way option model for this.

```
- simple object {} (with its rigging)
- collection [] (with its rigging)
- entity (with all its rigging)
- component (with its rigging)
```

right now we are forced to consume the entity model as the ONLY kind of store when a variety of stores are reality for instances and collections and their rigging.

**Comment by Coly010** [comment]
Hey @nhhockeyplayer 

We'll consider this feature request for upcoming versions of Nx. However, in the meantime, I'll link to the NgRx Docs, as you don't _have_ to use generators to set this stuff up. If what is generated doesn't fit the model you need, it may be easier to just add the files and code yourself.

https://ngrx.io/guide/store

I'll also link to the NX Devkit docs, because you could also write a generator to generate the code you way need it!

https://nx.dev/extending-nx/nx-devkit


NgRx also has it's own schematics package that you could use: https://ngrx.io/guide/schematics
