### ISSUE TITLE
The command to install Eleventy is wrong

### ISSUE THREAD

**Issue by urielblanco** [nrwl/nx#11010]
### Documentation issue

- [ x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description
The command to install Eleventy in npm is the following => nx generate @nrwl/react:library 
Different from the yarn one.

Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
Can you add a link to the affected docs page, perhaps a screenshot of the incorrect info etc? Currently there is not enough info to begin working on a fix.

**Comment by pumano** [comment]
https://nx.dev/core-tutorial/01-create-blog that guide simply does not work.

`nx serve blog` just show error `Cannot find project 'blog'`

**Comment by rotavio** [comment]
In the third step of the tutotial, [Adding Eleventy](https://nx.dev/core-tutorial/01-create-blog#adding-eleventy), the npm version of the command line is doing another unrelated thing:

**Yarn**
yarn add -D @11ty/eleventy@1.0.0

**Npm**
nx generate @nrwl/react:library

And although the yarn command is apparently right, it raises and error and dos not run:
_Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check)._

**Comment by rotavio** [comment]
On the next step, [Running Eleventy with Nx](https://nx.dev/core-tutorial/01-create-blog#running-eleventy-with-nx), the first command:

_nx serve blog_

also does not work, and print this error:

 _>  NX   Cannot find project 'blog'_

**Comment by nightmarelie** [comment]
> On the next step, [Running Eleventy with Nx](https://nx.dev/core-tutorial/01-create-blog#running-eleventy-with-nx), the first command:
> 
> _nx serve blog_
> 
> also does not work, and print this error:
> 
> _> NX Cannot find project 'blog'_

1. Please delete workspace.json in the root to handle `NX Cannot find project 'blog'` error

2. For npm project. To handle `command not found: eleventy`:

 `npx nx serve blog`
