### ISSUE TITLE
[Angular] after latest release, my MFEs broke. path has changed for imports

### ISSUE THREAD

**Issue by Coly010** [nrwl/nx#11030]
BTW after some recent upgrades, my MFEs broke. Looks like the path has changed from `@nrwl/angular/mfe` to `@nrwl/angular/mf`

![image](https://user-images.githubusercontent.com/707567/177447603-286605b2-9053-40d7-9bbd-0f549cb021d7.png)

![image](https://user-images.githubusercontent.com/707567/177447626-66ec2704-71d3-48b3-9204-69154bec951c.png)

_Originally posted by @benpsnyder in https://github.com/nrwl/nx/issues/10887#issuecomment-1175669137_

**Comment by Coly010** [comment]
@benpsnyder In what manner did you upgrade Nx? There were migrations that should have run that would have automatically fixed these paths for you.

Did you upgrade nx using `nx migrate latest`?

**Comment by benpsnyder** [comment]
@Coly010 on this one ... I might have upgraded early to `next` while you guys were pushing betas for 14.4.x ... but I always am careful to run migrations, and when in doubt, I re-run them like so: `nx migrate @nrwl/workspace@14.4.2 --from="@nrwl/workspace@14.0.0"`

Sorry I know this isn't too helpful as it's not specific, but I am just letting you know that I _usually_ don't skip the migrations! :)

**Comment by leosvelperez** [comment]
@benpsnyder it turns out the migration for this is targeting `14.5.0-beta.0` but the change was released in `14.4.0`. Because of that, even though the migration is available in the published package, the migrator tool doesn't pick it up because it's targeting a greater version.

Unfortunately, there's little we can do at this point to fix the existing versions (>=14.4.0 <14.5.0-beta.0) and folks that have already migrated to those versions will need to either adjust their source code manually or wait for 14.5.0 to upgrade. Pushing a change to amend the target version to 14.4.0 can only be released in a version greater than that, so, it won't solve the problem in those versions.

Because of the above, you can either:

- Adjust your code manually to handle the changes
- Wait for 14.5.0 to migrate to it and get the automatic migration (don't migrate to 14.5.0-beta.0, there's currently an issue with the migration that's [being fixed](https://github.com/nrwl/nx/pull/11126) and should be released in a later version)

**Comment by benpsnyder** [comment]
> 

Lovely, thorough reply. Thank you!

**Comment by leosvelperez** [comment]
I'm going to close this issue since there's nothing we can do to fix the already published versions. For anyone coming to this, please wait for the 14.5.0 release which will include the automatic migration.
