### ISSUE TITLE
Replace node with Bun, insane performance with node package resolution compatibility.

### ISSUE THREAD

**Issue by algoflows** [nrwl/nx#11049]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Integrate Bun instead of node.

## Motivation

Insane performance is better than rust. 
Unlike deno is completely compatible with npm and node ecosystem. Just 4x improvement over deno and 2x over node.

## Suggested Implementation

Instead of using node and npm we would use Bun for all bundling and package management.

## Alternate Implementations

There is no other way.

**Comment by AgentEnder** [comment]
Hey @algoflows 👋.

Several of us are interested in bun, and the improvements it can offer, but currently this is not something that we would integrate for a few reasons. 

As noted in buns readme, bun isn't quite ready for production use.
> bun is experimental software

I'm going to close this out for now. After bun has matured a bit, and proven its sticking power, we will happily re-evaluate.

**Comment by ericwooley** [comment]
IDK about replacing node with bun, but support for either would be nice.

**Comment by algoflows** [comment]
I get that Friday feeling people want to see this happen, hopefully this gets re-opened! Bun support on the way, imagine how happy this would make the NX community and how much positive press this could generate through an article and reddit threads! Headline "NX supports Bun", millions of click and lots of developer traction 😄

**Comment by AgentEnder** [comment]
You can see the thinking here: https://github.com/nrwl/nx/discussions/11048#discussioncomment-3191305

If some community members wanted, they could spearhead a community plugin to add support for executing/bundling with bun pretty easily. Support for bun as a package manager requires changes inside Nx core though, and bun is labeled as experimental.

**Comment by Nick-Mazuk** [comment]
> Support for bun as a package manager requires changes inside Nx core though, and bun is labeled as experimental.

Out of curiosity, why would this require changes to Nx core?

From my perspective, Node runs Nx. Nx does not run Node (some Nx plugins definitely do call Node under the hood, but that's not core). Likewise, using Bun would mean Bun calls Nx. Nx would not need to call Bun if Nx does not call Node.

Now Nx definitely does use Node APIs, but Bun supports 90% of Node apis. So as far as I can tell, as long as Nx doesn't use one of the 10% of APIs which are unsupported by Bun, things should just work.

I'm probably missing something here, so I'm really curious about what that might be.

**Comment by algoflows** [comment]
@AgentEnder Quite a bit of traction already on this issue, it should be re-opened, it was closed way waaaay to quick.

**Comment by AgentEnder** [comment]
I'm going to lock this issue, as no current actions will be taken within Nx for `bun` support. Discussions of the various ways that `bun` can be integrated with Nx, and any follow up that may have been posted here **_should_** be in the discussion, rather than a closed issue.

The discussion for `bun` is here: #11048

@Nick-Mazuk 
>  > Support for bun as a package manager requires changes inside Nx core though, and bun is labeled as experimental.
>
> Out of curiosity, why would this require changes to Nx core?
> 
> From my perspective, Node runs Nx. Nx does not run Node (some Nx plugins definitely do call Node under the hood, but that's > not core). Likewise, using Bun would mean Bun calls Nx. Nx would not need to call Bun if Nx does not call Node.
> 
> Now Nx definitely does use Node APIs, but Bun supports 90% of Node apis. So as far as I can tell, as long as Nx doesn't use one > of the 10% of APIs which are unsupported by Bun, things should just work.
>
> I'm probably missing something here, so I'm really curious about what that might be.

Support for bun **as a package manager** would require changes to this utils file: https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/package-manager.ts

Since it is hard coded in the nx package, I'd consider it part of the core. There are a few places that replicate that functionality that we would need to update as well. Since **_bun is experimental software_**, and making these changes would necessitate adding bun to our e2e matrix, no current action is planned. We are watching `bun`, and are hopeful that it can pick up traction and stabilize, but its not stable yet.
