### ISSUE TITLE
[Feature Request] Implement File Replacements

### ISSUE THREAD

**Issue by ahasall** [nrwl/nx#1111]
I am using the the `@nrwl/builders:jest` builder in a **non-nx** Angular workspace.

The official Angular CLI karma builder supports **file replacements** while `@nrwl/builders:jest` doesn't.

Is it something you've considered? If yes, I can try to implement the feature and land my first PR.

Thank you

**Comment by FrozenPandaz** [comment]
Thank you for your enthusiasm to contribute! 👍 

I believe the `karma` runner uses `webpack` to control the replacements since the runner does not have it's own module system.

Jest does have it's own module resolution and I think you might be better off using [`jest.mock(path)`](https://jestjs.io/docs/en/mock-functions#mocking-modules).

Does this solve your issue?

**Comment by ahasall** [comment]
`jest.mock(path)` was not an option for me because I am migrating from Karma to Jest and didn't want to modify the tests (for now).

I have solved the issue but by using `modeNameMapper` in `jest.config.js` like so:
```
moduleNameMapper: {
        "^environments/(.*)$": "<rootDir>/src/environments/environment.testing.ts",
        '(.*)\/environments\/(.*)$': '<rootDir>/src/environments/environment.testing.ts',
}
```

Thank you very much to all the Nrwl team for your time and energy.
