### ISSUE TITLE
@angular/localize not working with module federation + kendoUI

### ISSUE THREAD

**Issue by Vevl** [nrwl/nx#11121]
Hello @Coly010,

Issue [#10182](https://github.com/nrwl/nx/issues/10182) is back after updating to v14 of Angular.

New error message says:
![image](https://user-images.githubusercontent.com/35180926/178682188-a7bd4b39-5a19-4506-8340-e04c5fcf4e40.png)

You can check it by yourself, I updated repo - https://github.com/Vevl/kendo-test

Thanks.

Best regards.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

There's still an issue with the default eager config for `@angular/localize`. I'll push a fix for it. Please note you don't need to configure `@angular/localize/init` to be consumed eagerly. That's already built-in in the provided `withModuleFederation` helper.

To unblock yourself, until the fix is released, please configure `@angular/localize` to be eagerly loaded. The `host` app in your repo would have the `module-federation.config.js` like the following:

```js
module.exports = {
  name: 'host',
  remotes: ['test'],
  shared: (libraryName, libraryOptions) => {
    if (libraryName === '@angular/localize') {
      return {
        ...libraryOptions,
        eager: true,
      };
    }
  },
};
```

**Comment by minijus** [comment]
I am still getting this issue on latest nx version. Could there been changes that affected the previous fix?

**Comment by nayfin** [comment]
We're also seeing this in nx: "14.8.4"
