### ISSUE TITLE
Once pnpm-lock.json changes, all cache are invalidated.

### ISSUE THREAD

**Issue by niudai** [nrwl/nx#11166]
## Current Behavior
I have a pnpm monorepo which I use nx to build all my packages, but I found that when I change the pnpm-lock.json file, even if I only add a blank line, all cache for all projects are invalidated, which triggers rebuild of all.

## Expected Behavior
I never specify `pnpm-lock.json` in my `implicitDependencies` config in nx.json, so I suppose when I change it, it will not invalidate all cache.

I found other files except `pnpm-lock.json`, in which I do not specify in `implicitDependencies` either, they will not invalidate any cache when I change them, unless I specify them in `implicitDependencies`.

Because the pnpm-lock file change very frequently, so this issue makes the cache almost not cacheable.

## Steps to Reproduce
just pick a pnpm repo, and add nx to it.

### Environment
```
Node : 16.4.1
   OS   : darwin x64
   pnpm : 6.32.8
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.2.4
   ---------------------------------------
   Community plugins:
```

**Comment by sbayd** [comment]
+1

**Comment by NavidK0** [comment]
We've run into this as well. I looked into it, and it seems it's just because of `legacyFilesetInputs` located on line 84 of `nx/hasher.ts`. Commenting out `pnpm-lock.yaml` from the `legacyFilesetInputs` gives us the behavior we're looking for. We pin all our dependency versions, so it shouldn't be a problem to exclude the pnpm lock file.

At the moment, we're just using a `pnpm patch` to override that bit of code, but it would be nice to see an option to modify that behavior natively.

**Comment by NavidK0** [comment]
Seems like [release 15.0.0](https://github.com/nrwl/nx/releases/tag/15.0.0) fixed this issue for us. Great work! 🎉

**Comment by NavidK0** [comment]
After trying it out for a week, we've seem to run into this bug which seems related to this problem: https://github.com/nrwl/nx/issues/11055

Unfortunately, we've had to revert to version 14 with the patch we created ([stated here](https://github.com/nrwl/nx/issues/11166#issuecomment-1264499609)) to get the desired behavior (independently cached targets being pulled from our remote cache).

**Comment by meeroslav** [comment]
The change in the lock file would invalidate the cache in the following cases:
- The changed package affects all of the projects (e.g. `nx`)
- The target is run with a custom or ambiguous executor (e.g. `run-commands`)

In the latter case, we don't know what packages your executor depends on, so we pessimistically set everything as affected.

It's not ideal, but it's better than missing a run. 

We are discussing options to add an additional type of input to allow users to explicitly specify what packages these executors depend on. But until then, this behavior is intentional.
