### ISSUE TITLE
Cypress: stop electron test-runner app from closing after a run

### ISSUE THREAD

**Issue by hevans90** [nrwl/nx#1119]
## Expected Behavior

`ng e2e <app-e2e>` should ideally allow the passing of `--no-exit`: [here's the Cypress command](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-no-exit).

## Current Behavior

![image](https://user-images.githubusercontent.com/12142999/53643058-02d0a800-3c2b-11e9-8bd7-07d76f2f5b55.png)

**Comment by FrozenPandaz** [comment]
This would be a great feature :+1: Would someone like to give this a try?

**Comment by yglin** [comment]
Is there any way to stop cypress from closing currently, without upgrading @nrwl/nx ?

I glanced some POST abort error on singing in to google firebase but can not identify it clearly because cypress close immediately after running test.

I tried cypress commands debug() and pause(), no luck, it just runs and closes.
And the only failed record I can found is a screenshot in /dist, no more detail, don't know where to find some more logs.
It's frustrating, I'm sorry if not appropriate to ask here.
