### ISSUE TITLE
Non headless e2e advise needed pls

### ISSUE THREAD

**Issue by paul-hammant** [nrwl/nx#11223]
In page https://github.com/nrwl/nx/blob/master/docs/shared/cypress-plugin.md there is this text:

    "By default, Cypress will run in headless mode."

There's isn't any advice on how to configure or override for headed, or non-headless mode. The documentation would be even better if it had that advice.  Not sure if there i such a mode, but use of the word "default" implies that there is.

Thanks - Paul

**Comment by juristr** [comment]
I think you should be able to just pass `--headed` flag to the command. I can look into updating the docs to highlight that, although that's more of a Cypess thing: https://docs.cypress.io/guides/guides/command-line#cypress-run-headed

But a note in the docs doesn't hurt :)

**Comment by paul-hammant** [comment]
`--headed` works as suggested.  

New problem: the in-house Nx Monorepo has multiple modules that an `e2e`  aspect. Part way though the `-all` invocation it halts. When I ctrl-c I find out that port 4200 was blocked. I'm guessing module-1 e2e is completing but not releasing the localhost-dev socket by stopping that server process. Then module-2 can't start cos it is blocked, but isn't fast failing.  This is OUR problem, most likely. If the in-house dev teams finds that it is not, I'll circle back and make a new issue.

**Comment by barbados-clemens** [comment]
for @nrwl/cypress you can use the --watch flag, or set `watch:true` in the project configuration. 

Docs: https://nx.dev/packages/cypress#watching-for-changes-(headed-mode)

as for your second issue, that is as you mentioned because a port is in use. make sure you're running with `--parallel=false` so each project has time to wait for the port to be released. otherwise, make a different port number for each project.
