### ISSUE TITLE
child tsconfig excludes test.ts instead of test-setup.ts

### ISSUE THREAD

**Issue by pburkindine** [nrwl/nx#1139]
## Expected Behavior

Generated libs' and apps' tsconfig files have
`"exclude": ["src/test.ts", "**/*.spec.ts"]`

instead of
`"exclude": ["src/test-setup.ts", "**/*.spec.ts"]`

Does not appear fixed by:

https://github.com/nrwl/nx/pull/786

**Comment by skydever** [comment]
hi!

I had a short look at it and I think it has to be added [here](https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/application/files/app/tsconfig.json). I can create a PR if it is the case and if it would help @bcabanes? checking the `unitTestRunner` there and decide what to add ...

#768 was only targeting the `tsconfig.spec.json` (before each project had its own `tsconfig.json` due to IDE typings issues), so I guess `exclude` can be removed completely there then too - because `tsconfig.spec.json` is extending `tsconfig.json`. I can include that removal in the PR too.

**Comment by skydever** [comment]
... but this will overwrite the `exclude` from the root `tsconfig.json` as well for the app (in the IDE only?)?

... wanted to mention that too, because I have some performance issues with vscode lately as mentioned in #1152 but still had no time to do more investigation on that 😢 the `tsconfig.json` at the root level has this `"exclude": ["node_modules", "tmp"]` and the app will scan `node_modules` with this change?

**Comment by pburkindine** [comment]
@bcabanes @skydever any update here?

**Comment by vsavkin** [comment]
@FrozenPandaz Hey Jason. Since you are making updates to the cypress setup, could you also take a look a this issue?
