### ISSUE TITLE
pnx what is it used for

### ISSUE THREAD

**Issue by morriswinkler** [nrwl/nx#11462]
### Documentation issue

- [ x] Documentation improvement

https://github.com/nrwl/nx/blob/e8cfa35e8235daf6dbdb8392278e0c6be7feb46b/packages/nx/bin/nx.ts#L68-L82

I can't find any documentation regarding what pnx is used for.
Iit seems nx related, but there is noting in your code base that uses it.

I am wondering if this whole cli warning is just an artefact that is not useful anymore?

**Comment by AgentEnder** [comment]
This warning is only surfaced when executing a globally installed version of Nx with `pnpm`... There are some known issues for that IIRC.

The `pnx` recommendation is just an alias to make your commands shorter, there's not anything that its used for necessarily... It is just you would use it instead of typing out like this: `pnpm nx build app` vs `pnx build app`
