### ISSUE TITLE
`@nrwl/angular:stories` – rename the `name` flag to `project`/`projectName`

### ISSUE THREAD

**Issue by theorlovsky** [nrwl/nx#11466]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, all the other generator (that I'm aware of) specify a project name as `project` or `projectName`, which makes sense. It's obvious what you should pass to it even without reading a flag description. Moreover, some UI plugins ([Nx Console Idea](https://plugins.jetbrains.com/plugin/15101-nx-console-idea) in our case) rely on that names and suggest autocompletion, which is veeery convenient, and which is not happening with just `name`.

## Motivation

Autocompletion ❤️

## Suggested Implementation

Rename `name` to `project` or `projectName`

**Comment by mandarini** [comment]
Hi there @theorlovsky ! Thank you very much for the suggestion. No need to make this change, however! The [`name` is aliased](https://github.com/nrwl/nx/blob/master/packages/storybook/src/generators/configuration/schema.json#L11) to `project` and `projectName` and the dropdown to the UI plugins should be working since last month! Making that change would not be backwards compatible and it could break some custom configurations of people. Since the three keywords can be used interchangeably due to the aliases, there's really no need to make that change! :)

Let me know if this helps, and if you think we should still go ahead with the change, and I will reopen this issue! 


![Screenshot 2022-08-29 at 5 41 30 PM](https://user-images.githubusercontent.com/6603745/187227784-0d07072a-37f8-444b-a345-405e43d1de3a.png)
