### ISSUE TITLE
Cypress component test setup not working with Angular

### ISSUE THREAD

**Issue by bene-starzengruber** [nrwl/nx#11602]
## Current Behavior
When following the steps described at https://nx.dev/packages/cypress with a completely fresh repository one ends up with an error.
There is a separate documentation for component testing but it only features a react package that is not available yet for angular https://nx.dev/cypress/cypress-component-testing.
Calling `cypress open` from the app folder and letting cypress do the job also results in issues.

## Expected Behavior
Component tests work

## Steps to Reproduce
Follow the steps documented at https://nx.dev/packages/cypress

### Failure Logs
`Error: Could not find a project with projectType "application" in "angular.json"`

which makes sense as the `angular.json` now looks like this and the "real" information is in the project.
```
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {
    "one": "apps/one",
    "one-e2e": "apps/one-e2e"
  }
}
```

my `package.json` looks like this
```
"dependencies": {
    "@angular/animations": "~14.1.1",
    "@angular/common": "~14.1.1",
    "@angular/compiler": "~14.1.1",
    "@angular/core": "~14.1.1",
    "@angular/forms": "~14.1.1",
    "@angular/platform-browser": "~14.1.1",
    "@angular/platform-browser-dynamic": "~14.1.1",
    "@angular/router": "~14.1.1",
    "@nrwl/angular": "14.5.6",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.1.1",
    "@angular-eslint/eslint-plugin": "~14.0.0",
    "@angular-eslint/eslint-plugin-template": "~14.0.0",
    "@angular-eslint/template-parser": "~14.0.0",
    "@angular/cli": "~14.1.0",
    "@angular/compiler-cli": "~14.1.1",
    "@angular/language-service": "~14.1.1",
    "@nrwl/cli": "14.5.6",
    "@nrwl/cypress": "14.5.6",
    "@nrwl/eslint-plugin-nx": "14.5.6",
    "@nrwl/jest": "14.5.6",
    "@nrwl/linter": "14.5.6",
    "@nrwl/workspace": "14.5.6",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "cypress": "^10.2.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.5.1",
    "jest-preset-angular": "~11.1.2",
    "nx": "14.5.6",
    "prettier": "^2.6.2",
    "ts-jest": "27.1.4",
    "ts-node": "10.9.1",
    "typescript": "~4.7.2"
  }

```

**Comment by yusijs** [comment]
Just wanted to add a bit here:

There is a generator in nx called `@nrwl/cypress:cypress-component-project`. When running this generator it creates all the config files etc in my projects, but I'm not able to actually run any tests, as it will always fail with the error below:

```
ERROR in polyfills
Module not found: Error: Can't resolve '/Users/ronnie/dev/my-project/client/apps/recon/apps/landing/src/polyfills.ts' in '/Users/ronnie/dev/my-project/client/apps/recon'
```

For some reason it looks like it's trying to include files that are *not* part of the project, but it looks from the root and tries to find every single .ts file. The reason seems to be something to do with the tsconfig.json file in the projects, as cypress is not using the tsconfig.cy.json file, but rather the tsconfig.json file. I've tried messing around in multiple ways to get component testing to work, but I was not able to make it work within the nx framework

Running the tests ends up like this:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/11261560/185109088-0820dc7e-2382-4d97-9ffd-679fac502d28.png">

**Comment by FrozenPandaz** [comment]
Just as an update, we are working on this with the Cypress team. :smile:

Stay tuned for updates.

**Comment by bene-starzengruber** [comment]
I still have this issue with a brand new setup of nx 14.7.5

![image](https://user-images.githubusercontent.com/18653151/189934922-c9136b47-9e65-4167-aa4d-bce7f3ae38b8.png)

**Comment by barbados-clemens** [comment]
@bene-starzengruber You have to run via the nx executors for cypress component + nx to work. There is [a generator to setup](https://nx.dev/packages/angular/generators/cypress-component-configuration) the project you want to add component testing. 
`nx g cypress-component-configuration --project=<project-name>`


it does look like you're on windows, so there is a [bug with paths that just got merged](https://github.com/nrwl/nx/commit/1a9df531b643a30616571797ef24c923144d634c) and should be released soon.

**Comment by yusijs** [comment]
There are still a few issues with the setup here:
* You pass in tsconfig.app.json from project.json, and tsconfig.app.json excludes cy.* files (i.e exclude them from compilation). Should probably use tsconfig.cy.json (I sent a PR to the cypress project which is merged to account for tsconfig files). Without it the angular webpack compilation process fails because the files are excluded
  * Can be overridden in the result from `nxComponentTestingPreset`
  * `options.devServer.options.projectConfig.buildOptions.tsConfig = '../../apps/my-app/cypress/tsconfig.cy.json';`
* Seems like it fails to compile sass-files. I've verified that you send in stylePreprocessorOptions to cypress, but I still get build failures with `SassError: Can't find stylesheet to import.` for all files in node_modules (works fine in build/serve)

@barbados-clemens should I create a separate bug for these items?

**Comment by basti-n** [comment]
+1 on that issue. Either I have misunderstood how to ensure the scss files are added to the base paths.
So is this still an issue from nx or cypress side? 

```javascript
        "stylePreprocessorOptions": {
          "includePaths": ["libs/shared/ui/src/lib/styles"] // aka the path where my scss files reside
        },
```

Still, when running the test I get an error.

```
Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @use 'styleguide' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by barbados-clemens** [comment]
@basti-n make sure you're on nx latest as there was an upstream change with cypress v10.8.0 that caused issue with tsconfigs on our side. should be fixed in latest but if not please open a new issue so I can take a look

**Comment by basti-n** [comment]
@barbados-clemens I am running v10.8.0 , I created a minimal repro project (https://github.com/basti-n/cypress-component-test)
Run `npm run test-cmp` to run the component tests.


```
 >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin x64
   npm  : 8.15.0

   nx : 14.7.13
   @nrwl/angular : 14.7.13
   @nrwl/cypress : 14.7.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : 14.7.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.13
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.13
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
@basti-n Can you open a separate issue since this is a different setup/error that the initial issue?
