### ISSUE TITLE
Cypress 10 is not overwriting the baseUrl property defined in the cypress.config.ts

### ISSUE THREAD

**Issue by gerardcastell** [nrwl/nx#11662]
## Current Behavior

Applying baseUrl porperty to "cypress.config.ts" is not being applied. It seems like Nx dev server is the one used and overwrites this behaviour. 
In previous version of Cypress (<10) and Nx (<14) this did not happen, so this is a regression.

## Expected Behavior

What we expect is that if we define a new baseUrl when we used the cy.visit('/') and the cy.request(...) use such a baseUrl.

## Steps to Reproduce
I have created a new repository to emulate the error, found it [here](https://github.com/gerardcastell/nx-cypress-broken-url).
If you look at the cypress.config.ts of the "checkout-e2e" application you will find the following code:
`import { defineConfig } from 'cypress';
import { nxE2EPreset } from '@nrwl/cypress/plugins/cypress-preset';

export default defineConfig({
  e2e: { ...nxE2EPreset(__dirname), baseUrl: 'http://localhost:4200' },
});
`
where the baseUrl property is overwritten to point to the port 4200 of the localhost. If you run:
`nx e2e checkout-e2e --watch`
you may see how the opened url by the cy.visit('/') command is "http://localhost:4201".

The reason because I need this behaviour is that in my company we use microfrontends and I serve the whole app wired up in another port different that the one from the Microfrontend that we test so we need to visit that url to test the whole e2e flow.
### Failure Logs

<img width="1017" alt="Screenshot 2022-08-22 at 13 12 02" src="https://user-images.githubusercontent.com/25346175/185907866-f8e503ab-e4c8-4469-9dd3-23004277cf8a.png">

### Environment

Node : 14.18.1
   OS   : darwin x64
   npm  : 6.14.15
   
   nx : 14.5.4
   @nrwl/angular : 14.5.4
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by puku0x** [comment]
Using `baseUrl` in `project.json` is a workaround.

```js
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/my-app-e2e/src",
  "projectType": "application",
  "targets": {
    "e2e": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "baseUrl": "http://localhost:4201",
        "cypressConfig": "apps/my-app-e2e/cypress.config.ts",
        "devServerTarget": "my-app:serve:development",
        "testingType": "e2e"
      },
      "configurations": {
        "production": {
          "devServerTarget": "my-app:serve:production"
        }
      }
    },
  :
}
```

**Comment by gerardcastell** [comment]
Thank you! I have found that setting it in the setupNodeEvents it works as well:
` setupNodeEvents(on, config) {
      config.baseUrl = 'http://localhost:4200';
      return config;
    }`
    Nevertheless, the previous behaviour is lost and the official Cypress documentation still encourage to do like that, so I guess something is broken in the @nrwl/cypress executor.

**Comment by barbados-clemens** [comment]
Just glancing at this before taking off for the day so might miss something.

but this behavior makes sense to me, because the way the cypress executor works is 

if you have a [`devServerTarget` -> run it and return the baseUrl from the executor options or running dev server](https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L168). Then that value will be [passed to Cypress.open/run](https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L53)

Maybe Cypress change logic in how it loads the baseUrl from the config? I doubt it since storybook + cypress testing would be broken (presumably) since it uses the [`baseUrl` in the config](https://github.com/nrwl/nx/blob/master/packages/storybook/presets/cypress.ts#L6)

That leads me to think that this is a MFE related.

I'm not super versed in how the MFE stuff works under the hood. but looking at the configurations in `project.json` for the app. it makes total sense that the url is port 4201 and not 4200 because the [config says 4201](https://github.com/gerardcastell/nx-cypress-broken-url/blob/main/apps/checkout/project.json#L72) which is where cypress executor is getting it from.

Because if I run that target `checkout:serve:development` it will only be listening on port 4201 and nothing is on 4200 and that's what you told `@nrwl/cypress:cypress` to do. Run this target and that target listens on port 4201 so that's where it'll listen and if you want to change what `@nrwl/cypress:cypress` is doing, then you'll need to use the project.json to control it. 

not saying this isn't worth discussing more, but so far everything checks out with why things are behaving like they are.

Let me know if something doesn't make sense or I missed something.
