### ISSUE TITLE
Migration to Cypress 10 causes tests to fail after the fact

### ISSUE THREAD

**Issue by Chowarmaan** [nrwl/nx#11802]
## Current Behavior

Using my existing project, with Cypress 9.7.0 has the test files called app.spec.ts.  Running the `nx g @nrwl/cypress:migrate-to-cypress-10` completes successfully.  Attempting to run the tests however, errors out with:

    Can't run because no spec files were found.
    We searched for specs matching this glob pattern:
    > ui-e2e\src\e2e\**\*.cy.{js,jsx,ts,tsx}

The issue is the test files are still called `*.spec.ts`, while the new Cypress configuration is looking for `*.cy.ts`.  The pathing has also changed to require the test files in an e2e subdirectory (`src/e2e/` instead of `src/`).

## Expected Behavior

The configuration should support the `*.spec.ts` file specifications, or renaming the test files in the project accordingly including the new path change.

## Steps to Reproduce

Take a project with the Cypress 9.7.x, and then run the `nx g @nrwl/cypress:migrate-to-cypress-10`. When this is done, try to run the e2e test `nx e2e ui-e2e` and the error will occur.

### Environment

   Node : 18.5.0
   OS   : win32 x64
   npm  : 8.12.1

   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : 14.5.10
   @nrwl/next : Not Found
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.26.0

**Comment by barbados-clemens** [comment]
hmmm the migration should have renamed the files from .spec. to .cy.

unsure about the import part as that is for importing anything that was in 
src/integration/index.ts => src/e2e/e2e.ts so might have had an issue there I'm not expecting

do you have a repo I can look at?

**Comment by Chowarmaan** [comment]
Let me create a base one.  Maybe my source files were in the wrong place?  
[timesheet-ui-e2e.zip](https://github.com/nrwl/nx/files/9463370/timesheet-ui-e2e.zip)

**Comment by barbados-clemens** [comment]
@Chowarmaan csn you please make a clone-able repository

**Comment by Chowarmaan** [comment]
I have emptied out the application, and have a basic environment available to show the issue [on GitHub](https://github.com/Chowarmaan/cypress-migrate-11802)

**Comment by robinpellegrims** [comment]
I had the same issue on a Windows machine. In my case it seems to be caused by the [visitNotIgnoredFiles](https://github.com/nrwl/nx/blob/306d8a4cecb431ee3d770ef9c734bd5cb3111114/packages/cypress/src/generators/migrate-to-cypress-ten/conversion.util.ts#L232) function passing a path with backslashes to the visitor function (because of how [path.join](https://github.com/nrwl/nx/blob/306d8a4cecb431ee3d770ef9c734bd5cb3111114/packages/devkit/src/generators/visit-not-ignored-files.ts#L23) behaves on Windows?).
The visitor function will then fail to execute the file renames since the backslashed [path doesn't contain the `oldIntegrationFolder`](https://github.com/nrwl/nx/blob/306d8a4cecb431ee3d770ef9c734bd5cb3111114/packages/cypress/src/generators/migrate-to-cypress-ten/conversion.util.ts#L233) path (in forward slash format).

I worked around it by executing the migration in a Ubuntu terminal using WSL and this worked just fine.

**Comment by Chowarmaan** [comment]
Good to know.  I use the Git Bash shell on Windows, which while it works for most things, had the issue here.  I will look to try the Ubuntu WSL for future migrations until this is addressed.

**Comment by barbados-clemens** [comment]
thanks for the pointing out the trouble areas @robinpellegrims 
have a PR to address this issue.
