### ISSUE TITLE
Guides > Environment Variables page 404

### ISSUE THREAD

**Issue by tonymamo** [nrwl/nx#11804]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Getting a 404 on the following page, the number 1 search result for `nx environment variables`
https://nx.dev/guides/environment-variables

**Comment by barbados-clemens** [comment]
the valid URL is https://nx.dev/reference/environment-variables
and when I search I'm seeing the first result redirect to that url as well.

Wonder if it's a cache issue since the docs were restructured recently?


https://user-images.githubusercontent.com/23272162/187715537-8246e29d-5f98-4380-9148-bfafe7c2cec0.mp4

**Comment by tonymamo** [comment]
@barbados-clemens sorry meant to say first result *when searching on google*. I tried multiple browsers, including one that I know for sure I have never visited the website with. I can indeed see the same page as in the video

**Comment by mrlubos** [comment]
Huh, maybe they moved the docs. There should've been at least a redirect though or some note, ran into a similar issue earlier https://github.com/nrwl/nx/issues/11839
