### ISSUE TITLE
Optimize e2e web servers

### ISSUE THREAD

**Issue by oschlegel** [nrwl/nx#11827]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
It should be possible for executors to specify "before all" and "after all" hooks, which are executed once before / after running a executor for projects with `nx run-many` and `nx affected` commands.

## Motivation
My usecase is that i have a executor to run playwright tests for a project, which requires a dev server to be started before running tests. At the moment the dev server is started each time the executor is running. It would be i nice optimization if the dev server could be started once and the reused for all playwright tests. This is just one example of many where some kind of set up or tear down logic which can be done once accros all executions

**Comment by FrozenPandaz** [comment]
This is an issue for our `Cypress` implementation as well.
cc @barbados-clemens 

I think this discussion should be focused on e2e test kind of implementations rather than a generic lifecycle design.

The easiest way to optimize this right now is to implement a `serve-static` target which will run the application in a way where it is able to reuse the cached build of the application...

So if you run

```sh
nx build app1 # this builds the app and caches it
nx e2e app1-feature-a-e2e # This will switch the `devServerTarget` to `serve-static` which will use the cache starting it instantly.
nx e2e app1-feature-b-e2e # This also use the cache to start the tests immediately.
```

**Comment by wrslatz** [comment]
Cross-posting related issues / discussions
https://github.com/nrwl/nx/issues/6835
https://github.com/nrwl/nx/issues/5570
https://github.com/nrwl/nx/discussions/7668

**Comment by barbados-clemens** [comment]
Will be tracking this in our 'serve-static' work that should be worked on in the coming months.
