### ISSUE TITLE
Ivy support: workaround or solution for path mapping

### ISSUE THREAD

**Issue by dirkluijk** [nrwl/nx#1189]
We use a project layout based on Nx Workspaces. It seems that there is an issue with path mapping when using the Angular 8 Ivy preview.

Please see https://github.com/angular/angular/issues/29361 for more information.
I thought it might be good to report it here as well.

**Comment by FrozenPandaz** [comment]
According to that issue, it's a bug in the ivy compiler so there's not much we can do but wait.

**Comment by alxhub** [comment]
@FrozenPandaz (hey man!) I wouldn't say it's a bug. There are essential design questions that are unanswered, and we (Angular and nx teams) should probably sync on it sometime. Let's talk on Slack.

**Comment by dirkluijk** [comment]
The suggested solution is that you can perfectly use path mapping, as long as you don't use barrel files like I did.

Nx does not advocate the use of barrel files, so I don't think there is currently an issue at this moment.

**Comment by alxhub** [comment]
@dirkluijk I actually think this isn't the case. Our compiler still won't know how to write imports to your pathmapped project files, because it doesn't know whether to assume that the module specifier by which you imported the NgModule should be reused for components (as with the APF case) or should be adjusted to point to the components directly (monorepo application case). Today, I believe we'll fail to generate an import at all.

**Comment by dirkluijk** [comment]
Thanks @alxhub. My mistake, I didn't yet understand it completely. I'll investigate the situation.

Reopened this issue.

**Comment by vsavkin** [comment]
We fixed all the known Ivy-related issues some time ago, so I'm going to close this issue. If you still has problems, please reopen the issue with a repro. Thank you!
