### ISSUE TITLE
angular.json is re-formatted with each update

### ISSUE THREAD

**Issue by LPCmedia** [nrwl/nx#11965]
## Current Behavior

When running `nx migrate latest `  some files such as angular.json are reformatted but no actual changes are applied. 
From one version to another, the format seems to vary. This makes it difficult to track real changes to the file. 

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/5975736/189468923-71988b8b-66f6-4dae-84b5-17bd98e86a89.png">

## Expected Behavior
Don't change my files if there are no changes.

**Comment by DaSchTour** [comment]
I've also observed this problem with tsconfig and others. I think that migrate or creation of new libraries should run format:write.

**Comment by Coly010** [comment]
Creation of New Libraries does run `format` unless stated otherwise by the developer running the generation.

Nx Migrate will not run `format` unless required by any particular migration.

Unfortunately, this occurs because of the adapter layer between Nx and Angular. We need to convert from Nx Workspace Configuration format to Angular Workspace Configuration format and vice versa when running Angular and Nx migrations. This means that there can be some formatting or whitespace differences, coming from `JSON.stringify`.
