### ISSUE TITLE
Superfluous dependency populated in dist package.json

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#11990]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

We have a library with multiple sub-entry points, in one of these sub-entry points,  **in a spec file**, there's the following import declared: 

```ts
import { CommonModule } from '@angular/common';
```

The problem is that when we build the library using `@nrwl/angular:package`, the dependency `@angular/common` is added in the peerDependencies of the distribution package.json with a fixed version, even if it's only declared in a test file. Here is the produced dist package.json:

```jsonc
"peerDependencies": {
  "@angular/core": ">=12.0.0",
  "@angular/platform-browser": ">=12.0.0",
  "@rx-angular/cdk": ">=1.0.0-beta.2",
  "rxjs": ">=6.5.5",
  "@angular/common": "12.2.16" // <- resolved from the spec file import
}
```

Here is the [spec file in question](https://github.com/rx-angular/rx-angular/blob/9ebbe9ac76bcf569f41561a9dc021d2f14fc1777/libs/template/for/src/lib/tests/for.directive.observable.spec.ts#L1), if I remove the reference to the `CommonModule` in the spec file and I rebuild, peerDependencies are not populated with this superfluous dep.

It seems like the builder `@nrwl/angular:package` is not excluding spec files as it is defined in the `tsconfig.lib.json` when `updateBuildableProjectDepsInPackageJson` is true:

```json
"exclude": ["src/test-setup.ts", "**/*.spec.ts", "**/*.test.ts"]
```

This is producing a warning for our users:

```
template has incorrect peerDependecy for @angular/common = 12.2.16
```

#### How To Reproduce

1. clone https://github.com/rx-angular/rx-angular
2. yarn install
3. run `nx build template`
4. see that dist/libs/template/package.json is populated with `@angular/common`
5. removing the `CommonModule` declaration in [the spec file](https://github.com/rx-angular/rx-angular/blob/9ebbe9ac76bcf569f41561a9dc021d2f14fc1777/libs/template/for/src/lib/tests/for.directive.observable.spec.ts#L1) also removes it from the dist package.json

#### Expected Behaviour

Modules imported in spec files should not be taken into account when populating distribution peer dependencies.

#### Version Information

```
  Node : 16.16.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : 12.10.1
  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.1
  @nrwl/nx-cloud : 13.1.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by minijus** [comment]
I recently noticed that having `updateBuildableProjectDepsInPackageJson` enabled generates huge list of (peer)Dependencies in built package.json file.
This became problem in our repo. One of auto added dependencies was `fsevents` (I am building on Mac), which does not work (fails on install due to unsupported platform) on Linux. Strangely many (almost all) of automatically added dependencies were never used/imported into package buing build directly.

**Comment by gpiumatti** [comment]
I'm having the same issue with projects built with `@nrwl/js:tsc`. Dependencies that are only imported in `.spec.ts` files are included in the generated `package.json` (using Nx 15.0.13).
Might also be similar to #11293.

Is this something that will be addressed?

**Comment by edbzn** [comment]
It appears that the function responsible for this behavior is [`addMissingDependencies`](https://github.com/nrwl/nx/blob/35750280552350477bc347bc2ce962f5463719d8/packages/js/src/utils/package-json/update-package-json.ts#L101), it is taking all npm dependencies detected by Nx (cf: [`ProjectGraphExternalNode`](https://github.com/nrwl/nx/blob/35750280552350477bc347bc2ce962f5463719d8/packages/nx/src/config/project-graph.ts#L90)) for a given project and populate them in the dist package.json.

I think there's a conceptual piece missing here, we would need to copy only dependencies that are actually used by the application at runtime, taking into account what `ts.config.app.json` includes and excludes. I quickly tried to draft something, but could not find a clean way of filtering npm dependencies based on this.

If someone from the Nx team could guide me on a way of doing it, I would be happy to contribute.

**Comment by AgentEnder** [comment]
This may actually be fixed! https://github.com/nrwl/nx/pull/13966 reads like it should have addressed the issue. Can you check in v15.9.0-rc.1?

**Comment by gpiumatti** [comment]
@AgentEnder does not seem to fix it for me (using Nx 15.9.2). 
In my case, I have a package in the monorepo where I implement some utilities for testing.
A second package in the same monorepo uses the first package in .spec.ts files only.
Building the second package includes a dependency to the first in the generated package.json.

The tsconfig files are as follows: 
- tsconfig.json with references to tsconfig.lib.json and tsconfig.spec.json
- tsconfig.lib.json includes all .ts files and excludes .spec.ts files
- tsconfig.spec.json includes .spec.ts files
- both tsconfig.lib.json and tsconfig.spec.json extend tsconfig.json (this is the default layout generated by Nx, although it was generated a while back with a different version of Nx).

In project.json "build" configuration (using @nwrl/js:tsc executor) I point to the tsconfig.lib.json file.

**Comment by Norby125** [comment]
My issue is slightly different, but I guess the root cause is the same. Let me know if I should open a new issue instead of putting it here.

I've upgraded my angular NX based application from 13 to 15. I have a publishable library with a storybook. After packaging, it suddenly started to add "@storybook/addon-docs" as a peer dependency. I could narrow down the root cause to "@nrwl/angular" package. 14.8.5 does not have this problem, but 15.0.0 started to produce the issue. Please note that It works fine if I'm using "@angular-devkit/build-angular:ng-packagr" executor, therefore my assumption was that the executor seems to have some logic that gathers the "missing" dependencies.

"updateBuildableProjectDepsInPackageJson" flag for the "@nrwl/angular:package" executor does it, but it seems it gets carried away looking at folders/files that suppose to be excluded from the packaging process. Regardless these files are specs/stories. For now, I had to turn this off.

Repro steps are straightforward, just need the latest NX with a publishable library that has the storybook configured and make an import in preview.js (or any other js file) like this: "import { setCompodocJson } from '@storybook/addon-docs/angular';"

**Comment by tommyk** [comment]
this is certainly happening to me as well. i am commenting to keep this from going stale.

if you are creating packages to be published and used elsewhere this is kind of a breaking issue.  i can try and work on a simple repo / steps to make this easier to debug if that helps.
