### ISSUE TITLE
ESLint: ENOENT: no such file or directory when referencing the secondary entry point

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#12067]
Hi,

i have structure like this:

```
/libA                        
  /src
    /liba.module.ts
 /core
   /src
     /lib
        /models.ts
```

- LibA is primary entry point
- Core is secondary entry point

Everything is generated by NX schematics - @nrwl/angular:library and @nrwl/angular:library-secondary-entry-point so all files are generated correctly. 

However, i would like to import  models.ts and use it in libA.module.ts. But there is a problem... 

When i import by generated path:
`import { Something } from "@libA/core";`

I got:
```
Error: ENOENT: no such file or directory, open 'libs/libsA/src/index.ts'
Occurred while linting ....
Rule: "@nrwl/nx/enforce-module-boundaries"
```
But everything is building fine 

-----------------

. When i change to relative path:
`import { Something } from "../../core/src";`

Lint error is gone, however i cannot build, because
"is not under 'rootDir'" error.

How should we import Secondary-entry-point files withing primary-entry-point files ? (under liba/src/lib) ?

**Comment by FrozenPandaz** [comment]
Can you please provide a repo where we can see the issue?

**Comment by montella1507** [comment]
Of course! 
[eslint.zip](https://github.com/nrwl/nx/files/9638636/eslint.zip)

**Comment by montella1507** [comment]
All was generated automatically just with your schematics. No manual work there.

**Comment by Samuel-Beslogic** [comment]
@nrwl/nx/enforce-module-boundaries crashes ESLint for me as well when there's a relative import.

**Comment by montella1507** [comment]
I can't build the solution when there is relative import (aka ../../core/...) because "is not under rootDir" error mentioned above. 

We had to disable @nrwl/nx/enforce-module-boundaries linting and use "namespace imports" @lib/core ..

**Comment by vojtesaak** [comment]
I have this issue as well.

**Comment by vojtesaak** [comment]
Could you please remove `blocked: repro needed` label as there si reproduction available [here](https://github.com/nrwl/nx/issues/12067#issuecomment-1256952758) ?

**Comment by vojtesaak** [comment]
It seems this is a regression since it has been working in previous versions of nx. 

I created a fork from https://github.com/kauppfbi/kauppfbi-blogs where I replicated issue

Here is the working [example](https://github.com/vojtesaak/secondary-entrypoints-bug/blob/main/libs/shared/greeter/src/lib/simple-greeter/simple-greeter.module.ts#L5) without an error. (nx13)

<img width="728" alt="Screenshot 2022-10-11 at 9 26 40" src="https://user-images.githubusercontent.com/5442796/195023129-6ee5786c-626d-4f6b-8a19-9eda4077b2ff.png">








Here is the same code with the latest version of nx which reproduces [issue](https://github.com/vojtesaak/secondary-entrypoints-bug/blob/ng14/libs/shared/greeter/src/lib/simple-greeter/simple-greeter.module.ts)

<img width="776" alt="Screenshot 2022-10-11 at 9 29 28" src="https://user-images.githubusercontent.com/5442796/195023698-fb5fc468-f46e-456d-9ee9-c6e9c5cb9e82.png">

**Comment by montella1507** [comment]
I believe this issue should be escalated to higher priority as far as it is one of the "selling points" of NX.

**Comment by meeroslav** [comment]
We will look into it as soon as possible. Sorry to keep you all waiting.

**Comment by meeroslav** [comment]
Hmm... The reproduction zip contains out-of-sync package.json and package-lock.json.
Running `npm install` and then `npx nx run-many --target=lint --all` shows no error. 
The same goes for VSCode, so this error is only shown in WebStorm.

The repo is not a result of **only** scaffolding and changing import scopes according to `nx.json` (where npm scope is set to `eslint`) fixed the issue. The problem however is in the fact that WebStorm runs ESLint with a working directory different than the workspace root, so paths are not recognizable.

I'll try to create a fix as soon as possible.
