### ISSUE TITLE
[Feature] Cypress builder should watch fixtures 

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#1207]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

The cypress builder should watch file changes within the `fixtures` directory.

## Current Behavior

The cypress builder [does not](https://github.com/nrwl/nx/blob/5e470ca42f5b3327974a3b161bef1a748995e05a/packages/builders/src/cypress/cypress.builder.ts#L165-L177) watch file changes within the `fixtures` directory.

**Comment by gcirone** [comment]
Very important feature in watch mode. I tried to point direct the fixture folder from cypress.json but the logic inside the builder don't support that.

**Comment by TekSiDoT** [comment]
I've done some investigating into this issue, here's what I found so far:

* The nx/cypress builder is initally copying fixture files to the respective cypress `out` folder 
* The builder is not watching the files itself, the only watching right now is done by the Angular Dev Server.
* Since the fixtures are located outside of the related Angular project, modifying these files will not trigger the dev server rebuild. Even if it did, it would not copy the modified files.
* Therefore, fixtures are only copied once during the initial build.

Possible approaches for this feature:

1. Extending the nx/cypress builder to
   * accept (multiple) folder references to watch
   * watch these folders (using [chokidar](https://github.com/paulmillr/chokidar)?)
   * implement the context.reportRunning() method of the architect
   * re-trigger a cypress run (using [cypress-watch-and-reload](https://github.com/bahmutov/cypress-watch-and-reload)?)

2. Alternatively, you could probably implement this feature as a cypress plugin
   * Start with [cypress-watch-and-reload](https://github.com/bahmutov/cypress-watch-and-reload).
   * Extend it to accept additional commands ( like `copy x to y`) to be performed on changes.

While I'd be willing to attempt either approach, I'm leaning towards the second option as it does seem to be a little more straight forward and not as much effort.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
