### ISSUE TITLE
Have a command to list available targets

### ISSUE THREAD

**Issue by jonathanmorley** [nrwl/nx#12123]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Have an `nx targets` command that would list the targets in a workspace

## Motivation

The list of available targets is not necessarily obvious, especially if you have plugins that are dynamically adding targets to projects.

## Suggested Implementation

See #11745

**Comment by FrozenPandaz** [comment]
In what situations do you find yourself needing to search for the available targets?

Is it in preparation to run a target on a single project? Is it in preparation to use `affected`/`run-many` to run many projects?

**Comment by fvsch** [comment]
I have a similar need.

My use case: I’m coming into a repo that was set up using Nx, and which has only a handful of projects, but there are no docs in the root `README.md` and only a few scripts in `package.json` to tell me what I can run.

In a classic Node-based project, by convention the scripts in `package.json` kinda give you an overview of what different manual and/or automated tasks are involved in contributing to the repository. Docs are better of course, but sometimes docs are lacking our outdated, and the package.json scripts are a more up-to-date source of truth.

In a project managed by Nx, since the Nx way seems to have all your development tasks (build, lint, serve, etc.) for each project go through Nx, I’m really missing this "overview of configured tasks".

Thinking about how `npm run`, `yarn run` and `pnpn run` all print a list of scripts, I tried:

```sh
# Prints usage info
nx run

# Same, prints usage info
nx run --project some-project
```

Okay maybe some of the other commands might do it?

```sh
# Lists Nx plugins, not projects or targets from projects
nx list

# Lists projects, maybe we're getting somewhere?
nx show projects

# Let's try listing targets from a project?
nx show my-project # nope
nx show project my-project # still no
```

And after all this trial and error, a search sends me to this issue :)

Personally, I'd like it if `nx run` showed a list of projects and their targets, or gave information on how to do that.

Maybe it should be a part of the `nx show` command, since this already exists and doesn't do much currently (only supports `nx show projects` so far)?
