### ISSUE TITLE
Angular host app fails on 'extract-i18n' with added remotes

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#12312]
## Current Behavior
Using `extract-i18n` on host Angular application it fails with following error:
```
./apps/mf-host/src/app/app.module.ts:19:36-70 - Error: Module not found: Error: Can't resolve 'remotes-mf-remote/Module' in '/projects/mf-localize-demo/apps/mf-host/src/app'

./apps/mf-host/src/app/app.module.ts:23:36-71 - Error: Module not found: Error: Can't resolve 'remotes-mf-remote2/Module' in '/projects/mf-localize-demo/apps/mf-host/src/app'

```

## Expected Behavior
It should be possible to use `extract-i18n` on host apps that have remote apps included.

## Steps to Reproduce
Repo with reproduction: https://github.com/minijus/mf-localize-demo
```bash
npx nx run mf-host:extract-i18n
```

### Environment
```

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 14.8.1
   @nrwl/angular : 14.8.1
   @nrwl/cypress : 14.8.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.1
   @nrwl/eslint-plugin-nx : 14.8.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.1
   @nrwl/js : 14.8.1
   @nrwl/linter : 14.8.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.1
   @nrwl/web : Not Found
   @nrwl/workspace : 14.8.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:


```

**Comment by Coly010** [comment]
Unfortunately, this one will have to use only the workaround listed above.

Module Federation loads the remotes at runtime, and the webpack plugin for Module Federation tells the build to ignore those imports at build time, ensuring they will be available at runtime.

Because of this, the `extract-i18n` cannot follow those paths to extract translations because they theoretically don't exist at build time.

This is fine. In fact, in this scenario, those remote applications should like have their own translations and use their own `extract-i18n` to create separate bundles of the remote application with their own translations. Then at runtime, the host app can load the remote bundle with the correct translations in place.

e.g.

Let's say you have a set of DE and FR translations.

this would mean you would have

host-de, host-fr
remote-de, remote-fr

At runtime, `host-de` should attempt to fetch the `remote-de`.

This is due to the technical constraint on how Module Federation builds applications. There isn't much more we can do at this moment other than the workaround mentioned above: https://github.com/nrwl/nx/issues/12312#issuecomment-1265513925

I'm going to close this issue for now. But if I have any further brainwaves, I'll revisit it.

Thanks @minijus for raising this and providing the workaround!
