### ISSUE TITLE
Lint affected doesn't work after 14.2.2 => 14.8.3 migration

### ISSUE THREAD

**Issue by anthodb** [nrwl/nx#12438]
Referring to this issue which is now closed : 
https://github.com/nrwl/nx/issues/10768

Unfortunately this problem doesn't seem to be resolved in NX 14.8.3. 
I thinks this should be re-opened.
It was working nicely before the migration from 14.2.2 to 14.8.3
I'm using "lint-staged" as this and never had issues

```
"lint-staged": {
    "*": [
      "nx format:write",
      "nx affected --target=lint"
]
}
```

My lint executor is this
```
"lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/my-custom-app/**/*.{ts,tsx,js,jsx}"]
      }
    }
```

The result of npx lint-staged fails with this message : 
```

Error: Nx no longer supports using positional arguments for base and head. Please use --base and --head instead
````

Using the logs I see that it's appending file paths to the final command, which is probably leading to the error.
```
nx affected --target=lint --verbose --skip-nx-cache "/Users/anthodb/......cypress.config.ts" "/Users/anthodb/...."
```

Do you have a solution for this or do we need to rollback to be able to use affected commands in lint-staged?

**Comment by meeroslav** [comment]
This is the code that is responsible for your error:
```Typescript
    if (
      !nxArgs.files &&
      !nxArgs.uncommitted &&
      !nxArgs.untracked &&
      !nxArgs.base &&
      !nxArgs.head &&
      !nxArgs.all &&
      overridesFromMainArgs._ &&
      overridesFromMainArgs._.length >= 2
    ) {
      throw new Error(
        `Nx no longer supports using positional arguments for base and head. Please use --base and --head instead.`
      );
    }
```

Please note that ALL Nx targets run on the level of the projects, meaning that regardless of the files you provide `nx affected --target=lint` will still lint the entire project containing those files. This is because, despite false assumptions, changes in one file CAN influence the linting of another.

The given `lint-staged` configuration can be replaced with the following:
```
npx nx format:write --umcommitted
npx nx affected --target=lint --uncommitted
```

By using lint-staged you are just adding one additional layer on top of the Nx, which does help reduce the amount of work.
