### ISSUE TITLE
@nrwl/nest build generates no package.json despite using the "generatePackageJson" option

### ISSUE THREAD

**Issue by Zeilar** [nrwl/nx#12462]
## Current Behavior
When running the shipped build script, it doesn't include the required dependencies. It only lists `tslib` in there, and thus the app crashes when trying to run it outside of my local node_modules context.

## Steps to Reproduce
Generating a Nest app using the `@nrwl/nest` library. I tried with some changes to project.json and a completely untouched default generated app, both produce the problem.

### Environment
Windows 10.

**Comment by Zeilar** [comment]
Apologies for changing the issue a bit, I'm trying to resolve this as I'm typing this.

**Comment by Zeilar** [comment]
Did some interesting discovery. When changing the name of the folder, and its project name, from `api` to anything else (tried with `core` and `test`) it suddenly works. Rename the very same folder back to `api` and it goes back to only listing `tslib` in the build dependencies.

**Comment by nartc** [comment]
Hi @Zeilar, thank you for reporting. However, I couldn't reproduce the issue.

Here's my generated `package.json` for `api`
<img width="607" alt="image" src="https://user-images.githubusercontent.com/25516557/194986914-8e75a244-92a7-470c-a5ca-0d6826f6778f.png">

Here's my terminal running `node main.js`
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/25516557/194986908-d5b0ebcd-c49e-45dc-b844-6757e5e23d39.png">

Can you try again with the latest version of Nx? If the problem persists, can you provide a reproduce repo? Also, if you have access to Linux/Mac, can you try on those OSes as well (since I saw you listed your OS as Windows)

**Comment by Zeilar** [comment]
Thanks for looking into it. I got it to work by changing the project name from "api" to anything else. I tried `nx reset` and deleting node_moduels, yet whenever I named the project "api" it would only generate the "tslib" dependency in package.json.

**Comment by jhonny9550** [comment]
I updated NX to its latest version, currently `14.8.4` and works now for me.

**Comment by Zeilar** [comment]
Glad that I wasn't going insane! I suppose this won't be an issue in the future where I would use the newer version instead by default. Still very strange issue.
