### ISSUE TITLE
Local workspace-generator does not work after update to nx@15.0.0

### ISSUE THREAD

**Issue by bridzius** [nrwl/nx#12677]
## Current Behavior
`npx nx workspace-generator <name> <options>` fails with 
> Not enough non-option arguments: got 0, need at least 1

The error happens due to a recent change in `nx`, where `(option)` is appended to the command if there are options specified.

Converting https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/nx-commands.ts#L841 
from `if(options.length)` to `if(!options.length)` seems to fix the issue.
I can try creating a PR if that helps.

## Expected Behavior
`npx nx workspace-generator <name> <options>` should launch the generator and generate the required code.

## Steps to Reproduce
Reproduction in https://github.com/bridzius/workspace-generator-repro
Clone, `npm ci`, run `npx nx workspace-generator generato --all`. Should run the generator, but fails with said error.

### Failure Logs
```
npx nx workspace-generator generato --all
nx workspace-generator generato [name] (options)

Positionals:
  name  Library name                                                                                              [string]

Options:
  --help     Show help                                                                                           [boolean]
  --version  Show version number                                                                                 [boolean]
  --all      All for testing                                                                                     [boolean]

Find more information and examples at https://nx.dev/nx/workspace-generator

Not enough non-option arguments: got 0, need at least 1
```

### Environment
```
   Node : 16.17.1
   OS   : darwin arm64
   npm  : 8.15.0
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
Workspace generators is configured by default to require a name.
https://github.com/bridzius/workspace-generator-repro/blob/main/tools/generators/generato/schema.json#L20

If you run the following, it will work:

```
npx nx workspace-generator generato my-name-here --all
```

The error isn't the greatest but we can fix this.

I think a better error would be the following?

```
 NX   Required property 'name' is missing.
```

**Comment by Hotell** [comment]
> Workspace generators is configured by default to require a name.

Would you mind to elaborate more on this one @FrozenPandaz ? There is no mention of such a thing in docs nor release changelog.


Anyways workspace generator execution is indeed **broken in nx 15** (it has nothing to do with missing `name` )


<img width="900" alt="image" src="https://user-images.githubusercontent.com/1223799/196682958-9bdc0145-8edb-4be9-9357-ff1b1531101f.png">

**Comment by ShiJuuRoku** [comment]
I have same issue here.
No required params is specified.

```
{
  "$schema": "http://json-schema.org/schema",
  "cli": "nx",
  "$id": "app-generator",
  "type": "object",
  "properties": {
    "target": {
      "type": "string",
      "description": "Target Project name",
      "$default": {
        "$source": "argv",
        "index": 0
      }
    }
  }
}
```

**Comment by ild0tt0re** [comment]
I have the same issue, I'm on Nx v`14.8.6`

**Comment by Roozenboom** [comment]
We have exactly the same error after upgrading to NX 15.0.1 (from 14.8.2) and after removing the following lines from `packages/nx/src/command-line/nx-commands.ts L842` it worked again.
```js     
if (options.length) {
    command += ' (options)';
}
```
We also have another issue with local workspace-generators that has no properties object in the schema.json, because of missing error handling it throws the following error: `TypeError: Cannot convert undefined or null to object` for `Object.entries(schema.properties).forEach(([name, prop]) => {` as a workaround I can add an empty properties object to each schema.json but this can be fixed by checking if the property exists on `packages/nx/src/command-line/nx-commands.ts L814`.

I am happy to raise a pull request for both fixes.

**Comment by YegorMedvedev** [comment]
Seems that it isn't working since ver 14.8.5
Instead of asking questions in the terminal, it fails with an error:
```
Not enough non-option arguments
```

**Comment by stomvi** [comment]
Same here.

**Comment by meeroslav** [comment]
Sorry folks for this issue. 

As @bridzius found out, the missing `name` is actually the generator name. The error message is a generic one and comes from the `yargs` we now use for automating help messages for your generators.

The issue that @Hotell found comes from invalid `yargs` command automation that unfortunately expects you to pass all mandatory values as positional (e.g. `my-generator my-name`) instead of flags (e.g. `my-generator --name=my-name`).

I'll get to it asap.
