### ISSUE TITLE
git add option for fromat:write

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#12729]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The `format:write` command should have a `--git-add` flag that runs `git add <file>` for every changed file.

## Motivation
When using `format:write` with husky in pre-commit hook the changes have to be somehow added to the current commit. But there is no easy and straight forward way to do this.

So it would be easier if format could do the job.

## Suggested Implementation
Execute `git add <file>` for all changed files.

## Alternate Implementations
No idea

**Comment by AgentEnder** [comment]
`format:write` can affect files that are not meant to be part of the current set, so its better for devs to think about the files that are added.

**Comment by DaSchTour** [comment]
So format:write should not be used together with husky?

**Comment by DaSchTour** [comment]
Looking at this issue https://github.com/nrwl/nx/issues/869 it seams to me, that the tooling around prettier and linters is somehow incomplete.

**Comment by AgentEnder** [comment]
You can use `format:write` in husky if you want, dev's can (and should) use `git commit --amend` to update existing commits when necessary. Alternatively, swap to `nx format:check` in a pre-commit hook s.t. it will fail the commit instead of writing the first commit if devs are uncomfortable with using `--amend` or rebasing.

I'm not telling you not to use format:write; I'm simply saying that it doesn't make sense for us to add all changed files to git automatically in this case. Imagine you have the following git status:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   packages/core/src/executors/test/executor.ts

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   packages/core/src/executors/build/builder.ts
        modified:   packages/core/src/executors/format/executor.ts
```

When running `git commit`, `nx format:write` finds changes and updates either of the changes not currently staged for the commit. If we were to have specified `--git-add` or some equivalent flag, these files, which are not currently meant to be a part of the change set specified by the developer, would now have been added to it. The commit would already be made.

This can easily lead to changes being bundled together when they were meant to be kept separate or lead to further headaches as you now have to remove changes from an existing commit which is more complicated than adding new changes.
