### ISSUE TITLE
@nrwl/react:stories is not generating 'stories' files

### ISSUE THREAD

**Issue by rek** [nrwl/nx#12742]
## Current Behavior
On a new workspace (integrated/react/emotion):
```
nx g @nrwl/react:stories test
```
Does generate `*.stories` in `apps/test`

But:
```
nx g @nrwl/react:stories common-ui 
```
Does not generate any `*.stories` in `libs/common-ui`

## Expected Behavior

```
npx create-nx-workspace@latest
nx g @nrwl/react:lib common-ui
nx g @nrwl/react:storybook-configuration test
```
This makes the app stories ^

```
nx g @nrwl/react:storybook-configuration common-ui
```
This will generate the common-ui stories initially (but **only** for files in `src/lib` though, not in other `src*` folders)
```
nx g @nrwl/react:stories common-ui
```
This does nothing for things in `libs/*`

### Environment
```
>  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : linux x64
   npm  : 8.15.0
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by mandarini** [comment]
Hi there @rek ! Thanks for filing an issue. Unfortunately, I cannot reproduce this on my machine. Can you please create a reproduction repository and share it with me?

I suggest creating a workspace, and in that workspace create the apps/libs that you need. And bring it to a state where if I clone it and I run locally `nx g @nrwl/react:stories common-ui` no stories would be generated. Does this make sense?

Thank you so much in advance!

Just a note (just in case, to make sure we're on the same page), `.stories.*` files are generated next to component files, so if you don't have a component in your library, no stories are going to be created!

**Comment by rek** [comment]
Here is a repo: https://github.com/rek/nx-story-gen-test

![image](https://user-images.githubusercontent.com/180949/197460909-c8a3647c-3cf4-4866-bc5a-f585a0962f69.png)

Here are the components i'm expecting stories for:
![image](https://user-images.githubusercontent.com/180949/197461015-814a7f6c-06ab-4235-addb-670c58e6b0b7.png)

**Comment by mandarini** [comment]
Hi @rek ! Ohh I see what you mean. I will look into your issue this week, thanks for the PR!

**Comment by rek** [comment]
[This might fix it](https://github.com/nrwl/nx/pull/12805)

**Comment by mandarini** [comment]
Yes yes, I saw that PR. The thing is, we have the `lib` folder there for a reason, and it complies with the folder structure Nx imposes/suggests. I am trying to understand if it would add any value to allow for components outside the `lib` folder, you see?

**Comment by mandarini** [comment]
So, @rek , to be honest, I believe it would be confusing to allow for components to exist outside the `lib` folder, given how Nx sets up folders and files. We add the library code files inside the `lib` folder, and we use the `index.ts` which is outside the `lib` folder to export everything from the lib. Can you describe a use case where you would need to have files outside the `lib` folder?

**Comment by mandarini** [comment]
I changed the label from `bug` to `enhancement` because at the moment it works as intended. However, I am 100% open to discussing the other approach!

**Comment by rek** [comment]
Awesome, thanks for the feedback and discussion :)

> given how Nx sets up folders and files

I'm a bit new to nx, so initially I didn't see the reason behind the `lib` idea. I saw the index file is used to export things, eg [in the examples](https://github.com/nrwl/nx-examples/blob/master/libs/shared/header/src/index.ts), but that just seemed superfluous, so I removed it from my setup and ended up with something like:

```ts
libs/ui/src/
         |--> component1/
                 |--> Component1.js
                 |--> index.js
         |--> component2/
                 |--> Component2.js
                 |--> index.js
         |--> index.js
```
and index exporting the things I needed eg `libs/ui/src/index.js`:
```ts index.ts
export * from './component1'
export * from './component2'
```
Now I see that apps also have the pattern you mentioned with `apps/app1/src/app/`, which makes sense to me, because apps for sure always have more things to organize... I'm just not sold that we need to restrict `libs` to this pattern too (especially when none of the [examples](https://github.com/nrwl/nx-examples/tree/master/libs) make use of this structure by having other folders next to lib).

I am a bit torn now seeing the symmetry between `app` and `lib`,  but struggling to find another reason for keeping this folder. I suspect though as my projects grow it will become more apparent? So I guess I want to flip the question, what is the use case for having lib?

**Comment by mandarini** [comment]
Hi there @rek ! I see the confusion.

So, in the [link you posted](https://github.com/nrwl/nx-examples/tree/master/libs) that is just a folder containing libraries. If you open [each library](https://github.com/nrwl/nx-examples/tree/master/libs/shared/product/ui/src), you will see that it uses the structure:
```
libs/
└── my-app/
    └── feature-home/
        └── src/
             ├── index.ts
            └── lib/
```

You can read our guides:

* [Mental model](https://nx.dev/concepts/mental-model)
* [Applications and libraries](https://nx.dev/more-concepts/applications-and-libraries)
* [Library types](https://nx.dev/more-concepts/library-types)

These guides explain in very much detail the rationale behind the architecture that Nx suggests.

I understand that each user has their own use-case, but we at Nx recommend that setup. So our generators work with the setup we suggest. If you want to customize your workspace (and you 100% can customize it however you want and Nx will still work), that means that some of our generators (which are, in a simplified way, codemods) may not work with the custom setup, since they will be expecting something else. That does not stop you from using the power of Nx (DTE, cache, fast builds, CI, etc etc). Most of our generators take into account special setups, but it would not be scalable to try and take into account every possible setup. But, again, as I said, that should not stop anyone taking full advantage of all that Nx offers.

We think that if someone (a user, a team, an organization) uses Nx in the [integrated style](https://nx.dev/concepts/integrated-vs-package-based), which makes the most of utilizing our plugins and generators, that someone will use, to the extend that it works with what they have, the architecture (and folder/file structure) that Nx imposes (I didn't want to say "imposes" because it's a strong word, but I'll leave it there to convey what I mean). So, if "imposes" is a strong word, then let's say "The architecture with which Nx achieves its full potential".

As to why we are using the `lib` folder and the `app` folder, these are some choices that were made (considering the specific file structure to be convenient, helpful, tidy, non-confusing, ... ?), and around these choices our generators and executors are built.

Let me know if you have any more questions, I'll be super happy to help clear things up for you! :)

**Comment by rek** [comment]
I'm still not 100% sold on 'restricting' (ie: just a minor generator not working) all libs to have an internal `lib` folder.. but I do highly appreciate you taking the time to explain all this and Nx's point of view. I hadn't read the the [library types](https://nx.dev/more-concepts/library-types) before either.
I'm happy to close this though :)
