### ISSUE TITLE
Angular production build do not tree shake not used files (even with optimization=true)

### ISSUE THREAD

**Issue by distante** [nrwl/nx#12939]
## Current Behavior
All files of a library that are not used are included on production bundle.

## Expected Behavior
File that are exported by a library should not be included on `main.js` if not used.

## Steps to Reproduce
Run `npx nx build my-app --configuration=production` after checking out this repo: https://github.com/distante/angular-nx-tree-shaking-error

<details>
   <summary>Detailed Explanation From Repo Readme</summary>

The monorepo has one angular app (`MyApp`) and one angular library (`MyLibrary`). 

`MyLibrary` contains an `MyLibraryModule` that declares and exports `MyComponentComponent`.

```typescript
@NgModule({
  imports: [CommonModule],
  declarations: [MyComponentComponent],
  exports: [MyComponentComponent],
})
export class MyLibraryModule {}
```

It is imported in `MyApp` `app.module.ts` file.
```typescript
@NgModule({
  declarations: [AppComponent, NxWelcomeComponent],
  imports: [BrowserModule, MyLibraryModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

`MyLibrary` also exports some "`stub`" `testing` files that can be used by apps/libraries consumers for unit testing. Those files import some `@testing-library/angular` files in them.

>⚠️ Currently those files are not imported anywhere.

# Problem

After building the app with `npx nx build my-app --configuration=production` we get a couple of warnings after build:

```
Warning: /Users/saninn/dev/temp/tree-shaking/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js depends on 'aria-query'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/saninn/dev/temp/tree-shaking/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js depends on 'pretty-format'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

and in the generated `main.*.js` file, `testing-library` is being included, even when we have configured our app with `"optimization": true,`.

</details>

### Failure Logs
```
Warning: /Users/saninn/dev/temp/tree-shaking/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js depends on 'aria-query'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/saninn/dev/temp/tree-shaking/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js depends on 'pretty-format'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

### Environment
```
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 15.0.5
   @nrwl/angular : 15.0.5
   @nrwl/cypress : 15.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.5
   @nrwl/js : 15.0.5
   @nrwl/linter : 15.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.5
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.5
   @nrwl/workspace : 15.0.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @testing-library/angular: 12.1.2
```

**Comment by Coly010** [comment]
The problem comes from these files:

https://github.com/distante/angular-nx-tree-shaking-error/blob/main/libs/my-library/src/index.ts
https://github.com/distante/angular-nx-tree-shaking-error/blob/main/libs/my-library/src/lib/index.ts#L2
https://github.com/distante/angular-nx-tree-shaking-error/blob/main/libs/my-library/src/lib/testing/index.ts

You're exporting the testing stubs from the main library entry point, which forces them to be included in the application.

If you need those testing stubs outside the library itself, you should use the `library-secondary-entry-point` generator that will limit the files exported from the main library and the files exported from the secondary entry point, separating the concerns and allowing the bundle to not include the testing files.

https://nx.dev/packages/angular/generators/library-secondary-entry-point

**Comment by g3tr1ght** [comment]
@Coly010 I'm sorry but the problem is related to NX inability to tree-shake properly. Think of testing stubs as unused imports (which is a legit use-case given NX barrel exports/imports philosophy), which must have been tree-shaken out as clearly they are side-effects free.
I might be missing something and testing stubs somehow get imported in the app modules and executed at run time? If that's the case, could you please point?

**Comment by Coly010** [comment]
Nx doesn’t build your app however. Nx runs a different tool, which you specify in your project.json, to build it. 

The problem is coming from the Typescript Path Aliases that lets you have import statements of “@myorg/mylib”.

Because you’re exporting everything from your library, combined with the path alias, typescript is stating all exported functions must be available for consumption.

That’s the crux of the problem. The actual tree-shaking is done by webpack plugins that Angular sets up, not Nx. You use the angular browser builder to build your app, and it uses Webpack under the hood. 

The workaround I’ve given above should work fine.

**Comment by distante** [comment]
@Coly010 The workaround not work on this use case because the library is not a publishable library.

**Comment by Jasonkoolman** [comment]
For those still struggling to get tree shaking to work with the default Webpack configuration, read https://github.com/nrwl/nx/issues/9717#issuecomment-1424044108

**Comment by distante** [comment]
> For those still struggling to get tree shaking to work with the default Webpack configuration, read [#9717 (comment)](https://github.com/nrwl/nx/issues/9717#issuecomment-1424044108)

Sadly this make no difference on an Angular Project.

I set
```
"build": {
  executor": "@nrwl/angular:webpack-browser",
     "options": {
        " customWebpackConfig": {
           "path": "apps/my-app/webpack.config.ts"
        },
} 

```

and the config is:
```typescript

import { Configuration } from 'webpack';

module.exports = function (config: Configuration, _options: unknown) {
  console.log('current config.resolve.mainFields', config.resolve?.mainFields); // Log the current Webpack
  // See https://github.com/nrwl/nx/issues/9717#issuecomment-1424044108
  if (config.resolve && Array.isArray(config.resolve?.mainFields)) {
    // Fix 1: resolves tree-shaking issue
    // The default in NX is [ 'browser', 'main', 'module' ]. Thus, 'main' had preference over 'module' when Webpack reads the `package.json` files, which is not what we want. Module should become before main - the order matters!
    // See https://webpack.js.org/configuration/resolve/#resolvemainfields
    config.resolve.mainFields = ['browser', 'module', 'main'];
  }

  console.log('FIXED config.resolve.mainFields', config.resolve?.mainFields); // Log the current Webpack
};

```

I can see my logs there:
```
current config.resolve.mainFields [ 'es2020', 'es2015', 'browser', 'module', 'main' ]
FIXED config.resolve.mainFields [ 'browser', 'module', 'main' ]
```

But the warnings and not wanted modules still land in main[id].js

Applying the TerserJS plugin makes my bundle bigger, BTW.
