### ISSUE TITLE
@nrwl/next:build `fileReplacements` option does not work

### ISSUE THREAD

**Issue by yoont4** [nrwl/nx#12959]
## Current Behavior

When running a build with the `next:build` executor, the `fileReplacements` option doesn't work (nothing gets replaced).

## Expected Behavior

The file should get replaced

## Steps to Reproduce

Create a bare NextJS project + 1 file: `.env.random.file` at the project root

Add the following option to a build target:
```
"options": {
  "fileReplacements": [
    {
      "replace": "apps/frontend/.env.local",
      "with": "apps/frontend/.env.random.file"
    }
  ]
}
```

Run the build: `nx run frontend:build`

If the file replacement worked, the very first line of the build log would include:
```
> nx run frontend:build:alpha

info  - Loaded env from apps\frontend\.env.local
```

But it does not.

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 14.17.0
   OS   : win32 x64
   pnpm : 6.32.10
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : 14.4.2
   @nrwl/next : 14.4.2
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @nx-tools/nx-docker: 3.0.0-alpha.2
   	 @trumbitta/nx-plugin-unused-deps: 1.11.0
```

**Comment by FrozenPandaz** [comment]
I don't think this is a bug.

The first line you see is the info for this guide: https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order

This is separate from `fileReplacements` which replaces source files with different ones. In order to load environment variables from a different file, please refer to the guide above.

**Comment by yoont4** [comment]
The goal is to build for different environments than what they support. NextJS only has development and production environments that get picked up, but we have multiple that require different environment variables. Using the default NextJS load order does not work for us because of that, which is why I need the `fileReplacements` option.

Also I know it doesn't work because I tried replacing a file required for compilation with a junk file, and it still builds fine. If it really did the replacement then it would have failed while compiling.

**Comment by ALexander4295502** [comment]
@FrozenPandaz sorry but your response is still confusing to me. From this link https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order I don't see any clue regarding why the env file cannot be replaced by nx properly.

Here is what I found that might be helpful to resolve your confusion. @yoont4 

After digging into the source code of `@nrwl/next` I found the `fileReplacements` config is consumed [here by `prepareConfig()`](https://github.com/nrwl/nx/blob/master/packages/next/src/executors/build/build.impl.ts#L70), and inside 
 `prepareConfig()` it first running the [`next#loadConfig`](https://github.com/nrwl/nx/blob/master/packages/next/src/utils/config.ts#L113) so you will see this logline:
```
info  - Loaded env from apps\frontend\.env.local
```

This means the file replacement won't affect the next load config process. 

@FrozenPandaz I am not pushing you to change this behavior if this is by intention, but at least we should put some disclaimer in the [doc here](https://nx.dev/packages/next/executors/build) saying this "limitation" to make this clear and avoid further misleading like this post (I can foresee tons of people using next will fall into this situation since the env file setup for different staging is a major use case for `fileReplacements`)
