### ISSUE TITLE
Cypress Component testing not able to load assets

### ISSUE THREAD

**Issue by lydemann** [nrwl/nx#12987]
I originally posted this issue on Cypress with Cypress component tests not being able to load assets, which is working now for Cypress and Angular CLI projects. However, it breaks with Nx and the Nx Cypress runner + component test config.

## Current Behavior

Can't load assets eg. icons from Angular material registry loader.

This works for a Cypress component test project without Nx though:
https://github.com/lydemann/cypress-assets-bug/tree/master

## Expected Behavior

Should be able to load assets

## Steps to Reproduce

1. Create Nx Angular project
2. Set up Cypress component testing with Nx component test config for app
3. Create a test that loads a custom Angular material icon
4. Run the test and see that it fails

Demo repo:
https://github.com/lydemann/cypress-assets-bug/tree/nx

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by tobiornot2b** [comment]
Any updates on this?

**Comment by jerkovicl** [comment]
Same for me can't get to include scss files same paths work on build-storybook target tough

**Comment by barbados-clemens** [comment]
So this issue has been puzzling me for a while. 

basically unsure what is happening here, but if you change the assets string into the object syntax in the project.json it works.

```diff
assets: [
- "apps/<app-name>/src/assets",
+ {
+   "glob": "**/*",
+   "input": "apps/<app-name>/src/assets",
+   "output": "assets"
+ }
]
```
from my understanding "apps/<app-name>/src/assets" string basically means the same thing as the object syntax. Still debugging, but this should at least get you up and working in the mean time. 
![screenshot of showing assets loading](https://user-images.githubusercontent.com/23272162/210446326-3d4cf65c-ac93-4c17-80d4-24ad08ab6e5d.png)

**Comment by jerkovicl** [comment]
@barbados-clemens i tried with object syntax, but that didn't work for me

**Comment by barbados-clemens** [comment]
do you have a repo I can look at @jerkovicl? 

I think I've tracked down to the actual values angular uses and working on understanding more of the problem. 

from what i've seen the default `"apps/demo/src/assets" turns into 
```json
 {
      "glob": "**/*",
      "input": "../../apps/demo/src/assets",
      "output": "src/assets"
    }
```

and 
```json
 {
      "glob": "**/*",
      "input": "apps/demo/src/assets",
      "output": "assets"
 }
```
is turning into 
```
 {
      "glob": "**/*",
      "input": "../../apps/demo/src/assets",
      "output": "assets"
 }
```

under the hood in the angular builder. 

so when running Cypress CT the path to assets is mapped to `src/assets` instead of just `assets`

Or at least that's where I ended yesterday off and working on debugging more today to see what exactly is happening.

**Comment by jerkovicl** [comment]
@barbados-clemens i can send you zipped code on slack if you want?

**Comment by pjlamb12** [comment]
The object syntax seems to have helped me with JSON files that are in the assets folder, but not images. It seems like images still can't be found. Do you know of any other things to try?

**Comment by pjlamb12** [comment]
It looks like some assets are converted to this: 

`http://localhost:8080/__cypress/src/assets/path/to/asset.jpg`

and some don't have the `__cypress` part so those ones don't load.

**Comment by barbados-clemens** [comment]
I'm seeing the same thing, still trying to figure out what is causing this when only in an nx workspace vs ng cli. 

oddly enough either syntax shows the assets in the same location for me.

**Comment by barbados-clemens** [comment]
Okay folks I think we got the root issue. I still have a handful of things I need to test, but I at least understand what the issues is. 

Basically cypress opens in the Nx project root. but when in an angular cli project it opens in the `workspaceRoot` (root of the repo). The component-testing preset for angular provides the path offsets to correctly resolve paths which seem to have only been _kind of_ working. As within the `@cypress/webpack-dev-server` package the pathing causes the angular webpack utils to use the project root as the workspace root so while it's able to build the webpack config the assets get mapped to a different url where they aren't getting proxied as expected. i.e. `__cypress/src/assets` instead of `assets`

I'll make a PR to Cypress that will allow nx to provide it's own workspace root to use which should fix the issue. I still have a bunch of testing I need to do to make sure this will in fact fix the issues for both app and lib project component testing without breaking existing angular cli workspace testing. This fix also requires some change on the Nx side so all of that will be get coordinated and I'll keep y'all updated on where everything lands.

**Comment by pjlamb12** [comment]
That is great! Thanks so much for your help and support on this. :)

**Comment by jerkovicl** [comment]
Yeah that is great news, good job on finding the root cause so quickly!

**Comment by barbados-clemens** [comment]
Please retry with latest Nx and Cypress. I believe the issue has been resolved as I cannot reproduce the issue any more. Things I've tried is using stylePreprocessorOptions/img tag asset loading, HttpClient asset load all work across libs/apps. 

Here is the repo I used for reference. 
https://github.com/barbados-clemens/cy-asset-style-demo

I'm going to mark the issue as blocked until there is a repro that shows this not working on 
Nx v15.6+ and Cypres v12.3+. 

Odds are this was an issue in cypress v10/v11 but was fixed in v12 and/or in combination with angular v15. 

I'll still work on making some e2e tests in the Nx repo to make sure this doesn't regress and to fix a couple other smaller issues like 

```
ERROR in polyfills
       Module not found: Error: Can't resolve '../../zone.js' in
```

you might see when using component testing but major issues of asset loading look to be resolved.

**Comment by Tungsten78** [comment]
@barbados-clemens seeing this issue reproduce under:
* Nx 15.8.5
* cypress 12.7.0

Characterized by asset paths not resolving as `__cypress/src/assets`.

Using your [repro branch](https://github.com/barbados-clemens/cy-asset-style-demo), I also don't see the problem resolve after upgrading to cypress 12.3.0 as I understood your last comment..  Coincidentally, same issue if going to 12.7.0.

Was there something else needed other than nx/cypress combo?
