### ISSUE TITLE
ng update for angular frontend does not show updates available

### ISSUE THREAD

**Issue by mfechner** [nrwl/nx#1349]
## Expected Behavior

Executing `ng update` should show available updates as it works on an Angular project that was created with the Angular CLI.

## Current Behavior

It does not show you that an update for Angular is available which is wrong. Version 7.2.13 is available while writing this issue.

## Failure Information (for bugs)

As I'm new to NX I'm not sure if this is a bug related to NX or the Angular CLI. Please point me into the right direction.

### Steps to Reproduce

1. `npx create-nx-workspace nxTestAngularUpdate`
    Select SCSS, workspace name: nxUp, and angular as frontend
2. `cd nx-test-angular-update`
3. `ng update`

You will see:
```
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       7.3.1 -> 7.3.9           ng update @angular/cli
      rxjs                               6.3.3 -> 6.5.2           ng update rxjs
```

### Context
The package.json shows angular version ^7.0.0 installed but 7.2.13 is available:
```
...
  "dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
...
```

## Other

Any other relevant information that will help us help you.

**Comment by FrozenPandaz** [comment]
Hi, there are in fact no updates for `@angular/core` for your repo. Let me explain:

1. `ng update` is based on the version installed in the workspace
2. The version installed in the workspace is defined by the `package.json` which is `^7.0.0`. This means the latest stable version (not `-beta`, `-rc` versions) between `7.0.0` up to `8.0.0 which at this time is `7.2.13` will be installed.
3. Because the latest stable version of `@angular/core` is also `7.2.13`, you have the latest version installed.

When a new version of `@angular/core` comes out, you should see `ng update` show the updates of `@angular/core` are available. Hopefully this makes. Please let me know if you have any questions.

**Comment by mfechner** [comment]
Thanks a lot for your help!
The command `npm run update` fixed my problems.
Now `ng update` seems to work nicely. Maybe a problem that is now fixed with a newer NX version.

Really a very nice work you do here!

**Comment by ctilley83** [comment]
This gremlin is causing me grief. I ran ```ng update``` and it showed that angular updates were available. 15.1.5 -> 15.2.0. I ran ```npm upgrade``` to update other dependencies first, and now running ```ng update``` shows no packages available although my package.json is still referencing 15.1.5.
