### ISSUE TITLE
Error message >  NX   Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by DrewImm** [nrwl/nx#13889]
### Current Behavior

After installing prettier-eslint (to customize linting options to fit our team's style guide), I cannot run any nx command in the repo:

>  NX   Cannot read properties of undefined (reading 'data')

Tried `nx reset`, `nx repair`, removing node_modules/package-lock, but NX is always emitting the same error

### Expected Behavior

NX commands should not throw any errors

### Github Repo

https://github.com/DrewImm/nx-prettier-eslint

### Steps to Reproduce

1. `npx create-nx-workspace@latest nx-prettier-eslint --preset=npm`
2. `cd nx-prettier-eslint`
3. `npx nx graph` (Shows that nx commands work prior to prettier-eslint installation
4. `npm i -D prettier-eslint prettier-eslint-cli`
5. `npx nx graph` (Shows that nx commands are now broken)

### Nx Report

```shell
$ npx nx report

 >  NX   Cannot read properties of undefined (reading 'data')


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Failure Logs

```shell
$ npx nx graph

 >  NX   Cannot read properties of undefined (reading 'data')


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

**Comment by nfroidure** [comment]
Having the exact same problem : https://github.com/nfroidure/whook/actions/runs/3731277632/jobs/6329322050#step:5:16

Happening in this branch:
https://github.com/nfroidure/whook/pull/62

**Comment by AlexisG0** [comment]
Hey, any update about this error?
Get it too, tried to downgrade but nothing happened

**Comment by nfroidure** [comment]
FYI, I just figured out that the problem was a version that was not well set in the `package.json` file of a monorepo managed with lerna. I supposed that it led to 2 versions of the same module to be installed and this module is managed by lerna (@whook/http-router) : https://github.com/nfroidure/whook/blob/685225fbf4308cd405ac72c5880de2ca12d46d2e/packages/whook-example/package.json#L84

Just setting the package.json back to the good version and `npm i` fixed the issue. No idea why but thought it could help you to fix the original issue.
