### ISSUE TITLE
On windows I get the following Error: tree.branch is not a function

### ISSUE THREAD

**Issue by kevincam3** [nrwl/nx#139]
Node v 8.9.1
NPM 5.6.0
Angular CLI 1.5.5

![image](https://user-images.githubusercontent.com/870934/33579414-ed3c7298-d930-11e7-8291-67640b1703e9.png)

**Comment by Yonet** [comment]
I was getting the same error. You can try cleaning up my node_modules.

**Comment by kevincam3** [comment]
what does that mean "cleaning up my node_modules" what command do I run to do what you're suggesting?

**Comment by vsavkin** [comment]
The issue is that you have multiple versions of RxJS installed globally, so there are two Observable prototypes and instanceof checks do not work, so angular schematics wrap the tree object twice.

It's hard to make `ng new blah --collection=somecollection` reliable as it highly depends on what you have globally installed.

This is why I highly recommend using the script approach described here https://nrwl.io/nx/guide-getting-started It creates a sandbox, so it very rarely causes issues.

If you don't want to use the script, find where you have node modules installed globally. Search for `"name": "rxjs"` to figure out where you have different versions of RxJS installed.
