### ISSUE TITLE
NX is not able to run the E2e Test in parallel

### ISSUE THREAD

**Issue by bikeshresth** [nrwl/nx#14088]
### Current Behavior

I try to run my end to end spec file in parallel but it doesnt work even if i use --parallel flag or max-parallel flag. 

### Expected Behavior

Parallization for E2e should be working. 

### Steps to Reproduce

1. Run nx command for e2e 
2. nx run projName-e2e:e2e --parallel --max-parallel=2  including all by record key for cypress and all but still it doesnt parallelize my spec files. It is already connected to the Cypress Dashboard. 

But the parallelization process is not working properly. 

### Nx Report

```shell
Ports are already in use.
```

**Comment by mandarini** [comment]
@barbados-clemens it must be that thing of Storybook. I'm planning to work on it this week and the next, but assigning you too, because I'll need reviews etc

**Comment by barbados-clemens** [comment]
this is because the e2e tests that use a devServerTarget will run that devServerTarget. if those dev servers both use this target, then they are unable to run in parallel because the port is being used. 

If you want to run multiple dev servers in parallel with e2e testing then you'll need to make sure the dev servers are set to run with different port numbers. 

@mandarini is working some storybook changes to handle the port changes that storybook does, but that doesn't look completely related to this issue.

**Comment by mandarini** [comment]
Ohhh I see! Since it does not look super related, I am removing myself. Will still reference that PR though, once it comes :P

**Comment by mandarini** [comment]
So @bikeshresth thanks for filing this issue.

You can fix this issue by changing the ports of all the apps you expect to run in parallel so they do not collide. Doing this automatically through Nx, within the cypress executor, could be error prone. So it's best to leave this up to the user. Let me know if the issue persists once you change the ports, and we can revisit!

**Comment by bikeshresth** [comment]
Actually the problem is to run the test cases of a particular project in
parallel rather than the project itself.
We have a project called lyra, luzon and admin and
I need to run the test cases of lyra-e2e in parallel rather than running
lyra and luzon parallel.

I want the specs of the lyra project to run parallel.
For example,

test.spec.ts , test1.spec.ts are the test cases of LYRA and it should run
in parallel.

**Comment by mandarini** [comment]
I see @bikeshresth ! Maybe @barbados-clemens can suggest something?

**Comment by barbados-clemens** [comment]
instead of spinning up the dev server with cypress (devServerTarget) 
you should instead serve the application outside of the executor and just point cypress to that url (baseUrl). this way you won't have the port collision. 

you can do this with the file-server from nrwl/web. or just run the server command before running e2e tests.

**Comment by bikeshresth** [comment]
it didnt worked out for us.
