### ISSUE TITLE
(@nrwl/angular) core-js not needed in dependencies

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#1411]
## Expected Behavior

Angular CLI has [removed `core-js` from the installed dependencies](https://github.com/angular/angular-cli/commit/a0a583a) when creating a project as those are handled via the differential polyfilling. Additionally, they've also bumped their use of it to the next major version (`^3.0.0`) internally. As part of upgrading to Nx 8, perhaps something similar needs to happen.

On a related note, I haven't looked in detail to the differential polyfilling strategy used for @nrwl/web, but this may potentially relate to the functionality under that package too.

## Current Behavior

`core-js` is included as part of the add schematics in `@nrwl/angular` and it remains as part of the repo's dependencies after upgrading to Nx 8, although perhaps it's worth noting is that (as far as I can tell) the Angular CLI update migration [doesn't remove `core-js` from the `package.json` either](https://github.com/angular/angular-cli/blob/v8.0.0/packages/schematics/angular/migrations/update-8/update-dependencies.ts); they're only excluding it when creating new projects.

## Failure Information (for bugs)

No failure that I've seen yet. Not sure if issues could ever arise from having `core-js@^2` while  the Angular builders use a more upgraded version, but I haven't seen any issues so far.

### Steps to Reproduce

N/A beyond running `npx ng update @nrwl/schematics@next` in upgrade-applicable cases.

### Context

Please provide any relevant information about your setup:

- Nx version: `7.8.6 -> 8.0.0-rc.2 (current next)`
- Angular CLI version: `7.3.7 -> 8.0.0`
- Angular DevKit version: `0.13.8 -> 0.800.0`
- 3rd-party libraries and their versions: `core-js@^2.5.4`

### Failure Logs

N/A

## Other

N/A

**Comment by FrozenPandaz** [comment]
Thanks for the information! We should definitely stop adding `core-js` to generated repos.

I think it is not removed during migration because people may depend on that dependency so even though the `@angular/cli` doesn't use it, it may be added elsewhere.

For our differential loading implementaiton, we don't add our own polyfills and instead let the user decide which to add. We don't yet generate these files but may in the future.

**Comment by matheo** [comment]
@emilio-martinez @FrozenPandaz  I just saw that `core-js` is required by `jest-preset-angular` as `peerDependency`

**Comment by FrozenPandaz** [comment]
I haven't had the time to look into this.

@jaysoo is working on the web builder. Maybe he can provide some insight into whether or not we need to include `core-js`?

**Comment by jaysoo** [comment]
I don't think we need to add `core-js` as a dependency for the generated workspace. The package that needs core-js should define it as its dependency instead of relying on it being in `peerDependencies`... this is especially true when project update `core-js@2` to `core-js@3` (which contain breaking changes).

I'll take a look to see if we can remove it outright. There is a related issue here #2086.

**Comment by brandonroberts** [comment]
This issue has been resolved. See https://github.com/nrwl/nx/issues/2086 for reference
