### ISSUE TITLE
Nx daemon not available in docker containers

### ISSUE THREAD

**Issue by hytromo** [nrwl/nx#14126]
### Current Behavior

Currently the Nx daemon usage is completely disabled when Nx is running in a docker container ([source](https://github.com/nrwl/nx/blob/19abb973f0b78733c1fbd3d9ee05576a42a602e5/packages/nx/src/daemon/client/client.ts#L75)).

This causes Nx commands to recalculate the project graph each time instead of using the daemon's cache ([source](https://github.com/nrwl/nx/blob/19abb973f0b78733c1fbd3d9ee05576a42a602e5/packages/nx/src/project-graph/project-graph.ts#L127)).

So, for every nx command that is run, this includes hashing all the monorepo files each time, which can be a really time consuming operation for larger monorepos ([source](https://github.com/nrwl/nx/blob/19abb973f0b78733c1fbd3d9ee05576a42a602e5/packages/nx/src/project-graph/build-project-graph.ts#L51)).

We are developing inside a docker container to ensure common tooling between the team members, and this is really slowing us down (5+ seconds to _start_ running each nx command, like `nx run <project>:<target>`)

Hacking the code on the fly to enable the daemon to work inside a docker container seems to work fine, so not sure why this was introduced [here](https://github.com/nrwl/nx/commit/1a31018ea2bc9f415268636b2ad834ff02a8d147#diff-ac77bbed6ea29034032e92619972b1ad989e0accad1b05b5462a276707549da0).

### Expected Behavior

Nx Daemon should work inside docker containers to avoid recalculating the project graph each time which can be a very expensive operation.

### Steps to Reproduce

1. Start a docker container and mount your large monorepo in it
2. Try to run an nx target to see the slow startup time
3. Run `nx daemon` to see that the daemon hasn't started
4. Run another nx target and notice how slow the startup is

### Nx Report

```shell
Node : 18.12.1
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.4.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by lega0208** [comment]
Thanks for this. I've been working on streamlining a build/CI pipeline for a couple of days now and have been wondering whether I was configuring things wrong or if it was intentional behaviour from NX. For some reason googling "docker nx cache" or similar things yields essentially no results so I was beginning to think I was the only one with this issue. Good to know that's not the case.

Would you mind sharing your workaround if it's not too much trouble? Much appreciated.

**Comment by hytromo** [comment]
> Would you mind sharing your workaround if it's not too much trouble? Much appreciated.

I haven't found a real workaround, unfortunately. To test out whether the Nx Daemon works inside a docker container I just edited on the fly the Nx code itself.

**Comment by lega0208** [comment]
> 
> I haven't found a real workaround, unfortunately. To test out whether the Nx Daemon works inside a docker container I just edited on the fly the Nx code itself.

Oh sorry I misunderstood. Well thanks either way.

Looking at the source, it seems like a simple way to solve this would be to have the env variable take precedence over everything else. From the way the logic is laid out, it seems like there might be a reason why that's not the case, but what that might be isn't clear to me. I could potentially take a stab at a PR if a maintainer can chime in and give some direction.

**Comment by StalkAltan** [comment]
Hi @hytromo / @lega0208 

To provide some context, we originally disabled the daemon in Docker because when running with Nx Cloud we offload network calls to it.

With this setup, it was possible for people to get their workspaces/caches into bad states due to the docker container closing when Nx's process is completed, but before those background calls were finished.

There is probably a smarter way for us to approach this than flat-out disabling the daemon.

**Comment by lega0208** [comment]
> I haven't found a real workaround, unfortunately. To test out whether the Nx Daemon works inside a docker container I just edited on the fly the Nx code itself.

Sorry, I misunderstood, but thanks nonetheless!

> Hi @hytromo / @lega0208
> 
> To provide some context, we originally disabled the daemon in Docker because when running with Nx Cloud we offload network calls to it.
> 
> With this setup, it was possible for people to get their workspaces/caches into bad states due to the docker container closing when Nx's process is completed, but before those background calls were finished.
> 
> There is probably a smarter way for us to approach this than flat-out disabling the daemon.

Thanks for the reply, I figured it was something along those lines.

I'm unfamiliar with the internals so forgive me if this is a silly question, but would it be difficult or problematic to wait for the background calls to finish before exiting the process? Seems like a really straightforward solution so I'm guessing there's a good reason it isn't done that way.

If the reason is performance-related, it might still be better than no daemon at all, and could be worth adding a way to opt-in to that for this particular use case as a temporary solution? I don't know a lot of the details so just throwing that out there.

**Comment by hytromo** [comment]
A simpler, one-line-of-code solution would be to introduce a new environment variable in Nx Cloud and check its value instead of disabling the daemon inside docker containers blindly.

**Comment by prmichaelsen** [comment]
> Thanks for this. I've been working on streamlining a build/CI pipeline for a couple of days now and have been wondering whether I was configuring things wrong or if it was intentional behaviour from NX. For some reason googling "docker nx cache" or similar things yields essentially no results so I was beginning to think I was the only one with this issue. Good to know that's not the case.

I've been pulling my hair out as well. I assumed I was doing something wrong and could find _nothing_ on  it.

**Comment by prmichaelsen** [comment]
For the interim, I went with a different remote cache solution: https://github.com/wvanderdeijl/nx-remotecache-gcs

`nx.json`
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "npmScope": "parm",
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx-remotecache-gcs",
      "options": {
         "bucket": "gs://parm-nx-cache"
        "cacheableOperations": [
          "build", "lint", "test", "e2e", "server"
        ],
     }
  },
  ...
}
```

```yaml
# docker-compose.yml
services:
    app: 
        build:
            args: 
                GCP_CREDENTIALS: $GCP_CREDENTIALS
```

```sh
# .env
GCP_CREDENTIALS=<service-account-credentials>
```

```Dockerfile
# Dockerfile
# for nx-remotecache-gcs
ARG GCP_CREDENTIALS=
RUN echo "${GCP_CREDENTIALS}" > credentials_path
ENV GOOGLE_APPLICATION_CREDENTIALS credentials_path

RUN npx nx run <commands>

```

**Comment by GrumpyMeow** [comment]
You can check if the NX Daemon is running with: `ps -aux | grep node_modules/nx/src/daemon/server/start.js`
If it's not running, you can manually start it with: `nx daemon --start`
To manually stop: `nx daemon --stop`
I'm also using NX in a Linux DevContainer (Cypress/included container actually). 
I hope this helps...

**Comment by JakeDern** [comment]
My team is also running into this issue in Linux Dev Containers. Starting the daemon manually using `nx daemon --start` and/or adding `NX_DAEMON=true` to the environment does not restore the caching behavior for us even though `nx daemon` reports that it is "running".

@StalkAltan Is there anything in progress to resolve this? VSCode Dev Containers are widely used especially with complex monorepo environments and this is a pretty major barrier

**Comment by prmichaelsen** [comment]
I discovered a workaround where this isn't an issue if you don't use Nx

**Comment by JakeDern** [comment]
Still an issue we're working around in our team. Commenting to stop it from being marked stale.

**Comment by tfrijsewijk** [comment]
@JakeDern 

> Here is our solution for working around this in devcontainers - We're hacking the daemon client with the following script on startup after running `npm install`. It's not perfect since a variety of `npm` commands can undo it, but it gets the job done most of the time and works for our pipelines. Nx is such a great tool it's unfortunate that this is needed... hoping for a real fix in the future.

Take a look at https://www.npmjs.com/package/patch-package. Although it is still a hack, patch-package is made for this.

Thanks for your hack! We're up and caching.

**Comment by LPCmedia** [comment]
Can't say if its the daemon or another issue, but since ~1 month the performance of nx inside of docker is making it impossible for us to use. 

- 2 front end apps + 1 node back end starts randomly after ~1 minutes.

**Comment by cjam** [comment]
Running into the same issue within a devcontainer environment.  My nest app won't reload on changes since the Daemon isn't running.  Seems like the suggestion [about a separate environment variable](https://github.com/nrwl/nx/issues/14126#issuecomment-1422717959) might be a good alternative to support the nx cloud without breaking nx functionality inside devcontainers.  

Starting the daemon manually via `nx daemon` or setting the NX_DAEMON environment variables won't ever do anything because as far as the code is concerned, it bails as soon as it see's that it's inside a docker environment.  Perhaps it could check to see if there is a daemon running?  That would still require manual starting of the daemon which doesn't seem like a great solution.

https://github.com/nrwl/nx/blob/a8dc251ccec87dcb8874b4ccb5132b33e74daa9e/packages/nx/src/daemon/client/client.ts#L116-L126

Will unfortunately need to use patch-package to remove that line as was suggested, but given the role that devcontainer's play within our organization it would be great to have an actual solution.

**Comment by mathewtrivett** [comment]
Just adding a +1 to this discussion. I have a monorepo that I want to run in development using nx inside a docker container but blocking this by default is pretty frustrating.

**Comment by rylan** [comment]
An issue I had that on the face of it sounded very similar to this issue, when upgrading past 19.4.4 in dev container. The problem for me was if the root folder name is the same as your application Nx cannot find it  for example `sample-app/apps/sample-app/`. So all my standard run commands would fail and instead of saying project not found would be dependency graph error. If you run `nx show projects` and your target application is missing, the simple fix is to just rename it.

**Comment by vdiaz1130** [comment]
I don't know if this helps but I was able to get the services running in Docker to restart with `docker compose up --watch`.

**Comment by jamesikanos** [comment]
Upgrading to latest (19.8.4) and setting `NX_DAEMON=true` env variable works fine inside dev container now.
