### ISSUE TITLE
Support cy2 in cypress executor

### ISSUE THREAD

**Issue by mathpaquette** [nrwl/nx#14450]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

Would you be interested to add an option to instruct cypress executor to use cy2 to configure cypress to use an alternate Cypress dashboard. I'm using Sorry-Cypress instead of the Cypress dashboard because I have to use on prem version and Cypress doesnt have that.

## Description

nx e2e my-app-e2e **--cy2**

## Motivation

support sorry-cypress instead of the just the standard Cypress dashboard.
on prem is allowing better speed and stability.

## Suggested Implementation

It's pretty straightforward. It's just a matter of using the spawn provided by cy2.
https://github.com/sorry-cypress/cy2#spawn

## Alternate Implementations

Do you have any doc about extending cypress executor if you're not interested supporting that out of the box.

**Comment by mi4i0** [comment]
+1

**Comment by olegsmall** [comment]
+1

**Comment by spaque99** [comment]
+1

**Comment by mathpaquette** [comment]
Maybe it could be as simple speechifying the command for starting cypress ?

**Comment by barbados-clemens** [comment]
Currently I don't think this a direction we want to take the `@nrwl/cypress:cypress` executor. 

But makes a good candidate for a community plugin/local plugin since all you'd really need to do is take the current `nrwl/cypress:cypress` executor and switch out the `Cypress.run` call to the `cy2` run api instead. 

https://github.com/sorry-cypress/cy2#run
