### ISSUE TITLE
Storybook does not recognise Next.js config

### ISSUE THREAD

**Issue by terrymun** [nrwl/nx#14656]
### Current Behavior

The configuration in the `next.config.js` file does not seem to be respected or parsed by Storybook, but works when serving the site locally. For example, the following barebones config file (the only difference from the default is that I've added `images.remotePatterns`) is not being honoured by Storybook:

```js
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withNx } = require('@nrwl/next/plugins/with-nx');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'http',
        hostname: 'localhost',
        port: '4400',
      },
      {
        protocol: 'https',
        hostname: '**.placeholder.com',
      },
    ],
  },
};

module.exports = withNx(nextConfig);
```

When attempting to use `next/image` using an allowed source, it throws an error on storybook `nx run my-lib:storybook`:

> Invalid src prop (https://via.placeholder.com/400x350) on `next/image`, hostname "via.placeholder.com" is not configured under images in your `next.config.js`

![Screenshot 2023-01-27 at 08 56 17](https://user-images.githubusercontent.com/5593067/215036162-2d095366-7acc-4abd-aec5-df0837e5c7a4.png)

But it works when serving the Next.js site by running `nx run next-js:serve`.

![Screenshot 2023-01-27 at 08 57 37](https://user-images.githubusercontent.com/5593067/215036379-2098cd29-18d6-4a24-a941-ec3642898d90.png)

This suggests that Storybook that is created using the `nx g @nrwl/storybook:configuration [PROJECT_NAME]` command has failed to read settings from `next.config.js`.

### Expected Behavior

The settings in `next.config.js` should also be respected by Storybook. I should not except to receive an error message when using an allowed URL from `images.remotePatterns` in my storybook story.

### GitHub Repo

https://github.com/terrymun/nx-nextjs-storybook-test

### Steps to Reproduce

1. Create workspace: `npx create-nx-workspace@latest --preset=next`
2. Update `next.config.js` to add allowed [`images.remotePatterns`](https://nextjs.org/docs/api-reference/next/image#remote-patterns) so that we can read images served by storybook (from `http://localhost:4400`) and an example remote domain (e.g. `https://**.placeholder.com`:

```js
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
  // NOTE: Manually add `images.remotePatterns`
  images: {
    remotePatterns: [
      {
        protocol: 'http',
        hostname: 'localhost',
        port: '4400',
      },
      {
        protocol: 'https',
        hostname: '**.placeholder.com',
      },
    ],
  },
};
```

3. Generate a new library: `nx g @nrwl/next:lib my-lib`
4. Update the default component so that it uses `next/image` that will rely on the `images.remotePatterns` config from above. Note that the `src` matches the pattern in `images.remotePatterns`:

```tsx
<Image src="https://via.placeholder.com/400x350" width={400} height={350} alt="My image" />
```

5. Update the next-js app `index.tsx` file to consume this component:

```tsx
import { MyLib } from '@my-lib';

export function Index() {
  /*
   * Replace the elements below with your own.
   *
   * Note: The corresponding styles are in the ./index.scss file.
   */
  return (
    <div>
      <MyLib />
    </div>
  );
}

export default Index;
```

6. Run `nx run next-js:serve` and notice that the remote image loads correctly. This is expected behaviour as the Next.js app reads from `next.config.js` correctly.
7. Create a storybook on the `my-lib` package: `nx g @nrwl/storybook:configuration my-lib`
8. Create an example storybook for the `my-lib` package:

```tsx
import type { ComponentStory, ComponentMeta } from '@storybook/react';
import MyLib from './my-lib';

const Story: ComponentMeta<typeof MyLib> = {
  component: MyLib,
  title: 'MyLib',
  parameters: {
    layout: 'centered',
  },
};
export default Story;

const PrimaryTemplate: ComponentStory<typeof MyLib> = () => {
  return <MyLib />
}

export const Primary = PrimaryTemplate.bind({});
```

9. Start storybook: `nx run my-lib:storybook`. Notice that the Storybook will throw an error on an invalid image URL being used by Next.js `<Image>` because it has failed to read the `image.remotePatterns` setting from `next.config.js`

### Nx Report

```shell
Node : 16.18.0
OS   : darwin x64
yarn : 1.22.19

nx : 15.6.2
@nrwl/angular : Not Found
@nrwl/cypress : 15.6.2
@nrwl/detox : Not Found
@nrwl/devkit : 15.6.2
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.6.2
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.6.2
@nrwl/js : 15.6.2
@nrwl/linter : 15.6.2
@nrwl/nest : Not Found
@nrwl/next : 15.6.2
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 15.6.2
@nrwl/react-native : Not Found
@nrwl/rollup : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 15.6.2
@nrwl/web : Not Found
@nrwl/webpack : 15.6.2
@nrwl/workspace : 15.6.2
@nrwl/vite : Not Found
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
```

**Comment by terrymun** [comment]
Just a side note: we also noticed that the svgr plug-in config is also not being recognized by storybook, and it likely has the same root cause.

**Comment by mandarini** [comment]
@terrymun I'll take a look this week! Thanks!

**Comment by terrymun** [comment]
@mandarini Thanks a lot for picking up the ticket and looking into it :)

**Comment by mandarini** [comment]
Hi @terrymun ! I just looked into it!

So, here's why your setup does not work:

1. You need to use the Storybook addon for Next.js
2. You need to use the Storybook addon for `swc`
3. You need to show Storybook where your Next.js config file is

In your case, you have a Next.js app, and your Next.js config file is in that app.
Then, you have a Next.js library, which does not have a Next.js config file, which makes sense, since [Next.js libraries are just React libraries in essence](https://nx.dev/packages/next/generators/library), since if you're using Next.js, the app (a project that is made to be publishable) is the only project type that would have a Next.js config file. 

Makes sense so far?

The way our Storybook configuration generator works is the following:

1. If you want to generate Storybook configuration for a Next.js project, you should (as you have already done, correctly)
 use the [`@nrwl/react:storybook-configuration` generator](https://nx.dev/packages/react/generators/storybook-configuration). That is because for Next.js components we are using React components, so that's the syntax we want to use for generating the stories.
2. Our `@nrwl/react:storybook-configuration` generator will go ahead and install the necessary dependencies for Storybook + React, and it will also generate the `.storybook/` directory which contains the Storybook configuration files and settings, all configured for React
3. Then, our generator will look into your project's `project.json` file to try and infer if you're using React or if you're on a Next.js project. To do that, it will look at the `executor` of your `build` target. If the `executor` of your `build` target is `"@nrwl/next:build"` (as it is for Next.js __apps__), then it will ALSO add the necessary plugins in your `.storybook/main.js` file, so that Storybook can work with Next.js and also find the Next.js config file. You can verify that in your project if you try to generate Storybook configuration for your `next-js` app like this: `npx nx g @nrwl/react:storybook-configuration --project=next-js`. Do that, and look at your `apps/next-js/.storybook/main.js`. You will see that Nx added bot the `'storybook-addon-swc'` and the `'storybook-addon-next'` addons, the latter pointing at your `next.config.js` file!
4. Since you generated your Storybook configuration for a Next.js library, Nx had no way of knowing if it was indeed a Next.js library or just a plain React one. So, it only added the React settings, and omitted the Next.js settings.

What you can do, is add a Next.js config file for your library, and then add the two addons in your `libs/my-lib/.storybook/main.js` file like this:

```
  addons: [
    ...rootMain.addons,
    '@nrwl/react/plugins/storybook',
    'storybook-addon-swc',
    {
      name: 'storybook-addon-next',
      options: {
        nextConfigPath: path.resolve(__dirname, '../next.config.js'),
      },
    },
  ],
```


You may suggest that we add a new `@nrwl/next:storybook-configuration` generator, to account for Next.js libraries, as well, but I think it makes sense to only keep it that way, and integrate it in the React generator. In any case, we will be slowly transitioning to Storybook 7, where the Next.js support is native in the Storybook nextjs builder, so there will be no need for the extra addons!

In any case, thank you very much for filing this issue! It's understandable that there's confusion around this!

**Comment by terrymun** [comment]
Hi @mandarini, thank you so much for looking into the issue and coming back with a step-by-step guide to fix the issue, I really appreciate it. It is exceptionally useful especially for those (like me) who are not familiar with the inner workings.

Just curious tho: this seems to be a recent change because our storybook builds used to recognise the next.config.js app. I know that this is probably not by design, but the broken build with the latest Nx update did puzzle us :)

**Comment by mandarini** [comment]
I see. So you're saying that the exact same setup works with a previous version of Nx? Which version would that be?

**Comment by terrymun** [comment]
@mandarini Yeah, it used to work without issue, but I cannot remember which version... but I can verify that your solution works (even on an actual project that I am working on right now), so consider that an issue that's successfully resolved ;)

**Comment by mandarini** [comment]
Perfect, thanks!!!! :D If you ever do find that version that it used to work, just post it here, so that I can see what broke it!! 

Again, that you very very much for the detail you put in that bug report. I wish all bug reports were like this!!!!
