### ISSUE TITLE
Error: Module build failed - Babel plugins passed to the 'include' option are not valid

### ISSUE THREAD

**Issue by robinlarsson** [nrwl/nx#14689]
### Current Behavior

Can't start `nx serve` after upgrading with migration to v. 15.6.3 due to `Error: Module build failed`.

Babel plugins passed to the 'include' option are not valid.

### Expected Behavior

The web server should start after migration.

### Steps to Reproduce

Not sure what's needed, as I tried with a fresh project but can't reproduce. 

However, in my project I ran the migration in steps and tested each one of them. Finding the error first in `chore:ngrx-component-migration-15-beta`.

1. Run migrations from 14.3.6 to v. 15.6.3 (stop at ngrx-component-migration-15-beta).
2. Start the web server with `nx serve`

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component: 15.0.0
         @ngrx/component-store: 15.0.0
         @ngrx/effects: 15.0.0
         @ngrx/entity: 15.0.0
         @ngrx/router-store: 15.0.0
         @ngrx/store: 15.0.0
         @ngneat/spectator: 11.1.0
         @ngrx/schematics: 15.0.0
         @ngrx/store-devtools: 15.0.0
         @storybook/angular: 6.5.16
         @testing-library/angular: 12.0.2
```

### Failure Logs

```shell
/node_modules/@angular-devkit/build-angular/node_modules/css-loader/dist/runtime/sourceMaps.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: [BABEL] /Users/robinlarsson/Develop/frontend/node_modules/@angular-devkit/build-angular/node_modules/css-loader/dist/runtime/sourceMaps.js: @babel/preset-env: The plugins/built-ins '@babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods' passed to the 'include' option are not
    valid. Please check data/[plugin-features|built-in-features].js in babel-preset-env (While processing: "base$0$0")
```

### Additional Information

No custom babel config used.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, we can't reproduce the issue with the information provided. You mention you can't reproduce it in a fresh project, so it's probably something specific to your project. Could you share the project? Or a slim-down version of it where any secret or relevant info that can't be shared is removed?

Due to the nature of the issue, you can also try recreating the `yarn.lock` file and see if it makes a difference. Maybe something funky happened with the package manager resolution for babel packages.

**Comment by robinlarsson** [comment]
Thank you for the reply. 

Great tip with the lock file. 

One issue was that an old migration.json file was still in the repo. Cleaned that up and our resolutions cause issues as well. 

Closing this issue.

**Comment by prewk** [comment]
Same team here, I can clarify our solution (and some extra info about the problem):

**Problem**: It turned out the errors started at the first `yarn install` step, after running `yarn nx migrate latest` and `yarn`. So turned out to not be the migration step mentioned.

**Solution**: From scratch, upgrade all the packages incrementially (jumped some patches at a time, then some minors, then major etc). Finally ended up with the same versions that were in nx' suggested `package.json` we got from `migrate latest`.

The lockfile caused by those incremential installs worked. So the migration could be done by using _that_ instead as a starting point.

So, the thing to blame is probably some undeterministic behavior of the complex node_modules process and yarn.
