### ISSUE TITLE
`nx:run-commands` and `nx:run-script` don't execute traps

### ISSUE THREAD

**Issue by anthonygood** [nrwl/nx#14737]
### Current Behavior

BASH traps aren't called when the script is interrupted with Ctrl-C.

With the following script:
```sh
trap cleanup EXIT
cleanup() {
  echo "cleanup"
  exit 0
}

echo "1"
echo "2"
sleep 3
echo "3"
```
When run with `nx:run-commands` the trap is executed if the script exits normally, outputting:
```
1
2
3
cleanup
```
But when interrupted with Ctrl-C it aborts immediately:
```
1
2
^C% 
```
When executing the same script via `yarn`, the trap is invoked correctly:
```
1
2
^Ccleanup
```

### Expected Behavior

The trap should be invoked when the process is interrupted using Ctrl-C (same behaviour as `yarn`).

### Steps to Reproduce

1. Run a script with a trap on EXIT
2. Interrupt the script run with Ctrl-C
3. Trap won't execute

### Nx Report

```shell
N/A
```

**Comment by AgentEnder** [comment]
Hey @anthonygood! We just took a look at this and could use some further clarifications.

1. In our tests, the trap **_is_** executed, but the output isn't forwarded through to the terminal. I **_think_** this is because the node process is shutting down at that point. You can see the behavior in action by changing the trap to `touch` a file. It gets created 😄.
1. We can't reproduce that yarn **_fully_** supports this. In our local tests, running `yarn script-with-trap` doesn't echo out the cleanup function, but supports traps that create files like we do above.

Can you check if the trap is actually functioning for you, but the output is swallowed maybe? Is this enough for your use case?

On the other hand, if it isnt, can you provide your yarn version as well as `nx report`'s output please?

----

One other, potentially unrelated note, is that using these traps in this way **_will_** make it to where your development environment is not super portable. They behave differently on different OS's. I'd recommend seeing if theres a more portable solution for your use case, but I also understand that portability isn't a hard requirement in every repository.

**Comment by anthonygood** [comment]
Thanks for looking into this. I can double check whether it's just a case of the output getting swallowed. Interesting observation regarding `yarn` exhibiting different behaviour between our respective environments. I just tried with `npm run` and that included the trap output, I would be interested to know if it's related to NPM/Node version.

I appreciate that traps are pretty shell-specific and probably not widely used. Maybe NX can solve the problem another way?

Our use case is running some tests that require some setup and teardown. We'd actually scripted this using `run-commands` with something like:

```sh
   "tests": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "docker-compose",
          "wait-on tcp:5432",
          "nx run app:test-script",
          "docker-compose down"
        ],
        "parallel": false
      }
    },
```
The main problem is that if the tests fail, the last command doesn't run. What we really want is to always run all the commands, but specifically use the exit code of the tests. This is why we ended up wrapping the above in BASH with a trap.
