### ISSUE TITLE
Code on 2-project-graph page contains ESLint errors

### ISSUE THREAD

**Issue by NikitaIT** [nrwl/nx#14785]
### Documentation issue

- [x] Reporting a documentation bug

### Is there a specific documentation page you are reporting?

https://nx.dev/react-standalone-tutorial/2-project-graph

### Additional context or description

`import { Banner } from '@store/shared/ui';` in cart section

> ESLint: Imports of apps are forbiddeneslint@nrwl/nx/enforce-module-boundaries

P.S. Maybe it's a bug with ESLint, because it works without errors after vscode restart. If someone will be able to reproduce
this, we should add some disclaimer about this behaviour.

**Comment by NikitaIT** [comment]
This seems to be due to the definition of default linting rules when the repository is initialized. I just disabled this rule for the time being, although it obviously needs to be configured prior to creating modules.

**Comment by isaacplmann** [comment]
The issue is that the typescript paths have been changed in `tsconfig.base.json` but the typescript hasn't picked them up yet.  When you restart VS Code, the typescript server is also restarted.  You can restart the typescript server without restarting all of VS Code from the command pallette (Command shift P) "Typescript: Restart TS Server".
