### ISSUE TITLE
@nrwl/js copies dependencies with fixed version only

### ISSUE THREAD

**Issue by arthurgubaidullin** [nrwl/nx#14878]
### Current Behavior

If you specify a version with ^ in the main package.json, then it will be ignored in the built package.

### Expected Behavior

It is expected that in the assembled project there will also be a version with a caret.

### GitHub Repo

https://github.com/arthurgubaidullin/embed-dependencies

### Steps to Reproduce

1. `npx nx run-many --target=build`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.6.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @arthurgubaidullin/nx-embed-dependencies
   ---------------------------------------
   Community plugins:
```

**Comment by mi-kei-la** [comment]
Same issue here. I found that it worked well with @nrwl/js up to 15.6.1 or 15.6.2 (cant remember), so it could be a minor change done in the latest version

**Comment by meeroslav** [comment]
Hey @arthurgubaidullin, thank you for reporting this. I'll explain why this is not an issue but a design decision.

## The explanation

The version defined in your lock file and installed in your `node_modules` is the version we can guarantee that everything works with. Bumping a patch could break things. That's why when deploying applications, we enforce fixed versions. The latest Nx also provides the possibility to generate pruned lock files which makes this fixed version enforcing even more accurate.

Not only this leads to a more secure set of dependencies, but also installing deps on CI/CD is faster because the package manager doesn't have to recompute the correct versions every time.

## Is there a workaround?

While fixed versions make sense for deploying apps, for publishing libraries, you will most likely want to be less restrictive. Typical ranges for released packages are even less stringent than their parent `package.json`.  

For example, your repo can say it depends on `typescript: ^4.8.4` while your published package should be `typescript: >= 4`.

To do this, you need to create a `package.json` in your project's folder where you can define arbitrary ranges for the packages. The resulting built `package.json` will respect the ranges you specified there as well as scopes (dev, peer, etc.) but add any missing packages that you might have skipped.

**Comment by arthurgubaidullin** [comment]
@meeroslav Thank you. I will check the workaround.
