### ISSUE TITLE
Support for Stencil 

### ISSUE THREAD

**Issue by Cammisuli** [nrwl/nx#1487]
Now that Stencil has reached it's 1.0.0 milestone, what's the feasibility of adding support for Stencil as a schematic?

### Reasoning
Since Stencil is a compiler for creating web components I feel that support for it in a Nx Workspace is a great fit. These components could be libraries that have zero dependencies on any framework.

They're also great for publishing separately. Basically the best a library can get.

Since we have support for React here, why not Stencil?

### Links
https://stenciljs.com/

### Help
If adding Stencil (or pretty much any other web component library) is in the interest of this project, I'll be more than willing to help create the schematics/research needed to get it in. 

Web components is something I feel that could help a lot of places with their reusable components.

**Comment by xmlking** [comment]
Svelte is also an option for adding micro-apps

**Comment by vsavkin** [comment]
I'm a big fan of both Stencil and Svelte. 

We made Nx 8 plugable. Instead of having a single @nrwl/schematics, we have @nrwl/react, @nrwl/angular etc. So the foundations are in place. Nx can support Stencil just as well it supports Angular.

So I'm happy to see this support implemented but  I don't think we should add support for stencil or svelte into the Nx repo.

Instead of `@nrwl/stencil` I would rather see `@stencil/nx`. So basically I think Ionic folk should own this. 

I'm happy to help them make this happen. 

So please open an issue at https://github.com/ionic-team/stencil and link this issue there. I'm planning to get in touch in Adam and Mike soon to talk about it.

**Comment by ronnyek** [comment]
I for one would like to see this too

**Comment by jackbravo** [comment]
And what about svelte? Should it also be @svelte/nx and a issue be opened in svelte's repo? And not just svelte, but sapper too (their next/nuxt framework).

**Comment by DominikPieper** [comment]
Any news on this?

**Comment by Jimmysh** [comment]
@DominikPieper I code stencil-toolkit
https://github.com/aiao-io/aiao/tree/develop/libs/stencil-toolkit 
demo
https://github.com/aiao-io/aiao/tree/develop/integration/stencil-toolkit-nx
Enjoy!
