### ISSUE TITLE
🐛 BUG: @nrwl/jest unable to change ts compilation options of `jest.config.ts`

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx#14888]
### Current Behavior

If you want to read the path mapping from a tsconfig.json and try to import it you are facing
```
error TS2732: Cannot find module './tsconfig.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```
but since there is no way to change it in the executor you cannot do this.
This is necessary to enable jest to use the same path mappings in the moduleNameMapper as typescript.

### Expected Behavior

Either somehow find the path mappings automagically by default or make the tsconfig that is used to read the jest.config.ts extendable.

### Steps to Reproduce

1. Add json import to jest.config.ts
2. Try to run tests

### Nx Report

```shell
Node : 16.14.2
   OS   : win32 x64
   pnpm : 7.26.3

   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.30.0
```

### Failure Logs

```shell
>  NX   Jest: Failed to parse the TypeScript config file <projectRoot>\jest.config.ts

     TSError: ⨯ Unable to compile TypeScript:
   <projectRoot>/jest.config.ts:2:26 - error TS2732: Cannot find module './tsconfig.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
   
   2 import jestTSConfig from './tsconfig.json';
                                             ~~~~~~~~~~
```
```


### Additional Information

_No response_

**Comment by barbados-clemens** [comment]
did you try adding the resolveJsonModule to your tsconfig.spec.json, might also need to add it as a part of the files/includes?
you can try using `const json = require('./my-jsonfile/json');`

if that doesn't work I assume this is because jest uses ts-node under the hood to read the jest.config.ts which is probably looking for tsconfig.json in the process.cwd().

you can tell ts-node what tsconfig to use with the `TS_NODE_PROJECT=path/to/tsconfig.spec.json nx test <blah>` as a crude work around. 

tbh I'd just use a require('myjsonfile.json'); 

because even if we decided to set this value in the nrwl/jest executor. it can be customized by anyone at any point. and there isn't a guaranteed value in the jest.config.ts that would say what tsconfig to use.

**Comment by barbados-clemens** [comment]
use valid work around on using require('jsonfile.json') or readFileSync('jsonfile.json') or manually setting the TS_NODE_PROJECT value.
