### ISSUE TITLE
project configured with package.json should have sourceRoot and type configurable

### ISSUE THREAD

**Issue by GaryB432** [nrwl/nx#14898]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

My  generator needs `sourceRoot` from the project configuration to generate my user's files. [see my issue](https://github.com/GaryB432/gb-nx/issues/8)  However if their project is configured with an `nx` section in `package.json` rather than in `project.json` it seems that the `sourceRoot` (and `root`) are set to "." even if I add those values to the aforementioned `nx` section.

## Motivation

My generator will run with a `package.json` configuration

## Suggested Implementation

add `sourceRoot` (and `type`) to the schema and handling of the `package.json.nx` entry.  `root` being locked at "." makes sense.

## Alternate Implementations

I can just have my users move their configuration to `project.json` and use `run-commands` to re implement the `package.json` scripts. I didn't know if respecting `sourceRoot` in `package.json.nx` is antithetical to your awesome product!  just lmk.

**Comment by GaryB432** [comment]
bump

**Comment by GaryB432** [comment]
bump

**Comment by jaysoo** [comment]
Hi @GaryB432, sorry for the the late reply. We would rather not use the `sourceRoot` property for generators and executors if it's not needed. The `root` property is also not needed since it is inferred by Nx already (you can remove it from `project.json` if it exists).

For generators, you already know the project root from the project config.

```ts
const projectConfiguration = readProjectConfiguration(tree, projectName);
console.log(projectConfiguration.root)
```

As for `sourceRoot`, you can either hard-code it in your generator (if you know it's always `<project-root>/src` for example). Or let the user pass in the directory option. e.g. `nx g my-plugin:my-generator --directory=libs/lib-a/src`.

Note that `sourceRoot` is not guaranteed to exist for all projects either, so it's better to not assume this property exists.
