### ISSUE TITLE
NX Graph group-by-folder acts strangely

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#15030]
### Current Behavior

![image](https://user-images.githubusercontent.com/13711224/219122212-40d8975e-63dd-4bb6-8983-5d29abf7fc53.png)

The project structure is as follows:
```
/apps
	/merchant-admin/project.json
	/merchant-admin-e2e/project.json
/packages
	/icons/project.json
	/rating-icons/project.json
	/shopify-node-api/project.json
	/nx-plugin/project.json
	/nx-plugin-e2e/project.json
/project.json
```

### Expected Behavior

The project graph should group all projects under `packages` and `apps` together, respectively.

### Steps to Reproduce

1. `pnpm nx graph`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.19.3
   OS   : darwin x64
   pnpm : 7.21.0
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.5.1
   @nrwl/react : 15.5.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   	 @loox/nx-plugin
   ---------------------------------------
   Community plugins:
```

### Additional Information

The repository is in a migration process to NX and was not created with `create-nx-workspace`.

I suspect that the issue might be caused by the root project (since it's a fairly new feature to NX itself), but I've not checked the codebase of the graph project (it's a little much for me to investigate, compared to NX itself).

I've looked at `nxdeps.json`, and all the projects seem to have `root` setup properly, which is what I assume is the source-of-truth for the group-by-folders feature.

**Comment by philipjfulcher** [comment]
I suspect there's some misconfiguration somewhere in your workspace. `apps` and `packages` should probably be configured in your `workspaceLayout`. They'll be treated as special cases and not included in the "Group By Folder" option. Grouping all of your apps and libs together like that makes the graph harder to read because they have to fit inside a smaller container. By leaving those special cases out (since all apps and libs will be nested this way in most cases), we can spread out the graph across a larger area and make it easier to read.

Given that, it looks like `nx-plugin-e2e` is the one that's out of place, since it's being grouped under `packages` but probably shouldn't be. Can you take a look at the `project.json` for that project and make sure the `packageType` is set to `library`? When we determine the grouping, we consider the type of the project and check for the appropriate configuration in `workspaceLayout`.

**Comment by gioragutt** [comment]
Technically the workspaceLayout is right, it's apps/packages. But you're right about nx-plugin-e2e being out of place. Do you believe that moving it to apps will resolve this issue?

**Comment by gioragutt** [comment]
Update: I've moved nx-plugin-e2e to apps (using `nx generate @nrwl/workspace:move nx-plugin-e2e --projectName=nx-plugin-e2e`), now nothing happens when I turn `Group By Folder` on.

Does the feature only work when the projects are nested further down in the apps/libs folder?

**Comment by philipjfulcher** [comment]
@gioragutt - That's correct. Given an apps directory like this:
```
apps
    frontend
        public
        admin
    backend
        auth
```
You'd see the projects nested under `frontend` and `backend`. Further nesting of directories would also be nested under those two. The `Group by Folder` ignores whatever you have configured as your `workspaceLayout` directories.

**Comment by gioragutt** [comment]
Gotcha. I hoped I'd be able to start at the root of each of them, but I get that decision
