### ISSUE TITLE
TypeError: (0 , path_1.join) is not a function

### ISSUE THREAD

**Issue by sherry-li-or** [nrwl/nx#15041]
![image](https://user-images.githubusercontent.com/33445287/219309621-db7ac948-14bb-4569-8556-89e45b630494.png)

### Environment

- Nx Console version:
- VSCode version:

**Comment by jdgriffith** [comment]
`nx report` is also broken for me after encountering this same error.

**Comment by AgentEnder** [comment]
Can you get the versions of Nx and any NRWL packages from your package.json,  as well as node version, package manager + version, etc

**Comment by jdgriffith** [comment]
Sure thing.

pnpm: `7.26.3`
node: `18.*`
typescript: `5.0.0-dev.20230226`

```
    "@nrwl/cli": "15.7.2",
    "@nrwl/cypress": "15.7.2",
    "@nrwl/esbuild": "15.7.2",
    "@nrwl/eslint-plugin-nx": "15.7.2",
    "@nrwl/jest": "15.7.2",
    "@nrwl/js": "15.7.2",
    "@nrwl/linter": "15.7.2",
    "@nrwl/nest": "15.7.2",
    "@nrwl/node": "15.7.2",
    "@nrwl/react": "15.7.2",
    "@nrwl/web": "15.7.2",
    "@nrwl/workspace": "15.7.2",
    "nx": "15.7.2",
```

So I was able to fix this FYI after trying a number of different things. And I think it's possibly related to one of two things I tried:

1. I reverted typescript to the latest 4.9.* stable version instead of the 5.0 dev version they released.
2. I switched to Node 19 from Node 18.*.

Once I made those changes it started working.  

So now I have:

```
node: `19.7.0`
typescript: `4.9.5`
```

Hope this helps.

**Comment by AgentEnder** [comment]
I'm pretty suspicious of the typescript dev version. The thing failing here is essentially just `require('path').join` not being a function. This is a default node builtin thats certainly not changed anytime recently...

I don't think this is an issue on our side, more likely on TS. I'm going to close this out, if anyone can repro it without the TS dev version, we can investigate more.
