### ISSUE TITLE
Failed to migrate from 12.2.0 to 13.4.1

### ISSUE THREAD

**Issue by core2drew** [nrwl/nx#15063]
### Current Behavior

I created a workspace v12.2.0 to support our angular project with version 11.
But when I tried to migrate it to version 13.4.1

I encounter Failed to run update-jest-config-to-use-util from @nrwl/jest. This workspace is NOT up to date!
So I saw a solution that you can skip it and do it manually.

But after trying again I encounter another failed migration step

### Expected Behavior

I was expecting to migrate it without any problem

### Steps to Reproduce

1. Create new workspace with 12.2.0 version
2. Migrate to 13.1.4

### Nx Report

```shell
Node : 16.15.0
  OS   : win32 x64
  npm  : 8.5.5

  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.6
```

### Failure Logs

```shell
NX   Failed to run migration-v12-activated-route-snapshot-fragment from @angular/core. This workspace is NOT up to date!
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

There was an issue with Nx 15.7.0 and 15.7.1 that was causing this (https://github.com/nrwl/nx/issues/14990). The issue was addressed in 15.7.2. The `nx migrate` command works by always installing the latest version of `nx` in a temp dir and running the `migrate` command from that. That's why even though you are migrating older versions, it was still affected by the issue introduced in latest.

Can you try running the migration again and let us know how it went? If it fails, please run it with the `--verbose` flag so the stack trace is printed and share it here.
