### ISSUE TITLE
skipFormat option ignored ?

### ISSUE THREAD

**Issue by jeffschulzusc** [nrwl/nx#15134]
### Current Behavior

i generate a new angular standalone component in a lib:

`nx g @nrwl/angular:library host --directory=uscsf --simpleName --skipTests --unitTestRunner none --standalone --style=scss --skipFormat`

however, nx.json, tsconfig.base.json, and project.json(s) files all get formatted ... 
i also tried --skipFormat=true

### Expected Behavior

should not format any files, just create the lib

### Steps to Reproduce

1.
nx g @nrwl/angular:library host --directory=uscsf --simpleName --skipTests --unitTestRunner none --standalone --style=scss --skipFormat

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nest              : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.0.0
   @ngrx/entity         : 15.0.0
   @ngrx/router-store   : 15.0.0
   @ngrx/schematics     : 15.0.0
   @ngrx/store          : 15.0.0
   @ngrx/store-devtools : 15.0.0
```

**Comment by Coly010** [comment]
@jeffschulzusc  I can't reproduce this on a new repository. Can you provide repository that i can clone that will reproduce this issue?

It should be mentioned that `tsconfig.base.json` will be updated as it needs to add the new path to your library. If it was previously formatted, using `skipFormat` may result in the new file contents being in a different format than was previously stored.

i.e `JSON.stringify(tsconfig, null, 2)` vs `prettier`

**Comment by jeffschulzusc** [comment]
https://github.com/jeffschulzusc/usc-skipformat-sample.ws

```
1. created this ws
npx create-nx-workspace --preset=apps

2. add angular support:
npm install -D @nrwl/angular

3. add mfe host
nx g @nrwl/angular:host home --directory=mfe --style=scss --skipTests=true --unitTestRunner none --e2eTestRunner none --skipFormat

4. add sample app
nx g @nrwl/angular:app sample --style=scss --skipTests=true --unitTestRunner none --e2eTestRunner none

5. add mfe remote 
nx g @nrwl/angular:remote kitchen --directory=mfe --host=mfe-home --style=scss --skipTests=true --unitTestRunner none --e2eTestRunner none --skipFormat  

PROBLEMS: 
1. apps/sample/project.json path to schema is incorrect ... should be '../../node_modules...'
2. even though i had option --skipFormat, it reformatted apps/sample/project.json 
3. apps/mfe/home/src/app/app.routes.ts failed to write trailing ] for Routes array, so does not compile
```

reformatted:
![Screenshot 2023-02-21 at 4 16 43 PM](https://user-images.githubusercontent.com/91924637/220489863-714fe958-b1a0-424f-a8d3-9518ce3e260e.png)


build error:
![Screenshot 2023-02-21 at 4 25 19 PM](https://user-images.githubusercontent.com/91924637/220489899-7a613c97-fb53-42fd-802f-092f183319c0.png)  

thanks :)

**Comment by Coly010** [comment]
The `skipFormat` issue here is a known issue, and it occurs when you sometimes use `skipFormat` and sometimes don't use it.

The problem is, that with Angular schematics etc, in our Ng CLI Adapter layer, we have to collect all the project.json files into a single in-memory angular.json configuration object that can be used by Angular Builders and Schematics. 

After those builders/schematics have completed execution, we have to split the angular.json back into project.json files.

If `skipFormat` is used, then we just run `JSON.stringify(content, null, 2)` when writing those files.

When skipFormat is not used, prettier gets a run over the files.


The problem you're seeing with some project.json files having formatting changes is because they had previously had a prettier pass on them, changing their format from simply `JSON.stringify(content, null, 2)` to the format defined by the `.prettierrc`.

Therefore, when skipFormat is used after this, there's a formatting difference created for that project.json file. Unfortunately, there's nothing we can do about that at this time.

The routing issue you've mentioned is more problematic and I have created a PR to fix that.

**Comment by jeffschulzusc** [comment]
thanks much

"... we have to split the angular.json back into project.json files ..." 
not clear why would need to do this (i.e. for existing project.json(s) unrelated to the generator output) 
but anyways is not a big deal
