### ISSUE TITLE
Jest error in summary of nx output from failed tests

### ISSUE THREAD

**Issue by DzixxxVizlib** [nrwl/nx#15172]
We have enabled jest thresholds and it's a little bit problematic to get reason of the jest failure (no met threshold) cause we need to scroll whole file ... 

```
[...] ----------|---------|----------|---------|---------|-------------------
[...] File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
[...] ----------|---------|----------|---------|---------|-------------------
[...] All files |   72.91 |     37.5 |   72.22 |   64.28 |                   
[...]  index.ts |   72.91 |     37.5 |   72.22 |   64.28 | 12-19,36-41       
[...] ----------|---------|----------|---------|---------|-------------------
[...] Jest: "global" coverage threshold for lines (100%) not met: 64.28%    <----- THIS IS WHAT WE"RE LOOKING FOR
[...] Test Suites: 1 passed, 1 total
[...] Tests:       xxx passed, xxx total
[...] Snapshots:   0 total
[...] Time:        xxx s
[...] Ran all test suites.

// other libraries tests, logs and summaries

---------

[...]  >  NX   Running target test for xxx projects failed
[...] 
[...]    Failed tasks:
[...]    
[...]    - my-library:test
[...]  


```

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'd like to see in summary jest error PWEASE 😂 

## Motivation
I'd like to not search through all logs from tests

## Suggested Implementation

Not sure if achievable 🤔 
```
[...]  >  NX   Running target test for xxx projects failed
[...] 
[...]    Failed tasks:
[...]    
[...]    - my-library:test
[...]       -- [Jest]: "global" coverage threshold for lines (100%) not met: 64.28%
[...]    - my-library2:test
[...]       -- [Jest]: "global" coverage threshold for lines (100%) not met: 64.28%

```

## Alternate Implementations

No idea :elmo_shrug:

**Comment by barbados-clemens** [comment]
Hi @DzixxxVizlib, thanks for the feature request and I see how that can be helpful when digging through multiple failed project. But it's a bit of a tricky problem to solve as the @nrwl/jest plugin isn't able to change the display output of jest and Nx. all it does is report if a task passed successfully or not and nx core is responsible for capturing the output and displaying the info and list of failing projects. 

So in order to implement that would require a big architectural change on how Nx and executors communicate which is something we are not interesting in doing right now. 

that being said, I think a good alternate measure would be [leveraging Nx Cloud](https://nx.dev/nx-cloud/intro/what-is-nx-cloud) as it makes reading/parsing logs much easier, especially in larger runs like `nx affected`.

For example, you can see the individual projects success/fail and then view that projects individual logs. It's a feature I use daily. 

Once again thanks for the feature request and like the ideas so keep them coming!
