### ISSUE TITLE
unable to use custom configurations in `nx serve` for angular:module-federation-dev-server executor

### ISSUE THREAD

**Issue by RichFinn-WTW** [nrwl/nx#15212]
### Current Behavior

In an angular module federation project that was set up using the basic steps defined in [Advanced Angular Micro Frontends with Dynamic Module Federation](https://nx.dev/recipes/module-federation/dynamic-module-federation-with-angular), when running `nx serve dashboard -c customConfig`, where `customConfig` is a custom configuration defined in the `serve` section of `project.json`, I'm receiving the error:
```
[path_removed]\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:76
                        throw new Error(`Configuration '${configuration}' is not set in the workspace.`);
                              ^

Error: Configuration 'customConfig' is not set in the workspace.
    at Object.getOptions ([path_removed]\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:76:31)
    at WorkspaceNodeModulesArchitectHost.getOptionsForTarget ([path_removed]\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:162:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
```

`project.json` serve section looks like this:
```json
"serve": {
  "executor": "@nrwl/angular:module-federation-dev-server",
  "configurations": {
    "production": {
      "browserTarget": "dashboard:build:production"
    },
    "development": {
      "browserTarget": "dashboard:build:development"
    },
    "customConfig": {
      "browserTarget": "dashboard:build:development"
    }
  },
  "defaultConfiguration": "development",
  "options": {
    "port": 4200,
    "publicHost": "http://localhost:4200"
  }
},
```

### Expected Behavior

custom `nx serve` configuration should work

### GitHub Repo

https://github.com/RichFinn-WTW/nx-serve-issue

### Steps to Reproduce

1. clone github repo above and run `nx serve dashboard -c customConfig`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : win32 x64
   yarn : 1.22.19

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
```

### Additional Information

I noticed when I specify a configuration that does _not_ exist in the `configurations` section, it will fall through to the `defaultConfiguration`, so it seems that it's seeing the custom configuration but not using it.

If I switch the executor to `@nrwl/angular:webpack-dev-server` the custom configuration is found and works as expected. Also, when specifying `development` as the config to use, it works fine, so I figured that the custom config might need to be defined in the host `build` and `serve` sections as well as the remote `build` and `serve` sections. This is how the code exists in the repo now.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `@nrwl/angular:module-federation-dev-server` executor serves multiple projects, the host and any associated remotes. By default, the executor runs the remotes' `serve-static` target unless you provide [the remote in the `devRemotes` option](https://nx.dev/packages/angular/executors/module-federation-dev-server#devremotes), in which case, it runs the `serve` target of the remotes. That's where the `customConfig` is missing in your setup. You must set that configuration in the `serve-static` target of the `login` project:

```json
// apps/login/project.json
{
  ...
  "targets": {
    ...
    "serve-static": {
      ...
      "configurations": {
        ...
        "customConfig": {
          "buildTarget": "login:build:development"
        }
      }
    }
  }
}
```

You don't need to define that config in the `build` targets unless you want to use it. You need it in the remotes' `serve` and `serve-static` targets which are scheduled by the host run depending on the values provided to `devRemotes`.

Please note the repo currently has a typo in the `serve` target of the `login` project. It has `dashboard:build:development` but needs to be `login:build:development`.

I'm going to close this since the executor is working as expected.

**Comment by RichFinn-WTW** [comment]
Thank you @leosvelperez for the good explanation! My error was indeed due to the missing configuration in the `serve-static` target, and I can confirm that adding it resolved my issue.

Also, thanks for pointing out my typo :man_facepalming:

Updated my repo with the fixes for posterity
