### ISSUE TITLE
jest resolver resolves to wrong file

### ISSUE THREAD

**Issue by richard-ling** [nrwl/nx#15312]
### Current Behavior

When resolving path './foo.js', if './foo.js' does not exist but '../foo.js' exists, the resolver will incorrectly resolve to '../foo.js'.

### Expected Behavior

resolver should be unable to resolve the file

### GitHub Repo

https://github.com/nrwl/nx

### Steps to Reproduce

1. Use`npx create-nx-workspace@latest` to create an angular standalone app called `foo`. Accept all defaults.
2. In `src/app/app.component.spec.ts`, add a mock as follows
    `jest.mock('./main', () => undefined);`
3. Try `npx nx test foo`

**Expected result**: test suite should fail to run, with an error `Cannot find module './main' from 'src/app/app.component.spec.ts'`

**Actual result**: The tests will pass. Tracing the code, the file found by '@nrwl/jest/plugins/resolver' is the existing file `src/main.ts`, i.e. `../main.ts`.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   npm  : 8.3.1
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.8.4
```

### Additional Information

This line in the jest resolver seems suspicious to me

        return ts.resolveModuleName(path, options.basedir, compilerOptions, host)
            .resolvedModule.resolvedFileName;

`options.basedir` has the value `src/app` which is a directory, but the receiving parameter in `ts.resolveModuleName` is named `containingFile`. If `src/app` is considered as a file, then `src/main.ts` would be a good resolution for `./main.ts`.

Changing this line to

        return ts.resolveModuleName(path, options.basedir + '/some-file', compilerOptions, host)
            .resolvedModule.resolvedFileName;

gives the expected behaviour, `./main' cannot be resolved anymore.

**Comment by barbados-clemens** [comment]
hi @richard-ling thanks for the issue report, 

I am seeing what you're saying the resolver is resolving to. 

i.e.
```js
{
  path: './main',
  baseDir: '/Users/caleb/Work/sandbox/jest-resolve-bug/src/app',
  resolved: '/Users/caleb/Work/sandbox/jest-resolve-bug/src/main.ts'
}
```

when I switch to options.rootDir I do get the error expected that the import doesn't exist. 

<img width="853" alt="error saying ./main doesn't exist" src="https://user-images.githubusercontent.com/23272162/222916954-18c9dada-86ca-4d7f-bcfd-2edae005c94e.png">

but I will say I am a bit confused as to why it was basedir instead of rootDir, as for nx the rootDir is always going to be the projectRoot is could be because I don't fully understand the finer details of jest + nx

since we do pass the rootDir for pulling the tsconfigs.

changing this value in the Nx repo doesn't seem to break anything, but there are a lot of various testing configurations out there that this could break for people so I'll need to test a lot more before agreeing to making this change.
