### ISSUE TITLE
Migrating angular cli application to NX

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#15378]
### Current Behavior

The current project is a angular "14.2.12" project.. when I try to run `ng add @nrwl/angular@14.2.1` I get the following error:
`Cannot parse angular.json: (0 , workspaces_1.toNewFormat) is not a function`

I have checked the angular.json file and it looks fine (no parsing error) so I'm not sure what is going on here..

### Expected Behavior

I expect a nx.json file to be created and some migration steps to be performed

### Steps to Reproduce

1. N/A

### Nx Report

```shell
N/A
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Angular projects on version 14.2.x should at least use Nx 14.6.0. That said, since Nx 15.7.0 we now support Angular v14 and v15 on the latest version of Nx. So, it's recommended to use the latest version of Nx when you are on those versions of Angular and migrate running `npx nx@latest init` or `ng add @nrwl/angular@latest` on your Angular CLI workspace.

For more info on the versions see [Nx and Angular Versions](https://nx.dev/packages/angular/documents/angular-nx-version-matrix).

**Comment by mackelito** [comment]
Thx for the replay..
when trying with v15 it does perform some actions but I still face some problems..
````
ng add @nrwl/angular@15                                          
ℹ Using package manager: npm
✔ Package information loaded.

The package @nrwl/angular@15 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
[signing-site] No e2e project was migrated because there was no "e2e" target declared in the "angular.json".
[signing-site] The tsConfig file "src/tsconfig.app.json" specified in the "build" target could not be found. Skipping updating the tsConfig file.
[signing-site] The path "src/karma.conf.js" does not exist. Skipping.
[signing-site] The path "src/tsconfig.spec.json" does not exist. Skipping.
[signing-site] The tsConfig file "src/tsconfig.spec.json" specified in the "test" target could not be found. Skipping updating the tsConfig file.
[signing-site-dev] No e2e project was migrated because there was no "e2e" target declared in the "angular.json".
[signing-site-dev] The path "src/tsconfig.app.json" does not exist. Skipping.
[signing-site-dev] The tsConfig file "src/tsconfig.app.json" specified in the "build" target could not be found. Skipping updating the tsConfig file.
[signing-site-dev] The path "src/karma.conf.js" does not exist. Skipping.
[signing-site-dev] The path "src/tsconfig.spec.json" does not exist. Skipping.
[signing-site-dev] The tsConfig file "src/tsconfig.spec.json" specified in the "test" target could not be found. Skipping updating the tsConfig file.
Cannot create a new project signing-site-e2e at apps/general-signing-site-e2e. It already exists.
`````
I guess it's fine that the e2e project has problems even if it is declared (I think it's bad config) but no nx.json is generated.. I would expect it to be!(?)

**Comment by leosvelperez** [comment]
According to those logs, the `nx.json` was not generated because an error was thrown and the migration was halted. If you think there's a bad config, please correct it first and then retry with the migration.

A less invasive migration (and our recommendation) is to run `npx nx@latest init`. That one doesn't move projects and folders around. It leaves your workspace structure as is and performs minimal setup to have Nx working.

**Comment by mackelito** [comment]
We already have a NX workspace up and we are now moving the projects into it.. so in this case my understanding was that I should use this other approach?

**Comment by leosvelperez** [comment]
Sure. If you have an existing workspace and it's using the `apps` and `libs` layout (integrated monorepo), then it's better to do a similar migration to the other repo and then, move the projects.

Now, if you already have another Nx workspace you're moving these new one's projects into, be sure to be using the same versions for all of them. This is not the typical scenario described in the docs, so you need to keep in mind some extra considerations like the version used. Otherwise unexpected issues can arise. As mentioned in a previous comment, for Nx 14.2.x you need to at least use Nx 14.6.0. Check the versions on your existing monorepo and ensure they are the same ones you are using in the workspace you are migrating. Also, the Angular version should match as well.

While in the latest version of Nx we have support for Angular v14 and v15, not every Nx 15 version supports it. That support was added in Nx 15.7.0. Make sure that whatever Nx version you choose to migrate to, is compatible with the Angular version you have [Nx and Angular Versions](https://nx.dev/packages/angular/documents/angular-nx-version-matrix)

Make sure you correct the config you think is bad and try again. If you're having more issues and you think the generator is wrong, please provide a repro so we can troubleshoot it.

**Comment by mackelito** [comment]
Ok so I'm well on my way now but have one last (?) problem... When I try to serve or build the app I get the following error:
````
⠙ Generating browser application bundles (phase: setup)...Error: ENOENT: no such file or directory, open '/apps/site/main.ts'
````
The main.ts is located in /apps/site/src/ together with polyfills, tslint, tsonfig etc.. So I guess there is a path issue in the project.json file.

But when looking there it seems correct.. `  "sourceRoot": "apps/site/src/",`
And the main.ts path file also seems correct.. `        "main": "apps/site/src/main.ts",`

What am I missing?
