### ISSUE TITLE
Solve reported issues about `@nrwl/nx-cloud` reported by socket.dev

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#15413]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
We recently started using https://socket.dev/ as part of our dependencies maintenance and the tool has detected a handful of issues in `@nrwl/nx-cloud` which should be solved or at least investigated: https://socket.dev/npm/package/@nrwl/nx-cloud

## Motivation
Expect ideally no issues at all to pop up related to `@nrwl/nx-cloud`

**Comment by AgentEnder** [comment]
Hey, thanks for opening the issue. I took a look at the report, and dont believe any of the items it mentions are actionable. 

Let's address these on a per issue basis

### No repository

The Nx cloud package is proprietary and closed source. As such, even if we were to add a link, it would be to a private repo you can't see. That kind of defeats the purpose of doing so, so I can't imagine it would remove this from the report

### No tests

We have tests, in the closed source repo. They can't be detected by tools like this since they aren't part of the distribution and the repo is private.

### Non OSI license

This is the license for cloud, changing it has legal ramifications.
