### ISSUE TITLE
createGlobPatternforDependencies returns an empty array on hot reload sometimes

### ISSUE THREAD

**Issue by anichols-ht** [nrwl/nx#15427]
### Current Behavior

I see #12786 and #12721 addressed an issue where `createGlobPatternforDependencies` wouldn't work if you were using `nx:run-commands` and the `cwd` option. We have that setup (with tailwindcss), and I want to report that, while that behavior is fixed for initial load, something is still missing because there are certain actions (I haven't been able to isolate exactly what triggers it) that cause it to revert to an empty array on a hot reload. So basically, occasionally I'm editing a file and I save it, and then all my styles from dependency projects just disappear.

### Expected Behavior

Styles from dependencies should always load, not just on initial load.

### Steps to Reproduce

1. Create an app that uses tailwind, with a config like this:

```
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');
const path = require('path');
const baseConfig = require('../../libs/design/tailwind.config');

// Not required, but this is how I realized what was happening.
console.log(createGlobPatternsForDependencies(__dirname));

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    path.join(
      __dirname,
      '{src,pages,components}/**/*!(*.stories|*.spec).{ts,tsx,html}',
    ),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  ...baseConfig,
};
```

2. Create a design lib with a tailwind config like this (I don't think the specifics matter here).

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#005CB9',
        'primary-dark': '#00488E',
        'primary-medium': '#C7EAFB',
        'primary-light': '#F1FAFE',
      },
  },
};
```

3. Write some components in the design lib that use tailwind classes (e.g. `bg-primary`, which is easy to notice)
4. Use those components in your app (including other styling possibly).
5. This is where I don't know what to advise because I can't nail down what causes it to happen. Saving changes to the design lib? Saving changes to the tailwind config? Saving changes to the app itself? I'm not sure, but basically after some period of time making changes (and pretty reliably) the styles from the lib stop working. Styles in the app itself continue to work, however.

### Nx Report

```shell
Node : 18.9.0
   OS   : darwin arm64
   npm  : 8.19.1

   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : 15.6.2
   @nrwl/jest : 15.4.4
   @nrwl/js : 15.4.4
   @nrwl/linter : 15.4.4
   @nrwl/nest : Not Found
   @nrwl/next : 15.6.3
   @nrwl/node : 15.6.2
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : 15.4.4
   @nrwl/webpack : 15.6.2
   @nrwl/workspace : 15.4.4
   @nrwl/vite : 15.4.4
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by maxfriedmann** [comment]
Hi @anichols-ht, I am facing the same problem. This issue only happens since we moved from workspace.json to the per app/lib project.json approach, which happened automatically during the last migration from nx 14x to 15x.

In our case, `createGlobPatternsForDependencies` does return [] as well, which is correct according to the project graph. I had a look at `nx graph` and realized, that an app which relies on 25 libraries suddenly has NO dependencies at all anymore.

My current quick fix was to introduce an implicitDependency in the apps->project.json: 
```
"implicitDependencies": ["application-components"],
```

Afterwards, the project graph looked better, `createGlobPatternsForDependencies` returned something and tailwind components (where my issue originated) got styled again. 

I would bet that it has something to do with the project graph creation... Maybe it helps you as well.

**Comment by DaSchTour** [comment]
Very frustrating issue. I don't even get the dependencies on initial start and even when adding implicitDependencies I only get them for this one library. It looks like the function doesn't follow the dependency graph at all.

BTW: I'm on the latest 16.5.2

**Comment by shaharkazaz** [comment]
I'm experiencing the issue when upgrading from `16.6.0` to `16.7.2` up until now it was working as expected.

I ran the graph on both `16.6.0` and `16.7.2` but I see that my main app is displayed as independent on both versions, which is untrue since it consumes libs but on `16.6.0` `createGlobPatternforDependencies`  is working for me.

Currently, this is blocking me from upgrading, the workaround suggested is complex to maintain on my workspace.

**Comment by alexdabast** [comment]
I notify this issue also and for some weird reason when using nx serve myapp --verbose it works as expected
It's a angular app tho

**Comment by anichols-ht** [comment]
I mean, this is definitely still a problem. I made a brand new app using the latest version of nx about a week ago and experienced this issue.
