### ISSUE TITLE
Could not find a version for "xxx" in the root "package.json" when collecting shared packages for the Module Federation setup. The package will not be shared. 

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx#15456]
### Current Behavior

For instance, We have marked some_library as shared. Which has a dependency on lodash which is not part of the root package JSON. Now when we build the angular application, it gives us a warning

"Could not find a version for "lodash" in the root "package.json" when collecting shared packages for the Module Federation setup. The package will not be shared."

We don't want to share the package, as it will cause another HTTP call just to get this chunk. Since, we are on HTTP 1, it will become very slow.

Is there any way we can achieve this without bloating the root package.json

### Expected Behavior

Should not throw warning

### Steps to Reproduce

-

### Nx Report

```shell
Node : 16.14.2
   OS   : darwin x64
   yarn : 1.22.18
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/storybook         : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.3.0
   @ngrx/router-store   : 15.3.0
   @ngrx/store          : 15.3.0
   ngx-build-plus       : 15.0.0
   @ngrx/store-devtools : 15.3.0
   @storybook/angular   : 6.5.16
   ng-mocks             : 14.6.0
   nx-stylelint         : 13.4.0
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please note the warning doesn't break your build. The automated collection of shared libraries logs that warning because it could be a legit issue. The helper can't know whether you intentionally want that behavior, so we log the warning to be safe.

That said, I'll push a PR to consider your [`shared` config](https://nx.dev/recipes/module-federation/faster-builds#excluding-or-overriding-shared-libraries) and not warn for any dep you exclude there.
