### ISSUE TITLE
nrwl cloud github action doesn't work with private repos

### ISSUE THREAD

**Issue by ALMaclaine** [nrwl/nx#15512]
### Current Behavior

Step Derive Appropriate SHAs for base fails with:

Error: Resource not accessible by integration
Error: Process completed with exit code 1.

### Expected Behavior

It doesn't fail

### Steps to Reproduce

1. setup an empty project with nrwl, set github repo to private, add github ci action, attempt to run ci flow.

### Nx Report

```shell
NA
```

### Additional Information

Everything works for public repos.

**Comment by StalkAltan** [comment]
Hi, please take a look at the following:

You may need to set these overrides: https://github.com/nrwl/nx-set-shas#permissions-in-v2

Based on whether your repo has "permissive" or "restricted" defaults for the GITHUB_TOKEN system env variable. 

More info from GitHub is available here: 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#configuring-the-default-github_token-permissions

If you are still having problems, please open an issue on https://github.com/nrwl/nx-set-shas instead of this repo.
