### ISSUE TITLE
Federated Modules, FormsModule, and shared libraries

### ISSUE THREAD

**Issue by jefflamb-8451** [nrwl/nx#15524]
### Current Behavior

In Angular, when using ngModel in from FormsModule in a child app I get the error "No value accessor for form control name: 'caseSelection'."  When I click on the error documentation from the console it takes me to this URL: https://angular.io/errors/NG01203

Item #6 in that article lists that when using federated modules and references this github issue: https://github.com/angular/angular/issues/43821#issuecomment-1054845431

That issue recommends adding configuration to webpack.config.js, to indicate that the forms module should be shared. like below.

`module.exports = {
...
  plugins: [
    new ModuleFederationPlugin({
      remotes: {
         ...
      },
      shared: share({
        '@angular/forms': { // <-- This was missing
          singleton: true,
          strictVersion: true,
          requiredVersion: 'auto',
          includeSecondaries: true
        },
        ...
      }),
      ...
    }),
    ...
  ]
};`

unfortunately when I add this the function "share" can't be found.  I found some examples that provide the config without the share function, but when I do this the build fails saying " sharedFn is not a function"

### Expected Behavior

a function "share" should exist, or the compiler should be able to accept the config without the function reference.

### Steps to Reproduce

1. set up an application with federated modules
2. Import FormsModule into child application
3. add a component that uses ngModel <input [(ngModel)]=value (ngModelChange)="modelChangedFunction()">
4. add "shared" config into webpack.config.js as recommended by anguler
5. note that share is not a function

### Nx Report

```shell
yarn run v1.22.18
$ /Users/j753284/dev/activation-web-ui/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   yarn : 1.22.18

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/storybook         : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/web               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.1.0
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.0.0
   @ngrx/effects         : 15.0.0
   @ngrx/router-store    : 15.0.0
   @ngrx/store           : 15.0.0
   @ngrx/store-devtools  : 15.0.0
   @rx-angular/cdk       : 1.0.0
   @rx-angular/template  : 1.0.0
   @compodoc/compodoc    : 1.1.19
   @ngrx/schematics      : 15.0.0
   @storybook/angular    : 6.5.15
   ng-mocks              : 14.6.0

✨  Done in 1.27s.
```

### Failure Logs

```shell
ERROR Error: NG01203: No value accessor for form control name: 'caseSelection'. Find more at https://angular.io/errors/NG01203
    at _throwMissingValueAccessorError (forms.mjs:3165:11)
    at setUpControl (forms.mjs:2938:13)
    at NgModel._setUpStandalone (forms.mjs:4025:9)
    at NgModel._setUpControl (forms.mjs:4013:37)
    at NgModel.ngOnChanges (forms.mjs:3972:18)
    at NgModel.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1574:14)
    at callHook (core.mjs:2498:18)
    at callHooks (core.mjs:2457:17)
    at executeInitAndCheckHooks (core.mjs:2408:9)
    at refreshView (core.mjs:10434:21)


 NX   sharedFn is not a function
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

From your description, it is not clear how you set up Module Federation in the Nx workspace. If you are using the `withModuleFederation` helper exposed by `@nrwl/angular/module-federation`, you have a couple of options that helper receives to configure the shared libraries:

- You can use [the `shared` function option](https://nx.dev/packages/webpack/documents/webpack-plugins#shared) to modify the share configuration of a library that's going to be shared.
- You can use [the `additionalShared` option](https://nx.dev/packages/webpack/documents/webpack-plugins#additionalshared) to provide additional libraries that you want to share and are not shared automatically by the `@nrwl/angular` utilities

You can find an example using the `shared` function option at https://nx.dev/recipes/module-federation/faster-builds#excluding-or-overriding-shared-libraries. For additional libraries to share (libraries that were not automatically picked up to be shared by the `withModuleFederation` helper), you can do:

```js
// module-federation.config.js
module.exports = {
  name: 'host',
  remotes: ['shop', 'cart', 'about'],
  additionalShared: ['<lib or pkg name to share>'] // see https://nx.dev/packages/webpack/documents/webpack-plugins#additionalshared for additional types you can use
};
```

I'm closing this since it seems to be a misconfiguration. If you continue to have issues after using the above, please post a repro so we can troubleshoot it.
