### ISSUE TITLE
Error: Invalid source or target versions. Source: 5.0, Target: 5.1

### ISSUE THREAD

**Issue by dormeiri** [nrwl/nx#15573]
### Current Behavior

I get an error when running `nx` commands on my packages.

For example: `npx nx run-many --target=lint` (could be anything, not only lint)

### Expected Behavior

Nx run my commands.

### GitHub Repo

https://github.com/noodle-graph/monorepo/tree/nx-issue

### Steps to Reproduce

1. Create some package based monorepo with this tutorial: https://nx.dev/getting-started/package-based-repo-tutorial
2. `npm i nx@15.8.5 @nrwl/devkit@15.8.5`
3. `npx nx run-many --target=lint` (it can be anything, not only lint)

Beside `nx` and `@nrwl/devkit` I don't have any other `nx` related packages.

### Nx Report

```shell
➜  monorepo git:(master) ✗ npx nx report
error: unknown command 'report'
```

### Failure Logs

```shell
Could not find 'nx' module in this workspace. Error: Invalid source or target versions. Source: 5.0, Target: 5.1.
       
       Only backwards compatibility between "5.1" and "5.0" is supported.
       This error can be caused by "@nrwl/..." packages getting out of sync or outdated project graph cache.
       Check the versions running "nx report" and/or remove your "nxdeps.json" file (in node_modules/.cache/nx folder).
           
           at projectGraphAdapter (.../github/noodle-graph/monorepo/node_modules/nx/src/project-graph/project-graph.js:175:11)
           at readCachedProjectGraph (.../github/noodle-graph/monorepo/node_modules/nx/src/project-graph/project-graph.js:45:12)
           at run (.../github/noodle-graph/monorepo/node_modules/nx/src/command-line/run.js:171:69)
           at requireCli (.../github/noodle-graph/monorepo/node_modules/nx/bin/run-executor.js:17:23)
           at Object.<anonymous> (.../github/noodle-graph/monorepo/node_modules/nx/bin/run-executor.js:12:1)
           at Module._compile (node:internal/modules/cjs/loader:1159:14)
           at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
           at Module.load (node:internal/modules/cjs/loader:1037:32)
           at Module._load (node:internal/modules/cjs/loader:878:12)
           at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

### Additional Information

I looked a bit on the `nx` package code, and it feels to me that the issue is here: https://github.com/nrwl/nx/blob/16ad3086be4ff7c0174b518384428d11e2c4dfaa/packages/nx/src/project-graph/project-graph.ts#L186

I am not familiar with the code, but I would expect the backward compatibility to be the other way:

```ts
if (+targetVersion > 5 && +sourceVersion === 5) {
```

Instead of
```ts
if (+sourceVersion > 5 && +targetVersion === 5) {
```

What do you think? I can create a PR if that's help

**Comment by hoductrong** [comment]
I have the same problem when using lerna cache task results. I use a custom runner to upload the cache task result to GCloud, but it's not working since the latest releases. The issue goes away if I change the my custom runner to the `nx/tasks-runners/default`. Please help. Currently, I must disable the cache task result to get lerna to work again.

**Comment by DGuidi** [comment]
same prolbem appeared today after a fresh checkout + npm install :(

**Comment by dormeiri** [comment]
I don't know why, but I can't reproduce it now...

`nxdeps.json` is at version 5.1 after I run `nx run-many --target=build`

I also tried to downgrade Nx to 5.7.1, `nxdeps.json` was at 5.0, and then took again 5.8.5 which changed `nxdeps.json` version to 5.1.

**Comment by driley-abbvie** [comment]
somehow mine resolved itself after checking out different branches

**Comment by meeroslav** [comment]
Hey all,

The issue is not in the adapter you were looking at (the condition `+sourceVersion > 5 && +targetVersion === 5` is fine since this is meant for backward compatibility of custom plugins). 

Despite this error occasionally popping up whenever we change the graph version, we have experienced so far that it was primarily due to:
- stuck daemon (can be reset with `nx reset`) or
- misaligned versions of nx/nrwl packages

Changing the nx package version should trigger cache miss and graph rebuild would eliminate the outdated `5.0` version. If versions are out of sync, this would potentially lead to mismatched graph versions.

Please note that the steps described by @dormeiri will for sure create a broken version setup. You should never update packages manually using `npm i/yarn add...` (or make sure to update all of them), but rather use `nx migrate` to ensure all versions are in sync and the code is migrated.

If someone has a repo/scenario where this can be reproduced every time we can look into it.

Otherwise, there's nothing we can do about this, except to suggest cleaning up the local cache folder `node_modules/.cache/nx` which would trigger the graph rebuild and advice you to always use `nx migrate`.

**Comment by dormeiri** [comment]
Thanks for the answer, just a few things to clarify:

1. I use only `nx` and `@nrwl/devkit` and both were synced.
2. I tried `nx migrate` and `nx reset`, also tried to delete the project and clone it again. Nothing helped, only few days later I tried again to `npm i nx@latest` and it worked.

For now all good :)

**Comment by meeroslav** [comment]
Hm... it could then be some issue in the `nx-cloud`. Are you using `nx-cloud` and if yes, was that one up to date?

**Comment by DGuidi** [comment]
> Changing the nx package version should trigger cache miss and graph rebuild would eliminate the outdated 5.0 version. 

yep, this fixed my problem
