### ISSUE TITLE
Add feature to @nrwl/react:component generator to generate Storybook stories and pre-defined coding style

### ISSUE THREAD

**Issue by ubeytd** [nrwl/nx#15651]
## Description
I suggest adding a new feature to the `@nrwl/react:component` generator that generates a 📚 story file for the generated component if Storybook is already configured in the project. Additionally, it would be great if the generator could include a pre-defined coding style, such as a template for the component or story file, where variables can be replaced with actual values.

## Motivation
This feature would save developers ⏰ time and effort when creating components. The current behavior is not practical as we need to copy the path of components to generate a story.

- [x] I'd be willing to implement this feature

## Suggested Implementation
- We could add a checkbox option for generating stories to NX Console. ✅
- We could add a dedicated folder for templates and pull from there. 📁

**Comment by mandarini** [comment]
@ubeytd yes, by using the `@nrwl/react:stories` generator. Here, you are using the `@nrwl/react:component-story` generator. This is an internal generator, and not meant to be used by users, since it leaves a lot of manual input to the user. Please take a look at [our documentation for setting up Storybook with React](https://nx.dev/packages/storybook/documents/overview-react#auto-generate-stories), we explain how you can generate stories for your components, even after you have configured Storybook.

Also, I updated above comment to explain how you can contribute to Nx if you want.

**Comment by ubeytd** [comment]
Thank you for the prompt response. 🤗

From what I understand, the [@nrwl/react:stories generator](https://nx.dev/packages/react/generators/stories) would generate for all components in the project except `ignorePaths` . 

However, the use case I described is to generate stories when I generate components in single command. 

If necessary, I could achieve the same result with local generators, which is my fallback plan. 

Regarding templates, I think the methodology you suggested is an excellent option and is exactly how I plan to proceed.

**Comment by mandarini** [comment]
Indeed there is no generator at the moment to generate both components and stories. I suggest you create a local generator that calls the component generator and then calls the component-story generator for that specific component that was generated. 

In any case, I suggest you use the `stories` generator instead of the `component-story` generator when you are generating stories manually.

**Comment by ubeytd** [comment]
Fantastic! 🤗 I really appreciate this amazing thread! I'll definitely try it out for template ideas.

**Comment by mandarini** [comment]
Glad I helped! Closing this issue now, but feel free to ping me to reopen if you need to!
