### ISSUE TITLE
Can't find the article about correct migrating from webpack 4 to webpack 5 

### ISSUE THREAD

**Issue by OlegPalchyk** [nrwl/nx#15764]
### Documentation issue

https://nx.dev/guides/webpack-5

Previously was the page with nx command for updating webpack version 

ot this is not correct now and just need update webpack manually ?

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by jaysoo** [comment]
The migration guide was removed since it was only applicable to Nx 13 (which is unsupported). Starting in Nx 14, only Webpack 5 is supported.

If you are migrating from an outdated Nx version you can find the guide here: https://github.com/nrwl/nx/blob/13.10.6/docs/shared/guides/webpack-5.md 

I also recommend checking out the official Webpack guide: https://webpack.js.org/migrate/5/
