### ISSUE TITLE
@nrwl/next: Cannot find module '@nrwl/next/plugins/with-nx'

### ISSUE THREAD

**Issue by grz-gajda** [nrwl/nx#15931]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[@nrwl/next -> Setting up Next.js](https://nx.dev/packages/next#setting-up-next.js)

### Additional context or description

With changes from https://github.com/nrwl/nx/pull/15824 package `@nrwl/next` needs to be included in `dependencies`, not in the `devDependencies`, otherwise generated `package.json` doesn't have `@nrwl/next` and it's not possible to run the Next's application because of error:

```
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '@nrwl/next/plugins/with-nx'
```

Workspace generated by command `npx create-nx-workspace@latest --preset=next` have `@nrwl/next` in the `dependencies`.

**Comment by grz-gajda** [comment]
> Is it actually a good idea to require @nrwl/next as a dependency?

Not only `@nrwl/next` is required as dependency but also all of plugins imported in `next.config.js`. I've been using `next-translate` and I had to move `next-translate-plugin` from `devDependencies` to `dependencies`. For sure it's breaking change but I don't have an opinion which way is better (like it's right now or how it was previous), that's why I made an issue for documentation.

**Comment by jaysoo** [comment]
I think there are two separate issues here.

1. Some Next.js plugins like `next-translate` are actually needed during production runtime. So you _do_ need to have them installed for production. This is because the compiled runtime code will need to import things like `next-translate/appWithI18n`.
2. Currently `@nrwl/next` is also needed for production to run, but it is pulling in other modules that aren't needed.

(1) is not an Nx issue. If you _know_ a plugin isn't needed you must check for the phase in your `next.config.js` file. Such as:

```js
const { PHASE_PRODUCTION_SERVER } =require('next/constants');

const nextConfig = {
  reactStrictMode: true,
};

module.exports = (phase) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    return nextConfig;
  } else  {
    // This plugin only has an effect during build (e.g. it applies additional transforms)
    const somePlugin = require('some-dev-only-plugin');
    return somePlugin(nextConfig);
  }
}
```

(2) is something we can address for Nx 16. For now you must install it as a prod dependency.
