### ISSUE TITLE
Cache is not cleared when external package is removed or version changed

### ISSUE THREAD

**Issue by jepstein-eagle** [nrwl/nx#15964]
### Current Behavior

**A build uses the cache and passes** after a dependency package is removed from the project's root `package.json` via npm

### Expected Behavior

**A build does not use the cache and fails** after a dependency package is removed from the project's root `package.json` via npm

### GitHub Repo

https://github.com/jepstein-eagle/package-test

### Steps to Reproduce

1. `npx nx build buildable` (seed cache)
2. `npm rm date-fns` (remove dependent package used in `buildable/src/lib/date/date.component.ts`)
3.  `npx nx build buildable` (uses cache when should not)

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : darwin x64
   npm  : 8.19.3

   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/angular           : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/webpack           : 15.8.9
   typescript              : 4.9.5
```

### Additional Information

This use case is essential to many users because a typical pattern is to change dependent external package versions, and this causes lib builds to pass when they should not if the cache was correctly cleared.

We can use the `implicitDependencies` in the `nx.json` with the following content to resolve:

```
 "implicitDependencies": {
    "package.json": {
      "dependencies": "*"
    }
  }
```

but this should not be required in nx 15 per the [docs](https://nx.dev/deprecated/global-implicit-dependencies#dependencies-on-sections-of-the-root-file) and causes any root `pacakge.json` change, even unrelated to the lib, to require a rebuild.

Thank you in advance for your help 😄

**Comment by meeroslav** [comment]
Unfortunately, I wasn't able to reproduce this error on your repo.

As soon as I removed the package, the IDE itself already marked the `date.component.ts` as invalid and as expected the build failed due to missing dependency:
![Screenshot 2023-03-31 at 11 25 16](https://user-images.githubusercontent.com/881612/229081606-9e03387b-c888-4f7d-b0b3-7f74233d4401.png)

Can you try to remove your `node_modules` and re-run `npm ci` and then recheck the scenario?

**Comment by meeroslav** [comment]
The original run had `bc14a8da2f515f4ca54ada775ede2afe02fdd45ffe8144f5fafb4b74ad5291b4` hash, and the run without  `date-fns` has hash `d1075546ace355979f3fba8e191edf4f53468e8ecead62d1695f76101782cd0f` which causes the cache miss.

Before removal:
![Screenshot 2023-03-31 at 11 36 17](https://user-images.githubusercontent.com/881612/229084299-bd411d20-0715-4598-ac65-8e6754ef9c8c.png)

After removal
![Screenshot 2023-03-31 at 11 37 28](https://user-images.githubusercontent.com/881612/229084578-5458b903-c532-44f7-84ab-095429a9d297.png)

You can see that the command hash is the same since the command didn't change, but the hash of the `date-fns` dependency is now generic in the second run since the graph no longer contains information about this package.

This further influences the final hash to be different and the entire run to be a cache miss.

**Comment by jepstein-eagle** [comment]
@meeroslav Thank you for taking a look and performing this analysis!

Upon removing my `node_modules` and `npm i` I could no longer reproduce. However, I can replicate this by making a new repo (as with this example) so I want to further determine what is in the `node_modules` leading to this issue.

What command are you running to determine the dep hash so I can reproduce your results locally and then go on more of a deep dive in the `node_modules` to get to the root cause of the issue?

**Comment by meeroslav** [comment]
This was unfortunately generated by adding `console.log`'s to hashing function - `node_modules/nx/src/hasher/hasher.js`

I added the console log to these lines:
`class Hasher -> hashTask -> right after "const command..."`:
```javascript
console.log('Command', command);
console.log('Hash', this.hashArray([res.value, command]));
```

`class TaskHasher -> hashExternalDependency -> before the final "return"`:
```javascript
if (projectName === 'npm:date-fns`) {
  console.log('date-fns hash:', hash);
}
```

Hope that helps

**Comment by meeroslav** [comment]
Can you let me know what exact commands are you running to generate this error from scratch?

**Comment by jepstein-eagle** [comment]
@meeroslav Thank you for providing the commands needed to reproduce that output. I was able to follow your steps and successfully reproduce the issue with the same hash output (as below) when making a new example repo:

Before removal:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/43790368/229847417-22ccd37d-d045-4fb9-b585-313432c2e637.png">

After removal:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/43790368/229847571-f693ceac-51f2-49cf-985b-9fb3ca5788af.png">

Here are the exact steps I followed (tested 2X):
1. `npx create-nx-workspace@latest package-test2 --preset=angular-standalone --style=css --standaloneApi=true --routing=true --nxCloud=false`
1. `cd package-test2`
1. `npx nx g @nrwl/angular:lib buildable --buildable`
1. `npx nx g @nrwl/angular:component date --project=buildable`
1. Copy file contents from https://raw.githubusercontent.com/jepstein-eagle/package-test/main/buildable/src/lib/date/date.component.ts to `buildable/src/lib/date/date.component.ts`
1. `npm i date-fns`
1. In `buildable/src/lib/buildable.module.ts`: Change `import { DateComponent } from './date/date/date.component';` to `import { DateComponent } from './date/date.component';` (maybe a generator bug)
1. Add hashing commands as in https://github.com/nrwl/nx/issues/15964#issuecomment-1494951990
1. `npx nx build buildable`
1. `npm rm date-fns`
1. `npx nx build buildable` (hits cache when should not)

I have been unable to determine the issue in `node_modules` thus far, but I am hoping you might be able to further debug🤞

**Comment by meeroslav** [comment]
Ok, I can see the error now. The graph doesn't contain a dependency link between `buildable` and `date-fns` because it was installed after the last change to the file that made the dependency. That's why it was important to know the exact steps (and the order) to reproduce it.

I was wondering why your screenshot doesn't contain logs of `date-fns` hashes. 😀 

Here is the explanation of the problem:
1. We add `import { format } from 'date-fns'` to the `date.component.ts`
2. Our AST file checker parses all the imports and tries to match them to the existing npm dependencies from the lock file
3. Since `date-fns` is not installed yet, we cannot map that dependency, and we ignore it (`build` and `lint` would still fail) <- **THIS IS THE SOURCE OF THE ERROR**
4. We install the `date-fns`.
5. The `build` and `lint` is now successful but our graph still doesn't have a dependency between `buildable` and `date-fns`
6. When we remove the `date-fns` the node gets removed from `externalNodes` but dependencies remain unaffected (since `date-fns` was never there)
7. This leads to hash being the same

If you would make any change in `date.component.ts` after step 4, this would re-trigger the AST checker and the dependency would have been created.

Despite being a corner case issue, I'll make sure to fix this as soon as possible.
Thank you for providing the reproduction scenario.

**Comment by jepstein-eagle** [comment]
@meeroslav, I really appreciate this detailed explanation. The issue leading to the problem makes sense to me as well ✔️ 

I wanted to comment more about the scope of the issue so all parts are incorporated in the fix: In addition to teams consuming external dependencies, many teams (such as us) that utilize internal npm packages are also affected. It affects changes to dependencies in the `package.json`. Specifically:

- npm package removal
- npm package updates

As such, we have been unable to utilize `nx`'s awesome AST file checker to bust the cache until this issue is resolved in favor of the hack to the `implicitDependencies` in the [original comment](https://github.com/nrwl/nx/issues/15964#issue-1646223115).

Thank you again in advance for your help in allowing us to remove this band-aid and fully utilize the amazing powers of `nx` 🚀
