### ISSUE TITLE
New workspace using v15.9.2 shows "Error: Cannot find module '...'" while importing local libs

### ISSUE THREAD

**Issue by stomvi** [nrwl/nx#16140]
### Current Behavior

Using `create-nx-workspace@latest` to create a new workspace by nx@15.9.2. While importing a lib created by `@nrwl/node:lib` from an app created by `@nrwl/node:app` then run `nx serve myApp` shows:

```
Error: Cannot find module '/.../projects/pname/dist/libs/utils'
Require stack:
- /.../projects/pname/helpers/apps/helpers/src/main.js
- /.../projects/pname/helpers/main.js
- /.../projects/pname/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._resolveFilename (/.../projects/pname/tmp/helpers/main-with-require-overrides.js:41:36)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Function.Module._load (/.../projects/pname/packages/js/src/executors/node/node-with-require-overrides.ts:14:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/.../projects/pname/apps/helpers/src/main.ts:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
```

Build the lib manually will work.

### Expected Behavior

A node app imports @namespace/lib-name should work while "serving".

### Steps to Reproduce

1. `nx create-nx-workspace@latest namespace`
2. `cd namespace`
3. `nx g @nrwl/node:app helpers`
4. `nx g @nrwl/node:lib common`
5. The import the node lib from node app and run `nx serve helpers`

### Nx Report

```shell
Node : 16.20.0
OS   : darwin arm64
npm  : 8.19.4

nx                      : 15.9.2
@nrwl/js                : 15.9.2
@nrwl/jest              : 15.9.2
@nrwl/linter            : 15.9.2
@nrwl/workspace         : 15.9.2
@nrwl/cli               : 15.9.2
@nrwl/cypress           : 15.9.2
@nrwl/devkit            : 15.9.2
@nrwl/esbuild           : 15.9.2
@nrwl/eslint-plugin-nx  : 15.9.2
@nrwl/next              : 15.9.2
@nrwl/node              : 15.9.2
@nrwl/react             : 15.9.2
@nrwl/tao               : 15.9.2
@nrwl/web               : 15.9.2
@nrwl/webpack           : 15.9.2
@nrwl/nx-cloud          : 15.3.5
typescript              : 4.9.5
```

**Comment by stomvi** [comment]
#10099 seems to be the same issue.  Why does a buildable library won't be auto built?

**Comment by stomvi** [comment]
I found the `dependsOn` config. Close this issue.

**Comment by pedropmedina** [comment]
Hi @stomvi. DependsOn needs to be set in order to first build those 'buildable libraries', however, does your code updates upon making changes to one of those dependent buildable libraries while the server is running? 
My problem is that if I have app1 with lib1 and lib2 as buildable libraries and I make a change to lib1, the server refreshes, but the change isn't available in app1. Is this working fine for you?

**Comment by stomvi** [comment]
@pedropmedina Here's the result after some tests.

Apps generated by `@nrwl/next` is working properly.  I don't have to set `dependsOn` for `next` apps, only for apps that are generated by `@nrwl/node`.  Node app is able to detect its dependent libs are changed, but won't take new values into account.

**Comment by pedropmedina** [comment]
I haven't been able to find a good explanation as to how buildable libraries work @stomvi and the docs don't go into much details. The dist/ looks interesting and if you dig a bit deeper you can see that the libs get generated under the `dist/libs/{lib}` and apps under `dist/apps/{app}` which makes sense. However if you go into the apps in more details you'll notice `dist/apps/{app}/libs` and in there nx keeps tracks of app specific libraries dependencies. The way nx figures out how to resolve its dependencies is via a manifest array found inside of `dist/apps/{app}/main.js`. 

Interestingly `@nrwl/js:node` does a poor job at resolving buildable libraries as it keeps on resolving to the libs outside the app itself; the ones located at `dist/libs/{lib}` instead of the one directly under the application `apps/{app}/libs/{lib}` which is the one that gets re-compiled on changes to the {lib}.

I believe the benefits of having buildable libraries is to reduce the final build before deploying production. Take as an example an app with 20+ libs where you need to go in and make changes to 1 lib. Once you're done nx will type-check and re-compiled only the main app and that lib you made the changes on. The rest will be taken from cache so the build process is a lot faster. 

One solution I found to leverage buildable libraries is to build with esbuild which is the default executor if you created the app with `@nrwl/node:app` as you have the option to `bundle: true`. This way node will always be reading from a single file with the re-compiled changes made to those libs you were working on. I'm not that happy with this solution, but it seems to do the trick for now.
