### ISSUE TITLE
Support environment variables in nx.json

### ISSUE THREAD

**Issue by jbadeau** [nrwl/nx#16179]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I think supporting interpolating environment variables in at least the nx.json would be extremely welcome as it would dramatically simply pipelines.  

## Motivation
Tasks need to be able to read values from the env such as gitlab/github ci variables. Tasks could write envvars directly to the host or via .env files and subsequent tasks could pass them as options. Currently every plugin developer or user needs to create workarounds like [postTarget](https://github.com/jscutlery/semver#triggering-executors-post-release) from semvers to pass values from one task to another. All of your competitors support this and it makes the NX very verbose because of workarounds to get access to envvars.

## Suggested Implementation

```
{env.SOME_VALUE} would interpolate envvar SOME_VALUE.
```

```json
    "build-chart": {
      "executor": "@techx/nx-helm:build",
      "options": {
        "chartPath": "chart",
        "destination": ".",
        "repository": "techx",
        "version": "{env.VERSION}"
      }
    }
```

## Alternative Implementation

```
{$SOME_VALUE} would interpolate envvar SOME_VALUE.
```

```json
    "build-chart": {
      "executor": "@techx/nx-helm:build",
      "options": {
        "chartPath": "chart",
        "destination": ".",
        "repository": "techx",
        "version": "{$VERSION}"
      }
    }
```

**Comment by jbadeau** [comment]
There are similar issues that have not been answered of addressed like: https://github.com/nrwl/nx/issues/4606
I don't understand why such a basic feature is not supported?

**Comment by AgentEnder** [comment]
Hey @jbadeau! This is something we are considering supporting for target options in general, rather than just in `nx.json`. There are some complexities as allowing substitution in these makes migrating them much harder.

Imagine a migration that renames the project's jest configuration file. If the path to that file contains an env variable, or {projectRoot}, its another step that can be forgotten and makes our migrations a bit more fragile.

This is the reason that its not currently supported, and also the reason that we don't support things like `{workspaceRoot}`, `{projectRoot}` etc inside `project.json` but rather limit them to `nx.json`

We will continue to evaluate the support, its not something that we've ruled out but something that needs to be considered.

**Comment by jbadeau** [comment]
Now that v16 is loose is there any chance to have a look at this?

As a first step, why not enable envvars for target options first. This is the main place where they are required.

```json
"release-gitlab": {
  "executor": "@jscutlery/semver:gitlab",
  "options": {
    "tag": "${tag}",
    "description": "${notes}"
  }
}
```

This would allow for many of the benefits but would not impact migration.

**Comment by jbadeau** [comment]
Any update on this issue?
