### ISSUE TITLE
Upgrading past 15.6 doesn't work

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#16366]
### Current Behavior

Unable to get NX to work after upgrading from 15.4.5 to 15.9.2

Issues with the webpack changes and what the instructions actually mean?

![image](https://user-images.githubusercontent.com/12847881/232747549-6e82fa92-f8f3-403d-88c9-87c004386a90.png)

I have installed the packages requested and I have created a webpack.config.js file in my app project as follows 

![image](https://user-images.githubusercontent.com/12847881/232748836-44769f86-4391-457a-bfe8-76ecbb19be73.png)

but I still get the same issue

Is this what I am supposed to do?

Some clearer guidance would be good - I build lovely front-ends, configuring build tools isn't something I care for tbh!

### Expected Behavior

It would work after following instructions

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 16.18.0
   OS   : win32 x64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.4.5
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/tao@15.4.5

   To fix this, run `nx migrate nx@15.9.2`
```

**Comment by 72gm** [comment]
Hi,

The first question would be is the approach correct?

If not, the second would be where is the fools guide to get this to work?

Thanks

**Comment by 72gm** [comment]
@AgentEnder could you or someone else respond to this? I don't think I've asked unreasonable questions.

I really like NX but the support can be a bit hit or miss... and not being able to upgrade easily, within the same major release, is a bit of a deal breaker tbh

**Comment by 72gm** [comment]
Hello anybody doing support form NX? many issues not answered

**Comment by Coly010** [comment]
Hi, I'm sorry you do not feel your issue was addressed on a timescale that you would have preferred. It's worth noting that this is OSS, and the engineers within Nx do their best to address Issues in a timely manner. 

It's also worth pointing out that to get the best support, it's worthwhile to provide reproduction steps and if possible a repo so that we can do more thorough troubleshooting.

Now, on to your issue. 

Have you tried removing your `node_modules` and running `yarn install` again?
This seems to be an issue with package resolution that has surfaced after the migration. 

Try doing a fresh install of your packages:

1. Remove `node_modules` folder
2. Clean the `yarn` cache: `yarn cache clean`
3. Run `yarn install`

**Comment by 72gm** [comment]
Hi,

Thanks for the answer, I've tried that a few times and in many different ways but no joy... 

Just to be clear: I have no issue with the engineers, I really don't... there are only so many hours in a day and you do what you can... it just that there are lots and lots of issues not being answered ... which suggests that someone in charge isn't allocating enough/appropriate resources to the support of the product... 

As an alternative, I've looked at creating a new repo and porting the src folders across but that is having it's own issues (storybook mainly) ... so parking the upgrade for now as too much time spent

**Comment by jaysoo** [comment]
@72gm Is error when serving Storybook or the React app itself?

If it is Storybook, then make sure you are updated to Storybook v7, as v6 is not longer maintained. See: https://nx.dev/packages/storybook/documents/storybook-7-setup

If it is your application code, then you might be bringing in a package that has both server and client code. In this case, you can override the fallbacks to just turn them off (since you shouldn't need to on the client-side for the most part).

```
// webpack.config.js
module.exports = composePlugins(
  withNx(),
  withReact(),
  (config) => {
    config.resolve.fallback = {
      crypto: false,
       timers: false,
       // ...
    };
    return config;
  }
);
```

If the above doesn't work, can you please share your package.json dependencies/devDependencies?

**Comment by 72gm** [comment]
Thanks for the answer.. apologies had a release to get out so had to park.... I'll have another ago on this in the next day or so but another question if I may:

I need to publish my storybook to NPM so as it can be used by external orgs... I've used rollup successfully before on a non NX project to do this but I can't get it to work in NX (story of my life ;) )  

Do you know if this is actually possible? I can't see anyone that has tried this! 

I'm trying to evaluate whether it may be better that we pull our SB out of NX (so the above won't be an issue!)
