### ISSUE TITLE
Migration for `@angular/cli` value

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#165]
In the last few weeks, the value for `@angular/cli` in the package.json has changed from `nrwl/fix-cli-build` => `nrwl/fix-cli-build#release16` => `file:.angular_cli.tgz` without clarity on upgrade paths. Should there be guidelines or documentation for what value to follow/set while the [PR mentioned in the FAQ](https://github.com/nrwl/nx/wiki/FAQ) is still pending approval status?

I think adding this to the migration scripts could be considered a bit too opinionated since not everybody might be ready to upgrade Angular versions at a drop of a hat, but knowing what the differences are and when they happen might be beneficial. Personally, I only realized digging into commit diffs.

**Comment by chaosmonster** [comment]
I add this here, because it feels like it's the correct place.
When you upgrade an existing angular/cli project using the steps described here https://nrwl.io/nx/guide-nx-workspace#convert-an-angularcli-project-to-an-nx-workspace you won't get a `.angular_cli.tgz` file and this fix. If you do not add this by hand (the tgz file was copied from a newly created workspace and the package.json needs to be changed as well) you are no longer able to `npm install` or any `ng` command

**Comment by emilio-martinez** [comment]
Somewhat related to #173. Regardless of when that ticket is resolved, a migration plan for changes made to the `@angular/cli` value would be ideal.

**Comment by vsavkin** [comment]
This is the plan for @angular/cli: https://github.com/nrwl/nx/wiki/FAQ. The moment the needed fix gets merged into master, we are going to switch to the default CLI distribution.

**Comment by emilio-martinez** [comment]
@vsavkin this issue is more around how to keep the @angular/cli value updated _before_ it changes to the default CLI distribution. For example, I was using the fix-cli-build on 1.5.0 but I wasn't upgraded to the 1.6.0 version by running nx-migrate.

**Comment by russoturisto** [comment]
Can't wait for the PR to make it into cli!

PS  You guys probably know but PR didn't pass CI tests and there is a conflicting file.
