### ISSUE TITLE
@nx/react/plugins/storybook is not installed after migrating to 16.0.0

### ISSUE THREAD

**Issue by barrymichaeldoyle** [nrwl/nx#16629]
### Current Behavior

<img width="663" alt="Screenshot 2023-04-28 at 08 40 07" src="https://user-images.githubusercontent.com/4674486/235073361-9b9c7a5b-44c1-4419-b7c2-0fac2fd261bc.png">

I'm getting this eslint error after migrating to version 16. This got added `@nx/react/plugins/storybook` used to be named `@nrwl/react/plugins/storybook` and it didn't give me issues then.

### Expected Behavior

I expect this to not give any eslint errors. I've tried deleting my `node_modules` and reinstalling everything, restarting my ESLint server etc.

I've made sure that `@nx/react` is installed, but just none of it works.

### Steps to Reproduce

1. Migrate from any version before 16 and you should see this issue

### Nx Report

```shell
Node   : 18.14.2
   OS     : linux arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx                      : 16.0.0
   @nx/js                  : 16.0.0
   @nrwl/js                : 16.0.0
   @nx/jest                : 16.0.0
   @nrwl/jest              : 16.0.0
   @nx/linter              : 16.0.0
   @nrwl/linter            : 16.0.0
   @nx/workspace           : 16.0.0
   @nrwl/workspace         : 16.0.0
   @nx/cypress             : 16.0.0
   @nrwl/cypress           : 16.0.0
   @nx/devkit              : 16.0.0
   @nrwl/devkit            : 16.0.0
   @nx/eslint-plugin       : 16.0.0
   @nrwl/eslint-plugin-nx  : 16.0.0
   @nx/react               : 16.0.0
   @nrwl/react             : 16.0.0
   @nx/storybook           : 16.0.0
   @nrwl/storybook         : 16.0.0
   @nrwl/tao               : 16.0.0
   @nx/web                 : 16.0.0
   @nrwl/web               : 16.0.0
   @nx/webpack             : 16.0.0
   @nrwl/webpack           : 16.0.0
   @nrwl/nx-cloud          : 16.0.5
   nx-cloud                : 16.0.5
   typescript              : 4.9.5
```

### Additional Information

Add you can see in the Nx Report, there seem to be `@nrwl` versions and `@nx` version which might be the cause of the conflict. I feel like the migration steps should have gotten rid of the `@nrwl` stuff.

**Comment by mandarini** [comment]
Hi there @barrymichaeldoyle ! This is happening because the Storybook migrator added the `storybook/recommended` in your `.eslintrc.json` file.

You have two options right now, but I'm working on a third option.

The two options are the following:

1. In your `.storybook/main.js` files find the `'@nx/react/plugins/storybook'` and add `/* eslint-disable storybook/no-uninstalled-addons */` right before it, like this:

```
...
  addons: [
    '@storybook/addon-essentials',
    ...,
    /* eslint-disable storybook/no-uninstalled-addons */ '@nx/react/plugins/storybook',
  ],
...
```

I understand that his may be annoying to do for every file.

2. Remove `"plugin:storybook/recommended"` from your `.eslintrc.json`. I would not do that, but it's the most straightforward option right now.


The third option I'm working on is to add the `ignore` option to that rule, so once [that PR](https://github.com/storybookjs/eslint-plugin-storybook/pull/129) is merged and part of a release, then you will be able to do this in your `.eslintrc.json`:

```
...
  "extends": ["plugin:storybook/recommended"],
  "rules": {
...,
    "storybook/no-uninstalled-addons": [
      "error",
      {
        "ignore": ["@nx/react/plugins/storybook"]
      }
    ]
  },
...
```

I will close this issue now, but I will make sure to update our code once the Storybook PR is merged! Thank you so much for pointing this out to us!

**Comment by pikilon** [comment]
I came here to fix it and here are my 2 cents: Add the comment just before the line (instead of the same line)
```js
  addons: [
    '@storybook/addon-essentials',
    ...rootMain.addons,
    // eslint-disable-next-line storybook/no-uninstalled-addons
    '@nx/react/plugins/storybook',
  ],
  ```
