### ISSUE TITLE
Anti-feature request: please do not autoformat files on migration

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#16630]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
While migrating Nx from v15 to v16, every file where "@nrwl" was found, every such file was auto-formatted using some your formatting rules. It screwed our documentation files (.MD) and even some Excel files (.XLSX). Please do not do this.

## Motivation

There is a huge chance that repo has it's own formatting rules and overriding them is not cool.

## Suggested Implementation

Maybe move auto-formatting into a separate command, like `nx affected:format`. Or just don't auto-format files, that weren't created (not just updated) by Nx.

**Comment by hi2u** [comment]
Not sure if related, but I also had an odd issue today...

I upgraded to Nx v16, using the normal instructions in: https://nx.dev/core-features/automate-updating-dependencies

When I ran the `nx migrate --run-migrations` command, it modified 2 binary files I had under `/apps/myapp/assets/` in one of my apps.

Odd that `nx migrate` would touch anything at all under an `/assets/` dir?  Let alone some random binary files totally unrelated to Nx or even webdev at all really.  

The files were `hello.exe` and `erase.exe` from this page: https://www.mscs.dal.ca/~selinger/md5collision/ - I had a look at some binary diffs, there wasn't anything that stood out, just random looking differences here and there in the data.  Maybe related to encoding or something?

**Comment by AgentEnder** [comment]
> Not sure if related, but I also had an odd issue today...
> 
> I upgraded to Nx v16, using the normal instructions in: https://nx.dev/core-features/automate-updating-dependencies
> 
> When I ran the `nx migrate --run-migrations` command, it modified 2 binary files I had under `/apps/myapp/assets/` in one of my apps.
> 
> Odd that `nx migrate` would touch anything at all under an `/assets/` dir?  Let alone some random binary files totally unrelated to Nx or even webdev at all really.  
> 
> The files were `hello.exe` and `erase.exe` from this page: https://www.mscs.dal.ca/~selinger/md5collision/ - I had a look at some binary diffs, there wasn't anything that stood out, just random looking differences here and there in the data.  Maybe related to encoding or something?

The migrations shouldn't have touched any binaries, we are updating our list of extensions now.

**Comment by AgentEnder** [comment]
> There is a huge chance that repo has it's own formatting rules and overriding them is not cool.

Hey @e-oz! 

For files that we modify it typically makes sense to format them as the code we add is not likely to match the formatting rules of the organization. If you use prettier for formatting your workspace, we read your config via prettier's public API and obey them.

If you don't use prettier and use another formatter, or just want to opt out of formatting, I believe you should be able to specify the paths in a `.prettierignore` file in your workspace root.

Does this work for you?

**Comment by e-oz** [comment]
> For files that we modify it typically makes sense to format them as the code we add is not likely to match the formatting rules of the organization

No, it doesn't make sense for our MD files. Your formatting rules are not welcomed.

> If you use prettier for formatting your workspace, we read your config via prettier's public API and obey them.

World is more complicated.

> I believe you should be able to specify the paths in a .prettierignorThe world is more complicated.

> 

Just because we use Nx we have to use prettier and .prettierignore? Mention it in documentation maybe.

**Comment by AgentEnder** [comment]
> No, it doesn't make sense for our MD files. Your formatting rules are not welcomed.

See response to your last question

> The world is more complicated.

I'm not sure what this means

> Just because we use Nx we have to use prettier and .prettierignore? Mention it in documentation maybe.

You don't have to use prettier at all with Nx, and if it's not installed we won't run it. Nx has no direct dependency on prettier, and checks if its available during formatting. @nx/js generators will set it up on first run, because we believe it is currently one of the better tools for formatting, and is something of a standard for JS projects.

**Comment by e-oz** [comment]
> I'm not sure what this means

There are more formatters than Prettier.

Nx is very intrusive. You are going the wrong way when editing the files you haven’t created without asking.

I already have a habit to check “what was damaged” after every “nx migrate latest”. That's how I found damaged .xlsx and .md files. But I could miss some damaged lines, another developer (without this habit) could update Nx - then it would go to release.

You really need to reconsider this policy and overall idea “we can modify whatever we want, let them parse and fix our mistakes”.

**Comment by AgentEnder** [comment]
> There are more formatters than Prettier.

I hear you. I get that there are more formatters than prettier, thats just the one we stand up by default when starting a new repo. Like I said, if its not available, we don't run it. If its running, that means its installed in your repo and if you aren't using it than you should remove it. Check if its installed via `npm ls prettier`, `yarn why prettier`, or `pnpm ls prettier`.

>  damaged .xlsx

This was a bug in our migration, its fixed now. We did not ignore some binary files that shouldn't have been modified.

> .md files, we can modify whatever we want (etc)

This particular migration set was rather large, as we migrated our packages from the `@nrwl/{x}` scope, to the `@nx/{x}` scope. In order to keep repositories in a good state, and be able to drop the @nrwl packages in Nx 17, we performed migrations that found any references to the old packages and updated those to the new packages. This was a lot of files, which isn't generally the case for most migrations.

If you had a markdown file that referred to @nrwl/node for instance, it **_generally_** would make sense to update that reference to @nx/node.

----

I'm going to close this issue, considering that the feature request has already been fulfilled. If a repo does not have prettier installed, it will not be ran. If you find that this is not the case, feel free to open a bug report stating that.

**Comment by e-oz** [comment]
You are making a mistake.
