### ISSUE TITLE
Use "git mv" in @nrwl/workspace:move

### ISSUE THREAD

**Issue by mojoaxel** [nrwl/nx#16634]
## Description
`@nrwl/workspace:move` should use [git mv](https://git-scm.com/docs/git-mv) instead of a plane filesystem-based move/rename if the project has a git context.

## Motivation
When using `@nrwl/workspace:move` to move or rename a library the files get moved to the new location by using a native move/rename feature from the operating system.

This results in a lot of deleted and newly created files in a version-control-system like git. That means the git history of all the moved files get lost.

## Suggested Implementation
Instead of using the native fs-extra functions to move around files, existing files should be moved using [git mv](https://git-scm.com/docs/git-mv) (if the project has a git context!).

## Alternate Implementations
It looks to me the file operations are done in the relative abstract [FsTree class](https://github.com/nrwl/nx/blob/15.9.x/packages/nx/src/generators/tree.ts#L234-L251). Maybe it could be worth making this class "git aware"!?

**Comment by galah92** [comment]
Work like that very much.

**Comment by leblancmeneses** [comment]
1) navigate to root nx directory
2) git add new-files-directories
3) git status # shows files deleted and files added
4) git add -A .
5) git status # shows files renamed

https://stackoverflow.com/questions/433111/how-to-make-git-mark-a-deleted-and-a-new-file-as-a-file-move

**Comment by MaxKless** [comment]
Hello! 
So I just played around with it a bit and when I moved a project, all files were correctly picked up as renames instead of deletion and addition. 
Keep in mind that you have to stage everything for git to figure out the relationship between the new and old files. 
Also, if you have short files and make some changes, they might not be picked up correctly. Git has a similarity threshhold of 50% so if the files are modified too much during the move, they will not be associated with their older versions.

It seems to be working well to me though, so I'll close this issue :)
