### ISSUE TITLE
Angular 13 -> 14 migration fails, nx migrate --run-migrations doesn't run Angular migration, angular.json format is incorrect

### ISSUE THREAD

**Issue by Signaturo** [nrwl/nx#16904]
### Current Behavior

 
`
Run 

`nx migrate —run-migrations`

outputs the result:

```
 Command failed: File 'migrations.json' doesn't exist, can't run migrations. Use flag --if-exists to run migrations only if the file exists

File migration.json doesn’t generate migration.json

```
Run
`run nx serve `

```
outputs the result:

angular.json format is incorrect

   Nx no longer supports the v2 format of angular.json.
```

run `nx report `

outputs the result: 

 ```
>  NX   Using `implicitDependencies` for global implicit dependencies configuration is no longer supported.

   Use "namedInputs" instead. You can run "nx repair" to automatically migrate your configuration.
   For more information about the usage of "namedInputs" see https://nx.dev/deprecated/global-implicit-dependencies#global-implicit-dependencies


 >  NX   The "path" argument must be of type string. Received undefined
```

Run 
`nx repair `

outputs the result: 

```
Failed to run 14-2-0-replace-relative-outputs-with-absolute from nx. This workspace is NOT up to date!

Cannot update Project data-access-prisma at libs/data-access/prisma. It doesn't exist or uses package.json configuration.
```

### Expected Behavior

Automatic Migration of Angular components succeeds, nx serve command works, application starts correctly after migration.

### GitHub Repo

https://github.com/Signaturo/printi-price/tree/migrate_to_nx14

### Steps to Reproduce

1.npm i
2. nx migrate --run-migrations

### Nx Report

```shell
NX   Using `implicitDependencies` for global implicit dependencies configuration is no longer supported.

   Use "namedInputs" instead. You can run "nx repair" to automatically migrate your configuration.
   For more information about the usage of "namedInputs" see https://nx.dev/deprecated/global-implicit-dependencies#global-implicit-dependencies


 >  NX   The "path" argument must be of type string. Received undefined
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I tried the solutions from [this issue 10659 ](https://github.com/nrwl/nx/issues/10659) but nothing worked for me:

More possibly related problems
[15004](https://github.com/nrwl/nx/issues/15004)
[7490](https://github.com/nrwl/nx/issues/7490)
[10628](https://github.com/nrwl/nx/issues/10628)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Looking at the commits in the `migrate_to_nx14` branch in the repo you provided, you seem to have tried to update Nx straight from v13 to latest (v16). That's not recommended and it might produce invalid results or won't work. The recommended approach is to [migrate one major version at a time](https://nx.dev/recipes/other/advanced-update#one-major-version-at-a-time,-small-steps).

Also, I'm unsure how you generated the package updates and migrations. What I see in that branch doesn't match what it would be generated if migrating to latest directly.

That said, if your goal is to update to Angular v14 or Nx v14, please run the following on your main branch (still on v13):

- `npx nx migrate 14.8.8` (latest Nx v14 version)
- `npx nx migrate --run-migrations`

I ran those steps in your repo `main` branch and was able to serve the application successfully.

I will close this since it seems to be an issue with how migrations were run. If you follow the above and still face issues, please feel free to leave a comment and we can reopen this.
