### ISSUE TITLE
CSS are not being correctly bundle in storybook

### ISSUE THREAD

**Issue by adchag** [nrwl/nx#16962]
### Current Behavior

The CSS from node_modules is not being imported to the library.

`import '@material/top-app-bar/dist/mdc.top-app-bar.css'` // this line doesn't work
`import './app-bar.styles.css` // this line works 

### Expected Behavior

The CSS from node_modules should be imported to the library.

### GitHub Repo

https://github.com/frntfinancial/monorepo-sample

### Steps to Reproduce

1. Clone the repository.
2. Run `pnpm i`.
3. Run `nx serve my-awesome-lib:storybook`.
4. Verify that the app-bar is correctly styled with `background-color: #6200ee;`.
5. In `libs/my-js-lib/src/lib/app-bar/app-bar.jsx`, comment out `import './app-bar.styles.css'` and uncomment `import '@material/top-app-bar/dist/mdc.top-app-bar.css'`.
6. Verify that the app-bar is no longer styled.

Note: The content of `mdc-top-app-bar.css` has been copied and pasted into `libs/my-js-lib/src/lib/app-bar/app-bar.styles.css`, so the styling should be applied similarly in both cases.

### Nx Report

```shell
Node   : 16.17.0
   OS     : darwin arm64
   pnpm   : 7.32.0
   Hasher : Native
   
   nx (global)        : 15.9.2
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/next           : 16.1.4
   @nx/react          : 16.1.4
   @nx/storybook      : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @adchag ! This seems to be an issue with Storybook rather than with Nx. Please check this repo I created, which is a pure Next.js app with Storybook, and it has the same problem: https://github.com/mandarini/next-app-storybook
So, I would suggest opening up this issue on the Storybook repository.

However, if you want to solve your issue on your repo you can see what I did in this PR: https://github.com/frntfinancial/monorepo-sample/pull/1

1. Add `vite`
2. Change `@storybook/nextjs` to `@storybook/react-vite`
3. `nx storybook my-js-lib` works as expected

**Comment by brandoncollins7** [comment]
I found out that the new webpack likes to strip out files it thinks aren't being used via sideEffects. css files have it set to false, and because I am not using anything "exported" by a css file the new webpack will strip it out. Literally 5 solid days of work to finally find this solution :(

module.exports = composePlugins(withNx(), withReact(), (config) => {
  const {module} = config

  let cssRule = module.rules.find((rule) => rule.test.toString().includes('css'))
  cssRule.sideEffects = true

  return config
})
