### ISSUE TITLE
Opt-In linter rule: throw error on linting step when directory of a project has a .gitkeep

### ISSUE THREAD

**Issue by CodingSpiderFox** [nrwl/nx#16988]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Some directories in our monorepo still contain a .gitkeep file while there are already some other files in the same directory and thus the folder would not be deleted anyways.

## Motivation
It would keep the folders more clean when the .gitkeep would be deleted as soon as someone adds a version controlled file next to it

## Suggested Implementation
Add a scanner step in the nx lint executor that lets the linting fail when a .gitkeep is in a directory where there are already other versioned files (this should be an opt in feature)

**Comment by AgentEnder** [comment]
`workspace-lint` is due to be removed and a noop now, and `nx lint` just runs the `lint` target on your project. Most frequently, with eslint. I don't believe eslint is capable of linting file structures, only file contents, but there **_may_** be a way to do it. Either way, this is something that we'd recommend configuring just for your project via a lint rule config or custom script.
