### ISSUE TITLE
Need a Cypress 12 migration guide in docs

### ISSUE THREAD

**Issue by cforsyth68** [nrwl/nx#17188]
### Documentation issue

The community needs a guide for upgrading to Cypress 12 (after running @nx migration to latest @nx all my cypress tests are broken now)

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/cypress/documents/v11-migration-guide

### Additional context or description

Might want to mention this guide in the docs too:  https://docs.cypress.io/guides/references/migration-guide

But what we really need is to understand what things we have to do to our NX monorepo to make existing cypress tests work again after NX migration  (cy tests written in older version of Cypress that was installed by previous version of NX).

**Comment by barbados-clemens** [comment]
migrating from v9 to v10/v11 was a special case as before that Nx did perform any migrations for cypress outside of it's own configuration changes. 

as of v10 the cypress plugin does provide migrations between major cypress versions. so after if you're on v11 when v12 comes out then when running `nx migrate latest` cypress will be updated. v12 did bring in breaking changes that could not be automatically migrated though since it's runtime based validations that could not be detected in a straight forward manor with static analysis

In these cases the migration simply commented stating that this piece of code most likely will need to be looked at further with a relevant link to the cypress migration guide . https://docs.cypress.io/guides/references/migration-guide

for v12, the migration was in nx v15.5.0.
https://github.com/nrwl/nx/blob/7ca22adce5229224bec21acc84e593959f435d5f/packages/cypress/migrations.json#L39-L44

You can rerun this migration with the `--from` argument for migrate.

```shell
nx migrate @nrwl/cypress@15.5.0 --from="@nrwl/cypress@15.5.0"
```

hopefully that explains why there isn't a v12 migration page for cypress on the nx docs because it's just now apart of the normal migrate process.

**Comment by barbados-clemens** [comment]
closing as reason has been given as to why no v12 page.
