### ISSUE TITLE
Error: export 'NxModule' (imported as 'NxModule') was not found in '@nx/angular' (possible exports: fetch, navigation, optimisticUpdate, pessimisticUpdate)

### ISSUE THREAD

**Issue by SPokhriyal123** [nrwl/nx#17181]
### Current Behavior

I have upgraded nx version from 13 to 16 in which @nrwl has been updated to @nx.
After the upgradation, I am seeing an error related to NxModule.
Earlier I was using :
import { NxModule } from '@nrwl/angular';

### Expected Behavior

Now this has been upgraded to :  import { NxModule } from '@nx/angular'; 
in which I am getting an error: 
 Error: export 'NxModule' (imported as 'NxModule') was not found in '@nx/angular' (possible exports: fetch, navigation, optimisticUpdate, pessimisticUpdate)

### Steps to Reproduce

1.
 import { NxModule } from '@nx/angular'; 
 Error: export 'NxModule' (imported as 'NxModule') was not found in '@nx/angular' (possible exports: fetch, navigation, optimisticUpdate, pessimisticUpdate)

### Nx Report

```shell
Module '"@nx/angular"' has no exported member 'NxModule'.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `NxModule` was deprecated since v14 and it was removed in v15. You can use the different Data Persistence operators directly in your code as shown in the docs https://nx.dev/recipes/other/misc-data-persistence.

Please note that we are going to deprecate those operators from `@nx/angular`. Since NgRx v16, those operators are available in `@ngrx/router-store/data-persistence` and you should use them from there to be prepared for the deprecation and future removal of those operators from `@nx/angular`. So, instead of:

```ts
import { fetch, navigation, optimisticUpdate, pessimisticUpdate } from '@nx/angular';
```

Do:

```ts
import { fetch, navigation, optimisticUpdate, pessimisticUpdate } from '@ngrx/router-store/data-persistence';
```
