### ISSUE TITLE
Switch to the official CLI distribution

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#173]
Currently we are using a fork of the CLI (see here why https://github.com/nrwl/nx/wiki/FAQ). We should switch to the official CLI distribution as soon as we can.

**Comment by emilio-martinez** [comment]
Cross-linking a ticket (#165) I opened regarding migration tasks for the `@angular/cli` value. I'll keep it as a  separate ticket for the time being, but it could be rolled into this ticket if the scope fits.

**Comment by ThomasBurleson** [comment]
Fixed with SHA acdeb1b

**Comment by dhknudsen** [comment]
I'm a bit confused, but with the release of 0.8.0 and switch to angular-cli 1.7.1, when is the migration file suppose to be available when running `yarn nx-migrate`? I see the file is sitting on master: 
`https://github.com/nrwl/nx/blob/master/packages/schematics/migrations/20180225-switch-to-cli17.ts`
along with 3 other updates since then, but I see none of them executing when I try to migrate our project (our latest migration is `20180130-angular-devkit-schematics`) 
Am i missing something?

**Comment by emilio-martinez** [comment]
@dhknudsen did you install `@nrwl/schematics@0.8.0` and `@nrwl/nx@0.8.0` before running? Also, the old script is being deprecated so you could try running `./node_modules/.bin/nx update`.
