### ISSUE TITLE
Cache invalided when pnpm-lock.yaml is changed

### ISSUE THREAD

**Issue by lstkz** [nrwl/nx#17307]
### Current Behavior

Related https://github.com/nrwl/nx/issues/15116#issuecomment-1568271324

When changing a dependency of any package, the cache is invalided for all packages. Packages are unrelated to each other.

The workaround with `.nxignore` doesn't work.

### Expected Behavior

Commands should be cached because their dependencies are not changed.

### GitHub Repo

https://github.com/lstkz/nx-cache-miss

### Steps to Reproduce

1. git clone https://github.com/lstkz/nx-cache-miss
2. pnpm i
3. nx run a:build    
4. nx run a:build    (verify command is cached)
5. Change `packages/b/package.json` ` "remeda": "1.1.0"` -> ` "remeda": "1.2.0"`
6. pnpm i
7. nx run a:build 
The command is not cached but should be. `a` doesn't depend on `b`.

### Nx Report

```shell
Node   : 18.14.2
   OS     : darwin x64
   pnpm   : 8.3.1
   Hasher : Native
   
   nx (global)  : 16.2.2
   nx           : 16.2.2
   @nrwl/tao    : 16.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by roderik** [comment]
I sometimes use the following hack in the CI

```
    # - name: Hack NX to ignore lockfile changes
    #   shell: bash
    #   run: |
    #     if [[ -f node_modules/nx/src/plugins/js/project-graph/affected/lock-file-changes.js ]]; then
    #       sed -i 's/pnpm-lock\.yaml/something\.yaml/g' node_modules/nx/src/plugins/js/project-graph/affected/lock-file-changes.js
    #     fi
```

**Comment by lstkz** [comment]
I am able to do the following workaround:
1. add to nx.json
```
  "pluginsConfig": {
    "@nrwl/js": { "analyzePackageJson": false, "analyzeSourceFiles": false }
  }
```
2. Add to every package.json
```
  "nx": {
    "implicitDependencies": [ "my-lib-a", "my-lib-b" ]
  }
```
Where `implicitDependencies` are my libraries from package.json "dependencies".

Also, `"analyzeSourceFiles": true` has some random behavior. Sometimes it was able to create the graph correctly, and sometimes some edges were missing, but without changing any source code. The build/test could fail because of the incorrect order.

**Comment by meeroslav** [comment]
Hi @lstkz, this behavior is by design.

## Explanation

We do not analyse the contents of your `build` script so we can't really tell what that command depends on. In you case it doesn't depend on anything since it does just `echo` but it could be depending on the above mentioned `remeda`. Despite having is installed as a dependency of project `b` depending on your package manager, other projects could be accessing it as well.

## Exceptions

When using `@nx/...` executors for your targets e.g. `@nx/js:tsc` we can guarantee which packages it depends on so it will be only affected if one of those packages have changed in your `node_modules`

## Solution

Recently we implemented a solution for such cases. For your target you can specify explicitly which packages it depends on:

```jsonc
{
  ...
  "nx": {
    ...
    "targets": {
      "build": {
        "inputs": [
          "prod"
          { "externalDependencies": [] } // <= this is the only change
        ],
        "outputs": [],
        "dependsOn": []
      }
    }
  }
}
```

What this does is it tells the hasher that our `build` target's executor does not depend on packages.

If you would have some dependencies e.g. `"build": "lerna publish"` then you would simply specify it as `{ "externalDependencies": ["lerna"] }`.

Hope this helps. You can find the official documentation at https://nx.dev/reference/project-configuration#inputs-&-namedinputs
