### ISSUE TITLE
TS2304: Cannot find name '$localize'

### ISSUE THREAD

**Issue by LexanRed** [nrwl/nx#17309]
### Current Behavior

When using i18n with Angular via @angular/localize, the template marker $localize is marked as error in the editor. 

We are using IntelliJ and WebStorm. 

The build itself is working fine, it is just the very annoying error in the IDE which marks every file es containing an error which uses the $localize marker.

The IDE also offers to import it {$localize} from "@angular/localize/init"; 
That makes the build crash, because then $localize is imported as a function and not treated as the template marker anymore.

I guess there is a problem with the typescript configuration. 

If anyone knows a solution or a workaround, I'd be happy to hear it. 

### Expected Behavior

$localize should not be treated as missing field / import.

### Steps to Reproduce

1. Create a new Nx Repo
2. Add Angular application
3. Setup i18n according to the Angular docs
4. Use $localize in any .ts file

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin arm64
   npm    : 9.5.1
   Hasher : Native
   
   nx (global)        : 16.1.0
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nrwl/devkit       : 15.9.4
   @nx/eslint-plugin  : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store             : 16.0.0
   @ngrx/effects                     : 16.0.0
   @ngrx/entity                      : 16.0.0
   @ngrx/router-store                : 16.0.0
   @ngrx/schematics                  : 16.0.0
   @ngrx/store                       : 16.0.0
   @ngrx/store-devtools              : 16.0.0
   @nx-tools/nx-container            : 4.0.3
   @nxrocks/nx-spring-boot           : 8.0.2
   angular-server-side-configuration : 16.0.0
   ng-extract-i18n-merge             : 2.7.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.9.4
   
   To fix this, run `nx migrate nx@16.2.2`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I couldn't reproduce the issue, though I'm using VSCode. Still, the TS configuration looks fine to me and I'd guess the IDE should pick it up correctly. I followed the reproduction steps you mentioned and it worked fine. Some steps are not very detailed, so for a sanity check, these are the steps I ran:

- `npx --yes create-nx-workspace@latest --no-nx-cloud my-repo` (answers: integrated, angular-monorepo, app1, No, Yes, css)
- `npm i -D @angular/localize`
- `npx nx g @angular/localize:ng-add --project app1`
- updated `apps/app1/src/app/app.component.ts`:
```diff
- title = 'app1';
+ title = $localize`app1`
```

Could you provide a reproduction so we can troubleshoot it further? Otherwise, please make sure you have:

- the `tsconfig.app.json` contains `"types": ["@angular/localize"]`
- the `tsconfig.json` has a project reference to the `tsconfig.app.json`
- the `main.ts` file contains `/// <reference types="@angular/localize" />`
- the TS file where you're using the `$localize` symbol is part of the `tsconfig.app.json` TS program (part of the `include` or `files`)

**Comment by LexanRed** [comment]
Thanks for your detailed response. 
I was able to get to the root of the problem. 
Since my app is merely a shell and the heavy lifting is done in libraries, I already added `types: ["@angular/localize"]` to the tsconfig.base.json.

By default every tsconfig.lib.json specifies "types": [] in compilerOptions which overwrites the entry in the tsconfig.base.json.

Is this intended? Is there an option not overwrite but merge the entries of types together? 
Inheriting the config but overwriting any array based property means we have to copy the entries of the base config the every lib which specifies an own type. 

Right now I went through and deleted all empty type config properties in my libs and it seems to work for now.
