### ISSUE TITLE
Documentation enhacements

### ISSUE THREAD

**Issue by fkolar** [nrwl/nx#1768]
#Environment info

```
Angular CLI: 7.3.9
Node: 10.9.0
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

```

# Prerequisites
- [ ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I am trying to find in the docs something that  mentions about `@nrwl/schematics`, meaning if I have existing project where before I followed steps and install the `@nrwl/schematics` and now there is nothing. There is only `@nrwl/workspace and /angular`, nothing that `@nrwl/schematics` is deprecated or something? 

It woudl really help me to mention that `@nrwl/schematics` how come you dont mention this one anymore so developers know that they should now use something else. 

I see there is still `@nrwl/schematics` 7, 8, is this separate path for develoeprs who wants to use ng naturallly ?

**Comment by mehrad-rafigh** [comment]
Hi @fkolar 

In Nx 8 the package structure changed, because NX is moving to become a framework agnostic tool for monostyle repo development. You can read more about it here
https://blog.nrwl.io/nxs-new-look-in-v8-25d7325260d

`@nrwl/schematics` is still used and that's what drives the migrations for nx versions. Say you want to update your nx 7 Workspace to v8, the `@nrwl/schematics` updates your dependecies to make them v8 compatible. While at it, the `@nrwl/schematics` dependencies are deleted and the new packages are added as dependencies. 


The package `@nrwl/workspace` is the new way forward starting with v8.
It includes the schematics and all scripts needed, like the `affected` scripts.

Hope this helps. If you have any question, feel free to post in the Slack Channel: https://github.com/nrwl/nx/issues/1739

**Comment by fkolar** [comment]
Great. So adding nx to existing project that is based on version 7, I would still use `ng add @nrwl/schematics@7`

**Comment by mehrad-rafigh** [comment]
If you are using angular 7 and beneath, than yes.
