### ISSUE TITLE
Introduce a `headers` option to @nx/webpack:dev-server as is the case with @nx/angular:webpack-dev-server.

### ISSUE THREAD

**Issue by triglian** [nrwl/nx#17821]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Introduce a `headers` option to @nx/webpack:dev-server as is the case with @nx/angular:webpack-dev-server.

## Motivation

Very useful to add custom HTTP headers. In our case we wanted to add the `Service-Worker-Allowed` HTTP header.

## Suggested Implementation

Same as for @nx/angular:webpack-dev-server.

cc @jbadeau

**Comment by jaysoo** [comment]
This is already possible just using the webpack [devServer](https://webpack.js.org/configuration/dev-server/#devserverheaders) configuration. There are two options:

Using the [`withNx`](https://nx.dev/recipes/webpack/webpack-plugins#withnx) webpack plugin:

```
const { composePlugins, withNx } = require('@nx/webpack');
const { withReact } = require('@nx/react');

module.exports = composePlugins(withNx(), withReact(), (config) => {
  config.devServer.headers = {
      'X-Custom-Foo': 'bar',
  };
  return config;
});
```

Or starting in Nx 18, using the [`NxWebpackPlugin`](https://nx.dev/recipes/webpack/webpack-plugins#nxwebpackplugin):

```
const { NxWebpackPlugin } = require('@nx/webpack');
const { NxReactWebpackPlugin } = require('@nx/react');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/demo'),
  },
  devServer: {
    port: 4200,
    headers: {
      'X-Custom-Foo': 'bar',
    }
  },
  plugins: [
    new NxWebpackPlugin({
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      index: './src/index.html',
      styles: ['./src/styles.css'],
      outputHashing: process.env['NODE_ENV'] === 'production' ? 'all' : 'none',
      optimization: process.env['NODE_ENV'] === 'production',
    }),
  ],
};
```

We'd rather users configure it directly through webpack rather than add a new executor option that does the same thing.
