### ISSUE TITLE
Fails on npm warnings with nodejs prerelease version

### ISSUE THREAD

**Issue by theoparis** [nrwl/nx#17846]
### Current Behavior

I ran:
```
npx create-nx-workspace@latest . --preset=npm
```
 
However, with a prerelease/bleeding edge nodejs version, nx assumes the warnings from npm are fatal.

### Expected Behavior

nx should ignore these warnings and proceed.

### Steps to Reproduce

1. Build nodejs from source on the latest commit
2. Try to setup an nx workspace

### Nx Report

```shell
>  NX   The current directory isn't part of an Nx workspace.

   To create a workspace run:
   npx create-nx-workspace@latest <workspace name>

   To add Nx to an existing workspace with a workspace-specific nx.json, run:
   npx nx@latest init
```

### Failure Logs

```shell
✖ Creating your workspace in .

 >  NX   Failed to create a workspace.

   Error: npm WARN cli npm v9.7.2 does not support Node.js v21.0.0-pre. This version of npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
First things first, `npx create-nx-workspace@latest . --preset=npm` is not a good command... you should pass a name for the workspace:

```
npx create-nx-workspace@latest my-workspace --preset=npm
```

Otherwise, Nx will try to create the workspace in your current working directory... The expected behavior is for it to create a new directory with your workspace in it.

Okay, so that is the real error that was indeed obfuscated by the warnings from `npm`. 

However, at the moment, Nx doesn't work with the nightly/pre version of Node anyways. We could look into that deeper but for now, I'll fix the obfuscation of the error.
