### ISSUE TITLE
Add a flag to apply packageManager value to package.json generated by generatePackageJson, if packageManager is specified in root's package.json.

### ISSUE THREAD

**Issue by yizumi1012xxx** [nrwl/nx#17932]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Add a flag to apply packageManager value to package.json generated by generatePackageJson, if packageManager is specified in root's package.json.

## Motivation
I have specified packageManager in package.json in the root directory, but I am having trouble because the value is not reflected in package.json generated by generatePackageJson.

## Suggested Implementation
1. Add `packageManager` option to `@nx/webpack:webpack`. This option is valid only if generatePackageJson is true. If a value is specified, add that value to the generated package.json. Default value is `undefined`.

2. Add `inheritRootPackageManager` option to `@nx/webpack:webpack`. This option is valid only if generatePackageJson is true. If a value is true, `packageManager` field will inherit the value of the root's package.json. Default value is `false`.

3. Add `inheritRootPackageJson` option to `@nx/webpack:webpack`. This option is valid only if generatePackageJson is true. This option can be specified as an array of strings, and the specified string fields will inherit the value of the root's package.json. Default value is `[]`.

**Comment by jaysoo** [comment]
If you create a `package.json` file under the app, it will inherit values from it.

e.g.
```json5
// apps/demo/package.json
{
  "name": "demo",
  "packageManager" "pnpm@~8.7.0"
}
```

Then running `nx build demo`, you will see the values from `apps/demo/package.json` in the `dist/apps/demo/package.json` file (minus `dependencies` and `devDependencies`).

We don't want to inherit from the root `package.json` as it likely contains entries like `scripts` that you don't want to end up in your app's `package.json` file.

**Comment by alumni** [comment]
I already created a patch for our repo to copy `resolutions`, `pnpm` and `packageManager` from the root package.json.

Since lockfile pruning seems to be broken for `pnpm`, we are also running `pnpm prune` in the Dockerfile.

Since we maintain the dependencies, packageManager, dependency resolutions and patches for the entire monorepo, it makes more sense for us to use the root package.json.

We like that nx takes the dependencies from the root package.json and picks only the ones used in each app when generating the app package.json. I think that resolutions/overrides and patches should also be handled, as well as the package manager, but luckily it is quite easy to patch nx if it doesn't behave this way :)

**Comment by alumni** [comment]
I opened #18402 since I realized there's a bit more than just copying some keys from the root `package.json`, pruning is also needed for those things.

Regarding `packageManager` - in our setup we use a single package manager and keep the dependencies in the root `package.json`. I see the package manager also as some sort of dependency.

Renovate for example bumps by default the versions in `*dependencies`, `packageManager`, `resolutions` (yarn/pnpm) `overrides` (npm) and `engines` since they treat everything as a project dependency - they are not aware of `pnpm.overrides` or `pnpm.patchedDependencies` yet.

I would definitely NOT inherit the `scripts` from the root, nor the `name`/`description`.
