### ISSUE TITLE
projectRoot and workspaceRoot unclear

### ISSUE THREAD

**Issue by vergilfromadyen** [nrwl/nx#17948]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/concepts/how-caching-works

### Additional context or description

Currently the documentation says:
> `{projectRoot}` is a key word that is replaced by the path to the current project's root directory.
`{workspaceRoot}` is a key word that is replaced by the root path of your workspace.

However:
- projectRoot can be interpreted as "the folder that contains a project.json file" (which is typically a npm workspace). Saying "*current* project's root" doesn't help either.
- workspaceRoot can be interpreted as "one of your workspaces in your monorepo" (which is also a project).

If we take [one of the NX repos](https://github.com/nrwl/react-module-federation) as an example, does `projectRoot` refer to the folder where `nx.json` is and `workspaceRoot` to one of the `libs/*` folders or the other way around?

**Comment by AgentEnder** [comment]
Nx `projects` are analagous to a `workspace` in pnpm / npm / yarn workspaces. Within Nx when we talk about "the workspace", "your workspace" etc youll notice its never plural. The entire repo is your Nx workspace. (e.g. create-nx-**workspace**)

The **_are_** cases where workspace root or project root may be the same thing, if you have a project at the root of your workspace as an example or if you use a standalone app preset rather than a monorepo setting.
