### ISSUE TITLE
Using nrwl/nx ngrx cli, puts all state into singular +state directory

### ISSUE THREAD

**Issue by CharlieGreenman** [nrwl/nx#181]
Using the nx ngrx cli is very nice. However, instead of it putting all the files in a single state directory, I was wondering if we could split actions, reducers, effects, and interfaces(models), into their own directories? I think it would allow for things to be a bit more manageable. 

The following is a great example of what I mean: https://github.com/ngrx/example-app/tree/master/src/app

**Comment by dereklin** [comment]
Todd Motto released a very high quality ngrx store + effects course at https://ultimateangular.com/ngrx-store-effects

He has shown a very clean code structure regarding ngrx.

Here is the repo: https://github.com/UltimateAngular/ngrx-store-effects-app/tree/27-testing-effects

I think I would follow his code structuring for now.  It would be nice if nx can use something similar or enhance on top of it.

**Comment by kylecordes** [comment]
I'm a bit skeptical of the approach shown in that repo. It reminds me a lot of early AngularJS guidelines which recommended a directory to put all your directives then, a directory to put all your filters and, a directory to put all your services in. That of course turns out to be a great learning step... but when we used AngularJS at scale, we organized things according to the problem domain or other concern, but not according to what kind of AngularJS "thing" they are.

I have seen the same thing happened with NgRx applications that we work on...  we started out dividing the world into reducers and so on, but over time, our files instead are broken down according to the problem domain in some way. Fluently using the relevant kinds of NgRx bits where appropriate.

**Comment by MarkPieszak** [comment]
I just wanted to add to what Kyle is saying, that the benefit of having your files organized by “feature” is that when you’re working on or looking through a specific ngrx portion (let’s say Bicycles), you have all the relevant reducers/selectors/actions right next to each other for Bicycles - rather than shifting through large folders that could have countless files in them (once your state management gets quite large).

**Comment by CharlieGreenman** [comment]
@kylecordes + @MarkPieszak valid points, and I definitely would like to hear more about it. It really comes down to making sure that one adheres to breaking down into smaller modules when appropriate, so that the different actions/reducers do not pile up in the folder. I actually do understand that, and I like that approach. I think that perhaps following nrwl/nx's code structure for the most part, and then creating a shared folder, for state expected to be used across the app(with it's own specific reducer/action/constant folder structure), is something that I would be interested in doing. A hybrid'ish approach :)

That being said, from a user perspective:

The core contributors of ngrx/store seem to recommend the following [code structure](https://github.com/ngrx/example-app/tree/master/src/app):. The core contributors of nrwl/nx seem to recommend otherwise. However, I have not been able to find an article specifying as to why I should follow nrwl/nx's code structure. I think we should create a doc someplace, as to why we chose that architecture.

Alternatively, if an article like this already exists, specifying why the nrwl/nx team decided to make actions, reducers, effects module specific, a link would be also suffice. Thank you, and I appreciate your time.

**Comment by netwobble** [comment]
@CharlieGreenman .. I agree with 2 foundation projects recommending different approaches makes it hard to say what best practice is.  

Adding a folder structure does not dictate that all files of that type live there.  I agree everything should be split into features.  That being said a given feature, in reality, also contains sub features and allowing to have multiple files (example reducers or effects) gives projects flexibility .  Even if the dir only contains one folder most of the time.

Given this approach, I think the use of index.ts files to roll up exports could be used to wire-up all the pieces.  This will give one consistent pattern to implement a single feature or a feature and sub features (domain).  

With enterprise software having one pattern that can handle both requirements just makes sense.  In addition the nx generator can take care of all the wiring up.  

just my 2 cents,

AJ

**Comment by vsavkin** [comment]
I agree that depending on your background/experience you can find one approach more preferable than the other one. E.g., if you have Rails experience, you will find grouping by file type more natural.

At this point, we decided to follow the default NgRx schematics as close as possible (we actually invoke them under the hood). The default schematics don't group by file type and, as a result, we don't either.

I think ideally you should have small enough libs so one +state folder is sufficient. When not, you can do something like this:

```
ng g ngrx feature1 --directory=+state/feature1
ng g ngrx subfeature1 --directory=+state/subfeature1 --onlyAddFiles
ng g ngrx subfeature2 --directory=+state/subfeature2 --onlyAddFiles
```

which will result in the following:

```
+state/
    feature1/
        feature1.actions.ts
        feature1.reducer.ts
        ...
    subfeature1/
        subfeature1.actions.ts
        subfeature1.reducer.ts
        ...
    subfeature2/
        subfeature2.actions.ts
        subfeature2.reducer.ts
        ...
```

Closing this issues because we are going to stick with the default NgRx schematics unless there is a very good reason not to.
