### ISSUE TITLE
Nx marks all projects as changed if a single project is removed

### ISSUE THREAD

**Issue by hytromo** [nrwl/nx#18112]
### Current Behavior

When I fully remove a project all my other projects are marked as affected. This doesn't have to do with change in the global files (`tsconfig.json`, `package.json`, `package-lock.json` etc). In the reproducible example I provide you will see that my projects are single-file (just `project.json`)

### Expected Behavior

No project is marked as affected if a project is removed.

### GitHub Repo

https://github.com/hytromo/nx-bug-all-changed

### Steps to Reproduce

1. Go to the `improvement--remove-pkgA` branch
2. Run `npx nx show projects --affected --base=main --head=HEAD` and `PAGER= git diff --name-only main`, the outputs will be `pkgB` and `packages/pkgA/project.json` respectively.

I've also reproduced this in the CI through the https://github.com/nrwl/nx-set-shas github action. See the "Show affected projects" step in https://github.com/hytromo/nx-bug-all-changed/actions/runs/5552134257/jobs/10139088661#step:5:1

### Nx Report

```shell
   Node   : 19.8.1
   OS     : linux-x64
   npm    : 9.5.1

   nx         : 16.5.2
   @nrwl/tao  : 16.5.2
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This is intentional. We mark all projects as affected when a project is deleted.

When we calculate affected, it is calculated off of the current graph. The current graph has no idea what the deleted project was and won't draw any connections to it. If a different project depended on it, that project would be broken even though it no longer has a dependency to the deleted library. Thus, the safest thing we can do is to mark all projects as affected.

Fortunately, if the tasks are cacheable, any projects that don't depend on the deleted project will still be cached. This will still prevent long CI times for cached tasks when deleting projects.

**Comment by hytromo** [comment]
> Fortunately, if the tasks are cacheable, any projects that don't depend on the deleted project will still be cached. This will still prevent long CI times for cached tasks when deleting projects.

This assumes only a few projects inside the monorepo whose CI initialization times are short. Even if the build tasks are cacheable, many projects have to go through time consuming (and disk space hungry) tasks before reaching the cacheable tasks. Not to mention that in many CI/CD cases the changed projects will also be auto-deployed once a PR is merged which can add a ton of time on top as well.

Big monorepos with a diverse range of projects really don't benefit from such a behavior. Ideally there should be a configuration option to control the behavior of Nx when a project is being deleted. This will cover a more wide range of use cases, but I understand why this default is OK for the typical Nx user whose monorepo contains only npm packages with hoisted dependencies and only a few services.

---

I want to point out that straight up closing down an issue with a "Works as expected" message without giving the opportunity for further discussion doesn't send the best message to the community.
