### ISSUE TITLE
generatePackageJson does not include local publishable dependencies (REACT + VITE)

### ISSUE THREAD

**Issue by tnrich** [nrwl/nx#18332]
### Current Behavior

nx run nxtester123:build:production does NOT include local libs in the generated package json file

### Expected Behavior

nx run nxtester123:build:production should include publishable libraries in the generated package json file.

### Steps to Reproduce

1. Either just clone the repo here - https://github.com/tnrich/nxtester123 or follow these steps to make it:
```
npx create-nx-workspace
```
Use the following options:

✔ Where would you like to create your workspace? · nxtester123
✔ Which stack do you want to use? · react
✔ What framework would you like to use? · none
✔ Standalone project or integrated monorepo? · integrated
✔ Application name · nxtester123
✔ Which bundler would you like to use? · vite
✔ Default stylesheet format · css
✔ Enable distributed caching to make your CI faster · No

Set the following in libs/zonk/package.json:
```
generatePackageJson:true
```

Make a new lib:
npx nx generate @nx/react:library --name=zonk --bundler=vite --importPath=@tg/zonk --publishable=true --no-interactive 

Import that lib into apps/nxtester123/src/app/app.tsx : 
```tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Zonk } from '@tg/zonk';
import styles from './app.module.css';

import NxWelcome from './nx-welcome';

export function App() {
  return (
    <div>
      <Zonk />
      <NxWelcome title="nxtester123" />
    </div>
  );
}

export default App;
```
 
2. Then run `nx run nxtester123:build:production` 
Look at dist/apps/nxtester123/package.json and you'll see that the @tg/zonk module is not included as a dep!

### Nx Report

```shell
nx report
>  NX  Unable to locate swc-node or ts-node. Nx will be unable to run local ts files without transpiling.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 16.13.0
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/react          : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   @nx/web            : 16.5.5
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @tg/zonk
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Please help! Thanks

**Comment by jaysoo** [comment]
I don't think this is a valid use-case, because the browser bundle must contain all of the code necessary to run the app. Since the `@tg/zonk` workspace library is bundle into the app, it doesn't need to be specified as a dependency in `package.json`.

If this is for a library, we are removing `--generatePackageJson` support for libraries in favor of managing dependencies using the `@nx/dependency-checks` lint rule (it will validate and fix issues). We want the source `package.json` file to be correct, and we just help with detecting and fixing errors during `nx lint pkg` and `nx lint pkg --fix`. This method allows Nx to help users like we did before (by automatically picking up deps), but give users full control into what should go into `package.json`. See: https://nx.dev/packages/eslint-plugin/documents/dependency-checks

**Comment by tnrich** [comment]
@jaysoo ok thanks for setting me straight here. I've got my repo set up so the individual packages don't need to specify their deps so perhaps I'll consider moving towards that direction in the future. 

Thanks for the response!
