### ISSUE TITLE
Command is considered failed if local caching step fails

### ISSUE THREAD

**Issue by samijaber** [nrwl/nx#18449]
### Current Behavior

If something goes wrong when copying to locale cache (like https://github.com/nrwl/nx/issues/18448), the whole step is considered to have failed. This is a bit overly aggressive, as the error is an Nx caching error only, and has nothing to do with the user's script.

### Expected Behavior

The step should be considered a success, with the locale cache for that task reset. 

### Steps to Reproduce

1. clone https://github.com/BuilderIO/builder/pull/2521 into an M1 mac
2. go to packages/
3. run yarn
4. go to packages/core
5. run yarn nx build

Alternatively, create any simple Nx project and manually edit this function to throw an error:

https://github.com/nrwl/nx/blob/1dcb80d447f115c0054b8782fdf1a2dd118d0cdd/packages/nx/src/tasks-runner/cache.ts#L187 

### Nx Report

```shell
Node   : 16.14.0
   OS     : darwin-arm64
   npm    : 8.3.1
   
   nx (global)  : 16.6.0
   nx           : 16.6.0
   lerna        : 3.20.2
   @nrwl/tao    : 16.6.0
   nx-cloud     : 16.2.0
   typescript   : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @e2e/next-app-dir-client
         @e2e/next-pages-dir
         @builder.io/sdk-vue-3
         @builder.io/sdk-vue-2
         @e2e/next-app-dir
         @e2e/gen1-react
         @e2e/solid-start
         @e2e/gen1-next
         @e2e/sveltekit
         @e2e/qwik-city
         @e2e/solid
         @e2e/svelte
         @e2e/react
         @e2e/vue3
         @e2e/vue2
         @builder.io/react
         @builder.io/sdks
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This is as intended because the cache is a core part of Nx. Ideally, this process is bulletproof and the implementation does its best to ensure that it is such as retrying multiple times.

We have 2 options here:

1. We error when Nx fails to use the cache and fail the command
  a. Although this adds the possibility of Nx causing errors that wouldn't be there if the user was not using Nx, it ensures that the cache is working as expected. If it errors for whatever reason, it is better to not update the version of Nx, report the issue, and wait for it to be fixed. We will handle these issues with utmost urgency.
2. We warn users when Nx fails to use the cache and do not fail the command
  a. This allows users to use Nx even if the cache is not working at all or working intermittently. In these cases, Nx is not doing its intended purpose but because the command passes, users may or may not report the issue. In some cases, users might even move from a version of Nx which works as intended to a version of Nx which does not work as intended.

Of these 2 options, we choose option 1 because we believe that the cache is such a core feature of Nx that it needs to work. 

We looked at the issue you were experiencing together which was mysteriously resolved. Please let us know if you have issues again.

**Comment by Tom910** [comment]
@FrozenPandaz maybe is it possible create a fallback logic, if something in cache don't work (like copy of data), skip cache and works without cache? Sometimes I have a similar issue
