### ISSUE TITLE
Get `nx graph` data via stdout

### ISSUE THREAD

**Issue by skeate** [nrwl/nx#18689]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Add a mechanism to get project graph data out of nx in a manner useful for scripts.

## Motivation
`nx graph` by itself spins up a web server to serve an interactive graph, which is fine for humans but unusable for scripting. Sometimes it would be nice to programmatically get (for example) a list of the internal projects that a particular project depends on.

## Suggested Implementation
A `--stdout` option (or something similar) for the `nx graph` command.

## Alternate Implementations
There is a workaround, though it's a bit convoluted; `nx graph` already can output JSON if you give it a `--file=<something>.json` option (presumably this looks at the extension, since you can also do `--file=<something>.html` and get an HTML page). Thus, with some tempfile shenanigans, you can get a one-liner that does the same kind of thing, something like

```sh
$TMPDIR=$(mktemp -d) nx graph --file=$TMPDIR/graph.json && \
  jq -r ".graph.dependencies" $TMPDIR/graph.json
```

but that's ugly, and I'm honestly not sure how portable it is (my original attempts used other options of `mktemp` which aren't actually options in MacOS's version of the program).

Since there's already the mechanism to output JSON, this should be a fairly simple addition. But maybe there _is_ already a way (aside from my hack) and I just couldn't find it in the docs.

**Comment by FrozenPandaz** [comment]
There is actually a way.

You can pass `--file stdout` but I think we can definitely add a `--print` flag which would print the graph to the terminal.

Would you be interested in making a PR?

**Comment by skeate** [comment]
Hmm. I feel like there's not too much gain with `--print` over `--file stdout`; it's just pretty unclear that the latter is an option from the documentation. Maybe this is just an "improve docs" request?

Or do you think it would be worth having a separate `--print` flag for better discoverability?

Either way, yeah, I can probably make a PR for this.

**Comment by FrozenPandaz** [comment]
Exactly, `--print` is more self-explanatory. It will show up in the docs, --help, etc.

We cannot remove `--file stdout` because it allows for `nx build nx --graph stdout`.

`--file stdout` also needs to be documented properly though. That would be a separate change though.

**Comment by rlmestre** [comment]
I could take this if work hasn't started on it yet. (adding the new flag + docs, docs for `--file stdout`)

**Comment by jhecking** [comment]
I was looking for a way to use the generated graph programatically as well and was very happy to find out about the `stdout` option through this ticket. Especially  since it works with `nx affected --graph <file>` as well. Definitely should be documented better!

However, I am still facing some minor issues with this feature:

1. When trying to pipe the output of `nx affected -t build --graph stdout` to another command the output seems to be truncated. E.g. `nx affected -t build --graph stdout | jq .` results in "parse error: Unfinished JSON term at EOF at line 2566, column 4". 

```
❯ nx affected -t build --graph stdout | tail
              "options": {
                "lintFilePatterns": [
                  "apps/borneo-cli/**/*.ts"
                ]
              },
              "configurations": {}
            }
          },
          "tags": [],
          "implicitDepen
```

On the other hand, when redirecting the stdout output to a file, it seems to be complete – obviously, this defeats the purpose of using `--graph stdout` in the first place, though.

```
❯ nx affected -t build --graph stdout > graph.json

❯ tail graph.json
      "smithy:build": [],
      "borneo-workers:bundle-workflows:production": [],
      "borneo-encryption:build": [],
      "borneo-client-internal:build": [
        "smithy:build"
      ],
      "smithy-server-express:build": []
    }
  }
}
```

2. Depending on other options passed, `nx graph --file stdout` includes other content in the output on stdout, which makes it hard to process it, e.g.

```
❯ nx graph --affected --file stdout | head

 >  NX   Affected criteria defaulted to --base=main --head=HEAD

{
  "graph": {
    "nodes": {
      "borneo-client-internal": {
        "name": "borneo-client-internal",
        "type": "lib",
        "data": {
```

If this text would be printed to stderr instead it would be easy to filter out, e.g. `nx graph --file stdout 2>/dev/null`. Or, alternatively, maybe there should be a `--quiet` or `--silent` option or some such.
