### ISSUE TITLE
Are react-native sync-deps and ensure-symlink necessary?

### ISSUE THREAD

**Issue by ste7en** [nrwl/nx#18788]
Hi, I'm opening this issue more as a feedback / clarifications post than a real issue. 

With `react-native 0.72` Metro is finally shipped with support for symlinks and what I am wondering is if we still need to run the `sync-deps` and `ensure-symlink` targets in our applications. 

Previously, I thought `sync-deps` was only needed as prerequisite for the ensure-symlink target in order to symlink the correct `node_modules` within the app folders, but do we really need to specify twice the dependencies of our apps both in the workspace and project's `package.json` files?

Also, is it safe to remove those targets from `project.json`?

Thanks for any clarification

**Comment by xiongemi** [comment]
Currently, for react native 0.72, I think the support for symlink is still beta, so that is why i still add the symlink to dependsOn just in case it is unstable. once it is fully supported in 0.73, i think i will remove this dependsOn.

**Comment by ste7en** [comment]
Thanks for answering @xiongemi . Regarding the `sync-deps` target instead, do you think we can avoid redeclaring dependencies in the project-level package.json once the symlink support will be stable?

In particular I don't get how that target should be used: it adds a `*` for the version of a specific dependency but can lead to version mismatch with the ones declared in the workspace-level package.json, especially during upgrades. Also, I don't get why some dependencies need to be listed and others don't, especially when `ensure-symlink` creates a symlink'd node_modules in the project folder

**Comment by xiongemi** [comment]
the reason why there is a project-level package.json is to run `pod install`. however, if in the future, symlink is supported and pod install can be run, then I will remove the package.json.

**Comment by arekkubaczkowski** [comment]
> Thanks for answering @xiongemi . Regarding the `sync-deps` target instead, do you think we can avoid redeclaring dependencies in the project-level package.json once the symlink support will be stable?
> 
> In particular I don't get how that target should be used: it adds a `*` for the version of a specific dependency but can lead to version mismatch with the ones declared in the workspace-level package.json, especially during upgrades. Also, I don't get why some dependencies need to be listed and others don't, especially when `ensure-symlink` creates a symlink'd node_modules in the project folder

@xiongemi  I would like to bump those questions, I understand that it is needed for pod install but how can that work if the versions of dependencies are different from workspace level package.json? I don't find it usable because of that, also sync-deps doesn't move all necessary dependencies to project level package.json which leads to errors while pod-install.

**Comment by xiongemi** [comment]
@arekkubaczkowski currently nx only supports single version policy, meaning developers define all dependencies in the root package.json file. ideally, the react native node modules should not be different from the workspace root node modules.

in the future, i am going to take out the symlink node_modules since react native no longer requires it.
however, i still need the sync-deps target for pod-install.

you can remove the sync-deps target in your project.json if you got different versions of app from workspace root. remove "sync-deps" from all the "dependsOn", so it will not change anything in your project package.json:

```
"start": {
      "executor": "@nx/react-native:start",
      "dependsOn": [], // <-- remove sync-deps here
      "options": {
        "port": 8081
      }
    },
```
