### ISSUE TITLE
override module boundaries rule

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#188]
Is there a way to override the module boundary rules for deep imports?  With the way actions are defined as string types I wanted to add an object that apps can reference to cut down on bugs from misspellings (i.e. 'LOAD_DATA' would be referenced by an object called MyActions and a property called LoadData with value of 'LOAD_DATA').  I thought I could get around the deep imports issue by re-exporting that object in the libs index.ts file but then ended up with a circular dependency with the module and reducer. Having this rule is having me spend more time figuring out where to export my modules rather than actually developing them.

**Comment by vsavkin** [comment]
Could you provide an example (a github repo) illustrating the issue?

**Comment by jasedwards** [comment]
The more I worked with it the more I realized it could be solved if I just designed my libs better so that is what I did.  This is just a little inconvenient I guess for large libraries as I have to reexport all of my providers in index.ts.  Perhaps it could automatically export providers in that file when they are generated?

**Comment by vsavkin** [comment]
By providers you mean "custom services"?

**Comment by vsavkin** [comment]
Sorry for the late response.

I follow this rule: Everything we generate should be useful 9 times out of 10.
And I'm not sure that 9 or 10 services should be exported. For instance, lazy loadable libraries almost never want to export their services. And because over exporting doesn't break any tests, the result will be that a lot of services will be made public, where they should not be.

The second rule I follow is: don't change what the CLI does unless you have to. Since we merely delegate to the CLI schematic here, I'd prefer not to add any new behavior, to keep Nx as close to the CLI as possible.

Given these, I think we should stick with the current behavior.

**Comment by jasedwards** [comment]
Makes sense.  For something like this then where the module is used to initialize all the apps and provide common services would you recommend I don't make it so much a "lib" module but just a folder in libs that people can import?

**Comment by Skubakoob** [comment]
Just hit the same issue - what did you do in the end? Did you put these services into a separate folder or keep them within their libs?

**Comment by jasedwards** [comment]
Unfortunately if I am doing something like a control library my only choices seem to be 
1.  manually export every control in the index.js.
2. don't make it an actual lib in angular-cli.json.  of course doing this causes you to lose the ability to generate stuff automatically.  Not real good solution
