### ISSUE TITLE
deprecating generatePackageJson breaks key use-case of nx

### ISSUE THREAD

**Issue by firxworx** [nrwl/nx#18851]
Building something with `generatePackageJson: true` in `project.json` now shows a deprecation warning and advises to replace its use with an eslint rule from `@nx/dependency-checks`.

Issue: no  _lint rule_ could possibly serve as a replacement for a configuration option that has such a significant influence on the build output produced by Nx.

### Current Behavior

`generatePackageJson: true` in a `project.json` has significant impact on the dist output especially for a buildable and/or publishable library.

If removed for apps/libs then (confirmed with esbuild bundler): `package.json` in `dist/` can no longer have `module` and `main` dynamically set during the build nor will the file include any dependencies.

This could break all kinds of scenarios including: docker, lambda development, and being able to import libs into front-end and back-end apps.

### Expected Behavior

I expect that I can still use Nx to manage my various project workspaces after you deprecate `generatePackageJson` 
(or decide to keep it or provide alternate ways to achieve the same results)

One of the primary draws to Nx is the promise of shared libraries that can be used across the stack that can also be easily published for use outside of a workspace.

I have no idea how to to achieve this in a real-world project without `generatePackageJson`. 
If there is a way please advise!!

@meeroslav I saw your comment on https://github.com/nrwl/nx/issues/18503 and thought to make this issue,

### GitHub Repo

Easily replicate with any nx by changing `generatePackageJson`

### Steps to Reproduce

I will provide a detailed example of essential `generatePackageJson` behaviour to have reusable libraries in a workspace.

Important context is that Nx does not currently have strong support for ESM: there are issues with generators (Node!), dependency graph generation, etc.

In practical terms this means buildable libraries that output both CJS (e.g. for Express per `@nx/node`) + ESM (e.g. React with Vite bundler) really help everything work and play nice within an Nx workspace.

Note even if Nx did work well with ESM, its still an important requirement to be able to build and publish packages with support for both CJS + ESM support as many popular libs do and many orgs would require.

### Example Use-Case: Steps

One of my current workflows with shared buildable+publishable libs and the `esbuild` bundler:

**Step 1**: In `project.json` under the "build" target set `"generatePackageJson": true` and `"format": ["cjs", "esm"]` to build for both CJS + ESM. 

CJS enables apps and libs built with the Node generators (Express, Fastify, etc) to import from shared libs and have no issues with dev servers, build, deploy etc.

ESM is essential for ESM-forward frameworks (e.g. Vite+React) to import and properly tree-shake. Tree shaking is _essential_ for front-end especially (plus, in general its good to not have bloated bundles for back-end either, e.g. lambda deployments).

**Step 2**: Strip the `package.json` in the lib to not have any `type`/`module`/`main` properties.

The removal causes these entries to not influence the build output. The build process will now generate a `package.json` with the correct entries.

An example of a stripped `package.json` I use on a lib is:

```
{
  "name": "@hello/example",
  "version": "0.0.1",
  "dependencies": {},
  "sideEffects": false
}
```

I specifically set `sideEffects` to `false` (or state them if there are side effects) in order to enable tree-shaking when consumed by ESM projects. Otherwise a tiny one-liner function import will cause the kitchen sink to be included in the bundle.

**Step 3**: Build. This dist will have a `package.json` emitted that adds `module` and `main`:

```json
{
  "name": "@hello/another-example",
  "version": "0.0.1",
  "dependencies": {
    "dotenv": "^16.3.1",
    "dotenv-expand": "^10.0.0",
    "slonik": "^34.1.0",
    "slonik-interceptor-field-name-transformation": "^1.6.5",
    "slonik-interceptor-query-logging": "^1.4.7",
    "zod": "^3.22.2"
  },
  "sideEffects": false,
  "module": "./index.js",
  "main": "./index.cjs"
}
```

The above shows one of the most significant behaviour differences of `generatePackageJson`:

**It populates the dependencies.**

No lint rule is going to modify build behaviour like this!

---

If one removes `generatePackageJson` or sets `generatePackageJson: false` the `package.json` emitted is now the following: 

```json
{
  "name": "@hello/another-example",
  "version": "0.0.1",
  "dependencies": {},
  "sideEffects": false
}
```

This is for a library that's supposed to be both **buildable** and **publishable**:

With `module` and `main` absent the library is borked.

Taking a look at other issues... I haven't confirmed, but its quite possible https://github.com/nrwl/nx/issues/18106 and others like it are related. Perhaps someone took action on the deprecation notice and may not have been aware of the consequences. 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : linux-x64
   pnpm   : 8.6.12

   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/esbuild        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/node           : 16.7.4
   @nx/react          : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.2.2
```

### Failure Logs

```shell
There are no failures if we keep generatePackageJson behaviour.
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you for raising the concern @firxworx. We can assure you this decision was not made hastily and was carefully thought through. 

## An insight into future changes
We are deprecating only the `generatePackageJson` option, not the functionality. 
- The applications (lambdas etc.) will be built the same way as before with generated package.json and additional pruned lock files. You have somewhat control over the resulting `package.json` by having a local `package.json` in the app's folder.
- The libraries will no longer "generate" `package.json` but rather copy it over to the output folder. Our generators already set the necessary defaults when you generate a buildable library
- Before we remove `generatePackageJson`, we will migrate all the projects to ensure the missing configuration is set in the local `package.json` files.

## An insight into the reasoning
The current `generatePackageJson` functionality is fundamentally broken. It was trying to solve two vaguely similar, but essentially different problems:
- Generating `package.json` for publishable libs
- Generating `package.json` for applications

The applications benefit from a strict version policy and need a pruned lock file to ensure the final installation (via docker or using some bucket) will use the exact packages we have installed in our monorepo. The ideal scenario is to bundle everything, except for the platform-specific external dependencies.

Publishable libraries, on the other hand, benefit from loose version ranges. For example, the `react-helmet` repo uses `react: 16.13.1`, but the published version has peer dependency to `react: >=16.3.0`. We can't tell this by reading the root `package.json`. This should be your decision and your responsibility. 

### The problems with existing `generatePackageJson`

The current functionality is very rigid, mainly because it was built to serve two masters - apps and libs:
- Versions are read directly from the root `package.json` and changes need to be done manually
- We are reading all the production files when detecting dependencies (including any configuration files like `webpack.config.js`. You can't opt out of this and need to modify `package.json` after the build manually
- While we add all the missing dependencies, we don't remove any obsolete ones. This potentially ends up with several unused dependencies defined in the output `package.json`
- We don't check for version mismatches leading to potential problems

### The proposed solution
- Buildable libs already come with healthy defaults (setting `module`, `main` etc.)
- Before we sunset the `generatePackageJson` there will be migration to apply those defaults to existing projects. At the moment you can copy it over from the generated package.json
- Linter rule will remind you of any missing, obsolete or mismatched packages in the package.json
- Rule is not opinionated, and as long as the package is defined anywhere (dependencies, optionalDependencies, peerDependencies) it will accept it. Also, any version range that contains the installed package version is acceptable.
- You can optionally override the build target name, ignore certain packages or files when detecting dependencies

All of this gives you more control and freedom when shaping your `package.json` while at the same time, automated fixes give you a similar level of `works-out-of-the-box` behavior that you are used to.

If you find any specific missing behavior from the new functionality, please open a dedicated issue and we will make sure to address it as fast as possible.

Hope it's more clear why this change was needed and why it's actually better for you.
