### ISSUE TITLE
Add in tests using @ngneat/spectator

### ISSUE THREAD

**Issue by adamlesniak** [nrwl/nx#18855]
## Description

Using the schematics provided in `@ngneat/spectator` that are going to provide overall better readability and usage of the unit tests in Angular - that's simplified compared to standard angular boilerplate.

## Motivation

Current Angular tests appear heavy at first use and not intuitive, Spectator introduces testing hosts, standard components, and services.

**Comment by AgentEnder** [comment]
At Nx, we love spectator. That said, not everyone uses it and it may not be a great fit for all workspaces. Additionally, adding it to our generated tests moves them further away from the generated angular cli tests, which may be confusing for new users. User's moving from Angular CLI without exposure to spectator would need to learn it, and Nx, rather than just Nx.

If this is a good fit for your workspace, I'd recommend creating a plugin in it that contains these generators, and perhaps wraps our angular generators. This could then be published as a community plugin if you feel it would provide value for others.
