### ISSUE TITLE
dataPersistence.navigate() === bad practice?

### ISSUE THREAD

**Issue by philly-vanilly** [nrwl/nx#1889]
NX is all about architecture and most Angular architects decouple their redux stores so the outer world is a blackbox and communicates only over actions.

Considering that, isn't having a function which has a dependency to a route or component inside Effects a bad practice? This automatically leads to circular dependencies and strong coupling.

Some modules depend on other module's stores, so you can't always have a 1:1 relationship between a BusinessComponent and a specific store, ergo they should be decoupled.

What is NX team's take on this?

**Comment by vsavkin** [comment]
>  This automatically leads to circular dependencies and strong coupling.

Why does it lead to circular dependency? Your component shouldn't import anything from the effect.

Also, see the "Router is the source of truth" section here: https://blog.nrwl.io/using-ngrx-4-to-manage-state-in-angular-applications-64e7a1f84b7b

**Comment by philly-vanilly** [comment]
@vsavkin thank you for the answer and sorry for replying a bit late, I just started a new job.

My components don't import from the store. But they have a reference to the store module - not from the Effect directly, but a Facade, which is dispatching actions. I think this is a pretty loose dependency and not a problem. However, I think Effects should not have a reference to a specific component as in here: `navigation(TalksAndFiltersComponent`. This creates a circular dependency effect > component > facade > effect.

IMHO if you regard the router as the single source of truth, it should use Effects as a black box as well and dispatch navigation actions over a facade. The component itself which knows when it is being called from the router, is thus a better place to handle that router/navigation logic, no?

**Comment by vsavkin** [comment]
Sorry for the really late reply. 

I sort of agree that referencing a component from an effect can be seen is not pure, but the component there signifies the route because there is not easy way to reference a route.

The thing I find a bit odd is why anyone would have to reference effect. I'd imagine the facade referencing actions, not the effect. After all, you can't do anything with the effect class. You don't normally call methods on it etc.

**Comment by brandonroberts** [comment]
In these cases, you should separate your dependencies from the feature lib, and the state lib to break the circular dependency. Your separated state/effects shouldn't depend on feature imports.

**Comment by BickelLukas** [comment]
@brandonroberts I don't understand completely. I have the same problem for `dataPersistande.navigation` but also when opening dialogs from the store.

Managing the dialog lifetime in store is a pattern that we have adopted long before switching to NX but now have problems with.

It makes sense to manage the lifetime of dialogs in the effects because then I can keep the dialog open until the API call is finished and close it upon success. Same thing goes for showing an error dialog when something goes wrong.

**For Example**:
We have a root action called `undoAndShowError`. It is called everytime a server error occurs that is not handled otherwise. In the effect we dispatch an undo action and show the error dialog. For dialogs we use Angular Material.
```ts
    public showError$ = createEffect(
        () =>
            this.actions$.pipe(
                ofType(showError),
                tap(_ => {
                    this.dialog.open(ErrorPopupComponent, {
                        data: {
                            title: 'Common.ErrorOccured',
                            text: 'Common.ErrorOccuredMessage',
                        },
                    });
                })
            ),
        { dispatch: false }
    );
```

Because we need a reference to the `ErrorPopupComponent` in the effect we actually create a dependency on the UI library inside the data-access library. This is not allowed when enforcing module boundaries.

It gets even worse when handling the lifetime of an edit dialog because the the data-access library depends on the feature library creating a circular dependency.

Any ideas on how to achieve this without violating the module boundaries?

**Comment by BickelLukas** [comment]
Actually after stating the problem I found the solution myself. In case anybody else stumbles upon this here's my solution.

**The answer is dependency inversion:**
I declared an injection token. 
```ts
export const ERROR_DIALOG_TYPE = new InjectionToken<ComponentType<any>>('ErrorDialog Type');
```

I then inject this into the effects class and use it to open the dialog.
```ts
    constructor(
        private actions$: Actions,
        private dialog: MatDialog,
        @Inject(ERROR_DIALOG_TYPE) private errorDialogType: ComponentType<any>
    ) {}

    public showError$ = createEffect(
        () =>
            this.actions$.pipe(
                ofType(showError),
                tap(_ => {
                    this.dialog.open(this.errorDialogType, {
                        data: {
                            title: 'Common.ErrorOccured',
                            text: 'Common.ErrorOccuredMessage',
                        },
                    });
                })
            ),
        { dispatch: false }
    );
```


In the feature library I then provide the correct implementation type for the injection token:
```ts
    providers: [
        { provide: ERROR_DIALOG_TYPE, useValue: ErrorPopupComponent },
    ],
```

This way the data-access library doesn't case which dialog it opens. It simply manages the opening and closing but the feature library takes care of making sure that the correct UI gets displayed.

**Comment by fmalcher** [comment]
Even though it's an old issue, I'd like to bring up this topic again. I stumbled over the same problem and it seems there is a common misconception about how library dependencies should be structured.

**Please let me know if there is a better place to discuss this!** @brandonroberts @vsavkin

-----

![Screen Shot 2020-09-11 at 11 55 52](https://user-images.githubusercontent.com/1683147/92907626-c556f880-f425-11ea-803d-3fc0e0cacc9b.png)


Arrows show TS imports, directed to "where into" the import happens.

The `DataAccessLibModule` is part of a *data-access*  lib that contains all NgRx-related stuff. It includes the store (`StoreModule.forFeature()`) and the effects (`EffectsModule.forFeature()`).
To enable this NgRx feature slice, I need to import the lib module into my *feature* lib module:

```ts
import { DataAccessLibModule } from '@foobar/myapp/data-access-books'

@NgModule({
  // ...
  imports: [DataAccessLibModule, /* ... */]
})
export class FeatureLibModule {}
```

The component has to import selectors from the *data-access* lib in order to fetch data from the store.
Same applies to a facade, which has to be imported from the * data-access* lib as well.

```ts
import { selectBooks } from '@foobar/myapp/data-access-books';
import { BooksFacade } from '@foobar/myapp/data-access-books';
```

Now, when I use `navigation()` from `DataPersistence` and import the component into my effect, it creates a circular dep (as seen in the diagram).
The Nx docs state about library constraints:

> A data-access library can depend on data-access and util libraries.

Thus, importing a component (= a feature lib) in an Effect (= in an data-access lib) is not within the constraints.

**What am I missing or doing wrong? Thanks for your help! 🙂**

**Comment by HarryPi** [comment]
> Actually after stating the problem I found the solution myself. In case anybody else stumbles upon this here's my solution.
> 
> **The answer is dependency inversion:**
> I declared an injection token.
> 
> ```ts
> export const ERROR_DIALOG_TYPE = new InjectionToken<ComponentType<any>>('ErrorDialog Type');
> ```
> 
> I then inject this into the effects class and use it to open the dialog.
> 
> ```ts
>     constructor(
>         private actions$: Actions,
>         private dialog: MatDialog,
>         @Inject(ERROR_DIALOG_TYPE) private errorDialogType: ComponentType<any>
>     ) {}
> 
>     public showError$ = createEffect(
>         () =>
>             this.actions$.pipe(
>                 ofType(showError),
>                 tap(_ => {
>                     this.dialog.open(this.errorDialogType, {
>                         data: {
>                             title: 'Common.ErrorOccured',
>                             text: 'Common.ErrorOccuredMessage',
>                         },
>                     });
>                 })
>             ),
>         { dispatch: false }
>     );
> ```
> 
> In the feature library I then provide the correct implementation type for the injection token:
> 
> ```ts
>     providers: [
>         { provide: ERROR_DIALOG_TYPE, useValue: ErrorPopupComponent },
>     ],
> ```
> 
> This way the data-access library doesn't care which dialog it opens. It simply manages the opening and closing but the feature library takes care of making sure that the correct UI gets displayed.

Thanks for this an amazing idea and true to the SOLID principles

**Comment by omar-zahid** [comment]
@fmalcher Did you manage to find a workaround? You're absolutely right about the architecture here and I'm facing the same issue. Is it okay to ignore the circular dependency in production for the effects file? 
I tried @brandonroberts suggestion to separate the common dependencies but couldn't. Something is being dependent somewhere.
