### ISSUE TITLE
Show projects command documentation does not covers all use cases

### ISSUE THREAD

**Issue by reno** [nrwl/nx#18947]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/show

### Additional context or description

In nx version 15.9 I used the command `nx affected:apps` and `nx affected:libs` to list my apps and libs respectively. After updating to 16.7 these commands stopped working, so I got it to work with `nx print-affected --type=app`. But `print-affected` is also deprecated. Nx docs suggest using the `show projects` command instead, but it's not documented how to use it to list only apps or libs, or if this is even possible with the command.

**Comment by AgentEnder** [comment]
There is currently not a direct replacement to get the name of apps and libs independent of each other. Can I ask what the use case is? We've not seen these used for great use cases in the past, and the distinction is kind of arbitrary so we are not sure if it makes sense to continue supporting them.

**Comment by jorundoa** [comment]
We have the same problem. Our use case is wanting to spin up an entire cluster of all apps in our pipeline. Until now we've used
npx nx affected:apps --all --plain
The script we are using uses the app names in deployment commands, and attempting to use these commands with library names crashes the script.

**Comment by EcksDy** [comment]
I'm in the process of migrating from 14.1 to 16.8.

We have a similar situation where we are relying on the list of affected libs/apps, as they require different setups in our CI/CD.
  
For example we build our docker images for our apps using matrix jobs. Having the ability to differentiate between apps and libs, saves us from spinning up tens of machines just to fail - when they shouldn't have been span up in the first place. 

It would make sense to be able to get the following lists through the `nx show projects` cli:
- All projects ✅ 
- Affected projects ✅ 
- All apps ❌ 
- Affected apps ❌ 
- All libs ❌ 
- Affected libs ❌ 

The fact that the APIs to get these lists moved so much in an year, losing/changing it's capabilities every time, makes me think negatively on maturity of `nx` as a tool. If we couldn't use the already marked for deprecation `print-affected`, it would affect our setup too much to even bother trying. 

It puts us in a position where we're stuck between using outdated tools with no easily available documentation(I couldn't find any docs of previous versions), and changing our entire setup because of API changes that take away existing abilities.

**Comment by TomONeill** [comment]
@AgentEnder We're triggering a pipeline that (Azure DevOps) tags itself with the output of the affected command. Other pipelines trigger based on the tags of that pipeline. It couldn't hurt to tag itself with the affected libs too, although I am not sure if there's a limit to the amount of Azure DevOps tags. I'd rather have a worthy equivalent to something that existed before, or at least get informed on the details of why it was removed, what those "not great usecases" are what the right way to do things is instead.

Maybe a month later things have changed, but I have found that providing the `--help` flag to the `show` command does state an example to only get the apps:

```
> nx show projects --help
(...)
Examples:
  nx show projects --projects "apps/*"         Show all projects in the apps directory
```

This seems to be the equivalent of `--type=app`, however it does not work the same.
We work with deeper nested apps, so like `apps/layer1/app1`, though it only detects apps that are one layer deep, like `apps/app2`.

I was thinking, well if it's glob, we can use `**`, right? It does behave differently, but not quite as expected.
`nx show projects --projects "apps/**"` or `nx show projects --projects "apps/**/*"` both result in the same: it doesn't show the same projects from the previous command, nor does it show all app projects. It somehow chose to only output an e2e project: `apps/layer1/app1-e2e`. No `apps/layer1/app1`.

I'm really not sure why the behaviour is the way it is, but to me there's something off.
The alternative is to use `---withTarget=serve` but technically that isn't the same and it doesn't feel right using it, as things might change in the future and cause unexpected results.

Important part of `nx report`:
```
 Node   : 20.7.0
 OS     : win32-x64
 npm    : 10.1.0

 nx (global)        : 16.8.1
 nx                 : 16.8.1
```
