### ISSUE TITLE
[Question] Defining a breaking change for Nx

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#1921]
## Expected Behavior

To gain a better understanding on what constitutes a breaking change for the Nx team and what kind of checks and quality control we can expect as consumers of Nx.

## Current Behavior

This is in some ways a related to #1836 which was deemed by @jaysoo as a "won't do" given that Nx has no plans of reverting from babel-loader to ts-loader. Here's an extract of the response, just for reference in this issue:

> The main objective for moving to babel-loader is that babel is used in most non-Angular projects (React, Vue, etc.), so it makes sense to support the majority use case. This means we won't be moving back to ts-loader for the web builder.

The reasoning behind the change is understood—however, the underlying issue wasn't addressed: this was a breaking change. In other words, supporting "the majority use case" isn't the issue but rather that there was a change in which use cases are covered by Nx in a minor version bump, leaving our team as Nx consumers with broken applications (in some cases at build time and in others at runtime).

Your team is obviously free to support the use cases you feel are appropriate for your product. However, I'd love to get a better understanding as to what constitutes a breaking change to your team to effectively either re-align our expectations as consumers of Nx or pivot in a different direction that better aligns with our understanding of semver.

### Context

For any applicable context not described within this issue, see #1836.

**Comment by jaysoo** [comment]
> clarity into your breaking change policy

The minor version changes are not supposed to introduce breaking changes. The web builder regressions should not have happened, so again sorry for that.

> keep maintaining a custom webpack config that works or simply to pivot by maintaining our own builder

We want to be at the point where custom webpack isn't needed for the majority of projects -- which was the reason for the babel-loader change. The fact that it is needed as a regression workaround points to possible bug(s) that we need to fix.

If you do need to use `ts-loader` then a separate builder would be needed, especially since `differentialLoading` support will need different implementations.

> especially considering the current builder relies on Angular's webpack config fairly heavily

We have plans soon to remove the reliance on Angular's webpack config. It was never intended as a long term solution.

Hope that clears up some points for you. I hope we can work through any remaining issues you are still facing so the web builder will work without custom webpack config.

**Comment by vsavkin** [comment]
Defining what constitutes a breaking change isn't easy for integrated tools like Nx.

There are two extremes:

* For a runtime library, you have a well-defined interface and then you can make assertions against. This, of course, doesn't guarantee that a code change won't break anyone. Any code change can break someone somewhere, even if it is a small bug fix. After all, someone could reply on the existence of the bug. I.e., it's about probabilities and not guarantees.
* For a IDE or an editor, you cannot meaningfully define "a breaking change" because the interface is graphical and it's hard to formally define it. That's why, for instance, VSCode and Intellij don't use semantic versioning.

Nx sits someone in between. These are the guidelines we use:

* Nx Commands (e.g., affected). We are in full control of this, so we are trying to make sure that absolutely no-one is broken. This doesn't always works. For instance, changing the command output to use colors broke some folks because they parsed the command outputs in CI. We added a flag to help with this.

* Schematics. It's hard to define the interface of a schematic. When it comes to inputs, we are trying to treat them like an interface. We don't remove flags or introduce new mandatory flags in minor releases. The outputs, the generated code, can be used in many different ways, it's hard to make any formal assertions about it. So we are simply trying to do our best and not change the generated code drastically in a non-major release.

* Builders. when it comes to inputs, we are trying to treat them like an interface. Builders often delegate to external tools, and not all of them use semantic versioning. So we cannot guarantee that a minor update won't break you, but we do our best. 

* Runtime Components. It's a runtime library, so we treat it as such.

Until very recently we mainly focused on non-breaking Angular projects and Angular users. This allowed us to experiment and implement React, Node and Web support in a short amount of time. It changed. More people are using React and Node, so we've started to put the same amount of care into non-breaking folks.

The vast majority of non-Angular developer don't want to use `ts-loader`, so we made a decision that maintaining two options is too costly. 

I want to apologize for landing this change in a minor release. It should have been a major release.

Any particular issues you are experiencing with the babel-loader? We can fix those.
