### ISSUE TITLE
nx/jest reporters is only allowed to be string[]

### ISSUE THREAD

**Issue by BigForNothing** [nrwl/nx#19240]
### Current Behavior

Currently in `project.json`, the `nx/jest:jest` executor requires reporters to only be a `string[]`. However, it is [allowed](https://jestjs.io/docs/configuration#reporters-arraymodulename--modulename-options) to pass in an tuple. 

* As jest's configuration specifies `[array<moduleName | [moduleName, options]>]`,
* Or as `@jest/types` handles it
```
  export type ReporterConfig = [string, Record<string, unknown>];
  reporters: Array<string | ReporterConfig>;
```
This is useful for configuring [jest-junit](https://www.npmjs.com/package/jest-junit).
export type ReporterConfig = [string, Record<string, unknown>];

### Expected Behavior

I should be able to pass in an array that matches the same type as jest

### Steps to Reproduce

1. create a new library with jest
2. Attempt to configure a reporter like jest-junit
```
reporters: [
    "default",
    [ "jest-junit", { suiteName: "jest tests" } ]
  ]
```

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Providing reporter options is only allowed in the Jest configuration (the link you provided). Providing reporter options via the CLI is not supported:  https://jestjs.io/docs/cli#--reporters.

The `reporters` option in the `@nx/jest:jest` executor is provided as an option to the Jest CLI when invoking it. Therefore, it only allows a `string[]` because that's what the Jest CLI supports. If you need to provide options for a reporter, please do so in the jest configuration file.
