### ISSUE TITLE
nx/dep check dependency not retrieving the current version of lib when fixing deps

### ISSUE THREAD

**Issue by vsamofal** [nrwl/nx#19340]
### Current Behavior

@nx-dependency-check is not populating the current version on libraries withing the current workspace, and setting * instead of version 

### Expected Behavior

It should set the current version from package.json for libs within a workspace 

### Steps to Reproduce

create multiple publishable/buildable libs where the first depends on the second
configure nx-dep check rule
run lint, see that nx rule setting * as a version in the package.json in the second lib instead of the actual version  

### Nx Report

```shell
Node   : 20.5.1
   OS     : darwin-arm64
   yarn   : 3.6.3
   
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/nest           : 16.8.1
   @nx/node           : 16.8.1
   @nx/plugin         : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.1.0
   ngx-deploy-npm    : 7.0.1
   ---------------------------------------
   Local workspace plugins:
         @softkit/resource-plugin
```

### Package Manager Version

yarn 3.6.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

[A bit more details](https://dev.to/vsamofal/comment/297nf)

**Comment by meeroslav** [comment]
This is by design. If the rule would set the version in your second package, the next time you change the version in the first package, it would be a linting error in the second (since the version would no longer be `*`).

Additionally, it's suggested to use version ranges and not fixed versions for publishable libraries and tool cannot know which range you support.

If having synchronized versions is what you want (similarly to how we do it in the Nx repo) the suggested way is to have a post-build step that sets the version in the `package.json` in the `dist` folder based on your requirements.

**Comment by vsamofal** [comment]
@meeroslav makes sense, thank you. 

I think it will be good to update docs, at least with these notes
