### ISSUE TITLE
nx and vue

### ISSUE THREAD

**Issue by davidmoshal** [nrwl/nx#19375]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/showcase/example-repos/add-vue

### Additional context or description

Trying to create a vue app per the docs at the link above.

1) first bug:
```sh
create-nx-workspace@latest acme ...
```

Should be:
`npx create-nx-workspace@latest acme ...`

2) Second bug:
```sh
npm install --save-dev @nx/vite @nx/js vue vue-tsc vitest vite-tsconfig-paths vite-plugin-dts vite @vitejs/plugin-vue @vitejs/plugin-vue-jsx
```

results in this error:
```sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vitejs%2fplugin-vue-js - Not found
npm ERR! 404
npm ERR! 404  '@vitejs/plugin-vue-js@*' is not in this registry.
npm ERR! 404
```

It would be nice to see VueJs receive first class treatment in NX, have been struggling with NX and Vue for many years now!

**Comment by mandarini** [comment]
Hi there @davidmoshal ! It seems that the `@vitejs/plugin-vue-js` typo has already been fixed, since now the command says `@vitejs/plugin-vue-jsx`, which is the actual plugin that does exist!

However, we just published the [`@nx/vue` plugin](https://nx.dev/nx-api/vue), so you can use that to generate your applications! :)

I will be closing this issue now, but please let me know if there's anything else we can help with!

Again, thanks for pointing this out!
