### ISSUE TITLE
rendering of dep-graph broken

### ISSUE THREAD

**Issue by stefan-karlsson** [nrwl/nx#1938]
## Expected Behavior

Render full dependency graph

## Current Behavior

The whole dependency graph is not rendered, only parts of it.
![image](https://user-images.githubusercontent.com/25538602/66604577-b5e48500-ebae-11e9-8235-b37554cee15a.png)

## Failure Information (for bugs)

This started to occur when updating nx workspace from v8.5.1 to v8.6.0

### Failure Logs

There is no console errors reported by browser (Chrome)

**Comment by johannesnormannjensen** [comment]
I am experiencing the same

**Comment by tashoecraft** [comment]
Seems to be an issue with the css and transform properties applied on the element. If you do some minimal modifying of the html it'll start rendering fine. Haven't dug into the source for where it's determining those property values yet though

**Comment by tashoecraft** [comment]
The issue is that width doesn't appear to be updated when the graph gets built, so the default svg width of 1024 gets used. I'll have a pr up shortly which updates the width after the graph is rendered and moves when the center offset is calculated to below the height and width calculation so that it is centering based on full graph data.
