### ISSUE TITLE
lint for 50 angular packages takes 12+ mins

### ISSUE THREAD

**Issue by govindappaarun** [nrwl/nx#19459]
### Current Behavior

We have nx linting for 50+ packages monorepo of an angular based application 
As reported earlier in this ticket https://github.com/nrwl/nx/issues/18297  its taking 10-15 mins which was taking just 4+ mins earlier to Nx migration

Linter executor we have used @nx/linter:eslint as well, no improvements observed

### Expected Behavior

Lint should pass faster and not to take more than 5mins

### Steps to Reproduce

1.

### Nx Report

```shell
> nx report


 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : linux-x64
   npm    : 9.6.7
   
   nx             : 16.9.1
   @nx/js         : 16.9.1
   @nx/jest       : 16.9.1
   @nx/linter     : 16.9.1
   @nx/workspace  : 16.9.1
   @nx/angular    : 16.9.1
   @nx/cypress    : 16.9.1
   @nx/devkit     : 16.9.1
   @nrwl/tao      : 16.9.1
   @nx/webpack    : 16.9.1
   typescript     : 4.9.5
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
In order to understand what is slowing down your linter can you run your lint command with `TIMING=20`?

```
TIMING=20 npx nx run-many --target=lint --skip-nx-cache
```

This would provide information on where the slowdown is coming from. It's unlikely that the executor is the bottleneck.

**Comment by govindappaarun** [comment]
When I ran with TIMING, Here is what I could see, where for each project the rule @typescript-eslint/naming-convention  is taking 25 to 30% of the time for all the modules. 
@typescript-eslint/naming-convention     |   164.005 |    28.7%
@typescript-eslint/no-floating-promises  |    80.397 |    14.1%
@typescript-eslint/prefer-readonly       |    58.654 |    10.3%
max-len                                  |    22.313 |     3.9%
@typescript-eslint/no-empty-function     |    15.425 |     2.7%
comma-dangle                             |    15.424 |     2.7%
no-unexpected-multiline                  |    15.135 |     2.7%
@ecocode/no-multiple-access-dom-element  |    12.442 |     2.2%
brace-style                              |    12.049 |     2.1%
no-prototype-builtins                    |    11.094 |     1.9%
no-global-assign                         |    10.209 |     1.8%
@typescript-eslint/member-ordering       |    10.130 |     1.8%
@typescript-eslint/no-loss-of-precision  |     9.424 |     1.7%
no-regex-spaces                          |     6.737 |     1.2%
no-misleading-character-class            |     5.871 |     1.0%
@typescript-eslint/no-unused-vars        |     5.569 |     1.0%
no-useless-escape                        |     5.378 |     0.9%
@typescript-eslint/ban-types             |     5.082 |     0.9%
@typescript-eslint/quotes                |     5.058 |     0.9%
@typescript-eslint/no-unused-expressions |     5.030 |     0.9%

Anything else you want me to provide from the report, May I know what do you infer from this report?

**Comment by govindappaarun** [comment]
@meeroslav May I know how to understand this report, anything that you can infer from.

**Comment by meeroslav** [comment]
Hi, sorry for the delay.

This report clearly shows us that you have three rules that take almost 50% of the linter run duration:
- @typescript-eslint/naming-convention
- @typescript-eslint/no-floating-promises
- @typescript-eslint/prefer-readonly

I suggest you check if these are absolutely needed, and if not, kick them out.

Usually `@nx/enforce-module-boundaries` is among the top three rules, since it has a fairly complex rule and is expected to be slower than most of the rules. I don't see it here on your list, which either means you don't have it on, or there are 20 slower rules.

Additionally, when comparing `before` and `after`, it's essential to compare the same configurations. We often see that people are comparing linter runs that lint just `.ts` files with linter run that lints both `.ts` and `.html` (which is the default case when using `Angular` with `nx` linter). 

We can investigate the performance if you can provide access to your repo or create a showcase repo where this is visible. Otherwise, the linter executor is just a shallow wrapper around `ESLint` CLI so there's nothing there that could be causing this slowdown.

**Comment by meeroslav** [comment]
Closing as stale
