### ISSUE TITLE
Document issue

### ISSUE THREAD

**Issue by Blithe07** [nrwl/nx#19494]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/node-server-tutorial/2-project-graph

### Additional context or description

In the code block, `success` field should be of boolean type instead of boolean value.

```
export type AuthResponse = AuthSuccessResponse | AuthFailureResponse;
export interface AuthSuccessResponse {
  success: true; // boolean
  name: string;
}
export interface AuthFailureResponse {
  success: false; // boolean
}

export function doAuth(): AuthResponse {
  return { success: true, name: 'Cheddar' };
}
```

**Comment by AgentEnder** [comment]
This looks correct to me - the type of success in each interface is `true` or `false` respectively, and that allows typescript to narrow the response type based on if the success property is true or false. In this example, the `name` field in the `doAuth` function is required because success being true means it is an AuthSuccessResponse.

Read more here: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions
