### ISSUE TITLE
Bug 688 is still not fixed. ng g m html-lib --routing does not create routing ts file

### ISSUE THREAD

**Issue by brianreinhold** [nrwl/nx#19499]
### Current Behavior

running command ng g m html-lib --routing

creates module ts file in the directory html-lib but there is no routing.ts file

### Expected Behavior

The routing.ts file is also created

### Steps to Reproduce

1. In any Angular project run ng g m html-lib --routing

there will be a new module directory and a module ts file in that directory but no routing ts file.

### Nx Report

```shell
The nx report did not work as it appears not to exist.
```

### Failure Logs

```shell
There are no failure logs. Angular appears to think everything ran just fine.
```

### Package Manager Version

npm 18, Angular 16

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
#688 doesn't seem to relate to this, can you clarify?

**Comment by brianreinhold** [comment]
If I could figure out how to find that bug again I would. But it was exactly the same issue verbatim that I have raised. However, that bug got closed due to inactivity. There was no remark about resolution.

IN any case, the bug is simple . Invoke ng g m html-lib --routing and no routing ts file is created.

**Comment by Coly010** [comment]
Hey @brianreinhold An Nx Report would help: `npx nx report` at the root of your workspace should provide one.

The Angular plugin for Nx also does not have a `module` generator, so this _should_ be invoking Angular's schematic.

If you run `npx nx g module html-lib --routing`, do you get different behaviour? Because `ng` would indicate you're using the Angular CLI and not Nx CLI. We have stopped decorating the `ng` command for some time now, so it doesn't pass through Nx first.
