### ISSUE TITLE
NX does not generate the project-graph in {{workspaceRoot}}/.nx

### ISSUE THREAD

**Issue by vincentB-lemon** [nrwl/nx#19648]
### Current Behavior

I recently upgraded from v15 to v16 of NX. Right now I'm running v16.10.0 but our monorepo and pipelines got broken. I first encountered the issue in our CICD (linux), but have also succeeded in replicating it locally (Mac).

With the `cacheDirectory` option in the `nx.json` file set to the default ".nx", whenever I run an nx command (like nx test), I receive the following error message:
<img width="1005" alt="image" src="https://github.com/nrwl/nx/assets/73707483/f24550e4-a987-43e5-8fc8-70da7816657e">

After running nx reset, the project-graph is saved in `node_modules/.cache/nx`, but there is no `.nx` folder in the root of the project. If I then run nx test, the command fails. Information about the latest run is stored in the root `.nx` folder, but still no sign of the project-graph.

If I change the `cacheDirectory` option to `node_modules/.cache/nx`, the nx test command works. However, I don't like this "fix", as I would think that I should also be able to use the default `.nx` folder like it was previously...

So, even though I had kind of a fix, I investigated a little further and started playing with the `useDaemonProcess` option for the TaskRunner inside `nx.json`. When I set the `useDaemonProcess` to false and the `cacheDir` to `.nx`, the following happened:
1. First an nx reset => No project-graph in either `.nx/cache` or `node_modules/.cache/nx`
2. Then a first time nx test => ONLY project-graph in `node_modules/.cache/nx`, NOT in `.nx/cache`.
3. Then a second time nx test => project-graph was visible in BOTH folders, and tests succeeded.

This process is repeatable again and again.

So, at least with useDaemonProcess set to false, I managed to get the project-graph in the normal `.nx/cache folder`, but only at the second attempt of nx test. So for CI/CD purposes, this was useless.

=> In the end it seems to me there is something off within the daemon process building the project-graph inside `.nx/cache`. In the meantime I can use the cache inside node_modules, but I was hoping someone could give me more input here or perhaps you recognize the issue. 

### Expected Behavior

I would expect to see nx generate the project-graph when I run an nx command like nx test.

### Steps to Reproduce

Not sure if it can be replicated in a clean monorepo. I will test this ASAP

### Nx Report

```shell
Node   : 16.20.1
   OS     : darwin-arm64
   yarn   : 3.2.0
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/express        : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @ngrx/effects                    : 16.0.1
   @ngrx/store                      : 16.0.1
   @storybook/angular               : 6.5.16
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
We didn't move the default directory to `.nx/cache` until the upcoming v17 release. Otherwise, it is only the default if the .nx directory already exists.

It is possible that the daemon may need to be reloaded when changing things like the cache directory, and specifically there are weird runtime issues that can arise with the daemon and the existence of the `.nx` directory. A lot of the funkiness there should be fixed in the latest v17 betas that have the new default directory.

To help explain the behavior that you are reporting, its worth noting that there are 2 logical cache directories that Nx uses. One holds cache artifacts, and is what is controlled with the cacheDirectory option. The other is sort of a local temp storage for Nx itself. The artifacts within it (project graph cache being an example), don't really make sense for a user to move the position. It **_always_** uses the default location, and isn't controllable via the nx.json changes.

With this in mind, lets look at your repro steps:

1. First an nx reset => No project-graph in either .nx/cache or node_modules/.cache/nx 

> Nx reset clears both cache directories. The cache artifact directory, and Nx's tmp storage.

2. Then a first time nx test => ONLY project-graph in node_modules/.cache/nx, NOT in .nx/cache.

> No .nx/cache directory, so the default cache directory is `node_modules/.cache/nx`. Nx JSON says to use `.nx/cache`
> - Cache artifacts go to user spec'd location @ .nx/cache
> - Project graph goes to default location @ node_modules/.cache/nx

3. Then a second time nx test => project-graph was visible in BOTH folders, and tests succeeded.

> .nx/cache exists, so the default cache directory is `.nx/cache`. Nx JSON says to use `.nx/cache`
> - Cache artifacts go to user spec'd location @ .nx/cache
> - Project graph goes to default location @ .nx/cache

I hope this explains the behavior you are seeing, and clears up some of the confusion. Again, this will be changing in v17 to be a bit clearer.

That said, you shouldn't rely on the location or existence of the project graph cache, file map cache or similar files which Nx stores in the tmp storage. That's not a public API, and could change either position or data format at any time, just to advise some extra caution.

**Comment by wespickett-cb** [comment]
@AgentEnder This should not be closed. 

The daemon process is creating the project-graph.json at `node_modules/.cache/nx/project-graph.json`
here: https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/project-graph.ts#L156

And then some other nx code is looking for the `project-graph.json` at `<cacheDirectory>/project-graph.json`, which is `.nx/cache/project-graph.json` since  I have `"cacheDirectory": "./.nx/cache` in `nx.json`
here: https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/nx-deps-cache.ts#L90

And that results in the error described by [vincentB-lemon](https://github.com/vincentB-lemon) being thrown every time I try to run an nx command
here:  https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/project-graph.ts#L34

So the daemon is writing to the node_modules cache, but the nx code expects the project-graph.json to be at `<cacheDirectory>/project-graph.json`, so something is not lining up, and this should not have been closed

**Comment by wespickett** [comment]
@AgentEnder This should not be closed. 

The daemon process is creating the project-graph.json at `node_modules/.cache/nx/project-graph.json`
here: https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/project-graph.ts#L156

And then some other nx code is looking for the `project-graph.json` at `<cacheDirectory>/project-graph.json`, which is `.nx/cache/project-graph.json` since  I have `"cacheDirectory": "./.nx/cache` in `nx.json`
here: https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/nx-deps-cache.ts#L90

And that results in the error described by [vincentB-lemon](https://github.com/vincentB-lemon) being thrown every time I try to run an nx command
here:  https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/project-graph.ts#L34

So the daemon is writing to the node_modules cache, but the nx code expects the project-graph.json to be at `<cacheDirectory>/project-graph.json`, so something is not lining up, and this should not have been closed

**Comment by AgentEnder** [comment]
Can you try on the v17 betas? This should be fixed there and is the reason for closing the issue.
