### ISSUE TITLE
nx migrate fails - .bin/nx: not found

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19899]
### Current Behavior

I have 2 separate NX monorepos. In one, I've managed to execute the `nx migrate latest` without any issue (and so did my colleague), however, in the other, I can use the `nx` commands, e.g `nx serve...`, but I cannot run the migrate script.

When I run `nx --version`, it shows:
```ts
Nx Version:
- Local: v16.10.0
- Global: Not found
```

I am using Volta for managing nodejs.

### Expected Behavior

The migrate should recognize the `nx`  command.

### Steps to Reproduce

I am not sure what causes this, so I cannot reproduce it.

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.4
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/vite           : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
nx migrate latest           
/bin/sh: 1: /tmp/tmp-68810-2OwFrgKzD8Mg/node_modules/.bin/nx: not found
Command failed: /tmp/tmp-68810-2OwFrgKzD8Mg/node_modules/.bin/nx _migrate latest

These paths get generated, and they contain the `package.json` and `yarn.lock` files.

package.json content
{
  "dependencies": {
    "nx": "latest"
  },
  "license": "MIT"
}

```

### Package Manager Version

yarn: 3.6.4

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by christianengineer** [comment]
The error message `/bin/sh: 1: /tmp/tmp-68810-2OwFrgKzD8Mg/node_modules/.bin/nx: not found` indicates that the shell (`/bin/sh`) attempted to execute the Nx CLI tool located at `/tmp/tmp-68810-2OwFrgKzD8Mg/node_modules/.bin/nx` but could not find it. This error typically arises due to one or more of the following reasons:

### Possible Causes

1. **Installation Issues**: Nx may not be properly installed in the specified directory. This could be due to a failed `npm install` or `yarn install` operation.

2. **Incorrect Path**: The path specified might be incorrect, either due to a misconfiguration or because the process that's trying to run Nx is doing so in the wrong context or directory.

3. **Environment Variables**: If the path relies on environment variables, those might not be set correctly, leading to a wrong absolute path.

4. **Temporary Directory**: The use of a `/tmp` directory suggests this might be part of a temporary operation or part of a CI/CD process. Make sure that the Nx installation is carried out correctly within this temporary environment.

5. **Permission Issues**: In some cases, although less likely given the "not found" message, there could be permission issues preventing the script from accessing the specified path.

### Debugging Steps

1. **Check Installation**: Run `ls /tmp/tmp-68810-2OwFrgKzD8Mg/node_modules/.bin/` to verify if `nx` is actually present in the directory.

2. **Reinstall Nx**: Try running `npm install` or `yarn install` again to ensure that Nx and all other dependencies are properly installed.

3. **Verify Environment**: If this is part of a CI/CD pipeline, make sure that the environment in which the script is running has access to all the required dependencies and paths.

4. **Check Scripts and Configuration**: Review any scripts or configuration files that might be setting the path to make sure they are correct.

5. **Check Permissions**: Use `ls -l` and `whoami` to ensure that the user running the script has the necessary permissions to access the path and execute the binary.

**Comment by nemonemi** [comment]
As I've stated, previously, I'm using Volta to install my nodejs and global dependencies on my local machine.

I am trying to run `nx migrate latest`, and that fails, while all the rest of the nx commands pass with flying colors, e.g. `nx serve ..., nx lint...` etc.

The `tmp_....` folder, where nx is not being searched at, is being generated with each `nx migrate` run. Why? There is a global instance of NX installed at `~/user/.volta/bin/nx`.
I've used it recently to migrate one of the projects to version 17.0.2, but it doesn't work for this other project.

**Comment by lucastanger** [comment]
Having the exact same issue, also running node using `volta`. Any idea how to solve this temporarily?

**Comment by nemonemi** [comment]
So sad that there hasn't been any movement here :(

**Comment by nemonemi** [comment]
The minor release of what, volta?

**Comment by unrealsolver** [comment]
Try updating Nx with `yarn up nx` or whatever other equivalent of this. It worked for me.

**Comment by leosvelperez** [comment]
This issue has been addressed in recent versions of Nx. If you're seeing this thread because you're facing this issue, see https://github.com/nrwl/nx/issues/16338#issuecomment-1923471782 for more context and a workaround.

Another workaround is to set the `NX_MIGRATE_USE_LOCAL` env var when running the `migrate` command. For example:

```bash
NX_MIGRATE_USE_LOCAL=true nx migrate latest
NX_MIGRATE_USE_LOCAL=true nx migrate --run-migrations
```
