### ISSUE TITLE
Nx 17 no longer respecting project name changes from a Project Graph plugin

### ISSUE THREAD

**Issue by ethanjdiamond** [nrwl/nx#19906]
### Current Behavior

I'm currently using a Project Graph plugin to change the name of my projects, but nx is not picking up the name changes.

As background, my monorepo is fully npm based and I'm only using the package.json files to define my nx project configurations. In order to prevent package name collisions with third party packages, I'm prefixing all my package.json names with `@workspace/`. However, I'd like to have the names of my projects omit the `@workspace/` since it's redundant, so I wrote a Project Graph plugin that does a `.replace('@workspace/', '')` on the name and writes it back into the configuration.

In the CreateNodesFunction, I've tried both returning the projects field with a mapping of `{ UNMODIFIED_PROJECT_NAME => PROJECT_CONFIGURATION_WITH_MODIFIED_NAME }` and a mapping of `{ MODIFIED_PROJECT_NAME => PROJECT_CONFIGURATION_WITH_MODIFIED_NAME }`, and neither of them have an affect on what Nx views as the project names.

I do know that the plugin is being used by Nx and that it's running properly because there are other changes I'm making to the ProjectConfiguration that are successful.

This was working in Nx 16, so I believe this regression was introduced in Nx 17. It was using `{ UNMODIFIED_PROJECT_NAME => PROJECT_CONFIGURATION_WITH_MODIFIED_NAME }`.

### Expected Behavior

I would expect the name of projects to be pulled from the `name` field of the modified ProjectConfiguration returned by the CreateNodesFunction.

### Steps to Reproduce

1. Write an Nx plugin that modifies the `name` of the ProjectConfigurations it finds
2. Observe that it doesn't pick up the name change when you do nx graph etc

### Nx Report

```shell
Node   : 18.18.2
   OS     : linux-arm64
   pnpm   : 8.9.2
   
   nx (global)        : 17.0.1
   nx                 : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/plugin         : 17.0.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @workspace/generators   : 1.0.0
   @workspace/linters      : 1.0.0
   @workspace/task-runners : 1.0.0
   ---------------------------------------
   Local workspace plugins:
         @workspace/task-runners
         @workspace/generators
         @workspace/linters
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Information merged by project configurations is done by the order of the plugin in `nxjson.plugins`. The part that most people won't see is that there are 2 plugins implicitly defined at the end of the array. When we load plugins, we append a plugin to parse package.json files and project.json files. Doing it in this order means that the name from project.json or package.json will overwrite any name specified by plugins.

This can feel clunky and behave differently from the v1 apis, but it's intentional. To rename a project to be unique, you need to do so in either package.json directly (which isn't feasible if you are publishing the package under a different name), or project.json. If `project.json` doesn't exist, you can create one that's just `{ "name": "@workspace/myproj"}`. This is the recommended way of doing the task described.

To reduce the effort involved with keeping this up to date, you could create a generator inside of a local plugin to keep this synced up. It would look something like below:

```typescript
import { Tree, glob, readJson, writeJson, joinPathFragments } from '@nx/devkit';
import {dirname} from 'node:path/posix';

export default function generator(tree: Tree) {

	const packageJsons = glob(tree, ['packages/**/package.json']);
    for (const packageJsonPath of packageJsons) {
        const { name } = readJson(tree, packageJsonPath);
        writeJson(tree, joinPathFragments(dirname(packageJsonPath), 'project.json', {
          name: `@workspace/${name}`
        })
    }

}
```

**Comment by ethanjdiamond** [comment]
`This can feel clunky and behave differently from the v1 apis, but it's intentional`

@AgentEnder it makes sense if there's a good reason to take away user control by running the implicit plugins after the user defined plugins. What do the plugins do that it makes sense to put them after the user's plugins?
