### ISSUE TITLE
nx migrate isn't working with Angular 17

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#19916]
### Current Behavior

```
nx migrate @angular/cli@next

...

There are no migrations to run, so migrations.json has not been created.
```

### Expected Behavior

from a new Angular 16 project
```
ng update @angular/cli --next

** Executing migrations of package '@angular/cli' **

Angular v17 introduces a new control flow syntax that uses the @ and } characters.
  This migration replaces the existing usages with their corresponding HTML entities.
  Migration completed (No changes made).

Updates `TransferState`, `makeStateKey`, `StateKey` imports from `@angular/platform-browser` to `@angular/core`.
  Migration completed (No changes made).

CompilerOption.useJit and CompilerOption.missingTranslation are unused under Ivy.
  This migration removes their usage
  Migration completed (No changes made).
```

### Steps to Reproduce

1. generate a new nx project using latest angular version (16)
2. run `nx migrate @angular/cli@next`

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32-x64
   pnpm   : 8.6.0

   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/angular        : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/nest           : 17.0.2
   @nx/node           : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.2.0
   @nguniversal/express-engine : 16.2.0
   ng-mocks                    : 14.11.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

trying to run `ng update @angular/cli --next` in nx project throw an error 

> Error: This command is not available when running the Angular CLI outside a workspace.

**Comment by AhsanAyaz** [comment]
Just to clarify @robertIsaac , is the intention for this ticket to work with the RC? Or stable Angular v17 when it goes out?
TBH, I'm interested in both 🙂

**Comment by robertIsaac** [comment]
> Just to clarify @robertIsaac , is the intention for this ticket to work with the RC? Or stable Angular v17 when it goes out? TBH, I'm interested in both 🙂

well I hope it's the same root cause and be fixed together
but if not, let's focus on the stable v17, which is being released next week (Nov 6)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The Angular CLI migrations have a target version of 17.0.0, which is the stable version. Therefore, the `nx migrate` command doesn't pick up the migrations because the 17.0.0-rc.2 is lower than the target version. The `ng update` command seems to normalize the installed version by removing the prerelease identifier. That's why that command matches the migrations versions and collects them to run.

That said, there are two things to consider here:

- Once Angular v17 becomes stable, the migration will work as expected.
- Angular is not meant to be updated in Nx workspaces by "only" updating the Angular CLI (and related Angular packages). The `@nx/angular` package needs to support the version of Angular you're migrating to. So, updating Angular to the next version without updating the `@nx/angular` package to a version that supports that version of Angular will lead to issues. More so when you're updating to a new major Angular version, which would contain more significant changes with a higher likelihood of breaking changes.

We're already working on adding support for the Angular v17 update, and we aim to release it as soon as possible after the Angular team releases. When we release the support, the recommended way to update your Angular version is to update Nx to the version that supports it (`nx migrate latest`).

**Comment by robertIsaac** [comment]
But didn't nx decoupled nx from angular so that developers can upgrade their angular version freely?
Also this is a problem that I have no way to test beta/rc releases if Angular if I'm using nx
Nx should be upgrade to Angular cli, now this is a big limitation

**Comment by leosvelperez** [comment]
Developers have more control over the Angular version as long as Nx supports it. This is explained in our docs: https://nx.dev/concepts/more-concepts/nx-and-angular#ng-update-vs-nx-migrate. Being decoupled from the Angular version doesn't mean all versions are supported automatically. A ton of work still needs to be done to support every Angular version. More so, given the latest versions of Nx support multiple versions of Angular, which is not something the Angular CLI supports. While that's great, it comes with added complexity.

Nx is a different CLI, offering support for Angular through its `@nx/angular` plugin. As with any plugin or tool that provides support for a framework, it needs to explicitly support the versions of that framework.

Angular is a big framework with complexities regarding tooling (custom compiler, custom CLI, etc). Every major release of Angular (and sometimes even minor releases) comes with many changes for tooling developers. The `@nx/angular` plugin has to be updated to support those changes. Also note that with Nx, there's a range of tools that can be used in Angular workspaces that also need to be tested and updated to support every new version of Angular (Jest, Angular ESLint, NgRx, Storybook, etc). While we would love to have support for every prerelease version of Angular that comes out, it's not something feasible.

**Comment by robertIsaac** [comment]
> Developers have more control over the Angular version as long as Nx supports it. This is explained in our docs: https://nx.dev/concepts/more-concepts/nx-and-angular#ng-update-vs-nx-migrate. Being decoupled from the Angular version doesn't mean all versions are supported automatically. A ton of work still needs to be done to support every Angular version. More so, given the latest versions of Nx support multiple versions of Angular, which is not something the Angular CLI supports. While that's great, it comes with added complexity.
> 
> Nx is a different CLI, offering support for Angular through its `@nx/angular` plugin. As with any plugin or tool that provides support for a framework, it needs to explicitly support the versions of that framework.
> 
> Angular is a big framework with complexities regarding tooling (custom compiler, custom CLI, etc). Every major release of Angular (and sometimes even minor releases) comes with many changes for tooling developers. The `@nx/angular` plugin has to be updated to support those changes. Also note that with Nx, there's a range of tools that can be used in Angular workspaces that also need to be tested and updated to support every new version of Angular (Jest, Angular ESLint, NgRx, Storybook, etc). While we would love to have support for every prerelease version of Angular that comes out, it's not something feasible.

I want to ask a simple question that might sound stupid
why when running angular cli commands you don't just make a virtual angular.json file and make angular cli uses it, that way all angular commands should be working

**Comment by ovitrif** [comment]
This is quite a blocker, not sure I'll end up using `nx` given this…

**Comment by BenRacicot** [comment]
I'm surprised to see this one closed. 
Since we don't use the Angular CLI within Nx is there general guidance on Angular's automated migration tools?

For instance, all Nx users will have to manually update all view templates which include any `@`, `{` or `}` for control-flow syntax?

This is particularly confusing because Nx's major version matches with Nx V17.x.

**Comment by robertIsaac** [comment]
> I'm surprised to see this one closed. BTW The Angular team knows about this [1806375921](https://github.com/angular/angular/issues/52787#issuecomment-1806375921)
> 
> Since we don't use the Angular CLI within Nx is there general guidance on Angular's automated migration tools?
> 
> For instance, all Nx users will have to manually update all view templates which include any `@`, `{` or `}` for control-flow syntax?
> 
> This is particularly confusing because Nx's major version matches with V17.x.

Nx copy the Angular migration into theirs
But it doesn't always work 
See
https://github.com/nrwl/nx/issues/20162
