### ISSUE TITLE
Don't invalidate lint cache for dependent libraries, unless NX lint tags rules have changed

### ISSUE THREAD

**Issue by adrdilauro** [nrwl/nx#19988]
I am reopening https://github.com/nrwl/nx/issues/19580 as a feature request.

The reason why this would be very useful is that 

1. Linting is typically much slower than running test
2. It should be simple for NX to detect whether the changes of a library involve the lint tag rules or not. In 99% of cases they don't, yet we need to re-run lint for hundreds of libraries that could be easily cached

I see you guys improved a lot of details in the caching algorithm: the cache is smarter than in the past, and very useful to use. But this one unfortunately is a regression, because it didn't use to do it in the past.

### Current Behavior

Let's say I have `lib1` that depends on `lib2`, and their lint tasks are already cached. If I change one file in `lib2`, the cache of `lib1` gets invalidated too. This did not happen in version 13.

### Expected Feature

Changing a library should not invalidate the lint cache of libraries where it's imported. It should invalidate only the test cache, not the lint one

### Steps to Reproduce

1. Run the lint on all libraries, so that the result gets cached
4. Change a library that is used in another library
5. Run the lint again: now the lint cache has been invalidate not only in the library that you modified, but also in all the libraries where it's used

### Nx Report

```shell
Node   : 16.14.2
   OS     : linux-x64
   npm    : 8.5.0
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/express        : 16.10.0
   @nx/node           : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.10.2
   @ionic/angular                   : 7.5.0
   @ngrx/effects                    : 16.0.1
   @ngrx/entity                     : 16.0.1
   @ngrx/router-store               : 16.0.1
   @ngrx/schematics                 : 16.0.1
   @ngrx/store                      : 16.0.1
   @ngrx/store-devtools             : 16.0.1
   ng2-charts                       : 5.0.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you, @adrdilauro, for reporting this.

Unfortunately, changing the tags is not the only thing that can trigger the parent library. Let's say:
- your `Lib1` imports a function from `Lib2`
- Lib1 has a rule set to disallow the use of `deprecated` functions 
- you mark that function in `Lib2` as deprecated

In this case, despite not changing any tags, you would want the lint in `Lib1` to fail but if it's not marked as affected it wouldn't have been checked.

Another example is you import `Lib2` from `Lib1` and then at some point you import `Lib1` in the `Lib2` creating a circular dependency (something that enforce-module-boundaries checks). You want both of the libs's lints to fail, since both of them were affected by this circular dependency, not only Lib2.

Unfortunately, without running the lint we can't tell ahead of time whether that change you made actually caused ripple effects in the parent project or not. Therefore we mark it as "potentially" affected.
