### ISSUE TITLE
Add plugin for platformatic  

### ISSUE THREAD

**Issue by alexanderkhivrych** [nrwl/nx#20072]
## Description

Add NX plugin for platformatic 
https://docs.platformatic.dev/docs/reference/sql-graphql/queries
## Motivation

There is support for nest.js.  It would be great similar for Platformatic

**Comment by AgentEnder** [comment]
Hey @alexanderkhivrych 👋 - I'm going to close this out as we don't currently have plans for a first party plugin for platformatic. I'm labeling this with "community: plugin-request", because it is a good candidate for a community plugin.

Generally there are a few criteria that we use to determine if we should create a first party plugin for a given technology:
- We use it ourselves (either internally or via an enterprise client)
- The technology is super popular with the community (think something like being a standard tool)
- Our relationship with the tool maintainer 
	- Things like the tool wanting to promote Nx as a clear pathway to use said tool.
	- This typically leads to a "first party" plugin, but maintained by the tool owner rather than us. In these cases we help them get things working and such, but still no @nx scoped plugin.
- The technology does something different that would require a plugin to be able to be used via Nx, and we want to see the effort and techniques that the plugin required. 
	-  This is the least important criteria, and the resulting plugin is more likely to live in https://github.com/nrwl/nx-labs than the main repo as we haven't really committed to full time maintenance.

In this case I don't think platformatic is really strong for any 1 of those criteria. It appears that it should be easy to write a community plugin though, and I'd encourage trying it out.
