### ISSUE TITLE
Provide executors to each project in a workspace

### ISSUE THREAD

**Issue by alper** [nrwl/nx#20173]
In the writing a simple executor we have this bit:

> Our last step is to add this executor to a given project’s targets object in your project's project.json 

Would it be possible to provide a bunch of executors to every project from the workspace root?

I don't see anything we could add to `nx.json` at the root to enable this.

It's going to be a bit tedious to touch every project's `project.json` to provide it the same utilities.

**Comment by FrozenPandaz** [comment]
One way is to write a `generator` which will update all projects using [getProjects](https://nx.dev/nx-api/devkit/documents/getProjects) and [updateProjectConfiguration](https://nx.dev/nx-api/devkit/documents/updateProjectConfiguration).

Another way is to write a `createNodes` plugin using the experimental API but it may change. https://nx.dev/extending-nx/recipes/project-graph-plugins. I think this would be the best way actually but, the API is fresh and we're still making sure it has the right shape before we make it stable.

I'm going to make this a docs issue since we really ought to have a guide on this.

**Comment by alper** [comment]
> Another way is to write a createNodes plugin using the experimental API but it may change. https://nx.dev/extending-nx/recipes/project-graph-plugins. I think this would be the best way actually but, the API is fresh and we're still making sure it has the right shape before we make it stable.

This looks interesting, but the documentation does not make a lot of sense or at least I can't get the `createNodes` function to be called as part of our existing plugin (which is nothing but a collection of generators and executors).

**Comment by isaacplmann** [comment]
Since this issue was filed, there have been a couple new docs pages that would address it:
Reduce Repetitive Configuration - https://nx.dev/recipes/running-tasks/reduce-repetitive-configuration
Tooling Plugin Tutorial - https://nx.dev/extending-nx/tutorials/tooling-plugin
