### ISSUE TITLE
feat(lint): add import rule to prevent circular dependencies

### ISSUE THREAD

**Issue by bcabanes** [nrwl/nx#2019]
## Current Behavior

Importing from within a given library (.e.g. `@proj/lib-a`) should use relative paths (.e.g. `./module`) instead of the paths in path-mappings (e.g. `@proj/lib-a`). Currently, there is no way to restrict this via linting.

## Expected Behavior

Importing from `@proj/lib-a` from within `@proj/lib-a` should result in a linting error.

We can use the following rules for each library's `tslint.json` or `.eslintrc`:

### TSLint

https://palantir.github.io/tslint/rules/import-blacklist/

```
    "import-blacklist": [true, "rxjs/Rx", "@nx-examples/shared/jsxify"]
```

### ESLint

https://eslint.org/docs/rules/no-restricted-imports

```
"no-restricted-imports": ["error", "import1", "import2"]
```

### Caveats

If the workspace has this rule in their root linting config, the generated rule should include what is there because it will be completely overwritten otherwise.

We should also write a migration which will add this rule to existing projects within the workspace.

## Related Issues
#738
#741

**Comment by FrozenPandaz** [comment]
I don't think this would be too hard for someone in the community to attempt. Would somebody be interested in taking a look?

**Comment by mehrad-rafigh** [comment]
Hi @FrozenPandaz! Our Team is having the same issues since our IDEs tend to use the mapped path import. 
Would you so be so kind and point to me the direction, where the changes are needed?

**Comment by twittwer** [comment]
Currently, we're doing this via a workspace schematic: https://gist.github.com/twittwer/d1adb85f873b02b14b6f52d2aa9ec4f3#file-index-ts-L124

Would be nice to get this out of the box 😄

**Comment by nealeu** [comment]
Agree that out of the box is important.

I've just arrived in "nx world", and the experience is such that it's easy to just decide "I'll stay as I was with Yarn workspaces".

The problem here is that after an import using `add-nx` things look sort of okay, that is, until things get pushed to a CI server where nx makes the wrong decision about the build order where a circular dependency exists.  Naturally, our developers were getting away with it because tsc was able to cope because one of the directions gets erased when generating the .js.

For nx, it would be far better to have an opinionated out of the box experience that at:
- errors, saying that there are circular dependencies
- tells the user how to explicitly override the dependencies for dep-graph generation, or how to specify a preferred build order where there is ambiguity

**Comment by llwt** [comment]
Not stale :) Could still really use this, we might contribute this if someone doesn't beat us to it.
