### ISSUE TITLE
feat: ✨ Creating @nx/angular:esbuild-dev-server - Incremental build dev server for esbuild with Angular 17

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#20267]
## Description
With the introduction of Angular 17 and the new default builder: @angular-devkit/build-angular:application, we no longer have an incremental serve story with Nx. If you try to use the webpack-dev-server, you'll see the error:

`NX   The `application` and `browser-esbuild` builders do not support Webpack transforms.`

## Motivation
When using the new esbuild feature from Angular 17 and TailwindCss, it takes us 500+ seconds to start up a large application. When we make a simple code change, it takes 280+ seconds for esbuild to rebuild.

The esbuild build story is GREAT. Working with esbuild and TailwindCSS on a daily basis is a completely different story.

Wondering what's possible here. The current situation is not currently tenable. 

Thoughts from the great Nx Team highly requested 🍺
Bjorn

**Comment by JelleBruisten** [comment]
After updating to nx 17/17.1, I'm running into related problem: 
`Cannot find builder 'browser-esbuild' in ...node_modules\@nx\angular\executors.json.`. 

Before we were using the webpack builder, we found that the webpack builder runs into memory problems in our azure pipeline ( a feature branch regarding a large feature, that is due to be moved to the main branch soon ). This problem seemed to have been resolved with using the browser-esbuild however after upgrading to nx 17/17.1 we are not able to serve our application locally anymore. Therefore upgrading is not a option at this moment.

We're using the executor for serving:
`@angular-devkit/build-angular:dev-server` for serving

And for building the following executor is used:
`@nx/angular:browser-esbuild`

The building works, we also can deploy it and works fine, but it won't work for local development. This prevents us from upgrading `nx` and `angular` to the latest versions.

Having a incremental build dev server for esbuild would likely resolve this issue

**Comment by leosvelperez** [comment]
@JelleBruisten that's a separate issue that has already been fixed by https://github.com/nrwl/nx/pull/20307 (though it hasn't been released yet). The issue reported in this thread will be addressed by https://github.com/nrwl/nx/pull/20311.
