### ISSUE TITLE
Option to exit parallel run-commands with non-zero exit code

### ISSUE THREAD

**Issue by twittwer** [nrwl/nx#20285]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like an option to stop parallel running commands of `run-commands` executor based on the exit code of the first one ready.
Currently, it is supported to define a custom done condition via [`readyWhen`](https://nx.dev/nx-api/nx/executors/run-commands#readywhen). But this causes an exit code of 0 all the time.

## Suggested Implementation

The idea is to add a `race` flag to the `run-commands` options, like in [npm-run-all](https://github.com/mysticatea/npm-run-all/blob/bf91f94ce597aa61da37d2e4208ce8c48bc86673/docs/npm-run-all.md). So the first command exiting will define the exit code for the whole `run-commands`-target and stops other parallel running commands.

## Alternate Implementations

Alternatively, a `failsWhen` companion for `readyWhen` would be great to define a text which stops all commands like `readyWhen` but triggers a non-zero exit code for the whole `run-commands`-target.

## Motivation

My use case is storybook testing in the CI.
The standard `test-storybook` command (generated by storybook plugin) requires a running storybook instance:
`test-storybook --config-dir libs/workspace/.storybook --url http://localhost:4220`
The easiest way to provide this is the also generated `static-storybook` command, which serves a built storybook.

The idea for our CI pipeline was to run both commands in parallel.
But because `static-storybook` will not end automatically, I added `readyWhen`.
```
{
  "commands": [
    "npx nx run workspace:static-storybook",
    "npx nx run workspace:test-storybook"
  ],
  "parallel": true,
  "readyWhen": "Ran all test suites"
}
```

But this exits with exit code 0 regardless of the test command's exit code.

**Comment by ErickRodrCodes** [comment]
following up this since it has been a while for this issue.

**Comment by twittwer** [comment]
Thx @ErickRodrCodes for the ping, missed following up during the Christmas season.
I was waiting for some reaction from the nx team, if the idea is appreciated, to know if it's worth to start implementation.

@AgentEnder Could you say something about, if such a PR would have a chance to be accepted?

**Comment by ganlhi** [comment]
I completely agree with this proposition! I have this need to run a static web server running Storybook and `test-storybook` in parallel, but I need to exit when the tests are done. Right now I'm forced to use `concurrently` because `run-commands` with `readyWhen` won't report a failure if my tests fail. 

I think one very simple way of doing it I found is to change lines 295-300 of `packages/nx/src/executors/run-commands/run-commands.impl.ts` to:

```typescript
  childProcess.stderr.on('data', (err) => {
      process.stderr.write(addColorAndPrefix(err, commandConfig));
      if (readyWhen && err.toString().indexOf(readyWhen) > -1) {
          res(false);
      }
  });
```

**Comment by arimgibson** [comment]
There's a related bug here as well I believe -- because the process can't exit with a non-zero status code, child processes are not able to handle shutdown signals properly. The application is exited immediately without a chance for the process exit to be handled gracefully. Planning on submitting a bug about this and will link this issue as well
