### ISSUE TITLE
Cannot find builder 'module-federation-dev-server'

### ISSUE THREAD

**Issue by imdurdydan** [nrwl/nx#20291]
### Current Behavior

We currently have an application that uses module federation  that consists of one host and 4 remote apps. The host is an angular application while the remotes are all react applications. 

The command most developers run to start the application is `npx nx serve accelerator-shell --devRemotes=<remoteName>--skipRemotes=<remotesTheyDontCareAbout>  --proxy-config proxy.conf.json`

Which has worked pretty flawlessly until we just recently upgraded the NX versions (attached a screenshot of what we were on and what we went to). 
<img width="914" alt="Screen Shot 2023-11-16 at 15 43 28" src="https://github.com/nrwl/nx/assets/9564462/3d8fa3ef-2185-4f31-a85b-dbb7c0256046">

<img width="849" alt="Screen Shot 2023-11-16 at 15 46 19" src="https://github.com/nrwl/nx/assets/9564462/57270fe6-a8c4-4c9b-afb4-c4e058a94515">

Now when we run the same command we get the following error:
<img width="1016" alt="Screen Shot 2023-11-16 at 15 46 59" src="https://github.com/nrwl/nx/assets/9564462/df781359-7d3a-419b-a81d-260782bb40c8">

If i go to the file location it says it cant find it at i see the executors but nothing about builders. I dont think this is really anything wrong with NX but probably something that changed in the setup of module federation projects once we upgraded to the new versions we are on, so just looking for any insight into what that error could even mean. 

### Expected Behavior

I can serve my angular host application with react remotes

### Steps to Reproduce

1. Setup a module federation project with an angular host and a react remote application
2. Serve the host app with the devRemotes option that lists the react remote application

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-x64
   npm    : 9.8.1
   
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/react          : 17.0.3
   @nx/storybook      : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/vite           : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   nx-cloud           : 16.5.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/spectator : 14.0.0
   @ngneat/transloco : 4.3.0
   @ngrx/store       : 15.3.0
   ng-mocks          : 14.11.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Angular Host Project `serve` phase:
<img width="729" alt="Screen Shot 2023-11-16 at 15 53 26" src="https://github.com/nrwl/nx/assets/9564462/668436ad-dc3a-4db7-b274-273a6c76cbeb">

React Remote `serve` phase:
<img width="560" alt="Screen Shot 2023-11-16 at 15 53 40" src="https://github.com/nrwl/nx/assets/9564462/5b87af4d-0fe9-4871-ad8f-78d514f6243d">

**Comment by ndcunningham** [comment]
Hi,

Thanks for reaching out and sharing the details of your application setup. Currently, our implementation of Module Federation is designed to support applications within the same framework. The scenario you've described, which involves one Angular host application and four React remote applications, isn't within the scope of our intended use cases.

If you've previously experienced successful integration across these mixed frameworks, it's important to note that this was not an intentional feature of Module Federation. Our primary focus is supporting single-framework applications to ensure stability and optimal performance.

For your current setup, we recommend considering strategies that align with this approach. Thanks.

**Comment by Coly010** [comment]
As @ndcunningham has mentioned, this is not a strategy we support or encourage. In fact we actively discourage it as it is in the realm of Micro Frontend Anarchy. 

However, although we don’t support it, this could be solved and actually likely will be when one of my open PRs is merged.

The angular module federation dev server uses Angular’s scheduleTarget api to run the dev remotes.

This worked before Nx 17 because React had compat versions of executors, as angular builders, so scheduleTarget was able to work with the compat.

We removed this compat support in Nx 17.

So there’s no builder for Angular to use when using scheduleTarget.

However, I have a PR which converts the Angular module-federation-dev-server to an Executor, which will use runExecutor for the dev remotes, meaning this will work again.

**Comment by imdurdydan** [comment]
@Coly010 and @ndcunningham thanks for the replies. Sadly we are aware this is actively discouraged and was just a choice we had to make after starting a new angular application and having to hard pivot the technology as resources changed drastically for us and is really just a short term solution until we can get some original feature work converted to react. I will keep an eye open for that PR of yours @Coly010 and we may try again then, we dont intend to keep our codebase in this fragmented technology stack, if anything these responses will probably just hasten our conversion of the angular code to react.
