### ISSUE TITLE
Please explain how peer dependencies are used with a single package.json

### ISSUE THREAD

**Issue by charlesritchea** [nrwl/nx#20451]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

(https://nx.dev/concepts/more-concepts/dependency-management)

### Additional context or description

I have a bespoke lerna, yarn workspaces, non-angular-cli webpack based monorepo that I'd like to migrate to a typical Nx monorepo with a single package.json, but one thing I don't understand is how peer dependencies come into the picture with a single package.json. We don't have NPM published libraries, but we have libraries that cannot have certain dependencies be bundled becase they are are included with another bundled library and duplicate dependencies results in app failure. Do I just ignore peerDependencies in package.json and only focus on webpack externals? But even if I did have a simple NPM published library in a monorepo with an app it would have the same problem.

**Comment by FrozenPandaz** [comment]
Sorry, I'm not sure I understand the question here.

Let me see if I understand correctly.

Some projects in the repo have `peerDependencies` which rely on something else bringing them in for them. For example, `lib1` has a peer dependency on like.. `lodash`. `app1` and `app2` both provide their own versions of `lodash`.

With multiple `package.json` files, `app1` installs `lodash@v1` and `app2` installs `lodash@v2`. `lib1` does not get bundled with any version of `lodash` but rather uses the one from `app1` or `app2`.

With a single `package.json` file, `app1` and `app2` both install the same version of `lodash`. `lib1`, still does not get bundled with any version of `lodash`. Now it just happens to be the same version.

It's still perfectly fine for `lib1` to have a `peerDependency` because something else will bring it in. Is this the explanation you were looking for in the docs?

**Comment by charlesritchea** [comment]
I think so, I barely remember asking this question. I'm so used to yarn workspaces right now, I find the entire "normal" Nx idiom very confusing. I kinda get it starting from scratch, but trying to migrate toward that... I just don't understand how to do that. Our system is so weird it's probably not worth humoring me right now. I'm just so so frustrated with trying to reconcile this originally lerna bootstrap based repo (that builds most libs like they're apps and loads them with evalolol) with what is expected by the tooling. It's Lovecraft country!
