### ISSUE TITLE
Unable to use separate Nx Cloud Remote Cache for different GitHub CI runners

### ISSUE THREAD

**Issue by nbolton** [nrwl/nx#20456]
### Current Behavior

The cache is downloaded from Nx Cloud to the macOS runner (so that now the macOS runner is using code built on the Linux runner). We set `NX_CI_EXECUTION_ENV` to the OS name assuming that it would create a new cache for each Nx execution environment, but that didn't work.

```
 >  NX   Creating run group. branch: 695, ciExecutionId: 7021083527-1, ciExecutionEnv: ubuntu, runGroup: 7021083527-1-ubuntu, commitSha: 9e57023b6f052e928a22b31ad82924c60cddd39b

[Nx Cloud] Detected Env: GitHub Actions
{
  "branch": "695",
  "ref": "some-branch-name",
  "title": "Merge b5fb9b3ee13edb54474577ca95cd213e655fe48e into 0e74450ac4fb5f692a9ff7797c7432cda48ab622",
  "headSha": "9e57023b6f052e928a22b31ad82924c60cddd39b",
  "baseSha": null,
  "commitLink": "####",
  "author": "####",
  "authorUrl": "####",
  "authorAvatarUrl": "####"
}

 >  NX   Trying to create heartbeat background process for run group: 7021083527-1-ubuntu
```

### Expected Behavior

Expected cache to be separate based on the `NX_CI_EXECUTION_ENV` so that the macOS runner doesn't download the cache build on the Linux runner. This however does nothing for cache.

### Steps to Reproduce

1. Use Nx Cloud Remote Caching
2. Set `NX_CI_EXECUTION_ENV` to current OS (e.g. "linux")
3. Build using a Linux GitHub runner
4. See that cache is uploaded to Nx Cloud
5. Build the same source code on a macOS GitHub runner

### Nx Report

```shell
Run npx nx report
  npx nx report
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: false
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 1
    NX_BRANCH: 695
    NX_CLOUD_ACCESS_TOKEN: ***
    NX_VERBOSE_LOGGING: true
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    NX_CI_EXECUTION_ENV: ubuntu

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : linux-x64
   npm    : 9.8.1
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/esbuild        : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/node           : 17.1.3
   @nx/playwright     : 17.1.3
   @nx/plugin         : 17.1.3
   @nx/react          : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/vite           : 17.1.3
   @nx/web            : 17.1.3
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
   	 @synergy/toolchain
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Workaround: Write a script that puts a file in every dir with the OS name, e.g. `.nx-cache-ubuntu`.

**Comment by StalkAltan** [comment]
This is working as intended -- `NX_CI_EXECUTION_ENV` allows you to group work from different environments (could be OS, machine spec, etc) under a single CI Pipeline Execution. It doesn't influence caching by default, because caching is fully defined using `inputs` or `namedInputs`.

If your output really does depend on the OS it's run from, you can do one of the following:
1) Use a `runtime` input and execute something that tells you your current OS ([runtime example here](https://nx.dev/recipes/running-tasks/customizing-inputs#include-runtime-information-in-the-cache-hash)), or
2) Use an `env` input and use the value of `NX_CI_EXECUTION_ENV` directly. I would not recommend this as this variable is probably not going to be defined locally, so there wouldn't be a possibility for developers to retrieve cached artifacts that were built in CI. ([example here](https://nx.dev/recipes/running-tasks/customizing-inputs#include-runtime-information-in-the-cache-hash))

Hope this helps!

**Comment by nbolton** [comment]
> Use a `runtime` input

Perfect, thank you, I'll give that a shot!
