### ISSUE TITLE
Apps are not generating inside apps folder for integrated monorepo

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#20464]
### Current Behavior

Apps are creating on root level of the application

### Expected Behavior

Apps should get created inside apps folder for integrated monorepo

### Steps to Reproduce

1. npx create-nx-workspace@latest (Select `integrated` monorepo)
2. install @nx/angular (npm i @nx/angular -D)
3. nx g app
4. Check where the new app is getting created
 

### Nx Report

```shell
C:\Projects\projects\workspaces2\5.12\nx17app>nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : win32-x64
   npm    : 8.19.3

   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2


C:\Projects\projects\workspaces2\5.12\nx17app>
```

### Package Manager Version

npm

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by hemanth-r** [comment]
Adding the parameter `--directory=apps/` to the `nx g` command works for me.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

You didn't get what you expected because after the workspace was created, there's no `apps` folder and therefore, the generator assumes that folder is not being used and the application is generated at the root because no directory was provided. That is just one of the many rules Nx generators followed up until recently. It's not the only one. There are many rules and in general, generators assume many things for the user. This limits flexibility and what users can generate. It also makes the mental model of how and where things are generated more complex.

A few versions ago, Nx introduced a new way of generating projects and artifacts. With the new way, Nx generators will create projects or artifacts exactly as the options provided by the user specify. We still support the old way which would have allowed you to get what you expected, but, as explained above, there was no `apps` directory in the workspace, so, the old way and the new way generate the same thing in that case.

For a more in-depth explanation and examples, please see https://nx.dev/deprecated/as-provided-vs-derived.

Please note the new way will be the only way of generating things in Nx v18.

I'm closing this since it's working as expected.
