### ISSUE TITLE
Storybook setup fails with 'resolveName does not accept ObjectMethod'

### ISSUE THREAD

**Issue by bosycom** [nrwl/nx#20468]
### Current Behavior

Running storybook on a fresh workspace setup does not work.

### Expected Behavior

Running storybook should work.

### GitHub Repo

Not needed, easy to reproduce

### Steps to Reproduce

`npx create-nx-workspace@latest`
 -> workspace "org"
 -> react
 -> next.js
 -> integrated monorepo
 -> app name "org"
 -> cypress
 -> styled-components
 -> no cache distribution

`yarn nx g @nx/next:lib my-ui-lib`
 -> styled components

`yarn add -D @nx/storybook`

`yarn nx g @nx/storybook:configuration my-ui-lib`

-> yes, interaction tests
-> @storybook/nextjs

`yarn nx run my-ui-lib:storybook`

`
ERROR in ./node_modules/markdown-to-jsx/dist/index.modern.js
Module build failed (from ./node_modules/@storybook/preset-react-webpack/dist/loaders/react-docgen-loader.js):
TypeError: Attempted to resolveName for an unsupported path. resolveName does not accept ObjectMethod".
`

### Nx Report

```shell
Node   : 20.9.0
   OS     : win32-x64
   yarn   : 1.22.21

   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/next           : 17.1.3
   @nx/react          : 17.1.3
   @nx/storybook      : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/vite           : 17.1.3
   @nx/web            : 17.1.3
   typescript         : 5.2.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @bosycom ! I unfortunately could not reproduce your issue. Here is my repository: https://github.com/mandarini/storybook-nextjs-nx

I am on MacOS so maybe it's a Windows issue. I'll ping someone from the team who's on Windows so that they can investigate, but it looks like an issue with Storybook, so maybe you can open a new issue on the Storybook repository, or look in their issues if it's been reported already.

Just off the top of my head:
could it be that you don't have any stories? can you try generating storybook configuration using the [`nx g @nx/react:storybook-configuration` generator](https://nx.dev/nx-api/react/generators/storybook-configuration), which will also generate stories for you? i don't know if that's the issue, but just checking.

**Comment by I-NOZex** [comment]
+1

**Comment by mandarini** [comment]
@I-NOZex can you please share a reproduction repository?

**Comment by I-NOZex** [comment]
@mandarini - Resolved by adding this to the config :
```js
 typescript: {
    reactDocgen: true,
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) =>
        prop.parent ? !/node_modules/.test(prop.parent.fileName) : true,
    },
  },
```
.storybook\main.js


```js
module.exports = {
  stories: [
    './pages/**/*.stories.mdx',
    '../src/**/*.stories.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
  ],

  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-react-native-web',
    '@storybook/addon-mdx-gfm',
    '@storybook/addon-docs',
    '@storybook/addon-viewport',
  ],

  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },

  docs: {
    autodocs: true,
  },
  typescript: {
    reactDocgen: true,
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) =>
        prop.parent ? !/node_modules/.test(prop.parent.fileName) : true,
    },
  },
  webpackFinal: async (config) => {
    config.module.rules = config.module.rules.filter(
      (rule) =>
        !rule?.use?.some?.((u) =>
          String(u?.loader)?.includes?.('export-order-loader')
        )
    );

    return config;
  },
};
```

**Comment by mandarini** [comment]
Thanks for the reply @I-NOZex  :D Glad you solved it!!!!

**Comment by herzaso** [comment]
This issue is not solved, I get it as well in version 7.6.10:
```
 ERROR  11:00:20 AM [vite] Internal server error: Attempted to resolveName for an unsupported path. resolveName does not accept ObjectMethod".
  Plugin: storybook:react-docgen-plugin
```

The provided workaround has the same effect as `reactDocgen: false` in my environment which is not good since props and descriptions are unavailable.

I don't have a reproduction env, but it might have something to do with monorepo.
I'm using React 17.0.2, vite 4.4.9, typescript 5.1.3 and I have 1 repo with 2 workspaces (yarn 3.3.1)

The failures I get are from trying to import package A from package B

**Comment by mandarini** [comment]
@herzaso can you please provide a simple reproduction repository? it will help me in solving the issue!

**Comment by herzaso** [comment]
@mandarini I'm sorry but the issue seems to be related to Storybook and not nx. I'll take it there...
