### ISSUE TITLE
[Vite][Yarn Workspace] Failed to resolve entry for package "xyz"

### ISSUE THREAD

**Issue by bobalazek** [nrwl/nx#20520]
### Current Behavior

I am unable to build react libraries if they are dependent on another library.

I spent the whole afternoon yesterday trying to fix this, but I couldn't really get to the bottom of this. Clearly, I've tried to set those "main" and "exports" to `./src/index.js`, but this didn't work either, which kind of makes sense, because the `web-ui` library does build and in the `dist` folder the `index.js` is actually in the same directory as package.json, so I couldn't wrap my head around why that is an issue.

### Expected Behavior

Should build as expected

### GitHub Repo

https://github.com/bobalazek/nx-issue-repro

### Steps to Reproduce

1. Clone the repo
2. Run yarn to install dependencies
3. Run yarn nx run-many --target=build --all to try to build the apps

### Nx Report

```shell
Node   : 20.9.0
   OS     : darwin-arm64
   yarn   : 4.0.2
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/react          : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/vite           : 17.1.3
   @nx/web            : 17.1.3
   typescript         : 5.2.2
```

### Failure Logs

```shell
yarn nx run-many --target=build --all
 
    ✔  nx run web:build:production (2s)

    ✖  nx run web-core:build:production
       vite v4.3.9 building for production...
✓ 2 modules transformed.
       
       [vite:dts] Start generate declaration files...
       ✓ built in 645ms
       [vite:dts] Declaration files built in 611ms.
       
       [commonjs--resolver] Failed to resolve entry for package "@nx-issue-repro/web-ui". The package may have incorrect main/module/exports specified in its package.json.
       
        >  NX   Failed to resolve entry for package "@nx-issue-repro/web-ui". The package may have incorrect main/module/exports specified in its package.json.
       
          Pass --verbose to see the stacktrace.
       
       
    ✔  nx run web-ui:build:production (4s)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 3 projects (4s)
 
    ✔    2/3 succeeded [0 read from cache]
 
    ✖    1/3 targets failed, including the following:
         - nx run web-core:build:production
```

### Package Manager Version

Yarn v4.0.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by bobalazek** [comment]
The hacky fix for me was setting `main` in `package.json` to `./src/index.ts`, which was mentioned in this task: https://github.com/nrwl/nx/issues/18492#issue-1836822457

Sadly that was only one of the issues I encountered, so in the end, I decided to migrate the whole project to Turborepo instead.

**Comment by fsgreco** [comment]
Hi @bobalazek I found a different solution in case you're interested: basically instead of removing the symbolic link, you need to change the import alias name on "paths" property inside `tsconfig.base.json`. It need to have a different alias from the name specified in the `package.json`. If you call it `@nx-issue-repro/web-ui` then try to change it inside tsconf file and use this last new alias to import it inside the app. 

I explain this solution in more detail in this recent issue: https://github.com/nrwl/nx/issues/21030
I guess yarn is doing the same thing that npm, since it creates a symbolic link of the library inside the node-modules directory that generate some conflicts, I also saw that your project uses `nxViteTsPaths` too... 

Please let me know in the comments in case you try this and works (I'm curios if this happens also using yarn, it seems to be the case).

**Comment by MBelniak** [comment]
This might help, as it's most probably related to symlinks as @hailerity mentioned https://github.com/nrwl/nx/issues/18931#issuecomment-2034872283
