### ISSUE TITLE
While installing latest nx@16.7.4 we are facing issue Blocked App MMC.EXE Location c:\windows\system32

### ISSUE THREAD

**Issue by jnellissery** [nrwl/nx#20610]
### Current Behavior

can't install Angular 16 with nx 16.7.4 . My Node version is 18.7.0

### Expected Behavior

install angular 16.2.0 with nx 17.74 

### Steps to Reproduce

1.
While installing latest nx@16.7.4 we are facing issue Blocked App MMC.EXE Location c:\windows\system32

### Nx Report

```shell
While installing latest nx@16.7.4 we are facing issue Blocked App MMC.EXE Location c:\windows\system32
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
It sounds like this may be caused by smart screen on windows. In my experience it can be helpful to disable screening of development environments, but it may also help to run from an admin terminal: https://answers.microsoft.com/en-us/windows/forum/all/this-app-has-been-blocked-for-your-protection/e1d11ec3-8544-4c4b-afe3-1cf075681280
