### ISSUE TITLE
@nrwl/workspace - wrong dependencies installed?

### ISSUE THREAD

**Issue by jbjhjm** [nrwl/nx#2072]
## Expected Behavior

When installing @nrwl/workspace@8.7.1 the version of dependencies @angular-devkit/core & schematics should be 8.3.14 as seen in https://github.com/nrwl/nx/blob/master/packages/workspace/package.json

## Current Behavior

When installing @nrwl/workspace@8.7.1, version 8.3.3 of dependency @angular-devkit/core & schematics is being installed. My node_modules/@nrwl/workspace/package.json contains

```json
{
  "_args": [
    [
      "@nrwl/workspace@8.7.1",
      "D:\\projects\\uz_edu_portal\\application"
    ]
  ],
  "_development": true,
  "_from": "@nrwl/workspace@8.7.1",
  "_id": "@nrwl/workspace@8.7.1",
  // ...
  "dependencies": {
    "@angular-devkit/core": "8.3.3",
    "@angular-devkit/schematics": "8.3.3",
    // ...
  }
}
```

As I see, your package.json's are being post processed when building.
Can you please confirm if the current workspace version 8.7.1 depends on @angular-devkit/schematics 8.3.3 or 8.3.14?

If latter is the case I'll need to further investigate what's wrong here.

**Comment by mbriggs** [comment]
Hey, 

We are currently on 8.8.1, somewhere since 8.7.1, those versions have been changed. I looked at a version of the code from 8.7.1 and it matches what you have. https://github.com/nrwl/nx/blob/148a8c89e301288bbe78adbbad99a3ccae53e7f0/packages/workspace/package.json

Going to close this, if you have more questions, feel free to reopen : )

**Comment by jbjhjm** [comment]
Thanks @mbriggs !
