### ISSUE TITLE
Bypass nx generate @nx/angular:library "You can't specify both a directory and a name with a directory path"

### ISSUE THREAD

**Issue by urielzen** [nrwl/nx#20756]
### Current Behavior

I am trying to create an Angular library named `service/auth` in directory `libs/service/auth`.

![image](https://github.com/nrwl/nx/assets/7947179/6187a1c8-6b9f-4287-8210-41cb378f13c1)

This gives me the following error
```
You can't specify both a directory (libs/service/auth) and a name with a
directory path (service/auth).
Please specify either a directory or a name with a directory path.
```
![image](https://github.com/nrwl/nx/assets/7947179/549947b4-2b1c-48da-951d-7e88a77ab27c)

I then change the name of the library to `service-auth` as well as the directory to `libs/service-auth`. And that works with no problem.

![image](https://github.com/nrwl/nx/assets/7947179/64089f2a-e1ad-4e7b-a70b-be986209355e)

But then I can bypass the initial validation error above by moving the newly created library. Using both the directory and name that I wanted originally. And I get no errors.

![image](https://github.com/nrwl/nx/assets/7947179/feff7238-0a98-4439-bdd0-bc4bd306d19d)

![image](https://github.com/nrwl/nx/assets/7947179/df952dd0-2043-4c68-a7e9-05ee7e0939ed)

I end up with this in the tsconfig.base.json
```typescript
"@lf/service/auth": ["libs/service/auth/src/index.ts"],
```

### Expected Behavior

I would expect the validation error to be consistent between creating a library and moving it.

### Steps to Reproduce

See above

### Nx Report

```shell
Node   : 18.17.1
   OS     : win32-x64
   npm    : 8.11.0
   
   nx (global)        : 17.1.3
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/angular        : 17.2.0
   @nx/cypress        : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   @nx/webpack        : 17.2.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.14.0
   @ngrx/component-store            : 17.0.1
   @ngrx/signals                    : 17.0.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please note that a name of `service/auth` won't be allowed for the logical name of a project. Path segments are only allowed if you have scoped package names (e.g. `@acme/my-project-name`). When providing a path in the name (like `service/auth`), Nx project generators treat it as the directory and use the last segment (or anything after a `@`) as the project name. That's why you can't provide both a directory and a project name containing path segments.

As you pointed out, there's a bug in the `move` generator that's allowing that, which it's not consistent with the project generation. In the case of the move generator, the `--newProjectName` option won't allow providing path segments (unless it's a scoped package name) because the `destination` is a required option and will already contain the directory.

I'll push a fix for that.
