### ISSUE TITLE
NX   Missing Platform Dependency

### ISSUE THREAD

**Issue by gabrielpah7** [nrwl/nx#20845]
### Current Behavior

The Nx CLI could not find or load the native binary for your supported platform (linux-arm64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.

Macbook Pro M1
Docker
node 18
yarn 4.0.0.rc.42

### Expected Behavior

No errors

### Steps to Reproduce

1. yarn docker:up [service]

### Nx Report

```shell
Node   : 18.19.0
   OS     : darwin-arm64
   yarn   : 4.0.0-rc.42

   nx (global)        : 17.2.6
   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/jest           : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/esbuild        : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nx/nest           : 17.0.1
   @nx/next           : 17.0.1
   @nx/node           : 17.0.1
   @nx/plugin         : 17.0.1
   @nx/react          : 17.0.1
   @nx/rollup         : 17.0.1
   @nx/storybook      : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/web            : 17.0.1
   @nx/webpack        : 17.0.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
If you are copying dependencies from your local machine -> the docker container, you'll need to make sure to install the version of the native packages required by the platform your container is using, otherwise it will indeed not be present when trying to run commands.

If you are already running an installation step inside the docker container, it may be worth double checking your lockfile as it should contain the platform deps.
