### ISSUE TITLE
Ability to create your own dependencies in applications

### ISSUE THREAD

**Issue by W014ara** [nrwl/nx#20861]
## Description

Hello, i have a monorepository project with several Angular applications and libraries.
Current version of Angular is 12.1.4
NX version - 12.5.8

The question arose about updating to new versions of Angular. However, there are problems with packages that no longer support version 13 and must be abandoned. (there may be big impacts on the application).
The question arose: is it possible to update one of the applications to Angular 13 without affecting the others (individual update)? We tried to add our own package.json inside the application, our own angular.json. We made changes to the resolution of paths in tsconfig.json. However, when built, the application still works with the old version of Angular.

Is it possible to somehow separately assign applications their own dependencies and update them separately? Or does this contradict the monorepository paradigm?

## Motivation

More flexible application configuration without relying heavily on third-party dependencies

**Comment by jaysoo** [comment]
You can use npm/yarn/pnpm workspaces to install different versions across your projects, but it comes with its own problems because Nx generators and executors may not work with workspaces from package managers.

This will be improved soon, as we are focusing on better support for multiple versions of packages within the monorepo. Stay tuned!
