### ISSUE TITLE
Creating a Playwright E2E project for an existing project

### ISSUE THREAD

**Issue by michalvadak** [nrwl/nx#20900]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The [Cypress](https://nx.dev/nx-api/cypress/documents/overview#creating-a-cypress-e2e-project-for-an-existing-project) has option to create a separate E2E project for an existing one but [Playwright](https://nx.dev/nx-api/playwright/documents/overview) does not. 

## Motivation

This would be beneficial if you don't generate the E2E project with Playwright at the start. Unfortunately, you can't do that later.

## Suggested Implementation

The same as `nx g @nx/cypress:configuration your-app-name-e2e --project=your-app-name` works. It would generate a separate E2E project with Playwright.

**Comment by leosvelperez** [comment]
Thanks for the request!

There's a mistake in the docs linked to the example for the `@nx/cypress:configuration`. That generator doesn't create a separate project for the E2E tests. The generator docs explain this: https://nx.dev/nx-api/cypress/generators/configuration#feature-based-testing.

We don't plan to provide a generator to generate separate projects for E2E testing (Cypress or Playwright). Even though there's a `@nx/cypress:cypress-project`, it's an internal generator not meant to be used by users and might be removed at any moment without notice. In the link above is explained the benefits of having E2E in the same projects. You can make sure your task inputs are correctly set, so E2E code changes don't invalidate the cache for your builds, or unit test code changes don't affect your E2E tests, for example.

If you still want to create a separate project, you could create a simple generator to create the `project.json` file, the required tsconfig file and run the `@nx/playwright:configuration` generator. There are not many things needed to create a separate project.

I'm closing this since we're not planning to provide a generator to generate separate projects for E2E testing.
