### ISSUE TITLE
NX missing platform dependency 

### ISSUE THREAD

**Issue by Zachti** [nrwl/nx#20962]
### Current Behavior

I'm trying to docker compose my services in nx workspace but after the build and the log that notify that the docker is trying to perform nx start to my app im getting an error -
 NX   Missing Platform Dependency, 
 The Nx CLI could not find or load the native binary for your supported platform (linux-x64).
  This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.

i tried to add optional dependencies , and to add  to my nx.json file this - "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
    
  as i saw that it worked for some people but it didnt help , in addition tried to add .npmrc file to the root dir with include=optional but didnt work either.

  also i will add the complete log from the docker , the docker-compose file and dockerfile of each app.
  
<img width="1397" alt="Screenshot 2023-12-31 at 19 12 56" src="https://github.com/nrwl/nx/assets/114566720/3b86ae87-672c-4fcd-a295-5b6c047f40d0">

<img width="944" alt="Screenshot 2023-12-31 at 19 14 49" src="https://github.com/nrwl/nx/assets/114566720/d32b4776-e26f-4056-b805-67c3f35a7596">

<img width="974" alt="Screenshot 2023-12-31 at 19 14 56" src="https://github.com/nrwl/nx/assets/114566720/7de2c569-4cac-4adc-bccf-b5feaaf270b3">

<img width="974" alt="Screenshot 2023-12-31 at 19 15 33" src="https://github.com/nrwl/nx/assets/114566720/b8b58b29-0040-453b-b6be-4f1d448b9869">

### Expected Behavior

the code will run in the docker

### Steps to Reproduce

1.

### Nx Report

```shell
NX   Missing Platform Dependency
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

package manager - npm

**Comment by Zachti** [comment]
also i do have the package @nx/nx-darwin-x64 package inside my node_modules dir , and i can make nx command using the cli on my terminal.

**Comment by gwenael-hagenmuller** [comment]
Hi @Zachti,
Your issue is certainly that your Docker container is missing the `@nx/nx-<platform>-<architecture>` for it. You mentioned that you have `@nx/nx-darwin-x64` package inside your `node_modules` dir but I would be surprised that the platform/architecture of your Docker container is `darwin-x64`. From what you shared, you seem to use `alpine` for your Docker container, so it would be more `@nx/nx-linux-x64-musl` or `@nx/nx-linux-x64-gnu` I think. `linux-x64` is actually mentioned in the error message you shared. In your Docker container make sure to `npm install` WITH optional dependencies. Maybe https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues#supported-native-module-platforms can help. Do you check what you have in `node_modules` for `heimdall` and `vault`?

**Comment by Zachti** [comment]
Hi @gwenael-hagenmuller ,
Thanks for your response. 
I verified that I installed the dependency with the optional dependencies. 
within my Docker container, inside the node_modules directory there is @nx directory, both the Linux-x64-gnu and the Linux-x64-musl directories are installed there.

**Comment by MonochromeChameleon** [comment]
Just in case it's useful, I've been seeing a similar issue in my CI builds on a linux-x64 box, but not locally on darwin-x64. Specifically, in CI we can install and use 19.0.2 without any problems, but 19.0.3+ all raise the missing platform dependency error. Looking inside `node_modules` I can see that the linux-x64-gnu and linux-x64-musl dependencies are present.
I don't remember which steps I used to get there, but my digging around last week suggested that there might be an issue with the signing of the bundled binaries.

**Comment by FrozenPandaz** [comment]
This was fixed with #22870. :tada:
