### ISSUE TITLE
Lint: Dependency constraint checks don't work when path matches project name

### ISSUE THREAD

**Issue by tmtron** [nrwl/nx#2124]
## Expected Behavior

When the path in tsconfig matches the project name, the lint dependency constraint check should still work - or at least report an error or warning.

## Current Behavior

The tslint checks don't report anything.

### Steps to Reproduce

It's easiest to explain based on the [nx-examples]( https://github.com/nrwl/nx-examples) repo.

E.g. in [angular.json](https://github.com/nrwl/nx-examples/blob/master/angular.json#L290) we have a library named `shared-product-data`: 

```
    "shared-product-data": {
      "root": "libs/shared/product/data",
      "sourceRoot": "libs/shared/product/data/src",
      "projectType": "library",
```
and in [tsconfig.json](https://github.com/nrwl/nx-examples/blob/master/tsconfig.json#L23) we have a path mapping:

```
{
  "compilerOptions": {
    "paths": {
      "@nx-example/shared/product/data": [
        "libs/shared/product/data/src/index.ts"
      ],
```

With this mapping the lint checks work as expected. E.g. when `apps/products` imports some code from `@nx-example/shared/product/data`, we get a nice lint message, that this is not allowed.

 ```
ERROR: D:/dev_no_backup/nx-examples/apps/products/src/main.ts:6:1 - A project tagged with "type:app" can only depend on libs tagged with "type:feature", "type:ui"
```

But when the path in `tsconfig.json` matches the project name in `angular.json` we get no message at all. I've created a github-repo [tmtron/nx-examples](https://github.com/tmtron/nx-examples) to reproduce the issue.  
The only relevant changes are in this [commit](https://github.com/tmtron/nx-examples/commit/1e1f6a7a778def2eed4c9193689fe98f690d1ad2):  
in [tsconfig.json](https://github.com/tmtron/nx-examples/blob/master/tsconfig.json#L23) the path has been changed to `@nx-example/shared-product-data`  (note the dashes):
```
      "@nx-example/shared-product-data": [
        "libs/shared/product/data/src/index.ts"
      ],
```

When we now run lint again, we get no message at all.

## Other

It took me really long to find out what's going on. I hope you can fix that or at least provode some info in the docs to help other newbies.  
I found an old closed issue that seems to have the same issue #1108

**Comment by Cammisuli** [comment]
Thanks for the reproduction! 

It looks like you're right. When changing the path map to something that's not the actual source path, we cannot find the project. 

https://github.com/nrwl/nx/blob/53f17d5331baaaf421a7fb162df4c3c076ff7d75/packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts#L140-L150

This is because there's a function that's getting the project, normalizing the root and trying to match it with the import.

https://github.com/nrwl/nx/blob/53f17d5331baaaf421a7fb162df4c3c076ff7d75/packages/workspace/src/utils/runtime-lint-utils.ts#L128-L141


Changing the path mapping so that the imports are a bit cleaner is definitely something that should be supported properly.

**Comment by Cammisuli** [comment]
As a workaround, you could place the lib to the root of the lib folder with the same name as the import.
