### ISSUE TITLE
Unit tests really slow on first run

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#21260]
### Current Behavior

when running unit tests the first run is really slow.. 
```
 PASS   feature-payment  libs/feature-payment/src/lib/feature-payment/payment.component.spec.ts (94.194 s)
```
then when run it a second time (using --skip-nx-cache) I would expect about the same result.. but this is what I get:
```
 PASS   feature-payment  libs/feature-payment/src/lib/feature-payment/payment.component.spec.ts (6.492 s)
```
only the first run is really slow and then it runs fast after that..

This becomes a problem when running in CI.. it's slow each time there..

````
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { FeaturePaymentsComponent } from './feature-payments.component';
import { TranslocoModule } from '@ngneat/transloco';

global.ResizeObserver =
  window.ResizeObserver ||
  jest.fn().mockImplementation(() => ({
    disconnect: jest.fn(),
    observe: jest.fn(),
    unobserve: jest.fn(),
  }));

describe('FeaturePaymentsComponent', () => {
  let component: FeaturePaymentsComponent;
  let fixture: ComponentFixture<FeaturePaymentsComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [FeaturePaymentsComponent, HttpClientTestingModule, TranslocoModule],
      providers: [{ provide: Window, useValue: window }],
    }).compileComponents();

    fixture = TestBed.createComponent(FeaturePaymentsComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
````

### Expected Behavior

Execution time should be roughly the same

### Steps to Reproduce

1. Not really sure how to reproduce

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-x64
   npm    : 10.0.0

   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.14.0
   @ngneat/transloco                : 4.3.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Jest (and `ts-jest` used by Angular tests) has its own cache for the files it processes. That's separate from the Nx cache and it explains why, even though you're skipping the Nx cache, you still got a faster run. If you want to compare apples to apples, you need to also clear the Jest cache between runs `npx jest --clearCache`. So, what you were experiencing is the expected behavior.

Your test being slow is a separate issue that could be caused by a wrong configuration and/or test (e.g. not mocking stuff). If you think there's an issue with the Nx-generated configuration or the executor running the tests, please provide a reproduction so we can troubleshoot it.
