### ISSUE TITLE
Using npx to execute nx changes the status code returned

### ISSUE THREAD

**Issue by Voziv** [nrwl/nx#21506]
### Current Behavior

Using `npx nx run example-service:test` seems to cause an exit code of 0 at all times. It also caches this so future runs without npx also return the cached status of 0.

### Expected Behavior

`npx` shouldn't change the exit code returned nor cached.

### GitHub Repo

https://github.com/Voziv/monorepo-nx/pull/2

### Steps to Reproduce

1. Checkout `https://github.com/Voziv/monorepo-nx` and switch to the `add-new-test` branch
2. Run `npx nx run example-service:test` and observe the failing test but the exit code of `0`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : linux-x64
   npm    : 8.19.4
   
   nx            : 17.3.1
   @nx/devkit    : 17.3.0
   @nrwl/devkit  : 17.2.7
   @nrwl/tao     : 17.3.1
   typescript    : 4.9.5
   ---------------------------------------
   Community plugins:
   @theunderscorer/nx-semantic-release : 2.10.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@17.3.0
     - @nrwl/devkit@17.2.7
   
   To fix this, run `nx migrate nx@17.3.1`
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

My current work around for this is using `./node_modules/bin/nx` instead of using `npx`

**Comment by Cammisuli** [comment]
I'm terribly sorry about that. When I was testing the fix the last time, I was running nx directly (because I have `./node_modules/.bin` in my PATH env) 

I'll check in the morning with using npx. I suspect it's a similar issue to what was fixed last time. 

For instance if you run nx with `yarn` or `pnpm` you wouldn't get the issue. 

Anyway, I'll look into this further in the morning.
