### ISSUE TITLE
Webstorm unit test plugin

### ISSUE THREAD

**Issue by mmonteiroc** [nrwl/nx#21529]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
We started using Nx in our team. 
We have an Angular+karma+jasmine set up

Some of our members use Webstorm, which allowed us to run / debug karma unit tests in the IDE
Now with NX this is not valid, as this plugin / functionality uses "ng" command.

Would be nice, if you could fork and adapt the plugin for Nx users so that more devs ( as us and others ) could benefit of this productivity tool to the max 

## Motivation
Would encourage users of webstorm tool to move to NX + improve productivity

## Suggested Implementation
Fork a plugin and adaptit to nx cli instead of ng  cli

**Comment by leosvelperez** [comment]
Thanks for the suggestion and request!

Unfortunately, we have no plans to provide our own version of that plugin. This could be requested in the plugin's repository instead https://github.com/JetBrains/intellij-plugins/tree/master/js-karma. It would be way easier for them to add such functionality. Forking the plugin and providing it ourselves comes with maintenance overhead since we'd need to maintain the forked plugin in sync. On top of that, [Karma is deprecated](https://github.com/karma-runner/karma?tab=readme-ov-file#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes) so we don't plan to invest on adding features for it.

**Comment by mmonteiroc** [comment]
Fair enough. I was not aware of such deprecation.
Thanks anyways for the time you spent answering
