### ISSUE TITLE
Update prettier

### ISSUE THREAD

**Issue by AliYusuf95** [nrwl/nx#2159]
## Expected Behavior

Run `nx format:write` to format Typescript 3.7 code containing optional chaining.

## Current Behavior

`error Command failed with exit code 1.`

## Failure Information (for bugs)

Update prettier to [1.19.x ](https://prettier.io/blog/2019/11/09/1.19.0.html) to support TypeScript 3.7

**Comment by ball6847** [comment]
Hi,

Just want to check with you guys, Is there any reason for not shipping prettier 1.19.x  in newly created nx workspace ?

Since angular9 and nx9 were released and it comes with TypeScript 3.7, but the prettier version currently generated in nx workspace is still at 1.18.x which does not seem to support TypeScript 3.7 (but it does in 1.19.x)

For me it now make sense to ship prettier 1.19.x by default in nx workspace to make it fully compatible with TypeScript 3.7.

Related - https://github.com/prettier/prettier/issues/6595
