### ISSUE TITLE
nx/packages /nuxt/ path alias not working. 

### ISSUE THREAD

**Issue by g1ronn1mo** [nrwl/nx#21673]
### Current Behavior

import { useOpenBisStore } from '@/src/composabels/openbisAPI.ts'

When I try to import something with the path variable "@' which at default should point to the root dir, it did not get resolved. 

https://nuxt.com/docs/api/nuxt-config

### Expected Behavior

Get resolved and automatically suggest when typing. 

## Install NX

```
bun add --global nx@latest
```

## Initialize Apps

The main purpose of a [[Nuxt Monorepo]] is to have apps which share:
- Ui components 
- [[Middle-Ware]]
- configuration via [[nuxt.config]]

Nx is a tool winch can help us with building a `monorepo`. It has a VS Code extension for fast interaction with the `NX CLI tool`. To start with the creation of a `monorepo` follow these steps:

```bash
 bunx create-nx-workspace@latest --preset=nuxt
```

This will open a wizzard, where the project name (first app name) and so on, will be ask. 

**To add more Apps**:
1. Open NX Console 
2. click generate
3. search for `@nx/nuxt - application `  in the drop down menu
4. Fill in the form:
	- name:  `app-name`
	- directory: `apps/app-name`

Now, we need to create a shared components lib. A convention is to put all shared libraries in a `libs` folder. A library can be something like a component library, or  a `data library` for accessing an API.

Install the dependencies by running:

```bash
bun i 
```

### Nx Report

```shell
Nothing to report
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by NitroG42** [comment]
I have the same issue because we're trying to integrate nx in an existing project with multiple modules.
If anyone has a workaround, I will take it gladly.

**Comment by Coly010** [comment]
Thank you for bringing this issue to our attention! I want to assure you that I will take a look as soon as I can.

**Comment by NitroG42** [comment]
By the way, the way we hacked around the issue for now (not completly sure it's the same but it looks like it) is to declare paths manually in every tsconfig.lib/.app .json of each module like this:

```json
"compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": [
      "vite/client"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ],
      "@api": [
        "../../common/api/src/main.ts"
      ],
      "@design-system": [
        "../../common/design-system/src/main.ts"
      ]
    }
  },
```
and I think having this in the tsconfig.json of each module too is required:
```json
"compilerOptions": {
     ...
    "baseUrl": "."
  },
```

and of course the base vite.config.ts too:
```json
resolve: {
    preserveSymlinks: true,
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
  },
```

**Comment by Coly010** [comment]
Hi all,

Unfortunately, this issue arises due to a current limitation with Nx's approach to tsconfig paths and how Nuxt handles aliases (which get mapped to tsconfig paths) within Integrated Monorepos.

One workaround is to copy the compilerOptions.paths from .nuxt/tsconfig.json into either your project's tsconfig.json or the workspace's tsconfig.base.json.

Copying it into your project's tsconfig.json would require also copying any compilerOptions.paths defined in the workspace tsconfig.base.json. Consequently, any new paths added to tsconfig.base.json would need to be manually added to your project's tsconfig.json thereafter.
Alternatively, copying it to your tsconfig.base.json would necessitate updating all paths to be relevant to a single project, potentially impacting multiple other projects.
Another option is to use a Package Based Monorepo approach with NPM/Yarn/PNPM workspaces. More details can be found here: [Nx - Integrated vs Package Based](https://nx.dev/concepts/integrated-vs-package-based).

We apologize for any inconvenience caused by this limitation. Given the current constraints, there is no immediate resolution available from our side.

Thank you for your understanding.
