### ISSUE TITLE
Completely changed without proper documentation

### ISSUE THREAD

**Issue by jrwhip** [nrwl/nx#21815]
### Documentation issue

- [ ] Reporting a typo
- [x ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/nx-console/console-generate-command

### Additional context or description

The update to version 17 has butchered the component creation process. The existing documentation is now worthless, offering zero assistance for using the Nx Console to create components. This "update" has taken what was a straightforward task and twisted it into a convoluted mess. It's now more efficient to bypass your tool and create components manually. This represents a monumental regression in usability. Immediate action is required: correct your documentation and revert these changes. The current state is unacceptable and reflects poorly on the decision-making involved.

**Comment by beeman** [comment]
For reference, I created a similar issue [here](https://github.com/nrwl/nx/issues/21791). 

I really hope there will be a (permanent) option to opt out of all the fancy magic. I like to have files represent what they do - kinda the whole idea about having a code base. Too much magic is harmful to DX.

**Comment by MaxKless** [comment]
Hey @jrwhip can you elaborate on what exactly changed for you? Looking at the documentation you linked, it seems like the generate ui still works as described? 
What specific issues are you facing and what pain points would you like to see adressed in the docs?

**Comment by jaysoo** [comment]
I'm guessing this issue is referring to the working directory and `nameAndDirectoryFormat` changes for the component generators?

The best way to create components in a specific directory is to right-click on the directory and access the generate menu item there.

<img width="1050" alt="Screenshot 2024-04-16 at 9 24 11 AM" src="https://github.com/nrwl/nx/assets/53559/b2b2feaf-6e88-4d2f-9035-5b044e530abf">

This would populate the directory for you.

<img width="1933" alt="Screenshot 2024-04-16 at 9 24 27 AM" src="https://github.com/nrwl/nx/assets/53559/57d1a3b2-66da-4d98-b4f4-2a68b5a526ed">

**Comment by MaxKless** [comment]
Hey! I think the changes are documented quite well in https://nx.dev/deprecated/as-provided-vs-derived
I understand that the behaviour here has changed and that can be disorienting. But we've put thought into it and how generators are run is now much more consistent across packages :)
