### ISSUE TITLE
React standalone generation with Nx 18 is completely broken

### ISSUE THREAD

**Issue by DenysVuika** [nrwl/nx#21817]
### Current Behavior

The `react standalone` project is missing all the targets, when generating with Nx 18

### Expected Behavior

The application should be able running standard targets like build/test/lint, etc

### Steps to Reproduce

`npx create-nx-workspace@latest my-app --preset=react-standalone`

The `project.json` file is empty:

```json
{
  "name": "my-app",
  "$schema": "node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "./src",
  "projectType": "application",
  "targets": {},
  "tags": []
}
```

It is not possible running `nx lint`, `nx build` or any command from the `package.json` except `npm start`

### Nx Report

```shell
Node   : 18.19.0
   OS     : darwin-x64
   npm    : 10.2.3
   
   nx (global)        : 18.0.4
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/playwright     : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/vite           : 18.0.4
   @nx/web            : 18.0.4
   typescript         : 5.3.3
```

### Package Manager Version

10.2.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @DenysVuika !

You're `project.json` is intended to have no targets listed since Project Crystal was released.
Some information about Project Crystal:
- https://blog.nrwl.io/what-if-nx-plugins-were-more-like-vscode-extensions-dcdad140ae09
- https://www.youtube.com/watch?v=wADNsVItnsM
- https://nx.dev/concepts/inferred-tasks


If you run the following command:
`nx show project my-app --web`

You'll see the Project Details View which lists the targets available for you to run on your project:
<img width="1175" alt="image" src="https://github.com/nrwl/nx/assets/12140467/41d44f02-868c-4c65-a436-7c105fba1b68">


These can then still be run as usual with `nx targetName`

For example, following your reproduction steps, I created a standalone react workspace and these are the results of running the lint and build commands
<img width="985" alt="image" src="https://github.com/nrwl/nx/assets/12140467/0e01cf43-663a-4cad-830d-9c849cd73573">

**Comment by DenysVuika** [comment]
@Coly010 this is not the case I'm having... all the commands fail with the similar message:

```
 The externalDependency 'vite' for 'my-app:build' could not be found
```

while there's definitely a `vite` dependency there.

manually adding all those targets help, but for sure it's not working out of the box based on my attempts
