### ISSUE TITLE
Make the NX Welcome component import svg and images

### ISSUE THREAD

**Issue by davidearci** [nrwl/nx#21899]
There are many tickets around issues with svgs and images on an nx setup. In the nx-welcome component, svg are used in the dom. It would be nice to have those svgs imported, along with some image, to show the right configuration without workarounds. Atm, following tutorials on nx website, images are NOT working for last nx versions. Having these welcome component using image imports will be really beneficial i think.

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Working examples on image import in the nx-welcome component for react monorepos with remotes

## Motivation
I'm spending already too much time trying to make svgs or images imports work with nx. 

## Suggested Implementation
import { ReactComponent as NxLogo } from '../assets.nxlogo.svg'

remove svgs nodes from jsx

**Comment by FrozenPandaz** [comment]
Hm, I have also seen there are quite a few issues regarding SVGs and React. We will look into and fix those.

However, importing from a different file for the welcome component is not something we're interested in doing. Involving multiple files for the welcome component makes it harder to remove. We like the welcome component because it provides useful information for new Nx users but, eventually you will remove it and start building the application you really want to build.

We have other ways of dogfooding this.. such as with the `nx.dev` site or the graph application. I will ask the team about dogfooding SVG importing there.

I'm going to close this issue as we won't be implementing it for the welcome component but you may see this soon.
