### ISSUE TITLE
Eslintignore under the workspace root will not work with project crystal

### ISSUE THREAD

**Issue by larryro** [nrwl/nx#21988]
### Current Behavior

When we use **project crystal** to lint the project. It can't detect the **eslintignore** file under the workspace root. It will use the root of the project as the root of the executor. If I copy **eslintignore** to the dir of the project, everything work well.
![image](https://github.com/nrwl/nx/assets/5787117/0d571d85-81eb-4f1f-a770-9a76330ce45c)
__

### Expected Behavior

Project crystal should use the workspace root instead of the project root as the root of the executor.

### Steps to Reproduce

1. Use the project crystal to lint the project
2. Create a **eslintignore** file under the workspace root.
3. Run the lint for the project from the NX Console

### Nx Report

```shell
Node   : 20.11.1
   OS     : linux-x64
   pnpm   : 8.13.1
   
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/nest           : 18.0.4
   @nx/next           : 18.0.4
   @nx/node           : 18.0.4
   @nx/playwright     : 18.0.4
   @nx/plugin         : 18.0.4
   @nx/react          : 18.0.4
   @nx/rollup         : 18.0.4
   @nx/storybook      : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-prisma : 5.2.0
   ---------------------------------------
   Local workspace plugins:
         @tale/core/nx
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by PaulACoroneos** [comment]
I have the same issue here. What is the nx recommended path here for having eslintignore file globally apply to all lint package runs while under inferred tasks mode?

**Comment by FrozenPandaz** [comment]
This is because the inferred ESLint tasks are run from the project root rather than the workspace root.

Ultimately, `.eslintignore` was recently deprecated in ESLint in favor of `ignores` in `eslint.config.js`: https://eslint.org/docs/latest/use/configure/ignore. This would be the most recommended method from both Nx and ESLint to configure ignoring files.

Given that's a big change, for the `.eslintignore` file, it's recommended to specify the `ignorePatterns` in `.eslintrc.json` instead.

ESLint only picks up the `.eslintignore` file from the current working directory and it does not cascade (ESLint does not look up to find parent files).

https://eslint.org/docs/latest/use/configure/ignore-deprecated#the-eslintignore-file

However, it does for `ignorePatterns` in `.eslintrc.json` files.. so we would recommend doing that.

https://eslint.org/docs/latest/use/configure/ignore-deprecated#ignorepatterns-in-config-files

I hope that answers your question.
