### ISSUE TITLE
fileReplacements does not work with scss files

### ISSUE THREAD

**Issue by shadow1349** [nrwl/nx#22000]
### Current Behavior

In my production config I have fileReplacements defined because I need to be able to swap out scss files dynamically

```json
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "outputHashing": "all",
          "fileReplacements": [
            {
              "replace": "test/src/theme.scss",
              "with": "config/src/theme.scss"
            }
          ]
        },
```

But I keep getting an error that scss does not conform to some pattern for file replacements. File Replacements should be able to replace any file, I thought.

### Expected Behavior

File replacements should be able to replace any type of file.

### GitHub Repo

https://github.com/shadow1349/nx-filereplacementissue

### Steps to Reproduce

1. Please clone the repo
2. Run npm install
3. Run production build

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                 : 18.0.2
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.3
   @nx/eslint         : 18.0.3
   @nx/workspace      : 18.0.2
   @nx/angular        : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.3
   @nx/playwright     : 18.0.4
   @nx/plugin         : 18.0.4
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   ngx-build-plus : 17.0.0
```

### Failure Logs

```shell
Property 'replace' does not match the schema. 'test/src/theme.scss' should match the pattern '\.(([cm]?j|t)sx?|json)$'.
```

### Package Manager Version

npm - 9.8.1

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is by design and not something imposed by Nx. Note how you're using the Angular CLI `@angular-devkit/build-angular:application` builders to build the application. The restriction comes from that builder's schema. Even if you were to swap it with the Nx-provided `@nx/angular:application` executor, the same restriction would apply because the Nx executors for Angular are wrappers built on top of the Angular CLI builders (providing some extra features).

If you think stylesheets (or other type of files) should be supported by `fileReplacements`, please open a feature request in the Angular CLI repo.

**Comment by shadow1349** [comment]
Sounds good, thank you!
