### ISSUE TITLE
Cannot disable run-many verbose logging in CI

### ISSUE THREAD

**Issue by TheSpyder** [nrwl/nx#22063]
### Current Behavior

When I set `NX_VERBOSE_LOGGING=false` in a CI environment the `run-many` output is still verbose.

### Expected Behavior

Verbose logging should be disabled when the `NX_VERBOSE_LOGGING` variable is set to false, regardless of the other environment state.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. run `export CI=true` to make Nx think it's running in CI
2. confirm that `nx run-many -t build` runs in verbose mode without adding `--verbose`
3. run `export NX_VERBOSE_LOGGING=false` 
4. re-run `nx run-many -t build` and observe the output is still verbose

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 21.6.2
   OS     : darwin-arm64
   yarn   : 1.22.21

   nx (global)        : 18.0.4
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/angular        : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 17.0.1
   @ngrx/effects         : 17.0.1
   @ngrx/entity          : 17.0.1
   @ngrx/router-store    : 17.0.1
   @ngrx/store           : 17.0.1
   @ngrx/store-devtools  : 17.0.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I normally do want `run-many` to be verbose in CI, but I have a situation where it makes the build log too busy and I'd like to suppress the verbose output in that specific scenario.

It's possible other nx commands also force their verbosity in this way, I haven't checked.

**Comment by AgentEnder** [comment]
Hey @TheSpyder - sorry for the long turnaround time here.

What you are seeing is likely the static terminal output rather than verbose being enabled, if verbose was enabled you'd see information about hash calculation and similar. You can try specifying a different output style with --output-style, but the reason we default to something other than the shortened dynamic output on CI is that it doesn't behave well on CI as it relies on moving the cursor in the terminal, which isn't supported by most CI providers.

I'm going to close this out based on that, if you believe that you are seeing verbose logs still feel free to ping here and I'll reopen.

**Comment by TheSpyder** [comment]
@AgentEnder thank you for the details. I don't mind whether it's static or dynamic, I just don't want the full task logs to be emitted. Particularly if the result is cached, but I'd be fine with suppressing all of them.

Is there a way to do that in CI?
