### ISSUE TITLE
Package-based generators doesn't work

### ISSUE THREAD

**Issue by dormeiri** [nrwl/nx#22078]
### Current Behavior

Error when running `nx workspace-generator new-package` after migrating from Nx v15 to v18 on a package-based project.

### Expected Behavior

I can run my generator at v18.

### GitHub Repo

https://github.com/dormeiri/nodejs-package-based-monorepo-template

### Steps to Reproduce

1. Create a pacakge-based monorepo on Nx v15.
2. Create generator.
3. Migrate to Nx v18.
4. Run the generator, get an error.

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-arm64
npm    : 10.2.3

nx          : 18.0.5
@nx/devkit  : 18.0.5
@nrwl/tao   : 18.0.5
typescript  : 5.3.3
```

### Failure Logs

```shell
NX   Cannot find project 'new-package'
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

My files structure looks something like this:

```
./tsconfig.base.json
./nx.json
./package.json
./tools
./tools/tsconfig.tools.json
./tools/generators
./tools/generators/new-package
./tools/generators/new-package/files/...
./tools/generators/new-package/index.ts
./tools/generators/new-package/schema.json
./packages/my-package-1/...
./packages/my-package-2/...
```

**Comment by AgentEnder** [comment]
Hey 👋 - it seems likely that you missed some migrations. Workspace generators were removed in v17 in favor of supporting workspace plugins. Since `workspace-generator` is no longer a valid command, running `nx workspace-generator my-package` is trying to run a target named `workspace-generator` on `my-package`.

See docs here on the transition: https://nx.dev/deprecated/workspace-generators
