### ISSUE TITLE
The `--watch` flag for Cypress e2e no longer supported

### ISSUE THREAD

**Issue by jondotblack** [nrwl/nx#22389]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Docs: https://nx.dev/nx-api/cypress/documents/overview#watching-for-changes-headed-mode

### Additional context or description

The `--watch` parameter appears to be no longer supported.  I believe it is now updated to be `--headed --no-exit`.

**Comment by tranlehaiquan** [comment]
You save my life 👍

**Comment by tranlehaiquan** [comment]
But I got another problem, after exit (Crt + c) that comment the web (project) still be these will not turn off.

**Comment by FrozenPandaz** [comment]
We updated the `e2e` target to run `cypress run` which defaults to being headless and exit once it is done. 

We will be adding a separate `open-cypress` target which will run `cypress open` which will default to `headless` and watch for changes to tests.

Rather than `nx e2e e2e --watch`, it will be `nx open-cypress e2e` which will run `cypress open` within the root of the `e2e` project.

Stay tuned while we work on this.

**Comment by jondotblack** [comment]
> Having the same Issue. It's not the same as `cypress watch` tho. I want the GUI to select, which browser I need to run the tests and to select which tets to run.

from directly within your e2e app directory run the command `npx cypress open`
