### ISSUE TITLE
App Crashing when external remote is not loaded along with remotes in the mono-repo workspace.

### ISSUE THREAD

**Issue by MrVipinVijayan** [nrwl/nx#22403]
### Current Behavior

App crashes with white screen

### Expected Behavior

App should load eventhough one of the remote crashed

### Steps to Reproduce

1.
I have a react mono-repo with 4 remotes.
remotes: [
"remote1",
"remote2",
"remote3",
"external-app": "http://localhost:4300/remoteEntry.js"]
]

external app url is down which causes the whole app to crash.

### Nx Report

```shell
nx global 18.0.7
nx: 18.1.1
rest all : 18.1.1

typescript: 5.3.3
```

### Failure Logs

```shell
Console shows 
Connection refused to http://localhost:4300/remoteEntry.js
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This is expected behavior.

When using static module federation as you are using here, when the application loads, it fetches the `remoteEntry.js` files for each remote, so that it can subsequently load the remote modules when required.

If it cannot find those remotes because they are down, then an error correctly occurs.

If you need some kind of fallback, you can explore the `promise new Promise` syntax to do this.

Documentation on `promise new Promise` syntax: https://webpack.js.org/concepts/module-federation/#promise-based-dynamic-remotes
Potential solution you can implement: https://stackoverflow.com/a/72617755

To use `promise new Promise` support with Nx change your remotes config to:
```
remotes: [
"remote1",
"remote2",
"remote3",
"external-app": "promise new Promise(....)"]
]
```
