### ISSUE TITLE
GitHub action failing when disconnected from Nx cloud

### ISSUE THREAD

**Issue by polyphilz** [nrwl/nx#22444]
### Current Behavior

We use `npx nx` run-many commmands in some of our GitHub actions. For this month, we ran out of credits a bit early, so we got disconnected from Nx Cloud. Unless I explicitly pass in `--skip-nx-cache` to the `npx nx` commands, the actions have started failing because they're not able to connect to Nx Cloud.

### Expected Behavior

In the past, this wouldn't cause the actual process to fail and therefore the Github Action to fail; it just resorted to not connecting to the cloud and running locally instead without the cache.

### Steps to Reproduce

1. Make a free Nx account that has no credits available
2. Use some `nx` command in a Github action (like a linter)
3. Don't pass in `--skip-nx-cache`
4. Confirm the action fails

### Nx Report

```shell
N/A (run from CI). On a side note, this still works locally; it's just in the GitHub Action it fails.
```

### Package Manager Version

N/A (`npx nx`)

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

On a side note, this still works locally; it's just in the GitHub Action it fails.

**Comment by StalkAltan** [comment]
Hi @polyphilz and @stefanmo! Sorry for the inconvenience this caused. Allow me to explain.

The "failing in CI" behavior is expected here.

The Nx Cloud CLI was supposed to prompt disabled users of the free plan on how you can be re-enabled, though it appears that right now we are always sending the general-case error message. This is our bad and I'm sorry for wasting your time debugging.

For others who find this issue before we release a hotfix, there are a few options for how to get back in action in CI.

1) Your organization is likely eligible for a free trial of Nx Cloud's Pro plan, which can be activated for free on `cloud.nx.app`.
2) You can add set the `NX_NO_CLOUD` environment variable to `true` in your pipelines, to disable Nx Cloud.
3) You can add `--no-cloud` to your Nx Commands, to disable Nx Cloud.
4) You can remove Nx Cloud altogether, by either:
  a) Removing the `nxCloudUrl` and `nxCloudAccessToken` properties from your `nx.json`, if on Nx>17, or
  b) Changing your task runner to `nx/tasks-runners/default`, and removing the `accessToken` and `url` properties from your `nx.json`, if on Nx<17.

Hopefully this helps, and once again, sorry for the runaround while debugging. I am going to close the issue as the actual behavior mentioned is intentional.
