### ISSUE TITLE
Generating package.json and pruned lockfile for webpack executor stopped working

### ISSUE THREAD

**Issue by meeroslav** [nrwl/nx#22486]
> I have a newly generated project in 18.1.2 with the added `"generatePackageJson": true` in the project.json
> 
> here is public reproduced project https://github.com/adrian-goe/nx-generate-packagejson
> 
> The expectation would be to have a package.json in the dist/apps/demo after build step. 
> 
> Edit:
> Maybe its a separate issue, as the step does not crash, but it also does not generate one...

_Originally posted by @adrian-goe in https://github.com/nrwl/nx/issues/21651#issuecomment-2012540558_

**Comment by SirPhemmiey** [comment]
Hey @meeroslav, see a related issue [here](https://github.com/nrwl/nx/issues/22481). 

I upgraded to the latest webpack and i thought it worked but i found out that it was working because `yarn.lock` was removed from `.nxignore` file. 

But the problem is that if i don't put `yarn.lock` in `.nxignore` then [this](https://github.com/nrwl/nx/issues/15116#issuecomment-1535260119) issue will reoccur when you already suggested an alternative [here](https://github.com/nrwl/nx/issues/15116#issuecomment-1535260119)

**Comment by meeroslav** [comment]
@SirPhemmiey these two issues are not related. But thank you for opening the second issue. 

We will look into it as soon as possible.

**Comment by jaysoo** [comment]
More info from @meeroslav:

If you set `generatePackageJson: true` on `NxWebpackPlugin` then the package.json and lockfile generate, but setting it on the executor options in `project.json` does not work. There is likely an issue with defaults from `NxWebpackPlugin` overriding the executor options.

The options  are normalized here: https://github.com/nrwl/nx/blob/master/packages/webpack/src/plugins/nx-webpack-plugin/lib/normalize-options.ts#L51

And the generate package json plugin is added here: https://github.com/nrwl/nx/blob/master/packages/webpack/src/plugins/nx-webpack-plugin/lib/apply-base-config.ts#L314-L316
