### ISSUE TITLE
"nx run-many" does not display lint warnings

### ISSUE THREAD

**Issue by tuffz** [nrwl/nx#22501]
### Current Behavior

When I run `nx run-many -t lint` I get no lint warnings, but when I run the projects individually I get warnings.

![Screenshot 2024-03-25 at 20 32 04](https://github.com/nrwl/nx/assets/2077427/c59230cc-d563-4232-a16e-0e94715d7b59)

### Expected Behavior

When I run `nx run-many -t lint` the lint warnings are displayed directly so that I don't have to run the projects individually to see the warnings.

### GitHub Repo

https://github.com/tuffz/nx-lint-warning-issue

### Steps to Reproduce

1. `nx run-many -t lint && nx run nx-lint-warning-issue:lint && nx run shared-ui-img:lint`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.0
OS     : darwin-x64
npm    : 10.2.4

nx (global)        : 18.0.8
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/cypress        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/next           : 18.1.2
@nx/react          : 18.1.2
@nrwl/tao          : 18.1.2
@nx/web            : 18.1.2
@nx/webpack        : 18.1.2
typescript         : 5.4.2
---------------------------------------
Community plugins:
@jscutlery/semver : 5.2.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This is intentional, we have a `dynamic` [`outputStyle`](https://nx.dev/nx-api/nx/documents/run-many#outputstyle) option here which is default on local dev environments.

`nx run-many -t lint --outputStyle static` will show the full logs.

It's set to `static` in CI environments so the output will be there.

In addition, if you have Nx Cloud enabled, the Nx Cloud link after running the command will have the full command logs there:
https://staging.nx.app/runs/a2SbJ3Ztyf
