### ISSUE TITLE
Tutorial Step4 wrong sample source

### ISSUE THREAD

**Issue by ksakae1216** [nrwl/nx#2251]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

pass test

## Current Behavior

fail test

## Failure Information (for bugs)

rerun test, Assertion fail is "expected 0 to equal 2".

app.component.ts:
fail -> "todos: Todo[] = [];"
pass -> "todos: Todo[] = [{ title: 'Todo 1' }, { title: 'Todo 2' }];"

**Comment by FrozenPandaz** [comment]
Hi @ksakae1216,

Thank you for reporting this issue. Do you mind providing a URL where you noticed this issue?

**Comment by ksakae1216** [comment]
@FrozenPandaz,

URL is below.
https://nx.dev/angular/tutorial/04-connect-to-api

**Comment by FrozenPandaz** [comment]
Sorry, I think this might be a bit confusing and it's not as simple as having the wrong source.

Step 4 of the tutorial intentionally breaks the functionality of the application by prematurely connecting it to an API which will be created in Step 5. The test you mentioned should in fact fail. Would it be less confusing if Step 4 and Step 5 were swapped so that the API is created first and the frontend is connected to it afterwards so that the test doesn't fail?

**Comment by ksakae1216** [comment]
@FrozenPandaz ,

I was misunderstanding.
After checking again, there was no problem, Sorry.

**Comment by FrozenPandaz** [comment]
No worries. Closing this issue :)
