### ISSUE TITLE
Changing the version of an eslint-plugin package should invalidate the cached lint results

### ISSUE THREAD

**Issue by daiscog** [nrwl/nx#22664]
### Current Behavior

After installing a new version of `@whatever/eslint-plugin` running `nx run-many -t lint` reuses the cached results of previous lint runs.

### Expected Behavior

A cache miss should occur because the inputs for the operation (the lint rules) have changed.

Even when configuring the targetDefaults in nx.json as follows, we still get a cache hit:

```json
{
  "targetDefaults": {
    "@nx/eslint:lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        {
          "externalDependencies": ["eslint", "@whatever/eslint-plugin"]
        }
      ],
      "cache": true
    }
  }
}
```

### Steps to Reproduce

Where `@whatever/eslint-plugin` is an externally-managed package that exports some eslint rules or eslint configs which have changed between versions:

```
nx run-many -t lint
npm i -D @whatever/eslint-plugin@latest
nx run-many -t lint
```

### Nx Report

```shell
Node   : 20.12.0
OS     : darwin-x64
npm    : 10.5.0

nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/jest           : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/angular        : 18.1.3
@nx/cypress        : 18.1.3
@nx/devkit         : 17.3.2
@nx/eslint-plugin  : 18.1.3
@nrwl/tao          : 18.1.3
@nx/web            : 18.1.3
@nx/webpack        : 18.1.3
nx-cloud           : 18.0.0
typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Current workaround is to run with `--skip-nx-cache` after installing the new version of the eslint plugin pacakge and fix any errors reported.

**Comment by FrozenPandaz** [comment]
This will be fixed by the new ESLint flat configs which will import plugins via JS. Nx will recognize this and draw the dependency.

For the `.json` files, Nx does not draw dependencies based on the plugins specified. It's a bit late to add it now since the JSON config files will be deprecated soon.

https://eslint.org/docs/next/use/configure/configuration-files#using-a-shareable-configuration-package

I'm going to close this issue because it will be solved once we moved to the new config and does not need to be acted on separately.
