### ISSUE TITLE
Cannot Convert an AngularCLI project on Windows

### ISSUE THREAD

**Issue by pgrm** [nrwl/nx#237]
I installed the dependencies via `yarn add --dev @nrwl/schematics`

When I afterwards run `ng generate workspace mycurrentapp --collection=@nrwl/schematics` I get the error

````
Error: EPERM: operation not permitted, rename '...\src' -> '...\apps\mycurrentapp\src'
````

I tried it in bash on windows and got a similar error

````
Error: EACCES: permission denied, rename 'src' -> 'apps/mycurrentapp/src'
````

**Comment by abnersouza** [comment]
@pgrm I thought the same was happening on a mac, but did the migration today, from my CLI project to Nx using the following:

npm install --save-dev @nrwl/schematics
ng generate workspace mycurrentapp --collection=@nrwl/schematics

I think is really an issue in Windows, because my friend using Win10 cant make it work as well

**Comment by ph55** [comment]
Need close apps that using your project directory (even with administrator).
Closing editor (WebStrom) solved the issue in my case.

**Comment by ThomasBurleson** [comment]
Closing as not an issue w/ 0.8.0 release.

**Comment by dpsthree** [comment]
I just ran into this today with v1.0.0 of @nrwl/schematics

**Comment by noelmace** [comment]
@dpsthree This is most likely an issue with node on Windows, not Nx, especially since the file access is here handled by schematics. I run into this kind of issue a lot on my work computer, but nothing that closing VS Code and any other app using this files, or, as a last resort, a good old (yurk) "run as administrator", won't fix. Sometime, running ``node <your-script>`` from the powershell console (instead of the node_modules/.bin script from git bash) helps.
