### ISSUE TITLE
Project "api" not support command serve

### ISSUE THREAD

**Issue by devjack-front** [nrwl/nx#2446]
I'm creating a project using nest, and when execute the command ng serve api (api is a nest project) not work

Comands
#Add nest 
ng add @nrwl/nest

#Create a project api (ok)
ng g @nrwl/nest:app api --frontendProject=booking

#Should serve api project
ng serve api

Error returned: An unhandled exception occurred: Project 'api' does not support the 'serve' target.

**Comment by skoblenick** [comment]
The same is true for `ng build api` and `ng test api` per the documentation here https://nx.dev/angular/tutorial/05-add-node-app

**Comment by skoblenick** [comment]
I found the reason for the above error was due to me adding a directory name when prompted for:

`? In which directory should the node application be generated? `. 

I didn't realize this nests the `api` directory in a subdirectory. So if you provide anything to the prompt you need to add `<user-entered-prompt-value>-api` as part of your serve, build or test command. You can check the name of the expected script command name in your `nx.json`.

**Comment by juristr** [comment]
Hey @skoblenick 👋 

yes, you're right. The directory param is meant to nest things within apps/libs. Usually for instance if you use an Nx workspace, you may have related libraries. Say you have an app feature that handles contacts, you may want to have a nesting like

```
apps
libs
  | - contacts
       |- data-access
       |- feature-contact-list
...
```

So when generating a new library for "contacts" you'd pass in the `--directory=contacts` property. Since that type of nesting is not allowed in the `angular.json`, all projects there are "dasherized", meaning they will be named `contacts-data-access`, `contacts-feature-contact-list` etc.

The best way to debug these kind of issues is to open the `angular.json` (or `workspace.json`) and see what project key got assigned to the generated project.

I'm closing this issue as it seems to be solved. Feel free to open another one if you have any questions
