### ISSUE TITLE
NEXT JS: nx build myNextJsApp doesn't export assets stored in /public folder

### ISSUE THREAD

**Issue by asherccohen** [nrwl/nx#2474]
# Prerequisites

- [x ] I am running the latest version
- [ x] I checked the documentation (nx.dev) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Running nx build myNextJsApp creates build artifacts including assets from /public folder.

## Current Behavior

Running nx build myNextJsApp and next start loads the app but assets are not in the built folder.

**Comment by asherccohen** [comment]
UPDATE:

I am closing this since I misunderstood how mapping to /public folder works.
I assumed that /public folder would be copied in .next folder (making them part of the artifacts.
Instead these are simply referenced, by this I mean that the minimum structure of your projectto be deployed on a hosting platform/server is:

root
- .next
- public
- package.json
- node_modules

This is somehow different from usual webpack configuration I'm aware of but reduces build time, I guess.

**Comment by xeodou** [comment]
I come from a Google search. I got the same issue with my monorepo + Next.JS. The `nx` will run the command in the app's folder, so it will search all the public assets under `apps/your_app/public/**/*`. 
Basically, to fix this temporary you need to move your public assets to your application folder.

**Comment by asherccohen** [comment]
Yup. Basically move assets from apps/myNextJsApp/public to dist/apps/myNextJsApp/public.
I think that only nx export actually moves the assets correctly.

**Comment by xeodou** [comment]
Yes. Unless next.js support merge different public assets.  Another hack solution right now would be you can manually move the assets from one place to another. You can find the right buildId in the `BUILD_ID` file.

**Comment by stramel** [comment]
Just ran into this issue as well.

**Comment by dotDeeka** [comment]
I just ran into this today as well.

Could this be fixed by adding the copy-webpack-plugin to the nx build builder, to copy `apps/<project-name>/public` to `dist/apps/<project-name>/public` ?

**Comment by stramel** [comment]
This is still an issue AFAICT

**Comment by vsavkin** [comment]
Sorry. The issue was marked by mistake. I removed the label.

**Comment by fakeplayerr** [comment]
Bump!

I also have the same issue.

I just tested with a new app

`npx create-next-app`

i copied some files in /public folder

like 

/public/robots.txt
/public/sitemap.xml

then i ran

`npm run build`

`npm start`

when i go to [(http://localhost:3000/sitemap.xml)]

i receive a 404 error.

i tried a lot of things and nothing worked, images as well, i went with next-images for them because nothing in the public folder gets copied to the build, not even the favicon

I tried on docker too,
same issue, here is the docker file. yarn and npm are the same so i don't think that is the problem

`###
# Build stage
###
FROM node:12-alpine AS builder
WORKDIR /build

COPY package.json yarn.lock ./
RUN yarn

COPY . .
RUN yarn build
#&& rm -rf .next/cache

###
# Exec Stage
###
FROM node:12-alpine
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn --production

COPY --from=builder /build/.next .next
COPY next.config.js .
RUN mkdir pages

CMD ["yarn", "start:production"]`

**Comment by jaysoo** [comment]
The assets are now copied from `app/[name]/public` to `dist/apps/[name]/public` and should be served correctly now.

**Comment by turi4200** [comment]
happened to me today
