### ISSUE TITLE
[tslint] deep imports into libraries are forbidden (nx-enforce-module-boundaries)

### ISSUE THREAD

**Issue by shawnrmoss** [nrwl/nx#252]
I generated a new library in a new workspace and tried to import it into my app.

I get the above linting error when trying to import the lib into an app 
import { MaterialModule } from '@myproject/material/src/material.module';

Any ideas what Im doing wrong

**Comment by aleho70** [comment]
What is reason, how it shall be in correct way? I have same problem, and  in nx-example is the same problem

**Comment by jdk339** [comment]
Still getting this issue with the following line:

`
import { DatabaseService } from '@my-products/database/src/database.service';
`

Any ideas?

**Comment by jdk339** [comment]
As _always_ happens when I ask people questions, I found the answer myself. I just added 
`export * from './src/database.service';`
to my index.ts of the lib

**Comment by aire-con-gas** [comment]
@jdk339 I'm finding my linter still complaining about `import of apps are forbidden` following your advice. I also updated the `angular.json` file and set the `projectType` to `library` but to no avail. Any thoughts?

**Comment by ThomasBurleson** [comment]
@here - Here is a brief explanation:

This issue happens when you are using (aka importing) an external library into some source module and the import path by-passes the barrel (`index.ts`); by using `/src/` or `/src/lib/` as part of the import path.

The goal of the *barrel* is to define the **public** API of the library. Anything else is non-public, considered private/hidden and should NOT be directly accessed.

For libraries with source that wants to import files from inside the same lib, you should **always** use relative path imports.

**Comment by ThomasBurleson** [comment]
@aire-con-gas - 

*  apps can never import other apps
*  libs can never import apps
*  apps can only import libs
*  libs can import libs
