### ISSUE TITLE
npx create-nx-workspace@latest not working

### ISSUE THREAD

**Issue by crissxross** [nrwl/nx#2563]
- [x] I am running the latest version - N/A - I am attempting to
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

To be able to create a Nx workspace with global @angular/cli 9.0.3 installed using the command:
npx create-nx-workspace@latest [my-name].

## Current Behavior

It fails to create a Nx workspace.

## Failure Information (for bugs)

See failure logs below.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest repro-workspace
2. Failed
3. Also tried: 
sudo npm install -g @nrwl/schematics@9.0.3
But it could not find @nrwl/schematics@9.0.3 (see failure logs below).

### Context

Please provide any relevant information about your setup:

Angular CLI: 9.0.3
Node: 12.6.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.3
@angular-devkit/core         9.0.3
@angular-devkit/schematics   9.0.3
@schematics/angular          9.0.3
@schematics/update           0.900.3
rxjs                         6.5.3

npm version 6.13.7

### Failure Logs

npx create-nx-workspace@latest criss
npx: installed 180 in 9.092s
? What to create in the new workspace empty             [an empty workspace]
? CLI to power the Nx workspace       Angular CLI  [Extensible CLI for Angular applications. Recommended for Angular projects.]
Creating a sandbox with Nx...
(node:10565) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error @angular-devkit/core@9.0.3: The engine "yarn" is incompatible with this module. Expected version ">= 1.13.0".
error An unexpected error occurred: "Found incompatible module".
(node:10521) UnhandledPromiseRejectionWarning: Error: Command failed: yarn install --silent
    at checkExecSyncError (child_process.js:623:11)
    at Object.execSync (child_process.js:659:15)
    at createSandbox (/Users/christine/.npm/_npx/10521/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:317:21)
    at /Users/christine/.npm/_npx/10521/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:75:36
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:10521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

~ sudo npm install -g @nrwl/schematics@9.0.3
Password:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/schematics@9.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

## Other

Any other relevant information that will help us help you.

**Comment by vsavkin** [comment]
Thank you for submitting the issue. Going to track the progress of it here: https://github.com/nrwl/nx/issues/2326

**Comment by alxizr** [comment]
hi, 
i had the same issue
these are the steps i took to fix it:

- update [node ](https://nodejs.org/en/) to latest version (14 at the moment)
- uninstall yarn globally (npm uninstall -g yarn)
- clean cache and verify ( npm cache clean --force && npm cache verify  )
- restart my machine (win 10 pro - shutdown /r /f /t 0)

best of luck

**Comment by sjcrisme** [comment]
> hi,
> i had the same issue
> these are the steps i took to fix it:
> 
> * update [node ](https://nodejs.org/en/) to latest version (14 at the moment)
> * uninstall yarn globally (npm uninstall -g yarn)
> * clean cache and verify ( npm cache clean --force && npm cache verify  )
> * restart my machine (win 10 pro - shutdown /r /f /t 0)
> 
> best of luck

tryed all this at win 10 twice 
also install latest yarn , node 12 , node v14.2.0
don't work :(

**Comment by M0Sharif** [comment]
I did `npm install -g create-nx-workspace` and that worked

**Comment by sjcrisme** [comment]
> > hi,
> > i had the same issue
> > these are the steps i took to fix it:
> > 
> > * update [node ](https://nodejs.org/en/) to latest version (14 at the moment)
> > * uninstall yarn globally (npm uninstall -g yarn)
> > * clean cache and verify ( npm cache clean --force && npm cache verify  )
> > * restart my machine (win 10 pro - shutdown /r /f /t 0)
> > 
> > best of luck
> 
> tryed all this at win 10 twice
> also install latest yarn , node 12 , node v14.2.0
> don't work :(

I remove yarn what was installed to window(not by npm). Install lates version and all works fine.
but have another problem with console :)

**Comment by jbeckton** [comment]
Broken for me too, maybe Yarn was not such a good idea after all? Maybe allow us to choose which package manager to use?

**Comment by jbeckton** [comment]
I guess I won't be able to use NX...

Jesses-MacBook-Pro:DigitalResponseMarketing Jesse$ npx create-nx-workspace@latest --unhandled-rejections=strict
npx: installed 193 in 11.359s
? Workspace name (e.g., org name)     drms
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? CLI to power the Nx workspace       Nx           [Recommended for all applications (React, Node, etc..)]
? Use the free tier of the distributed cache provided by Nx Cloud? No  [Only use local computation cache]
Creating a sandbox with Nx...
(node:12218) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
error @angular-devkit/core@10.0.8: The engine "yarn" is incompatible with this module. Expected version ">= 1.13.0".
error Found incompatible module
(node:12204) UnhandledPromiseRejectionWarning: Error: Command failed: yarn install --silent
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createSandbox (/Users/Jesse/.npm/_npx/12204/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:332:21)
    at /Users/Jesse/.npm/_npx/12204/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:84:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lujakob** [comment]
My problem was `yarn global list` revealed a deprecated "@angular/cli@6.0.3" - I updated the the latest and it worked.
