### ISSUE TITLE
NX_TASK_TARGET_PROJECT is not exposed in NX 19

### ISSUE THREAD

**Issue by vcardins** [nrwl/nx#26023]
### Current Behavior

Until version 18, I relied on the env var `NX_TASK_TARGET_PROJECT` to set my router basename, however on upgrading to nx 19 it is not available. 

### Expected Behavior

The `NX_TASK_TARGET_PROJECT` var should be available from `process.env`

### Steps to Reproduce

1. Migrate to nx 19
2. Start up a demo app
3. Type somewhere: `console.log(process.env.NX_TASK_TARGET_PROJECT)`
4. Nothing is logged

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
yarn   : 1.22.19

nx                 : 19.0.8
@nx/js             : 19.0.8
@nx/jest           : 19.0.8
@nx/linter         : 19.0.8
@nx/eslint         : 19.0.8
@nx/workspace      : 19.0.8
@nx/cypress        : 19.0.8
@nx/devkit         : 19.0.8
@nx/eslint-plugin  : 19.0.8
@nx/playwright     : 19.0.8
@nx/react          : 19.0.8
@nx/storybook      : 19.0.8
@nrwl/tao          : 19.0.8
@nx/vite           : 19.0.8
@nx/web            : 19.0.8
@nx/webpack        : 19.0.8
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/storybook/plugin
```

### Package Manager Version

1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This is related to the security fix here: https://nx.dev/blog/2024-05-08-nx-19-release#breaking-change-updating-bundled-environment-variables-to

@jaysoo do you have any guidance for how to pass this information into the build?

**Comment by vcardins** [comment]
@jaysoo Any idea?

**Comment by myownsumm** [comment]
same thing for me. no variables passed into `process.env` from `.env` file:
* NX updated to 19.1.0
* react 18.3.1
* @nx/vite 19.1.0

**Comment by vcardins** [comment]
@myownsumm Are you suggesting the the env var `NX_PUBLIC_TASK_TARGET_PROJECT` is available during build time? Could you confirm that?

**Comment by NicolasBelliard** [comment]
Hello!
Is there any news about this subject?

I made some test on this test project: https://github.com/NicolasBelliard/nx-version-19

It looks like the `NX_PUBLIC_TASK_TARGET_PROJECT` or `NX_PUBLIC_TASK_TARGET_PROJECT` are not taking into account in the build time or when you are running the project with the nx serve command.

**Comment by jaysoo** [comment]
Like Jason said, this is a intentional change. There are tokens and secrets that are prefixed as `NX_`, and those were being bundled into browser code by accident in some projects if someone does `console.log(process.env`) for example. Using `NX_PUBLIC_TASK_TARGET_PROJECT` is not going to work as Nx does not set that variable.

Let me see if there's a workaround for what you're trying to do @vcardins

**Comment by jaysoo** [comment]
@vcardins I suggest one of the approaches outlined here: https://github.com/jaysoo/react-basename

If you are using Webpack (or some other bundler), then you can define any `process.env` variables needed. Otherwise just hardcoding it per-app works as well.

Since this isn't a bug, I will close the issue. If you run into any other problems please open a new issue.

**Comment by vcardins** [comment]
@jaysoo Thanks for the response. Respectfully, I disagree this is not a bug, once it was a previous NX version (18) available resource and it's no longer available, this configure to me a breaking change.  I accept it will no longer be available and I should find workarounds, however I still believe situation like this can be avoided in the future.
