### ISSUE TITLE
Unused '@ts-expect-error' directive error when set strict to false

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#26156]
### Current Behavior

I created an Angular application using the monorepo preset. After changing the `strict` option to `false`, I encountered an error when running the tests:

```
ng-lib/src/test-setup.ts:1:1 - error TS2578: Unused '@ts-expect-error' directive.

// @ts-expect-error https://thymikee.github.io/jest-preset-angular/docs/getting-started/test-environment
```

Here is a repository to reproduce the issue: [nx-ng-strict-bug](https://github.com/wizardnet972/nx-ng-strict-bug)

### Steps to Reproduce

1. Create a new NX workspace:
   ```bash
   npx create-nx-workspace@latest nx-ng-test-strict-bug

   NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

   ✔ Which stack do you want to use? · angular
   ✔ Integrated monorepo, or standalone project? · integrated
   ✔ Application name · nx-ng-test-strict-bug
   ✔ Which bundler would you like to use? · esbuild
   ✔ Default stylesheet format · scss
   ✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
   ✔ Test runner to use for end to end (E2E) tests · playwright
   ✔ Set up CI with caching, distribution and test deflaking · skip
   ✔ Would you like remote caching to make your build faster? · skip

   NX   Creating your v19.1.0 workspace.

   ✔ Installing dependencies with npm
   ✔ Successfully created the workspace: nx-ng-test-strict-bug.
   ```

2. Add an Angular library:
   ```bash
   yarn nx g @nx/angular:lib ng-lib --buildable
   ```

3. Run build and test:
   ```bash
   yarn nx run-many -t build,lint,test --all
   ```

   Everything works fine at this point.

4. Change `strict` option from `true` to `false` in `ng-lib/tsconfig.json`.

5. Run the build and test again:
   ```bash
   yarn nx run-many -t build,lint,test --all
   ```

   The test fails with the following error:
   ```
   ng-lib/src/test-setup.ts:1:1 - error TS2578: Unused '@ts-expect-error' directive.

   1 // @ts-expect-error https://thymikee.github.io/jest-preset-angular/docs/getting-started/test-environment
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Test Suites: 1 failed, 1 total
   Tests:       0 total
   Snapshots:   0 total
   Time:        0.85 s, estimated 1 s
   Ran all test suites.
   ```

Please advise on how to resolve this issue.

### GitHub Repo

https://github.com/wizardnet972/nx-ng-strict-bug

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/playwright     : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin

✨  Done in 2.17s.
```
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jon9090** [comment]
+1

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is expected TypeScript behavior. When you create a new workspace with an Angular application, the application is configured to use strict type-checking by default. In strict mode, the `globalThis.ngJest = ...` line in the `test-setup.ts` file throws a compiler error due to `ngJest` not being defined in the module `globalThis`. The `ngJest` property is something `jest-preset-angular` uses to allow configuring the test environment for Angular. So, for strict mode (what got generated by default), we need to add the `@ts-expect-error` directive to tell the TypeScript compiler that the next line won't actually throw an error at runtime.

By setting `strict` to `false`, you're opting out of the strict mode type-checking, in which case, that line doesn't throw a compiler error anymore. Therefore, TypeScript is now telling you that the directive is no longer needed because the next line doesn't actually throw an error.

As mentioned, this is expected TypeScript behavior. Since the application is generated with strict type-checking, the rest of the code is also generated to comply with that. You can opt-out of strict type-checking when creating a new application by passing the `--no-strict` or `--strict=false` flag to the application generator. When creating a new workspace, this is not configurable. In that case, the same way you manually disabled the strict type-checking, you need to adjust any code that was relying on strict type-checking to be enabled.
