### ISSUE TITLE
nx release version ignore changes to a package when the associated commit comes from the github "squash and merge" command

### ISSUE THREAD

**Issue by Bare1337** [nrwl/nx#26241]
### Current Behavior

When multiple changes are made to a package and are added to the base branch through the "squash and merge" option from github at merge time, launching nx release version on the base branch lead to:
{packageName} 🚫 No changes were detected using git history and the conventional commits standard.
{packageName} 🚫 Skipping versioning "{packageName}" as no changes were detected.

though my commit is respecting the conventional commits standard and directly affect the package.

### Expected Behavior

A commit which respect the conventional commits standard and affect my package should be properly interpreted by nx release version and lead to a correct version compute, whether or not it has been squashed with the github ui command.

### Steps to Reproduce

1.Create a package in an nx workspace and commit your changes => git commit -m "feat: introduce my package"
2.Create a dummy file inside the created package and commit your changes => git commit -m "feat: new package feat"
3.Create a pull request against the base branch from your current branch and merge using the option "squash and merge" from github UI.
4. Launch nx release version command from the base branch containing the commit squashed by github.

### Nx Report

```shell
Node   : 20.9.0
OS     : win32-x64
pnpm   : 8.15.1

nx                 : 18.3.5
@nx/js             : 18.3.5
@nx/jest           : 18.3.5
@nx/linter         : 18.3.5
@nx/eslint         : 18.3.5
@nx/workspace      : 18.3.5
@nx/angular        : 18.3.5
@nx/cypress        : 18.3.5
@nx/devkit         : 18.3.5
@nx/eslint-plugin  : 18.3.5
@nrwl/tao          : 18.3.5
@nx/web            : 18.3.5
@nx/webpack        : 18.3.5
typescript         : 5.4.5
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The issue comes from a conflict between the separator "----" used by github to delimit the squashed commit messages and the separator used there https://github.com/nrwl/nx/blob/7088b09f472bb767d386df73ca0534e09386d7db/packages/nx/src/command-line/release/utils/git.ts#L129 and there https://github.com/nrwl/nx/blob/7088b09f472bb767d386df73ca0534e09386d7db/packages/nx/src/command-line/release/utils/git.ts#L134

In case of a commit squashed from github here is a result example of the prettify log command:

```
----
feat: my feat|{hash}|{author}|{email}
* feat: add lib

* feat: new feat for my lib

* fix: fix prettier and linter issues

---------

Co-authored-by: {authorName}


M       .eslintignore
M       .eslintrc.json
A       .github/workflows/main.yml
```

Because of that format, the split('----') discard changed files completely and nx release version is no longer able to determine if the commit affect any library.

As it seems tough to completely avoid that since people can as well edit the commit format from the UI, we could at least use a different separator or maybe compute a unique separator on the fly.

I'am willing to submit a PR if necessary.

**Comment by NachoVazquez** [comment]
It seems this is what I'm experiencing as well.

**Comment by JamesHenry** [comment]
I'm really sorry for the long delay here folks. One of the separators in question here was already made more unique since the original issue was opened and I have just opened a PR for the other one, the commits separator: https://github.com/nrwl/nx/pull/29261

I believe that's everything we can do from a technical perspective in Nx Release. I might be misunderstanding some of the comments here but it sounds like potentially there are some false expectations so I'll just clarify:

When you squash merge you are intentionally creating a single commit to represent one or more changes. Conventional commits is based on commits, not the changes that went into those commits, so the bump will be based on the single squashed commit. A commit body cannot influence the type of bump it is.

Possibly based on your expectations, it seems you would be better served by a different merge strategy, or splitting your PRs into more granular changes before merging.

Either that, or you could explore using file based versioning, which in Nx Release is called versioning plans: https://nx.dev/recipes/nx-release/file-based-versioning-version-plans#file-based-versioning-version-plans

With this you can control the bumps and changelog entries in a way that is divorced from your commit history.

Thanks again for your patience, I'll close this one once https://github.com/nrwl/nx/pull/29261 lands
