### ISSUE TITLE
Usage of ungh.cc is not documented and potential security issue

### ISSUE THREAD

**Issue by pkuczynski** [nrwl/nx#26311]
### Current Behavior

When releasing with nx with changelog generation it is using [ungh](https://github.com/unjs/ungh) package which queries ungh.cc domain for GitHub username based on the commit author's email address. This is a potential security/privacy issue as this is a third-party API which might harvest users' emails. It's especially undesirable in the enterprise setups.

### Expected Behavior

1. This dependency against 3-rd party API should be well documented.
2. User should be able to completely turn off such email->username resolution without the need to turn off the whole author's section generation
3. User should be able to choose an alternative resolution technique (eg. [github-username](https://github.com/sindresorhus/github-username) package or a custom one)

### Steps to Reproduce

1. Add the example section to your `nx.json` config:

```
    "release": {
        "projects": ["packages/*"],
        "projectsRelationship": "independent",
        "version": {
            "conventionalCommits": true,
            "generatorOptions": {
                "fallbackCurrentVersionResolver": "disk"
            }
        },
        "changelog": {
            "automaticFromRef": true,
            "projectChangelogs": {
                "createRelease": "github",
                "file": false
            }
        }
    },
```

### Nx Report

```shell
Node   : 22.1.0
OS     : darwin-arm64
pnpm   : 9.1.4

nx (global)  : 19.1.1
nx           : 19.1.1
@nx/js       : 19.1.1
@nrwl/tao    : 19.1.1
typescript   : 5.5.0-dev.20240510
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I am happy to provide a PR(s) if proposed expected behaviour is approved

**Comment by FrozenPandaz** [comment]
We can document the dependency.

There is no actual security vulnerability though because `ungh` provides a caching layer on top of Github API so.. anything which is accessible via `ungh` is already accessible via the Github API. So any user-emails harvested via `ungh` could already be harvested via Github's API without `ungh`.

@JamesHenry please correct me if I'm wrong.

**Comment by pkuczynski** [comment]
I don't think you are correct. You are sending committers email addresses to a 3rd party service and you can't guarantee what this service does with the data. It might as well harvest the emails and sell them. For GitHub Enterprise, email addresses might not be publicly available.

For our security officer, this is a huge concern preventing us from using `nx`.

I proposed 2 solutions (points 2 and 3 above) how to overcome this problem. I am also happy to provide a PR for this.

**Comment by Badisi** [comment]
Also a concern for me.

Even if my email comes from a commit info, I explicitly made it private on Github:
`Settings > Emails > Keep my email addresses private`

So I don't want my email to be used anywhere.

---

**Plus**: because my email is private on Github, ungh.cc cannot find me and I end up as plain text in changelogs. Which sucks because I do have a public Github profile...

**Comment by JamesHenry** [comment]
@pkuczynski 

I have created https://github.com/nrwl/nx/pull/26672 to address this.

It has always been possible to create a custom changelog renderer to control the exact nature of your commits being turned into changelog markdown, however, I agree if that it is shame if avoiding this lookup is the only reason someone would need to do that.

Therefore I have added a new default changelog renderer option `mapAuthorsToGitHubUsernames` which will only do anything if `authors` is enabled, but allows for the lookup/matching behaviour to be skipped but still print the author names.

I have also documented the requests made by the default behaviour.

**Comment by JamesHenry** [comment]
@Badisi I am not sure what you mean, ungh.cc is just a cached form of what is available via the GitHub Search API.

The git commit data has an email in it. I went to the first open-source repo on your public GitHub profile and your gmail address is freely available to scrape via `git log`. Setting that email option on GitHub does not update your commit history on your repos.

> Plus: because my email is private on Github, ungh.cc cannot find me and I end up as plain text in changelogs. Which sucks because I do have a public Github profile...

By setting that option, you are explicitly preventing the GitHub Search API from allowing your user to be found via the email in your commit data. There is no way around it if you continue to use your gmail for your commit data but do not allow it to be used as a query to the search API.

However, if you want to update your git commit data to use your anonymized GitHub email address `{USERNAME}@users.noreply.github.com` instead of your gmail:

A) your gmail will stop being added to new commits going forward (it will not be scrubbed from previous commits though naturally)
B) our existing logic will already not perform the ungh.cc lookup, and instead just extract the username directly from that email string: https://github.com/nrwl/nx/blob/ae94ca5e20da8ed70d6d6188958a0d4eaa7f3ec9/packages/nx/release/changelog-renderer/index.ts#L306-L314

Hope that helps!

**Comment by pkuczynski** [comment]
Thank you @JamesHenry! This is for sure useful. However when I set `release.changelog.renderOptions: false`, the calls to `ungh.cc` stopped, and I still see authors properly linked to theirn GitHub profiles in the GH releases. Not sure why and how, but this is how it works atm!

**Comment by Badisi** [comment]
@JamesHenry, I got your point.

It's true that in the context of **GitHub** I chose to anonymize my email (using their settings) but in the context of **Git**, I'm using `SourceTree` which obviously uses my personal email during commits..

Using `{USERNAME}@users.noreply.github.com` as you suggested could be a solution, but I would also like to suggest an improvement to your existing logic:

Currently, you are searching for `email` to retrieve a user but you are neglecting the `name`.
In my case, commit author look like: `Badisi <user@mail.com>`.
It's true that you won't find me with my email (as it is disabled on GitHub) but my name does exists and `https://ungh.cc/users/find/Badisi` does work.

So maybe you could improve the lookup by searching by email first, then by name, and if not found default to name as plain text 😊 ?

**Comment by JamesHenry** [comment]
@Badisi I feel like it's relatively uncommon for folks to have an exactly matching name and username on here, but I am happy to accept a PR to add that behaviour if you would like to submit it.

You could potentially also have it handle cases like mine where my name is my username just minus the spaces (although in my case the email is already resolvable).

I don't think we should keep trying a ton of permutations and slow down the changelog generation, but if you could process the name string to strip all spaces before looking it up on the API (in the case that the email address has already not matched) then I think that would be a decent compromise.
