### ISSUE TITLE
The typecheck target (@nx/js/typescript) adds excluded paths from tsconfig.base.json as invalid filesets (without `{workspaceRoot}`)

### ISSUE THREAD

**Issue by mayrn-techdivision** [nrwl/nx#26521]
### Current Behavior

The @nx/js/typescript plugin adds all excluded paths to it's inputs. For example `"exclude": ["node_modules"]` is turned into the fileset `../../node_modules`. However since filesets have to start with either `{workspaceRoot}` or `{projectRoot}` this is invalid.

The typecheck target from the plugin will result in the following error when being run:
```
 NX   "!../../node_modules" is an invalid fileset.

All filesets have to start with either {workspaceRoot} or {projectRoot}.
For instance: "!{projectRoot}/**/*.spec.ts" or "{workspaceRoot}/package.json".
If "!../../node_modules" is a named input, make sure it is defined in nx.json.
```

### Expected Behavior

The generated fileset is either `{workspaceRoot}/node_modules` or `{projectRoot}/../../node_modules`

### Steps to Reproduce

1. Add the following plugin configuration to nx.json:
```
{
  ...
  "plugins": {
      "plugin": "@nx/js/typescript",
      "options": {
        "typecheck": {
          "targetName": "typecheck"
        },
        "build": false
      }
    },
  },
  ...
}
```
2. Ensure that their are excluded paths in tsconfig.base.json
3. Run `nx typecheck <project>`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 22.2.0
OS     : darwin-arm64
npm    : 10.7.0

nx                 : 19.2.3
@nx/js             : 19.2.3
@nx/jest           : 19.2.3
@nx/linter         : 19.2.3
@nx/eslint         : 19.2.3
@nx/workspace      : 19.2.3
@nx/devkit         : 19.2.3
@nx/eslint-plugin  : 19.2.3
@nx/react          : 19.2.3
@nrwl/tao          : 19.2.3
@nx/vite           : 19.2.3
@nx/web            : 19.2.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/js/typescript
@nx/eslint/plugin
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@nx-tools/nx-graphql-codegen : 1.0.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@mayrn-techdivision We will address this but please note that that plugin is intentionally undocumented right now (and has been since it was quietly introduced).

We are dogfooding it and collaborating with the TypeScript Team to ensure that it will match the best practices they want to promote for TS monorepos, and we are working on some additional tooling to massively ease the burden around maintaining accurate project references.

Therefore, if you do decide to keep using it please be aware that things could change until the point at which we more formally announce and document it.
