### ISSUE TITLE
[Plugin] Enabling Continous Deployments for Serverless infrastructure

### ISSUE THREAD

**Issue by wickstargazer** [nrwl/nx#2670]
Hi,
We have been using Nx since November and is having a grande time using it to develop and streamline our product release!

# Story/Pain Points
Since we are usually releasing onto **serverless architecture**, mostly **Lambda**, we had the need to create our own **schematics** and **builders** to help us do so within the nx workspace itself! 

So we started off with the **Serverless framework** as some of our projects are already utilizing it. First I wrote the plugin not utilizing the nx workspace, then after nx-plugins arrived have refactored it using the nx-plugins (Great work by the way 👍 ). Also added unit-tests to it although i do not complete understand the `e2e` tests yet ☹️  

# Achievement Solutions

At the moment what have been achieved are
* Enabling angular-universal to be deployed through serverless framework
* Enabling node-typescript apis to be deployed through serverless framework.

For angular-universal its mostly enabling express servers to be able to deployed! However I haven't got around to do schematics for the express part yet! But its because we handle a lot of our OpenID logic in express and not in Angular, I will be getting around to that soon! 😄 

We also have the need to spin up some infrastructure before deploying our applications, so I do plan to add several **IAC (Infrastructure as a code)** automation builders into the plugin. Although I do wonder if  we can utilize `Bazel` instead?

**The link to the repository is --> [nx-plugins](https://github.com/flowaccount/nx-plugins)**

# Plans for the upcoming future

I hope it will help someone and also the **plans for the future enhancement of the plugins are**
* Make express deployable to Lambda
* Add templates for other cloud providers
* have some sort of automation builders to build Infrastructure or check them before deploying applications, for the *CD* part of the *CI/CD* formula

I would appreciate the feedbacks as I see you the workspace is growing, tools are popping out and I might be writing duplication over **Bazel** ?

**Comment by Bielik20** [comment]
Hi, I like the idea, I tried your plugin and it worked fine, except for deploy. Still it just feels like a lot of work to basically use nx style builder instead of serverless builtin solution. This is way I decided to go with a simpler serverless based option:

```json
    "test-serverless-app": {
      "root": "apps/test-serverless-app",
      "sourceRoot": "apps/test-serverless-app/src",
      "projectType": "application",
      "prefix": "test-serverless-app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "./tools/src/builders/command-runner:command-runner",
          "options": {
            "command": "sls",
            "args": ["package"]
          }
        },
        "serve": {
          "builder": "./tools/src/builders/command-runner:command-runner",
          "options": {
            "command": "sls",
            "args": ["offline"]
          }
        },
        "deploy": {
          "builder": "./tools/src/builders/command-runner:command-runner",
          "options": {
            "command": "sls",
            "args": ["deploy"]
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/test-serverless-app/**/*.ts"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/test-serverless-app/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    }
```

and my serverless plugins are

```yml
plugins:
  - serverless-bundle
  - serverless-offline
```

I loose some of nx functionalities like replace `environemnt.ts` with `environment.prod.ts` and builder options, but since it is targeted at serverless perhaps it is better to let serverless handle it. My only complaint is that `serverless-bundle` is not very optimal. Perhaps we should focus on creating an nx serverless plugin instead of whole builder abstraction over serverless itself.

---

PS That command runner I am using is basically the one from [Angular's cli builder tutorial](https://angular.io/guide/cli-builder).

**Comment by bmcilw1** [comment]
@Bielik20 can you post your example repo? I'd love to see how you got this working

**Comment by bmcilw1** [comment]
@wickstargazer I've taken a look at your plugin and tried to use it. It looks like there are version conflicts with the latest nrwl, basically it looks like dependencies have not been updated. Are you still maintaining this project?

It would be great if nrwl would adopt such an ability to easily deploy with the serverless framework!

**Comment by wickstargazer** [comment]
Hi! Yes i am maintaining it, although slow but we are as we are using it on our production environment.

We will be releasing the bunch of new fixes soon its under testing and i think what you are referring to is how tsconfig extends the wrong one from the root? It has to be tsconfig.base.json?

**Comment by bmcilw1** [comment]
Ok great! So glad you're still here because I got blocked pretty early on and opened a few issues on that repo. Let's continue the conversation there and I'm happy to help in any way I can. I can't seem to get serveless lambda deployments happening in our nx repo any other way I've tired.

**Comment by Bielik20** [comment]
@bmcilw1 Hi, sorry for late response. I have it setup for my work repository and it is not open source, so I can't show it here. Maybe I will create my own separate repository and share it here, but I can't make any promises. We are still improving our solution and it would be hard to maintain two repositories with similar configurations.

**Comment by Bielik20** [comment]
Hi @bmcilw1, I have managed to find some time. It still needs some testing before releasing, but I am preparing simple plugin to work with serverless. You can take a look at [this commit](https://github.com/Bielik20/nx-plugins/tree/50f0081e5ffbb15365cb7317371a174b29e72322/packages/nx-serverless/src/executors) in my repo. You could event run `nx e2e nx-serverless-e2e` and play with the result yourself - it will be somewhere in `tmp` directory.

**Comment by wickstargazer** [comment]
Hey guys, i am doing a release for v0.5.3 which will fix a lot of deployment in-capabilities and bugs.
appreciate any feedback :)

**Comment by wickstargazer** [comment]
@bmcilw1 @Bielik20 Guys, the 0.5.3 is working well with deploy, nx cache and trimming package.json for each project.

I am currently undergoing the port and removing all imports for workspace only using devkit.
it will enable the plugin to work with the newest version and easy to update.

Would appreciate any inputs on this.

**Comment by Bielik20** [comment]
Thank you for the update, I might look into that 🙇 
For now we are tied with the current implementation though.

**Comment by Bielik20** [comment]
Hello y'all. If anyone is still interested, I have been working on version 2.0 of my serverless plugin. I want to maintain minimal coupling with Nx so that we can easily access all `serverless` features, but I still want it to integrate well, so that stuff like cache and incremental builds work.
To achieve that I decided to go with a very simple sls executor, little more than a wrapper on execute commands and `serverless` plugin that uses Nx internally to compile the code. It supports only `aws` provider at the time.

**I have created PR**: https://github.com/Bielik20/nx-plugins/pull/36
It still needs some things before it is done, mainly:
* https://github.com/nrwl/nx/pull/7538
* (nice to have) https://github.com/nrwl/nx/issues/7616

I would like to hear what do you think. Especially I would like someone from Nx team to look mainly at [this part](https://github.com/Bielik20/nx-plugins/blob/47bf85f5f1b56e245894f43c2e8e812a5b6f9779/packages/nx-serverless/plugin/nrwl/nx-facade.ts#L48). It is kind of dirty but I haven't found a way to execute Nx commands programmatically and slack channel unfortunately wasn't helpful. @vsavkin Maybe you could delegate someone to take a look at it. I would like to work more closely with you guys to deliver something more stable, that integrates well.

You can try alpha release by installing `@ns3/nx-serverless@2.0.0-alpha-serverless-plugin.1`

**Comment by AgentEnder** [comment]
I'm going to close out this issue since its not requesting any additional functionality, feel free to open new issues for plugin functionality that is desired and it can be evaluated as-needed.
