### ISSUE TITLE
run-commands workspace task caching does not function correctly.

### ISSUE THREAD

**Issue by Ben-Barron** [nrwl/nx#26749]
### Current Behavior

The result is only cached and served from the cache upon the 3rd time of running.

### Expected Behavior

Expect the second run to be served from the cache.

### Steps to Reproduce

You only need this `package.json` file to replicate:
```
{
  "name": "test",
  "devDependencies": {
    "nx": "19.3.2"
  },
  "nx": {
    "targets": {
      "cmd": {
        "executor": "nx:run-commands",
        "inputs": [],
        "outputs": ["{workspaceRoot}/hello.txt"],
        "cache": true,
        "options": {
          "commands": ["echo Hello > hello.txt"]
        }
      }
    }
  }
}
```

1. run `npm install`
2. run `npm nx cmd`
3. run `npm nx cmd` again, you would expect the result to be served from the cache, it is not.
4. run `npm nx cmd` again, this time, it is correctly served from cache.

### Nx Report

```shell
N/A, sorry unable to provide.
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The command is updating a file in the workspace root, and the project root is equal to the workspace root. Given that, consider that the hash includes all files under the project root by default.

1st run: hello.txt likely doesn't exist, hash is XXX. Creates hello.txt
2nd run: hello.txt exists and included in hash. Hash is YYY. Recreates hello.txt, but with exact same contents
3rd run: hello.txt exists, its hash is same. Full target hash is YYY. Cache hit.

You can verify this is the behavior you are seeing by replacing `echo Hello > hello.txt` with `echo Hello >> hello.txt`. This will always append to the file, thus always altering its hash, and you'll never get a cache hit.

The fix is to specify file inputs for the target.
