### ISSUE TITLE
can't install nx package using npm

### ISSUE THREAD

**Issue by 0xMALVEE** [nrwl/nx#26760]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/35369563/e8a319bd-e89b-4626-8cf3-c81bcaad594b)

### Expected Behavior

should install

### Steps to Reproduce

1.npm install

### Nx Report

```shell
none
```

### Package Manager Version

npm -v 10.8.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hey! This might be because of the native file cache. Can you try setting [NX_NATIVE_FILE_CACHE_DIRECTORY](https://github.com/nrwl/nx/issues/NX_NATIVE_FILE_CACHE_DIRECTORY) to a folder that is accessible for your user? It might be some permission issues? 
I will work on better surfacing the actual error message to see what's happening here.

**Comment by 0xMALVEE** [comment]
@MaxKless I fixed it, I had to install Visual C++ Redistributable that's why it was not installing.

**Comment by 0xMALVEE** [comment]
but the error message in there was not that usefull maybe you guys can put a error message saying to install c++ Redistributable

**Comment by MaxKless** [comment]
I don't think it's that easy but there is definitely something we can do to make the error message better. Thanks :)
