### ISSUE TITLE
Question: new exclude entry in linter options

### ISSUE THREAD

**Issue by n9niwas** [nrwl/nx#2691]
NX v9.1.0 introduced a new exclude entry in linter options:

```ts
"linterOptions": {
  "exclude": ["!**/*"]
}
```

Related commit says "improve support for mixed linters when using IDEs".

Could you clarify, what's the purpose of adding this exclude?

**Comment by FrozenPandaz** [comment]
Before, we excluded things in `workspace.json` so that running `nx lint` was fast. However, IDE's are not aware of this configuration. This entry is something that linters can pick up from your actual lint config. This means that IDEs can also pick it up. Now, IDEs won't apply more than one linter (for users who use both TSLint and ESLint) to a specific set of files.

**Comment by elvirdolic** [comment]
@FrozenPandaz how does this work with global tslint.json which we extend global entries are ignored then.
global tslint.json
```
  "linterOptions": {
    "exclude": ["**/generated/*.ts", "**/generated/**/*/*.ts"]
  },
```

VS
project tslint.json
```
 "linterOptions": {
    "exclude": ["!**/*"]
  }
```

global entry doesn't work.
