### ISSUE TITLE
Unexpected token when running `nx run [project-name]:nx-release-publish

### ISSUE THREAD

**Issue by ju-Skinner** [nrwl/nx#27045]
### Current Behavior

I have a mono-repo that contains three projects. The first dependent project fails on release with the following error.

```
Something unexpected went wrong when processing the npm publish output
   SyntaxError: Unexpected token 'vite "... is not valid JSON
      at JSON.parse (<anonymous>)
      at runExecutor (/home/runner/work/supreme-waffle/supreme-waffle/node_modules/@nx/js/src/executors/release-publish/release-publish.impl.js:212:37)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async promiseToIterator (/home/runner/work/supreme-waffle/supreme-waffle/node_modules/nx/src/command-line/run/run.js:33:11)
      at async getLastValueFromAsyncIterableIterator (/home/runner/work/supreme-waffle/supreme-waffle/node_modules/nx/src/utils/async-iterator.js:15:19)
      at async iteratorToProcessStatusCode (/home/runner/work/supreme-waffle/supreme-waffle/node_modules/nx/src/command-line/run/run.js:44:29)
      at async handleErrors (/home/runner/work/supreme-waffle/supreme-waffle/node_modules/nx/src/utils/params.js:9:24)
      at async process.<anonymous> (/home/runner/work/supreme-waffle/supreme-waffle/node_modules/nx/bin/run-executor.js:59:28)
 NX   Running target nx-release-publish for 3 projects failed
```

### Expected Behavior

I'd expect the project to publish as it does when running `npm publish` directly.

### GitHub Repo

https://github.com/ju-Skinner/supreme-waffle

### Steps to Reproduce

1. Pull the repo and install the packages.
2. Run `npx nx release`

You can also look at the actions/Continous Deployment in the sample repo

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
npm    : 10.2.4

nx             : 19.4.3
lerna          : 7.4.2
@nx/js         : 19.4.3
@nx/workspace  : 19.4.3
@nx/devkit     : 19.4.3
@nrwl/devkit   : 16.10.0
@nrwl/tao      : 16.10.0
typescript     : 5.4.5
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@16.10.0
  - @nrwl/tao@16.10.0

To fix this, run `nx migrate nx@19.4.3`
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Hi @ju-Skinner, I have not been able to reproduce this issue locally on your repo, so there must be some missing context/environment concerns.

The biggest thing that jumps out at me is 

```
@nrwl/devkit   : 16.10.0
@nrwl/tao      : 16.10.0
```

...from your report. These are ancient and simply should not be there.

As a next step, I strongly recommend fixes a number of unexpected things going on in your `package.json` when it comes to Nx related dependencies:

![image](https://github.com/user-attachments/assets/4d9e7f83-62f8-44f0-bbfc-a10079b0e9b2)

- `@nrwl/` packages should not be used, use the `@nx/` equivalent
- `tao` should not be referenced
- Updating to the latest 19.5.3, because why not!
- Lerna should be on at least v8 with nx 19

Try those things per the screenshot above and redoing your lock file and hopefully the inconsistencies with your packages in your `nx report` will be resolved (and in general the issue you are seeing).

Please feel free to reopen if you complete all of that and are still having issues.

PS the `prepublishOnly` lifecycle that is causing this issue feels a little redundant in your CI setup given you are calling build right before so you could probably get rid of it. I personally prefer to keep modifications of my package files to steps before the publishing stage, but that shouldn't fundamentally be a problem here. Let's see what happens when the deps are fixed up.

**Comment by ju-Skinner** [comment]
Thanks @JamesHenry . I'll give these suggestions a try.
