### ISSUE TITLE
Allow `NEXT_PUBLIC_` environment variables to be recognized the same way as `NX_` variables

### ISSUE THREAD

**Issue by andirsun** [nrwl/nx#27095]
### Current Behavior

I have a mono repo with `React App` + `Next Js` app.
I am trying to upgrade from Next `13.3` to `13.4` and until know I was using `NX_*` variables for both projects, now after I upgrade `Next` to `13.4` and `NX` to `17.3` I am no longer able to use `NX_*` formar because `Next` is not recognizing those environment variables at all.

After I change the prefix from `NX_` to `NEXT_PUBLIC_` it works but now those are not recognized by the `React` project. I have more than 30 env variables and is not an option to have duplicated Env vars just to change the prefix.

### Expected Behavior

Allow `NX` to receive a configuration so `NEXT_PUBLIC_*`  environment variables are recognized by Next and React projects.

### Steps to Reproduce

1. Use a NX 17.3 
2. Create a React project
3. Create a Next 13.4 project
4 Define NEXT_PUBLIC_* variable
5. Run next project (variables will be recognized)
6. Run React project (variable will be not recognized)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin-arm64
   npm    : 9.5.0
   
   nx (global)        : 18.0.3
   nx                 : 17.3.2
   @nx/js             : 17.3.2
   @nx/jest           : 17.3.2
   @nx/linter         : 17.3.2
   @nx/eslint         : 17.3.2
   @nx/workspace      : 17.3.2
   @nx/cypress        : 17.3.2
   @nx/devkit         : 17.3.2
   @nx/eslint-plugin  : 17.3.2
   @nx/next           : 17.3.2
   @nx/react          : 17.3.2
   @nx/storybook      : 17.3.2
   @nrwl/tao          : 17.3.2
   @nx/web            : 17.3.2
   @nx/webpack        : 17.3.2
   typescript         : 5.4.3
   ---------------------------------------
   Community plugins:
   nx-electron : 17.0.1

```
```


### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by ndcunningham** [comment]
Hey, I think this is intended. In Nx 17 we would merge `NX_` defined vars into the `DefinePlugin` so that it is visible in your Next.js app. 
This was not correct per Next.js documentation public env vars should be defined as `NEXT_PUBLIC_` so that you don't accidentally leak sensitive values in your Javascript bundle.

So in your case you probably need to add some sort of scripting where you define your env vars at one location and you modify it based on which project consumes it.

For Next.js you can probably import it inside your next config and add the vars to the `env` property.
Reference https://nextjs.org/docs/pages/api-reference/next-config-js/env
