### ISSUE TITLE
Support for @typescript-eslint/parser v8 for @nx/eslint-plugin

### ISSUE THREAD

**Issue by mathis-m** [nrwl/nx#27303]
### Current Behavior

Peer dependencies of @nx/eslint-plugin are "@typescript-eslint/parser": "^6.13.2 || ^7.0.0"

### Expected Behavior

major version 8 will be supported

### GitHub Repo

n/a

### Steps to Reproduce

1.
n/a

### Nx Report

```shell
n/a
```

### Failure Logs

```shell
n/a
```

### Package Manager Version

n/a

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

n/a

**Comment by JamesHenry** [comment]
This should land in Nx 19.7 by the end of the month, you can follow along with https://github.com/nrwl/nx/issues/27451 which I have created to avoid the multiple duplicates we currently have open.

The WIP PR is getting very close, so stay tuned. It's not easy because of a large differences in ESLint v9 support across ESLint plugins that Nx sets up for you.
