### ISSUE TITLE
Adding Component to UI Library after running Storybook Configuration does not create *.stories.ts file

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#2771]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

After applying the storybook configuration schematic to a library or application future components that are generated should also come with a `.stories.ts` file.

## Current Behavior

`.stories.ts` file is not created

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest workspace` Created an empty workspace
2. `cd workspace`
3. `npm install --save-dev @nrwl/angular @nrwl/storybook @storybook/core`
4. `ng g @nrwl/angular:lib ui`
`ng g @nrwl/angular:application dummy-app` (have to install dummy app to be able to use angular-cli even tho I've created an angular library)
`ng g component skip-link --project=ui --export` Creating first component
5. skip-link.component.stories.ts file is generated

    ```
    ng g @nrwl/angular:storybook-configuration ui
    ? Configure a cypress e2e app to run against the storybook instance? Yes
    ? Automatically generate *.stories.ts files for components declared in this library? Yes
    ? Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure schematic? Yes
    ```

6. no scroll-to-top.component.stories.ts file is generated

    ```
    ng g component scroll-to-top  --project=ui --export
    CREATE libs/ui/src/lib/scroll-to-top/scroll-to-top.component.scss (0 bytes)
    CREATE libs/ui/src/lib/scroll-to-top/scroll-to-top.component.html (28 bytes)
    CREATE libs/ui/src/lib/scroll-to-top/scroll-to-top.component.spec.ts (665 bytes)
    CREATE libs/ui/src/lib/scroll-to-top/scroll-to-top.component.ts (306 bytes)
    UPDATE libs/ui/src/lib/ui.module.ts (420 bytes)
    ```

### Context

```
  "dependencies": {
    "@angular/animations": "9.0.0",
    "@angular/common": "9.0.0",
    "@angular/compiler": "9.0.0",
    "@angular/core": "9.0.0",
    "@angular/forms": "9.0.0",
    "@angular/platform-browser": "9.0.0",
    "@angular/platform-browser-dynamic": "9.0.0",
    "@angular/router": "9.0.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.900.1",
    "@angular/cli": "9.0.1",
    "@angular/compiler-cli": "9.0.0",
    "@angular/language-service": "9.0.0",
    "@babel/core": "7.8.3",
    "@nrwl/angular": "^9.1.4",
    "@nrwl/cypress": "9.1.4",
    "@nrwl/jest": "9.1.4",
    "@nrwl/storybook": "*",
    "@nrwl/workspace": "9.1.4",
    "@storybook/addon-knobs": "5.3.17",
    "@storybook/angular": "5.3.17",
    "@storybook/core": "^5.3.17",
    "@storybook/react": "5.3.17",
    "@types/jest": "24.9.1",
    "@types/node": "~8.9.4",
    "babel-loader": "8.0.6",
    "codelyzer": "~5.0.1",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "jest-preset-angular": "8.0.0",
    "prettier": "1.19.1",
    "ts-jest": "24.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~3.7.4"
  }
```

**Comment by mandarini** [comment]
Hi there @ChazUK ! Thanks for filing this issue!

What you describe is indeed the behaviour the code was designed to do! Running `ng g @nrwl/angular:storybook-configuration LIBRARY-NAME` will indeed generate stories for the existing components. All components that you generate after that will NOT be automatically added to the library's storybook (no new `.stories.tsx`) as you already observed.

The `nx g @nrwl/angular:component component-name` command actually wraps the native Angular CLI's `ng generate component` command (the Angular CLI's `component` schematic), which does not include `.stories.tsx` generation. The feature you are requesting could indeed come in handy in some cases, but it is not planned at the moment.

The [Nx Plugin for Angular](https://nx.dev/angular/plugins/angular/overview) (`@nrwl/angular`), however, does offer the [`stories` schematic](https://nx.dev/angular/plugins/angular/schematics/stories). You can run this command after generating a new component. This schematic will essentially add the new components to the storybook for that library, meaning that it will generate the `.stories.tsx` files that you need!

In your case, since your library name is `ui`, you may run:
```
nx g @nrwl/angular:stories ui
```
and then you will notice the newly generated `libs/ui/src/lib/scroll-to-top/scroll-to-top.stories.ts` file.

Let me know if this worked, or if you have any more questions!

**Comment by ChazUK** [comment]
Thanks for the in depth answer. I’ll use `nx g @nrwl/angular:stories ui` from now on

**Comment by KamalAman** [comment]
This was very surprising the run into. I was definitely expecting stories to be automatically generated with components after the initial setup.

@mandarini can this be turned into a feature request and left open as a feature request?
Are there any generator life-cycle hooks where I can instruct NX to perform after running a generator to manually add in this feature?
