### ISSUE TITLE
namedInputs not respected in package.json for producing correct affected graph

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#27839]
### Current Behavior

Use of named inputs (or `.nx.namedInputs`) in package.json does not affect `affected`. That is, a named input changes, but the project is _not_ affected.

### Expected Behavior

For changes to namedInputs to yield a project into the affected set.

Per https://nx.dev/reference/inputs, `namedInputs` should be usable in package.json, but they don't seem to do anything in the core plugin.

visual ref:

<img width="662" alt="image" src="https://github.com/user-attachments/assets/5f249c7f-18db-4f48-8902-5fce2ea81ba7">

### GitHub Repo

https://github.com/cdaringe/namedInputs-affected-bug-reproduction

### Steps to Reproduce

See the readme. Short n sweet.

### Nx Report

```shell
 WARN  The "workspaces" field in package.json is not supported by pnpm. Create a "pnpm-workspace.yaml" file instead.

 NX   Report complete - copy this into the issue template

Node           : 20.13.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.6.0

nx                 : 19.6.6
@nx/js             : 19.6.6
@nx/jest           : 19.6.6
@nx/linter         : 19.6.6
@nx/eslint         : 19.6.6
@nx/workspace      : 19.6.6
@nx/devkit         : 19.6.6
@nx/esbuild        : 19.6.6
@nx/eslint-plugin  : 19.6.6
@nx/node           : 19.6.6
@nrwl/tao          : 19.6.6
typescript         : 5.5.4
```

### Failure Logs

```shell
n/a
```

### Package Manager Version

pnpm

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Hi @cdaringe , thanks for opening the issue. I think the confusion is that `inputs` and `namedInputs` are used to determine whether a task is cached or not. If nothing in the tasks' inputs have changed, then it will be replayed from cache.

The affected command uses dependencies from the project graph (e.g. `nx graph`). Since there isn't a dependency between `pkg1` and `pkg2`, changes to the latter does not affect the former. You can either use `import` or `require` to form JS dependencies. Of you can add `implicitDependencies` to your `project.json`/`package.json` file.

https://nx.dev/reference/project-configuration#implicitdependencies

**Comment by jaysoo** [comment]
I'll close this as it isn't a bug. If you run into further problems, please open a new issue.
