### ISSUE TITLE
`nx format:write` deletes `tsconfig.base.json` comments

### ISSUE THREAD

**Issue by privatenumber** [nrwl/nx#28484]
### Current Behavior

If my root tsconfig contains comments, running `nx format:write` deletes them.

### Expected Behavior

1. For the comments to be preserved. This is a pretty serious concern because users may lose their work if they run `nx format:write` prior to committing. This is very dangerous.

2. I think this should also be up to the appropriate codebase's formatting rules and Nx shouldn't enforce un-configurable formatting rules. And I believe with Nx 20, there's less emphasis on using tsconfig to resolve peer packages, so this feels unnecessary.

3. If Nx really wants to impose formatting... Formatting is an extremely complex task and it should be delegated to the appropriate tools that have been thoroughly tested. For example, [eslint-plugin-jsonc](https://www.npmjs.com/package/eslint-plugin-jsonc) handles JSON key sorting well while preserving comments.

Also, it should be documented in the [`format:write` docs](https://nx.dev/nx-api/nx/documents/format-write) that it imposes a sorting order to your tsconfig that's unconfigurable.

### Steps to Reproduce

1. Add comments to the root tsconfig file (e.g. `tsconfig.base.json`)
2. Run `nx format:write`
3. Observe that the comments in the tsconfig file get deleted

### Nx Report

Not relevant

### Package Manager Version

N/A

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is happening because of this:
https://github.com/nrwl/nx/blob/1dd401cdc3c34695d2b224ffc2bab8d563da7ce0/packages/nx/src/command-line/format/format.ts#L256-L266

It reads the tsconfig JSON, parses it with a JSONC parser (which doesn't retain comment data), sorts it, and overrides the file.

**Comment by JamesHenry** [comment]
Hi @privatenumber, I'm happy to learn that you are using Nx! I'm personally grateful for your hard work on `tsx`.

Sadly, we just missed the boat on Nx 20, so we can't change this behaviour for now, but I have opened a PR to add a flag for you to allow you to disable the sorting.

For full context, in large workspaces with lots of contributors, having the sorting in place helped cut down on merge conflicts _a lot_ which helps enterprises ship faster, that's why we added this capability in the first place many years ago.

I agree with you, though, that now that compilerOptions.paths will not be emphasized for as many workspaces, it makes sense to be able to toggle this off, and likely make it opt in instead of opt out in v21.

**Comment by JamesHenry** [comment]
I'd love to connect directly to allow for a tighter feedback loop (from Nx -> tsx/other packages you might work on, and you -> Nx), maybe you could add me via the Nx Discord if you have a Discord account: https://go.nx.dev/community

**Comment by privatenumber** [comment]
@JamesHenry

(Sorry for the late response—was on a business trip)

Thanks for the super fast turn around! Really appreciate the careful explanation and support 🙏

And yes, happy to connect! I just added you on Discord & X. We're using Nx at Square so you can expect more questions from me in the future :)
