### ISSUE TITLE
The nx release command doesn't accept the --otp CLI option

### ISSUE THREAD

**Issue by SokratisVidros** [nrwl/nx#28996]
### Current Behavior

Running `nx release --otp` returns an `Unknown argument: otp` error. As a result, the user is forced to run nx `version`, `changelog`, and `release`subcommands independently.

### Expected Behavior

The expected behavior is for `nx release` to allow the specification of CLI arguments for each subcommand. That is `--otp` to be passed directly to the `publish` subcommand. 

Since other subcommand CLI options have the same name, it is expected for the CLI options to apply to all subcommands. For example, passing `--first-release` should apply to `version`, `changelog`, and `publish.

### Steps to Reproduce

1.In an NX powered monorepo try `pnpm nx publish --otp 123456`.

### Nx Report

```shell
Node           : 20.14.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.11.0

nx                 : 20.1.2
lerna              : 5.6.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/devkit         : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/plugin         : 20.1.2
nx-cloud           : 19.1.0
typescript         : 5.6.2
---------------------------------------
Local workspace plugins:
         @novu/automation
```

### Failure Logs

```shell

```

### Package Manager Version

pnpm@9.11.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Hi @SokratisVidros, I would recommend:

```sh
nx release --skip-publish # or let it prompt you and say no
nx release publish
```

The versioning and changelog steps are potentially quite involved when optionally resolving versions from custom registries or manually editing changelogs in an interactive editor is done, so by the time OTP would be consumed it could have easily expired.

In general it is not a design goal of `nx release` to support all options for all subcommands, because that would scale horribly. `--first-release` is not a good comparison because it genuinely applies to multiple subcommands, `--otp` is specific to only publishing.

The alternative recommendation I would have is creating a release.js/release.ts script which you invoke with node/ts-node/tsx etc which leverages our first class programmatic API. You could then take in an --otp arg to your custom script and control how it is passed to `await releasePublish({ otp: '...', ... })`

Here is an example of using the programmatic API: https://nx.dev/features/manage-releases#using-the-programmatic-api-for-nx-release

**Comment by SokratisVidros** [comment]
James, thanks for the quick reply.

Indeed, the CLI API scalability can be challenging if you support all options. I did a quick pass on the current CLI arguments, and the common ones should apply across three commands, but I agree with the direction.

We were planning to use the programmatic API regardess, so we will just do that for now. An alternative is to use NPM automation tokens or granular access tokens.

**Comment by JamesHenry** [comment]
Sounds good, feel free to reach out with any more queries or concerns!
