### ISSUE TITLE
Bug: consumer/remote converting hyphen to underscore causes issue on project name with hyphen

### ISSUE THREAD

**Issue by jmvtrinidad** [nrwl/nx#29273]
### Current Behavior

after upgrading to 20.2.0, the withModuleFederation from rspack started to convert the remoteName and project name from [hyphen](https://github.com/nrwl/nx/issues/28497) to underscore. Due to this, it is a breaking change for any remote/consumer  which has hyphen on the project name.

### Expected Behavior

if possible add a way to opt in for converting to underscore but the default should make the projectName not to convert to underscore.

### Steps to Reproduce

1. same way as this https://github.com/nrwl/nx/issues/28497
2. https://github.com/nrwl/nx/pull/28244/files

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.4.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.3

nx (global)        : 20.0.8
nx                 : 20.2.0
@nx/js             : 20.2.0
@nx/jest           : 20.2.0
@nx/eslint         : 20.2.0
@nx/workspace      : 20.2.0
@nx/devkit         : 20.2.0
@nx/eslint-plugin  : 20.2.0
@nx/plugin         : 20.2.0
@nx/react          : 20.2.0
@nx/rspack         : 20.2.0
@nx/storybook      : 20.2.0
@nx/vite           : 20.2.0
@nx/web            : 20.2.0
@nx/webpack        : 20.2.0
nx-cloud           : 19.1.0
typescript         : 5.6.3
---------------------------------------
Community plugins:
@koliveira15/nx-sonarqube : 3.5.1
@nx-tools/nx-container    : 5.0.3
@nx/module-federation     : 20.2.0
---------------------------------------
Local workspace plugins:
         fe-tools
```

### Failure Logs

```shell

```

### Package Manager Version

9.12.3

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

currently we are using the project name to publish some package, the npm will not also allow to have a kebabCase.
Current workaroung
```js
    config.plugins.forEach((plugin) => {
      if (plugin.name === 'RspackModuleFederationPlugin') {
        plugin._options.name = plugin._options.name.replace(/_/g, '-')
        plugin._options.remotes = Object.entries(plugin._options.remotes).reduce((acc, [key, value]) => {
          acc[key.replace(/_/g, '-')] = value
          return acc
        }, {})
      }
    })
```

Im using the below remotes config
```js
remotes: [
 ['remote-app-one, 'remoteAppOne@/parent/remoteEntry.js'],
 ['remote-app-two, 'remoteAppTwo@/parent/remoteEntry.js'],
]
```

**Comment by christianulson** [comment]
Same with my project

**Comment by Coly010** [comment]
Unfortunately this is a limitation that we can't really avoid. It was fine previously when attached as a module, but that introduced a cascade of further issues because Rspack Module Federation still isn't quite ready with ESM support. So it had to be switched to CJS.

When a remote gets attached to the host, it's done via `var ${remoteName} = (() => {})()`

Therefore, the `remoteName` must be a valid JS variable name, which means that `-` cannot be allowed in the remote name. 
Otherwise you end up with `var my-remote = (() => {})()` which is invalid JS and fails immediately at runtime.

**Comment by christianulson** [comment]
Ok, tank's



Enviado do meu Galaxy



-------- Mensagem original --------
De : Colum Ferry ***@***.***>
Data: 19/12/2024 08:09 (GMT-03:00)
Para: nrwl/nx ***@***.***>
Cc: Christian Ulson ***@***.***>, Comment ***@***.***>
Assunto: Re: [nrwl/nx] Bug: consumer/remote converting hyphen to underscore causes issue on project name with hyphen (Issue #29273)


Unfortunately this is a limitation that we can't really avoid. It was fine previously when attached as a module, but that introduced a cascade of further issues because Rspack Module Federation still isn't quite ready with ESM support. So it had to be switched to CJS.

When a remote gets attached to the host, it's done via var ${remoteName} = (() => {})()

Therefore, the remoteName must be a valid JS variable name, which means that - cannot be allowed in the remote name.
Otherwise you end up with var my-remote = (() => {})() which is invalid JS and fails immediately at runtime.
