### ISSUE TITLE
`nx affected --target=build` is building more apps than necessary

### ISSUE THREAD

**Issue by protoEvangelion** [nrwl/nx#2996]
## Expected Behavior

**Given two simple apps:**
1. app 1 only imports a function called `add` from libs
2. app 2 only imports a function called `multiply` from libs

I would expect if I changed `libs/src/add.js` and ran `nx affected --target=build --files=libs/src/add.js` it would only show **app1 & libs** as affected. 

**File structure:**

![image](https://user-images.githubusercontent.com/20076677/81754179-5adb7f00-946a-11ea-9cd2-67ae249d08a9.png)

## Current Behavior

Nx thinks that all apps are affected even though app two is not importing the `add` function.

![image](https://user-images.githubusercontent.com/20076677/81754292-aa21af80-946a-11ea-947e-df16d32297b6.png)

### Steps to Reproduce

**Minimal Example**: https://github.com/protoEvangelion/nx-libs-example

**Check out & run** `nx affected --target=build --files=libs/src/add.js`

## Other

If this is by design, **_what are the options for us to inform nx to make more intelligent decisions_**? In this case, how can we only build what is **truly** affected: _app 1 & libs_.

**Comment by FrozenPandaz** [comment]
Hi, that's an interesting example.

Nx depends on _projects_ to construct the project graph.

Each project in `workspace.json` has a `root` directory which is the directory that contains the files associated with the project. When said files are modified, that project becomes touched and projects that depend on it become affected.

Your `libs` project contains both `add.js` and `multiply.js`. And because `micro-app-two` also imports from `libs`, it also becomes affected when `libs` is touched.

In order to separate those two, you would need to have at least `/add/add.js` and `/multiply/multiply.js` and have a project, `add`, with root `add` and another project, `multiply`, with root `multiply`. That's as minimal as it gets :smile:. now when you change `/add/add.js`, only the `add` project will be touched and `micro-app-two` does not depend on `add`, only `multiply` thus, `micro-app-one` will be affected while `micro-app-two` will not.

Hope that answers the question :+1:.

**Comment by protoEvangelion** [comment]
Thanks for taking the time to explain that @FrozenPandaz 😄 Since nx is already keying off of import statements, it seems reasonable that it could understand what is **actually affected**. _Are there any plans for nx to be smarter in ways like this?_
