### ISSUE TITLE
Save lint report to a json file

### ISSUE THREAD

**Issue by shabinpshams** [nrwl/nx#3016]
I am trying to save lint warnings to a json file by executing the following command.

nx affected:lint --all --parallel --maxParallel 6 -- --format json > ./code-smells/code-smells.json

And i am getting the below error

![image](https://user-images.githubusercontent.com/10242450/82068128-48677c80-96da-11ea-8b27-0259356d33d4.png)

**Comment by FrozenPandaz** [comment]
If you run the same command on http://github.com/nrwl/nx-examples does the same error occur?

If not, what is the result of `nx report`?

**Comment by shabinpshams** [comment]
> If you run the same command on [http://github.com/nrwl/nx-examples](https://github.com/nrwl/nx-examples) does the same error occur?
> 
> If not, what is the result of `nx report`?

There also I am facing the same issue.
My intention is to copy lint results into a son file to show in sonarqube.

When I run the below command, I will get the result.

ng lint <lib> --format=json > ./code-smells/establishment-public.json

But, if I use nx affected, it wont work.

**Comment by FrozenPandaz** [comment]
> But, if I use nx affected, it wont work.

When you are running with affected, it's separate lint processes running for each project as well as some logging. Piping all of the output into a json file will result in an improper json.

I recommend looking into defining a [jest reporter](https://jestjs.io/docs/en/configuration#reporters-arraymodulename--modulename-options) that outputs the test results to json for each project. Then you can aggregate them with a script and send that over to sonarqube.

I'm going to close this issue because I don't think this github issue is a good medium to help you with that.

However, if you need help, please feel free to join the [Community Slack](https://join.slack.com/t/nrwlcommunity/shared_invite/enQtNzU5MTE4OTQwOTk0LTgxY2E0ZWYzMWE0YzA5ZDA2MWM1NDVhNmI2ZWMyYmZhNWJiODk3MjkxZjY3MzU5ZjRmM2NmNWU1OTgyZmE4Mzc) and ask in the #support channel.
