### ISSUE TITLE
Dependencies at ~ instead of pinned?

### ISSUE THREAD

**Issue by pburkindine** [nrwl/nx#3029]
This is really more of a question than a request.  When nx creates/updates a package.json file, dependencies are pinned at the .0 version (so e.g. `"@angular-devkit/core": "9.1.0",`) rather than marked with `~` (`"@angular-devkit/core": "~9.1.0"`).  This means minor bugfix releases aren't picked up by default, and we either go from nx release to nx release without patches to any of these packages, or else modify nx's output.  I'm fine with adding the `~` myself but I want to make sure I understand the rationale behind not including it.

## Expected Behavior

Dependencies like angular and ngrx should be marked with ~ so that minor bugfixes are picked up, rather than pinned at the .0 version

## Current Behavior

Dependencies are pinned at .0

**Comment by Hotell** [comment]
Unfortunately npm versioning ecosystem cannot be trusted, so having not exact deps leads to various bugs and clashes.

> it bit myself many times in the past 

Always prefer explicit over "magic behaviour"

**Comment by pburkindine** [comment]
> Unfortunately npm versioning ecosystem cannot be trusted, so having not exact deps leads to various bugs and clashes.
> 
> > it bit myself many times in the past
> 
> Always prefer explicit over "magic behaviour"

Yeah, I'm assuming that's the reasoning but just want to confirm.

**Comment by vsavkin** [comment]
Thanks for submitting the issue!

Because we heavily depend on @angular-devkit/core", we have been broken by patch updates. That's the reason why we pin these. We are planning to have a simpler way to run tasks which will remove the dependency on angular-devkit/core altogether. This should happen in the next 5 months. So I'd keep it as is until we do the refactor.

I'm going to close this.
