### ISSUE TITLE
Deprecate @nrwl/cypress/plugins/preprocessor

### ISSUE THREAD

**Issue by AlexAegis** [nrwl/nx#3037]
In the generated `index.js` pluginFile of cypress the nx helper is there to preprocess TS Files.

```
  // Preprocess Typescript file using Nx helper
  on('file:preprocessor', preprocessTypescript(config));
```

Since Cypress 4.4.0 (4/13/2020), it supports typescript out of the box

> Added support for TypeScript without needing your own transpilation through preprocessors.

https://docs.cypress.io/guides/tooling/typescript-support.html#History

**If the nx preprocessor is more than that, then please clarify in the comment why it's needed.**

In a fresh project I tried to run `e2e` with the plugin removed and it ran fine. But then again, that was an empty workspace with a blank angular app.

**Comment by FrozenPandaz** [comment]
I agree, let's start investigating by opening a PR against https://github.com/nrwl/nx-examples with the preprocessor removed to see if everything works as expected there.

**Comment by demisx** [comment]
Will Nx migrate us to Cypress v4 when ready or will we have to do it manually? I've tried the latter, but running into similar issue. Should we stick with v3.x for now?

**Comment by george43g** [comment]
The latest Cypress has TS support built-in. I'm not sure what this means about the preprocessor hook personally - check out this thread for more info: https://github.com/cypress-io/cypress/pull/5906

But I wanted to point out a couple of important points:
In the default schematic, the generated cypress.json file should have a few changes made:
the `pluginsFile` needs to point directly to `plugins/index.ts` with the file extension. The default from when I set it up earlier in the year was `plugins/index`. This caused a crash.

This means that the default pluginsFile also needs to be updated to TS. I actually suspect that their preprocessor does a little more than transpile - it also had some tsconfig paths module in its source code and I suspect this is set up this way in order to be able to resolve the library paths as configured in the `paths` property in `tsconfig`. This is generally a pain point with tsc and is why they use webpack to bundle apps in NX. In order to be able to resolve these library paths while running ts-node, I _think_ you might need extra functionality in the preprocessor, hence why they built their own rather than using the one that was available previously to the Cypress community.

It would be **really helpful** to be able to not only write plugins in TS, but also be able to _require TS libraries_ from within the plugins file!

I also think that `typescript: 'project'` is a setting that should be set as well (please double-check this as I only had a cursory glance) but I'm not sure where from. I just know it's checked in the Cypress source code.

**Comment by tstackhouse** [comment]
Looks like this got marked as stale and closed out when it probably shouldn't have.

**Comment by docwhite** [comment]
If I simply remove the `on('file:preprocessor...` line, in an Angular nx monorepo, I get errors:

```
Error: Webpack Compilation Error
/Users/ramon/Watchity/frontend/libs/shared/ui/src/index.ts 15:9
Module parse failed: Unexpected token (15:9)
File was processed with these loaders:
 * ../../../../Library/Caches/Cypress/7.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
```

See my full log in the related issue https://github.com/nrwl/nx/issues/5713
