### ISSUE TITLE
Nest schematics use different linters for apps and libs

### ISSUE THREAD

**Issue by pf1gura** [nrwl/nx#3063]
## Expected Behavior

@nrwl/nest schematics use same linter (preferably eslint) for both apps and libs

## Current Behavior

* @nrwl/nest:app generates eslint configuration
* @nrwl/nest:lib generates tslint configuration

### Steps to Reproduce
1. `nx g @nrwl/nest:app api`
2. `nx g @nrwl/nest:lib api/common`

![image](https://user-images.githubusercontent.com/41795518/82751359-e7653600-9db6-11ea-940e-9cea91f3e0cd.png)

**Comment by FrozenPandaz** [comment]
Good catch! The issue is that the default workspace does not set the right default for `@nrwl/nest:lib`, only `@nrwl/nest:app`. This would be a good first issue for somebody to contribute. The function to alter is here:

https://github.com/nrwl/nx/blob/ba3f49c828f5120ca8be8f57b00691f8734effc5/packages/workspace/src/schematics/shared-new/shared-new.ts#L233

**Comment by pf1gura** [comment]
@FrozenPandaz I created a PR for that. Please look when you have a chance.

Also, I watched [your getting started video](https://www.youtube.com/watch?v=o11p0zSm0No&feature=youtu.be) before I started and `yarn e2e create-playground` fails with error that this is invalid project. Is that expected? Video is few months ago so maybe there is another way to test the changes? I used local npm registry approach, but this way seemed better.

![image](https://user-images.githubusercontent.com/41795518/89327678-91e9b700-d68c-11ea-9f4a-fd2f9716a376.png)
