### ISSUE TITLE
Apps/Libraries that uses other Libraries make it a option to use the dist instead of the source files by serving

### ISSUE THREAD

**Issue by LennardWesterveld** [nrwl/nx#3102]
Hi Nx devs,

I came op with the following problem with kinda a nice solution that could be built in in nrwl/nx,
For example, app1 uses library-icons and library-icons uses svgr to generate all the icons what is in there over 1.000 icons. But app1 is using just two icons of the whole icon set, at this moment app1 has just a dependency on the source file of library-icons/index.ts that is loading all the icons in and transfer them to react elements. What if app1 can uses the build of svgr by default by serving or a storybook environment so that those are not compiling library-icons them selfs but using the dist build what can be tree shaken.

**Comment by conioX** [comment]
+1 i need this too 😅instead off generate rollup based on files, we can control to build into dist folder

**Comment by StalkAltan** [comment]
Hi @LennardWesterveld!

If I am understanding your question correctly, you would like your Nx apps/libs to depend on an already-built version of another lib so you can get better tree-shaking? I think it is possible to achieve this with not much adjustment to your project structure.

The main change comes in the aliased paths inside the workspace root `tsconfig.json` file. Here, you can change the path for your 'library-icons' project to the `dist/library-icons/index.js` file instead of `libs/library-icons/index.ts`. Since the built version of the index file *should* be exporting the same members as the un-built ts file, none of your app/library code should be affected by this change.

Once you've done this, you will need to go into your workspace's `nx.json` and set `library-icons` as an implicit dependency for any projects that currently rely on it. Since the aliased path has been changed in the workspace `tsconfig.json` to the dist folder, Nx's code analysis won't detect changes in the typescript library's folder tree anymore.

Finally, you'll want to make sure it's easy for your team to keep their locally built version of the library updated. I would add an npm script to actually perform the build, and then run this script both post npm/yarn install, as well as on a git post-checkout hook using a tool like Husky. Unless this library is changing a lot, this should be a good enough safety net to make sure no one is using a mismatched version of your library.

**Comment by LennardWesterveld** [comment]
That worked but then I seem to have an issue with Storybook that isn't working with that and nextjs.
