### ISSUE TITLE
node --inspect/--inspect-brk incompatible with nx task runner

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3144]
## Current Behavior

on `node --inspect-brk ./node_modules/.bin/nx build best-app`, post attach, I cannot debug due to port conflict:

```
Debugger listening on ws://127.0.0.1:9229/10537d99-1102-40aa-8820-a5993dce9841
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> nx run best-app:build
Starting inspector on 127.0.0.1:9229 failed: address already in use
Waiting for the debugger to disconnect...
```

Port `9229` is otherwise free--it is not used until this very node process begins.

## Expected Behavior

`node --inspect-brk $(yarn bin)/nx build best-app` to allow me to debug my application's build pipeline

## Steps to Reproduce

reproduction and instructions can be found here: https://github.com/cdaringe/nxtester/tree/demo/no-debugging

**Comment by FrozenPandaz** [comment]
Thanks for reporting the issue :smile:

This is due to `fork` being used to run the command... We'll have to investigate how to handle this..

If you want to debug the actual build.. you should inspect the `tao` directly.

```
node --inspect-brk node_modules/.bin/tao build best-app
```

**Comment by cdaringe** [comment]
@FrozenPandaz thanks. for many cmds, this works great. i observed today that it does not work with `run-many`, which probably also needs a solve

**Comment by june07** [comment]
I solved a similar problem here https://blog.june07.com/socket-watcher/.  It may help in your case as well.

**Comment by vsavkin** [comment]
There are two things you can do:
1. `NX_SKIP_TASKS_RUNNER=true node --inspect ./node_module/.bin/nx build blah` will not fork the process. You should really avoid doing this.
2. `node --inspect=0  ./node_module/.bin/nx build blah` will use a random port as @june07 described. 

We cannot really fix because we need to create multiple processes to enable caching and when using run-many. 

@isaacplmann can you make we have a guide in the docs talking about debugging?

**Comment by m4r4c00ch0** [comment]
@vsavkin what is the current workaround to inspect node applications?

**Comment by tar-aldev** [comment]
Sorry to post on closed issue but I encounter the same issue as well.
I need to debug tests and take memory snapshots.
When launch 
 node --inspect-brk ./node_modules/@nrwl/cli/bin/nx test backend
It outputs
```
Debugger listening on ws://127.0.0.1:9229/54183c9a-66ed-4a2c-93c7-98f4788da4c2
For help, see: https://nodejs.org/en/docs/inspector
```
Then I go to chrome://inspect
Click on Open dedicated DevTools for Node
https://prnt.sc/12m6csh

It opens devtools and steps into `Sources` tab automatically. There I can see some code which seems to be coming from some nx files.
![1](https://user-images.githubusercontent.com/54899662/117417788-60f02880-af23-11eb-9484-28eeffb31aea.png)
Is it proper behavior?

Then I get an error
```
Starting inspector on 127.0.0.1:9229 failed: address already in use
```
If I try to take any snapshots it just hangs on a random percentage value and debugger is disconnected (I cannot see nx workspace in `chrome://inspect` anymore.
Tests continue to run and I cannot stop them with ctrl + c.

Please help me. I spent nearly one day on this issue and still unable to debug any tests.

**Comment by jkolyer** [comment]
> We cannot really fix because we need to create multiple processes to enable caching and when using run-many.
> 
> @isaacplmann can you make we have a guide in the docs talking about debugging?

Can you please provide links to docs talking about debugging.  I am trying to set a breakpoint in chrome and it doesn't break where it should, despite following all the instructions provide herein.  

With all due respect, saying "we cannot really fix" is a huge cop-out.  If I cannot debug simple issues in storybook using NX, then NX is not suitable for production applications. 

Developer experience is an important success factor, and this is a serious blocker.  That is, unless you can show me it is not.  

Meanwhile I cannot debug therefore I cannot go to production therefore NX is not suitable for production applications.  Prove me wrong please.

**Comment by jkolyer** [comment]
Why is this issue closed?  It's not resolved for at least 3 people.

The co-founder @vsavkin  commented "we cannot really fix".  Is that why  it is closed?  Please provide more details because it is a major blocker.  Any respectable product would not tell its user base that a major blocker cannot be fixed, then shut down further discussion.

**Comment by cdaringe** [comment]
> Any respectable product would not tell its user base that a major blocker
cannot be fixed, then shut down further discussion.

If you're not willing to send a patch yourself, you have zero right to
demand it from the maintainers. This software is open and free. Try again,
or do not participate.

**Comment by jkolyer** [comment]
> Any respectable product would not tell its user base that a major blocker cannot be fixed, then shut down further discussion.
> If you're not willing to send a patch yourself, you have zero right to demand it from the maintainers. This software is open and free. Try again, or do not participate.

I beg your pardon?  This issue is marked "closed".  It is clearly not closed.  Why would I patch an issue that was marked closed?  Would you spend time on that?  

The maintainer @vsavkin needs to address this issue and verify the status.   He has indicated the documentation needs updating, but provided no links. 

I suggest you keep your comments to yourself until this issue has been updated by the maintainer, @vsavkin .   If you're not willing to to patch it yourself, then kindly refrain from commenting on this issue.

**Comment by isaacplmann** [comment]
@jkolyer it seems that other people have found solutions.  What specific command are you having trouble debugging?  I always use the Javascript Debug Terminal in VS Code to debug things.

1. Command-shift-P and type in debug.  Then choose `Javascript Debug Terminal`
2. Set a breakpoint in your code (either with `debugger;` or using VS code's breakpoints)
3. In the debug terminal that opened, run your normal comand (i.e. `nx run my-app:build`)

Here are some docs talking about this method: https://nx.dev/latest/angular/generators/workspace-generators#with-visual-studio-code

**Comment by jkolyer** [comment]
@isaacplmann Thanks for your helpful reply.  I am debugging storybook, and am not a VSCode user, instead using node cli with chrome.  It appears my breakpoints were not working due to some sort of race condition.  They are working now.

I'm running this command 
`node --inspect ./node_modules/@nrwl/cli/bin/nx run $PROJ:storybook`

Then opening chrome to run the storybook.  On the first page load, breakpoints do not activate, but they do on page reload.  Same issue occurs using `--inspect-brk`.

I would suggest that nx.dev provide a dedicated documentation page for debugging techniques.  Other developers clearly are facing the same issues.  @vsavkin

**Comment by jkolyer** [comment]
@isaacplmann Unfortunately my problem has reoccurred in that breakpoints are not triggered both on Chrome and VSCode.  I will continue tracking this down and report back findings.

**Comment by jkolyer** [comment]
@isaacplmann Got debugging working in VSCode.  I'd be happy to collaborate on a debugging techniques document if you want to make a template I can add to.

**Comment by mend3** [comment]
I think it's worth to mention that debugging preferences is also available via **project.json** files.

As you can see in the image, I'm runnning 3 different projects (Express API) on diferent ports and debugging 2 of them (the other one is disabled for example purposes).

`Debugging 1st app on port 9230`

![image](https://user-images.githubusercontent.com/1450229/148670099-070e3ee9-caa9-44ca-8e62-e0618b5d4c3c.png)

`Debugging 2nd app on port 9231`

![image](https://user-images.githubusercontent.com/1450229/148670061-cf6de22c-5ad8-4e38-ae0d-c2fe4d7aeb09.png)

`Last app with debugging disabled`

![image](https://user-images.githubusercontent.com/1450229/148670071-77981fb5-53ca-40ba-8403-66d8dc7dc9ad.png)

`All 3 apps running alltogether`

![image](https://user-images.githubusercontent.com/1450229/148670041-ceecb4b0-47f0-476f-aaea-799a9aa83fc3.png)

More details at [NX Website](https://nx.dev/node/execute#nrwlnodeexecute)

**Comment by adamgen** [comment]
@mend3 Unfortunately, it's not working with a test target. 

And the link to the nx website is broken...

**Comment by isaacplmann** [comment]
Try this link:
https://nx.dev/packages/node/executors/node
