### ISSUE TITLE
nx affected:test/lint list all apps if the change is only made in lazy loaded lib

### ISSUE THREAD

**Issue by hehoo** [nrwl/nx#3263]
## Current Behavior
In my angular repo, there is one app with several libs. All the libs are lazy loaded by the app by using loadChildren. All the libs have reference/imports from the app, but there is no reference/import from app to lib(except the loadChildren). When I run "nx dep-graph" the dependency graph looks like: 
![image](https://user-images.githubusercontent.com/1418392/86306632-25783400-bc58-11ea-9697-46bd307a3918.png)
Does the dashed line indicate the relationship of the lazy load? 

When I made a change on one of libs, the `nx affected:test` would run all tests in all the libs and the app. The `nx affected:lint` would do the same thing as `nx affected:test`. 

## Expected Behavior

What I expected is that only the changed lib should be affected when I run either affected:test or affected:lint. 

## Steps to Reproduce

It works as expected before we upgrade the angular version from 8.x to 9.x.  The nx workspace version was upgraded to 9.2.4 from 7.x during the angular 9 upgrade. It seems like the the newer version of nx changed the behaviours how it generates the dependency graph. 
  
### Environment

  @nrwl/angular : 8.12.0
  @nrwl/cli : 9.2.4
  @nrwl/cypress : 9.2.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.4
  typescript : 3.8.3

**Comment by StalkAltan** [comment]
Hi @hehoo !

While it's definitely possible that the dependency graph logic changed during your version (I haven't been around Nx for enough versions to tell you for sure...), the current state of your dep graph would indeed create the 'issue' you've stated here.

Since all of your lazy loaded modules have direct imports from your app, if the app itself changes _or_ one of the app's dependencies change, all the other modules will have to be rebuilt. The only way that I'm aware of to avoid these rebuilds is going to be to remove the various module's imports from the app. Maybe someone else will have a different solution.

Also, your assumption was correct -- the dashed lines do represent lazy loaded dependencies.

**Comment by hehoo** [comment]
> Hi @hehoo !
> 
> While it's definitely possible that the dependency graph logic changed during your version (I haven't been around Nx for enough versions to tell you for sure...), the current state of your dep graph would indeed create the 'issue' you've stated here.
> 
> Since all of your lazy loaded modules have direct imports from your app, if the app itself changes _or_ one of the app's dependencies change, all the other modules will have to be rebuilt. The only way that I'm aware of to avoid these rebuilds is going to be to remove the various module's imports from the app. Maybe someone else will have a different solution.
> 
> Also, your assumption was correct -- the dashed lines do represent lazy loaded dependencies.

Hi @StalkAltan 
Thanks for your comment. If the app itself changes, it is expected that all dependant libs get affected/rebuilt as all libs have the references from the app. But my question is that if one of lib changes, the app and other libs should not get affected by given that the app just lazy load all libs and the app doesn't have direct import/reference from libs. Especially for the lint, I just changed one line of code in one of lib, why the other libs and the app should run the lint?

**Comment by StalkAltan** [comment]
> > Hi @hehoo !
> > While it's definitely possible that the dependency graph logic changed during your version (I haven't been around Nx for enough versions to tell you for sure...), the current state of your dep graph would indeed create the 'issue' you've stated here.
> > Since all of your lazy loaded modules have direct imports from your app, if the app itself changes _or_ one of the app's dependencies change, all the other modules will have to be rebuilt. The only way that I'm aware of to avoid these rebuilds is going to be to remove the various module's imports from the app. Maybe someone else will have a different solution.
> > Also, your assumption was correct -- the dashed lines do represent lazy loaded dependencies.
> 
> Hi @StalkAltan
> Thanks for your comment. If the app itself changes, it is expected that all dependant libs get affected/rebuilt as all libs have the references from the app. But my question is that if one of lib changes, the app and other libs should not get affected by given that the app just lazy load all libs and the app doesn't have direct import/reference from libs. Especially for the lint, I just changed one line of code in one of lib, why the other libs and the app should run the lint?

@hehoo maybe this will help shed some light: [link](https://github.com/nrwl/nx/blob/ad9776eb91e857132a0bf2a8dabe4a2afb1f3faa/packages/workspace/src/core/affected-project-graph/locators/workspace-projects.ts#L26)

If _any_ file in an implicit dependency changes, it will trigger a build of the dependent project. This means that Nx doesn't have a way to tell that your app is only using the lazy loaded dependency in a `loadChildren`, and so will force a rebuild of that app and all of its dependencies. Once your app is marked as affected, all the other modules will be as well because of their direct dependency on that app.

**Comment by FrozenPandaz** [comment]
I think there is a misconception about what "affected" means. Making changes to the projects, not only impacts the projects that are changed. Because the behavior of projects that depend on those that are changed can be impacted, those projects are affected as well.

The graph shown does limit the effectiveness of `affected` because touching any lib will cause the app to become affected. When that app is depended on by the other libs, those libs will become affected as well. To remedy this, I recommend moving parts of the app that is being depended on by the libs into a lib. This way, the libs won't depend on the app anymore and depend on that lib instead.

**Comment by dwy** [comment]
My understanding of the issue is that, if project A is changed, why do all projects that depend on A need to be _linted_?

If project B depends on project A and only A changed, I don't see why B would need to be linted as well.

**Comment by Lonli-Lokli** [comment]
@FrozenPandaz is there any way to exclude app with affected:test command?
Well-written angular app consists of almost empty she'll and set of lazy modules, and testing for affected changes in one lazy child should not trigger whole application.

**Comment by kievsash** [comment]
> My understanding of the issue is that, if project A is changed, why do all projects that depend on A need to be _linted_?
> 
> If project B depends on project A and only A changed, I don't see why B would need to be linted as well.

same for unit tests
