### ISSUE TITLE
Supporting java and golang backend project

### ISSUE THREAD

**Issue by dongnguyen9186** [nrwl/nx#3272]
First of all, thanks for the great front end framework. At time being, we only mention nestjs, node js backend in documentation. Do we have plan to support other types of backend, for example java or Golang? My project use Golang and java, wonder how i can make it work with nx

**Comment by vsavkin** [comment]
The core of Nx is technology agnostic, so you could add Golang or Java right now. We use Kotlin in our internal monorepo, and it's working well. We are planning to release a Java plugin this year that will help you set up the boilerplate, connect things to Gradle, etc.. The Golang plugin isn't planned for this year. But if someone else (or youself) wants to be build, we will help out.

**Comment by beeman** [comment]
Hey @dongnguyen918, I built a plugin that allows you to run Go projects in a Nx Workspace.

You can find it here: https://github.com/nx-go/nx-go

Let me know if you have any issues.

**Comment by jbadeau** [comment]
Any update on that java plugin?

**Comment by jbadeau** [comment]
Hello,

There is now a community spring boot plugin but out of the box its not integrated into the workspace dependency graph.

I have heard there is an official android plugin coming but not seen any details.

I wouldn't mind working on this but I don't want to duplicate efforts.

Any thoughts?

**Comment by tinesoft** [comment]
For future googlers,

I'm the author of that Nx plugin to integrate Spring Boot projects: [nxrocks/nx-spring-boot](https://github.com/tinesoft/nxrocks/tree/develop/packages/nx-spring-boot)😇 and I'm happy to announce it now supports **Nx's dependency graph** as well (since `nxrocks/nx-spring-boot@v2.1.0` and thanks to Nx12's [Project Graph Extension API](https://nx.dev/latest/angular/structure/project-graph-plugins#extending-the-project-graph-of-nx))!

Feel free to use it and report any issue/improvement you may have! 

Cheers

**Comment by cenguidanos** [comment]
Here a simple example of how to create custom executors or builders in your workspace, see `workspace.json`:

https://github.com/cenguidanos/next-ddd

**Comment by AgentEnder** [comment]
I'm going to close out this issue since it's not requesting any additional functionality, feel free to open new issues for plugin functionality that is desired and it can be evaluated as-needed.

Current community plugins exist for Java, .NET, Go, Rust, and a few other non-js technologies and can be found at nx.dev/community
