### ISSUE TITLE
Import shared classes from lazy-loaded modules.

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#328]
I have lazy-loaded module.
And I have shared service and models in this module.

Now when I import service or models(for typing) in another module it yells.
![image](https://user-images.githubusercontent.com/1386622/37339817-9e965442-26c4-11e8-8c19-7893a5425208.png)

Any suggestions how to handle it ?

**Comment by kylecordes** [comment]
At the top of your shared library, re-exports all of the necessary identifiers from an index.ts file. Example:

https://github.com/nrwl/nx-examples/tree/master/libs/model

**Comment by ph55** [comment]
Great, thanks.

**Comment by ph55** [comment]
@kylecordes So as I see it, there is no actual need of using barrel in lazy-loaded modules.
Anyway the only thing you export (and allowed to import) from index is module itself.

Correct me if I wrong.

**Comment by kylecordes** [comment]
@ph55 For some modules, that is correct, the only identifier used from elsewhere is the module itself. But for other more complex uses, it is common for other parts of your application to need access to the types or service classes (for services provided by the module) in order to use the module. Here's an example of access to a service class:

https://github.com/OasisDigital/angular-enterprise-example/tree/master/libs/employee-api

(This is an example application I work on, I am more familiar with it than with the official Nx example.)

**Comment by ph55** [comment]
I see. 
But in this case it's not lazy-loaded module. So it's clear.

Thanks.

**Comment by ph55** [comment]
https://github.com/nrwl/nx/issues/329

**Comment by kylecordes** [comment]
(My answer above accidentally ignored the "lazy" part of the question. For lazy loaded modules, you really don't want other parts of the application referring to identifiers inside. See explanation in #329.)
