### ISSUE TITLE
contributing instructions for installation require localhost:4873, but not specified as required

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3291]
## Current Behavior

- `yarn` fails, expecting verdaccio, but doesn't claim as a hard requirement in the instructions. `yarn.lock` has references to localhost for package origin

## Expected Behavior

`yarn` to install all from network

## Steps to Reproduce

https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#building-the-project

### Failure Logs

```
$ yarn
yarn install v1.19.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[##---------------------------------------------------------------------------------------------------] 65/2781yarn build
[###--------------------------------------------------------------------------------------------------] 88/2781
error An unexpected error occurred: "http://localhost:4873/fs-extra/-/fs-extra-9.0.0.tgz: connect ECONNREFUSED 127.0.0.1:4873".
```

### Environment

```
nx $ npx nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.4.4
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 9.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.4
  @nrwl/linter : 9.4.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.4.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.4
  typescript : 3.9.6
```

**Comment by bekos** [comment]
@cdaringe thx for reporting 😃 Can you please elaborate on this issue? I don't see any `localhost` references inside the `yarn.lock` and `verdaccio` is listed in `package.json` [here](https://github.com/nrwl/nx/blob/929f2f4b9d21e19d20e641a57749bccd3fa23ea4/package.json#L230). Maybe your issue got fixed in one of the recent releases 🤔 Plz check again with latest, and if there is still a problem, you can help me understand what needs improvement 😄

**Comment by cdaringe** [comment]
Sounds like it's been fixed if that's the case. Thanks
