### ISSUE TITLE
Enable project/app as parameter for storybook

### ISSUE THREAD

**Issue by mchl18** [nrwl/nx#3311]
## Description
Currently it is not possible to create different storybooks for different projects/apps within `nrwl`.

`nrwl/storybook` only enables us to use different libs from one app.

In our case we need to create storybooks with different themes and features for differet apps/projects, while the libs are shared. Right now storybook only supports a `default-project` value in `angular.json`. This problem is rooted in `@storybooks/angular`

## Motivation
I want to be able to run `nx run <project>:storybook`  in order to be able to run storybook with an angular project named `<project>`

## Suggested Implementation
One step would be to update storybooks implementation, as described here:
https://github.com/storybookjs/storybook/issues/11499

**Comment by mandarini** [comment]
Hi there @mchl18 ! Thanks for filing an issue!

Can you please check [this video](https://youtu.be/c323HOuFKkA) and see it it helps with what you are trying to do?

You can also take a look at [this pull request](https://github.com/nrwl/nx/pull/3264). The new feature that will be introduced will enable users to add Storybook to applications as well as libriaries. I know that what you are requesting is a bit different, but maybe when Storybook gets enabled for applications instead of just libraries, your issue will be solved, too?

Let me know if you have any questions, or if you need any further assistance!

**Comment by mchl18** [comment]
@mandarini The video does not help as our setup is much more complex (7 apps and 17 libs) with lots of configurable css.

However you are correct, if the issue you named is resolved and my issue at storybook has been adressed, then this would be a change request for nx to support the new storybook version.

**Comment by mandarini** [comment]
Hi @mchl18 ! I will close this issue, since I believe it was addressed/resolved by #3264 ! Let me know if you need anything else, and I hope your issue is resolved now! :)
