### ISSUE TITLE
auto import in vscode for lib exports not working for new project without explicit include in root tsconfig

### ISSUE THREAD

**Issue by rhyek** [nrwl/nx#3342]
## Current Behavior
For a new empty project with a nestjs app and a workspace lib called "utils", when typing the name of an exported function from `@org/utils` (for example `exportedExampleA`) in a file within the nestjs app I do not get an auto import suggestion from vscode's IntelliSense.

## Expected Behavior

If I'm typing `exportedExampleA` in a file within the nestjs app, I would expect vscode to suggest an auto import like `import { exportedExampleA } from '@org/utils'` so that I can select it without me having to type in the import manually.

## Steps to Reproduce

```
nx g @nrwl/nest:application webapi
nx g @nrwl/workspace:library utils
```
```ts
// libs/utils/src/index.ts
export function exportedExampleA() {
  return 'lol';
}
```
```ts
// apps/webapi/src/main.ts
...
exportedExampleA // type this and expect auto import suggestion
```
### Failure Logs

N/A.

### Environment

OS: macOS 10.15.5
vscode: 1.47.1
nx: latest

### Workaround
Add the following to the monorepo's root `tsconfig.json` and restart vsc:
```json
{
   ...
  "include": [
    "./libs/*/src/**/*",
    "./apps/*/src/**/*"
  ]
}
```
Auto import now works as expected.

**Comment by vsavkin** [comment]
Unfortunately, we cannot add "include" into the root tsconfig because it is inherited by all the projects. They have to be independent from each other.

Tollowing works:

Add the following to the lib:

```
export function funcA() {
  return 'lol';
}

export function funcB() {
  return 'lol';
}
```

Add the following the app:

```
import { funcA } from '@myscope/mylib' 
```

Now when type in "funcB", vscode will autocomplete it. Basically as long as your app imports mylib anywhere in its source, the autocompletion from mylib will work. Otherwise it won't. You can "fix" it manually by adding path to the lib to tsconfig.app.json of your app, but I personally would not do it. This is a limitation of how vscode autocompletion works. The language service has to know that myapp points to mylib before it can autocomplete tokens from it. The same is true about autocompleting tokens from  node_modules.

As a side note, WebStorm doesn't have this issue because their autocompletion doesn't rely on the language service.

I don't think this issue can be fixed on our side, so I'm going to close it.

**Comment by nhhockeyplayer** [comment]
importing libs and objects continues to be a wide open issue even in web-storm

there is no continuity in the docs on libs, exported functions within index.ts, paths in tsconfig

the end goal is to auto import for high velocity and its not attainable right now which is terrible

if this can be prioritized that would be fair for developers in the field pressed to deliver

someone needs to place some attention to this and fix it its the main cornerstone of velocity for writing and managing code

adding superfluous functions to the barrel file is unfair 
why cant barrel files be totally eliminated it seems its the socket ratchet to nail done a library but the impact of import statements and auto import has been shelved and left wide open

coding everything to bypass the barrel file and just operate a module introduces unending array of circular dependencies during compile

can this be reopened and looked at and resolved for all IDE

**Comment by reamerNC** [comment]
Agreed. This is a bummer. I'd like some elaboration on this issue and any workarounds as well.

Thanks.

**Comment by solarmetahedron** [comment]
Hey, I also had intellisense issues with a NX monorepo with Angular. I realized in my case in the tsconfig.base.json there is an 
`"exclude": ["node_modules", "tmp"]` 

So after removing "node_modules" from exclude and restarting VSCode intellisense started working normally.

Hope it helps

**Comment by dgrbrady** [comment]
Just in case anyone else is stumbling through this, I have pretty much a blank NX workspace that I created yesterday with 1 barebones angular app and 1 barebones nestjs app. Both were generated via the NX CLI. Doing these 2 things fixed the issue for me:
1. Only remove `node_modules` from the `excludes` property in `tsconfig.base.json` (only doing this did not fix the issue for me)
2. Add `"../../node_modules/@angular/**/*.d.ts"` to the `include` array in `tsconfig.editor.json` for your angular app. You may be able to add it in `tsconfig.json` or `tsconfig.app.json`, but based on file names alone, I figured it was more appropriate to place in the editor json since this is an editor related issue.

**Comment by yacafx** [comment]
I try with the extension [Auto Import](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport) and it works 😃, I know that it is not the "native" solution, but to keep working and avoid wasting time, it is a good solution 😉

https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

**Comment by anthonyma94** [comment]
@yacafx I installed the extension but it didn't change the behavior, how did you get it to work?

**Comment by Cammisuli** [comment]
For those that stumble across this issue in the future, the extension that we created [Nx Console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) includes a Typescript plugin that enables auto importing properly for all newly created libs. 

Give it a shot!

**Comment by samiulhsohan** [comment]
@Cammisuli Is it just enough to install the extension? or it needs any configuration?

**Comment by alexgorbatchev** [comment]
I can't seem to get this to work properly using neither Auto Import or Nx Console. All of my monorepo imports are imported via `libs/...` path instead of using `tsconfig.json/compilerOptions.paths`

**Comment by alexgorbatchev** [comment]
I seem to have just realized that auto import doesn't work for `default` exports, however it does work well for named exports.

**Comment by Cammisuli** [comment]
The plugin that's included with Nx Console finds the tsconfig.lib.json files that are based on the paths included in the compilerOptions.paths property in the tsconfig.base.json. 

When it finds the tsconfig.lib.json files, we tell the TypeScript language server about them for each TypeScript project that gets opened. 

TypeScript itself will then handle the code completion from that point forward because it knows about all the projects in the workspace. 

Now with the default exports, I feel that TypeScript has a hard time importing these from libs that are separate projects aka `@myorg/package`. But it can easily import them from within a lib, aka relative imports. 

It does it this way because it can associate the default export with the file name and automatically name the default export the same name as the file. It doesnt seem to do that with packages because there's no file associated with the path. 

For example, it can import this:
`import defaultExport from './default-export'`
But it cannot do this:
`import @myorgPackage from '@myorg/package'`

**Comment by xseman** [comment]
When you open the package as a workspace `File: Open Folder...` automatic import works. I've also install `Nx console` extension.
