### ISSUE TITLE
Can i rename my libs folder with 'projects' or anything?

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#3350]
I wanted to rename 'libs' folder to 'projects' as in my requirement I'm going to create many micro-apps/feature modules which will remain in libs folder and i think its not a suitable name when my focus is to create modules which are more of business specific.

**Comment by danielfyhr** [comment]
Try this in nx.json: (in your case use projects instead of packages)

```
  "workspaceLayout": {
    "libsDir": "packages"
  },
```

https://github.com/nrwl/nx/blob/master/nx.json

**Comment by ak274** [comment]
Thanks @danielfyhr !

That is exactly what i needed.

Can you please also let me know while creating workspace with angular-cli how I should use this option?

Is there any flag to mention the directory name while creating app using  `npx create-nx-workspace` ?

**Comment by danielfyhr** [comment]
In your case with "projects" manually is the only way. 

There's only "apps-and-libs" (default) and an option to create the workspace with both apps and libs in packages folder, i _think_ this is how you do it, though i'm currently not able to verify it.
```
npx create-nx-workspace --layout packages
```

**Comment by vsavkin** [comment]
You can run: `npx create-nx-workspace --preset=oss` or `npx create-nx-workspace --preset=oss --cli=angular` to get a workspace with the packages folder instead of apps and libs. You can also rename it to anything you want at any point. Just make sure to update the workspaceLayout property in nx.json to reflect the rename.
