### ISSUE TITLE
Support absolute URL for typescript

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3368]
Would be good to have a `useAbsolute` flag when generating libraries, this could be a universal flag that applies to all typescript projects.

## Description

Allow `baseUrl` to be applied, we'll need a third party plugin to transform the absolute paths to relative during compilation

## Motivation

Enables absolute URL for project, cleaner imports

## Suggested Implementation

Take `@nrwl/node:package` for example, We would need to modify compiler used here:

https://github.com/nrwl/nx/blob/c7b0e7d12284a8045b057c1addaa3d701a1adf9f/packages/node/src/builders/package/package.impl.ts#L205-L208

Compiler: https://github.com/cevek/ttypescript/tree/master/packages/ttypescript
Plugin: https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths

**Comment by vigie** [comment]
I would love to see this as the default strategy to support publishable libraries.

The current strategy, where `--publishable` insists you also add `--importPath` doesn't make much sense to me. To begin with, there doesn't seem to be any validation of the string passed to `importPath`, so that it happily accepts an invalid npm package name. But putting that to the side, it is not the name of the library to publish that is the concern (the source code of that library will never reference its own name), it is the subsequent use of other libraries that do not have valid npm package names from within the publishable library that will be the problem.

Now, when working within a large monorepo with many shared libs, it is not predictable which libraries may eventually need to be published. Currently, the only safe strategy is to make _all_ libs publishable. But that prohibitively limits the kind of typescript aliases that may be used to `@just/two-levels`, which is a shame as it removes a lot of flexibility.

It is not possible to provide a schematic that will guarantee a library's source will be publishable as is. A better strategy is the one suggested here, where a transform step is added at build time to selectively rewrite aliased paths to relative. 

Before using Nx, my company has had success with this strategy before, where a modified version of ng-packagr that did this rewriting enabled us to publish legacy libraries without needing to permanently rewrite all ts paths.

**Comment by marsicdev** [comment]
Any updates on this?

**Comment by shlajin** [comment]
I would love to see absolute imports not only for libraries, but for everything within one package.
A simple example would be shortening this
```
import IconTrash from '../../../../../../assets/icons/IconTrash';
```

to this

```
import IconTrash from '~/src/assets/icons/IconTrash';
```

Note that I don't want to specify the package name with the absolute import, this helps me keep packages within boundaries and it makes moving / renaming easier if necessary.

**Comment by Yedidyar** [comment]
> I would love to see absolute imports not only for libraries, but for everything within one package.
> A simple example would be shortening this
> ```
> import IconTrash from '../../../../../../assets/icons/IconTrash';
> ```
> 
> to this
> 
> ```
> import IconTrash from '~/src/assets/icons/IconTrash';
> ```
> 
> Note that I don't want to specify the package name with the absolute import, this helps me keep packages within boundaries and it makes moving / renaming easier if necessary.

Has anyone solved this problem?
