### ISSUE TITLE
core: add workspace TS solution config file

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#3413]
## Description
Since v10, every lib and app generates with solution files (tsconfig with references). 
It would be great to apply this setting to root workspace level

## Motivation
With workspace root solution file, we can:

- effectively run type-check/compilation on whole monorepo by running one command `tsc -b`
  - you might be thinking, why would one need that, as those checks are partially executed from webpack builds/ts-jest. 
  - well, if we use just `jest` and custom bundling (without running TS Fork checker), then we need to run `TS` "manually" 
- use incremental build TS perf optimization
- be ready for TS 4.0 ([which supports incremental builds with `noEmit`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#noemit-and-incremental) -> used mainly with React projects, where babel takes the main role of transpiler)

## Suggested Implementation

- generate `tsconfig.json` in the root

```jsonc
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {},
  "files": [],
  "include": [],
  "references": [
    // every app/lib schematic should add its path here
    {
      // generated library
      "path": "./libs/ui-test"
    },
    {
       // generated app
      "path": "./apps/todos"
    }
  ]
}
```

- update `tsconfig.base.json`

```diff
"compilerOptions": {
- "declaration": false,
+"composite": true,
+"incremental": true,
+"emitDeclarationOnly": true,
+"declarationMap": true,
}
```

- now to type check whole monorepo `tsc -b` will take some time
- consecutive `tsc -b` will be instant (if someone modifies code, just modified tree path will be checked)

### Drawbacks

With incremental builds and project refs, TS needs to have all paths set within its config. 

That means if, if this feature would be applied, all test files will need to be updated, like following:

**libs/a-react-one/tsconfig.spec.json**

```diff
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["jest", "node"]
  },
  "include": [
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.spec.js",
    "**/*.spec.jsx",
    "**/*.d.ts"
+  "**/*.tsx",
+  "**/*.ts",
  ]
}
```

Otherwise we'd get TS errors 
![2020-07-27 at 10 26 AM](https://user-images.githubusercontent.com/1223799/88520443-dffb1c80-cff3-11ea-8274-0ac199d7ffbf.png)

**Comment by vmcbaptista** [comment]
Hi. I believe this relates with #3409.

**Comment by FrozenPandaz** [comment]
Those are interesting reasons to have a `tsconfig.json` at the root.

I didn't want to add a solution style config that lists out all of the different projects because it becomes another file that needs to analyzed carefully to see what projects are being affected when the file is touched. I also think running global operations on the workspace like that becomes expensive and unmanageable at a certain scale.

I think writing a builder to run those operations on the individual projects is better so that we can use `affected` to optimize which parts need to be re-operated on.

For incremental builds, I again think we'll stick with using `run-many` or `affected` to execute `build` on projects which can then be built incrementally. Is it beneficial to use `tsc` on an entire workspace when it might contain different apps that you're not currently working on?

What do you think?
