### ISSUE TITLE
Generate Apps/Libs in nx plugins

### ISSUE THREAD

**Issue by myin142** [nrwl/nx#3445]
## Current Behavior

When trying to generate apps in a workspace generated with `create-nx-plugin`, it will be put in the e2e folder. And when trying to move it to the package folder with `nx g mv --project-name <project> packages`, it will be moved to the apps folder and will be renamed to `packages`.

Generating libs is not even possible. Fails with `Cannot read property 'paths' of undefined`.

## Expected Behavior

Do not know what the expected behavior should be. I was trying to create a package that is not a nx plugin.
Maybe give a proper feedback that apps/libs are not supported? Or these are bugs.

## Steps to Reproduce

- Create a new nx plugin project with `create-nx-plugin`
- Generate app or library of any nx schematic
- One of the outcomes from above will happen

### Environment

  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.2
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 10.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.2
  @nrwl/linter : 10.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.0.7
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.2
  typescript : 3.8.3

**Comment by masonembry** [comment]
I'm having the same problem. Cannot generate react libs. `Cannot read property 'paths' of undefined`. Any updates or workarounds on this?

**Comment by nelsieborja** [comment]
Same issue here, such a blocker can't create a new library.

**Comment by Cammisuli** [comment]
When creating a workspace with `create-nx-plugin` we expect that the workspace will be mostly used for plugins. So by default all apps go into `e2e` and all libs go into `packages`. This can be changed in the nx.json by changing the `workspaceLayout` to something like: 
```
"workspaceLayout": {
    "appsDir": "packages",
    "libsDir": "packages"
  }
```

Also, the `mv` command looks like it's working as expected because apps/libs will be placed into the associated dir that's mentioned in the workspace layout.

Give it a shot with the latest version, and if it's still reproducible open a new issue. Thank you!
