### ISSUE TITLE
Generate nx workspace without node_modules folder

### ISSUE THREAD

**Issue by devjack-front** [nrwl/nx#3587]
Can I run npx create-nx-workspace ....  and it generate without install the packages? 
I'm automating this creation e it not need the node_modules folder

**Comment by webberwang** [comment]
I would look into https://www.hygen.io/ or https://yeoman.io/ if you want more control in scaffolding apps.

Wouldn't really make sense to add a flag to omit node_modules for `create-nx-workspace`

**Comment by vsavkin** [comment]
You could generate the Nx workspace with the node modules, remove the node-modules and templatize the generated content.

Unfortunately, we have to install node modules because when you select a preset, we fetch that package from the registry to create the needed apps and libs, and that requires an 'npm install'.

Sorry, but I'll have to close this. Supporting this use would require us to rework workspace creation from scratch, which isn't in the roadmap.
