### ISSUE TITLE
How I can extract a library with React components as a separated JS file with all dependencies included? 

### ISSUE THREAD

**Issue by emanuelcostea** [nrwl/nx#3602]
## Description
I have a component library with various React components and storybook attached to it. Would like to extract this components and later to be able to use them independently without nx.
I was looking over https://nx.dev/react/plugins/web/builders/package but I can't figure it out what settings I would need to add to be able to run the package command. When I try to run it, it says that there is no target 'package' available.

**Comment by scdc** [comment]
For packaging web module you should add the following code to your web library the package builder inside your nx workspace.json or angular.json file
```
"architect": {
...
  "build": {
          "builder": "@nrwl/web:package",
          "options": {
            "project": "libs/plugins/package.json",
            "entryFile": "libs/plugins/src/index.ts",
            "outputPath": "dist/libs/rakuten",
            "tsConfig": "libs/plugins/tsconfig.lib.json",
            "external": []
          },
          "configurations": {
            "production": {}
          }
        }
}
```

But for react project and library, I think there a specific plugin for that and the web packager plugin will not be sufficient

**Comment by emanuelcostea** [comment]
Thank you for your response. 
I added something similar and the build process is working, but now I have an issue with resources that are included from another library.

This is the definition that I use for build target
```
        "build": {
          "builder": "@nrwl/web:package",
          "options": {
            "outputPath": "dist/libs/components",
            "tsConfig": "libs/components/tsconfig.lib.json",
            "project": "libs/components/package.json",
            "entryFile": "libs/components/src/index.ts",
            "external": ["react", "react-dom", "react-is", "styled-components"],
            "babelConfig": "@nrwl/react/plugins/bundle-babel",
            "rollupConfig": "@nrwl/react/plugins/bundle-rollup",
            "assets": [
              {
                "input": "libs/shared/assets/src/lib",
                "glob": "**/*",
                "output": "assets"
              }
            ]
          }
        },
```
```
Error during bundle: Error: /Projects/web/libs/components/src/font-faces.ts(1,25): semantic error TS6059: 
File '/Projects/web/libs/shared/assets/src/index.ts' is not under 'rootDir' '/Projects/web/libs/components/src'. 
'rootDir' is expected to contain all source files.
Bundle failed.
```

`libs/shared/assets` is another library with all static assets (images, svgs and fonts). `/libs/components` is the library that I want to build as separated package. `rootDir` is not defined in tsconfig.json from components library and if I define it I still get the same error.

How I should handle this case? When one library uses static assets from another library?

**Comment by iorran** [comment]
@emanuelcostea that issue you are facing is the same I'm facing.

For example, let's say I have a library A and it's buildable/publishable... and it depends on library B...

All child libs must be buildable/publishable!

**Comment by emanuelcostea** [comment]
> @emanuelcostea that issue you are facing is the same I'm facing.
> 
> For example, let's say I have a library A and it's buildable/publishable... and it depends on library B...
> 
> All child libs must be buildable/publishable!

Added the build target with the same options for my shared/assets library.
```
Error during bundle: Error: Unexpected character ' ' (Note that you need plugins to import files that are not JavaScript)
Bundle failed.
Error during bundle: Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
Bundle failed.
```

I get this error now, I presume is because I have static assets in that library (svgs, pngs and fonts files).

**Comment by iorran** [comment]
@emanuelcostea we are on the same page now! Let's find a way to solve it.

**Comment by asherccohen** [comment]
The rootDir issue can be fixed with by telling the main tsconfig.base.json to get built artifacts instead of using dev folders for typescript compilation.

Confusing, I know, but these steps should be clear:
- update to the latest NX (10 at this point in time) since it adds the --publishable and --buildable flags for your future libs
- open root level  tsconfig.base.json
- Scroll to the paths property and add this to it:  "@yourWorkspaceName/*": ["dist/libs/*"]

RootDit issue should be solved. I'm still fighting against assets, any suggestion as to why my project doesn't read from the glob?

**Comment by asherccohen** [comment]
UPDATE:

I have discovered a better way to fix the above problem. Instead of manually changing your tsconfig.base.json, AFTER UPDATING,  do this:

``` yarn build myLib --with-deps --buildLibsFromSource ```

Following the cryptic docs at [https://nx.dev/react/plugins/node/builders/build]

Now, what I noticed instead is that if we have a src/assets folder this is not copied automatically. 
Structure is:

```
src/assets
    /fonts
    /styles
```

We have to add this to our lib workspace:

```
            "assets": [
              {
                "glob": "README.md",
                "input": "libs/myLib/",
                "output": "."
              },
              {
                "glob": "**/*",
                "input": "libs/myLib/src/assets",
                "output": "assets"
              }
            ]
```

Which is not a problem itself, it's just not intuitive. BUT! 

1. I had issues copying assets over with git bash on Windows, the files would be completely ignored and no error would show.
I had to use WSL to workaround it and still haven't tried on a CI (worried this can be a blocker).

2. The assets are copied TWICE! Once in the appropriate dist/myLib/assets/folder and then also in dist/myLib/assets

@jaysoo Would you like to look into this?

**Comment by emanuelcostea** [comment]
I still can't get pass the rootDir issue, I have a setupTests.ts file on project root and is the first file that is imported on the project
I've tried @asherccohen suggestions but with no luck at all.

`File 'web/libs/components/setupTests.ts' is not under 'rootDir' 'web/libs/components/src'. 'rootDir' is expected to contain all source files.`

**Comment by asherccohen** [comment]
Can u provide a minimum setup or an image of your folder structure to understand your problem?

Also what command did u use to create the lib?

**Comment by dangviettuan** [comment]
I got the same error as this issue. Here is example source code: https://github.com/dangviettuan/nx-publishable
I have: 
- capitalize util
- button lib
- button showcase lib (publishable)
When I build the button showcase lib an error occurs like the picture below
![image](https://user-images.githubusercontent.com/11323132/105975033-16a81180-60c1-11eb-815d-85ec8849286e.png)
