### ISSUE TITLE
Cannot build my project, rollup namedExports issue

### ISSUE THREAD

**Issue by joshribakoff** [nrwl/nx#3629]
## Current Behavior
Cannot build https://github.com/rx-store/rx-store

Gives errors like:

`Error during bundle: Error: 'unstable_runWithPriority' is not exported by node_modules/scheduler/index.js
Bundle failed.`

I can't seem to find any way to get Nx to tell me what Rollup command it is running to easily debug this.

## Expected Behavior
It should build. It should be easier to debug the rollup setup if something goes wrong. How do I know what version I am on?

## Steps to Reproduce
Clone https://github.com/rx-store/rx-store & run `nx build visualizer`

### Environment

```
➜  rx-store git:(master) ✗ nx report

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.0.7
  @nrwl/cli : 10.0.7
  @nrwl/cypress : 10.0.7
  @nrwl/eslint-plugin-nx : 10.0.7
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.7
  @nrwl/linter : 10.0.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.0.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.7
  @nrwl/web : 10.0.7
  @nrwl/workspace : 10.0.7
  typescript : 3.9.7
```

Maybe related: https://github.com/rollup/rollup/issues/3755

**Comment by Bielik20** [comment]
I have the exact same problem. I occurs when I use `Formik` (because it uses `scheduler`) and try to build a library (works fine for app though).

I have found a similar [issue on StackOverflow](https://stackoverflow.com/questions/59085618/external-library-using-rollup-js-with-formik-doesnt-respect-named-exports) but was unable to test it yet.

**Comment by Bielik20** [comment]
I feel like I have found the problem. Libs include all packages not listen explicitly in `external` in `workspace.json`.

The reason for that is here: https://github.com/nrwl/nx/blob/e6e2dc67aac472aa4fafebf50e98af8a98c94984/packages/web/src/builders/package/package.impl.ts#L236-L237

In my example printing dependencies gives:
```js
dependencies [
  {
    name: 'npm:yup',
    outputs: [],
    node: { type: 'npm', name: 'npm:yup', data: [Object] }
  },
  {
    name: 'npm:formik',
    outputs: [],
    node: { type: 'npm', name: 'npm:formik', data: [Object] }
  },
  {
    name: 'npm:react',
    outputs: [],
    node: { type: 'npm', name: 'npm:react', data: [Object] }
  }
]
```

That translates to names:
```js
[
  'npm:yup',
  'npm:formik',
  'npm:react',
]
```

Obviously there is no package `npm:formik`. That's why it tries to bundle formik (in my case) with lib, which causes the error.

---

I am not sure if that should be a separate issue but it looks like a major problem and a bug. I would expect dependencies to not be bundled. Simple fix would be to split the name:

```ts
    const externalPackages = dependencies
      .map((d) => d.name.split(':')[1])
```
