### ISSUE TITLE
Dependency graph unreadable, nodes too small

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3701]
The node sizes are too small relative to the edge distances. It makes it difficult to read. Zooming in forces you to scroll excessively

<img width="1239" alt="127_0_0_1_4211" src="https://user-images.githubusercontent.com/26264925/92691426-65faca80-f2f7-11ea-9260-a9339ad37907.png">

## Description

Have a more sensible node size

## Motivation

More readable when projects get large

## Suggested Implementation

Modify d3 node/edge configurations

**Comment by cbejensen** [comment]
Indeed, our project has gotten so big that the dep graph isn't very useful. Here's our dep graph on a project with over 80 libs, with all libs selected:

![image](https://user-images.githubusercontent.com/12374723/94710223-d21f8b80-0303-11eb-9801-b0b467bbc45c.png)

Here's just the leftmost portion zoomed in:

![image](https://user-images.githubusercontent.com/12374723/94710341-fa0eef00-0303-11eb-898d-4720257949f2.png)

**Comment by juliusstoerrle** [comment]
I experience the same, but with even less nodes. What also makes it very hard for me to use is the low vertical spacing. I usually have to deactivate my shared libraries, to reduce the number of horizontal arrows to a level that I can still trace the remaining to the next node. It would be great if the vertical size can be configured or set to something larger, instead of trying to push everything on the horizontal axis.

**Comment by cbejensen** [comment]
Replying to keep the issue active.

**Comment by joshribakoff-sm** [comment]
re-open? the chart is still very cluttered and drawn poorly. zoom feature is also currently broken, it constantly zooms back out while trying to manipulate the zoom/pan
