### ISSUE TITLE
Not able to perform any action cause of the following error.

### ISSUE THREAD

**Issue by rajendrav5** [nrwl/nx#3808]
## Current Behavior
node_modules\.bin\ng.cmd' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:4
+ & {c:\Users\node_modules\.bin\ng.cm ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Users\712545...les\.bin\ng.cmd:String) [], CommandNotF 
   oundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mandarini** [comment]
Hi there @rajendrav5 ! Thanks for filing an issue! 

Can you please help us reproduce your issue, by providing some steps, or your environment, or even a repository that reproduces this?

Thank you very much and I really hope we can help you out!

**Comment by rajendrav5** [comment]
It is a private code, unfortunately cannot share more details, 
I was just trying to `run npm scripts` through nx and it throws this error.

**Comment by mandarini** [comment]
Hi @rajendrav5 ! 

I understand that it's private code, but could you at least provide some more details (eg. your environment), or a least a sample repository, which imitates some of the things you do in the private repository, to help me understand a little bit better and be able to reproduce, in order to help you?

Thank you so much!
