### ISSUE TITLE
Next Base Path

### ISSUE THREAD

**Issue by hloughrey** [nrwl/nx#3825]
## Current Behavior

When I use the [base path](https://nextjs.org/docs/api-reference/next.config.js/basepath) config and run `nx serve myApp` I can load my app on the specified base path, but when I run `nx build myApp --prod` & then run the app, the base path is ignored. 

## Expected Behavior

Should be able to render my app from both dev & production builds on the base path URL

## Steps to Reproduce

1. `npx create-nx-workspace@latest`
![Screenshot 2020-09-28 at 16 36 42](https://user-images.githubusercontent.com/7842215/94453796-029ee280-01a9-11eb-9d7a-30fb289de0b9.png)
2. `cd my-org/apps/todos`
3. Edit next.config.js to be `module.exports = { basePath: '/something' };`
4. `nx serve todos`
You'll find the todos app on `localhost:4200/something` 👍
5. `nx build todos --prod && cp package.json dist/apps/todos && yarn && npx next start`
The todos app renders on `localhost:3000` not `localhost:3000/something` 😢
![Screenshot 2020-09-28 at 16 28 10](https://user-images.githubusercontent.com/7842215/94456844-adb09b80-01ab-11eb-8b18-237b7ecfc5f7.png)

### Environment

```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : 10.2.1
  @nrwl/node : Not Found
  @nrwl/react : 10.2.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

**Comment by mandarini** [comment]
Hi there @hloughrey ! Thanks for filing an issue!

I think that this is not a bug of Nx, but rather the way Next.js and the [`basepath`](https://nextjs.org/docs/api-reference/next.config.js/basepath) in `next.config.js` works, since [the Next.js server uses it](https://nextjs.org/docs/api-reference/next.config.js/introduction).

In order to solve your issue and be able to serve your production app from within the build dist directory of your app, you should copy your `next.config.js` in the `dist/apps/todos` directory, next to the `package.json`.

Please let me know if this solves your issue, and if you would like any other help!

**Comment by mandarini** [comment]
@hloughrey 
To see what I mean (that this seems to be the way Next.js works, rather than an Nx bug), you can try the following:

1. Create a new `next.js` app (just a next app, outside of the Nx scope, [using the next CLI](https://nextjs.org/docs/api-reference/create-next-app) (the command is `npx create-next-app`)
2. Create a `next.config.js` in the root of your project directory (next to `package.json`) ([reference](https://nextjs.org/docs/api-reference/next.config.js/introduction))
3. Make the contents of `next.config.js` to be `module.exports = { basePath: '/something' };`
4. Build the app (`yarn build`)
5. Run the built app (`yarn start`)
6. Go to [localhost:3000/something](http://localhost:3000/something) and verify that your app works!
7. Delete `next.config.js`
8. Run the built app (`yarn start`)
9. Go to [localhost:3000/something](http://localhost:3000/something) and verify that you get a 404
10. Go to [localhost:3000](http://localhost:3000) and verify that your app seems to work, unstyled though, since all css files (and other imports) are under '/something`. The exact same thing happens when you do this in the Nx context.

So, with this we can verify that the Next.js server needs the `next.config.js` file to map the basePaths.

**Comment by mandarini** [comment]
Let me know if you think we should close this issue now, or if you need any help/guidance! :)

**Comment by hloughrey** [comment]
Hi @mandarini 

Ah, that's brilliant. 
I had tried running a Next production build in a non NX project and it worked, but come to think of it, that's probably because `next.config.js` was at the root as you've pointed out. 
That's a great help...thank you.

**Comment by mandarini** [comment]
Glad I could help :) :)
