### ISSUE TITLE
webpack dev server Proxies break historyApiFallback

### ISSUE THREAD

**Issue by ericwooley** [nrwl/nx#3859]
## Current Behavior

Loading a url with uri segments does not fallback to index.html after enabling proxies. This should be possible, according to [this](https://stackoverflow.com/questions/36138936/how-to-setup-a-webpack-dev-server-using-both-historyapifallback-and-proxying-rem)

## Expected Behavior

All urls should return index.html.

## Steps to Reproduce

Follow the react tutorial, add api's (I don't have time to actually do this ATM, but i'm confident it will work)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : 10.2.1
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.2.1
  @nrwl/react : 10.2.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7

**Comment by ZackDeRose** [comment]
Hi @ericwooley, I've attempted to reproduce this issue in the following repo, but appear unable to create the issue: https://github.com/ZackDeRose/webpack-dev-server-proxy-breaks-history-api-fallback-3859

If I'm somehow misunderstanding your report of the bug or the steps to reproduce, please reopen this ticket with some feedback on the behavior you were seeing vs. expected behavior. Thanks!!
