### ISSUE TITLE
shouldn't App/Libs have their own package.json?

### ISSUE THREAD

**Issue by nahumzs** [nrwl/nx#3878]
I have been playing briefly with `nx` (amazing tool) and this is more a question to understand the decision rather than a suggestion. 

Wondering why after creating a new lib under the libs folder this one doesn't own their own `package.json`?

From my understanding lacking from a package.json per package/app/lib, you are preventing your ecosystem from moving independently. 

For example:

### Team 1
Creates App1 which imports `@some-ui/Button` `v1.0`

### Team 2 
Creates App2 which imports `@some-ui/button` `v1.0`

/ time pass (weeks, months) / 

### Team 1 
Doesn't touch their app again, and work on App3

### Team 2
Keep investing a lot of time on App2 and now `@some-ui/button` has been progressively changing versions and currently is at  `v5.0`

For **team 2,** each time they bumped `@some-ui/button` to a new version were forced to go into **App1** and update their dependencies, breaking changes, and fix test cases. This because the entire repo is under one **package.json** only one version can exist per lib. This doesn't seem a really good deal for Team 2 IMHO (as far my I understand with my limited `nx` knowledge).

The flip side:
If each app / lib have their own package.json they would be able to have an independent version of libraries, isolating them from the velocity of other teams.  This is how lerna handle packages with yarn workspaces.

Any reason why `Nx` don't do it? It's an opinionated decision where the repo forces the entire organization to always keep their dependencies up to date? or am I wrong and each lib/app can have their own dependencies and I only need to initiate a package.json in each lib/app?

**Comment by gagle** [comment]
It seems that Nx cannot be used for your use case then. If you need to update app1 and you're not allowed to do that then you cannot have app1 inside a Nx monorepo

**Comment by Squixx** [comment]
The idea would be that whenever _anyone_ makes a breaking change, this get fixed in all downstream apps.

So whoever made the changes to ```@some-ui/button v1.0``` tests were run on app1 and are kept inline.

advantage: whenever breaking changes are done they are fixed in all apps. So when doing a small change in any app,  you dont have to spend a day figuring out dependency changes

disadvantage: some changes might become bigger, so you'll sometimes have to do smaller breaking changes that might take more work in the short run.

we currently have a setup where some libs in our NX repo are _also_ published to npm. To be used by applications outside of our NX monorepo. So a hybrid approach is possible as well.

To be honest having a package.json generated with the NX schematics could be usefull. Right we add them through our own schematics

**Comment by nahumzs** [comment]
> we currently have a setup where some libs in our NX repo are also published to npm. To be used by applications outside of our NX monorepo. So a hybrid approach is possible as well.

Yes, thank you for your answer @Squixx I have been thinking about it as I keep working with `nx`.

I think one main advantage of `nx` approach is somehow a culture where everybody is responsible for the health of the repo instead of isolated teams that only cares for their slices of the product. I think this is really good from an organizational perspective. 

> To be honest having a package.json generated with the NX schematics could be usefull. 

What do you mean, like have the ability to create package.json files for lib independently?
