### ISSUE TITLE
Libraries are not Tree Shakeable.

### ISSUE THREAD

**Issue by ItaiYosephi** [nrwl/nx#3920]
## Current Behavior
Importing a module from lib to app causes the whole lib to end up in the main bundle (everything that's exported in the lib's index.ts).

## Expected Behavior
Only what imported should end up in bundle.

## Steps to Reproduce
1) Generate nx workspace with angular app
2) Generate angular library
3) Generate 2 modules in lib and export in index.ts
4) import one of the modules to AppModule
5) the other module will also end up in the bundle

GitHub Repo: [nx-tree-shake](https://github.com/ItaiYosephi/nx-tree-shake)
Card module ends up in bundle even though it's never used or imported.

### Environment

  nx : Not Found
  @nrwl/angular : 10.3.0
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3

**Comment by brandonroberts** [comment]
@ItaiYosephi Is this with a production build also? Running a build without production mode is not going to tree shake unused modules.

**Comment by philipjfulcher** [comment]
I think there be some misunderstanding about how tree shaking works in Angular. A few things to note:

1) @brandonroberts is right, tree shaking will only happen when building in production mode, specifically with the `optimization` flag set to true. It's unclear if you've enabled the optimization here.
2) The `console.log` method you have of testing whether code is tree shaken isn't reliable as it exists outside of an Angular module, component, or service.
3) Tree shaking can happen at multiple levels, so a component may get tree shaken but not the module it's a part of, depending on how it's constructed.

I've created a fork of your repo with some tools and sample code to enable some experimentation: [https://github.com/philipjfulcher/nx-tree-shake](https://github.com/philipjfulcher/nx-tree-shake)

There are two npm scripts in the repo: `npm run analyze` and `npm run analyze:optimized`. These two commands will run the build in different configs (unoptimized and optimized) and then use webpack-bundle-analyzer to show a visualization of the code in the bundle.

You should be able to use these scripts to experiment with some different configurations to see how the tree shaking works. For example, running `npm run analyze` will run the dev build, and you should see both the button and card modules, as well as the button and card components. Running `npm run analyze:optimized` will show a different result: the button module and component are there, but only the card module is there. The card component itself, since it's unused, has been tree shaken away. 

Using the webpack-bundle-analyzer should be a more accurate way of determining tree shaking behavior. I've also added some example code that copies the `ui` library into the app. It has the same sort of `index.ts` file that an Nx library has and should behave the same way. If you change the app module to load the modules from there instead do of the library, you should see the same results.

So there's nothing about using an Nx library that should prevent tree shaking from working, but there are different scenarios that may impact how much can be tree-shaken away. In this particular example, it may be a better choice to separate the button and card modules into their own libraries. Then, if the card module is never imported, it'll never be a part of the compilation in the first place, so tree shaking doesn't even apply!

I'm going to close this bug since the issue doesn't seem related to how Nx implements libraries, but I hope some of this helped. :)

**Comment by Tbhesswebber** [comment]
@philipjfulcher - Is there any NX documentation on configuring tree shaking that you could link to for those of us that stumble upon this issue after the fact? Ideally, something that talks about solutions for various scenarios?

**Comment by philipjfulcher** [comment]
@Tbhesswebber - There's nothing about tree-shaking configuration that's specific to Nx. Nx passes the configuration options to the `@angular-devkit/build-angular` executor. Because that is external to Nx and can change at any time, your best bet is to refer to the latest Angular configuration docs, which are currently [here](https://angular.io/guide/workspace-config).

**Comment by Tbhesswebber** [comment]
Is this a standard expectation for framework executors or do all builds go through that? It seems odd that a non-angular application would be running through angular optimizations

**Comment by philipjfulcher** [comment]
@Tbhesswebber - Each app will have its own executor, I referred to the primary executor for Angular here because that's what the original ticket was about. If you have more questions about optimization across frameworks, you can ask those questions in the [community Slack or during our Office Hours](https://nx.dev/community).
