### ISSUE TITLE
Folders `e2e` and `src` are still there after migration to nx

### ISSUE THREAD

**Issue by meeroslav** [nrwl/nx#3944]
## Current Behavior
After migrating angular CLI built application to NX, all code is migrated but original folders `e2e/src` and `src/app`, `src/assets` and `src/environments` are still there.

## Expected Behavior
Original folders should be removed once the code is successfully migrated to `apps` and/or `libs`

## Steps to Reproduce
```bash
ng new test123
cd test123
ng add @nrwl/workspace
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
None

### Environment
Node: 14.4.0
Angular CLI: 10.1.7
OS: OSX Catalina

**Comment by mandarini** [comment]
This PR will be closed. Deleting the folders proves to be a bit trickier than anticipated, since they are empty, and `host` cannot really perceive them. We could delete the folders via `fs` but this could create some ugly tests.

So, this PR will be closed for now (it may be revisited in the future). It is a small price to pay to delete once the remaining, empty, `src` and `e2e` folders. Since they are empty, they are not even added in git.
