### ISSUE TITLE
Allow `implicitDependencies` flag to trigger rebuild while serving

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3947]
## Description

Say B depends on A, we can use `waitUntilTargets` & `implicitDependencies` for A to complete serving first before starting B. 

`nx serve B --with-deps --parallel` would start A then B.

But if A is re-built due to code change, B doesn't reload. We need some way for B to re-load as well anytime A changes.

`implicitDependencies` currently doesn't trigger re-builds.

## Motivation

Allow rebuilding of dependencies while serving projects

## Suggested Implementation

Would be related to code that controls `waitUntilTargets`

## Alternate Implementations

N/A

**Comment by wSedlacek** [comment]
Could this be reopened?
The `@nrwl/node` executors seem to only build their dependencies on initial startup and if something is changed it is not rebuilt.
In contrast to `@nrwl/angular` the dependencies are never built while serving (I presume because they are just imported by typescript path references)
