### ISSUE TITLE
ng serve + ng test ogether

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#4025]
## Description
I would like to have an ability to watch tests (jest) while ng serve working so get possibility to catch test failure on local machine 
## Motivation

It's a good practise which has been removed in CLI for performance reason without possibility to optional run this.

**Comment by fbaba-nibtravel** [comment]
You can open another terminal and run both at the same time. Also, if you use VSCode, there are some extensions that keeps jest unit tests in watch mode at all times and this means that if you change code and there are unit test covering that line, it will point out whether this is breaking the tests or not.

Having said that, for small code base this is an ok practice, when you are dealing with a large code base, the possibilities of failure, specially during refactor work, are large. I end up turning off all this stuff because it would freeze the IDE and most of the times, it would require an IDE restart. 
Running the tests in parallel along with ng serve is a bit better, but not convinced its something that I would run all the time.

**Comment by brandonroberts** [comment]
Thanks @Lonli-Lokli. You can achieve this today by running separate terminals, or using the run commands if you always want them to be started together. If you need more support, check out our [Slack workspace](https://bit.ly/2ZApcSo)
