### ISSUE TITLE
ESLint or Prettier is not working

### ISSUE THREAD

**Issue by taitruong** [nrwl/nx#4033]
## Current Behavior

ESLinter using `nx lint` should list all warnings and errors based on .prettierrc

## Expected Behavior

ESLint should log warnings and errors.

## Steps to Reproduce

Create an nx workspace with provided sample angular app.
Changed singleQuote from true to false in .pretierrc.
Starting `nx lint` tells me "All files pass linting":

```
$ nx lint
> ng run ng-eslint:lint 
>  NX   NOTE  Cached Output:
Linting "ng-eslint"...
All files pass linting.
```

### Environment

  nx : Not Found
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : 10.3.2
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5

**Comment by taitruong** [comment]
I found the problem through this: https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project
Basically you need to install and configure eslint-plugin-prettier:
- npm install -D eslint-plugin-prettier
- add these 3 lines in .eslintrc.json:

```
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    // add these 3 lines:
    "plugin:@typescript-eslint/recommended", // Uses the recommended rules from the @typescript-eslint/eslint-plugin
    "prettier/@typescript-eslint", // Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
    "plugin:prettier/recommended" // Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
  ],
```

Now `nx lint` works like a charm :).

Optionally you can also clean these up:
- uninstall tslint // nx stills has that when creating a new workspace with angular and eslint
- remove all tslint.json files
- define default formatter in VS Code by creating a settings.json in .vscode folder:

```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "eslint.format.enable": true,
  "eslint.alwaysShowStatus": true,
  "editor.detectIndentation": false,
  "typescript.validate.enable": false,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
```

**Comment by FrozenPandaz** [comment]
Hi, thanks for reporting the issue. I actually think this is working as intended. Let me explain.

We currently use `eslint-config-prettier` which _disables_ rules that conflict with formatting checks from `prettier`. To check that your files are prettier compliant, you would use `prettier --check`. In Nx, we have a command, `nx format:check`, which will do this intelligently for whichever projects are _affected_ (excluding files that aren't touched) which is significantly faster when you have _a lot_ of files in your workspace.

As you have found, there is another npm package called `eslint-plugin-prettier` which uses Prettier _inside_ of ESLint to produce ESLint failures and fixes for non-compliant files. This is pretty cool :smile:.

However, the reason we choose to use `eslint-config-prettier` is to separate the concerns of _formatting_ vs _enforcing best practices_. Prettier is used to format many types of files other than JS/TS files such as `.md`, `.json`, `.scss`, `.html`, etc.. ESLint, generally does not run on these files as it is mostly focused on JS/TS files. Because of this, we think it's better that `prettier` handles the _formatting_ and ESLint focuses on _enforcing best practices_ in the code. While it is possible to include other types of files in ESLint, I think that should be done when you are concerned with _enforcing best practices_ in that code and not _formatting_.

You may of course configure your workspace otherwise, but this is our recommendation.

Does that make sense?

**Comment by taitruong** [comment]
Hi, thanks for elaborated answer and yes it makes sense. It would help to document it somewhere - or I could find it.

Thanks, Tai

**Comment by krismeister** [comment]
That is good insight @FrozenPandaz . In case someone finds this in the future. There is CLI tool that comes with `eslint-config-prettier` which will tell you which ESLint rules are in conflict with your `.eslintrc.json` settings. 
```
npx eslint-config-prettier .ts
// and
npx eslint-config-prettier .html
```

The output will be something like this:
```
The following rules are unnecessary or might conflict with Prettier:

- quote-props

The following rules are enabled but cannot be automatically checked. See:
https://github.com/prettier/eslint-config-prettier#special-rules

- quotes
```
Deactivating the rules will make sure your prettier rules take precedence.
