### ISSUE TITLE
Build libs to use as umd

### ISSUE THREAD

**Issue by seta-louisle** [nrwl/nx#4084]
## Description

When I run `nx build js --with-deps --skip-nx-cache`

Rollup bundles js package and all dependent libraries. However, this common is currently not adding dependencies properly

I like end **umd** package to include all dependencies including react, sub libraries etc. so people can use them via cdn (similar for esm, end user's shouldn't import my library component separately). 
 
NX is already doing incremental bundles so I guess it's possibly to do  small fix on rollup config file but right now I haven't figured out how to do that.
I tried to follow this https://nx.dev/latest/angular/guides/ci/incremental-builds but no success? If you have any ideas, pls help! Many thanks

![error_message](https://user-images.githubusercontent.com/68586155/99058918-69991f00-25d0-11eb-95b0-fd524fc951b5.png)

**Comment by tanepiper** [comment]
I'd also like to understand this, I've asked in the nx support slack but never got an answer.

Because https://github.com/tanepiper/rxjs-primitives is just a set of functions on a public API, I decided to use @nrwl/node for the library generator for `--publishable` vs the web one, but it's not very clear how to add umd support to a library and build out main, module and es2015.

When I use the library in Angular I get `CommonJS or AMD dependencies can cause optimization bailouts`
