### ISSUE TITLE
After "nx (or ng) g app my-app, jest tests no longer run (for any app in the repo)

### ISSUE THREAD

**Issue by tcoz** [nrwl/nx#4103]
## Current Behavior

Using 
@angular/core "^10.0.14
@nrwl/workspace ^10.3.1
@nrwl/jest 10.3.1
jest 26.6.2

When generating a new app in the workspace, tests no longer run (e.g. n[g|x] test my-application). 

How I repro:

Run install on repo. Everything is fine, tests run etc. 

Generate a new app (n[g|x]) g app my-app

This adds a jest.preset.js file to the root of the repo, and the root jest.config is updated with a line like this:

projects: '<rootDir>/apps/somelib/my-app',

Tests are broken until I undo the change to jest.preset.js. 

After generating the app and running nx (or ng) test my-app, this is the error log:

[error] TypeError: (oldOptions[key] || []).map is not a function
    at /Users/Consolazio/Documents/GitHub/company/node_modules/jest-config/build/normalize.js:881:12
    at Array.reduce (<anonymous>)
    at normalize (/Users/Consolazio/Documents/GitHub/company/node_modules/jest-config/build/normalize.js:704:14)
    at readConfig (/Users/Consolazio/Documents/GitHub/company/node_modules/jest-config/build/index.js:224:68)
    at async readConfigs (/Users/Consolazio/Documents/GitHub/company/node_modules/jest-config/build/index.js:406:26)
    at async Object.runCLI (/Users/Consolazio/Documents/GitHub/company/node_modules/@jest/core/build/cli/index.js:230:59)

**Comment by mandarini** [comment]
Hi there @tcoz ! Thanks for filing an issue!

Unfortunately, I could not reproduce your issue. Can you please create a reproduction and share it with me so that I can take a look?

In the meantime, I'll tell you the steps I followed, just to check if we're on the same page:

1. `npx create-nx-workspace@10.3.1 my-wksp --preset="angular" --appName="test-app" --style="css" --linter="tslint"`
2. `cd my-wksp`
3. `nx g app my-app`
4. `nx test my-app`
5. `nx g app --name=my-app --directory=suprematism` (to copy your file structure)
6. `nx test suprematism-my-app` (this is the syntax to execute a task for an app inside a directory)

And the tests run successfully:
<img width="694" alt="Screenshot 2020-11-18 at 12 35 08 PM" src="https://user-images.githubusercontent.com/6603745/99519388-8059c000-299a-11eb-8365-6ac2f4571b29.png">

Here is my repository: [github.com/mandarini/jest-test-10-3-1](https://github.com/mandarini/jest-test-10-3-1)

I also tried with the latest version of Nx, and I encountered no errors there, either. Here is my repo: [github.com/mandarini/test-jest-latest](https://github.com/mandarini/test-jest-latest).

Can you please let me know if you followed some other steps? Or can you please try reproducing the error with the latest version of Nx?

**Comment by tcoz** [comment]
I'm working with an existing nx workspace repo, nothing unusual though. I can't repo this as I'd have to use the client's package.json to do it. 

I created two more apps today, the jest.preset file doesn't get added anymore because it was already added in the prior app creation I mention above, but it still adds the line to the jest.config file, the only difference is it points to the new app. I have to delete it, every time.

**Comment by mandarini** [comment]
Hi @tcoz ! I edited my comment to remove the references to your actual app! Did you checkout out my repos, to see that they work, and see if they match your setup?

If you can provide any more information it would really help me help you! :)

**Comment by BernhardFuchs** [comment]
Had a similar issue and solved it by pointing to `jest.preset.js` file instead of `jest.config.js`.

``` javascript
module.exports = {
  name: 'someLibrary',
  preset: '../../jest.preset.js', <-- before this was pointing to jest.config.js
  ...
```

For me the new `preset` file was generated during last update but older libs were not pointing to the correct file.

The `preset` file should look like this:
```javascript
const nxPreset = require('@nrwl/jest/preset');

module.exports = { ...nxPreset };
```
