### ISSUE TITLE
Migration filename incorrect/missing for Nx0.11.1

### ISSUE THREAD

**Issue by ankemp** [nrwl/nx#418]
The migration: `packages/schematics/migrations/20180404-adding-dep-graph.ts` created in #406.

The name for this file is: `20180404-adding-dep-graph`, yet in #400 `20180405-add-workspace-schematic-command` is created (which is a more recent date).

~~And on that note, I can't even find `20180404-adding-dep-graph` in the [schematics directory] (https://github.com/nrwl/nx/tree/bc559575f524aacbe3d25eb97210101e60de4526/packages/schematics/migrations).
There are only 22 files in the git repo, but on my local (freshly installed) there are 48 (which you'd have to divide by 2, as there's a JS and TS copy of each).~~

Found the missing file(s) on git, still having the issue of the migration in Nx0.11.1 being older than the migration in Nx0.10.X

**Comment by vsavkin** [comment]
Could you provide more info about the issue? The update command isn't working for you?

**Comment by ankemp** [comment]
The update command works fine, but it doesn't seem to always run the required migrations.

What I was trying to say was...
In, PR #400 (merged April 5th) you created a migration: `20180405-add-workspace-schematic-command.ts`
and in, PR #406 (merged April 6th) you created a migration `20180404-adding-dep-graph.ts`

The 406 was merged after 400, but 400 has a newer migration name. So if you were to have updated & ran `yarn update` before 406 was merged you would have never gotten the migration `adding-dep-graph` therefor you wouldn't have those scripts in your `package.json`.

**Comment by vsavkin** [comment]
You are right. We should have used the merge date instead of the creation date.

I'm not sure if it is worth addressing now because we switched to using the default Angular CLI update mechanism in Nx 6. So we will no longer use the nx-migrate command. 

I think the default CLI update mechanism can still have the same issue, so it might make sense to add a check making sure that a PR doesn't add any migrations to an already released version of Nx.

**Comment by ankemp** [comment]
I'll see what I can do about creating a PR.
