### ISSUE TITLE
Allow comments in .json configs

### ISSUE THREAD

**Issue by mikecann** [nrwl/nx#4244]
## Description

It would be nice if Nx supported JSON with comments. This would be helpul for new users of the repo and for documentation.

## Motivation

IMO RushJS does a great job of explaining whats available in its json config by using lots of comments, for example see this file: https://rushjs.io/pages/configs/rush_json/

Rush's FAQ also does a good job of explaining (https://rushjs.io/pages/help/faq/) motivation.

## Suggested Implementation

I assume it would involve removal of usages of JSON.parse with another implementation that supports comments much like RushJS does.

If this is something you feel is valuable and wouldnt be too hard, I dont mind submitting a PR..

**Comment by FrozenPandaz** [comment]
For sure, we would like to support comments in our config files. We have methods that should be used whenever we read JSON files but there are still some other instances of `JSON.parse`This could definitely be cleaned up.

The main caveat here is that we update a lot of our configs automatically and currently, it effectively strips comments when it's updated. We would want to figure out how to preserve comments when updating JSON files. Ideally, we could avoid doing so via AST traversal since that is much more complex than the current API.

Code: https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/ast-utils.ts#L496

The first part is low effort but the second part is more important since without it.. comments will get removed when generating code. We're not currently looking into this but we'd love recommendations for that part.

**Comment by mikecann** [comment]
@FrozenPandaz okay cool thanks, I might take a look at this if I get a sec

**Comment by Hotell** [comment]
I think leveraging json5 standard could be the way forward. 

this lib looks promising https://github.com/noahsug/json5-writer

**Comment by mikecann** [comment]
@FrozenPandaz I believe you guys are working on splitting up the workspace.json for the next update? Might be an ideal time to do this too?

**Comment by tstackhouse** [comment]
I'm kind of running into this at the moment because I have an e2e suite that wile working locally, doesn't yet work on my CI due to waiting for an upstream bugfix, and gets caught up in `affected:e2e` runs, so I have to comment the project out (unless there's a better way).  It seems like the generator scripts are using `JSON.parse` still, as I have to uncomment that code in order to generate a library at the moment.

**Comment by nikparo** [comment]
I'd like to petition to reopen this. We use a liberal amount of comments, and having them stripped from .json files is very annoying.

**Comment by tstackhouse** [comment]
This is still something that could be useful (and it's interesting to see my comment from 18 months ago up there :D ).  A quick way that this could work would be to update the schemas to allow a "comment" field or similar, so we can have comments in our targets for instance.

**Comment by shellscape** [comment]
The further down the Nx rabbit hole I go, the more of these kinds of DX improvement issues I'm seeing closed and abandoned. It's not a great look for Nx.

**Comment by HenryNguyen5** [comment]
This would be really useful to have, its value is easily seen when creating typescript projects, it's great having a commented `tsconfig.json`.
