### ISSUE TITLE
Cannot pass in multiple configurations using -c since nx 11

### ISSUE THREAD

**Issue by leon** [nrwl/nx#4296]
## Current Behavior

```bash
nx run app-api:build -c=production,dev-environment 

Could not find configuration "production,dev-environment" in app-api:build. Valid configurations are: dev-environment, production
```

## Expected Behavior

should be the same as running

```bash
nx run app-api:build --configuration=production,dev-environment
```

this works and applies both production and dev-environment configurations

## Steps to Reproduce

create multiple configurations for a app.
then apply them both using

-c=config1,config2

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

Could not find configuration "production,dev-environment" in app-api:build. Valid configurations are: dev-environment, production

### Environment

```
Node : 14.15.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : 11.0.4
  @nrwl/next : Not Found
  @nrwl/node : 11.0.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5

```

**Comment by yjaaidi** [comment]
This is where it happens:

https://github.com/nrwl/nx/blob/2651ff98f33de251438601bc75a96fff764ba93e/packages/tao/src/commands/run.ts#L111:L123

Should tao merge the configurations?

I'd be happy to help with a PR.

**Comment by dogmatico** [comment]
For us, this change broke the build pipeline as it was incompatible with the ng default behaviour of composing configuration using left to right patching. In particular, in a single tenant app with multiple deployments, we were composing production with a customer specific configuration that just changed the fileReplacements key.

With v10 patching of ng, calling the local ng `-- --c=production,config-1` was compatible with the standard ng behaviour. With v11, no.  We are bypassing the ng patch just for the build of the application and using the nx command for the other relevant stuff like testing and linting.

**Comment by henry-martinez** [comment]
@vsavkin 

This too, broke our build pipeline. We use `nx affected:build -c=production,dev1`. "dev1" only uses `deployUrl` to point to our dev1 url path. This setup has worked beautifully so that we don't have to duplicate all the "production" configurations in each and every dev config.. We have around 12 dev configs per app/lib and a few dozen app/libs, so this multiplies really fast and the config merging saves a lot of replication and maintenance. 

Regarding your workaround to "run twice", I'm not sure I follow how that would apply to our use case. Can you elaborate?
Seems like that would create a lot of unnecessary build time overhead.

Cheers!

**Comment by chrisfitz** [comment]
@vsavkin

Yet another person affected by this breaking change. As the last two commenters have mentioned, I too have several environments that are almost identical in their configuration except for a few properties and I have used the comma separated `configuration` feature that was recommended by the Angular CLI developers on multiple occasions as a way to avoid duplicating the entire configuration for each. I fear that not having this feature, or a reasonable alternative, will become a maintenance nightmare.

While I understand the complexity of continuing to support this feature of the Angular CLI, it's a bit troubling that is was removed without even being mentioned in any meaningful way, either in the Nx 11 blog post or even the patch notes, or given a realistic alternative to users who do use it. 

From your recommended workaround, it seems like you might misunderstand the purpose of this feature as it seems like you're under the impression that running `ng build myapp --with-deps --configuration=conf1,conf2` would build `myapp` twice with each configuration, thus running `ng build myapp --with-deps --configuration=conf1` then `ng build myapp --with-deps --configuration=conf2` as separate tasks would work as a solution. However, running the command twice would not give the desired result as the intention is that `conf1` and `conf2` are merged and only _one_ build is created.

**Comment by georgiee** [comment]
I'v been watching this issue for some time and I would like to second the opinion by @chrisfitz & @henry-martinez on this topic.

@vsavkin has been pretty clear about this topic:

> Given that the use case is somewhat rare and the workaround is straightforward (run the command twice), from now on we will only support one configuration per run.

What gives me hope is this:
> If the workaround doesn't around, please reopen the issue let me know the details, and I'll reassess the situation.


The proposed workaround does not fit the problem. It's about the **configuration composition** feature and not about running multiple builds. We use this feature extensively for our enterprise client and it's the official suggestion by Angular:

> For production builds, you can use configuration composition to execute both configurations:

```
ng build --configuration=production,fr
```

via https://angular.io/guide/i18n

This will take the production config and puts the partial config for the locale `fr` on top of it. This is clearly not "building twice".  

Workaround: We are also forced to use ng directly as nx chose to break this behavior.
Expected Behavior: nx should reflect the configuration composition from the Angular CLI

**Comment by PKSpeleo** [comment]
Hello, @vsavkin 
I am also want to support @georgiee: 
> This will take the production config and puts the partial config for the locale fr on top of it. This is clearly not "building twice".

We also actively use this feature and expecting behavior described in the [Angular documentation](https://angular.io/guide/i18n#apply-specific-build-options-for-just-one-locale): 

![image](https://user-images.githubusercontent.com/13855739/106118043-f4ab9f00-6153-11eb-8814-9fa0da98a748.png)

**Comment by FrozenPandaz** [comment]
Hi everyone,

Sorry, I think there was some confusion with how the Angular CLI handles this behavior.

It should be possible to support this behavior but as @vsavkin mentioned, there are definitely some complexities here. I think we should be able to take this one step at a time though starting with the ability to execute `nx build app1 --configuration config1,config2`.

There is an existing issue also opened by @leon long ago. We'll address this as part of https://github.com/nrwl/nx/issues/2839.

Thank you for being patient and calmly explaining the confusion.

**Comment by MortenGregersen** [comment]
We have the same problem after updating NX, and really need a solution for this as we have 8 brands in 4 different environments. We use a configuration for brand and a need separate configurations for the brand x environment because of the staticness of angular.json and the non-merging nature of Angular's parsing.

> With v10 patching of ng, calling the local ng `-- --c=production,config-1` was compatible with the standard ng behaviour. With v11, no. We are bypassing the ng patch just for the build of the application and using the nx command for the other relevant stuff like testing and linting.

@dogmatico How do you bypass the patching?

**Comment by dogmatico** [comment]
> We have the same problem after updating NX, and really need a solution for this as we have 8 brands in 4 different environments. We use a configuration for brand and a need separate configurations for the brand x environment because of the staticness of angular.json and the non-merging nature of Angular's parsing.
> 
> > With v10 patching of ng, calling the local ng `-- --c=production,config-1` was compatible with the standard ng behaviour. With v11, no. We are bypassing the ng patch just for the build of the application and using the nx command for the other relevant stuff like testing and linting.
> 
> @dogmatico How do you bypass the patching?

We removed the call to `decorate-angula-cli` script from the package.json `postinstall` hook.

**Comment by raphael22** [comment]
Please reconsider discussion about this.
Not having to copy/paste huge of configuration is kind of big deal.
