### ISSUE TITLE
`ng eject` disallowed due to JSON syntax error

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#439]
Nx has become my default starting point for Angular projects—even for demos and tests. In some cases, I have to use `ng eject` which works perfectly fine with Nx except for one single minor reason. 

The following error is thrown because of the comment in `tsconfig.e2e.json` and `tsconfig.app.json` within a generated app:

```
/* add all lazy-loaded libraries here: "<%= offsetFromRoot %>libs/my-lib/index.ts" */
```

That will naturally generate a `SyntaxError` when trying to parse the JSON:

```
Unexpected token / in JSON at position 181
SyntaxError: Unexpected token / in JSON at position 181
    at JSON.parse (<anonymous>)
    at Promise.resolve.then.then.then.then.then.then (/Users/emilio.martinez/Documents/emilio/ng-webworker-demo/node_modules/@angular/cli/tasks/eject.js:576:27)
    at <anonymous>
```

Of course it's as simple as just removing the comment and `ng eject` will work as usual. Just through  I'd bring it up; potentially a quick win that unblocks `ng eject`.

**Comment by FrozenPandaz** [comment]
Hi @emilio-martinez, thank you for opening this issue.

I believe this should be done in the Angular CLI since comments are valid in tsconfigs.

The Angular CLI should be stripping comments before parsing the JSON for data.

Could you please create the corresponding issue in https://github.com/angular/angular-cli/issues?

**Comment by vsavkin** [comment]
+1 to @FrozenPandaz. Closing this issue as it should be fixed in the CLI.
