### ISSUE TITLE
Typescript 4 re-exporting syntax throws an error

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#4393]
## Current Behavior
using the following re-export fails

```
export * as mainNetDataService from "./grpc/main-net-data-service"
export * as stnDataService from "./grpc/stn-data-service"
```

and the error

```
ERROR in ./libs/data-services/shared/grpc/src/lib/index.ts 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
> export * as mainNetDataService from "./grpc/main-net-data-service";
| export * as stnDataService from "./grpc/stn-data-service";
```

## Expected Behavior
I thought typescript 4 supported this syntax ?

My idea is not complaining :-)

## Steps to Reproduce
You try and use the export syntax and run nx serve

**Comment by iangregsondev** [comment]
Using the old syntax of this, works

```
import * as mainNetDataService from "./grpc/main-net-data-service"
import * as stnDataService from "./grpc/stn-data-service"

export { mainNetDataService, stnDataService }
```

**Comment by nkwood** [comment]
What is your Typescript ECMAScript target version set to? 

I believe the "export * as namespace" is part of ES2020. If you set your target to ES2020 a variety of things will fail because NX is still on webpack 4 and my understanding is the issue occurs because webpack 4 is using acorn 6.x. Migrating to Webpack 5 should fix the issue based on what I was able to find. See e.g. https://github.com/webpack/webpack/issues/10227 

I encountered this issue while attempting to use optional chaining and targeting ES2020. In my particular case I was able to solve the issue by targeting ES2019, but I don't know if that works in this instance, however it may be worth a try.
