### ISSUE TITLE
Peer dependencies are missing in next.js build package.json

### ISSUE THREAD

**Issue by gabrielbull** [nrwl/nx#4506]
## Current Behavior

When building next.js applications, peer dependencies of dependencies that are installed are missing in the generated package.json file. Two examples:

To use `@apollo/client`, one need to also install `graphql` as it is a peerDependency of `@apollo/client`
```shell
yarn add @apollo/client graphql
```

In the code, `graphql` will never be required, resulting in it not being added to `package.json` in the build.

The same goes for `@emotion/styled`, it requires a peer dependency of `@emotion/react`, which is never required in the code and thus, is missing in the package.json.

Those are only two examples that I have in my app but there are countless others.

## Expected Behavior

I expect the `package.json` to include peerDependencies or to allow me to specify which extra dependencies I want.

## Steps to Reproduce

```shell
npx create-nx-workspace depexample --preset empty --nx-cloud 0
cd depexample
yarn remove @nrwl/workspace --dev
yarn add @nrwl/next @nrwl/workspace
nx g @nrwl/next:application --name nextapp --style @emotion/styled
yarn add @apollo/client graphql
echo "import '@apollo/client'" >> apps/nextapp/pages/_app.tsx
nx build nextapp
```

To mimic running in a container, just move the build folder to outside the Monorepo and do a yarn install.

### Failure Logs

And when you run the application:

```
yarn start
```

```
Error: Cannot find module 'graphql'
Require stack:
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.4.0
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.2
  @nrwl/cypress : 11.1.2
  @nrwl/devkit : 11.1.2
  @nrwl/eslint-plugin-nx : 11.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.2
  @nrwl/linter : 11.1.2
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.2
  @nrwl/node : Not Found
  @nrwl/react : 11.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.2
  @nrwl/web : 11.1.2
  @nrwl/workspace : 11.1.2
  typescript : 4.0.5
```

**Comment by laSinteZ** [comment]
Happened to me as well, but worked fine at `@nrwl/next 10.4.4`

**Comment by laSinteZ** [comment]
https://github.com/nrwl/nx/commit/c062c6e6578a9649dda101c02a384ea71d7d14ee apparently, this commit breaks it, since before it all `rootPackageJson.dependencies` were copied, but here only used dependencies are copied to package.json (though, ignoring peer dependencies).

**Comment by gabrielbull** [comment]
@BigAB

**Comment by BigAB** [comment]
So are we thinking adding peer dependencies would fix the issue?

No right? Because it's not the `peerDependencies ` in the root `package.json` that are not being added to the built `package.json` it's that peer deps are missing in the final build.  I assume this because peer deps weren't added before [c062c6e](https://github.com/nrwl/nx/commit/c062c6e6578a9649dda101c02a384ea71d7d14ee) either but let me know if that is the issue, because that would be an easy fix.

Is this possibly related to using npm7?

What do you have to do in the "built" `package.json` (in the `dist` dir) to make it work?  Add deps?  Add `peerDependencies`?

**Comment by laSinteZ** [comment]
@BigAB Before https://github.com/nrwl/nx/commit/c062c6e6578a9649dda101c02a384ea71d7d14ee all root dependencies were added, and this worked (though it added tons of unused packages for sure).

For example, in my project we use `@apollo/client`. It has a peerDependency `graphql`, and we added to our `package.json` along with `@apollo/client` (as @gabrielbull mentions, apparently they do it in their project as well). Before, generated package.json would contain `graphql` because it simply copy-pasted all packages from root. Now `graphql` isn't there because it isn't imported in the code directly (though it is used by `@apollo/client` internally) and it is filtered out by `getProjectDeps`.

I think that the following approach would work (correct me if I am wrong):
1. Put only used dependencies to the generated dist `package.json` (nx does that already, thanks to your modification)
2. Iterate through those selected dependencies and if it has `peerDependencies` and this `peerDependencies` is in the root `dependencies`, add it to the generated `package.json` (this way we don't add not installed packages).

IMHO this should work, but I am not 100% sure since I am not very familiar with nx yet.

I don't think that's related to `npm@7`, since I use `npm@6`, and @gabrielbull uses `yarn`.

**Comment by gabrielbull** [comment]
That would work, it would need to be made recursive to make sure that peerDependencies of peerDependencies are also included, and so forth. Not that it is my case, but it could happen.

**Comment by laSinteZ** [comment]
@gabrielbull is there an example of package with peerDependencies of peerDependencies? I've assumed that peerDependencies of peerDependencies should either be dependencies because otherwise package won't work or it will be peerDependency itself. Bud I guess that's bold assumption :)

**Comment by gabrielbull** [comment]
Well, I don’t have a specific one in mind, but it’s a valid use case so it should not be ignored. Making the function recursive would solve that and avoid someone opening up a new issue about it down the line.

**Comment by BigAB** [comment]
I understand the problem.

- I think the **easiest fix** is to just revert this change and continue installing unused packages (@jaysoo)  
- Searching through the peer deps of the installed packages sounds like it would work as well, but I am not sure if we have easy access to those deps without getting weird about it (basing on known file structures and whatnot)
- another alternative is to have _some way_ to express "this Next.js app requires _these_ packages", either in addition to the ones installed, or maybe all of them.
    - maybe as command line args (sounds tedious)
    - maybe as some configuration in the app (sounds weirdly redundant to a package.json)
    - some other thing I haven't thought of?
    
 Not sure which way we want to head on this, so maybe @jaysoo could chime in with what he thinks we should do?

**Comment by gabrielbull** [comment]
Other Nx plugins allows you to specify extra dependencies in the `package.json` of the project. Like `apps/app1/package.json`. I know I do it with @nrwl/nest

**Comment by laSinteZ** [comment]
Yeah, I second that all deps = very huge dokcer container + long `npm install`. Having some way of mentioning needed peer deps would be nice (even though the __correct__ solution would be iterating through peerDeps, but it might be out of your scope guys, I guess it would require much more work)
