### ISSUE TITLE
Vulnerability detected: Prototype pollution

### ISSUE THREAD

**Issue by OysteinAmundsen** [nrwl/nx#4507]
https://snyk.io/test/npm/@nrwl/angular/11.1.2

Vulnerability exists in `cache-base@1.0.1` indirectly used by `@nrwl/cypress@11.1.2` through dependencies.

**FIX: Upgrade dependencies**
`@nrwl/cypress` depends on severely outdated versions of `ts-loader` and `fork-ts-checker-webpack-plugin`.

**Comment by mehrad-rafigh** [comment]
There is an issue for `fork-ts-checker-webpack-plugin`  #4494
Unfortunately there are a ton of breaking changes, like dropped support of constants nx relies on and much more.

**Comment by ultd** [comment]
I too am getting this vulnerability in our code security/analysis tool. I think this needs to be a top priority as our stack using angular and react uses `@nrwl/cypress` for testing (as do all nx e2e tests generated). Not to mention #4494 as well. This is making our development life very hard as our CI/CD pipelines reject merge requests on high severity vulnerabilities and our minikube development environment consistently needs to be restarted due to the buggy/outdated version of `fork-ts-checker-webpack-plugin`
