### ISSUE TITLE
Support ignoring lint folders/files which are defined in .eslintignore

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#4514]
## Description

Use `.eslintignore` to ignore ESLint running on files/folders when running `nx run-many --all --target=lint`. Currently this throws error 

```
Invalid lint configuration. Nothing to lint.
```

I have checked documentation but I couldn't find a way to ignore ESLint on projects. Using `ignorePatterns` in `.eslintrc.json` not working either.

Example repo at https://github.com/ahnpnl/nx-workspace

**Reproduce step**

- Clone the repo and install deps with `npm`
- Run `npm run lint`
- Observe the error in the console

## Motivation

`.eslintignore` is basic functionality of ESLint so I think `nx` should respect that

## Suggested Implementation

Any files/folders which are defined in `.eslintignore` should be ignored from `nx run-many --all --target=lint` with a workspace using ESLint

## Alternate Implementations

**N.A.**

**Comment by Camo30** [comment]
Same issue here

**Comment by Frikki** [comment]
This is very important to get fixed. Pre-commit hooks lose their value completely.

**Comment by JamesHenry** [comment]
Hi @ahnpnl, everything here is working as expected and your `.eslintignore` is being respected. I will outline all the relevant pieces:

- You have a `lint` target defined in your angular.json for your library project called "ui"
- Therefore when you run `nx run-many --all --target=lint` that lint target is being invoked. This is the same as if you had run: `nx lint ui` directly on the project.
- You are therefore instructing ESLint to run on that project's directory and subdirectories (as per the defined `lintFilePatterns` within your lint target's configuration), but at the same time in your `.eslintignore` you have told ESLint to ignore all files and subdirectories in that project's directory.
- Therefore _ESLint_ (not Nx) is correctly giving you that error because you have simultaneously told it to do something and ignore the same thing
- This is also the reason why linting works absolutely fine for your other projects:

![image](https://user-images.githubusercontent.com/900523/111068527-04433500-84c1-11eb-8622-8af9e29dbff3.png)


If you do not want to run ESLint on the project called "ui", then you should remove its `lint` target from your angular.json, or rename it to something else so that it does not get picked up by `run-many --target=lint`.

If it is not so black and white, and you only want to ignore part of the project, then you should amend the value in the `.eslintignore` file so that it does not ignore all files and folders for that project, and/or adjust the `lintFilePatterns`. It entirely depends on what you are trying to achieve with this.

Hope that helps!

**Comment by ahnpnl** [comment]
Thanks for your clear explanations 👍 I've tried the suggested solutions and they work well.

**Comment by chaosmonster** [comment]
Thanks @JamesHenry I stumbled over a similar issue and had a facepalm moment after reading your explanation
