### ISSUE TITLE
Broken links on the documentation site

### ISSUE THREAD

**Issue by akaRem** [nrwl/nx#4541]
## Current Behavior

There are multiple cases when links lead to 404 page.

For example,
https://nx.dev/latest/node/migration/overview#exploring-your-workspace => Take a tour of your Nx workspace. => https://nx.dev/latest/node/workspace/workspace-overview => 404

Choose "previous" version and click on Getting started => https://nx.dev/previous/react/getting-started/getting-started +. 404 (errors for angular react and node)

There could be even more broken links.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by vsavkin** [comment]
Thanks for submitting the issue. 

We restructured the docs a bit for 11 release. We added some redirect rules to handle the change, but those only work when you refresh the page.

I fixed the workspace overview link here: https://github.com/nrwl/nx/commit/a996db280a9a3ce2e150146ac58bb9851d35f5d1

The site frame doesn't handle the prev/current switch--it always renders same links (in opposite to the nav menu on the left), that's why the getting-started link doesn't work for "previous". Fixing this is a bit more involved, and given that the workaround is to click on the menu on the left, I'll leave it as it. Plus it's going to get fixed automatically once we release next major in April.

I'm going to close this issue.

Thanks again!
