### ISSUE TITLE
Cytoscape dep-graph changes the layout of the graph

### ISSUE THREAD

**Issue by dbrody** [nrwl/nx#4553]
## Current Behavior
The new cytoscape dep-graph makes straight lines. Before it was curved.
<img width="1485" alt="Screen Shot 2021-01-17 at 6 57 10 PM" src="https://user-images.githubusercontent.com/210322/104868229-aa2a5700-58f7-11eb-927c-a44945313b7f.png">
 

## Expected Behavior

<img width="1047" alt="Screen Shot 2021-01-17 at 7 02 24 PM" src="https://user-images.githubusercontent.com/210322/104868208-9979e100-58f7-11eb-8207-c13ef8e3c1b4.png">

## Steps to Reproduce

As of PR #4000 the change to [cytoscape](https://js.cytoscape.org/) seems to change the display.

## Followup
I'm confused why the PR doesn't:
- Include why the change was made
- Why cytoscape was chose
- How / if its configurable

Cytoscape seems powerful so if there are plans to make this customizable that would be great. But for now it should at least keep the same formatting as the previous d3 implementation.

Furthermore, Cytoscape [supports curved lines](https://js.cytoscape.org/demos/edge-types/) so this should be easily accomplishable.

**Comment by vsavkin** [comment]
@philipjfulcher could you answer?

**Comment by philipjfulcher** [comment]
@dbrody Thanks for the feedback. :) This change is part of an internal project at Nrwl to make the dependency graph more performant, especially for very large graphs. Part of that project is a desire to vizualize the graph differently than in the past, giving us more options to layout nodes, group related nodes together, and reduce the number of nodes or edges we render at a time. Cytoscape was chosen because it gave us a lot of options and power to accomplish these changes, along with an efficient renderer. 

When we have internal projects like these, we're not always as descriptive in the PR description. That's understandably frustrating for someone trying to track down why a change happened. I'll try to include more information in future PRs related to changes to the dependency graph.

When I moved the graph to Cytoscape, I knew there would be some visual changes, including using straight lines rather than curved lines. I tried to stay close to what we had before, but there were some changes. These changes were intentional but not explained in the PR. At the time, I thought that the calculation of the curved lines was slower to render than the straight lines. Unfortunately, if I wrote that performance data down, I can't find it any more. :( I'll take another look at using curved lines and document the performance. I'd be happy to admit I was wrong and bring back curved lines.

**Comment by davicoradini** [comment]
hi, first of all, good job with the dep-graph
I also think layout was kinda nicer before
couldn't we have an option to choose the layout? is that too complicated to implement?

**Comment by dbrody** [comment]
Yeah, if there is some hook into dep-graph to be able to easily customize Cytoscape that would be ideal.

**Comment by luchsamapparat** [comment]
It's good to hear that the switch to Cytoscape happened to improve the dependency graph. It is one of my feature features in Nx.

However, in its current state, this is a _huge_ step backwards. Even with only 6 nodes this graph becomes very hard to grasp:

![image](https://user-images.githubusercontent.com/875017/111824574-b0808380-88e6-11eb-902d-7919bbfb9fea.png)

![image](https://user-images.githubusercontent.com/875017/111824609-b8d8be80-88e6-11eb-9f40-63f90a4b772d.png)

And this is a graph for a well-structured app. I'm currently refactoring a spaghetti-style monolith and the dependency graph usually is very helpful in untangling such a mess. However, with this update, I have to reduce the node count to very low single digits in order to understand the relationships.

I understand the need to go forward and change things, but please keep in mind that people are using and relying on stuff like this. Maybe implement the new version in parallel and still provide the old one until it reaches feature-parity?

**Comment by philipjfulcher** [comment]
We're currently investigating different layout algorithms and ways of grouping nodes and edges to make this clearer.

**Comment by WolfspiritM** [comment]
@philipjfulcher That's good news. I was trying the dependency graph to find circular dependencies and check dependencies in general in our project but right now the graph is pretty much unusable with larget projects:

![image](https://user-images.githubusercontent.com/5904171/125004285-800d5280-e059-11eb-95d7-35e46794023f.png)

**Comment by promontis** [comment]
@philipjfulcher why not use https://github.com/iVis-at-Bilkent/cytoscape.js-fcose?
