### ISSUE TITLE
Support lint only and only uncommitted files

### ISSUE THREAD

**Issue by nguyenxndaidev** [nrwl/nx#4619]
## Description/Motivation

In my project, we want to add pre-commit git hook to format then **lint only uncommitted files**.
Using `affected:lint` is not a good idea for local development because it will lint also committed files in affected projects.

It's not a big problem if linting is fast, but everyone knows that linting is very slow and it reduces development productivity a lot if the hook try to lint too many files.

## Suggested Implementation

Currently, the command `nx format:write --uncommitted` works very well.
I would suggest to have the similar command for lint: `nx lint --uncommitted`. The command should not force to specify a project name and should lint only and only the uncommitted files like the format command does.

**Comment by kamechb** [comment]
@nguyenxndaidev you can use https://github.com/okonet/lint-staged to lint only staged files in git hook.

**Comment by nguyenxndaidev** [comment]
> @nguyenxndaidev you can use https://github.com/okonet/lint-staged to lint only staged files in git hook.

Hi @kamechb, I tried it. But it takes the wrong lint settings (eslint) for sub projects. Only NX command uses the right lint configuration for the sub projects.

**Comment by nguyenxndaidev** [comment]
@kamechb do you have a working example to use lint-staged with nx?

**Comment by gabrielmaldi** [comment]
I'd love to have a `nx lint --uncommitted` command just like we have `nx format:write --uncommitted`. This is not stale. Thanks!

**Comment by ntziolis** [comment]
@gabrielmaldi  It seems this is supported now (we are using nx 11, not sure when support was added), We use the following command in our lit-staged setup:  
`nx affected:lint --fix --parallel --uncommitted`

Please note that we could not get it to work when using the pnm script as a starting point:
https://github.com/okonet/lint-staged/issues/522#issuecomment-894680312

**Comment by zachgoll** [comment]
> @gabrielmaldi It seems this is supported now (we are using nx 11, not sure when support was added), We use the following command in our lit-staged setup: `nx affected:lint --fix --parallel --uncommitted`
> 
> Please note that we could not get it to work when using the pnm script as a starting point: [okonet/lint-staged#522 (comment)](https://github.com/okonet/lint-staged/issues/522#issuecomment-894680312)

I'm not seeing the support for `nx lint --uncommitted` [in the docs](https://nx.dev/l/r/cli/lint)?  I'm on NX 12.

For those looking for a basic `lint-staged` + `husky` setup, here's what I've got that is working pretty nicely ([with help from this post](https://github.com/okonet/lint-staged/issues/522#issuecomment-751219628)).

`package.json`: 

```json
"husky": {
    "hooks": {
        "pre-commit": "lint-staged"
    }
},
"lint-staged": {
    "*": [
        "yarn nx format:write --uncommitted",
        "yarn eslint --fix"
    ]
}
```

No need to use `nx` for the lint step because `lint-staged` already passes a list of files (uncommitted) to the `eslint` command.

**Comment by pranav-js** [comment]
@zachgoll use the new husky config if possible. one with pre-commit.sh file

**Comment by zachgoll** [comment]
> @zachgoll use the new husky config if possible. one with pre-commit.sh file

Very good, point!  I'm on an older version of Husky for the setup above (v4).  The newest versions of husky don't allow this `package.json` syntax anymore and require something like this in `./husky/pre-commit`:

```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
```

**Comment by nguyenxndaidev** [comment]
Be careful, `eslint` doesn't work if your sub projects want to overwrite the root lint config. In this case, you must use `nx`.

**Comment by pranav-js** [comment]
yeah, can someone from core please prioritize this? I believe it is a must-have in large teams and multiple projects to run lint on only changed files, especially people using it with pre-commit hooks

**Comment by meeroslav** [comment]
Hey all,

As @ntziolis wrote, the `uncommitted` does in fact exist and it's part of `affected` and `format` commands. 
Here is a little background on how linter and affected works:

## Formatting the `uncommitted`

On the `format` command the `uncommitted` flag works as expected since formatting of one file can not possibly influence the formatting of another file. Formatting can be expensive and we can limit it to only files that we plan to commit.

## Affected with `uncommitted` flag

On the `affected` command the `uncommitted` flag limits the affected graph calculation to only uncommitted files (default is `uncommitted` + `untracked` + `diff between head and base`). The affected graph, however, will still consist of projects, not files. An entire project will be linted. Again, the reason is to limit checks to only projects that will be affected by the files being committed.

## Linting only files that changed

### Why not lint just the files that have been changed?

Unlike formatting and linting outside of Nx (as being the premise used by @okonet for his amazing [lint-staged](https://github.com/okonet/lint-staged)), file changes in one file in the Nx can influence linting of another. When you change a tag in one project's configuration all the projects that depend on this project - directly or indirectly, will be affected.

### What if tags were not changed?

Since we know which files changed, we could check if the project's configuration (and more importantly tags) are among those changes. When not - we could lint just the changed files, otherwise we would lint the entire project. There is a catch, though - the implementation cost vs. the benefit.

### Implementation cost
The Nx is designed to work with projects - all the `executors` (build, test, lint...), `commands` (run, affected, run-many...), `caching`, and `distributed task execution` operate on the project level. If we would lint just the uncommitted files how should this be cached? In order to calculate the cache we need to get all the files in the project, but that means that we would potentially calculate cache with untracked files as well. This could lead to false positives being cached - a project with linting issues outside of uncommitted files would be marked as successful. With remote caching, it would mean, that it could affect multiple users. 

But most importantly, making a shift from the project-based focus would require a lot of work across the entire Nx ecosystem, primarily changing the core of the Nx. Making it right would require an enormous effort.

Is it worth it? We would argue that it's not. Based on our experience working with small to large scale monorepos consisting of 1-100 projects and various frameworks linter is usually not a problem. We have been improving the performance of the `enforce-module-boundaries`, `workspace-lint` and the core (daemon process) in the recent period to make sure linter is no longer the bottleneck. If your project's linting takes a long time, this might suggest that rules used are very slow or (usually) that the project should be split into several sub-libraries. Our book [Enterprise Angular Monorepo Patterns](https://go.nrwl.io/angular-enterprise-monorepo-patterns-new-book) (not just for Angular) describes how to architect solutions with best practices in mind.

## Final thoughts
 
While this might never become part of the Nx, for the reasons listed above, that doesn't mean that someone is not allowed to create e.g. `nx-eslint-staged` that would use project configuration from Nx to run lint-staged with proper eslint configuration. But please be aware of all the things you would be losing by running this over `nx lint`:
- local and remote caching of lint runs
- lint mismatches when tags are changed
If your lint is slow locally, it would be slow on CI as well. Splitting the project makes more sense in the longer run.

**Comment by binaryartifex** [comment]
Can confirm that the ```--uncommitted``` flag works with the ```affected:lint``` command in nx 13.10.3 (using windows OS). Ive started a completely new project, added my usual version control all stars team consisting of commitlint, commitizen, husky, lint-staged and prettier+eslint being provided by nx. I added two fresh nextjs applications. 

Following husky scripts are used ->
```
# commit-msg hook
yarn commitlint --edit $1

#pre-commit hook
yarn lint-staged

#prepare-commit-msg hook
exec < /dev/tty && node_modules/.bin/cz --hook || true
```

Lint-staged config consists of the following ->
```
// .lintstagedrc.json

{
  "*.{js,jsx,ts,tsx,json,md}": [
    "yarn nx affected:lint --fix --parallel --uncommitted",
    "yarn nx format:write --uncommitted"
  ]
}
```

For brevity sake, commitlint config ->
```
//commitlint.config.js

module.exports = { extends: ["@commitlint/config-conventional"] };
```

And standard commitizen config added into package.json file ->
```
 // package.json

  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
```

The following output was displayed after git commit command ->
```
$ git commit -m "test commit"
yarn run v1.22.17
$ F:\projects\###\development\###\node_modules\.bin\lint-staged
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.json — 31 files (chunk 1/2)...
[STARTED] .lintstagedrc.json — 31 files (chunk 2/2)...
[STARTED] *.{js,jsx,ts,tsx,json,md} — 26 files
[STARTED] *.{js,jsx,ts,tsx,json,md} — 25 files
[STARTED] yarn nx affected:lint --fix --parallel --uncommitted
[STARTED] yarn nx affected:lint --fix --parallel --uncommitted
[SUCCESS] yarn nx affected:lint --fix --parallel --uncommitted
[STARTED] yarn nx format:write --uncommitted
[SUCCESS] yarn nx affected:lint --fix --parallel --uncommitted
[STARTED] yarn nx format:write --uncommitted
[SUCCESS] yarn nx format:write --uncommitted
[SUCCESS] *.{js,jsx,ts,tsx,json,md} — 25 files
[SUCCESS] .lintstagedrc.json — 31 files (chunk 2/2)...
[SUCCESS] yarn nx format:write --uncommitted
[SUCCESS] *.{js,jsx,ts,tsx,json,md} — 26 files
[SUCCESS] .lintstagedrc.json — 31 files (chunk 1/2)...
[SUCCESS] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SUCCESS] Applying modifications from tasks...
```

From here it provided a commitizen wizard to generate an appropriate message.
