### ISSUE TITLE
Generators do not respect original line endings for non ts/js files

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#4699]
## Current Behavior
Creating a new react app with CRLF line endings will change the line endings to LF for files that are not ts,tsx,js,jsx. Code files are fine, but the `.vscode/extensions.json` and `package.json` files switch to LF line endings.

## Expected Behavior
When I use a generator, I expect to keep the original line endings.

## Steps to Reproduce
1. Switch your line endings for `.vscode/extensions.json` and `package.json` to CRLF.
2. `yarn nx @nrwl/react:application myapp`
3. The line endings for `.vscode/extensions.json` and `package.json` will be changed to LF.

### Environment

```
  Node : 12.18.3
  OS   : win32 x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 11.2.8
  @nrwl/cli : 11.2.8
  @nrwl/cypress : 11.2.8
  @nrwl/devkit : 11.2.8
  @nrwl/eslint-plugin-nx : 11.2.8
  @nrwl/express : 11.2.8
  @nrwl/jest : 11.2.8
  @nrwl/linter : 11.2.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.8
  @nrwl/react : 11.2.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.8
  @nrwl/web : 11.2.8
  @nrwl/workspace : 11.2.8
  typescript : 4.1.3
```

**Comment by FrozenPandaz** [comment]
This is expected behavior. Updated/ Generated files are formatted via `prettier` after being updated/created.

If you want to enforce `CRLF` line endings in your code, you can update your `.prettierrc` file to the following:

```
{
  "singleQuote": true,
  "endOfLine": "crlf"
}
```

After that, Nx will automatically format the code that it generates according to your updated `prettier` configuration and enforce `CRLF` line endings. You can also set the value to `"auto"` which will enforce that files use whichever line ending is at the end of the first line of the file so that you 

https://prettier.io/docs/en/options.html#end-of-line

**Comment by ardokirsipuu** [comment]
@cguilhermef .prettierc or .prettierrc?

**Comment by dmitri-afonin** [comment]
Why is it closed? The issue still here
Using NX 15.1.1 with angular

**Comment by cguilhermef** [comment]
> @cguilhermef .prettierc or .prettierrc?

.prettierrc my friend. Just a miss spelling here. I'm using the correct one in my project, and it doesn't work.
