### ISSUE TITLE
nx format not formatting all files (e.g. *.vue), but prettier does

### ISSUE THREAD

**Issue by realityfilter** [nrwl/nx#4702]
## Current Behavior

Running nx format does not format any vue files. Running prettier directly does format vue files.

## Expected Behavior

All files of types prettier can format should be formatted with nx format.

## Steps to Reproduce

- npx create-nx-workspace prettier
- cd prettier
- npm install @nx-plus/vue @nrwl/jest @nrwl/cypress  @nrwl/linter --save-dev
- nx g @nx-plus/vue:app my-app
- edit vue file to contain formatting problems: apps/my-app/src/App.vue 
- nx format 
- prettier -c .

Prettier does format the App.vue file. NX ignores all vue files.

### Environment
  Node : 12.16.3
  OS   : darwin x64
  npm  : 6.14.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5

**Comment by mikehaas763** [comment]
I came across this issue too, and I'd like to work on the fix if I can get consensus on the direction.

The issue is that Nx format relies on a static allow list at https://github.com/nrwl/nx/blob/06e13dae2fecb621d03a197b65d4e37c4c73e06d/packages/workspace/src/command-line/format.ts#L15-L27

This makes sense because in prior versions of prettier, you had to be very specific about the files and extensions you wanted to check/format. At some point, I think around prettier v2, they made the default behavior check all supported extensions at the specified path. For example, `prettier --check my/path` will now recursively check `my/path/main.ts`, `my/path/sub/foo.yml`, etc.

I'm thinking about fixing this by inspecting the version of prettier. If it's older than when prettier released this change, continue as is. Otherwise, move to formatting all files types/extensions that prettier supports by specifying only the path, and not the specific file extensions.

Thoughts?

**Comment by realityfilter** [comment]
This is still an issue.

**Comment by dhoepelman** [comment]
still an issue, prettier can handle a lot more files now

**Comment by jaysoo** [comment]
I don't think we even need to consider versions less than 2 since 1.19.1 came out two years ago, and upgrading is simple since it's just a dev tool.

I suggest the following:
- If `--all` is specified then use `"."` as the pattern so we format all files the workspace.
- If `--projects` are specified then use the project dirs as the pattern (e.g. `apps/app1 apps/app2 libs/lib1 libs/lib2`)
- If no  args or one of `--untracked`, `--uncommitted`, `--base`, `--head` are specified, then use the directories of those files rather than individual files (so we can skip checking supported extensions)

**Comment by jaysoo** [comment]
Actually, prettier already provides this info so we should just use their API.  :)

https://prettier.io/docs/en/api.html#prettiergetsupportinfo
