### ISSUE TITLE
Support for import of non-buildable libraries in buildable libraries

### ISSUE THREAD

**Issue by luchsamapparat** [nrwl/nx#4829]
## Description
Currently, it is not possible to import a non-buildable library in a buildable library. 

![image](https://user-images.githubusercontent.com/875017/108384496-16f08400-720b-11eb-9acf-179a77e7a7f0.png)

I think there are valid use cases for wanting to import non-buildable libraries in buildable libraries (see Motivation) and that therefore this should be supported by Nx (see _Motivation_)

## Motivation
As explained by @jaysoo in [this comment](https://github.com/nrwl/nx/issues/1765#issuecomment-589074590), this is a conscious decision by the Nx team:

> I'm going to close this issue since we will not be supporting imports of non-buildable libraries from buildable ones. Instead, dependencies should be made buildable as well. This constraint makes sense if you think about shared libraries between two buildable parents.

In ECMAScript/TypeScript a module is a file. That is the highest level of modularization with strict encapsulation offered on a language level. The only way to get something like "package-level" encapsulation is by using npm packages (and even that may not prevent deep imports). In large projects, I need something in between: coarser-grained than a file, but without the overhead of managing an npm package.

I started using Nx when it was still very much based on Angular, at a time when Angular didn't even support building libraries out of the box, and I have been convincing a lot of my colleagues to use Nx in their projects. For one simple reason: Libraries in Nx along with the `enforce-module-boundaries` linting rule provide me with the "package-level" encapsulation mechanism the JS/TS ecosystem is missing.

I cannot stress this enough: The main reason for me to use Nx Workspace is the ability to [modularize my project into separate libraries with clear APIs and strict encapsulation](https://github.com/ngxp/demo/tree/master/libs). I've seen countless unmaintainable Angular monoliths and I have refactored more than one of these monoliths into well-modularized, maintainable projects with the help of Nx. And now that you guys added support for Non-Angular projects, I can even use this to modularize my React or NestJS app.

Computation caching, Storybook/Jest/Cypress support, etc. - all that is nice, but without libraries and `enforce-module-boundaries` I don't think I would use Nx in most of my projects.

Why do I tell you all of this? Because the decision not to support the import of non-buildable library in a buildable library ignores the fact, that libraries are used by many projects to organize their code.

Let's have a look at an example:

I have two publishable libraries (`A` and `B`) in my workspace. Both depend on shared code in library `c`.

According to the decision of the Nx team, I need to publish library `c` as well. This means, when someone wants to use library `A`, he/she also needs to install library `c`. That is not only inconvenient, it comes with to problems:

1. I open the door for version mismatches, e.g. because a user of my library updates `A`, but forgets to update `c`. This is all solvable somehow, but why would I even want to deal with this problem, if I could just bundle the code of `c` with `A` and `B`?
2. I expose what _should be_ an implementation detail: the dependencies between modules of my project.

I saw a lot of discussions about 1. and I think both sides have valid arguments - so why not let the developer decide which way to go?

But for me, 2. is even more important. I do not want to expose the inner workings of my library to external users. What happens if at some point I decide to split `c` into `c1` and `c2`? Then all users of my library need to update their dependencies because _I_ decided to do some refactoring that may not even change the behavior of the library.

## Suggested Implementation
In Angular-land this may be not as as easy as it seems as [ng-packagr](https://github.com/ng-packagr/ng-packagr) seems to have [a hard-coded `rootDir`](https://github.com/ng-packagr/ng-packagr/blob/94dd2d8881bc06696fbe8e6b67f9f8a8e761fa96/src/lib/ts/tsconfig.ts#L93) matching the `entryPoint`. As for non-Angular libraries, I have no idea 🤷🏻‍♂️

## Alternate Implementations
Find a way to use `enforce-module-boundaries` without Nx, but who wants _that_...? ;-)

**Comment by Areen3** [comment]
I also join this wish

**Comment by ubergeoff** [comment]
**On Point 1**

```
because a user of my library updates A, but forgets to update c. This is all solvable somehow, but why would I even want to deal with this problem...
```

But you never really need to "deal" with this - as the problem is already solved..?

`c` is "automatically" an intrinsic dependency on A and B - so one never really has to worry about this dependency. i.e. the intrinsic dependency is:

1) Automatically added as a dependency (automatically added to the package.json file) by nx/packagr build process - but also,
2) It will be installed by the user/installer - without even "needing" to know anything about it. Just like any other npm package out in the wild.
3) You just have to ensure that `c` is published - which is not a big effort - since you are publishing other lib's in the meantime...

```
if I could just bundle the code of c with A and B
```

Why would you want to "re-bundle" code into A and B (is this not duplication ?) - surely it is better to "share" code.
i.e. rather let A an B share the common logic/modules of `c` ?


**On point 2** 

 I have no strong opinion here. For me: I need to have shared code - thus the need for the `c` package to exist.

Would be cool to see what the NX team have to say about that one...

```
 so why not let the developer decide which way to go?
```

There might be some value here... maybe `c` is quite small and there is no a "big" cost to bundling it up into A and B. Where do you draw the line..?

**Comment by Bogs-123** [comment]
We ran into the same error.
There is a lot of added value in this.

**Comment by KerickHowlett** [comment]
Sorry to be the one to add on top the pile, because all I'm trying to do is include a library that houses my interfaces and JSON files into my other libraries. I even made sure to follow what was done in a YouTube video when they went over API Interfaces. I even made sure to pull down and study over a couple of the example projects. I'm even using Nx Console and had rebuilt this project from the ground up a couple of times -- still encountering the same problem.

**Comment by Areen3** [comment]
the problem is due to several facts
library files must be within this library
if they are outside of it, they are available via an alias e.g. @ mylib34
if this library doesn't exist we have an error because there is no such npm with this alias

however, if you are compiling not a library but an application
all code is flattened into one main.js and then it works

**Comment by KerickHowlett** [comment]
Sadly, I haven't even had time to look into it since I posted this. 😞

**Comment by rishabhmhjn** [comment]
Following

**Comment by Amith-B** [comment]
I have similar issue, still wasn't able to find a way to fix this, there are 2 libraries a (with angular) and b (with react), and a util library c which is used in both a and b. When a or b is built, the code of c should be present in both the builds.

The react library(b) which uses @nxext/vite:package as executor works fine as it bundles the code of c in it build, but I am facing issue with angular library(a) build which is using @nrwl/angular:package as executor.
