### ISSUE TITLE
Feature: Add a postinstall command for migrate

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#4841]
## Description

Add `nx migrate` to postinstall in nx' package.json

## Motivation

We are using [renovatebot](https://github.com/renovatebot/renovate) which automatically keeps our packages up to date, but each time a nx version comes out, I close the PR and manually call `nx migrate latest` in order to make sure there are no new migrations that need to run. 

## Suggested Implementation

What would be great is to enforce migrations to be create and ran. Maybe some setting can be used to opt into this or something. 
	
## Alternate Implementations

Not sure

**Comment by FrozenPandaz** [comment]
I can see the value in that for sure! :smile:

Hm.. I don't think we want to run `nx migrate` after installing because that would be too late. `nx migrate` uses the installed version (old version) to compare to the target version (new version) to generate a list of migrations. I think what we want is for renovate bot to perform an update using `nx migrate` instead of updating the `package.json` and running an install. Does Renovate bot have a way to customize how an "update" is done?

**Comment by cyrus-za** [comment]
I dont think renovate has a way to update after install, but it does run postinstalls. I get that you using the current version, but maybe use git or something to check the changes to package.json and then based off of that run a set of migrations.

**Comment by ampcpmgp** [comment]
@FrozenPandaz I am facing this problem.
Should I ignore @nrwl/* module in renovate and migrate manually?
