### ISSUE TITLE
running nx run app-menu:storybook in react project produces ENOENT: no such file or directory, stat 'libs/app-menu/.storybook' unless running cmd as admin

### ISSUE THREAD

**Issue by bleakcon** [nrwl/nx#4871]
Very sorry if I have missed documentation for windows users (can't say I often dev in this environment either), all the commands to generate these files as well as the project and workspace were generated in a non-admin console.

The workaround of course is to run as an admin

## Current Behavior
Open up a terminal (not as admin)
When the command `nx run app-menu:storybook` is run
And there exists 'libs/app-menu/.storybook'
Then the response is ENOENT: no such file or directory, stat 'libs/app-menu/.storybook'

The storybook configuration was generated using:

`nx g @nrwl/react:storybook-configuration app-menu`

where 'yes' was answered for all 3 prompts (creation of cypress e2e)

## Expected Behavior
I expect it to start up the storybook instance with the app-menu stories loaded without having to run the terminal as admin

## Steps to Reproduce
With a react app in a windows 10 environment
run:  `nx g @nrwl/react:storybook-configuration app-menu` accept defaults for all prompts
run:  `nx run app-menu:storybook`
observe error: ENOENT: no such file or directory, stat 'libs/app-menu/.storybook'

### Environment
  Node : 14.15.4
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by mandarini** [comment]
Hi there @bleakcon! Thanks for filing an issue! Unfortunately, I could not reproduce the error you got. :( I could run Storybook on my Windows environment both as a simple (non-admin) user and as an admin. See screenshots.

Can you please share a repository with a reproduction, so that I can try it out? Thank you very much!

![Windows CMD as admin](https://user-images.githubusercontent.com/6603745/111633327-0e856c00-87fe-11eb-8373-22a2ae7ceccd.JPG)
![Windows CMD as simple user](https://user-images.githubusercontent.com/6603745/111633333-0fb69900-87fe-11eb-9e58-b89c5b13a311.JPG)

**Comment by mandarini** [comment]
Hi @bleakcon , is this still an issue?
