### ISSUE TITLE
Implement a  "shuffle" option for insertion of new libs in config files, randomly, to avoid conflicts in larger mono repos

### ISSUE THREAD

**Issue by un33k** [nrwl/nx#4888]
## Description
Last project was a massive enterprise application in Angular where 200 developers from all around the world were actively committing against the mono repo (nx 10.x)

Since the project was not started with NX, and we were converting it to NX, there were 10s of new libs being created everyday.  Since NX always added the new libs to the bottom of files such as `nx.json, angular.jso, tsconfig.base.json, etc.`, we were constantly in a state of conflict. And since the project not being fully converted to NX, we could not utilize the NX cache and affected features, so our CI took 30+ min. 

That meant any simple conflict of auto generated files took at least 1 hour to redo and re-push before it was ready for review. By the time we were ready to merge it in, another merge from another part of the world for a new lib would create a conflict again. 

As a work around, I instructed the teams, `with mixed success`, that on new libs creation, they should put the mouse cursor at the bottom of the libs in let's say `angular.json`, and flick it once, where ever the cursor landed, they were to move the newly created lib from bottom to that location. 

That fixed the issue by some 90%, but it was such a pain, as teams often forgot that. And it was a manual copy & paste so lot of errors were due forgetting something, etc. 

## Motivation
Generally speaking, since the larger projects are to benefit more from NX, it would be great for NX to handle the above issue during module creation.

## Suggested Implementation
I'd recommend a creation of a field called `"InsertShuffle":  false` in the `nx.json`. By default everything remains as before since the value is `false`.  With that, the larger teams that have conflict issues, can flip the value to `true`. If so, NX will randomize the insertion of any new config snippets in all related files mentioned above, so it mitigates the conflict hardship.

## Alternate Implementations
Alternative implantation would be a standalone script that can be assigned to commit hook and teams use it if they may.

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

One of our goals for Nx 12 is to add support for splitting the configuration into multiple files, so every lib and every apps will have their own nx-project.json, so the root workspace.json will only contain things that are not project specific. This should help with the conflict situation and also help with things like ownership and cache calculation.

 I believe this should solve your issue, right?

**Comment by un33k** [comment]
@vsavkin Yes, splitting the projects and help for sure. With that said, we'd still want to do something about the paths inserted at the bottom of the tsconfig.base.json as well.  Thx

**Comment by cyrus-za** [comment]
+1 for this, even when #4720 is done. 

Each tsconfig.base.json and jest.config.js has a new line added and if there are multiple libs added in parallel by different PRs the one going into master last will get merge conflicts due to the comma added at the end. 

Instead of shuffle, I'd prefer to make it alphabetical though. That way they wont always go at the end, and we also have it more organized

**Comment by stefan-schweiger** [comment]
There has been a new Feature in 12.4 which orders libs in angular.json alphabetically which should help somewhat. But what really drives me crazy is that now libs and apps and e2e tests are just wherever. It would be great if we could keep those "grouped" together.

**Comment by benjamincharity** [comment]
I agree that building something in for this would be nice. FWIW, in the meantime, the conflict issue can be solved fairly easily with a precommit hook: `sort-json ./angular.json ./nx.json ./tsconfig.base.json` etc

**Comment by vsavkin** [comment]
We have landed two features that should make this not an issue:

1. We sort workspace.json, angular.json during formatting.
2. You can pass --standaloneConfig when creating projects, so that their configs aren't inlined into the global config but stored in their corresponding folders. (see more here: https://blog.nrwl.io/per-project-configuration-storybook-support-for-angular-12-auto-refresh-for-dependency-graph-and-bcd2d1e06658)

You can also use (2) to quickly split your global config. The blog post covers it.

Hopefully this is a good solution, so I'm going to close this issue.

Thank you!
