### ISSUE TITLE
Gatsby v3.0.0 Support

### ISSUE THREAD

**Issue by mmmoli** [nrwl/nx#4966]
## Description
Support for Gatsby v3.0.0.

## Motivation
Gatsby 3 brings some nice features:
- Incremental builds
- React 17 + suspense

## Suggested Implementation
See [Gatsby migration guide from v2–v3](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/).

## Alternate Implementations
Don't know enough about nx. Sorry

**Comment by erkobridee** [comment]
so far I checked, the current issue here is the [gatsby-cli as a dependency on the project](https://github.com/nrwl/nx/blob/master/packages/gatsby/package.json#L39), this one should be a peer dependency and we have on the documentation or on the plugin creation the installation of it, so the dev would be enabled to change that version to the new one and doing so, it would be possible to migrate to the gatsby v3

follow a project where I keep my tests of the usage of Nx + Gatsby
[erkobridee/nx-gatsby](https://github.com/erkobridee/nx-gatsby)

**Comment by erkobridee** [comment]
I tried to downgrade the nx gatsby plugin for version 0.10.0 which doesn't have the gatsby-cli as a dependency

I also forced to use the `core-js@2.6.12` to fix the issue related to a file request by gatsby

but when I ran the gatsby application I got an error (That one I think it might be related to the nx gatsby plugin, but I don't have any sure of that):
```
⠏ Building development bundle
/${project path on my machine}/nx-gatsby/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^
```

<details><summary>followed by</summary><pre>
Error: NormalModuleFactory.afterResolve (ReactRefreshPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:291:14
    at Hook.eval [as callAsync] (eval at create (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/Hook.js:18:14)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:287:30
    at eval (eval at create (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:532:7
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:564:8
    at NormalModuleFactory.resolveRequestArray (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:915:34)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:556:11
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:636:8
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:786:5
    at finishResolved (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at done (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/cache/ResolverCachePlugin.js:217:12)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/cache/ResolverCachePlugin.js:164:28
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at Cache.store (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/CacheFacade.js:143:15)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/cache/ResolverCachePlugin.js:162:18
    at jobDone (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/FileSystemInfo.js:1676:5)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/FileSystemInfo.js:1949:7
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/util/AsyncQueue.js:312:5
    at Hook.eval [as callAsync] (eval at create (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._handleResult (/${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/util/AsyncQueue.js:284:21)
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/util/AsyncQueue.js:267:11
    at /${project path on my machine}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/FileSystemInfo.js:2819:5
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error during serve
</pre></detail>

**Comment by jaysoo** [comment]
We've updated the dependencies to `^3.2.0` in Nx 12, but we will look into moving it to peer dependencies.

**Comment by erkobridee** [comment]
@jaysoo awesome, thanks o/

**Comment by erkobridee** [comment]
today I did another try to update the Gatsbyjs to v3 using the nx v12.0.4 and nx gatsby plugin v12.0.4

1st step was to upgrade the nx to v12.0.4, I leave the nx gatsby plugin on the v11 and the gatsby on v2, with these dependencies I was able to run the gatsby application

then, I updated the nx gatsby plugin to v12.04 and manually I did the update of the gatsby to v3.3 following the [migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/)

on my first attempt to run, I got an error related to the core-js v2

<details>
<summary><strong>Can't resolve 'core-js/modules/web.dom.iterable.js'</strong></summary>
<pre><code> ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve 'core-js/modules/web.dom.iterable.js' in
'/${machine path}/nx-gatsby/apps/gatsby/.cache'

If you're trying to use a package make sure that
'core-js/modules/web.dom.iterable.js' is installed. If you're trying to use a
local file make sure that the path is correct.

File: .cache/find-path.js:5:0


 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve 'core-js/modules/web.dom.iterable.js' in
'/${machine path}/nx-gatsby/apps/gatsby/.cache'

If you're trying to use a package make sure that
'core-js/modules/web.dom.iterable.js' is installed. If you're trying to use a
local file make sure that the path is correct.

File: .cache/loader.js:12:0

not finished Building development bundle - 3.077s

Could not start Gatsby Development Server. See errors above.</code></pre>
</details>

so I force to use it, then I got another error:

<details>
<summary><strong>Errors related to the webpack</strong></summary>
<pre><code>➜  nx-gatsby git:(update/gatsby_v3) ✗ nx serve gatsby

> nx run gatsby:serve 
info

There are 3 other flags available that you might be interested in:
- FAST_DEV · Enable all experiments aimed at improving develop server start time
- DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side
Render (SSR) pages on full reloads during develop. Helps you detect SSR bugs and
fix them without needing to do full builds.
- PRESERVE_WEBPACK_CACHE · (Umbrella Issue
(https://gatsby.dev/cache-clearing-feedback)) · Don't delete webpack's cache when
 changing gatsby-node.js & gatsby-config.js files.
- PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue
(https://gatsby.dev/cache-clearing-feedback)) · Don't delete the downloaded files
 cache when changing gatsby-node.js & gatsby-config.js files.
- PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue
(https://gatsby.dev/parallel-sourcing-feedback)) · Run all source plugins at the
same time instead of serially. For sites with multiple source plugins, this can
speedup sourcing and transforming considerably.

success open and validate gatsby-configs - 0.076s
success load plugins - 1.529s
success onPreInit - 0.034s
success initialize cache - 0.006s
success copy gatsby files - 0.100s
success onPreBootstrap - 0.018s
success createSchemaCustomization - 0.005s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.061s
success building schema - 0.312s
info Total nodes: 45, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.002s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.066s
success update schema - 0.041s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.078s
success onPostBootstrap - 0.082s
info bootstrap finished - 5.104s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.186s
success write out requires - 0.004s
success run page queries - 0.017s - 3/3 179.47/s

 ERROR 

(node:93195) [DEP_WEBPACK_MAIN_TEMPLATE_OUTPUT_OPTIONS] DeprecationWarning:
MainTemplate.outputOptions is deprecated (use Compilation.outputOptions instead)


 ERROR 

(node:93195) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE] DeprecationWarning:
MainTemplate.hooks.require is deprecated (use
JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)


 ERROR 

(node:93195) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK]
DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to
NormalModule.getCompilationHooks(compilation).loader

⠴ Building development bundle
/${machine path}/nx-gatsby/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: NormalModuleFactory.afterResolve (ReactRefreshPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:291:14
    at Hook.eval [as callAsync] (eval at create (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/Hook.js:18:14)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:287:30
    at eval (eval at create (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:546:7
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:578:8
    at NormalModuleFactory.resolveRequestArray (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:929:34)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:570:11
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:650:8
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/NormalModuleFactory.js:800:5
    at finishResolved (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at done (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/cache/ResolverCachePlugin.js:217:12)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/cache/ResolverCachePlugin.js:164:28
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at Cache.store (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/CacheFacade.js:143:15)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/cache/ResolverCachePlugin.js:162:18
    at jobDone (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/FileSystemInfo.js:1839:5)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/FileSystemInfo.js:2112:7
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/util/AsyncQueue.js:347:5
    at Hook.eval [as callAsync] (eval at create (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._handleResult (/${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/util/AsyncQueue.js:317:21)
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/util/AsyncQueue.js:300:11
    at /${machine path}/nx-gatsby/node_modules/gatsby/node_modules/webpack/lib/FileSystemInfo.js:2982:5
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Could not start Gatsby Development Server. See errors above.</code></pre>
</details>

so, until now I wasn't able to move to Gatsby v3 😞 

follow my code: [update/gatsby_v3](https://github.com/erkobridee/nx-gatsby/tree/68bec3c21376e86bc68d43e4e0c07e49e79bfaaa)

**Comment by xiongemi** [comment]
> today I did another try to update the Gatsbyjs to v3 using the nx v12.0.4 and nx gatsby plugin v12.0.4
> 
> 1st step was to upgrade the nx to v12.0.4, I leave the nx gatsby plugin on the v11 and the gatsby on v2, with these dependencies I was able to run the gatsby application
> 
> then, I updated the nx gatsby plugin to v12.04 and manually I did the update of the gatsby to v3.3 following the [migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/)
> 
> on my first attempt to run, I got an error related to the core-js v2
> 
> **Can't resolve 'core-js/modules/web.dom.iterable.js'**
> ```
>  ERROR #98124  WEBPACK
> Generating development SSR bundle failed
> Can't resolve 'core-js/modules/web.dom.iterable.js' in
> '/${machine path}/nx-gatsby/apps/gatsby/.cache'
> If you're trying to use a package make sure that
> 'core-js/modules/web.dom.iterable.js' is installed. If you're trying to use a
> local file make sure that the path is correct.
> File: .cache/find-path.js:5:0
> ERROR #98124  WEBPACK
> Generating development SSR bundle failed
> Can't resolve 'core-js/modules/web.dom.iterable.js' in
> '/${machine path}/nx-gatsby/apps/gatsby/.cache'
> If you're trying to use a package make sure that
> 'core-js/modules/web.dom.iterable.js' is installed. If you're trying to use a
> local file make sure that the path is correct.
> File: .cache/loader.js:12:0
> not finished Building development bundle - 3.077s
> ```
> 
> `Could not start Gatsby Development Server. See errors above.`
> 
> so I force to use it, then I got another error:
> 
> **Errors related to the webpack**
> so, until now I wasn't able to move to Gatsby v3 😞
> 
> follow my code: [update/gatsby_v3](https://github.com/erkobridee/nx-gatsby/tree/68bec3c21376e86bc68d43e4e0c07e49e79bfaaa)

I took a look at repo and submit pr to fix your issue: https://github.com/erkobridee/nx-gatsby/pull/9

**Comment by erkobridee** [comment]
thanks @xiongemi, that fixed the gatsby, but I can't really go with that now, because of adding the webpack 5 on the root package.json that breaks the react app :)

I'll continue look for a solution, if it's possible to move to Gatsby v3 without break the react app inside of the mono repo :)

**Comment by Bulletninja** [comment]
Had the same problem, tried to apply the above solution (react-helmet and webpack update) but didn't work. Pinning core-js to ^2, did.

**Comment by xiongemi** [comment]
the quick solution is to use yarn or pnpm instead of npm.
I think this issue happens because @nwl/react use webpack 4 and gatsby needs webpack 5. by using npm, the wepback might not be resolved properly.

**Comment by xiongemi** [comment]
Now @nrwl/react support webpack 5 in version 12.6, so you could install using npm and able to serve up both react and gatsby apps. I created a pr in your repo:https://github.com/erkobridee/nx-gatsby/pull/11/files.
or you could install using yarn.
