### ISSUE TITLE
Nx 11.5.0 breaks existing Next.js workspaces

### ISSUE THREAD

**Issue by JamesHenry** [nrwl/nx#5027]
## Current Behavior

The updates to the babel configuration first introduced in https://github.com/nrwl/nx/commit/ddec362a5a9aff83a7b06a37c2c61af86d9b315c have caused existing Next.js workspaces to break.

The reason for this is that breaking changes in the babel configurations have been applied, without corresponding migrations being available:

- Root `babel.config.json` used to have presets, but if they remain there in 11.5.0 Next.js apps break
- Workspace libs didn't use to have their own `.babelrc` file, in 11.5.0 they do, and if they don't Next.js apps which consume them break.

There may be more issues, but point number 2 has a very large surface area that it impacts in my workspace and not something I can currently manually work past in order to uncover additional issues.

Beyond runtime concerns for the apps, there are additionally changes that have been made to babel + jest. These changes are also not migrated for existing workspaces:

**Existing projects:**

Has `babel-jest.config.json` and within `jest.config.js`:

```js
'^.+\\.[tj]sx?$': [
      'babel-jest',
      { cwd: __dirname, configFile: './babel-jest.config.json' },
    ],
```

**New project:**

No `babel-jest.config.json` and within `jest.config.js`:

```js
'^.+\\.[tj]sx?$': 'babel-jest',
```

## Expected Behavior

Non-major version upgrades should not cause existing workspaces to break

**Comment by jaysoo** [comment]
Hey @JamesHenry , we'll sync up on this as well, but just want to provide some info for anyone else that are experiencing similar issues:

1. `babel.config.json` should not contain any presets or plugins moving forward. We found a lot of issues when libraries and apps have conflicting presets/plugins with our own, so moving forward not having presets in the root would prevent a lot of potential bugs.
2. The workspace libs are tricky because they may or may not be used by a React/Next.js app, so we've also added the `--skipBabelrc` option to the generator. For workspace libs intended in Next.js apps, they should have `.babelrc` with `preset: ['@nrwl/web/babel']` at least so they will continue to compile.
3. For the jest issue, we didn't migrate in case folks have customized their setup, but if things are broken in 11.5 we should patch it.

We'll also make a change in the next version to display more helpful warnings when babel config is not working. Right now the messages aren't all that helpful which can lead to a lot of confusion.
