### ISSUE TITLE
SVG error when using nx with next-images

### ISSUE THREAD

**Issue by zhangciwu** [nrwl/nx#5130]
## Current Behavior
![image](https://user-images.githubusercontent.com/3340597/112635588-f73a2480-8e76-11eb-97c7-d033d2e705c1.png)
SVG can not show properly when using nx with next-images

## Expected Behavior
SVG shown

## Steps to Reproduce
See: https://github.com/zhangciwu/nx-next-svg-error-repo
Digest:
```jsx
import compass from './compass.svg';

export function Index() {
  return (
    <div className={styles.page}>
      <h2>Error of SVG: the below svg can not show properly</h2>
      <img src={compass}/>
    </div>
  );
}
```
next.config.js:
```js
const withImages = require('next-images');
const withPlugins = require('next-compose-plugins');

module.exports = withPlugins(
  [
    [
      withImages,
      {
        inlineImageLimit: 2048
      }
    ]
    // other plugins
  ],
  {}
);
```

### Failure Logs
No log
The svg file got wrapped in js in dist:
![image](https://user-images.githubusercontent.com/3340597/112635883-51d38080-8e77-11eb-9ecd-620bdb6fd4f5.png)

### Environment
Mac catalina, node 12

## Workaround

[This workaround works](https://github.com/nrwl/nx/issues/4182#issuecomment-737194409), just looks kind of ugly

**Comment by kirjai** [comment]
thanks for opening the issue!

I assume you're using `next-images` to load other types of images - not SVGs, but using it breaks importing SVGs, is that right?
In that case, there's another workaround - you can just tell `next-images` to ignore SVG imports using [the `fileExtensions` option](https://github.com/twopluszero/next-images#file-extensions). You could also use [the exclude option](https://github.com/twopluszero/next-images#exclude), if that works better with your setup.
That way, Nx handles SVGs, and `next-images` handles everything else you need.

I'll keep investigating though

**Comment by zhangciwu** [comment]
@kirjai Nope, I want to manage SVG with all the other types of images togeter, for example, do not inline big SVG files

**Comment by kirjai** [comment]
right, i see. so i don't think there's any other workaround other than the one you linked to.

for reference (i know you're already aware of this, but worth mentioning for anyone else stumbling upon this).
the reason for the issue is that in the webpack config we use, we use [`svgr`](https://github.com/gregberge/svgr) to allow users to import SVGs as react components. That interferes with whatever `next-images` is trying to do. you can still use `svgr` and `next-images` side by side, with some workarounds i mentioned in the previous comment. *but your request to be able to use `next-images` exclusively is definitely valid*, as we don't want to lock users into such decisions

Now, there's no official / supported way to disable `svgr` as of right now. so, what we're considering doing is allowing users to disable it via a new flag in `withNx`.

> As a side note, I noticed that in your repro repo, you're not using `withNx`, which we actually advise against. If you have specific reasons you're not using `withNx`, we'd like to know them, so we can address and fix them

We'll start working on this soon

**Comment by zhangciwu** [comment]
@kirjai We use nx since 9.x, so there is no `withNx` then. Any doc for this? I searched a bit but not found what it does

**Comment by kirjai** [comment]
> We use nx since 9.x

right, that explains it then. yeah, the documentation sounds like the one you found already ([link](https://nx.dev/latest/react/guides/nextjs#verify-the-project-39-s-next-config-js)). Probably shouldn't be in the "Deploying to Vercel" section, you're right. It started out as a deployment-only thing, but has grown in usefulness since. I'll make a note to address this 👍
