### ISSUE TITLE
JEST: default imports from json files cause tests to fail

### ISSUE THREAD

**Issue by smasala** [nrwl/nx#5195]
## Current Behavior
Because of https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules `json` (https://webpack.js.org/blog/2020-10-10-webpack-5-release/) imports now need to be as follows:

Previously - Webpack 4.x: `import * as x from './my.json;'`

Since - Webpack 5.x: `import x from './my.json';` as the line above will cause the build to fail.

Error you get with named exports and webpack 5:

```
Error: Should not import the named export 'someObj'.'someKey' (imported as 'x') from default-exporting module (only default export is available soon)
```

## Expected Behavior

In my case I import the json file and access it's values such as `x.someObj.someKey` (expect x not to be undefined)

## Result

`ng build` will import the `json` file correctly. However, jest will report that the import is `undefined` when using default imports.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
  Node : 14.16.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.6.1
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : 11.6.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by smasala** [comment]
Workaround / Fix 🤷‍♂️ :

Add to the top of the spec file (not inside the test suite):
```typescript
jest.mock('./my.json', () => ({
  __esModule: true,
  default: {
    someObj: {
      someKey: [],
    },
  },
}));
```

**Comment by Coly010** [comment]
Hi @smasala 

We do not currently support Webpack 5, however it is in our roadmap which you can read more on here: https://github.com/nrwl/nx/discussions/5475

Regarding your issue, perhaps I have misread it, are you suggesting that you have:
 - Updated to Webpack 5
 - Changed the import statement in your component / service to use the new `import x from 'my.json'`?
 - Running tests throws an error about this new import statement?

**Comment by leosvelperez** [comment]
@smasala I was taking a look at this and unfortunately, this seems to be an issue on Jest side.

You can see here https://github.com/facebook/jest/blob/master/packages/jest-runtime/src/index.ts#L843 how they resolve json files. You can notice they don't provide a `default` export in the resolved module (they just return the object as is, which works for named imports), while Webpack 5 forces us to use a default import.

There's also this meta issue https://github.com/facebook/jest/issues/9430, where you can search for "JSON/WASM module" and you'll find their position about this particular issue.

The workaround you mentioned works fine since you are effectively mocking the import to return a module with a default export.

**Comment by leosvelperez** [comment]
I'm closing this one since it doesn't seem something actionable for us. If you still think this an issue on Nx side, please feel free to reopen it.
