### ISSUE TITLE
Creating a lib does not create it in the correct filepath

### ISSUE THREAD

**Issue by Auha** [nrwl/nx#52]
I created a library called `client` using the following command `ng generate lib client`

I was assuming from the documentation that it would create the library in the following path:

`libs/client/src/client.ts`

Instead it created it like the following:

`libs/client/apps/<name of an app I made previously>/src/client.ts`

I could try to make a PR on this if you could point me in the right direction of where to go to fix it.

**Comment by vsavkin** [comment]
Could you provide a repro?

**Comment by Auha** [comment]
So I was able to reproduce the issue when I upgraded to @angular/cli: 1.5.0-beta.4. If I just keep to the original version of angular-cli it works consistently.

**Comment by ogix** [comment]
I have similar issue when generating another app

**Comment by vsavkin** [comment]
We are waiting on the CLI team to merge a PR that fixes it (https://github.com/angular/angular-cli/pull/7777). That's why the "fixed" version is needed. Once the CLI has this issue resolved, I'll update the generator to point to the latest version of the CLI.

Closing this as no changes in Nx needed--will be fixed by the CLI.
