### ISSUE TITLE
Angular NX Incremental Builds are too slow to use for local development

### ISSUE THREAD

**Issue by jredl-va** [nrwl/nx#5324]
## Current Behavior
Our largest angular client within the monorepo currently takes about 2 minutes and 45 seconds (ish) to start serving traffic using the `@angular-devkit/build-angular:browser` builder. A code change and subsequent reload takes around 12 (ish) seconds. 

With moving more and more of our frontends and libraries into the mono repo our next "boost" in developer productivity felt it would be around incremental builds. 

We've done so however we are finding them entirely too slow to make use of:
- A cold build (missing cache) takes 8 plus minutes (expectation would be not much slower than 3ish minutes)
- A rebuild after making a small html or css change is taking 4 plus minutes (expectation would be not much slower than 12s)
- A build that hits cache takes around 7 seconds (this is promising). 

## Expected Behavior

The expectation is that a build that misses cache wouldn't be too much slower than using the normal angular builders when serving locally. 

While maybe this isn't a problem with NX itself there are no indicators as where we should focus our attention to improve the speed of local builds. 

## Steps to Reproduce
We've followed the NX incremental build guide here: https://nx.dev/latest/angular/ci/setup-incremental-builds-angular

### Environment

```
  Node : 12.16.1
  OS   : darwin x64
  npm  : 6.14.5

  nx : 12.0.1
  @nrwl/angular : 12.0.1
  @nrwl/cli : 12.0.1
  @nrwl/cypress : 12.0.1
  @nrwl/devkit : 12.0.1
  @nrwl/eslint-plugin-nx : 12.0.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.1
  @nrwl/linter : 12.0.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.0.1
  @nrwl/web : 12.0.1
  @nrwl/workspace : 12.0.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by jredl-va** [comment]
For reference, I noticed another issue talking about how builds were slower between 11 / 12. I tried downgrading our workspace (incremental builds branch) to 11.6.3 today and found that for us they are roughly the same times as posted above. 

```
  Node : 12.16.1
  OS   : darwin x64
  npm  : 2.15.12

  nx : 11.6.3
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 11.6.3
  @nrwl/web : 11.6.3
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by GitMazzone** [comment]
@jredl-va Found this via your Slack post asking if anyone has been able to implement incremental builds and wanted to say yes, I have. There were several tricky things along the way, and I'm still not entirely convinced it's using the cache all the time (because it doesn't always say [retrieved from cache] in the build output).  
These are the steps as far as I can remember: 
I extracted any app submodules into their own buildable libraries by generating new ones with Nx's buildable lib generator.
Then I copied over any submodule code into the new buildable lib, updated tsconfig & workspace wiring, and deleted the old app submodule.
I updated the builders to use the `@angular-devkit/build-angular:browser` builder.

For reference, we've got about 12-15 buildable libs and a single app in this repo I tested this in, so it's by no means massive. 
I also did a ton of comparison between our repo and their [demo large, incremental repo](https://github.com/nrwl/nx-incremental-large-repo) while trying to get it working. I'm sure you've seen it, but it's hard to say where else to look without more info, sorry.

**Comment by jvandemo** [comment]
Seeing similar results here.

#### Without rebuildable libraries

```
$ ng serve app

// Make a small change that affects 4 libraries
// Rebuild takes 1.487 seconds

// Stop and start ng serve app
// 28.795 seconds
```

#### With rebuildable libraries (same application)

```
$ ng serve app

// Make a small change that affects 4 libraries
// Rebuild takes 14.271 seconds

// Stop and start ng serve app
// Instant => 🚀🚀
```

So the upside when restarting `ng serve` is super exciting. 🎉

However, the slower rebuild while running `ng serve` really affects the developer experience, since making changes during `ng serve` happens much more often than restarting `ng serve`.

Based on the CLI output, it seems that rebuilding the affected libraries causes the slowdown (as expected). Will perform more tests and share further findings if new data surfaces. 👍

The potential for this improvement is huge if the library build speeds could still be improved. 🚀

Thanks again to everyone involved for making this happen! 🏆

**Comment by leosvelperez** [comment]
Hey all! Thanks for reporting this!

As an FYI, we are aware of this issue and we are currently working to address it. As soon as we have something we'll update here.

**Comment by atifsyedali** [comment]
Is this because with rebuildable libraries we are not using watch mode of webpack, rather we are restarting a complete webpack rebuild every time code in one of those rebuildable libraries changes?

**Comment by atifsyedali** [comment]
Any updates on this? 

I have been thinking about this. The current way this is done is simply linking built webpack libraries with tsconfig paths I believe.

Another way might be to use webpack DLL for each buildable library; write a custom watcher for all files that were involved in that library from webpack POV; and if any files change then use a pool of webpack builders to recompile that file's library's DLL. Keep that webpack active so that the webpack's own watcher kicks into play (while we suspend our custom watcher for all that library's files) for fast recompile times.

I can't think of any other way to have both fast dev and build times.

**Comment by maxisam** [comment]
@leosvelperez while you are working on it, just let you know @nrwl/web:file-server has a bug. It doesn't compile SCSS correctly. I think it misses imports style. I will try to put together a repo when I have time.

**Comment by Coly010** [comment]
As @leosvelperez previously mentioned, this is something that we are aware of and we're continuing to work on to achieve better performance from.

As we have this listed on our internal roadmap, I'm going to close this issue for now. 

If we make any further progress on this, we will update this issue with the latest information.

Thanks everyone for the suggestions and for bringing this to our attention!
