### ISSUE TITLE
create-nx-workspace should respect angular-cli's  package manager default configuration

### ISSUE THREAD

**Issue by cvgaviao** [nrwl/nx#534]
in angular-cli v6 we can set the default package manager using:

> ng config -g cli.packageManager <yarn | npm>

so we don't need to specify which one to use when using `ng new`

would be great not to have to specify that parameter every time with `create-nx-workspace` also.

**Comment by jschwarty** [comment]
@cvgaviao With the latest version of Nx (v6) it is possible to create new Nx workspaces using the `ng new` command instead of the `create-nx-workspace` binary (see [Getting Started](https://nrwl.io/nx/guide-getting-started) for more info). This follows the Angular CLI workflow so it should honor the config setting. We are keeping the `create-nx-workspace` binary around just in case but don't currently plan on adding to it since we are now able to leverage the `ng new` command.

```
ng new myworkspacename --collection=@nrwl/schematics
```

**Comment by cvgaviao** [comment]
@jschwarty, thanks for the return.

**Comment by cvgaviao** [comment]
@jschwarty, I noted that `ng new myworkspacename --collection=@nrwl/schematics` is creating a project using versions of @angular/compiler-cli (6.0.1) that is not the current (6.0.7) installed in my environment.

Also, calling `yarn ng update` do not offer any update.

Wouldn't be possible to the `ng new` provided by nx collection to copy some from the collection provided by the current installed angular-cli ?
