### ISSUE TITLE
v12.0.4 NX ERROR Could not find Nx modules in this workspace

### ISSUE THREAD

**Issue by jhesgodi** [nrwl/nx#5349]
**Nx commands fail** **when** **run** in a **Docker** container from image **`node:lts-alpine`**.

After creating a new project setup with **`npx create-nx-workspace --packageManager=yarn`** and command **`nx run-many --target=build --all`** fails.

Updating to the latest `nx` **v12.0.4** doesn't fix the issue.

## Current Behavior
Any `nx` cli command throws error:
```
NX ERROR Could not find Nx modules in this workspace
```

## Expected Behavior
Command **`nx run-many --target=build --all`** will run on a Docker **`node:lts-alpine`** image successfully.

## Steps to Reproduce

0. Having **Docker** installed, 
1. Clone example github repo created just with `create-nx-workspace`: https://github.com/jhesg/nx-docker
2. Build the image and run containers by:
```
docker-compose up -d --build
```
3. Observe that, after having install packages and `nx` cli, build command fails with error
![image](https://user-images.githubusercontent.com/2966156/114684522-5394b380-9d54-11eb-8434-29c4d30b9a0a.png)

### Failure Logs
Please check the docker settings below:

<details><summary>Dockerfile</summary>
<p>

```Dockerfile
# --- -base- ---
FROM node:lts-alpine as base

ENV NODE_ENV=production
ENV YARN_CACHE_FOLDER=./yarn_cache

WORKDIR /root/app

COPY ./package.json ./yarn.* ./

RUN yarn install --frozen-lockfile

# --- -build- ---
FROM base as build

COPY . .
RUN npm i -g nx
RUN nx run-many --target=build --all

# --- -deploy- ---
FROM build as deploy

WORKDIR /var/www/html
COPY --from=build ./dist/apps/nx-docker .

RUN yarn install --production

# --- --- ---
CMD ls -las /root/app && tail -f /dev/null

```
</p>
</details>

<details><summary>docker-compose.yml</summary>
<p>

```yaml
version: '3.9'

services:
  nx-docker:
    container_name: nx-docker
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    restart: on-failure

```
</p>
</details>

### Environment
`nx report` fails to run inside the container as well :(

**Comment by jhesgodi** [comment]
Similar to: https://github.com/nrwl/nx/issues/4691

**Comment by FrozenPandaz** [comment]
I think this is a different issue. The issue is that you have `NODE_ENV=production` set quite high in the dockerfile. Specifically, it's above your `yarn install` which means only `dependencies` are installed, not `devDependencies` (including Nx modules).

If you change your dockerfile to this, it builds:
<detail>
# --- -base- ---
FROM node:lts-alpine as base

ENV YARN_CACHE_FOLDER=./yarn_cache

WORKDIR /root/app

COPY ./package.json ./yarn.* ./

RUN yarn install --frozen-lockfile

# --- -build- ---
FROM base as build

COPY . .

ENV NODE_ENV=production

RUN npx nx run-many --target=build --all

RUN ls -lah dist/apps/nx-docker

# --- -deploy- ---
FROM build as deploy

WORKDIR /var/www/html
COPY --from=build /root/app/dist/apps/nx-docker .

RUN yarn install --production

# --- --- ---
CMD ls -las /root/app && tail -f /dev/null

</detail>

**Comment by jhesgodi** [comment]
Thank you for looking into it @FrozenPandaz. That is indeed the error, I overlooked that variable.
Closing with suggestion.

Can that error be made more specific to mention that NX was not installed?
I was misled to think it wasn't finding `nx.json` or `workspace.json`

ie: `NX ERROR Could not find Nx modules, NX is not installed in this workspace`?
