### ISSUE TITLE
 nx g convert-tslint-to-eslint fails if tslint.json is in the workspace root

### ISSUE THREAD

**Issue by Splaktar** [nrwl/nx#5659]
## Current Behavior

`nx g convert-tslint-to-eslint` fails and appears to be unusable in my Nx project.

We also can't just run ` ng g @angular-eslint/schematics:convert-tslint-to-eslint` because that fails with:
```bash
Error: Angular CLI v10.1.0 and later (and no `tsconfig.base.json`) is required in order to run this schematic.
Please update your workspace and try again.
```

## Expected Behavior

The tool would recognize that the `tslint.json` file is located in the workspace root.

## Steps to Reproduce

1. Convert an Angular CLI v10 project with tslint to use Nx v10
2. Migrate to Nx v12
3. run `nx g convert-tslint-to-eslint --project=my-proj`

### Failure Logs
```bash
$ nx g convert-tslint-to-eslint --project=my-proj
✔ Would you like to ignore the existing TSLint config? 
  Recommended if the TSLint config has not been altered much as it makes the
  new ESLint config cleaner. (y/N) · false
✔ Would you like to remove TSLint and its related config if there are no TSLint projects remaining after
  this conversion? (Y/n) · true
We could not find a tslint.json for the selected project "apps/my-proj/tslint.json", 
  maybe you have already migrated to ESLint?
```

### Environment

```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.3.1
  @nrwl/cli : 12.3.1
  @nrwl/cypress : 12.3.1
  @nrwl/devkit : 12.3.1
  @nrwl/eslint-plugin-nx : 12.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.1
  @nrwl/linter : 12.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```
```
Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            9.1.15
@angular-devkit/schematics      9.1.15
@angular/fire                   6.1.4
@schematics/angular             9.1.15
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by JamesHenry** [comment]
@Splaktar Nx generates a project-level _and_ a root level tslint.json, so did you remove the project-level one at some point?

**Comment by JamesHenry** [comment]
You will want to align your workspace with what Nx does because this will also be the case for ESLint - you will have a project-level _and_ root level eslint config.

So the solution here is really to add back your `apps/my-proj/tslint.json` file, even if it is as simple as just an `"extends"` of the root config

**Comment by Splaktar** [comment]
> @Splaktar Nx generates a project-level _and_ a root level tslint.json, so did you remove the project-level one at some point?

I don't think so, but this project wasn't generated by Nx. It was just migrated to Nx.

**Comment by Splaktar** [comment]
> `apps/my-proj/tslint.json` file, even if it is as simple as just an `"extends"` of the root config

OK, thank you for confirming that approach. I'll do that.

**Comment by Splaktar** [comment]
Hrm, after fixing 1,537 errors from the migration (mostly removing new rules) now I'm down to 2 left...
```
/Users/splaktar/Git/my-workspace/apps/my-app/src/environments/environment.prod.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: apps/my-app/src/environments/environment.prod.ts.
The file must be included in at least one of the projects provided

/Users/splaktar/Git/my-workspace/apps/my-app/src/environments/environment.staging.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: apps/my-app/src/environments/environment.staging.ts.
The file must be included in at least one of the projects provided
```
Unfortunately, Google is not helping me with this one at all.

**Comment by Splaktar** [comment]
OK, I solved that by
```json
    {
      "files": ["*.ts"],
      // This fixed the environment file errors
      "parserOptions": {
        "createDefaultProgram": true
      },
```

**Comment by JamesHenry** [comment]
@Splaktar This again comes down to an incomplete migration - Nx generates a serious of tsconfigs (more than the Angular CLI) that make that setting unnecessary. It is not recommended to have `createDefaultProgram` enabled because it can mask configuration issues.

There could be other subtle issues with your migration you haven't encountered yet across different tooling, and what I recommend to anyone migrating like this is not to deal with config files by hand wherever possible, instead first generate a brand new project using `@nrwl/angular:application` and then apply your existing source files to that.

That way it is much less likely that you will have diverged from Nx's expected setup and you will find it easier to benefit from ongoing automated migrations, improvements etc.

Hope that helps!
