### ISSUE TITLE
Jest tests are broken when using web workers after the update

### ISSUE THREAD

**Issue by mddr** [nrwl/nx#5697]
## Current Behavior

Running tests using `nx test` fails if there's `import.meta.url` used – AFAIK it's neccessary for web workers to work with Webpack 5 (used by Angular 12).

## Expected Behavior

`nx test` should still work after the update. Before (using previous version with Angular 11) there were no issues, as `import.meta.url` was not used.

## Steps to Reproduce

Minimal repo: [https://github.com/mddr/jest-web-worker](https://github.com/mddr/jest-web-worker)

To reproduce, clone the repo above, install dependencies and run `nx test web-workers`.

### Failure Logs

Result of running the command above:
```
> nx run web-workers:test 
 FAIL   web-workers  libs/web-workers/src/lib/web-worker-service.spec.ts
  ● Test suite failed to run

    libs/web-workers/src/lib/web-worker.service.ts:7:58 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.

    7     const worker = new Worker(new URL('./sample.worker', import.meta.url), {
                                                               ~~~~~~~~~~~

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.352 s
Ran all test suites.

———————————————————————————————————————————————

>  NX   ERROR  Running target "web-workers:test" failed

  Failed tasks:
  
  - web-workers:test
```

### Environment

Library's `tsconfig.spec.json` contains `"module": "commonjs"`, as created by Nx tools. Removing or changing it to `esnext` (as told when running the test), doesn't make a difference.

Result of `nx report`:

```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : linux x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.3.3
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : 12.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by yannikfoth** [comment]
I am experiencing the same issue with version 12.3.6. Is there someone knowing more about it and maybe can support with a workaround or a solution here?

**Comment by pauleustice** [comment]
I'm also struggling with this problem. As @mddr says, it's due to Webpack 5 removing the [worker-loader](https://webpack.js.org/guides/web-workers/). The problem isn't nx-related as far I can tell; rather it's down to Jest's poor support of ES modules. It would be great if the nx team could devise a migration script for it though.

If it helps, there's one approach [documented here](https://github.com/just-jeb/angular-builders/issues/1003) that took some finding. It didn't help me (I'm unsure as to why), but it may help whoever reads this.

**Comment by MaximSagan** [comment]
Has anybody solved this yet? Or is there a workaround that's worked for anyone?
Surely the combination of workers and Jest can't be that uncommon among NX repos.

**Comment by mddr** [comment]
I haven't found the solution so far. Until it's fixed we decided to continue using v11.

**Comment by barbados-clemens** [comment]
Hi all, 
I looked more into this solution and it's quite puzzling. 

What I've concluded is that the jest ESM support is part of the issue here. 
creating this example in a plain TS workspace still produces the same error. 

Some options in things to try that I'm still working through. 

1. trying to mock `import.meta` I think you will still run into an issue as it probably isn't mockable 
2. using karma for these tests. this is probably the "easiest" solution that will work. just for the web worker lib, you can use Karma as the test runner which uses the browser so the API will go away. (still supported by nx)
3. look into babel-jest and using [babel-plugin-transform-import-meta](https://github.com/javiertury/babel-plugin-transform-import-meta)
4. providing the URL via DI token which allows for mocking in the tests (most _angular_ way)
5. moon shot using [vitest](https://vitest.dev)? ( I got this working in a plain TS file, but using angular causes issues. I do not recommend unless you want to be on the bleeding edge and writing a lot of your own setup glue)

I'll keep trying stuff so see if I can find a workable solution for y'all that involves jest.

**Comment by Avinash4243** [comment]
Hi @barbados-clemens - Any fix found for this? Been stuck with this for last 2 weeks. Any help would be highly appreciated. Thank you

**Comment by barbados-clemens** [comment]
> Hi @barbados-clemens - Any fix found for this? Been stuck with this for last 2 weeks. Any help would be highly appreciated. Thank you

I've provided some workaround in the comment above, but this is an issue with the lack of better ESM support with jest, since this isn't explicitly an nx issue that I can tell. 

my recommendation would be to abstract out the usage of the `import.meta.url` and provide it via DI to those that need it, providing an easier way to mock the deps.

**Comment by tjrobinson** [comment]
> my recommendation would be to abstract out the usage of the `import.meta.url` and provide it via DI to those that need it, providing an easier way to mock the deps.

This suggestion inspired me to try a few solutions. I didn't have much luck with DI but using the Jest config to swap out the file worked:

### session-prep-worker.factory.ts

I extracted this out to isolate the `import.meta.url` dependent code:

```typescript
/**
 * Provides the session preparation worker.
 */
export class SessionPreparationWorkerFactory {
    public get(): Worker {
        return new Worker(new URL('./session-preparation.worker', import.meta.url));
    }
}

```

### session-prep-worker.factory.fake.ts

Then I added this test double, which doesn't use `import.meta.url` anywhere:

```typescript
/**
 * Test double for the SessionPreparationWorkerFactory which doesn't depend on import.meta.url (which is not available in tests)
 */
export class SessionPreparationWorkerFactory {
    public get(): Worker {
        return new Worker(new URL('./session-preparation.worker', ''));
    }
}
```

### jest.config.js

Finally I configured Jest to replace references to the original file to the test double when running tests:

```javascript
    moduleNameMapper: {
        '.*session-prep-worker.factory': '<rootDir>/src/app/modules/survey-session/session-prep-worker.factory.fake.ts',
    },
```

**Comment by keshav-kishor** [comment]
> > my recommendation would be to abstract out the usage of the `import.meta.url` and provide it via DI to those that need it, providing an easier way to mock the deps.
> 
> This suggestion inspired me to try a few solutions. I didn't have much luck with DI but using the Jest config to swap out the file worked:
> 
> ### session-prep-worker.factory.ts
> I extracted this out to isolate the `import.meta.url` dependent code:
> 
> ```ts
> /**
>  * Provides the session preparation worker.
>  */
> export class SessionPreparationWorkerFactory {
>     public get(): Worker {
>         return new Worker(new URL('./session-preparation.worker', import.meta.url));
>     }
> }
> ```
> 
> ### session-prep-worker.factory.fake.ts
> Then I added this test double, which doesn't use `import.meta.url` anywhere:
> 
> ```ts
> /**
>  * Test double for the SessionPreparationWorkerFactory which doesn't depend on import.meta.url (which is not available in tests)
>  */
> export class SessionPreparationWorkerFactory {
>     public get(): Worker {
>         return new Worker(new URL('./session-preparation.worker', ''));
>     }
> }
> ```
> 
> ### jest.config.js
> Finally I configured Jest to replace references to the original file to the test double when running tests:
> 
> ```js
>     moduleNameMapper: {
>         '.*session-prep-worker.factory': '<rootDir>/src/app/modules/survey-session/session-prep-worker.factory.fake.ts',
>     },
> ```

Hi, @tjrobinson  I tried using the above approach but got this error:
Configuration error:

    Could not locate module ../worker/worker-url/util-worker-url mapped as:
    <<basePath>>\src\lib\worker\worker-url\util-worker-url-fake.ts.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/.*util-worker-url/": "<<basePath>>\src\lib\worker\worker-url\util-worker-url-fake.ts"
      },
      "resolver":  \node_modules\@nrwl\jest\plugins\resolver.js
    }
Can you please see if I am missing any config here? Thanks in advance.

**Comment by CharlieGreenman** [comment]
@tjrobinson you have the best solution I've seen after scouring the internet. Kudos to you. I've used this in combination with DI and I am convinced this is the solution people should use moving forward. I might do a write-up really quick to help the community, but this solution is top.

**Comment by CharlieGreenman** [comment]
wrote an article fam: https://medium.com/razroo/import-meta-url-and-jest-e8bff359b7c4
