### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by rogergl** [nrwl/nx#57]
Just looking at the screencast and the docs doesn't help to understand how the various parts should work together. Should I have one app and the remaining parts in lib ? Probably not. But why then does `ng serve` only serve the first app created ? I would have expected that every app automatically has it's own URL, like localhost:4200/firstapp or localhost:4200/secondapp. Or is that outside the scope of this project ?

**Comment by jschwarty** [comment]
Hey @rogergl great inquiries and suggestions. We will have some documentation and guides to explain more coming soon. But here are some answers for you now.

One of the powerful things about the libs structure is the ease of encapsulating stuff within `NgModule` chunks, keeping focus on small pieces. Instead of creating those within a single app, it is trivial to organize those in libs in the `Nx Workspace` and just consume them in the app. This sets you up to easily reuse those when you add more apps (among other advantages).

The `ng serve` of the first app in the list is a behavior of the Angular CLI. The port number or url to serve for each app is something that can be handled with the Angular CLI functionality. You can set up npm scripts to make serving individual apps easier:

**package.json**
```
{
  . . .
  "scripts" {
    . . .
    "serve:app1": "ng serve -a=app1 --port=4201",
    "serve:app2": "ng serve -a=app2 --port=4202",
    . . .
  }
  . . .
}
```
that can be run via:
```console
npm run serve:app1
```
This is a little more of an Angular CLI usage thing than a Nx thing, but there is probably some potential there for Nx to maybe make this setup easier. Guess it will depend on how opinionated Nx will be out of the box vs more flexibility.

**Comment by rogergl** [comment]
Thanks a lot for your kind reply. I'm really happy that there is an effort to provide some guidelines for large scale JS-Enterprise projects.
