### ISSUE TITLE
ng add @nrwl/workspace fails in angular app

### ISSUE THREAD

**Issue by heddendorp** [nrwl/nx#5751]
## Current Behavior

running `ng add @nrwl/workspace` leads to a fail like 

## Expected Behavior

The command should transform my project to a nx workspace

## Steps to Reproduce

Run the command in https://github.com/heddendorp/tumi-app/tree/nx-workspace

### Failure Logs

```
ERROR! apps/tumi-app-e2e/protractor.conf.js does not exist..
ERROR! apps/tumi-app-e2e/tsconfig.json does not exist..
ERROR! apps/tumi-app/src/app/components/index.ts does not exist..
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.4
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.3.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.4
  @nrwl/linter : 12.3.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by leosvelperez** [comment]
@heddendorp thanks for reporting this!

I'll have a look at it. Please note there this guide to manually transition your Angular CLI workspace to an Nx workspace https://nx.dev/latest/angular/migration/migration-angular#transitioning-manually. You can follow the steps outlined there to unblock the migration.

**Comment by leosvelperez** [comment]
The issue seems to be an Angular DevKit issue caused by files that are moved (renamed) and updated (overwritten). The Angular DevKit doesn't seem to be handling the new path of the moved files when validating the update operation. I created the following issue to try to get it resolved there: https://github.com/angular/angular-cli/issues/21083. If a resolution is delayed, we'll add a workaround in our generator.
