### ISSUE TITLE
Support Jest 27

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx#5771]
## Description

Jest 27 has just released and it only supports Node.js LTS and v15.
https://jestjs.io/blog/2021/05/25/jest-27
https://github.com/facebook/jest/releases/tag/v27.0.0

## Motivation

We can use the latest version of Jest.

## Suggested Implementation

A migration for `"testEnvironment": "jsdom"` may be needed.

**Comment by Brian-McBride** [comment]
I can across this error:
```
    import { render } from '@testing-library/react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Based on what you pointed out in your links, I added `testEnvironment: 'jsdom',` to my react projects. Just slipped it at the end of each `jest.config.js` 

Just in case anyone else runs across this. It will probably need to be added as a default value.

**Comment by tundera** [comment]
Yep, I saw this too the other day in a non-nx project. I think the `testEnvironment` setting needs to added since starting with v27 Jest assumes `testEnvironment: 'node'`.

I the Jest blog post linked up top, 

> Running tests in a JSDOM environment incurs a significant performance overhead. Because this was the default behavior of Jest unless otherwise configured up until now, users who are writing Node apps, for example, may not even know they are given an expensive DOM environment that they do not even need.
For this reason, we are changing the default test environment from "jsdom" to "node". **If you are affected by this change because you use DOM APIs and do not have the test environment explicitly configured, you should be receiving an error when e.g. document is accessed, and you can configure "testEnvironment": "jsdom" or use per-file environment configuration to resolve this.**

**Comment by cyrus-za** [comment]
@Brian-McBride's answer above solves it for all of my react libs, but none of my nextjs apps seem to work (with or without jsdom). I am fairly certain it has to do with the nrwl react plugin with this line
`'^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',`

**Comment by Brian-McBride** [comment]
I'm adding another thing I ran across. 

Make sure you set your `NODE_ENV` to `test` in the process that is running your jest tests.
I often have `development` set when I'm working.

**Comment by ruslan-byondxr** [comment]
While changing 'babel-jest' to 'ts-jest' , i got an error.
Testing components with SVG as ReactComponent :
```src/app/plugin.tsx:9:45 - error TS2307: Cannot find module '../assets/heart.svg' or its corresponding type declarations.```
