### ISSUE TITLE
[Documentation] tools folder purpose.

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#581]
Please explain tools folder purpose and usage.

**Comment by mrmeku** [comment]
Hey Justin, would you mind creating some documentation for what we use the tools folder for? I think currently its just used for our generated workspace schematics. However, you could also mention that this is the canonical folder where files are places which configure build systems (at least I know that's true for bazel projects I've worked with in the past)

**Comment by FrozenPandaz** [comment]
In the meantime, to expand on the use of the `tools` directory:

The `tools` directory is the home of non-sourcecode and non-config code.

One type of tool which you can create are `Workspace Schematics` (via `ng g workspace-schematic`) which allow you have codegen specific to your organization and help enforce standards.

In general, any type of **code** which does not fall under source code or configuration may be placed in the `tools` directory.

**Comment by jtlapp** [comment]
I'm still confused about the purpose of the tools directory. If it should not contain source code, why does it have a `tsconfig.tools.json`? Do you mean that it should not contain code that gets linked into an app?

**Comment by bcabanes** [comment]
@jtlapp Hi!
I'll try to add from @FrozenPandaz's description.

Because you can write your tooling script in Typescript (not just JavaScript), you will need to have a `tsconfig.tools.json` to be able to compile it.

The `tools` folder is not meant to contain any source code used in `apps`, `libs` or even `packages`. It is there to have a place where you can put _"stuff"_ that helps you manage your repo/monorepo, generators, executors, CI processes etc... Anything that is code related without affecting your artefacts source code, one example that would pop in mind right away would be your script to publish an artefact to your servers.

From the documentation:
>`/tools/` contains scripts that act on your code base. This could be database scripts, [local executors](https://nx.dev/recipes/executors/creating-custom-executors), or [local generators](https://nx.dev/recipes/generators/local-generators).

You can have a look at how we are using it on the Nx repository itself (we named it `scripts` for historical reasons) [here](https://github.com/nrwl/nx/tree/master/scripts).
It can also host your custom linting rules for example, like [here](https://github.com/nrwl/nx/tree/master/tools).

**Comment by jtlapp** [comment]
@bcabanes, your explanation is perfect. Thank you!

Now I'm thinking that a tool for running database migration files belongs in `tools`, in which case `tools` isn't only for "scripts that act on your code base". It's for scripts whose source is not used in `app`, `libs`, or `packages`.

It would be helpful for your more thorough explanation to appear in the docs.

**Comment by jtlapp** [comment]
Well, my attempt to but a migrations program in `tools` isn't working because it won't import libraries from `libs`. The  I guess it belongs in `apps` or `libs` after all. They [kysely](https://github.com/koskimas/kysely) query builder library requires that we code our own migration tool by calling into the library; no CLI is available or planned.

**Comment by bcabanes** [comment]
@jtlapp Nx supports natively migrations via generators (this is how we do it to migrate Nx itself and all its packages), you can create custom generators to handle your specific use case during migrations. That might not apply for the "[kysely](https://github.com/koskimas/kysely)" library you want to use but Nx generally supports this use case.

Here are some docs:
- https://nx.dev/recipes/advanced-plugins/migration-generators
- https://nx.dev/recipes/generators
- https://nx.dev/recipes/generators/local-generators

**Comment by jtlapp** [comment]
Thank you @bcabanes. I plan to get it working in a library package and then look into porting it to an Nx generator.

**Comment by jtlapp** [comment]
@bcabanes, I loved the plugin/generator development library, but I still wasn't able to get it to work because it's trying to pull configuration code in from other libraries, which apparently isn't allowed from either `tools/` or plugin libraries. I did succeed in making it an app in `apps/` though. See #14731.

Thanks for your help!
