### ISSUE TITLE
unable to generate coverage report

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#582]
Since the update to version 6 I am not able to get a valid coverage report.  I am assuming it is due to the changes in ng test where you can't just test all of your code at once.  Is there something I can change to get this functionality back?  I ran all the tests like you explained in [514](https://github.com/nrwl/nx/issues/514) by doing yarn affected:test --files=package.json.  I also just tried running ng test but below is what I get for a report:

![image](https://user-images.githubusercontent.com/5818023/41204530-3b2c4bfa-6cab-11e8-9037-7bb2bb0e57c3.png)

**Comment by mrmeku** [comment]
@jasedwards Sorry that you're having trouble with this feature! Lets try to get this fixed. Would you be so kind as to provide an example repository that we can use to reproduce the error? Ideally it should be as vanilla of an nx-workspace as possible. If you could do that for us it would greatly speed up the time it'll take us to fix this bug. 

Thanks!
Th

**Comment by jasedwards** [comment]
[cov-test.zip](https://github.com/nrwl/nx/files/2103983/cov-test.zip)

@mrmeku  Here you go.  thanks.

**Comment by FrozenPandaz** [comment]
Thanks, I think I know what's going on here. I'll address with an upcoming feature soon. ;)

**Comment by jasedwards** [comment]
thank you for the quick response.

**Comment by jasedwards** [comment]
@FrozenPandaz  this did not appear to fix the issue.  I updated all the karma.conf files in my workspace after updating to 6.2.  After that instead of one index.html with no data I got folders for each app and lib that contained an empty index.html just like what is in the above attached zip.  so I created a brand new workspace, generated an app and tried again.  the first time running yarn test:affected --all I got no coverage folder at all.  so I added coverage-istanbul to the reporters and then got the coverage folder with empty index.html again.  Am I missing something?

**Comment by Merott** [comment]
Can this issue be reopened? Running into the same issue, it seems...

**Comment by FrozenPandaz** [comment]
So there may be some confusion here.

1. By default, codeCoverage isn't set to true. You can either add it to your `angular.json` configuration or run `yarn affected:test --all --code-coverage`.
2. You will get separate coverage reports for each individual project (app or lib). This is because the tests run separately for each of those projects.

Summary, the following should work:
```sh
create-nx-workspace workspace
cd workspace
ng g app app1
ng g lib lib1
npm run affected:test -- --all --code-coverage
```

There should be a `coverage` directory with a similar file structure to your `apps` and `libs`. You can open `coverage/apps/app1/index.html` and `coverage/libs/libs1/index.html` and they should have coverage information.

For projects which were updated from 6.1, the migration did not adjust with your existing `karma.conf.js`. Unfortunately, existing projects won't get this fix as part of the migration and you must adjust your `karma.conf.js` files to get this fix. At the very least, the `coverageIstanbulReporter.dir` must be a unique path, otherwise, they override one another.

@jasedwards Did you alter your existing projects?

If someone has a repo, I could take a look at, this would be easier to debug.

**Comment by jasedwards** [comment]
@FrozenPandaz 
You are correct.  I assumed code coverage defaulted to true since a coverage folder was generated.  I have added that flag and all is well.  thanks.
