### ISSUE TITLE
add --unique option to library generators

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx#6042]
## Description

`nx g library mylib --directory=ui/global --unique=false` would create a project called "mylib" and not "ui-global-mylib". The option --unique is true by default. 

## Motivation

Grouping libraries by folders is a nice feature of dep-graph and in general its a structure way to organize my code. Short project names are easier to remember, and identify, and at the time of adding features to a library the short name is much more convenient that a long name.

## Suggested Implementation

This feature shouldn't be a breaking change. Making --unique default to true and have the library generator work as intended is good, but setting it to false gives me the coder a different a little control over the project names.

**Comment by webmandman** [comment]
@vsavkin Hello Victor, can i have some hints or tips on how I can contribute to nx with this feature request. Like what file should I look at to make this change?

**Comment by webmandman** [comment]
@vsavkin Any chance this will be added?

**Comment by jonhamm** [comment]
I have a similar problem - back from earlier versions of Nx I have multiple libraries with the same directory name but in different grouping folders - i.e. `libs/shared/util-core` and `libs/feature/util-core` is a simple example of this.

I tried to migrate our Nx 15.0.3 to 15.3.3 and it failed because the migration skipped the `util-core` libraries because they were not unique

I then tried to create a repo showing the error: 
This is also a Nx 15.0.3 repo.
But then I discovered that it is not possible to create libraries with non-unique names in the final directory - i.e. disregarding the grouping folder path
You can see the error if you checkout the repo and then do the following:
`npx nx generate @nrwl/angular:library util-core --style=scss --directory=feature --buildable --importPath=@exe/feature-util-core --no-interactive`
you will get this "error":
```
>  NX  Generating @nrwl/angular:library

[NX] Angular devkit called `writeWorkspace`, this may have created 'workspace.json' or 'angular.json
[NX] Double check workspace configuration before proceeding
Skipping feature-util-core since libs/feature/util-core/project.json already exists.
CREATE libs/feature/util-core/README.md
CREATE libs/feature/util-core/ng-package.json
CREATE libs/feature/util-core/package.json
CREATE libs/feature/util-core/tsconfig.lib.json
CREATE libs/feature/util-core/tsconfig.lib.prod.json
CREATE libs/feature/util-core/tsconfig.spec.json
CREATE libs/feature/util-core/src/index.ts
CREATE libs/feature/util-core/src/lib/feature-util-core.module.ts
CREATE libs/feature/util-core/project.json
CREATE libs/feature/util-core/tsconfig.json
UPDATE tsconfig.base.json
CREATE libs/feature/util-core/jest.config.ts
CREATE libs/feature/util-core/src/test-setup.ts
CREATE libs/feature/util-core/.eslintrc.json
```
So despite the warnings it appears that library names must be unique (final directory name)

Where did this breaking change sneak in ?
Is it by design? or is it an errror?
```
