### ISSUE TITLE
Nx autocomplete

### ISSUE THREAD

**Issue by adelin-b** [nrwl/nx#6151]
It would be decent to be able to use autocomplete when typing nx commands

Im thinking about two ways

 - make the `- - help` compliant with `compdef _gnu_generic nx`

- create completions through bash and zsh  

- using completion npm packages in the cli

**Comment by amayer42** [comment]
Was it intentional for this item to be closed? I know it's not the most important feature ever, but it would be nice to see it someday.

**Comment by justrhysism** [comment]
So #7027 was closed as a duplicate of this issue, and then subsequently this issue is closed :-|

One of the issues I have with Nx is that it's different to the traditional commands we're all used to, and when trying to execute a command on a specific package there's quite a lot to type in the terminal. Some form of autocomplete (leveraging the daemon, presumably) could make entering these commands much faster.

Don't make me think!
