### ISSUE TITLE
CI Successful tags are spamming releases feed

### ISSUE THREAD

**Issue by leon** [nrwl/nx#6224]
I subscribe to the NX releases, and at the moment nx is creating a new release for each successful CI run, which is a bit much :)

<img width="648" alt="Screenshot 2021-07-02 at 09 59 18" src="https://user-images.githubusercontent.com/13211/124241882-75643200-db1c-11eb-8ec1-a57fc9b33d45.png">

**Comment by JamesHenry** [comment]
@leon What is this a screenshot from please? I wonder if whatever tool it is can be adjusted?

I am also subscribed to releases on the repo but I correctly only get emails from GitHub when an actual release gets cut, as oppose to what you can see above which are just tags.

I know GitHub allows you to see tags under the releases view (but it hides them by default if they don't have a release associated with them), so hopefully the tool in question can be adjusted/made smarter

**Comment by leon** [comment]
It's from the app reeder where I have all my rss feeds.

The feed I'm listening to is `https://github.com/nrwl/nx/releases.atom`

It looks like the CI is creating new releases for each successful CI run.
I can see them on github too.
https://github.com/nrwl/nx/releases


The releases look the same as your new workflow plugin `nrwl/nx-tag-successful-ci-run` creates.

Could it be that you inadvertently have enabled it for nrwl/nx?

**Comment by JamesHenry** [comment]
@leon Yes as I stated above, GitHub applies tags under that releases view, it always has done - it’s been requested for years to be able to not show pure tags in there but they haven’t implemented it.

However, as I say, GitHub does know the difference between those tags and actual releases which is why it doesn’t notify people (like me) watching Releases natively in GitHub when those tags get created.

I have never used an RSS feed from GitHub but perhaps there is a way to add a filter in your RSS client? The tags and actual releases (with semver numbers) are structurally totally different so hopefully it’s possible to distinguish on the client?

**Comment by FrozenPandaz** [comment]
Hm this also makes it harder to see which versions a commit belongs to:

https://github.com/nrwl/nx/commit/ec389cfca29c9c868c92b82108429b00f73ae273

@meeroslav Is there an alternative implementation for this?

**Comment by leon** [comment]
@JamesHenry I understand, not a lot we can do about that if github doesn't split tags and releases into their own thing.

Just out of curiosity, what is the purpose of all the CI tags?

Ps.
You can close this issue now if you want.

**Comment by JamesHenry** [comment]
@leon The reason for using tags is to do with how `nx affected` should be applied when evaluating the criteria for the main/master branch.

In a naive approach, one might just go for `--base=HEAD~1` and `--head=HEAD`, however this fails to take into account that main/master builds can legitimately fail.

Conceptually, it is actual a `--base={{ LAST_SUCCESSFUL_MAIN/MASTER_BUILD }}` which we want to use for `nx affected` criteria.

Git tags are the easiest way to achieve this, because whenever a CI run completes successfully on main/master, we can tag the repo at that point, and then subsequent builds can check for the latest successful tag in order to derive a commit SHA to use for `--base`.

@FrozenPandaz That explanation above is the reason why we use tags, are you asking if something other than tags can be used for this purpose?

I believe the Nx repo is already using a CircleCI port from @meeroslav of the GitHub Actions I created to make this process of tagging and evaluating tags nice a concise in that tool, but I'll leave him to comment further as I was not directly involved in that.

**Comment by meeroslav** [comment]
Hey @leon and @FrozenPandaz,

As @JamesHenry already explained, the purpose of these tags is to mark the last successful build to base our `nx affected` on it. I have included the logic from his two Github actions - https://github.com/nrwl/nx-tag-successful-ci-run and https://github.com/nrwl/nx-set-shas to our CircleCI setup. The plan is to extract this to a reusable orb (planned for Thursday).

This concern actually arrived on time, as we still didn't finish the creation of the CircleCI orb. There are two options for reducing the noise that come to my mind:
- Once the new successful tag is set, all previous could be cleared out
- Skip using tags altogether and try to get the last successful commit directly (something similar to what @rarmatei did with https://github.com/nrwl/last-successful-commit-action)

Although the benefit of knowing the last successful build is higher than the inconvenience of having too many tags it still doesn't mean this is the only way.

cc @vsavkin

**Comment by meeroslav** [comment]
@FrozenPandaz, you are right. That commit log is very messy with all the successful tags in there.

**Comment by JamesHenry** [comment]
Ah I didn’t know about that work from @rarmatei - yes using GitHub’s API is another alternative to the non-git solution via file storage or a DB I mentioned above. Naturally the downside is the logic cannot be reused across other providers like Bitbucket and Gitlab but they likely have equivalent APIs that could be built upon

**Comment by meeroslav** [comment]
On CircleCI getting last successful build is not as simple as on GitHub, it would require a combo of two commands:
1. Get list of all pipeline runs (paginated)
```bash
curl --request GET --url 'https://circleci.com/api/v2/project/gh/nrwl/nx/pipeline?branch=master'
```
2. Get workflow of each pipeline run
```bash
curl --request GET --url 'https://circleci.com/api/v2/pipeline/{ pipeline_Id }/workflow'
```
3. If it's successful, return the revision SHA from the parent pipeline

Based on https://ideas.circleci.com/api-feature-requests/p/public-api-to-get-the-last-successful-build-for-a-specified-job direct implementation does not exist yet.
