### ISSUE TITLE
ng update equivalent action

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#6382]
## Description
See all packages that provide a migrate similar to the ng update command

## Motivation
I have a lot of packages and would like to know which I should update with nx migrate and which a can simply update with npm-check

## Suggested Implementation
Simply use what ng update provides

**Comment by FrozenPandaz** [comment]
Yes, we also read and run the same migrations that `ng update` does with `nx migrate`.

You can run `nx migrate @nrwl/workspace@latest` to update all of the packages that Nx added to your workspace such as `@angular/core` and `@angular/cli`.

Furthermore, you can also run `nx migrate @angular/material` and other things that `ng update` can update.

You can even run `nx migrate lodash` for packages that do not have any migrations setup but it will do little other than updating the field in your `package.json`.

The difference from `ng update` is that instead of installing and running the migrations all in the original command, `nx migrate` does things in two steps:

1. The initial `nx migrate` command will do the following:
  a. Update `package.json` with the appropriate versions of the dependencies. You can check these to make sure it did what you expect.
  b. Possibly write a `migrations.json` containing any migrations that should be run due to updating the packages. You can alter this `migrations.json` to run migrations one at a time or remove some migrations entirely etc.
2. Running `nx migrate --run-migrations` will then run the migrations listed in `migrations.json`

Here is a full guide: https://nx.dev/latest/react/core-concepts/updating-nx#migrating-to-the-latest-nx-version

I'm going to close this issue as the equivalent functionality already exists. If you have more questions, please create a new issue or ask in the community slack.

**Comment by DaSchTour** [comment]
You completly misunderstood what I mean. If you run ng update you simply get a list of packages that can be updated and probably have some schematics that do some updates. So I know for which it makes sense to update with ng/nx. Which lodash is not one of.

So what I wanted to say is, that while nx migrate @angular/core might be the equivalent as ng update @angular/core it's not true for nx migrate as it is not equivalent to ng update.

The result of nx migrate is
``` 
Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
/Users/dasch/Projekte/frontend/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/ky/zctv3hl1159b_r1mdff0b3xr0000gn/T/tmp-40359-PUBLynr2GpMd/node_modules/.bin/tao migrate 
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (/Users/dasch/Projekte/frontend/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:89:25)
    at Object.runCommand (/Users/dasch/Projekte/frontend/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/dasch/Projekte/frontend/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/dasch/Projekte/frontend/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/dasch/Projekte/frontend/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/Users/dasch/Projekte/frontend/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 40367,
  stdout: null,
  stderr: null
}

```

While ng update doesn't throw an error.

**Comment by tmtron** [comment]
maybe `nx update` should be an alias for `nx migrate` - or at least print some info to the console what to do

**Comment by DaSchTour** [comment]
> maybe `nx update` should be an alias for `nx migrate` - or at least print some info to the console what to do

the base `ng update` shows information about what packages have new versions. This is missing in nx. There is no possibility with nx to get the packages with updates list that `ng update` provides.

**Comment by tmtron** [comment]
@DaSchTour right. My idea is just to make getting started with nx easier when you used ng before. i.e. when I want to update something, I called `ng update` but since nx "decorates" ng, this is not possible anymore, because nx has no 'update' command.

So to make the "onboarding" of ng users a little easier, `nx update` should **at least** output some info, what to do instead. But I agree that it would be even better, if `nx update` worked the same way as ng.
