### ISSUE TITLE
`--with-deps` not passed to build in `affected:build`

### ISSUE THREAD

**Issue by steinroe** [nrwl/nx#6414]
## Current Behavior
Currently, `nx affected:build --with-deps --all` or `nx affected:build --with-deps --base=origin/staging` does not include `--with-deps` in the build command and therefore throws:
```
Some of the project core-service-shared's dependencies have not been built yet. Please build these libraries before:
- core-shared
- cloudevents

Try: nx run core-service-shared:build --with-deps
```

## Expected Behavior
It should pass `--with-deps` to the command. Running it directly, e.g. `nx run core-service-shared:build --with-deps` builds the libraries in the correct order.

This worked before with version `12.3.6` and stopped working after updating to the latest version.

## Steps to Reproduce
Update to latest version and run `nx affected:build --with-deps --all`

### Environment
 ```
 NX  Report complete - copy this into the issue template

  Node : 15.14.0
  OS   : darwin arm64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : 12.2.7
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

We need more details in order to reproduce the issue. Could you please share a minimal repo where the issue can be reproduced?

Please note that `--with-deps` is no longer required to be used in order to get dependencies to be built. We've added a better way to make sure dependencies are built in the right order and it doesn't require you to pass `--with-deps` in every command. You can configure target dependencies [globally](https://nx.dev/latest/react/core-concepts/configuration#target-dependencies) or on a [per-target basis](https://nx.dev/latest/react/core-concepts/configuration#targets).

**Comment by steinroe** [comment]
Thanks for the hint! While setting up the repro I recognised that the newly generated nx.json has the `targetDependencies` configured, while mine did not. Adding `targetDependencies` to nx.json solved it for me!
```
 "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```

**Comment by lasota-piotr** [comment]
I agree, after adding `targetDependencies`, it started working again. `nx migrate latest` didn't update this file
