### ISSUE TITLE
Support Cypress 8

### ISSUE THREAD

**Issue by wrslatz** [nrwl/nx#6430]
## Description
Nx should support Cypress 8. Cypress 8.0.0 is [now released](https://github.com/cypress-io/cypress/releases/tag/v8.0.0) and the [8.0.0 Changelog](https://docs.cypress.io/guides/references/changelog#8-0-0) highlights the key changes.

## Motivation
Allow Nx users to take advantage of new Cypress features, fixes, and performance improvements.

## Suggested Implementation
- Follow #5624 as an example.
    - Update current Cypress version in this repo to `8.0.0` or newer (if newer version is released).
    - Update current supported Cypress versions to include all `8` versions (`< 9` in `peerDependencies`)
- Make sure to check the changes to Cypress CLI config types and ensure the Nx Cypress CLI is compatible or makes any necessary changes.
    > The `Cypress.ConfigOptions`, `Cypress.ResolvedConfigOptions` and `Cypress.RuntimeConfigOption` types have been updated so that `ConfigOptions` match the JSON schema. Addressed in [#17251](https://github.com/cypress-io/cypress/pull/17251).

## Alternate Implementations
N/A

**Comment by tyler-morrison** [comment]
So I've got a work-in-progress branch started on this. The upgrading of dependencies is dead simple, but I have a question about the new [`--headless` by default change](https://docs.cypress.io/guides/references/migration-guide#cypress-run-runs-all-browsers-headless)

## Can we decouple `--headless` from `Cypress.run`?

In my opinion, this tight coupling is a design flaw; however, I may be missing some key context within the Nx executor. I believe we should refactor the logic to **only** rely on `--watch` flag so that we can omit `--headless` in [this line](https://github.com/minijus/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/cypress/src/executors/cypress/cypress.impl.ts#L177)…

```typescript
// Proposed change…
const result = await (!opts.watch ? Cypress.run(options) : Cypress.open(options));
```

In addition to simplifying the ternary that governs run vs. watch behavior, it would open up the ability for Nx users to explicitly set `cypress run --headed` to address this use case…
> _Chrome extensions will not load during a `--headless` run. If your run depends on a Chrome extension being loaded during `cypress run`, you should explicitly pass the `--headed` flag._
> – [Cypress: Migrating to Cypress 8.0](https://docs.cypress.io/guides/references/migration-guide#cypress-run-runs-all-browsers-headless)

## Additional Changes to Deprecate `--headless`
1. Add `logger.warn` if headless option is set `true`
```text
NOTE:
You can now remove the use of the '--headless' flag during 'cypress run' as this is the default for all browsers.
```
2. Add `logger.warn` if headless option is explicitly set `false`
```text
NOTE:
You can now remove the use of the '--headless' flag.
If your run depends on a Chrome extension being loaded during 'cypress run', you should explicitly pass the '--headed' flag.

If you are trying to execute 'cypress open', you should pass the '--watch' flag instead.
```
3. Add `--headed` option to [`schema.json`](https://github.com/minijus/nx/blob/master/packages/cypress/src/executors/cypress/schema.json) and [`CypressExecutorOptions`](https://github.com/minijus/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/cypress/src/executors/cypress/cypress.impl.ts#L15)
3. Decouple `opts.headless` and `opts.headed` within [`runCypress`](https://github.com/minijus/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/cypress/src/executors/cypress/cypress.impl.ts#L166)

I think we could do this without introducing a breaking change, but wanted to double-check with the team before submitting a PR.

**Comment by mehrad-rafigh** [comment]
@Cammisuli can you please take a look at that PR? Thanks

**Comment by demisx** [comment]
Any update on this by any chance? We'd love to start using Cypress 8 under Nx too.

**Comment by Cammisuli** [comment]
I'm going to try my best to get Cypress 8 support in. If someone gets to it before me, then awesome! 

But please don't wait for me, and if someone needs it asap, open a PR and I can review it 😄

**Comment by sumitparakh** [comment]
@Cammisuli  I can take a look.

**Comment by sumitparakh** [comment]
Hi @Cammisuli , please review:
https://github.com/nrwl/nx/pull/6808

**Comment by tyler-morrison** [comment]
@sumitparakh @Cammisuli do we want to address the deprecation of `--headless` in a separate PR?

SEE: [Comment above](https://github.com/nrwl/nx/issues/6430#issuecomment-894816349)

I believe we need to do a bit more to finalize this change, but would like some feedback before proceeding.

**Comment by Cammisuli** [comment]
@tyler-morrison, I appreciate the time you took to write out that analysis for `headless`! Thanks!

Here's one thing that we need to worry about though - there are still some users who are stuck on older version of Cypress. So we need to make sure that removing options or changing how things work don't break those users. I agree with all your points, and I'm ok with the changes, but we just need to make sure that we retain the old way as well 😅 

There should be a utility function to check what version of Cypress is currently installed https://github.com/nrwl/nx/blob/2f442ec63215fb2e16006603aabd2843c108628c/packages/cypress/src/utils/cypress-version.ts#L4-L20

**Comment by Cammisuli** [comment]
@tyler-morrison we can have another PR to address your headless analysis. I created a new issue #6811 to track since this one was closed by the PR.
