### ISSUE TITLE
WHen we don't set global email or name in git config creatung new workspace fails

### ISSUE THREAD

**Issue by ajitsinghkaler** [nrwl/nx#6570]
## Current Behavior

When ever I create a new workspace I cannot do it because I've not set the global git email and user. 

## Expected Behavior

I should be able to create a new workspace without setting global git params. I set different emails for different projects.

## Steps to Reproduce

Do git config --global --edit
Remove your email try to create a new work space
It fails using the following log
```bash
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address
```

### Environment

Not related to a created Nx workspace

**Comment by mandarini** [comment]
Hi there @ajitsinghkaler ! Thanks for filing an issue!

Unfortunately, I could not reproduce. Are you sure you're using the latest version of Nx? Regardless of me not being able to reproduce, I suggest you can do the following thing:

1. You can use the `skipGit` flag, to generate your workspace without setting up git. You can do this running the following command: `npx create-nx-workspace --skipGit=true`
2. Then, go into your workspace, set up your git username/email locally, and then do `git init`.

This will solve your issue.

PS: The reason I am saying I could not reproduce is the following:
1. I tried it with a completely misconfigured git (the `git` command was not working on my machine) and the workspace generated normally, it just did not set up git. No errors.
2. I tried it with an empty git username/email, and it just took the default name of my system user. So it still worked. 

However, this is ok, because I understand you may have a different setup on your local. So you can solve your issue by using the `skipGit` flag as I explained above! :)
