### ISSUE TITLE
Being able to define wrapping library (publishable) that includes other publishable libs without requiring them as npm dependencies

### ISSUE THREAD

**Issue by MartaGalve** [nrwl/nx#6574]
## Current Behavior
When I create a core library and define its index.ts file, I export components from a dependent lib's index.ts. With the default setup this results in a core library that defines its dependent lib as a peerDependency. 

// libs/ui/core-ui/src/index.ts
export {UiButton} from '@myorg/ui-button';

## Expected Behavior
I'd like to have a way of defining a lib as a wrapping lib, so its dependent libs are not defined as npm dependencies but just local dependencies that are bundled in the wrapping lib when built.

## Description
I'm trying to create a 'core' library that wraps other libraries, like Angular or many other libraries & frameworks do.
I want those libraries that core wraps to be also publishable independently, so a consuming app could import either individual libs or the core lib that contains them all as an npm module.

## Motivation
Having the flexibility of importing 1 wrapping library or individual libraries based on the needs of the app is useful.

Is there a workaround to make this work? I'd imagine I'd need to use a custom builder or a post-build script so, in the wrapping lib:
- the dependent libs are not added (or as deleted) as peerDependencies in the final package.json. 
- imports of other libs are replaced with relative imports based on the folder structure of the final npm pack, so:
 
// dist/libs/ui/core-ui/index.d.ts
// dist/libs/ui/core-ui/ui-core-ui.esm.js
export {UiButton} from '../ui-button';

Thank you,

**Comment by the-ult** [comment]
This would indeed be great.

Atm we are creating multiple internal libraries (auth, logging, error-handling, UI,etc)
And using the NX recommended way with multiple feature/ui/data-access libaries.

For example, when we wish to publish our `auth` library, it has peerDependencies to:
- auth-provider/keycloack
- auth-data
- shared-data
- shared-environment
- shared-utils

In this case we would like our users to only having to install `@our-org/auth` instead of all `peerDependencies` as well.

Is this possible in any other way?
