### ISSUE TITLE
Building Angular apps always trigger publishable dependencies whether in production mode or not

### ISSUE THREAD

**Issue by kkoo95** [nrwl/nx#6610]
## Current Behavior
2 things behind this ticket:  
With nx12, running a build prod on a angular application triggers the prod build of its dependent (publishable) libraries. That's fine I guess, but once it is done, it doesn't use what came out of them in their corresponding dist directories, but still direct access to their sources (through tsconfig "paths")
The other thing happening is, building an app in dev mode still trigger publishable dependencies build (and still don't use them)

## Expected Behavior
Shouldn't there be a tsconfig.prod to point to dist/libs/* to use what has just been built ? There are corner cases which doesn't work when we actually run the app with "npm installed" libraries.
Maybe the app build will be faster because everything is ready in dist directory ?? I don't know really about that, just asking.
Also, for apps built in dev mode, I feel like it makes sense to use direct code access, but why bother building them then ?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

It depends on what your configuration is. The dependent libs are being built, because the workspace is configured to [build the dependencies](https://nx.dev/latest/angular/core-concepts/configuration#target-dependencies). If you don't want the dependencies to be built, you can either change that configuration or remove it.

If you want to have the app build using the already built dependencies, you can make sure your apps are using the `@nrwl/angular:webpack-browser` executor. When that executor runs, it creates a temporary tsconfig where the paths point to the dependencies build output. You can read more about it in [the docs](https://nx.dev/latest/angular/ci/setup-incremental-builds-angular).

**Comment by kkoo95** [comment]
hum ok for now, i'll read that up. I totally missed that part from the docs. i though webpack-browser would be only to use custom webpack config over angular's
