### ISSUE TITLE
Deprecate Storybook Component Testing 

### ISSUE THREAD

**Issue by tyler-morrison** [nrwl/nx#6615]
## Description
With the release of `cypress@7.0.0` [component testing is no longer considered "experimental"](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/). Although it is still in **Alpha release** status, the core Cypress team is rapidly developing tools that support component testing as a first-class citizen within their test runner (SEE: [`@cypress/react`](https://github.com/cypress-io/cypress/tree/develop/npm/react) and [`@cypress/vue`](https://github.com/cypress-io/cypress/tree/develop/npm/vue)).

## Motivation
The [Storybook + Cypress](https://blog.nrwl.io/ui-testing-with-storybook-and-nx-4b86975224c) schematics were a resourceful solution in a time where proper tooling was sorely lacking; however, the landscape is shifting quickly. We ought to create an "end-of-life" process so that Nx users can adopt the native Cypress workflow as soon as possible.

### Key Benefits
- *Simplicity* – No reason to launch a Storybook iFrame when Cypress will offer its own `mount()` function.
- *Performance* – I have not had time to benchmark the two methods, but I speculate that Cypress will be faster.
- *Separation of Concerns* – Storybook for documentation. Cypress for testing.

#### 1. Maximize Testing Support for Component Libraries
- Jest is still an ideal tool for unit testing pure JavaScript, so we do not want to force users to choose between Jest and Cypress.
- Instead, component tests (via Cypress) and unit tests (via Jest) should be able to live side-by-side.
- Therefore, we will need a new target + file extension so that *"test"* target can be reserved for unit testing.
  - `*.spec.{js|ts}` files = Unit tests for Jest
  - `**/*.cy-spec.{jsx,tsx}`= Component tests for Cypress

#### 2. Maximize Framework Support
- Angular = Out of Scope
  - [`@cypress/angular`](https://github.com/cypress-io/cypress/tree/develop/npm/angular) is still work in progress. 
  - Therefore, we would want to leave Storybook + Cypress untouched until it is released on NPM,
- React
  - Begin deprecating all Storybook testing as outlined below

------

#### ~~1. Update Executor in `@nrwl/cypress`~~
~~*Cypress added new CLI commands that are not supported in `@nrwl/cypress:cypress` executor…*~~
> ~~Component tests will no longer be picked up when launching Cypress from cypress open or cypress run. Please use `cypress open-ct` or `cypress run-ct.`~~
> ~~– [Cypress: Component Testing Migration Guide](https://docs.cypress.io/guides/references/migration-guide#4-Use-CLI-commands-to-launch)~~
- ~~**testingType: "component"** should trigger `run-ct` by default~~
- ~~**testingType: "component" + `--watch`** should trigger `open-ct`~~

##### UPDATE 8/29:
The executor works just fine since it is using the NPM API. Also `--watch` trigger is remediated in #6811 

#### 2. Add `@nrwl/react:component-test-configuration`
*Generates default configuration files for Cypress component testing…*

`cypress.json`
```json
{
    "component": {
        "componentFolder": "./src/lib",
        "testFiles": "**/*.cy-spec.{js,jsx,ts,tsx}"
    }
}
```

Other operations might include…
- ADD `cypress` directory with typical sub-directories for fixtures, support, etc.
- ADD `tsconfig.cy-spec.json`, which extends `tsconfig.lib.json` and provides specific overrides.
- UPDATE `workspace.json` with a new target for the specified library (perhaps "ct" or "component")

#### 3. Refactor `@nrwl/react:stories`
*This should **only** create stories for all components declared in a library*

#### 4. Refactor `@nrwl/react:component-cypress-spec`
*This should generate `__componentName__.cy-spec.__fileExt__` as a sibling to Jest test for each component*

#### 5. Update `@nrwl/react:component`
*This should ensure future components have component tests generated by default, alongside the Jest `.spec` files…*
- ADD `__componentName__.cy-spec.__fileExt__`
- UPDATE `component.ts` so that it deletes `*.cy-spec` file if `options.skipTests === true` 

## Out of Scope …but also important
- Find a way to unify test coverage reporting across unit / component tests

## Alternate Implementations
1. **Allow Users to Choose** – Similar to the option to select Karma vs Jest for `unitTestRunner`, we could create Cypress component testing generators as *siblings* of the existing Storybook generators.
2. **Improve Documentation** – As mentioned in #5814 and #5622, the existing workflow is not well documented on Nx.dev.

**Comment by edbzn** [comment]
Hi, maybe it could interest you, we are working on a community alternative to `@cypress/angular`. Our package [`@jscutlery/cypress-angular`](https://github.com/jscutlery/test-utils/tree/main/packages/cypress-angular) works with Nx and Angular CLI as well. It already comes with an install generator that makes bootstrapping easier. Our next step is to deliver an executor to run Component testing using an executor. We recently added support to Cypress 8.1.0 where Component testing is no more experimental.

**Comment by tyler-morrison** [comment]
@edbzn Good call out! I saw your repo mentioned in #5622 and again in [@cypress/angular](https://github.com/cypress-io/cypress/tree/develop/npm/angular), but it’s been a few years since I last worked in the Angular ecosystem.

**question:** Are there any plans to merge your efforts with `@cypress/angular`? If not, what are the advantages / disadvantages compared to `cypress-angular`?

**Comment by edbzn** [comment]
Well, we should originally work with cypress on that, but it turned differently. The actual Angular implementation `@cypress-angular` was an external package not maintained by Cypress, we started to open discussions on this project, but finally, we decided to create our own implementation because we had another picture of how we should design this and we wanted to make our own decisions. It was decided that the first project was officially included in Cypress and we became a community alternative.

To compare these two projects:

1 - The official one relies on the `TestBed` which is the module that bootstraps Angular in a unit-test environment. Our implementation relies on the `BrowserPlatformDynamic` which is the module used to bootstrap Angular in the browser, we wanted that to make sure it behaves exactly as your application in the browser, especially the rendering part.

2 - The API was the biggest issue for us, here is the official one: 

```ts
it('...', () => {
  initEnv(AppComponent);
  mount(AppComponent);
  cy.contains('hello world');
});
``` 

Component testing with other frameworks use only one `mount` function, why only Angular should have this `initEnv(AppComponent)` function? It feels redundant, less simple. Here is our API: 

```ts
it('...', () => {
  mount(AppComponent);
  cy.contains('hello world');
});
```

3 - We have built-in schematics support with Nx and Angular CLI, they have not.
4 - The official solution does not come with the Webpack configuration that will start the dev server to run tests against, you need to copy [this file](https://github.com/bahmutov/cypress-angular-unit-test/blob/master/cypress/plugins/webpack.config.ts) and hope it will work with your application. Our implementation grabs the Webpack configuration from Angular CLI internals, so we make sure we have the closest symmetry with the production build.

There's a lot more to tell on topics like test coverage, separation of concerns... but I'll end over on the highlights I exposed.

**Comment by jasonmacdonald** [comment]
Is there any update on this? I'm about to start a new project and feel like using the current storybook/cypress plugins is about to get deprecated right at the start of my project. Is there anything I can do to avoid this for now?

**Comment by tyler-morrison** [comment]
@jasonmacdonald I made some headway on this issue over the holiday and plan to submit a PR in early Jan.

One of my remaining "To Do" items is to create a migration script for users with existing Storybook tests.

In theory, this shouldn't be too difficult because you're essentially swapping the `cy.visit('storybook-iframe')` for  a `cy.mount(<TestComponent/>)`

**Comment by barbados-clemens** [comment]
We will be adding better support for component testing when cypress 10 releases and the react storybook-cypress generator is something that will have to be addressed as it will be confusing at first to know which generate does what. 

I'm going to close this issue for now but you can track some progress on the [feat/cypress-10 branch](https://github.com/nrwl/nx/tree/feat/cypress-10) and I'll make a tracking PR for that when we are getting closer for it to be released.

**Comment by barbados-clemens** [comment]
@tyler-morrison if you want to start giving cypress 10 PR some testing to see if there's any show stoppers that would be awesome!
1. right now there isn't a cypress v10 tag on npm so it's hard coded to install a build from a semi-recent commit, but is the macos version. you can override this by manually install the cypress v10 for you OS as needed.
2. I would love to get feedback on the e2e conversation generator that will take cypress v8/v9 to v10.

Ping me if you have any questions/need help. Thanks!

**Comment by barbados-clemens** [comment]
Just to also note, we are not going to desperate the storybook/cypress testing generators/support. While there is some overlap. Component testing doesn't cover all use cases that storybook/cypress does. mainly still having a documentation site along with testing UI components.

this makes sense in terms of creating UI/Component libraries where you want to have tests for the stories. Cypress Component testing makes sense if you don't want to have a storybook site for the components. Think feature components that aren't really UI Components, closer to your implementation of that product vs a generic component that might make more sense to have in storybook. 

Because of that, I am going to close this issue since we won't be deprecating, but still are providing cypress component testing support. so free to talk about cypress component testing [on that PR if you got questions/issues with the WIP implementation](https://github.com/nrwl/nx/pull/9201)

**Comment by tyler-morrison** [comment]
Pumped to check this out! I'll spin up a test repo later this week
