### ISSUE TITLE
eslint outputFile is not cached

### ISSUE THREAD

**Issue by NotSoImportant** [nrwl/nx#6656]
## Current Behavior
When running linting with `outputFile` we are getting the cli output from the cache, but not the outputFile containing the lint result.

## Expected Behavior
outputFile will be cached and retrieved from the cache as well

## Steps to Reproduce

1. run linting once with `--outputFile=xxx` (result will go to the cache)
2. delete the output file
3. run linting again with the same command (cli output will come from cache, but not the output file)

## Details
Output from cache:
```
nx run my-app:lint --format=checkstyle --outputFile=dist/eslint/my-app.xml --force [existing outputs match the cache, left as is]
Lint errors found in the listed files.
```
### Reasoning
We are using Jenkins Warnings NG Plugin to display a trend based on these outputFiles. However since using the nx cache this is no longer reasonably working, because the outputFile xml files are not retained.
```
[ESlint] [-ERROR-] No files found for pattern 'dist/eslint/*.xml'. Configuration error?
```

## Environment
nx 12.6.2

**Comment by meeroslav** [comment]
Hi @NotSoImportant,

I'm assuming you are using a default lint target configuration which doesn't have `outputs` defined. This would explain why your `outputFile` was not cached.
You can change your configuration with following two lines:

```
"lint": {
  "executor": "@nrwl/linter:eslint",
  "outputs": ["{options.outputFile}"], <- important for caching
  "options": {
    "lintFilePatterns": [
      "apps/my-app/src/**/*.ts",
      "apps/my-app/src/**/*.html"
    ],
    "outputFile": "dist/eslint/my-app.xml" <- default value
  }
},
```

If you want to always generate outputFile then this configuration would work just fine. If you only need to run the command with `outputFile` on CI and normally you run it without, then the command would fail if outputFile is not defined (in options or as command line argument). 

This will be fixed in the linked PR.

**Comment by NotSoImportant** [comment]
Thank you @meeroslav. Looks like I just need to configure outputs as well. I will try that. Thank you.
