### ISSUE TITLE
error TS2304: Cannot find name 'require'.

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#681]
with latest nx update, we are getting `error TS2304: Cannot find name 'require'.` error.
according to this link  https://github.com/angular/angular-cli/issues/2221#issuecomment-367282459

this issue is caused  because nx adding empty `"types": []` to `tsconfig.app.json`

please remove `"types": []`  from nx generator template.

**Comment by matheo** [comment]
@xmlking have you customized your root `tsconfig.json` in such way that it conflicts with the template? if you are defining the types "manually" instead let the `typeRoots` do the job, what's your reason? if your case is not generic, you should customize the `types` of your generated projects because libraries don't use the same types as applications sometimes, and I guess that's why the generator template reset them.

**Comment by xmlking** [comment]
@matheo i haven't customized `tsconfig.json`.  All default from nx generated workspace.  
i have a need for importing via `require`
`const { version: appVersion } = require('../../../../../../package.json');` 
https://github.com/xmlking/ngx-starter-kit/blob/master/libs/home/src/lib/components/footer/footer.component.ts#L3 

I have to remove `"types": []` from generated app to overcome this issue.  
https://github.com/xmlking/ngx-starter-kit/blob/master/apps/webapp/tsconfig.app.json

**Comment by FrozenPandaz** [comment]
@xmlking 

It seems you are able to workaround the issue.

I think in general, people usually do not use `require` within the Angular Application so there may not be a need to change anything in the generated `tsconfig.app.json`. Thus, I am going to close this issue as there is a workaround for people who need `require` and other `types`.

**Comment by xmlking** [comment]
What would be best practice to load package.json in typescript for use like showing in  version number in webpage

**Comment by FrozenPandaz** [comment]
@xmlking 

I think `require` or `fs.readFile` would work fine. I don't think it's necessarily a bad practice and as you mention, it is useful for reading `json`.

Sorry for any misunderstanding, my point is that a _majority_ of people aren't doing that as far as I know so it doesn't make sense to make a change to the way things are currently. The `tsconfig` files are generated for you to use, but you can also alter them to suit your needs :).

**Comment by xmlking** [comment]
Agree.  @FrozenPandaz thank for all the great work you are adding e.g., jest, nodejs apps

**Comment by carlsonmacario** [comment]
Quick and Dirty
If you just have one file using require, or you’re doing this for demo purposes you can define require at the top of your TypeScript file.

declare var require: any
TypeScript 2.x
If you are using TypeScript 2.x you no longer need to have Typings or Definitely Typed installed. Simply install the following package.

npm install @types/node --save-dev
The Future of Declaration Files (6/15/2016)

Tools like Typings and tsd will continue to work, and we’ll be working alongside those communities to ensure a smooth transition.

Verify or Edit your src/tsconfig.app.json so that it contains the following:

...
"types": [ "node" ],
"typeRoots": [ "../node_modules/@types" ]
...
Make sure is the file in the src folder and no the one on the root app folder.

By default, any package under @types is already included in your build unless you’ve specified either of these options. Read more

TypeScript 1.x
Using typings (DefinitelyTyped’s replacement) you can specify a definition directly from a GitHub repository.

Install typings

npm install typings -g --save-dev
Install the requireJS type definition from DefinitelyType’s repo

typings install dt~node --save --global
Webpack
If you are using Webpack as your build tool you can include the Webpack types.

npm install –save-dev @types/webpack-env

Update your tsconfig.json with the following under compilerOptions:

"types": [
"webpack-env"
]
This allows you to do require.ensure and other Webpack specific functions.

Angular CLI
With CLI you can follow the Webpack step above and add the “types” block to your tsconfig.app.json.

Alternatively, you could use the preinstalled node types. Keep in mind this will include additional types to your client-side code that are not really available.

"compilerOptions": {
// other options
"types": [
"node"
]
}

Full Source Available At [Here](https://icetutor.com/question/typescript-getting-error-ts2304-cannot-find-name-require/)

**Comment by msschl** [comment]
Had the same issue! After adding `"types": [ "node" ]` to the `tsconfig.app.json` my angular app compiled again.

**Comment by IslombekMe** [comment]
The same thing happened in Nx 15.8.1. All of my tsconfigs with empty `"types": []` were giving me an error.
