### ISSUE TITLE
Remediate `headless` option for Cypress 8 

### ISSUE THREAD

**Issue by Cammisuli** [nrwl/nx#6811]
So I've got a work-in-progress branch started on this. The upgrading of dependencies is dead simple, but I have a question about the new [`--headless` by default change](https://docs.cypress.io/guides/references/migration-guide#cypress-run-runs-all-browsers-headless)

## Can we decouple `--headless` from `Cypress.run`?

In my opinion, this tight coupling is a design flaw; however, I may be missing some key context within the Nx executor. I believe we should refactor the logic to **only** rely on `--watch` flag so that we can omit `--headless` in [this line](https://github.com/minijus/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/cypress/src/executors/cypress/cypress.impl.ts#L177)…

```typescript
// Proposed change…
const result = await (!opts.watch ? Cypress.run(options) : Cypress.open(options));
```

In addition to simplifying the ternary that governs run vs. watch behavior, it would open up the ability for Nx users to explicitly set `cypress run --headed` to address this use case…
> _Chrome extensions will not load during a `--headless` run. If your run depends on a Chrome extension being loaded during `cypress run`, you should explicitly pass the `--headed` flag._
> – [Cypress: Migrating to Cypress 8.0](https://docs.cypress.io/guides/references/migration-guide#cypress-run-runs-all-browsers-headless)

## Additional Changes to Deprecate `--headless`
1. Add `logger.warn` if headless option is set `true`
```text
NOTE:
You can now remove the use of the '--headless' flag during 'cypress run' as this is the default for all browsers.
```
2. Add `logger.warn` if headless option is explicitly set `false`
```text
NOTE:
You can now remove the use of the '--headless' flag.
If your run depends on a Chrome extension being loaded during 'cypress run', you should explicitly pass the '--headed' flag.

If you are trying to execute 'cypress open', you should pass the '--watch' flag instead.
```
3. Add `--headed` option to [`schema.json`](https://github.com/minijus/nx/blob/master/packages/cypress/src/executors/cypress/schema.json) and [`CypressExecutorOptions`](https://github.com/minijus/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/cypress/src/executors/cypress/cypress.impl.ts#L15)
3. Decouple `opts.headless` and `opts.headed` within [`runCypress`](https://github.com/minijus/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/cypress/src/executors/cypress/cypress.impl.ts#L166)

I think we could do this without introducing a breaking change, but wanted to double-check with the team before submitting a PR.

_Originally posted by @tyler-morrison in https://github.com/nrwl/nx/issues/6430#issuecomment-894816349_

**Comment by Cammisuli** [comment]
_COPYING MY REPLY_

@tyler-morrison, I appreciate the time you took to write out that analysis for `headless`! Thanks!

Here's one thing that we need to worry about though - there are still some users who are stuck on older version of Cypress. So we need to make sure that removing options or changing how things work don't break those users. I agree with all your points, and I'm ok with the changes, but we just need to make sure that we retain the old way as well 😅 

There should be a utility function to check what version of Cypress is currently installed https://github.com/nrwl/nx/blob/2f442ec63215fb2e16006603aabd2843c108628c/packages/cypress/src/utils/cypress-version.ts#L4-L20

**Comment by tyler-morrison** [comment]
@Cammisuli thanks for highlighting this. I'll rebase my changes off of @sumitparakh branch and include that utility along with the proper testing so that we can ensure backward compatibility.

I should be able to post up a PR for all of this by ~Thurs when I'm back from vacation. Appreciate the feedback!

**Comment by tyler-morrison** [comment]
@Cammisuli just created a PR. Two quick notes…
1. I believe the unit tests in [cypress.impl.spec.ts](https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.spec.ts) would benefit from additional refactoring in a follow-up issue.
   - I chose to leave them relatively untouched to increase confidence in our regression tests.
2. I believe the `options` in `runCypress` would benefit from additional typing of [`CypressOptions`](https://github.com/cypress-io/cypress/blob/bdb5574e9b947ec0397dba11b79bab1f484ba2f7/npm/cypress-schematic/src/builders/cypress/index.ts#L16)
   - This would help us distinguish / map `CypressExecutorOptions` to the NPM API.
   - However, it might require additional refactoring of `normalizeOptions` so that we separate out the options passed to Webpack Dev Server vs. the ones forwarded to Cypress CLI.
