### ISSUE TITLE
Running multiple build-storybook targets in parallel results in ngcc conflict error.

### ISSUE THREAD

**Issue by LuukMoret** [nrwl/nx#6842]
## Current Behavior
Running multiple build-storybook targets in parallel (i.e. in affected or run-many use case) will result in an ngcc conflict error `ngcc is already running at process with id [process id]`. This is especially problematic running component tests with cypress using storybook in parallel as this will also result in the same error because this uses the build-storybook target. 

Commands that will cause the error:
`npx nx run-many --target=build-storybook --projects=[project1,project2] --parallel`
`npx nx run-many --target=e2e --all --parallel`.

## Expected Behavior
Running multiple build-storybook targets should not result in an ngcc lock error.
## Steps to Reproduce
- Create a new Angular workspace
- Run npm
- Create 2 libs with 2 storybook configurations
- Run `npx nx run-many --target=build-storybook --projects=[project1,project2] --parallel`

An ngcc error should appear, presumably because they are both using the same app which will trigger a short lock.

Repo where error is reproduced after executing the above steps: https://github.com/LuukMoret/test-org
Run command `npm install` and then run command `npx nx run-many --target=build-storybook --projects=test,test2 --parallel` or run `npx nx run-many --target=e2e --all --parallel`

### Environment
Node : 14.17.5
OS   : darwin x64
npm  : 6.14.14

nx : Not Found
@nrwl/angular : 12.7.2
@nrwl/cli : 12.7.2
@nrwl/cypress : 12.7.2
@nrwl/devkit : 12.7.2
@nrwl/eslint-plugin-nx : 12.7.2
@nrwl/express : Not Found
@nrwl/jest : 12.7.2
@nrwl/linter : 12.7.2
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 12.7.2
@nrwl/web : Not Found
@nrwl/workspace : 12.7.2
@nrwl/storybook : 12.7.2
@nrwl/gatsby : Not Found
typescript : 4.3.5

**Comment by smasala** [comment]
This is causing our CI pipeline to take ages!

**Comment by slaven3kopic** [comment]
Any news on this?

**Comment by daniel-cpl** [comment]
We are experiencing the same issue

**Comment by stefancplace** [comment]
had the same problem recently ...

**Comment by wrslatz** [comment]
https://github.com/nrwl/nx/issues/6835 seems like a potential solution on the Nx side, at least for the case where the server target is the same across the parallel tests.

**Comment by Kamshak** [comment]
Found another solution for this, but hacky: 

1) Before running parallel storybook builds (e.g. in pipeline) run ngcc once (took the parameters from what storybook passes): `ngcc --create-ivy-entry-points --first-only`
2) Patch the storybook package (I use patch-package for this) to prevent storybook from running ngcc again on each parallel instance:
```diff
diff --git a/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js b/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js
index deb7caf..90e9efd 100644
--- a/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js
+++ b/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js
@@ -131,7 +131,9 @@ exports.webpack = function (webpackConfig, options) { return __awaiter(void 0, v
                 if (angularOptions.enableIvy === false) {
                     return [2 /*return*/, webpackConfig];
                 }
-                exports.runNgcc();
+                if (!process.env.CI) {
+                  exports.runNgcc();
+                }
                 return [2 /*return*/, __assign(__assign({}, webpackConfig), { resolve: __assign(__assign({}, webpackConfig.resolve), { mainFields: [
                                 'es2015_ivy_ngcc',
                                 'module_ivy_ngcc',
```

**Comment by Coly010** [comment]
Hey! Thanks everyone for contributing to this issue.

The `ngcc` lock is an Angular safeguard to prevent erroneous compilations, while there is a compilation ongoing currently, of any ViewEngine libraries in the `node_modules` folder.

As can be seen here in a related Angular issue: https://github.com/angular/angular/issues/40405#issuecomment-759468563

This isn't in fact an error. It's just information that is logged to help you understand what is happening. 

However, I am aware that having to wait on the ngcc to complete for each and every target does become cumbersome. That said, once ngcc has made a first pass, each subsequent pass should be faster as it will not need to actually recompile anything.

Storybook forces `ngcc` to run, because it could be used in a non-Nx workspace. With Nx + Angular Preset, we make sure to run `ngcc` after installation.

That makes @Kamshak 's workaround (https://github.com/nrwl/nx/issues/6842#issuecomment-1017694561) completely viable. 

Unfortunately, until Angular drops `ngcc`, this will always present itself as an issue. With Storybook forcing `ngcc` to run every time, this is something that is outside of our control to fix. As such, I'll close this issue.

Again, the workaround from @Kamshak should work!
