### ISSUE TITLE
Running nx migrate latest gives warning "project is using a third-party builder"

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#6870]
## Current Behavior

Gives warnings that "project is using a third-party builder"

## Expected Behavior

Guess I should not get this information at all? :) 

## Steps to Reproduce

Have this in your angular.json as a lib
````
"ui-toster": {
      "root": "libs/ui/toster",
      "sourceRoot": "libs/ui/toster/src",
      "projectType": "library",
      "prefix": "mathem",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/ui/toster/src/**/*.ts",
              "libs/ui/toster/src/**/*.html",
              "libs/ui/toster/src/**/*.html"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/ui/toster/jest.config.js",
            "passWithNoTests": true
          },
          "outputs": [
            "coverage/libs/ui/toster"
          ]
        }
      },
      "schematics": {
        "@nrwl/schematics:component": {
          "styleext": "scss"
        }
      }
    }
````

### Failure Logs

````
"test" target in "ui-toster" project is using a third-party builder.
You may need to adjust the options to retain the existing behavior.
````

### Environment

````

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.21.1
  
  nx : Not Found
  @nrwl/angular : 12.8.0
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
````

**Comment by leosvelperez** [comment]
I revisited this and checked any possible implications or impact on folks running these migrations. I found out that:

- This particular Angular CLI migration is for targets using the `@angular-devkit/build-angular:browser` or `@angular-devkit/build-angular:server` executors.
- Even though those executors are normally only used by `build` and `serve` targets, the migration is logging a warning for every target (e.g. `lint`, `test`, etc.). This creates more noise but at the same time is expected, because when migrations authors can't assume the names of the targets (devs can use any name for anything).
- We did provide a migration for projects using our `@nrwl/angular:webpack-browser` executor. So, any target using it is migrated as expected.
- Unfortunately, we can't prevent the above warnings since they come from a package we don't control. Nx will run any migrations from any packages.

**Comment by leosvelperez** [comment]
I'm closing this one since a migration was provided for the `@nrwl/angular:webpack-browser` executor to cover the warnings mentioned in this issue. No real issue is expected to happen, if you do have a problem, please feel free to reopen this or create a separate issue.
