### ISSUE TITLE
Warning: Fell back to using 'fs' to identify

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#7022]
Hi, following to my comment https://github.com/nrwl/nx/pull/7013#discussion_r709458007: 

## Current Behavior

I work on a project with 2 pending changes in Git (not staged): 

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   packages/semver/package.json
        modified:   packages/semver/src/generators/install/index.spec.ts
```

Then I run tests locally before committing and I get: 

```
Warning: Fell back to using 'fs' to identify 7;33mM packages/semver/package.json as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
Warning: Fell back to using 'fs' to identify 7;33mM packages/semver/src/generators/install/index.spec.ts as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.

> nx run semver:test 

 RUNS   semver  packages/semver/src/executors/version/index.e2e.spec.ts
```

@JamesHenry I poke you on this since we recently discussed it. 

## Expected Behavior

Do not warn anything. 

### Environment

```
  Node : 14.16.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.4.3
```

**Comment by JamesHenry** [comment]
Thanks @edbzn, when you are in that state what is the result of running the following command from the root of your Nx workspace:

```sh
git status -s -u -z .
```

Also what is the output of:

```sh
git --version
```

**Comment by edbzn** [comment]
I already committed but it happens again if I modify any other file, so randomly: 

```
> $ git status -s -u -z .
 M packages/semver/src/generators/install/index.spec.ts%
 ```
 
 ```
 > $ git --version
git version 2.25.1
```

**Comment by JamesHenry** [comment]
Thanks @edbzn that's very strange then... The `M` should mean that this isn't picked up as being deleted.

I wonder if somehow it is not the git info that is broken, but the check itself (namely `statSync(join(path, f)).isFile();`) on linux which I see you are using.

Honestly by far the most useful thing you could do next is to go into your node_modules and add some logging into the Nx codebase. I'm sorry to have to ask you to do that but as I say it would be by far the best way to proceed.

Everything relevant is in the file here: `node_modules/@nrwl/workspace/src/core/hasher/git-hasher.js`

You want to find the function `gitStatus()` you will see it calls `parseGitStatus()` in order to produce an array of `filesToHash` and `deletedFiles`.

Once we have done that, we have a `checkForDeletedFiles()` utility which is what is throwing the error you are seeing.

The idea behind it is it is verifying that all of the `filesToHash` are genuinely existing files on disk, which is why that check runs `statSync(join(path, f)).isFile();` within the try catch there in `checkForDeletedFiles`.

Please could you investigate whether that line is maybe throwing for a different reason? 

Again sorry to have to ask you to go through this more low-level process yourself but it would be hugely helpful.

Perhaps the way we are deriving the filename for that call earlier in the `parseGitStatus()` is incorrect somehow: `const filename = chunk.substring(3).replace(new RegExp(`^${prefix}`), '');`

Hope that's useful as a basis for investigation, please let us know if you have any questions and what you find!

**Comment by edbzn** [comment]
> Again sorry to have to ask you to go through this more low-level process yourself but it would be hugely helpful.

No worries, I'm willing to help; that's how OSS works right?

> Please could you investigate whether that line is maybe throwing for a different reason?

If I log what's `parseGitStatus` parse:

```js
function gitStatus(path) {
    const deletedFiles = [];
    const filesToHash = [];
    parseGitStatus(path).forEach((changeType, filename) => {
        console.log({ filename, changeType }); // <- log here
        if (changeType !== 'D') {
          filesToHash.push(filename);
        }
        else {
          deletedFiles.push(filename);
        }
    });
    const updated = checkForDeletedFiles(path, filesToHash, deletedFiles);
    const status = getGitHashForFiles(updated.filesToHash, path);
    return { deletedFiles: updated.deletedFiles, status };
}
```

Then it gets me: 

```
> $ nx test --skip-nx-cache
{
  filename: '7;33mM\x1B[m packages/semver/src/generators/install/index.spec.ts',
  changeType: '\x1B'
}
Warning: Fell back to using 'fs' to identify 7;33mM packages/semver/src/generators/install/index.spec.ts as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
```

Maybe I go wrong, but shouldn't be the `changeType` equal to `M` instead?

**Comment by JamesHenry** [comment]
Ah interesting it seems like ANSI escape codes are ending up in the git command output of the child process.

Please try adding:

```ts
const stripAnsi = require('strip-ansi');
```

To the top of the git-hasher.js file (the strip-ansi package should already be in your node_modules so no need to install)

And then update the line which assigns chunks within `parseGitStatus` to use the stripAnsi package, e.g. :

```ts
var chunks = stripAnsi(output).split('\0');
```

And now see how your logs are affected

**Comment by edbzn** [comment]
Looks way better! No warning anymore. 

```
nx test --skip-nx-cache                                                                                                                          [±main ●]
{
  filename: 'packages/semver/src/generators/install/index.spec.ts',
  changeType: 'M'
}

> nx run semver:test 
```

**Comment by JamesHenry** [comment]
Thanks for confirming, @edbzn, I'll add this as a proper fix for this issue.

**Comment by JamesHenry** [comment]
@edbzn Would you mind doing one more thing for me and passing on the raw value of that `output` variable without the strip-ansi applied?

I would like to add it as a test in the PR

**Comment by edbzn** [comment]
@JamesHenry here is the output: 

```
> $ nx test --skip-nx-cache                                                                                                                      [±main ●]
{
  output: ' \x1B[7;33mM\x1B[m packages/semver/src/generators/install/index.spec.ts\x00'
}
```

**Comment by JamesHenry** [comment]
Thank you!
