### ISSUE TITLE
`create-nx-workspace@latest` no longer adds useful scripts to package.json

### ISSUE THREAD

**Issue by christianacca** [nrwl/nx#7078]
## Current Behavior

`create-nx-workspace@latest` no longer adds useful scripts to package.json, but now only includes:

```json
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
```

## Expected Behavior
That a newly minted workspace for angular include these useful scripts ie:

```json
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "nx": "nx",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx workspace-lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help"
  },
```

## Steps to Reproduce

Create the new workspace as follows:

```bash
npx create-nx-workspace@latest test-workspace --preset=empty --cli=angular --interactive=false --nx-cloud=false
cd ./test-workspace
npm install -D @nrwl/angular
npx ng g @nrwl/angular:application my-app --routing --style scss --prefix app
```

Notice that the package.json only has the scripts:

```json
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
```

### Environment

```bash
  Node : 14.17.4
  OS   : darwin x64
  npm  : 6.14.14
  
  nx : Not Found
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by linbudu599** [comment]
Maybe we can add a option like `--nx-scripts` to control weather verbose nx related scripts should be added to project package.json ? @vsavkin

**Comment by christianacca** [comment]
I'm guessing it was intentional to remove these npm scripts. I get that it makes for a less "intimidating" package.json. However, I think these scripts also have a nice way of documenting the core sets of nx commands, and so in that way helps a lot for someone new / less frequent user

**Comment by vsavkin** [comment]
Hi there,

We did consider having something like `--nx-scripts` but folks would have had to know about the flag (and most new nx users won't know about it). In general, invoking npm scripts is a headache because they require you to pass an extra `--` because you have two sets of flags: 1 for npm, 1 for nx.  I personally think that start/build/test should not be there either. Your scripts section should be empty by default.

The idea is that `nx --help` should be good enough, but I can see how having a set of scripts in the package.json is more tangible. 

One idea I had is to have a script called: "teach-me-nx", which will show you a few common commands and point to a tutorial online. 

I'm going to close this issue because it isn't a bug. We want to teach new folks how to use Nx (your concern is a legitimate one), but I don't think listing all possible commands is the best way to do it.

Thank you!

**Comment by christianacca** [comment]
Indeed the extra -- is gross. Of course you can use yarn for running
scripts but I get that is another install and newbies might just balk at
that.

No problem with closing this issue... I'll "watch this space" for an
alternative that you guys come up with.
