### ISSUE TITLE
remove library should remove the path in tsconfig.base.json

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx#7148]
## Current Behavior
When I remove a library with `@nrwl/workspace:remove`, it doesn't remove the related path from tsconfig.base.json

## Expected Behavior
remove the path in tsconfig.base.json

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by puku0x** [comment]
Because `@nrwl/workspace:remove` relies on `npmScope` in `nx.json` to determine which alias to remove.
https://github.com/nrwl/nx/blob/23d10a9dfc199f322bbc118237155de6b2b385be/packages/workspace/src/generators/remove/lib/update-tsconfig.ts#L24-L29

I guess you have created a library with different scope.
```
# Create a workspace which npmScope is workspace-7148
npx create-nx-workspace workspace-7148

# Create a library with --importPath but with different scope
npx nx g lib --name=foo --buildable --publishable --importPath=@workspace/components
```

You may need to remove the path alias manually in such situation.

**Comment by swuendri** [comment]
I run into the same problem last days but I cannot remove the path alias manually. The deletion and creation of library is automated to "recreate" libraries from OpenAPI specs. I'm wondering if there is an importPath option at creation time of a library but not for deletion? Is it worth to add such an option @puku0x ?

**Comment by swuendri** [comment]
@maxisam, since version 13.10.0 you are able to remove your mentioned libraries. Please check it out.
