### ISSUE TITLE
Setting baseUrl should override devServerTarget for cypress runner

### ISSUE THREAD

**Issue by meeroslav** [nrwl/nx#7169]
## Current Behavior
If you specify your e2e configuration like:
```
{
  "builder": "@nrwl/cypress:cypress",
  "options": {
    "devServerTarget": "my-project:serve",
    "cypressConfig": "./cypress.json",
    "tsConfig": "./tsconfig.json"
  },
  "configurations": {
    "regression": {
      "baseUrl": "https://my.deployed.staging/",
    }
  }
}
```
it will still serve `my-project` on `https://localhost:4200` although cypress tests will only run against `https://my.deployed.staging/`.

To overcome this, one must explicitly reset server target:
```
{
  "builder": "@nrwl/cypress:cypress",
  "options": {
    "devServerTarget": "my-project:serve",
    "cypressConfig": "./cypress.json",
    "tsConfig": "./tsconfig.json"
  },
  "configurations": {
    "regression": {
      "devServerTarget": "",
      "baseUrl": "https://my.deployed.staging/",
    }
  }
}
```

## Expected Behavior
Setting the `baseUrl` should override devServerTarget.

**Comment by barbados-clemens** [comment]
hi @meeroslav,

Just wanted to say what you've posted as a workaround is an expected way to handle overriding since the options and the configuration is merged together and passed on. So setting `devServerTarget` to an empty string is basically unsetting var.

What you can do if you don't want to provide an empty string/unset the var is remove the `devServerTarget` from the base `options`, and make a new configuration for when you want `devServerTarget` to be set. For Example
```json
{
  "builder": "@nrwl/cypress:cypress",
  "options": {
    "cypressConfig": "./cypress.json",
    "tsConfig": "./tsconfig.json"
  },
  "configurations": {
   "dev": {
      "devServerTarget": "my-project:serve",
    },
    "regression": {
      "baseUrl": "https://my.deployed.staging/",
    }
  }
}
```
then you would just target the `dev` configuration like `my-project-e2e:e2e:dev` when you're wanting to use `devServerTarget`

**Comment by meeroslav** [comment]
I will update the documentation to be more transparent about this.
