### ISSUE TITLE
Error in ng add third-party module

### ISSUE THREAD

**Issue by crane168** [nrwl/nx#732]
`bogon:ngzorrotest jingtong1$ **ng add ng-zorro-antd --project=ngzorro**
Installing packages for tooling via npm.
Path "/src/app/app.component.html" does not exist.
`
I am writing, but src/app/app.com ponent. HTML file exists, problems in nx space area, please help me, thank you！

**Comment by FrozenPandaz** [comment]
I understand why you're posting this issue here as it is not an issue with a normal `@angular/cli` workspace and _is_ an issue with **Nx**. However this is really an issue with the module you are trying to use. They probably should refer to the `angular.json` to determine where the `app.component.html` is instead of assuming it is within `/src/app`. There is not much we can do here because having an app in the `/src` directory would not scale with multiple apps.
