### ISSUE TITLE
Error generating project graph in linux

### ISSUE THREAD

**Issue by samuelfernandez** [nrwl/nx#7497]
## Current Behavior

Error when running nx from a GitHub Action

```
Command failed: npx --no-install nx workspace-lint
nx workspace-lint [files..]

Lint workspace or list of files.  Note: To exclude files from this lint rule, you can add them to the ".nxignore" file

Options:
  --help     Show help  [boolean]
  --version  Show version number  [boolean]

Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid NODE_OPTIONS env variable: --use-openssl-ca is not allowed in NODE_OPTIONS
    at new NodeError (internal/errors.js:322:7)
    at new Worker (internal/worker.js:199:13)
    at createWorkerPool (/tmp/renovate/repos/github/ng-easy/platform/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:129:18)
    at buildExplicitDependenciesUsingWorkers (/tmp/renovate/repos/github/ng-easy/platform/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:143:21)
    at /tmp/renovate/repos/github/ng-easy/platform/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:95:20
    at Generator.next (<anonymous>)
    at /tmp/renovate/repos/github/ng-easy/platform/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/tmp/renovate/repos/github/ng-easy/platform/node_modules/tslib/tslib.js:113:16)
    at buildExplicitDependencies (/tmp/renovate/repos/github/ng-easy/platform/node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js:87:20) {
  code: 'ERR_WORKER_INVALID_EXEC_ARGV'
}
```

## Expected Behavior

It works

## Steps to Reproduce

Run in linux, with `NODE_OPTIONs=--use-openssl-ca` and the `CAP_NET_BIND_SERVICE` capability on Node

https://github.com/nodejs/node/issues/31131

### Environment

Renovate runner

**Comment by robinpellegrims** [comment]
We observe the exact same issue after upgrading nx from v12.10.0 to v13.1.3 and running `nx affected:build` with the --use-openssl-ca flag set.

**Comment by robinpellegrims** [comment]
Not sure if there has been any progress on this, but this issue is blocking our upgrade to nx v13 so I did some further investigation. 

The error is thrown by the nodejs [Worker constructor](https://github.com/nodejs/node/blob/256fe21045b506a236b79a4ee4d4f440a3d36807/lib/internal/worker.js#L195) which is called [here](https://github.com/nrwl/nx/blob/d58584dcbf6c685b12c52f08420ffb3deb766a31/packages/workspace/src/core/project-graph/build-project-graph.ts#L255) in the `createWorkerPool` function in Nx. Apparantly some validation was added on the env variables that are passed to the Worker constructor, so a solution could be to filter the env variables in Nx (remove `--use-openssl-ca`) before passing them to the Worker constructor. 

If this is an acceptable fix, I could provide a PR with a semi-working test but I'll need some guidance completing the test since testing (or mocking?) the Worker functionality proves to be quite complex and there doesn't seem to be any tests yet in nx testing this particular part of the code.

**Comment by RobM-ADP** [comment]
This seems to still be an issue.

**Comment by RobM-ADP** [comment]
@robinpellegrims - Did you every find a work around for this?

**Comment by robinpellegrims** [comment]
> @robinpellegrims - Did you every find a work around for this?

Yes, eventually we worked around the issue by explicitly specifying the certificate using the env variable `NODE_EXTRA_CA_CERTS=[path-to-crt]` instead of the more general`NODE_OPTIONS=--use-openssl-ca`.

**Comment by fischermatte** [comment]
We get this issue after upgrading to Angular 14.2 with "@angular-eslint/builder" in Version 14.0.3. Seems it uses also some nrwl stuff which leeds to the same issue.

**Comment by robinpellegrims** [comment]
> We get this issue after upgrading to Angular 14.2 with "@angular-eslint/builder" in Version 14.0.3. Seems it uses also some nrwl stuff which leeds to the same issue.
> 
> This issue pops up in our pipeline's docker image where `ENV NODE_OPTIONS --use-openssl-ca` is being set.
> 
> @robinpellegrims Could you explain your workaround a bit? How to know the correct path for NODE_EXTRA_CA_CERTS?

In our case the certificates could be found in /usr/local/share/ca-certificates, but I suppose it depends on the OS that is used.

**Comment by matf** [comment]
Replacing `--use-openssl-ca` with the a PEM-File containing the necessary certificates worked for us:

```Dockerfile
RUN mkdir /usr/local/share/pem-bundle && \
    cat /usr/local/share/ca-certificates/*.crt > /usr/local/share/pem-bundle/bundle.pem

ENV NODE_EXTRA_CA_CERTS /usr/local/share/pem-bundle/bundle.pem
```
