### ISSUE TITLE
ngrx entity?

### ISSUE THREAD

**Issue by deanmiller** [nrwl/nx#75]
Hello,

I am evaluating Nx for use in our company. Will the Nx be incorporating ngrx/entity for the creation of ngrx boilerplate?

Thanks

**Comment by vsavkin** [comment]
Yup. I've been watching Entitiy for a few months now, and it looks very good. I just need a bit more practice using it before I bake a particular way of doing it into nx.

**Comment by deanmiller** [comment]
Thanks

**Comment by ankemp** [comment]
@vsavkin - I was thinking of taking this on, as I'd really like to be able to use ngrx/entity.

Would we add a flag to the `ng g ngrx [name]` command? Maybe `--entity`?
Since the file generation will be nearly the same, with the exception of the `reducers` & `reducers.spec` files would you just wrap the file in an if statement or is there another way to choose which file(s) to use during generation?

**Comment by mtabaj** [comment]
Hi Viktor, 
Do you think will have Entity anytime soon?

**Comment by vsavkin** [comment]
@ThomasBurleson since you have been working on refactoring the NgRx support, do you have any thoughts on how to use entity?

**Comment by ernie58** [comment]
Hi, any news on this feature? Would really be awesome

**Comment by rajesh-rajendran-ascendlearning-com** [comment]
I would like to know when this would be incorporated in Nx . It certainly would make the boilerplate more simpler I believe.

**Comment by vsavkin** [comment]
@TekSiDoT if you send a PR, I'll review it and merge it.

**Comment by TekSiDoT** [comment]
@vsavkin you mentioned you might have a preference for a particular way of using it, have you decided on that yet?

**Comment by brandonroberts** [comment]
Support for `@ngrx/entity` as part of the ngrx schematic was added in Nx 8.3. Use the `--syntax=creators` option
