### ISSUE TITLE
eslint not catching template errors

### ISSUE THREAD

**Issue by DrakeAnglin** [nrwl/nx#7545]
I have several angular application in a nrwl monorepo. When running eslint on any app in the repo, template errors are not showing. I can not find any documentation on this anywhere. 

## Current Behavior

All tests pass even if there is a error in a error in a template. 

## Expected Behavior

I would expect that the linter fails with a error

## Steps to Reproduce

by adding `{{ should.error }}` in any .html file or in a inline-template

![image](https://user-images.githubusercontent.com/37958526/139148972-cd67f35b-b6d6-4bb3-85c9-a8502d5eeda4.png)

![image](https://user-images.githubusercontent.com/37958526/139149009-8e883779-79cb-48e8-a00e-76e07af3cc6e.png)

### Environment

![image](https://user-images.githubusercontent.com/37958526/139148826-c039f612-5e6b-44f0-b72a-3370f69af07e.png)

**Comment by leosvelperez** [comment]
Hey @DrakeAnglin!

In the above screenshot, you have version mismatches between the different `@nrwl/*` packages, the most important one being the `@nrwl/angular` package which is on a different major version than the rest. You should have all nrwl packages in the same version.

Please note that is not recommended to just bump the version of the packages because you won't get the automatic migrations. You can try running `nx migrate @nrwl/angular@12.3.6` to have it on the same version as other packages. You can run a similar command for the rest of the packages that are not in that version.

If bringing all the nrwl packages to the same version doesn't solve your issue. Could you please share a minimal repo where this issue can be reproduced?
