### ISSUE TITLE
Shared cache's nxdeps.json is overwritten by subsequent builds

### ISSUE THREAD

**Issue by NotSoImportant** [nrwl/nx#7593]
This is a follow up of #7473 
In my setup I have
- (a local checkout of the repo with a local nx cache - _not relevant for this issue I guess_)
- different build machines that **share the same nx cache** via a shared drive (not nx cloud)

## Current Behavior
I have different builds running on different branches. Some have nx 12 (cache version 3.0), some nx 13 (cache version 5.0).
- When I delete the nxdeps.json the nx 13 build runs fine (and recreates the nxdeps.json with version 5.0)
- When then a build with nx 12 runs, it replaces / updates the nxdeps.json file with version 3.0 again.
    **This is wrong in my opinion**
- Now nx 13 builds will fail with "Invalid source or target versions. Source: 3.0, Target: 5.0" (see #7473)
    (even when using `--skip-nx-cache`, which is also confusing)

## Expected Behavior
1. Older versions should not overwrite the version / structure of the nxdeps.json / the cache
2. The cache should be downwards compatible

## Work around
Currently as a work around I am using a different cache path per cache version, so that they would not interfer which each other

## Steps to Reproduce
see above
https://github.com/nrwl/nx-examples uses nx cloud, so I cannot show it there

### Environment
nx report of a build machine:

>  NX  Report complete - copy this into the issue template

  Node : 12.14.0
  OS   : linux x64
  npm  : 6.13.4
  
  nx : Not Found
  @nrwl/angular : 13.0.2
  @nrwl/cli : 13.0.2
  @nrwl/cypress : 13.0.2
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : 13.0.2
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.0.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : 13.0.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

(meanwhile 13.1.2)

**Comment by meeroslav** [comment]
Hey @NotSoImportant, thank you for the clarification.

I'll try to address both of your points:
> 1. Older versions should not overwrite the version/structure of the nxdeps.json / the cache

Actually not. Nx v12 does not know how to handle project graph structure changes at v13 and would end up in a broken state. If version 12 would retrieve the v5 cache, all your external dependencies would be missing, as these were split from the project nodes.

> 2. The cache should be downwards compatible

The cache is downwards compatible for one version - there is a [backward adapter](https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/project-graph/project-graph.ts#L108-L125) that maps v5 to v4 for all the plugins that didn't migrate. Unfortunately, project cache v3 was already deprecated in Nx v12, and support was removed in v13.

The switch from v13 to v12 correctly invalidates the cache and generates a cache with the old structure.
The problem seems to be that when you switch back from v12 to v13, the cache should also be invalidated but that doesn't seem to be the case.

I will investigate this further. Would be super helpful if you can list the commands you run on this machine for every commit/PR so we can reproduce it as closely as possible e.g.:
```
- checkout
- npm install
- nx affected build
```

**Comment by NotSoImportant** [comment]
Hi @meeroslav, thanks for your explanations.

If you say that the cache should invalidate. Does that mean that the nxdeps.json is deleted or the complete cache?
In the first case this could be fine. Second case would mean subsequent builds from different versions would flip flop the cache.

The build is running the following (in jenkins):
```
checkout
- npm ci
- npx json -I -f nx.json -e "this.tasksRunnerOptions.default.options.cacheDirectory=${nxCacheDir}"
- nx run mock-server:build

then in parallel (full build)
    - nx run-many --target=lint --all --format=checkstyle --outputFile=dist/eslint/{project.name}.xml
    - nx affected:build --all --prod --parallel --maxParallel=2 --exclude=mock-server
    - nx run-many --target=test --all  --parallel --maxParallel=2 --code-coverage
    - npm run e2e:ci  # start-server-and-test start:mock-server http-get://localhost:3333 e2e:headless
                      # nx run-many --target=e2e --all --headless --browser chromium

instead PR builds
    - node_modules/.bin/eslint ${files} -f checkstyle -o ${outFile} --no-error-on-unmatched-pattern
    - nx affected --base=origin/${env.BRANCH_NAME} build --with-deps --exclude=mock-server
    - nx affected --base=origin/${env.BRANCH_NAME} test --code-coverage
    - npm run affected:e2e:ci    # start-server-and-test start:mock-server http-get://localhost:3333 affected:e2e:headless
                                 # nx affected:e2e --base=origin/$BRANCH_NAME --headless --browser chromium
```

**Comment by NotSoImportant** [comment]
Hi, do you have new thoughts on this?

**Comment by meeroslav** [comment]
Hi @NotSoImportant,

Cache depends on several factors - files (including package/yarn/pnpm lock files) and target. We do not remove the cache in between the runs. The `nxdeps.json` from the cache folder should be changed/removed every time the project graph changes and/or graph version changes (by using a different nx version).

 I'm looking now into whether the `nxdeps.json` is properly reset.

**Comment by NotSoImportant** [comment]
Thank you. Sounds better than if all was deleted. However it still means 2 build with different version cannot run in parallel (because they would flip-flop the nxdeps.json all the time). Does it? Or at which point of time of the build is the nxdeps.json needed?

**Comment by meeroslav** [comment]
Yes, that's correct. 

The cache folder is usually located in the `node_modules/.cache/nx`. Each new CI event (commit) would trigger a new checkout so since the codebase changes it's expected that `nxdeps.json` gets reset as well. The caches themselves stay intact and can be used if matched.

The `nxdeps.json` is used in multiple targets including lint, build, test, affected, etc., and can be used multiple times in those.

So no, running two targets with different Nx versions pointing to the same cache folder does not make sense and would lead to a race condition where one target would be served an invalid graph. Note that it's not only the structure of the graph that would be different - different branches could have additional projects or different imports.

**Comment by NotSoImportant** [comment]
Ok, think I understood.
Now how will/can the cache stay intact but nxdeps.json being recalculated/reset?
They both are in the same location (where `tasksRunnerOptions.default.options.cacheDirectory` points to).
Or is really every checkout supposed to work on a new cache? (not sure what would be meant by "stay intact" then)

I think the opposite is actually a strength of the nx cache: with a global cache: when out of 200 only 1 project was changed, I do not need to rebuild all. Instead even when builing with "--all" will recieve all inaffected from the cache. 
(I know that "affected" would only build the affected, but also
1. I would still need to rebuild all dependencies
2. In my setup I always want to output a big bundle with all apps included - without having to rebuild all
) 

Different imports or projects would produce a different hash and therefore force a rebuild anyhow, which is fine. I'm just afraid now of that this would also flip-flop a shared nxdeps.json. 

So the big question that comes out of all of this: how can I share project output that did not change (and also their deps not) between several builds without screwing up the nxdeps.json.

**Comment by NotSoImportant** [comment]
My current solution is to have the nxdeps.json beeing a symlink pointing to a non-existing location inside of the build container, so that all PRs can use the cache, but every PR will create its own nxdeps.json and so no conflicts will arise.

**Comment by minijus** [comment]
Hi, @NotSoImportant 

Question, not directly related to the issue: What kind of storage you are using to mount cache dir to many parallel builds? We have tried nfs (ReadWriteMany) before and it was too unstable, had to rollback to no shared local cache on CI.

**Comment by meeroslav** [comment]
> So the big question that comes out of all of this: how can I share project output that did not change (and also their deps not) between several builds without screwing up the nxdeps.json.

The remote (Nx Cloud) cache takes care of the artifacts caching. If nxdeps.json was modified, there was a reason for it and you should not fight it.

In order not to have cached local nx cache, you can do one of the following:
- Make sure you remove `.cache` folder from the dependencies cache
- Set nx cache to be stored somewhere outside of the repo (as you did) with `NX_CACHE_DIRECTORY` environment variable

```yaml
- name: Run e2e tests
  run: yarn nx run-many --target=e2e --parallel=1
  env:
    NX_CACHE_DIRECTORY: /tmp/nx-cache
```
