### ISSUE TITLE
Do not force `tsconfig.base.json`

### ISSUE THREAD

**Issue by desfero** [nrwl/nx#7598]
## Description

Right now `nx` forces to create `tsconfig.base.json` which would be not used by our app at all.

## Motivation

Will not force coupling packages with the monorepo setup in any way. Let the project decide the approach to code sharing (either from the monorepo root or from separate package)

**Comment by christianallred** [comment]
`tsconfig.base.json` Is how `nx` reasons about packages inside of the nrwl system, if it doesn't exist then why are you using `nx`? if you don't want to extend the tsconfig.base from a specific project you can remove it very easily by removing the extends parameter from that project that references the tsconfig.base

**Comment by desfero** [comment]
@christianallred i'm new to NX and don't see a lot of docs around `tsconfig.base.json` setup.

Can you please provide some use cases where `tsconfig.base.json` is useful for NX setup on top of `npm/yarn workspaces`? 
Right now our `tsconfig.base.json` is completely empty and everything is working alright.

**Comment by AgentEnder** [comment]
How do the packages from inside your monorepo reference each other @desfero? Generally `nx` workspaces use the paths defined in tsconfig for this (and our lint plugins will complain if you use relative paths) to locate which projects reference each other when building up the dep-graph.

**Comment by christianallred** [comment]
@desfero the documentation is all there. This is a question not an issue, and a better place for ask these questions is the slack community. 

Here is an explanation of what is generated in a base NRWL [repo](https://nx.dev/l/n/getting-started/nx-core#creating-a-new-workspace)

Nx internally uses the `tsconfig.base` and specifically the path object to do tooling, and also its how it makes it easy to import libraries into different applications or libraries inside of the nrwl repo, I would suggest you read up more on the monorepo pattern as it has a lot more to do with this than nrwls implementation of it. 

regardless here is an obviscarted example of a project i have in nrwl 

```
"paths": {
      "@mynrwl/lib2": ["libs/lib2/src/index.ts"],
      "@mynrwl/services": ["libs/services/src/index.ts"],
      "@mynrwl/anotherlib": ["libs/anotherlib/src/index.ts"],
      "@mynrwl/components": ["libs/components/src/index.ts"],
      "@mynrwl/utils": ["libs/utils/src/index.ts"]
    }
```

This allows you too easily import into an application build in nrwl like this `import {something} from @mynrwl/utils` instead of having to do crazy relative paths, or really long absolute paths. 

I can't speak to all of the locations where tsconfig.base.json is being used inside of the nx tooling, but i do know that it is currently used. 

To enders point... how do you import things in your repo now? also please explain what you mean by "everything is working alright" because basic builds, and basic things will always work. at its core its just javascript, but if you wish to use any of the tooling provided by nrwl. trying to get away from a core configuration is a bad idea. what is your use case for removing the `tsconfig.base`? its there to try to standardize your repo among other things.

**Comment by desfero** [comment]
> This allows you too easily import into an application build in nrwl like this import {something} from @mynrwl/utils instead of having to do crazy relative paths, or really long absolute paths.

We use `npm workspaces` so all packages are linked into `node_modules` where node modules resolutions mechanism comes into play and resolves properly `import {something} from @mynrwl/utils`

**Comment by christianallred** [comment]
So i guess my core question would be, why are you trying to use NRWL if you already have a mono repo set up via `npm workspaces`. 

NRWL is first and formost a mono-repo management tool, and it has specific tooling around how things are coupled. 

> ## Motivation
> Will not force coupling packages with the monorepo setup in any way. Let the project decide the approach to code sharing (either from the monorepo root or from separate package)

I think this ask is rather non-sensical if you don't plan on using nrwl for its dependency management. 

What is your use case for NRWL what are you trying to use it for? I think this might help us look in a better direction for this issue.

**Comment by AgentEnder** [comment]
@christianallred Nx does much more than just the dependency management, and it should be compatible with a yarn / npm / pnpm workspaces setup (I believe we have some docs on this). Using Nx still gives caching capabilities, task orchestration, Nx cloud and so on.

@desfero A completely empty tsconfig seems like a good workaround for now, but I don't see any reason why we should have to force the tsconfig.base.json file to exist (aside from having to check for it before reading it each time). I think we have enough info to consider moving forward with this, going to remove the blocked label.

**Comment by desfero** [comment]
thank you @AgentEnder.

@christianallred our use for NX was exactly what @AgentEnder is pointing towards: caching/orchastrations/nx cloud/dependency graphs. We try to have a clear separation between dependency management (npm worksaces) and build/test pipeline (NX with all it's awesome tooling)

@AgentEnder i do completely agree that empty `tsconfig.base.json` is a good workaround and it's not even that big deal. 
From my side i just wanted to raise a point that not all monorepo setups use TS references/aliases and having empty file would always rise some questions from new devs that are joining the project.
