### ISSUE TITLE
Hasher generates hash based on absolute path instead of relative to workspace root

### ISSUE THREAD

**Issue by mhelm306** [nrwl/nx#7692]
## Current Behavior
if an nx workspace is using a cacheDirectory outside the node modules folder, another instance of the same workspace in a different folder will generate a different hash for the cached outputs, rendering cached outputs from one workspace unusable by the other. This also means that developers can't leverage a cacheDirectory on a shared location if their local workspaces don't have the exact same file paths.

## Expected Behavior
I would expect the workspace to be able to use cached outputs for unchanged projects that are the same relative to the workspace root.

## Steps to Reproduce
1. Clone an nx repo with a cacheDirectory set up outside the repo (e.g. C:/nx/.cache) [Link to repro PR](https://github.com/nrwl/nx-examples/pull/174)
2.  run `nx test products --runner=local-shared` in the command line (to populate new cacheDirectory)
3. Clone the same repo to a new directory/folder
4.  run `nx test products --runner=local-shared` in the command line
5. Check the C:/nx/.cache folder and you can see the different hashes generated (12 total instead of the expected 6)

### Failure Logs
![image](https://user-images.githubusercontent.com/38252136/141168228-68b36cf3-7539-4d40-b6a2-b04e4611b8b8.png)

### Environment
we have a CI/CD process that runs feature branches through a test, lint and build process.  This build pipeline copies the repo into a new  folder for each feature build branch, and we have a shared cache file location to leverage the caching features for building with-deps on affected apps. However, each new build branch doesn't seem to leverage the existing cached outputs for non affected dependent libraries. Our workspace is currently ~200 projects and growing, and this have caused build times on feature branches to balloon to over 90min for an initial build.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I wasn't able to reproduce it. I used your fork of nx-examples with the changes and followed the provided steps. I also tried on a Windows machine just in case it was an OS-related issue.

Please note cache can ve invalidated by changes in source files (including dependencies), npm package versions, implicit dependencies, runtime arguments, and the command being run. Different workspace root folders should be a non-factor. We use paths relative to the workspace root.

Could you have a look again and see what else could be causing the issue and maybe update the reproduction steps? Otherwise, it would be hard for us to troubleshoot.
