### ISSUE TITLE
Upgrading NX 12 to 13 broke "nx run many" with "--only-failed" 

### ISSUE THREAD

**Issue by svzi** [nrwl/nx#7847]
## Current Behavior
After upgrading from NX 12 to 13 the command `nx run-many --all --target=lint --only-failed` will result in this error:
```bash
TypeError: Cannot read properties of null (reading 'getResult')
    at /Users/svzi/development/xyz/apps/node_modules/@nrwl/workspace/src/command-line/run-many.js:47:105
    at Array.filter (<anonymous>)
    at applyOnlyFailed (/Users/svzi/development/xyz/apps/node_modules/@nrwl/workspace/src/command-line/run-many.js:47:47)
    at Object.<anonymous> (/Users/svzi/development/xyz/apps/node_modules/@nrwl/workspace/src/command-line/run-many.js:22:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/svzi/development/xyz/apps/node_modules/tslib/tslib.js:114:62)
```

This is the corresponding function:

```js
function applyOnlyFailed(projectsNotExcluded, nxArgs, env) {
    return Object.values(projectsNotExcluded).filter((n) => !nxArgs.onlyFailed || !env.workspaceResults.getResult(n.name));
}
```

For whatever reason `env.workspaceResults` is null (we've debugged it).

## Expected Behavior
It should run as expected. When we remove the `--only-failed` parameter everything works as expected. But we have multiple apps and several libs in our project, so we really like that parameter.

## Steps to Reproduce
We upgraded an existing NX 12 workspace with Angular 12 to NX 13 / Angular 13. That's all. We run the migration commands as we're supposed to do. Everything else is looking good so far, just the issue mentioned above. 

### Environment
```bash
  Node : 16.11.1
  OS   : darwin arm64
  npm  : 8.0.0

  nx : 13.3.0-beta.2
  @nrwl/angular : 13.3.0-beta.2
  @nrwl/cli : 13.3.0-beta.2
  @nrwl/cypress : 13.3.0-beta.2
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.3.0-beta.2
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0-beta.2
  @nrwl/linter : 13.3.0-beta.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.0-beta.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0-beta.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0-beta.2
  @nrwl/storybook : 13.3.0-beta.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.0.2
  	 @angular/common: 13.0.2
  	 @angular/compiler: 13.0.2
  	 @angular/core: 13.0.2
  	 @angular/forms: 13.0.2
  	 @angular/google-maps: 13.0.2
  	 @angular/platform-browser: 13.0.2
  	 @angular/platform-browser-dynamic: 13.0.2
  	 @angular/router: 13.0.2
  	 @angular/service-worker: 13.0.2
  	 @ionic/angular: 5.9.1
  	 @angular-devkit/architect: 0.1300.3
  	 @angular-devkit/build-angular: 13.0.3
  	 @angular-eslint/builder: 13.0.1
  	 @angular/compiler-cli: 13.0.2
  	 @angular/language-service: 13.0.2
  	 @angular/localize: 13.0.2
  	 @storybook/angular: 6.4.0-rc.3
```

Any help would be really much appreciated!

Best,
Sven

**Comment by gkamperis** [comment]
having the same issue... 

looks like this commit introduced this bug

https://github.com/nrwl/nx/commit/e3c7b979b252661ee648672b705db2e71f8e000b

can someone pls check as the functionality is really important especially in cases of flaky envs

**Comment by gkamperis** [comment]
Hi @vsavkin 

looking at the above PR again... is the intention that --only-failed is to be removed as supported functionality?

Thanks

**Comment by alfaproject** [comment]
I have the same issue. I thought I had a weird repository configuration but after comparing with a fresh nx installation it doesn't seem the case.

This is a bit annoying and breaking. Any feedback, please?

**Comment by p-v-d-Veeken** [comment]
Would appreciate an update about this as well!

**Comment by gkamperis** [comment]
hello @AgentEnder @vsavkin any info on this? 
it is preventing our move to ng 13

**Comment by gkamperis** [comment]
Hello @FrozenPandaz can you maybe help as you are usually involved in the core features...?

**Comment by mlebarron** [comment]
It's not just broken on run-many, it seems broken everywhere. I use this all the time and this is incredibly annoying. 

it worked for me on Nx 13.1 but now fails. only difference in the codebase in below runs is one of them has migrated to updated Nx, the other hasn't.

working:
`nx affected:lint` then `nx affected:lint --only-failed`
```
  Node : 14.18.2
  OS   : darwin x64
  yarn : 1.22.15
  
  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : 13.3.6
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.3.6
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

fails:
`nx affected:lint` then `nx affected:lint --only-failed`
```
TypeError: Cannot read property 'getResult' of null
    at /dir/node_modules/@nrwl/workspace/src/command-line/affected.js:110:105
```

```
   
  Node : 14.18.2
  OS   : darwin x64
  yarn : 1.22.15
  
  nx : 13.4.3
  @nrwl/angular : 13.4.3
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : 13.4.3
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.3
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 13.4.3
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular-architects/module-federation: 12.5.3
         @angular/animations: 13.1.1
         @angular/cdk: 13.1.1
         @angular/common: 13.1.1
         @angular/compiler: 13.1.1
         @angular/core: 13.1.1
         @angular/forms: 13.1.1
         @angular/material: 13.1.1
         @angular/platform-browser: 13.1.1
         @angular/platform-browser-dynamic: 13.1.1
         @angular/router: 13.1.1
         ngx-pendo: 1.7.1
         @angular-devkit/build-angular: 13.1.2
         @angular/cli: 13.1.2
         @angular/compiler-cli: 13.1.1
         @angular/language-service: 13.1.1
         @angular/localize: 13.1.1
         @storybook/angular: 6.4.9
         @twittwer/compodoc: 1.6.6
         nx-stylelint: 13.1.0
```

**Comment by gkamperis** [comment]
anyone from Nrwl looking at his at all?

**Comment by AgentEnder** [comment]
At a glance in the original ticket the @nrwl/* packages are out of order. I'm not really able to dig deep into it right now, but try making sure those are all the same, cleaning out node_modules and reinstalling and see if it still occurs. 

If so, @FrozenPandaz may be able to take a look.

**Comment by gkamperis** [comment]
@AgentEnder 

The fix for the NPE is easy and I tried it locally and seems to work. 

https://github.com/nrwl/nx/blob/dcf835fb9e7616936a934adeae09224dee3eae73/packages/workspace/src/command-line/run-many.ts#L77

change to 

`
(n) => !nxArgs.onlyFailed || !env.workspaceResults?.getResult(n.name)
`

However, the rest of the changes on the PR show removal of `--only-failed` functionality and tests across the board...

**Comment by jbjhjm** [comment]
@gkamperis confirming the behavior that you explained. WTF, why are useful features being removed :O

**Comment by gkamperis** [comment]
@vsavkin any input on this would really help...

**Comment by alfaproject** [comment]
I've just updated to nx 13.5 and this is still broken. How can a regression can not be tackled for months?
```
% yarn affected:lint --only-failed
yarn run v1.22.17
$ nx affected:lint --only-failed

 >  NX   Affected criteria defaulted to --base=master --head=HEAD

nx affected:lint

Lint projects affected by changes

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
  --base  Base of the current branch (usually main)                                                                                                                                                                                                 [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually main)                                                                                                                                                                                                 [string]
  --head  Latest commit of the current branch (usually HEAD)                                                                                                                                                                                        [string]

or using:
  --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas                                                                                                        [array]
  --uncommitted  Uncommitted changes                                                                                                                                                                                                               [boolean]
  --untracked    Untracked changes                                                                                                                                                                                                                 [boolean]

Options:
  --help           Show help                                                                                                                                                                                                                       [boolean]
  --version        Show version number                                                                                                                                                                                                             [boolean]
  --parallel       Max number of parallel processes [default is 3]                                                                                                                                                                                  [string]
  --all            All projects                                                                                                                                                                                                                    [boolean]
  --exclude        Exclude certain projects from being processed                                                                                                                                                                       [array] [default: []]
  --runner         This is the name of the tasks runner configured in nx.json                                                                                                                                                                       [string]
  --skip-nx-cache  Rerun the tasks even when the results are available in the cache                                                                                                                                               [boolean] [default: false]
  --configuration  This is the configuration to use when performing tasks on projects                                                                                                                                                               [string]
  --only-failed    Isolate projects which previously failed                                                                                                                                                                       [boolean] [default: false]
  --verbose        Print additional error stack trace on failure

Examples:
  affected:lint --parallel=5                     Run lint in parallel
  affected:lint --all                            Run the lint target for all projects
  affected:lint --files=libs/mylib/src/index.ts  Run lint for all the projects affected by changing the index.ts file
  affected:lint --base=main --head=HEAD          Run lint for all the projects affected by the changes between main and HEAD (e.g., PR)
  affected:lint --base=main~1 --head=main        Run lint for all the projects affected by the last commit on main

Find more information and examples at https://nx.dev/cli/affected-lint

TypeError: Cannot read property 'getResult' of null
    at /Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/@nrwl/workspace/src/command-line/affected.js:110:105
    at Array.filter (<anonymous>)
    at applyOnlyFailed (/Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/@nrwl/workspace/src/command-line/affected.js:110:47)
    at Object.<anonymous> (/Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/@nrwl/workspace/src/command-line/affected.js:28:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Not only that, the summary of failed projects after an `nx affected:lint` is finished is not shown anymore. I was happy with the non pretty terminal when it was actually working. Now it's prettier but it's getting less useful by the day <.<

**Comment by gkamperis** [comment]
@vsavkin @FrozenPandaz @AgentEnder it has been 2 months since the issue was opened... 

would be good to get some insight on what the plan is, why the change was made and what the proposed workaround would be if it is intended to be removed

pls help!

**Comment by vsavkin** [comment]
Really sorry for the late reply folks. This is all the context:

--only-failed has caused a lot of issues because it was the only stateful part about Nx (things that we had to mutate in place between runs), so it caused bugs and special cases. But we didn't remove it cause it was hard but because it no longer made sense.

We introduced it early on before computation caching was implemented, task dependencies were implemented etc. When we introduced --only-failed most of the task graphs Nx worked with were flat (e.g., every task was independent). A lot of projects right now aren't flat: tasks can depend on other tasks.

When we examined the current situation a few months ago, we saw that `--only-failed` doesn't solve the problem holistically. If you are running, say `nx build myapp`, and that app depends on 1000 buildable libs, it's the caching that enables the min amount of recompute. `--only-failed` would still rerun `myapp` (same stuff about e2e tests depending on builds etc.) 

`--only-failed` in this case doesn't make much sense. What failed isn't the app, but something that the app depends on. If you run `nx build myapp` again, it will not rebuild the libs that were built successfully the first time. It will only rerun the ones that failed.

In other words, running the same command second time only reruns what failed (or skipped) the first time--the rest is retrieved from cache (or left as is if the right files are already in the right place). So in practice any command right now sort of runs with `--only-failed`.

The problem we had is that you would see too much noise in the terminal output--everything cached will still be printed out (at the top). The tasks that are being rerun would be printed last. We knew it's not ideal, and at the time we were already working on the new terminal output strategy we launched a week ago. With the new terminal output strategy,  rerunning something twice doesn't generate any noise in the terminal output.

It took us a bit longer to land the new terminal output strategy that we hoped for, and we had to remove --only-failed before that (cause of how we manage the life cycle). I apologize for that. I know it wasn't ideal.

Also, I added a warning saying that `--only-failed` is going to be skipped, but I made a mistake, and the exception was thrown before we could print the warning. I apologize for this as well.


Summary:

1. With caching and the new terminal output, rerunning any command essentially has `--only-failed`, and it works for non-flat graphs. I know it's not apple-to-apples and that it is possible to come up with some scenario where the previous DX was better. But the prev behavior only worked for flat graphs and was costly to maintain. You could always copy the project names and run them separately as a workaround, but we rarely would have to do that cause caching will do its job.

2. Jason is going to submit a PR to surface the warning properly.

Hopefully it makes sense. Thank you!

**Comment by gkamperis** [comment]
@vsavkin thanks for the detailed explanation but what about the simple scenario where I do not have cache enabled? what do I do then?

can we just simply use the fix identified above? it seems to work as expected if we avoid the NPE

**Comment by vsavkin** [comment]
@gkamperis most operations should be cached. 

Some exceptions where operations aren't cached:
1. Tasks that cannot complete (e.g., serve). --only-failed would not make sense this case.
2. Tasks that create global side effects (e.g, publish to npm). --only-failed should not be used for this as well.
3. Tasks that depend on external services (e.g, some e2e tests). --only-failed could be useful here, but those tasks are usually slow etc so most folks just rerun one task at a time. 

Does you task fall into one of the categories above?

**Comment by gkamperis** [comment]
@vsavkin tbh we do have the cache enabled... 

the main usage of --only-failed is for test targets in CI where we have browser disconnections or maybe flaky tests that intermittently fail because of mutations :( 

retrying only the failed saves us a lot of time in this case, but since you say with the newest version we get the same behavior with cache enabled then I guess we have a type of replacement for the flag.

If I recall correctly I read in the docs in the past that --only-failed and cached is not the same.
It would be good to update the docs and stress the importance of the cache for this "retry/only-failed" scenario.

Also one clarification pls... is this new better logging applicable for the CI logs too or will every retry dump cached logs for 100s of libs?

**Comment by FrozenPandaz** [comment]
`--only-failed` did help for flaky tests but it's kind of a sledgehammer solution as it would rerun the whole test suite.

I think ideally, the test runner would have a mechanism for this. For example, `jest` has [`jest-retries`](https://github.com/bluzi/jest-retries) and Cypress has it [built in](https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries).

This is a good way to avoid dumping cached logs of 100s of libs as well because it's part of what it means to test a single lib.

Does that make sense?

**Comment by gkamperis** [comment]
@FrozenPandaz unfortunately this does not help as browser disconnects happen on karma (jest has no browser). Does Karma have a similar setting?

The sledgehammer designation is a bit subjective I feel as --only-failed would run 2-3 projects dumping only their logs. Comparing against the run of the full set it is still much preferable.

By your reply I deduce that a retry based on the cache will dumb all the cached logs in CI for every retry and the "clean" behavior described above is only on the terminal. Is that correct? if so this will be unpleasant...

**Comment by kylecordes** [comment]
@vsavkin  Would you consider moving Nx closer to the old UNIX tradition that commands are silent unless something goes wrong? Moving a bit in that direction could help a lot with the excessive console output.

**Comment by svzi** [comment]
@vsavkin Thank you for the detailed answer!
