### ISSUE TITLE
Nest + Angular Template: Consider a Backend IS NOT an API.

### ISSUE THREAD

**Issue by morgan-wild** [nrwl/nx#7960]
When you create a new workspace including a NestJS backend and an Angular frontend, the backend it is automatically named "Api".

An API is an interface, not an app. I kwnow this bad designation is widely used, but it is not a reason ^^.
Using this name, you will be find a file named "api-interface" for example. But wait, what the I of API already means?

Fortunally, if you create a workspace asking only a Nest app, you can name it correctly!

Thank you for your job 🥰

**Comment by nartc** [comment]
@morgan-wild Hi, thank you for voicing your opinions. I do share the same view. How can we make it better? Any action item/suggestion that you can think of?

**Comment by twittwer** [comment]
Maybe use `server` or `backend` as default name for the generated nest app and put the `Message` interface in a `shared-interfaces` lib as `message(.interface).ts`

**Comment by morgan-wild** [comment]
Hi everyone and thanks for your fast replies.

I think the best way to do is to ask a name for the NestJs app with 'backend' as default choice.

**Comment by nartc** [comment]
@morgan-wild Sorry for the delayed response. I thought about this some more and I think there are two approaches we can take:
1. Modify `create-nx-workspace` to ask for NestJS app name IF `--preset=angular-nest` is selected
2. Provide a guide (as text) that the consumers can follow to rename the NestJS app and the `api-interfaces` library. (I already thought about making this "guide" as a custom generator but again, I feel like the gain is not justified enough)

As a consumer, option 1 is probably the best because it is intuitive. However, adding an option to the schema, especially JUST FOR ONE preset, to `create-nx-workspace` is quite a change for such little gain. I am hesitant to implement option 1. This is my own opinion and I haven't discussed it with the team yet. Please voice your opinions if you feel strongly about this.

Option 2 seems to be the least disruptive and less involved. It can be two commands:

```shell
npx nx g @nrwl/workspace:move --project api --destination <your-backend-name>
npx nx g @nrwl/workspace:move --project api-interfaces --destination <your-library-name>
```

I can also argue that it's best to select `--preset=angular` then generate a NestJS application afterward. This provides the necessary customizations for the consumers without having to maintain extra code in Nx for such little DX gain. Thoughts? cc @AgentEnder

**Comment by morgan-wild** [comment]
Thank you for your reply.

I finally decided to use the 'apps' preset and to add each app (and libs), one by one after.
That allows to name them like I want and to create  more than one backend.

However, excepted some details, the others presets are useful for learning ;)

Thank you for all.
