### ISSUE TITLE
@nrwl/angular:webpack-browser is slow in CI

### ISSUE THREAD

**Issue by artaommahe** [nrwl/nx#7971]
## Current Behavior

Using `@nrwl/angular:webpack-browser` in CI for building mfe apps is slow due to non-disabling `node_modules/.cache/nx/nxdeps.json` generation on build command startup (of 24Mb size for our repo). It's not required for regular builds and for our monorepo takes 3 minutes to start to build app.  
Also reproduced on local machine after deleting nxdeps cache folder and running build for any project that uses nx' angular builder.

## Expected Behavior

`@nrwl/angular:webpack-browser` should now generate nxdeps if it's not used

## Steps to Reproduce

nx-examples is too small to see the difference

To make sure that builder depends on this cache you can do this for nx-examples repo
- rm node_modules/.cache
- yarn nx build products
- ls node_modules/.cache/nx/
- see `nxdeps.json`

### Environment

```
  Node : 16.13.0
  OS   : darwin arm64
  yarn : 2.4.2
  
  nx : Not Found
  @nrwl/angular : 12.6.0
  @nrwl/cli : 12.6.0
  @nrwl/cypress : 12.6.0
  @nrwl/devkit : 12.6.0
  @nrwl/eslint-plugin-nx : 12.6.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.0
  @nrwl/linter : 12.6.0
  @nrwl/nest : 12.6.0
  @nrwl/next : Not Found
  @nrwl/node : 12.6.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.0
  @nrwl/storybook : 12.6.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.4
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you please expand why do you think `nxdeps.json` is not required?

Nx creates a dependency graph of the workspace in order to properly analyze and schedule the tasks to run. The `nx-deps.json` file is a cache of this project graph and it's used to avoid re-computing the whole graph for subsequent command executions. Most likely, the time spent before building the app is actually computing the project graph, writing the `nxdeps.json` file shouldn't take too long. You can output more performance logs when running a command by setting the `NX_PERF_LOGGING=true` environment variable.

This is not a `@nrwl/angular:webpack-browser` specific behavior, the project graph will be computed for every command run and the cached `nxdeps.json` allows to not re-compute it every single time, allowing for incremental computation of the project graph based on the changes.

In CI, you don't benefit from the incremental computation of the project graph because you don't make changes to the code, but you do take advantage of the cached project graph if you run multiple commands in your pipeline. Without the cached project graph, it will be fully re-computed at the start of each command.

If you still want to disable creating the project graph cache for whatever reasons, please note you can set the `NX_CACHE_PROJECT_GRAPH=false` environment variable.

**Comment by artaommahe** [comment]
@leosvelperez  some questions

1. How nxdeps is used for regular build with nrwl angular builder? Computation caching and buildable libs?
2. How can we cash nxdeps between pipelines? 3+ minutes to each pipeline are too much :( Will it be revalidated and updated e.x. if we re-create it once a week for a main branch and reuse from cache for branches pipelines?

**Comment by leosvelperez** [comment]
@artaommahe see answers below:

1. As explained in the previous comment, Nx uses the project graph to properly schedule tasks to run based on dependencies and target dependencies configuration. It also uses it, as you mentioned, for computation caching and to determine the buildable libs dependencies.
2. It depends on your pipeline setup. The gist of it is that you need to store it somewhere and pull it from there when you want. Please, keep in mind that storing a cached project graph for too long most likely would cause it to be invalidated most of the time due to the changes being made.

**Comment by artaommahe** [comment]
@leosvelperez so the usual CI pipeline with nrwl/nx should always spend N minutes (more for bigger repos) to generate nxdeps for current repo state for following commands proper execution?

**Comment by leosvelperez** [comment]
@artaommahe it should only take minutes for bigger repos, but yes, Nx will create the project graph from scratch for the first command run in the same agent. After that first command, any following command executed in the same agent would consume the cached project graph.

As I mentioned previously, you can run your commands with `NX_PERF_LOGGING=true` to output perf logs and see where the time is spent by Nx in that initial preparation work. Based on that, if you think there's an issue or area for improvement, please go ahead and let us know your thoughts.

**Comment by artaommahe** [comment]
@leosvelperez btw `NX_CACHE_PROJECT_GRAPH=false` does not help, still takes a lot of time before `Browser application bundle generation` starts. Looks like it re-creates project graph but just doesn't save it to disk

**Comment by leosvelperez** [comment]
@artaommahe yes, I mentioned that in [this comment](https://github.com/nrwl/nx/issues/7971#issuecomment-988069557). I was trying to explain that creating the project graph is the expensive operation there, not writing the cache file. The `nx-deps.json` file, as I mentioned in previous comments, it's just a file with the cached project graph, writing that file it's just an I/O operation that shouldn't take too long.

**Comment by artaommahe** [comment]
@leosvelperez btw how nx-deps is invalidated and updated by nx? Even having local development requires to update it's graph on new code changes (especially main branch pull). Is this invalidation increment or the whole graph is recreated from scratch?
