### ISSUE TITLE
color option for run-commands executor doesn't work

### ISSUE THREAD

**Issue by lourd** [nrwl/nx#8051]
## Current Behavior

The [`color` option](https://nx.dev/l/a/workspace/run-commands-executor#:~:text=See%20example%20above-,color,-Default%3A%20false) for the run commands executor doesn't have the intended effect.

## Expected Behavior
Terminal output should have colors when it's set to true; I'm assuming this is a regression.

## Steps to Reproduce
1. Create a new workspace
2. Create an application within the workspace, e.g. Next.js
3. In the newly created app, add a target that uses run-commands to execute another target. Set the `color` option to true. For example, `build` calling `build-run`

```json
{
  "root": "apps/my-app",
  "sourceRoot": "apps/my-app",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "nx run my-app:build-run",
        "color": true
      }
    },
    "build-run": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/my-app",
        "outputPath": "dist/apps/my-app"
      },
      "configurations": {
        "production": {}
      }
    },
  }
}
```
4. Call that wrapper command, (e.g. `yarn nx build my-app`). Observe that it doesn't not have colors, where `yarn nx run my-app:build-run` does.

### Environment
```
  Node : 16.8.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : 13.2.4
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.4
  @nrwl/cypress : 13.2.4
  @nrwl/devkit : 13.2.4
  @nrwl/eslint-plugin-nx : 13.2.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.4
  @nrwl/linter : 13.2.4
  @nrwl/nest : undefined
  @nrwl/next : 13.2.4
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.4
  @nrwl/web : 13.2.4
  @nrwl/workspace : 13.2.4
  @nrwl/storybook : 13.2.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
```

**Comment by msabramo** [comment]
I wonder if #8226 lets with this issue?

**Comment by Hotell** [comment]
> I wonder if #8226 helps with this issue?

it does not unfortunately

**Comment by Hotell** [comment]
the situation is even more problematic...

**Let's say we have following setup:**

```js
// @filename echo.js

const chalk = require('chalk');

main();

function main() {
  console.log(chalk.red('hello'));
}
```

Now if we gonna execute that script via `run-commands` executor:

```json
"targets": {
    "echo": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "node echo.js",
        "parallel": false
      }
    },
}
```


`yarn nx run test:echo` -> will emit in terminal 
![image](https://user-images.githubusercontent.com/1223799/154991852-f5d5c6b6-a4a4-4714-ad8d-2b12dc5e5daa.png)


If we enable color explicitly:

```diff
"targets": {
    "echo": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "node echo.js",
        "parallel": false,
+      "color": true
      }
    },
}
```

the output will be the same ( with color ).


If we turn color off:

```diff
"targets": {
    "echo": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "node echo.js",
        "parallel": false,
-      "color": true
+      "color": false
      }
    },
}
```

the output is again, **the same** 🚨 ![image](https://user-images.githubusercontent.com/1223799/154991852-f5d5c6b6-a4a4-4714-ad8d-2b12dc5e5daa.png)


quite confusing indeed. 

### Why is this happening?:

The main "culprit" is here 

1. leveraging forceColor https://github.com/nrwl/nx/blob/master/packages/workspace/src/utilities/output.ts#L31-L35
  - this is being evaluated once on code load, thus any configurations are disabled
 
2. setting forceColor in executor https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L183 
  - updating env https://github.com/nrwl/nx/blob/36245e14af6cc660cae5b073ffe118558729c9d5/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L236-L238 

based on that code setting it is obvious that the `color` option is being accommodated only in CI environment, not on local machine.

**NOTE: it is not set on CI either 🚨** 

following command will simulate that we are on CI (remember `"color":false` is set in executor):
 `CI=true NX_VERBOSE_LOGGING=true yarn nx run test:echo --skip-nx-cache`, but the color will be used no matter what.

💡 Now only way **ho to turn off color** is to explicitly set `FORCE_COLOR=false`

`FORCE_COLOR=false NX_VERBOSE_LOGGING=true yarn nx run test:echo --skip-nx-cache`

↓↓↓↓

![image](https://user-images.githubusercontent.com/1223799/154994743-4912cebe-78d1-49cd-b21d-3d27ecdc5566.png)


**Last thing**

While there is at least some way how to enable/disable color output, it is tightly coupled to `chalk`. This is problematic as not every tool that one uses leverages chalk for coloring, thus this approach will not work.

**invoking typescript example:**


We run into this when we wanted to execute `typescript` via run-command. The problem here is even more problematic, as the executor strips away pretty printed typescript messages


`NX_VERBOSE_LOGGING=true yarn nx run test:type-check --skip-nx-cache`
↓↓↓
![image](https://user-images.githubusercontent.com/1223799/154995950-83fea1f5-fba8-44c9-8363-e90b95d48aa2.png)

`yarn tsc -p libs/test/tsconfig.lib.json`
↓↓↓
![image](https://user-images.githubusercontent.com/1223799/154996062-9b22bcab-9b40-4a69-9b9a-a4d2fd01f5ff.png)


---

 **SUGGESTED ACTION ITEMS:** 
- change the docs to be explicit about what that option does for the executor

**Comment by lourd** [comment]
Still open

**Comment by superami-code** [comment]
I am seeing the same issue with graphql-codegen. If I run the command directly I get a concise and colorful output:

```
> graphql-codegen -r dotenv/config --config apps/auth/codegen.yml --watch

✔ Parse Configuration
❯ Generate outputs
✔ Parse Configuration
✔ Generate outputs
  ℹ Watching for changes...
```
But running it through _nx:run-commands_ I get a bloated and grey output:

```
> nx run auth:graphql --watch

[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to apps/auth/src/generated/types.generated.ts
[STARTED] Load GraphQL schemas
(node:151608) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[SUCCESS] Load GraphQL schemas
[STARTED] Load GraphQL documents
[SUCCESS] Load GraphQL documents
[STARTED] Generate
[SUCCESS] Generate
[SUCCESS] Generate to apps/auth/src/generated/types.generated.ts
[STARTED] Generate to apps/auth/src/generated/graphql.ts
[STARTED] Load GraphQL schemas
[SUCCESS] Load GraphQL schemas
[STARTED] Load GraphQL documents
[SUCCESS] Load GraphQL documents
[STARTED] Generate
[SUCCESS] Generate
[SUCCESS] Generate to apps/auth/src/generated/graphql.ts
[SUCCESS] Generate outputs
  ℹ Watching for changes...
```

My target:
```
    "graphql": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [{
          "command": "graphql-codegen -r dotenv/config --config libs/angular-gql/codegen.yml",
          "forwardAllArgs": true
        }],
        "color": true,
        "outputPath": "libs/angular-gql/src/lib/auth/generated"
      }
    },

```

Any update on this?

**Comment by whalemare** [comment]
Same issue with default `@nrwl/react-native:start`

```json
"start": {
    "executor": "@nrwl/react-native:start",
    "options": {
      "port": 8081,
      "interactive": true
    }
  }
```

<img width="755" alt="Снимок экрана 2023-02-01 в 14 20 46" src="https://user-images.githubusercontent.com/9128731/216028979-c1d13208-75b6-486e-a481-4b0a82d75e4c.png">

But expected:

<img width="502" alt="Снимок экрана 2023-02-01 в 14 21 38" src="https://user-images.githubusercontent.com/9128731/216029153-50ce970e-54c7-4bbc-a54d-099705cbeab2.png">

**Comment by trungk18** [comment]
In our use case, we configured the command that was missing color with the additional flag of `--output-style=stream-without-prefixes`


```diff
"serve-open": {
  "executor": "nx:run-commands",
  "options": {
    "commands": [
-     "nx run my-bank:serve",
+     "nx run my-bank:serve --output-style=stream-without-prefixes",
      "open https://our-custom-domain.local"
    ],
    "parallel": true
  }
}
```

See the detail [here ↗️][1]

[1]: https://trungk18.com/experience/nx-commands-output-color/

**Comment by Cirelion** [comment]
Any update on this? Specifically the graphql-codegen example, it clutters our CLI with verbose info we don't need. I'm assuming this will happen with near to all similar cases.

**Comment by xiongemi** [comment]
with latest @nx/react-native, it has color log now, no need to pass FORCE_COLOR in. it is no longer an issue.
<img width="662" alt="Screenshot 2024-05-14 at 10 16 50 AM" src="https://github.com/nrwl/nx/assets/16211801/dea55d2e-2238-4153-9188-30ccb28ce6a2">
