### ISSUE TITLE
`implicitDependencies` added to package.json when using `@nrwl/node:package`

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#8065]
Related to #3231 

## Current Behavior

Given the following `workspace.json`

```json
{
  "projects": {
    "openapi-client-plugin": {
      "//": "generated with @nrwl/nx-plugin:plugin",
      "targets": {
        "build-openapi-client-plugin": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "nx build openapi-client-plugin"
          }
        }
      }
    },
    "my-openapi-client-lib": {
      "root": "libs/my-openapi-client-lib",
      "sourceRoot": "libs/my-openapi-client-lib/src",
      "projectType": "library",
      "targets": {
        "build": {
          "executor": "./dist/libs/openapi-client-plugin:package",
          "outputs": ["{options.outputPath}"],
          "options": {
            "outputPath": "dist/libs/my-openapi-client-lib",
            "tsConfig": "libs/my-openapi-client-lib/tsconfig.lib.json",
            "packageJson": "libs/my-openapi-client-lib/package.json",
            "main": "libs/my-openapi-client-lib/src/index.ts",
            "assets": ["libs/my-openapi-client-lib/*.md"]
          },
          "dependsOn": [
            {
              "target": "build-openapi-client-plugin",
              "projects": "dependencies"
            }
          ]
        },
        "generate-sources": {
          "executor": "./dist/libs/openapi-client-plugin:generate-sources",
          "options": {
            "specUrl": "http://localhost:3333/swagger-json",
            "additionalProperties": {
              "withInterfaces": true,
              "supportsES6": true,
              "typescriptThreePlus": true,
              "useSingleRequestParameter": true,
              "enumPropertyNaming": "original"
            },
            "globalProperties": {},
            "typeMappings": {}
          },
          "configurations": {
            "production": {
              "specUrl": "https://production-url/swagger-json"
            }
          },
          "dependsOn": [
            {
              "target": "build-openapi-client-plugin",
              "projects": "dependencies"
            }
          ]
        }
      },
      "tags": [],
      "implicitDependencies": ["openapi-client-plugin"]
    }
  }
}
```

Running `yarn generate-sources my-openapi-client-lib` generates source code inside the lib folder
Then, running `yarn build my-openapi-client-lib` packages the code.

If the `my-openapi-client-lib:build` executor were to be `@nrwl/node:package`, that would be the output package.json:

```json
{
  "name": "@my-workspace/my-openapi-client-lib",
  "version": "0.0.1",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts",
  "publishConfig": {
    "access": "restricted",
    "registry": "https://npm.pkg.github.com"
  },
  "dependencies": {
    "@my-workspace/openapi-client-plugin": "0.0.1"
  },
  "peerDependencies": {}
}
```

I wrote the following executor which handles that:

```ts
import { ExecutorContext, joinPathFragments } from '@nrwl/devkit';
import { packageExecutor } from '@nrwl/node/src/executors/package/package.impl';
import { readJsonFile, writeJsonFile } from '@nrwl/tao/src/utils/fileutils';
import { ExecutorSchema } from './schema';

export default async function runExecutor(options: ExecutorSchema, context: ExecutorContext) {
  const result = await packageExecutor(options, context);

  const packageJsonPath = joinPathFragments(result.outputPath, 'package.json');
  const packageJson = readJsonFile(packageJsonPath);
  delete packageJson.dependencies['@my-workspace/openapi-client-plugin'];
  writeJsonFile(packageJsonPath, packageJson);

  return result;
}
```

This results in the following package.json:

```json
{
  "name": "@my-workspace/my-openapi-client-lib",
  "version": "0.0.1",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts",
  "publishConfig": {
    "access": "restricted",
    "registry": "https://npm.pkg.github.com"
  },
  "dependencies": {},
  "peerDependencies": {}
```

## Expected Behavior

I would expect `implicitDependencies` of my project not to be appended to the resulting package.json.

If, however, this is a breaking change, perhaps introducing a new `implicitDevDependencies` can do the trick.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
 ▶ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.2.4
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : 13.2.3
  @nrwl/next : undefined
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @nrwl/nx-plugin: 13.2.4
         @trumbitta/nx-plugin-openapi: 1.10.0
```

**Comment by DaSchTour** [comment]
I also just hit this issue and would like to explain the issue with that. We have a server and a client project with a docker build step in the server project. Building the server project and having the client project as an implicit dependency adds all the angular stuff from the client application to the package.json of the server application. Inside our docker we run an npm install for the dependencies of the server application. This now fails because @nrwl/angular is added to the package.json as a dependency which has a dependency to `@parcel/watcher` which needs Python3 to build dependency because there are no pre built binaries for ARM. That's for sure an extreme edge case. But in general there should be either an option to exclude dependencies of other projects or this should be solved in general.

**Comment by DaSchTour** [comment]
I wonder if so few people have issues with that or if they do workarounds or maybe don't even notice. Had thought there would be more feedback on this issue.

**Comment by jaysoo** [comment]
I'm going to close this issue for two reasons:

1. The `@nrwl/node:package` is now `@nx/tsc`, and no longer has the same issue with its `--updateBuildableProjectDepsInPackageJson` flag (which is same as `--generatePackageJson` from old executor)
2. We've deprecated `--updateBuildableProjectDepsInPackageJson` and will remove it in a future Nx version. Libs should be using the `@nx/dependency-checks` lint rule to check and update their `package.json` file rather having it generate during builds. This is much more flexible, and ensures that users can maintain their source `package.json` with Nx's help, and we don't modify the dependencies during build time.
---
@DaSchTour It sounds like your issue is with apps, not libs. I would look at the same lint rule (https://nx.dev/packages/eslint-plugin/documents/dependency-checks), and enable `includeTransitiveDependencies: true` to pick up dependencies of workspace libs, configure `ignoredDependencies`, and optionally add `ignoredFiles` (currently only in 16.8.0-beta.4, but we're releasing 16.8.0 soon) to skip files you don't think should count.

// apps/<app>/.eslintrc.json
```json5
{
  "extends": "../../.eslintrc",
  "rules": {},
  "overrides": [
    //...
    {
      "files": ["./package.json"],
      "parser": "jsonc-eslint-parser",
      "rules": {
        "@nx/dependency-checks": [
          "error",
          {
            "buildTargets": ["build"],
            "includeTransitiveDependencies": true,
            "ignoredDependencies": [
              "@parcel/watcher"
            ],
            "ignoredFiles": [
              "{workspaceRoot}/libs/other-lib/src/foo.ts"
             ]
          }
        ]
      }
    }
  ],
  "ignorePatterns": ["!**/*"]
}
```

This way you can run `nx lint <app>` and `nx lint <app> --fix` to check and fix issues respectively.
