### ISSUE TITLE
tsbuildinfo has wrong path for Storybook

### ISSUE THREAD

**Issue by BorisZubchenko** [nrwl/nx#8198]
## Current Behavior
.tsbuildinfo files, generated from the incremental flag, have wrong paths for Storybook:
```
apps/site/.storybook/apps/site/.storybook/tsconfig.tsbuildinfo
```

Also, I think these files should be gitignored.

Plus, [wrong paths](https://github.com/BorisZubchenko/nx-next/blob/tsbuildinfo-path/apps/site/.storybook/main.js#L10) is set for `.stories.` files (I don't know whether I have to create another issue for this problem):
```
    '../src/app/**/*.stories.mdx',
    '../src/app/**/*.stories.@(js|jsx|ts|tsx)',
```

## Expected Behavior
```
apps/site/.storybook/tsconfig.tsbuildinfo
```

## Steps to Reproduce

[repro repo](https://github.com/BorisZubchenko/nx-next/tree/tsbuildinfo-path) (branch `tsbuildinfo-path`)

1. `npx create-nx-workspace` with Nextjs (I'm not sure if it's true for other options)
2. build the project -- incremental flag should now be enabled in `tsconfig.json`
3. `npm i -D @nrwl/storybook`
4. `nx g @nrwl/react:storybook-configuration site`
5. `nx run site:storybook` (this command generates `tsconfig.tsbuildinfo`)

### Failure Logs

No failure logs

### Environment

```
  Node : 14.17.3
  OS   : linux x64
  npm  : 6.14.13
  
  nx : 13.3.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.6
  @nrwl/cypress : 13.3.6
  @nrwl/devkit : 13.3.6
  @nrwl/eslint-plugin-nx : 13.3.6
  @nrwl/express : undefined
  @nrwl/jest : 13.3.6
  @nrwl/linter : 13.3.6
  @nrwl/nest : undefined
  @nrwl/next : 13.3.6
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.6
  @nrwl/web : 13.3.6
  @nrwl/workspace : 13.3.6
  @nrwl/storybook : 13.3.6
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

```

**Comment by mandarini** [comment]
Hi there @BorisZubchenko ! Thanks for filing an issue. I'll look into the `. tsbuildinfo` things. However, I do not see how the `.stories.*` path are wrong. Can you please give me some more info on that?

**Comment by BorisZubchenko** [comment]
@mandarini, as seen [here](https://github.com/BorisZubchenko/nx-next/tree/tsbuildinfo-path/apps/site), the app doesn't have `src/app` folder, which leads to a compile error.

**Comment by mandarini** [comment]
Hi @BorisZubchenko ! Sorry, I literally just got around to looking into this. So, your real issue is that Nx does not support automatic Storybook configuration generation for Next.js. That does NOT mean that you cannot use Nx with Next.js+Storybook. You can, but you have to write your own configuration manually. 

As you can see, when you used the Nx generator to generate Storybook configuration for your project, you used the `@nrwl/react:storybook-configuration`. This means that Nx generated Storybook configuration that would be valid to a React project.

If you want to use Storybook on your Next.js app, you can [take a look at this great guide here](https://storybook.js.org/blog/get-started-with-storybook-and-next-js/). You can also take a look at [this blog post series by Juri](https://juristr.com/blog/2021/06/create-nextjs-webapp-nx/) explaining how to set up a Next.js + Nx + Storybook app! Notice how, at [this step](https://juristr.com/blog/2021/08/nextjs-storybook-tailwind-nx/), the components are built with React, in a React library, and Storybook is added in that library.

Please let me know if you have more questions, I'll be happy to help! And please let me know if I can go ahead and close this issue! :)

**Comment by BorisZubchenko** [comment]
@mandarini, thank you for a detailed response, it's now clear for me that I should manage storybook within React's library.

**Comment by mandarini** [comment]
:) Glad I could help!
