### ISSUE TITLE
Add express to monorepo - "Can only convert projects with one app" ERROR

### ISSUE THREAD

**Issue by duxard** [nrwl/nx#8272]
Hi Team,

I'm trying to create a monorepo with Angular + React + Express. I did the following steps:
1) Created a new monorepo with Angular in it
npx create-nx-workspace nx-monorepo --preset=angular

2) Added React pluggin
nx add @nrwl/react

3) Added React project
nx g @nrwl/react:app app-react

4) Then tried to add Express:
nx add @nrwl/express

But here it gives me an error "Can only convert projects with one app"

![image](https://user-images.githubusercontent.com/18247015/147072512-614f655e-880c-498c-8fba-634190a4c189.png)

Can you pls advice me on what I'm doing wrong? Is it possible to create [Angular + React + Express] monorepo at all?

Thanks,
Aleksandr

**Comment by FrozenPandaz** [comment]
I would start with the `react-express` preset since it contains 2 of the projects that you want. And then I would add `@nrwl/angular` to it.

1. `npx create-nx-workspace@latest nx-monorepo --preset react-express
2. `npm i @nrwl/angular`
3. `nx g @nrwl/angular:app angular-app`

`nx add` isn't recommended and once you install the `node_module`, you can immediately create the application.
