### ISSUE TITLE
Allow to create node-app without jest

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#839]
When generating a `node-app` in a new Nx Workspace, this message appears:

`Your workspace does not have jest installed. Please run "ng generate jest" to setup your workspace to run tests with jest.` 

It would be great if we could disable this requirement. :)

**Comment by FrozenPandaz** [comment]
So `node-app` sort of should work on `jest` instead of `karma` since they do not need to run in a browser. However, I fixed this issue by simplifying the flow of creating a project which uses `jest`. Instead of throwing an error telling you to generate `jest`, it will generate `jest` if necessary as part of the project creation (`ng lib` or `ng app`). What do you think?

**Comment by beeman** [comment]
@FrozenPandaz I'm totally fine with including it in the `app`/`lib` generator. Great solution, thanks! 👍
