### ISSUE TITLE
Integrate NativeScript Schematics w/ Angular 7

### ISSUE THREAD

**Issue by tommyc38** [nrwl/nx#841]
With the release of Angular 7, NativeScript CLI tools are integrated with angular to produce scaffolding.  It would be awesome if Nx could integrate as well.

**Comment by bcabanes** [comment]
Hi @tommyc38,
I think the integration with Nx and Nativescript is already done via @NathanWalker's library xplat: https://github.com/nstudio/xplat.

**Comment by NathanWalker** [comment]
Thanks @bcabanes - it’s possible to integrate {N} schematics with xplat as well. The approaches are slightly different as they both address 2 different use cases. 
@tommyc38 you might give both a try and share your thoughts on your use case with them.

**Comment by skydever** [comment]
hi @NathanWalker 

Maybe a bit off topic, sorry for that. I read on your [website](https://nstudio.io/xplat/) that you are planning to integrate [electron](https://electronjs.org/) as well. I had to create an electron app recently and I am in the middle of refactoring my custom integration. Maybe there is a preview version of that available somewhere, or can you expand on that somehow, how your solution would look like?

**Comment by NathanWalker** [comment]
Hi @skydever you can check out preview of some contributor changes here:
https://github.com/miguelramos/xplat/commit/49b6471e0a63c86b9ea61156bd11768eff6756cc
The aim would be for electron to be as seamless and consistent as the other app generators as well as play nicely with the entire setup to maximize reuse across multiple electron apps or any platform which makes sense in the workspace.

@tommyc38 this is also what sets xplat in slightly different use case category than just {N} schematics since xplat’s aim is to maintain interop scalability and harmony across multiple platforms in a single Nx workspace.

**Comment by skydever** [comment]
thank you @NathanWalker 👍

**Comment by tommyc38** [comment]
@NathanWalker , thank you for the response.  Your project looks sweet!  I am not quite clear on what the different use cases are for {N} schematics vs xplat given I've never built anything with {N} but plan to.   I saw the release notes of Angular 7 and saw there were schematics to remove the boiler plate setup and thought this would be amazing for Nx--assuming it wouldn't work out of the box correctly in an Nx workspace.  I look forward to giving your library a shot when the time comes in the next few months!
