### ISSUE TITLE
No build error logs with @angular-devkit/build-angular:ng-packagr

### ISSUE THREAD

**Issue by tmo207** [nrwl/nx#8456]
## Current Behavior
No build error logs are shown when building an angular library with @angular-devkit/build-angular:ng-packagr. The build error looks like the following no matter if the --verbose flag is passed or not.

<img width="582" alt="Capture d’écran 2022-01-10 à 12 09 35" src="https://user-images.githubusercontent.com/29772543/148756573-f0f51a16-9464-430b-9386-8a9b101bcf0d.png">

## Expected Behavior
The build error should display the error (location, error type, ...).

## Steps to Reproduce
Use this repo to reproduce the error: https://github.com/tmo207/nx-ng-build
The errors is produced here: https://github.com/tmo207/nx-ng-build/blob/master/libs/ng-lib/src/lib/ng-lib.module.ts

Run `nx build` and `nx build --verbose` to see the buggy behaviour.

### Environment
```
Node : 14.15.5
  OS   : darwin x64
  npm  : 7.13.0
  
  nx : 12.10.1
  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by Coly010** [comment]
@tmo207 After investigating this comprehensively, the reason that particular builder does not produce error logs is because it behaves different to other angular builders. Instead of throwing an error, it catches them internally and transforms them to an object containing an error string.

You can however get the expected outcome if you use `@nrwl/angular:pacakage` builder instead. It uses `ng-packagr` under the hood so you get the same experience, but it will output the logs correctly.
