### ISSUE TITLE
Cannot run NX commands after successful NX migration from 12 to 13

### ISSUE THREAD

**Issue by danwellman** [nrwl/nx#8588]
I'm trying to migrate an Angular 12 project to Angular 13
I've followed the nx migrate process:

1. `nx migrate latest`
2. `npm i --legacy-peer-deps` (had to use the --legacy-peer-deps flag because it was failing on mismatched deps)
3. `npm outdated` -> then manually update red items to minimum requested versions
4. Removed projects object from nx.json (couldn't run migrations until I did this)
5. `nx migrate --run-migrations` <- completed successfully with no errors, but gave a ton of warnings about unknown projects
6. One last `npm install` (without flags) just to be sure -> success

However, now when I try to run nx commands like nx serve or nx build, or even nx test it just fails with

> NX ERROR spawn ENAMETOOLONG

What now?

### Environment
Windows
node v 16.13.2
npm v 8.1.2

**Comment by danwellman** [comment]
FYI, re-adding the projects back to nx.json fixes the issue, but I am left with the warning about project configuration being moved to workspace.json/project.json

If this new config is required, should there be a migration that does it for you?

**Comment by danwellman** [comment]
Update:

Also tried changing angular.json version to 2 then running `nx format` followed by ` nx generate @nrwl/workspace:convert-to-nx-project --all=true`

The first command failed wiht output:
>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD
>  NX   ERROR  spawn ENAMETOOLONG

The second command seemed to complete successfully and has created project.json files for all of my libs, however, I still cannot run nx serve, it just gives the same message as before:

> Cannot determine project or target for command.

**Comment by aventic** [comment]
This is just a wild guess, but makes sense. I can see you posted this 2 days ago, and I see NX published a new version ​of the NX-suite (npm packages, workspace, cli and so on) 2 days ago.

I just encountered the same issue as you with ENAMETOOLONG when I was trying any NX command in my just migrated project. I rolled my current version one minor back. From 13.4.6 to 13.4.5. Not sure if that's working for you?

So there's definitely a bug in 13.4.6, just not sure what and why. I tried to remove some files i my project, and then I was able to run the nx serve command. I added the files I removed and then got the error again. I tried to remove one file at a time. And suddently I was able to run the commands without errors. So the bug seems related to number of files and not the content of the files, not sure tho. Didn't have time to test further.

**Comment by danwellman** [comment]
That's really useful, thanks @aventic 
Haven't got around to testing yet but I'll give this a try as soon as I can, thanks 👍

**Comment by danwellman** [comment]
To confirm, rolling back to 13.4.5 fixed the issue

**Comment by danwellman** [comment]
Running `nx format` has fixed the test issue 👍
