### ISSUE TITLE
`yarn lint` ignores `.eslintrc.js`

### ISSUE THREAD

**Issue by binary64** [nrwl/nx#8619]
Would it be good a good idea to add `.eslintrc.js` to nx.json > implicitDependencies too (since tslint is in there, why not this too)

**Comment by meeroslav** [comment]
The `.eslintrc.js` is not fully supported by Nx (migration and generator-wise). There was a request in the past to support that format as well, but due to our capacity and the fact that the `eslint` team is working on a new format `eslint.config.js` (more details [here](https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification)) we have decided to support only `json` format. 

The `tslint` was there historically for Angular projects, but should be removed for all the newly generated projects.

Once the new format is out, we will support it along with the current `json` format.
