### ISSUE TITLE
workspace: `workspace-lint` doesn't throw if project is missing in nx.json

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#8666]
## Current Behavior

with following setup:

_workspace.json_
```json
{
  "version": 2,
  "projects": {
      "ui-header": { ... }
      "my-app": { ... }
   }
}
```

_nx.json_
```json
{
"projects": {
   "my-app": { ... }
}
}
```

running `workspace-lint` will PASS ✅

![image](https://user-images.githubusercontent.com/1223799/150782569-b7a6e7dc-e89b-42d2-b30b-560a64f90e9e.png)

## Expected Behavior

running `workspace-lint` should FAIL as nx.json is missing `ui-header` project 

NOTE: this might come as a surprise for nx users that are not below version 13. starting nx 13 this is not an issue as all projects are merged to `workspace.json` or per project

## Steps to Reproduce

1. npx create-nx-workspace@12 --preset=react
2. npx nx g @nrwl/react:lib ui-header
3. remove `ui-header` from nx.json
4. npx nx workspace-lint

### Environment

```
 Node : 14.18.1
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.10.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : 12.10.1
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by FrozenPandaz** [comment]
Hm so it's been broken since `~12.5.0`.

If you submit a patch against [12.10.x](https://github.com/nrwl/nx/tree/12.10.x), I'll take a look. :)

**Comment by meeroslav** [comment]
Actually, this is intentional behavior. If a project is missing in `nx.json` it simply means that there are no tags and no implicit dependencies defined, since the remaining configuration (which is mandatory) is located in `workspace.json` for v12.10.x.

If you look at the [readNxJson](https://github.com/nrwl/nx/blob/12.10.x/packages/workspace/src/core/file-utils.ts#L227-L230) you will see that we intentionally map missing projects with dummy metadata.

In order to check for the missing project in `nx.json` we could check if any of the projects are defined without any metadata in the `WorkspaceIntegrityChecks` but by doing so we would break the `workspace-lint` for all those folks that depend on this not to be reported as an error.

IMHO, this should not be changed.
