### ISSUE TITLE
Do you want the application “node” to accept incoming network connections?

### ISSUE THREAD

**Issue by wiltsu** [nrwl/nx#8738]
## Current Behavior
After installing nx globally (`npm install -g nx`), and selected the nx cloud option on setup, every time i launch a node app (even outside the nx repo), mac prompts a 
`"Do you want the application “node” to accept incoming network connections?"`

## Expected Behavior
Mac shouldn't prompt this, especially outside the nx repo, and super especially not anymore since i **uninstalled** nx globally.

**Comment by FrozenPandaz** [comment]
As you mentioned, the issue occurs outside an Nx repo, without nx installed globally. Also, Nx does not do anything to update your `node` binary. I am pretty positive that this prompt is not caused by nor is it related to Nx. 

May I ask how you installed `node`? Was it through the `.dmg` file on the [nodejs website](https://nodejs.org/en/download/), `nvm`, or `n`?

Can you try re-installing node and see if that resolves the issue?

I'm not sure how to help beyond that.

**Comment by wiltsu** [comment]
> As you mentioned, the issue occurs outside an Nx repo, without nx installed globally. Also, Nx does not do anything to update your `node` binary. I am pretty positive that this prompt is not caused by nor is it related to Nx.
> 
> May I ask how you installed `node`? Was it through the `.dmg` file on the [nodejs website](https://nodejs.org/en/download/), `nvm`, or `n`?
> 
> Can you try re-installing node and see if that resolves the issue?
> 
> I'm not sure how to help beyond that.

This brings the thought to my head that I did update the required engine of the node application from 14.15.0 to 14.17.0 along with the nx migration, with `n`. I thought it had something to do with nx or with nx cloud more specifically. I guess not. Thanks for your help, I'll try to fiddle with the node installations and come back here if I find a solution.
