### ISSUE TITLE
Set different tags on a library depending on the file type

### ISSUE THREAD

**Issue by jogelin** [nrwl/nx#8818]
## Description
The [boundary system](https://nx.dev/structure/monorepo-tags) is really useful on big repositories for protecting developers against "human" mistakes. Especially when your repository is consistent on naming and folder structure.

However, there is a use case that I cannot solve with the current boundary system: How can we create a different constraint for a `.component` file and it's related `.spec` to be sure that the `.component` will not access to a library that is only reserved for testing?

## Motivation
A concrete example that I have in mind is the usage of mock factories exposed by a library for all of my tests. 
Those factories are using `faker.js` (RIP) and I want to be sure that my application will not have this code in the final bundle. However the `.spec` file next to my component is using it.

## Suggested Implementation
I was thinking about a way to assign a regex/glob for each tag in my library configuration:
```json
  "tags": {
       '*': ["domain:store", "type:ui"],
       '*.spec.ts': ["domain:store", "type:test"]
   }
```

## Alternate Implementations
- I could create another library only with `*.spec` files. Then I loose the benefit of having test next to components/services
- Add an eslint ignore in my tests imports (solution used for the moment)

**Comment by FrozenPandaz** [comment]
For linting, this is easier to specify as a different lint rule for a different subset of files via ESLint itself:

```json
  "overrides": [
    ...,
    {
      "files": ["**/*.ts"],
      "excludedFiles": ["**/*.spec.ts"],
      "rules": {
        "no-restricted-imports": ["error", "faker.js"]
      }
    }
  ]
  ```
  
This only errors in `.ts` files that are not `.spec.ts` files like you want.
  
The same goes with the `nx-enforce-module-boudnaries` lint rule, it can be applied with different configurations to different subsets of files. As such, I don't think tagging parts of projects is necessary since tagging is mostly used for linting.
