### ISSUE TITLE
Cannot import @nrwl/node:lib into @nrwl/next:app 

### ISSUE THREAD

**Issue by evk8** [nrwl/nx#8823]
## Current Behavior

nx version updating 12.9.0 -> 13.5.3
use next.js custom server.

project.json
```
"customServerPath": "server.js"
```

### Failure Logs

created abc library -> serve -> error
`
Module parse failed: Unexpected token (1:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export function abc(): string {
|   return 'abc';
| }
`

### Environment

"@nrwl/cli": "13.5.3",
  "@nrwl/cypress": "13.5.3",
  "@nrwl/eslint-plugin-nx": "13.5.3",
  "@nrwl/jest": "13.5.3",
  "@nrwl/linter": "13.5.3",
  "@nrwl/react": "13.5.3",
  "@nrwl/tao": "13.5.3",
  "@nrwl/web": "13.5.3",
  "@nrwl/workspace": "13.5.3",
  "@testing-library/react": "12.1.2",
  "@testing-library/react-hooks": "7.0.2",
  "@types/jest": "27.0.2",
  "@types/node": "16.11.7",
  "@types/react": "17.0.30",
  "@types/react-dom": "17.0.9",
   "next": "12.0.7",
    "react": "17.0.2",

**Comment by ndcunningham** [comment]
Hey, thanks for opening this issue from what I got you tried to import a lib inside of your nextjs app.
I could not reproduce it

P.S
`@nrwl/node:lib` is now `@nrwl/js:lib` could you try to see if this works with the latest version of master since this ticket is a few revisions behind current?
Please open a new issue if the problem still persist

**Comment by AlexandreCassagne** [comment]
@evk8  I have the same issue — were you able to fix it?
