### ISSUE TITLE
 tsconfig.json should not remove tsconfig.base.json paths

### ISSUE THREAD

**Issue by vugar005** [nrwl/nx#8826]
Assume you have mfe1 app in apps folder. This app has core folder. So you decide to simplify core imports via
// tsconfig.json in apps/mfe1
```
 "paths": {
     "@core/*": ["apps/mfe1/src/app/core/*"]
  }
```
Then you generate new library for example:
`nx g @nrwl/angular:lib shared/ui --importPath=@myorg/ui`
which adds path in tsconfig.base.json as expected. ` "@myorg/common-ui": ["libs/shared/ui/src/index.ts"]
`

## Current Behavior

But the problem is this tsconfig.base.json paths will be removed by tsconfig.json. So below will not work:
```
import { EventDispatcherService } from '@core/services/events-dispatcher';
import { PollingService } from '@myorg/common-ui'; // is not recoginized because it is removed.
```

## Expected Behavior
 tsconfig.json should NOT remove  tsconfig.base.json paths. It should override but not remove.

## Steps to Reproduce
Written on introduction above

### Environment
Nx 13.7

## Workaround
The workaround is to specify all paths in base.json but this is not convenient and we should include longs names such as `@core-mfe1` instead of `@core`
I know it is not issue with NX but tsconfig configuration but I would like to know the idea of NX how to solve this issue.

**Comment by FrozenPandaz** [comment]
Yes, this is the nature of `tsconfig.json` extensions and Nx doesn't do anything about this.

1. I would recommend keeping apps as lightweight as possible only serving to compose different libs together.
2. Create libs that are meant to only be consumed by 1 app.
  a. If your app is `admin`
  b. The lib could be like `admin/events-dispatcher`
3. The lib naturally have a path mapping
  a. This alleviates having to run the unit tests for that code each time because apps are most likely to be affected by changes to the workspace
  b. You would be able to easily move the lib later on if it were to be shared with other apps. You might think it will never happen but, you never know.
  c. Personally, I don't think the long paths are really an issue but if you'd like you can even specify a different `--importPath` when generating a library (or change it manually in `tsconfig.base.json`) to be shorter.
  
  I hope that answers your question. :smile:

**Comment by vugar005** [comment]
@FrozenPandaz Sorry for the late reply. Thanks for suggestion.

**Comment by roddc** [comment]
> Yes, this is the nature of `tsconfig.json` extensions and Nx doesn't do anything about this.
> 
> 1. I would recommend keeping apps as lightweight as possible only serving to compose different libs together.
> 2. Create libs that are meant to only be consumed by 1 app.
>    a. If your app is `admin`
>    b. The lib could be like `admin/events-dispatcher`
> 3. The lib naturally have a path mapping
>    a. This alleviates having to run the unit tests for that code each time because apps are most likely to be affected by changes to the workspace
>    b. You would be able to easily move the lib later on if it were to be shared with other apps. You might think it will never happen but, you never know.
>    c. Personally, I don't think the long paths are really an issue but if you'd like you can even specify a different `--importPath` when generating a library (or change it manually in `tsconfig.base.json`) to be shorter.
> 
> I hope that answers your question. smile

Hi,
I tried to override the `tsconfig.json` with `"@my-lib/*:["libs/my-lib/src/*"]"` in the lib folder, I copied all pathes from `tsconfig.base.json` and I got errors from compiler `Cannot resolve module @my-lib`.
However, if I add `"@my-lib/*:["libs/my-lib/src/*"]"`  to `tsconfig.base.json`, I will get `@nrwl/nx/enforce-module-boundaries` warning
