### ISSUE TITLE
Built JS projects can't access workspace libraries

### ISSUE THREAD

**Issue by jackmerrill** [nrwl/nx#8832]
## Current Behavior
Any projects built with `@nrwl/js:tsc` or `@nrwl/js:swc` can't access any custom workspace libraries (i.e. `@myworkspace/mylibrary`) when ran from the built JS file.

## Expected Behavior
When running `node ./dist/apps/myJsApp/src/index.js` with a custom workspace library, there should not be any module errors. For example, I get `Error: Cannot find module '@myworkspace/mylibrary'` with the stack in the built `index.js` file.

## Steps to Reproduce
1. Create a new NX project using `@nrwl/js`
2. Create a new NX JS library
3. Import the JS library in the project
4. Build the project and run it

### Environment
```
  Node : 16.13.2
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 13.4.5
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.4.1
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : 13.4.3
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : 13.4.1
  @nrwl/node : 13.4.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.5
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : 13.4.5
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.4.6
```

**Comment by jackmerrill** [comment]
Still having this issue on the latest version of `@nrwl/js` with both SWC and TSC. Works in dev mode (`yarn nx serve`). Is this an issue with SWC/TSC, my configs, or NX itself?

I hate to bump this issue but I really need this bug fixed so I can continue on my project. 

Worst case, I can use `@nrwl/node` but I would have to refactor a lot of my code. (Since that uses webpack, and my current code uses `fs` to import other JS files, I would need to rewrite some code to support it)

**Comment by ddanielcruzz** [comment]
@jackmerrill Hey did you find a solution? I'm having a similar bug 🐛

**Comment by jackmerrill** [comment]
I ended up doing what I said was my "worst case", rewriting everything. Heavily don't recommend haha.

So basically, no I didn't find a solution :(

**Comment by 03byron** [comment]
Maybe [this](https://nx.dev/reference/project-configuration#dependson) helps. 
```
"dependsOn": [{ "projects": "dependencies", "target": "build" }]
``` 
did the trick for me.

**Comment by clfhhc** [comment]
@03byron How did the trick help you?

I have the same issue with the compiled js file still trying to import from `@myworkspace/mylibrary`, even though all the dependencies have been compiled.

**Comment by AgentEnder** [comment]
Hey 👋, sorry this has taken a long time to get a solid (or any) answer from a team member.

In essence, the reason this doesn't work is that neither TSC or SWC bundles your project. Without a bundler, your imports still reference the tsconfig paths, but `node` and similar do not read tsconfig paths. From [typescript's docs](https://www.typescriptlang.org/tsconfig#paths:~:text=Note%20that%20this%20feature%20does%20not%20change%20how%20import%20paths%20are%20emitted%20by%20tsc%2C%20so%20paths%20should%20only%20be%20used%20to%20inform%20TypeScript%20that%20another%20tool%20has%20this%20mapping%20and%20will%20use%20it%20at%20runtime%20or%20when%20bundling.):

> Note that this feature does not change how import paths are emitted by tsc, so paths should only be used to inform TypeScript that another tool has this mapping and will use it at runtime or when bundling.

This is the same reason that if you were using `ts-node` you need to pass `-r tsconfig-paths`, that can be seen here: https://typestrong.org/ts-node/docs/paths/

What this means for you, a developer of a library that uses TSC or SWC within Nx is that you need to do one of the following when running your project:

- Use the @nrwl/node:node executor to run the code, rather than just `node` directly. With this, we provide some remappings at runtime that make your tsconfig paths work.
- Use (ts-node or swc-node) and tsconfig-paths,  as described in the docs above
- Set up your build s.t. the built directory structure mimics a node_modules layout or similar, so that node is able to resolve them natively (a bit convoluted, not super recommended)
- Use the `external` property on your build executor. See the docs here: https://nx.dev/packages/js/executors/tsc#external, specifically if you scroll up a bit there is info for inlining your workspace libraries in a tab.
