### ISSUE TITLE
Not setting 'workspaceLayout' breaks webpack config on @nrwl/next v 13.8.0

### ISSUE THREAD

**Issue by nilanjansiromani** [nrwl/nx#8924]
## Current Behavior
All tasks works fine on `12.8.0`

## Expected Behavior
On migrating to v 13.8.0, and upgrading @nrwl/next to v13.8.0
webpack configuration should work normally

## Steps to Reproduce
do not keep a workspacelayout property
install the latest @nrwl/next [v 13.5 onwards]
In the file `node_modules/@nrwl/next/src/utils/config.js`

the parameter defaults to `''`
and that breaks the webpackconfig

references

```js
function createWebpackConfig(workspaceRoot, projectRoot, fileReplacements = [], assets = null, nxConfigOptions = {}, dependencies = [], libsDir = '') { // 
    // ***************** libsdir should not be '' ??
    return function webpackConfig(config, { isServer, defaultLoaders, }) {
        // default `svgr` to `true`, as it used to be supported by default,
        // before this option was introduced
        if (typeof nxConfigOptions.svgr === 'undefined') {
            nxConfigOptions.svgr = true;
        }
        const mainFields = ['es2015', 'module', 'main'];
```

**Comment by cdaringe** [comment]
@nilanjansiromani, can you clarify? In the snippet provided, i don't see how libsdir interoperates with the webpackConfig?

**Comment by ndcunningham** [comment]
@nilanjansiromani I don't quite understand the problem.
Can you provide a sample repo?

**Comment by ericbiewener** [comment]
`workspaceLayout` does not necessarily need to be set in `nx.json` because [it defaults to `{ appsDir: "apps", libsDir: "libs" }`](https://github.com/nrwl/nx/blob/master/packages/nx/src/config/configuration.ts#L24-L27). The problem was that we were actually calling `createWebpackConfig` from some of our repo's code and did not update it to provide the `libsDir` argument that is now required in v13, whereas it was not required in [v12](https://github.com/nrwl/nx/blob/513f1036584267bb2b8f894d464f60e5e81cce1d/packages/next/src/utils/config.ts#L30-L37).
