### ISSUE TITLE
Tool to help merge conflict on workspace.json

### ISSUE THREAD

**Issue by Arcahub** [nrwl/nx#8960]
## Description
A tool to handle git conflict in `workspace.json` file

## Motivation
Hello, I am using @nrwl/nx monorepo for almost all projects, I am working with other people and so multiple branches and we always end up with merge conflicts on the `workspace.json` and the `tsconfig.base.json` files and since we are using `git rebase` strategy, it add a lot of burden to every pull request. So a tool to handle these conflicts would be really appreciated.

## Suggested Implementation
Sorry I do not have any ideas of how to implement this.

**Comment by FrozenPandaz** [comment]
We've done a lot previously to help reduce the chances of getting a merge conflict:
* Sorting projects alphabetically
* Moving configuration into `project.json` files

But when the workspace is first started, it can still be likely that you'll encounter merge conflicts. This should go *down* over time even as more devs onboard.

`workspace.json` is already _optional_. And one day, this may become the default.

While I do think that such a tool would be cool, I would not recommend building one since the best way to prevent merge conflicts is to not have the file at all. :wink: Again, it's a cool idea but I'm going to close this issue in favor of removing `workspace.json`.
