### ISSUE TITLE
Nx React and Content Security Policy (CSP) 

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#9091]
## Current Behavior
"INLINE_RUNTIME_CHUNK=false" command does not work with NX React. I would use this to avoid the use of 'unsafe-inline' for style-src CSP directive 

In a normal React app I would use 
`"build": "set \"INLINE_RUNTIME_CHUNK=false\" && react-scripts build"`
and this would enable my CSPs to work properly

I have tried the following in my pipeline
`script: set \"INLINE_RUNTIME_CHUNK=false\" && npx nx affected --base=HEAD~1 --target=build`
but this doesn't work 

Is there a way to use "INLINE_RUNTIME_CHUNK=false" when using NX?

Can you advise why #2932 was closed? This seems like a security issue that needs to be resolved to me?

More info https://drag13.io/posts/react-inline-runtimer-chunk/index.html

## Expected Behavior
You should be able to have "INLINE_RUNTIME_CHUNK=false" when using NX otherwise having CSPs breaks the application

**Comment by 72gm** [comment]
INLINE_RUNTIME_CHUNK is actually a create-react-app thing:

"By default, Create React App will embed the runtime script into index.html during the production build. When set to false, the script will not be embedded and will be imported as usual. This is normally required when dealing with CSP."

https://create-react-app.dev/docs/advanced-configuration/ 

So I guess my question should be how can you do this in NX? Are can you not have content security policies if using NX?

**Comment by 72gm** [comment]
A workaround is to use 'unsafe-inline'. 

![image](https://user-images.githubusercontent.com/12847881/155551068-6c6d0aba-f0a1-4f61-b8c7-bfe9c2731109.png)

This isn't ideal as it reduces the security rating from "A+" to "A" when scanning at https://securityheaders.com/ (hopefully my security team will let this pass)

Are there any plans to add such a config option to NX that create-react-app has?

**Comment by pinguinosod** [comment]
I'm facing the same issue.
Did you find a way to solve this without adding 'unsafe-inline'? @72gm

**Comment by sayeedhussain** [comment]
Hello Maintainers, @FrozenPandaz,

This seems to be a security concern. Can you please let us know your plan to address this?

**Comment by jaysoo** [comment]
There shouldn't be anything that requires  inline `<script>` or `<style>` tags. The default generated app has an `NxWelcome` component that uses `<style>`, but it is meant to be deleted anyway.

Here's a demo for a simple app.

https://github.com/jaysoo/csp-example

Can someone link to a reproduction for me to look at?

**Comment by jaysoo** [comment]
Also make sure you don't have any browser extensions that may inject styles or fonts.

**Comment by jaysoo** [comment]
Closing this issue as there shouldn't be anything from Nx's React setup that needs inline scripts or styles.

If someone can provide some reproduction steps please post them and re-open this issue (or create a new one).

**Comment by sayeedhussain** [comment]
@jaysoo Upon further investigation, I discovered that this issue is indeed cause by MaterialUI https://github.com/mui/material-ui/issues/19938

However, I have a question based on the sample code shared by you above.

In your code when we add inline style in the index.html file, we are getting the CSP error. But when we add inline style in app.tsx file, we are not getting the CSP error. Do you have any idea why that might be happening?

Please refer attachments.
<img width="1331" alt="Screenshot 2022-07-22 at 3 08 57 AM" src="https://user-images.githubusercontent.com/1550131/180274122-354298b5-c960-4247-bbc6-5a013ab81263.png">
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1550131/180274156-e2687c05-0d23-46c6-9c29-08ae5fcc0f94.png">
<img width="1335" alt="Screenshot 2022-07-22 at 3 09 30 AM" src="https://user-images.githubusercontent.com/1550131/180274179-7009ad46-0f00-44df-bc74-878ad5476a23.png">
<img width="1789" alt="image (1)" src="https://user-images.githubusercontent.com/1550131/180274211-7d2e8af9-cecd-4a1e-859e-7ed9f492d0c7.png">
