### ISSUE TITLE
web:rollup executor build watch mode not working when the project has dependencies

### ISSUE THREAD

**Issue by owen26** [nrwl/nx#9125]
## Current Behavior

Say there is a library A and library B which depends on A `B --> A`, both with target `build` powered by executor `web:rollup`.

Run `nx build B --watch`, only lib `A` is built and watched. B is neither built nor watched.

## Expected Behavior

Both A and B should be built and watched.

## Steps to Reproduce

Described in Current Behaviour.

Possible cause:

B target might be waiting for A target to be finished because NX detected A is a dependency for B.

However, in watch mode, this logic doesn't make sense as A never finishes because it's in watch mode.

### Environment

Node : 16.11.1
   OS   : darwin x64
   yarn : 1.22.17

   nx : 13.8.0
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.0
   @nrwl/cypress : 13.8.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.0
   @nrwl/eslint-plugin-nx : 13.8.0
   @nrwl/express : undefined
   @nrwl/jest : 13.8.0
   @nrwl/js : 13.8.0
   @nrwl/linter : 13.8.0
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.0
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.0
   @nrwl/tao : 13.8.0
   @nrwl/web : 13.8.0
   @nrwl/workspace : 13.8.0
   typescript : 4.5.5
   rxjs : 6.6.7

**Comment by owen26** [comment]
After investigating NX source code a bit, I've realised it may not be an easy fix that I imagined initially.

As mentioned in the issue description the main cause of this issue is that `watch` mode doesn't terminate the node process and that makes NX think the dependency command is not done yet. As a result, follow up command won't be called.

This edging case only affects scenarios where all tasks triggered by the watch mode command are using the same executors. e.g. `web:rollup`.

If the whole command chain is initialised by a different executor, for example `web:webpack`, this bug is avoided because in the definition of `function addTasksForProjectTarget()`, a different executor erases all inherited overrides including watch mode. So only the project from `webpack` executor is watched and webpack detect changes from all imported files.

To fix this issue a new target running option might need to be introduced to allow all tasks to run in parallel without waiting for deps task finish.

**Comment by AgentEnder** [comment]
Your suspicion that this wouldn't be a super easy change is correct, but it's also something I'd have imagined working. We'll take a look, thanks.

**Comment by kschaefe** [comment]
The point above about the same executor being the source of the problem holds true for Angular builds as well.  (As one would expect.). Having multiple Angular libraries, `--watch` waits for the first one and never watches anything else.

Our environment has only partially migrated to Nx and we have some libraries and applications in other repos.  We use `--watch` to help break the Webpack build cache that ng13 relies on so that we don't need to manually update the package version every single time while developing.

While a fix to the `--watch` problem (or the `--no-deps` option) would be great, I'd be happy  with a workaround that just added an option to append a timestamp to the package.json version (`--appendVersionTimestamp`).  This would solve our most frequent use-case.

**Comment by DibyodyutiMondal** [comment]
I noticed that if I create a custom exector, then I should either return a promise or an async iterator.

What I believe is happening, is that when we are building multiple projects (or perhaps, wherever the 'dependsOn' mechanic is applied) projects that depend on others wait for  a promise of the required task's completion.

However, in watch mode that promise never comes, because the process of the previous build never exits. This much has already been established.

What I'm curious to know is whether we can read the stdout of the previous commands. Maybe we identify some string that clearly indicates that the build completed, and it's now watching for changes. For example, the typescript compilere has a very clear message telling when it's finished compilation and is simply watching for changes. Now all we need to do is to use the async iterator mechanism, instead of a promise to emit build completion to the succeeding nrwl tasks.

**Comment by rodriguezjosetk** [comment]
Hi everyone!

Any news or fixes over this issue?

I'm facing the same problem, in development mode, I'm trying to serve my application but first, build its deps (libraries). Of course, in dev mode, I not only want to build those libs, I want to watch to changes, so their `build` script looks a bit like this:

```json
 "build": "rimraf dist && rollup --config --watch"
```

And my config for launching the app is:

```json
@nx.json

  "targetDefaults": {
    "dev": {
      "dependsOn": ["^build"]
    }
  }
```

Like @owen26  said in [this comment](https://github.com/nrwl/nx/issues/9125#issuecomment-1054283253), nx doesn't detect the process as finished (because simply it's not).

Which options do I have here? something to do with rollup maybe?

Thanks!
