### ISSUE TITLE
nx-plugin: The e2e executor  ignores dependsOn

### ISSUE THREAD

**Issue by DominikPieper** [nrwl/nx#9260]
## Current Behavior
We have several plugins in our workspace that dependsOn each other. We defined:
```
"dependsOn": [
        {
          "target": "build",
          "projects": "dependencies"
        }
      ]
```

to let them build all needed dependencies. That works finde with `nx build` but doesn't work in the e2e tests.

## Expected Behavior
If defined, all needed packages are built.

## Steps to Reproduce
Create two plugins  where one depend on each other and try to test it.

For reference: https://github.com/nxext/nx-extensions/tree/package-angular/e2e/angular-e2e

### Failure Logs
nx run angular-e2e:e2e

Some of the project angular-nx's dependencies have not been built yet. Please build these libraries before:
- angular-vite
- angular-swc
- vite

Try: nx run angular-nx:build --with-deps
Error
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/node/src/executors/package/package.impl.js:19:19
    at Generator.next (<anonymous>)
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/dominikpieper/Projects/angular/nxext/node_modules/tslib/tslib.js:113:16)
    at packageExecutor (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/node/src/executors/package/package.impl.js:13:34)
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/tao/src/commands/run.js:147:23
    at Generator.next (<anonymous>)
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)

### Environment
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.15

   nx : 13.8.3
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : 13.8.3
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.3
   @nrwl/nx-cloud : 13.1.5
   @nrwl/react : 13.8.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.8.3
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
   	 @angular-devkit/build-angular: 13.2.4
   	 @angular/compiler-cli: 13.2.1
   	 @angular/core: 13.2.3
   	 @angular/compiler: 13.2.1
   	 @nrwl/nx-plugin: 13.8.3
   	 @nx-plus/docusaurus: 12.2.0
   	 @nx-plus/vue: 12.2.0

**Comment by AgentEnder** [comment]
Hey, yeah this is correct. The reason behind this is that the executor internally is using runExecutor or similar instead of calling the target through Nx's CLI. This skips caching, task orchestration etc. It should be improved.

For now, I'd recommend adding `dependsOn: [{target: build, project: self}]` to the e2e target.

**Comment by DominikPieper** [comment]
Okay thanks, that's maybe a solution. I'll try.

**Comment by chiubaka** [comment]
The `dependsOn` solution is working well for me here, though I'm using `dependsOn: [{target: build, project: dependencies}]` and then listing the project that I'm trying to E2E test under `implicitDependencies`.

@AgentEnder It occurs to me, though: if all the `@nrwl/nx-plugin:e2e` executor is doing is creating a thin wrapper around the `@nrwl/jest:jest` executor but running the specified target first, so long as you can trigger running the specified target with a `dependsOn`, is `@nrwl/nx-plugin:e2e` really providing any value over `@nrwl/jest:jest`? I just tried switching to `@nrwl/jest:jest` and my Nx plugin E2E tests all work perfectly.

I don't have the full picture, but I'd argue it's actually less valuable, since `@nrwl/nx-plugin:e2e` doesn't allow passing important / useful options down to `jest` like `--testNamePattern` or `--runInBand` or `--ci`, which affect either convenience (I don't want to run my entire very slow E2E test suite if I'm just working on something mainly affecting one testing file) or correctness (sometimes extra options like these are required for CI). Some of these can be configured in `jest.config.ts`, but not all of them can, and sometimes I do want to run my E2E tests with some one-off arguments to test something out. (I have an open PR for this in #11442.)

**Comment by AgentEnder** [comment]
Hey @chiubaka! Yeah, the nx plugin e2e executor doesn't provide a ton of extra value, I agree. E2E in general for plugins is something that's on my list to revisit, its possible that the dependsOn setup should be preferred.

**Comment by chiubaka** [comment]
@AgentEnder In case it's helpful when you do revisit this, I've ended up creating a lot of my own tooling for plugin E2E, particularly around the use case of creating a custom preset generator. I factored out my testing utilities [here](https://github.com/chiubaka/genesis/tree/master/packages/nx-plugin-testing). More than happy to contribute parts of this back to Nx if generally useful.

Probably the biggest shift in my stuff vs the existing stuff is that my stuff supports multiple E2E testing suites potentially running simultaneously by creating separate E2E directories under `tmp` to run assertions over.

**Comment by DominikPieper** [comment]
@AgentEnder with just the Jest executor the tests run pretty fine. For e2e I added our own solution right now, which works a little like the e2e tests from the nrwl repo. We spin up a new workspace, deploy to and install from a local verdaccio instance. I created an executor from that, maybe that's worth as an alternative to the e2e executor
