### ISSUE TITLE
Recommendation to change Github Event Number to Head Ref for Pull Request Branches on the Nx Cloud

### ISSUE THREAD

**Issue by brandongallagher1999** [nrwl/nx#9267]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[Nx Cloud Docs](https://nx.app/docs/configuring-ci)

### Description

Under the NX Branch section of this page for GitHub Actions to set the source branch, the docs recommend you to do 
```
env:
  NX_BRANCH: ${{ github.event.number || github.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
```

However, after adding this to our our integration pipeline, the NX_BRANCH variable as reported on Nx Cloud is a pipeline number which is irrelevant to the developers / QAs. As a Dev / QA it is important to see what tests are passing or failing on **which branch.**

After investigation and some trial/error, I found that it was always better do directly reference the head ref as that is the source branch from which the tests/build/linting is happening.

I'd recommend changing that code snippet to reflect the source branch on Nx Cloud as such:
```
env:
  NX_BRANCH: ${{ github.head_ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
```

**Comment by StalkAltan** [comment]
Hi @brandongallagher1999 ! Thanks for reporting this. I've made the adjustment on our site, and I agree that in most cases it is more useful to know the branch name than PR number.

As an aside, I doubt that you need to manually specify these environment variables in your config, unless you are using a version of the cloud package that is more than a year old. We infer those values automatically from various CI providers, and currently default to the human-readable branch name for Github Actions. If you're having trouble with this, feel free to reach out to us directly at `cloud-support` @ `nrwl.io`.

Closing now since docs have been updated.
