### ISSUE TITLE
RegExp for builder webpack5 for storybook not recognized properly

### ISSUE THREAD

**Issue by creaux** [nrwl/nx#9290]
As soon as storybook configuration is structured by modules.

```
.
└── .storybook/
    ├── main.ts
    └── configuration/
        ├── index.ts
        └── core.config.ts
```

Where .storybook/configuration/core.config.ts could be like follows:

```
...
export const core: CoreConfig = { builder: 'webpack5' };
...
```

And .storybook/configuration/index.ts

```
import { core } from './core.config';
...
export const configuration: StorybookConfig = {
  core,
  ...
}

```

And .storybook/main.ts therefore:

```
import { configuration } from './configuration';

module.exports = configuration
```

The it doesn't work as following line is raw file reader and regexp.

https://github.com/nrwl/nx/blob/a32d46c5a36246b2349d72f7b50f7f0e532744bb/packages/storybook/src/executors/utils.ts#L117

Workaround is to put core property directly in `main.ts`. But I think it shiould work in better way.

**Comment by mandarini** [comment]
Hi there @creaux ! Thanks for filing an issue! I am going to mark this as an enhancement. Although I understand the issues that this may cause to your setup, I still believe it's sort of a niche use-case. We are relying on a regex to determine the `builder`, as this seems to be the most efficient way to do it, since the Storybook configuration uses that syntax (`builder: 'webpack5'`) to set the builder. We could potentially look at the imports into `main.ts` and then at the imports of the imports and so on, and look into every one of these files to see if there's a `builder: 'webpack5'`, but I think this would not be very efficient. With the Nx plugins we are trying to cover all the use cases, if that's possible, and where this is not possible, we are at least trying to cover most use cases. Since this has an easy workaround, and the workaround is actually the most common syntax, then I think it makes sense to leave it aside for the time being.

That said, if you come up with a better/more efficient way to do this, let me know, and I can help you implement this, as a contribution! :) Thank you, again, very much for submitting this issue! :)
