### ISSUE TITLE
Component Template Fails to Declare 'ViewEncapsulation'

### ISSUE THREAD

**Issue by colinskow** [nrwl/nx#93]
After creating new workspace and new app: `ERROR in apps/testapp/src/app/app.component.ts(7,18): error TS2304: Cannot find name 'ViewEncapsulation'.`

This is easily fixed by simply changing `import { Component, OnInit, ViewEncapsulation } from '@angular/core';` at the top of the file but needs to be fixed in the template.

**Comment by mikesmayer** [comment]
thanks -- i've encountered the same issue

**Comment by eaustin** [comment]
Appears to be an Angular CLI issue See [https://github.com/angular/angular-cli/issues/8374](https://github.com/angular/angular-cli/issues/8374)

**Comment by jschwarty** [comment]
The Nx schematics extend all the Angular schematics, which simply calls through to the code for those schematics. If there is an issue with any of those (component, service, pipe, etc) your best bet would be looking on the issues for the [Angular devkit](https://github.com/angular/devkit).

It looks like this is fixed in the latest version of the Angular schematics.
