### ISSUE TITLE
runExecutor fails running js:serve concurrently

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#9305]
## Current Behavior

Two `js:serve` executors should be able to run simultaneously, but only one ever runs at a time.

## Expected Behavior

Greater than one `js:serve` executor should be able to run simultaneously.

It's been broken for some time. It is discussed in https://github.com/nrwl/nx/pull/7110 some, and is still outstanding.

## Steps to Reproduce

- clone the PR below
- `yarn`
- `yarn nx baz foo`
  - observe that output from only one app is emitted, when output from _two_ apps is expected

https://github.com/nrwl/nx-examples/pull/193

More annotations exist in this PR for ease of understanding

### Environment

yarn run v1.22.17
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 17.1.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.8.1
   @nrwl/angular : 13.8.1
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : 13.8.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.2.2
   	 @angular/common: 13.2.2
   	 @angular/compiler: 13.2.2
   	 @angular/core: 13.2.2
   	 @angular/forms: 13.2.2
   	 @angular/platform-browser: 13.2.2
   	 @angular/platform-browser-dynamic: 13.2.2
   	 @angular/router: 13.2.2
   	 @ngrx/component-store: 13.0.1
   	 @ngrx/effects: 13.0.1
   	 @ngrx/entity: 13.0.1
   	 @ngrx/router-store: 13.0.1
   	 @ngrx/store: 13.0.1
   	 @angular-devkit/build-angular: 13.2.3
   	 @angular/cli: 13.2.3
   	 @angular/compiler-cli: 13.2.2
   	 @angular/language-service: 13.2.2
   	 @ngrx/store-devtools: 13.0.1

**Comment by cdaringe** [comment]
Hey all. I consider this kind of a fatal, big-deal kind of bug. Are other people simply _not_ running concurrent executors from the same process?

Anything I can do to help further?

**Comment by nartc** [comment]
@cdaringe Sorry for the late response. I am looking into this and already see a weird behavior with the child processes. 

I checked out your branch and upgraded everything to latest Nx + using the `nrwl/node:node` (since `nrwl/js: node` is removed from 13.9). The problem is still there and it's very funky. If you change the `dummy.ts`, then both processes start showing up. Then if you change it again, then the process that DIDN'T START at first GET STUCK! Each time the serve restarts because of file changed, the old process doesn't get cleaned up. 

At least, we know something's wrong with how the processes are being handled so there should be a solution soon.
