### ISSUE TITLE
Storybook does not work if staticDirs is defined from .storybook/main.js even though there is nothing defined about staticDir on project.json

### ISSUE THREAD

**Issue by iamrommel** [nrwl/nx#9306]
This happens on 13.8.6+ after this pull request merge (https://github.com/nrwl/nx/pull/8885#issuecomment-1065152060). I discussed also some details on pull request but i'm not sure if it will be fixed so I decided to put it here as i feel this is really an issue on the release.

## Current Behavior
There is an error on running storybook target, maybe the image below will explain more.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/177265/158015309-3973cacf-b624-4f43-9893-d3ff137db7db.png">

## Expected Behavior
-When there is nothing defined on project.json for staticDirs config, it should work fine (just like version 13.8.5 and below) and should follow what was defined on .storybook/main.json.
-When there is staticDirs on storybook config, and have it also on main.js, then should throw error
-When there is staticDirs on storybook config and nothing on main.js then it should work fine and use the staticDirs defined on project.json

## Steps to Reproduce
Just create a project with storybook, and on the .storybook/main.js add the staticDirs field. Do not add staticDirs on project.json storybook config

### Failure Logs
Check the image above

### Environment
iamrommel@Rommels-MacBook-Pro ztech-apps % nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.8.8
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.8
   @nrwl/cypress : 13.8.8
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.8
   @nrwl/eslint-plugin-nx : 13.8.8
   @nrwl/express : 13.8.8
   @nrwl/jest : 13.8.8
   @nrwl/js : 13.8.8
   @nrwl/linter : 13.8.8
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.8
   @nrwl/nx-cloud : 13.1.6
   @nrwl/react : 13.8.8
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.8
   @nrwl/tao : 13.8.8
   @nrwl/web : 13.8.8
   @nrwl/workspace : 13.8.8
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by marcinplatek** [comment]
I have the same issue

   Node : 17.6.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.8.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : 13.8.5
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.8
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.6.7

**Comment by mandarini** [comment]
Thanks people, I am on it! :)

**Comment by mandarini** [comment]
Hi all! Update:

1. I will push a fix soon
2. @iamrommel thank you for this. However, I think the expected behaviour you are describing is not exactly right. I was hasty to merge @leon 's [PR](https://github.com/nrwl/nx/pull/8885), since it seems to me they got it wrong. [Here is what Storybook says about `staticDir`](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag):
```
In 6.4 we've replaced the `--static-dir` CLI flag with the the `staticDirs` field in `.storybook/main.js`.
```

This does not mean that they RENAMED `staticDir` to `staticDirs`. This says that they are REMOVING the `staticDir` option from the CLI, and if anyone wants to provide a static dirs array, they should use the new `staticDirs` field inside `.storybook/main.js`. The `staticDir` CLI option will work until Storybook version 7, when it will not work any more.

So, the PR that leon submitted was wrong. There is NO renaming. The `staticDirs` option does not exist on the Storybook CLI. What we put inside `project.json` are the CLI parameters. 

So, to correct what you defined as expected behaviour, I think this is the correct:

* When the `staticDir` option **is not** provided in `project.json` or through the CLI, it should work fine and use `staticDirs` if it's provided in `.storybook/main.json`
* When the `staticDir` option **is** provided in `project.json` or through the CLI, and the user has also provided `staticDirs` in `.storybook/main.json`, then it should throw an error (Storybook's builder throws an error)
* In any other case, it should not work.

To be frank, I'm surprised it works on 13.8.5.. If `staticDirs` is provided in `main.js`, it should not work, because there's a flaw in our executor (which I am fixing now). The PR submitted by @leon may be wrong, however it does not affect at ALL the way our executor (and Storybook's builder) work.

**Comment by mandarini** [comment]
I'll probably (no promises here :P ) write a migrator to move the content of `statiDir` in `project.json` into `staticDirs` in `main.js`
