### ISSUE TITLE
Cannot read property 'includes' of undefined when configuring storybook for nx project

### ISSUE THREAD

**Issue by idoLumigo** [nrwl/nx#9549]
## Current Behavior
Getting this error after running `nx g @nrwl/angular:storybook-configuration --name=project-name`:

![Screen Shot 2022-03-27 at 18 07 03](https://user-images.githubusercontent.com/84006997/160287937-056880f9-79e2-43dc-a491-a564c932ff20.png)

## Expected Behavior
Config storybook for the project.

## Steps to Reproduce
Run `nx g @nrwl/angular:storybook-configuration --name=project-name`

### Failure Logs
Cannot read property 'includes' of undefined

### Environment

   Node : 14.18.3
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 13.8.4
   @nrwl/angular : 13.8.4
   @nrwl/cli : 13.8.4
   @nrwl/cypress : 13.8.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.4
   @nrwl/eslint-plugin-nx : 13.8.4
   @nrwl/express : undefined
   @nrwl/jest : 13.8.4
   @nrwl/js : undefined
   @nrwl/linter : 13.8.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.5
   @nrwl/tao : 13.8.4
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.4
   typescript : 4.5.5
   rxjs : 7.5.4

**Comment by mandarini** [comment]
Hi there @idoLumigo ! Thanks for filing an issue!

Can you please provide a reproduction repository? I just tried this with the latest version of Nx and it seems to be working fine on my end. Also, it may be possibly due to your node version (did not check, I don't know). Can you try using Node v.16? Again, I don't know if it's the node version to blame. So a reproduction repository would be most helpful! :)

**Comment by mandarini** [comment]
[This](https://github.com/nrwl/nx/pull/9561) solved this error

**Comment by marckassay** [comment]
@idoLumigo Is "project-name" the actual value for `name`?
