### ISSUE TITLE
Improve generators

### ISSUE THREAD

**Issue by mkurczewski** [nrwl/nx#9579]
## Description

I would like to use some of the already existing functions when creating a custom generator. It would be really nice to have them all exported and more customizable.

## Motivation

Sometimes custom generators are only a little modification of the original ones (for example editing only files templates) but this still requires to copy almost all the code from given generator instead of just importing some functions and using them out-of-the-box, with changed options.

## Suggested Implementation

For example, [in this generator](https://github.com/nrwl/nx/blob/master/packages/react-native/src/generators/component/component.ts), only the `reactNativeComponentGenerator` function is exported, so in order to create own react native component generator, I had to duplicate whole file and modify some lines.

If `createComponentFiles` and `addExportsToBarrel` would be exported too, creating a new generator would be much simpler as I could only import those functions and use them directly in my code.
However, for even better experience, I'd be also cool to have possibility to pass a custom `__dirname` to make it work with custom files templates (in this case `__dirname` will always point to the original ones from `node_modules/...`):

https://github.com/nrwl/nx/blob/6d52820d28c33064f72033848b93244d6abc30c2/packages/react-native/src/generators/component/component.ts#L34

This is only the example but I think it could be implemented in most of the generators.

**Comment by AgentEnder** [comment]
Hey @mkurczewski, generally in a generator file only the main generate function is exported. This is due to it being the only public api surface in the file. The other functions are generally written as an implementation detail or abstraction, and may be too narrow in use or not reusable enough for a public API. Additionally, that introduces more maintenance burden if the public api is split across packages.

In this specific case, for example, `addExportsToBarrels` may make sense as a method in @nrwl/devkit if it can be made re-usable enough.

I'm going to close this issue since it's really wide in scope, but if you want to create a few narrower issues to port some functionality to devkit we could take a look at them on a per-function basis. This would give a good place to discuss if its suitable. Thanks again!
