### ISSUE TITLE
@nwrl/js:tsc doesn't remove `tmp` folder

### ISSUE THREAD

**Issue by Viperwow** [nrwl/nx#9625]
## Current Behavior
When running `@nrwl/js:tsc` it creates `tmp` folder (building an NX plugin) and it doesn't remove it at the end

## Expected Behavior
Remove `tmp` folder

## Steps to Reproduce
Just run the command

### Environment
Node : 16.13.2
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.9.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.9.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 13.9.5
   @nrwl/react : 13.9.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.5
   @nrwl/web : 13.9.5
   @nrwl/workspace : 13.9.5
   typescript : 4.6.3
   rxjs : 6.6.7

**Comment by AgentEnder** [comment]
The @nrwl/js package can't entirely remove the tmp folder as it is used by other executors rather frequently (i.e., in the nx-plugin, the e2e setup locates there). While it's possible that we could check if the tmp folder is created or already exists, it can be helpful to debug by seeing what is in there.

Is there any reason you wish that it was cleaned up at the end rather than the .gitignore leaving it out of the repo?

**Comment by Viperwow** [comment]
It's called `tmp`, it's absolutely empty after running `@nrwl/tsc` ... so why should I store it? :)

Git ignoring is okay for intermediate results and automatic pipelines, but if you're developing infrastructure for developers you want to make your repo crystal clear
